// A Perfect Day — Tel Aviv, for The Drisco Hotel
// drisco_data_v1.js — the hotel, George & John, and 25 curated neighbourhood places
//
// v1 — June 2026
// Voice: boutique hotel concierge — warm, specific, walkable
// Categories: stay · dining · cafe · bar · culture · shop · wellness
// Neighbourhoods: colony · oldjaffa · fleamarket · nevetzedek · florentin · jaffaport
//
// Built by Ludara.AI as a sample for The Drisco Hotel (Relais & Châteaux).
// Place selection mirrors the hotel's own printed Tel Aviv Guide; descriptions
// rewritten in concierge voice. Coordinates are approximate, pending precise
// geocoding before any live deployment. No external claims beyond the hotel's
// own guide and publicly known facts.

const PLACES = [

  // ── THE AMERICAN-GERMAN COLONY ────────────────────────────────────────────
  {
    id: 1,
    nbhd: 'colony',
    name: 'The Drisco Hotel',
    cat: 'stay',
    emoji: '🏛️',
    address: 'Auerbach Street 6, Tel Aviv',
    lat: 32.056813, lng: 34.762712,
    search: 'The Drisco Hotel Tel Aviv heritage facade',
    note: 'Your home in Tel Aviv. A heritage landmark from 1866, the first hotel built outside the walls of Jerusalem, restored into a five-star member of Relais & Châteaux. Walk down from the lobby to the Mark Twain Salon, where hundred-year-old frescoes were uncovered during the restoration. Everything in this guide is a short walk from the front door.',
    tip: 'Ask reception about the complimentary daily tour of the hotel and the American-German Colony. It takes about 30 to 45 minutes and is the best possible introduction to the neighbourhood.',
    type: 'Heritage landmark hotel, established 1866',
    awards: 'Relais & Châteaux · MICHELIN Guide · TripAdvisor 4.9, #1 in Jaffa',
    website: 'https://thedrisco.com',
  },
  {
    id: 2,
    nbhd: 'colony',
    name: 'George & John',
    cat: 'dining',
    emoji: '🍽️',
    address: 'Auerbach Street 6, Tel Aviv (in the hotel)',
    lat: 32.056760, lng: 34.762680,
    search: 'George and John restaurant Tel Aviv Drisco',
    note: 'The restaurant at the heart of the hotel, a member of Relais & Châteaux, serving dishes inspired by modern Israel with broad Mediterranean influences. Named for the Drisco brothers who dreamed up Le Grand Hotel here over 150 years ago.',
    tip: 'Reserve before you arrive. Tables go quickly. The kitchen is at its best with the seasonal tasting menu.',
    type: 'Fine dining, modern Israeli and Mediterranean',
    awards: 'Top 10, MENA\'s 50 Best Restaurants (2022 to 2024) · Best restaurant in Israel, 50 Best',
    website: 'https://gandj.co.il/en/',
  },

  // ── OLD JAFFA ─────────────────────────────────────────────────────────────
  {
    id: 3,
    nbhd: 'oldjaffa',
    name: 'Adi Nissani',
    cat: 'shop',
    emoji: '🏺',
    address: "David Razi'el Street 7, Jaffa",
    lat: 32.056292, lng: 34.758153,
    search: 'Adi Nissani Jaffa ceramics studio tableware',
    note: 'A Jaffa-based ceramicist and designer making artisanal tableware and lifestyle objects. Each piece is designed, made and glazed by hand, with organic, classic shapes drawn from nature and ancient cultures. A lovely place to find a gift that was made a few streets away.',
    type: 'Ceramics and design studio',
  },
  {
    id: 7,
    nbhd: 'oldjaffa',
    name: 'Beit Kandinof',
    cat: 'dining',
    emoji: '🎨',
    address: 'HaTsorfim Street 14, Jaffa',
    lat: 32.053428, lng: 34.753446,
    search: 'Beit Kandinof Jaffa restaurant art gallery historic',
    note: 'Everything special about Jaffa under one roof: historic architecture, local Mediterranean food, and contemporary art in every corner. An eclectic eatery and gallery in a historic building, with a warm and lively vibe. Wander through the rooms during your meal to see the art.',
    type: 'Restaurant and art gallery',
  },
  {
    id: 11,
    nbhd: 'oldjaffa',
    name: 'Chelouche Gallery',
    cat: 'culture',
    emoji: '🖼️',
    address: "Mazal Te'omim Street 4, Jaffa",
    lat: 32.052724, lng: 34.752499,
    search: 'Chelouche Gallery Old Jaffa contemporary art',
    note: 'One of the most prominent art galleries in Israel, founded by Nira Itzhaki in 1985. It shows everything from video art and sculpture to painting, installation and photography, in an atmospheric space among the cobblestone streets of Old Jaffa.',
    type: 'Contemporary art gallery, established 1985',
  },
  {
    id: 16,
    nbhd: 'oldjaffa',
    name: 'Hilweh Market',
    cat: 'shop',
    emoji: '🧵',
    address: 'Yefet Street 32, Jaffa',
    lat: 32.053290, lng: 34.753944,
    search: 'Hilweh Market Jaffa Palestinian design textiles',
    note: 'A local artisanal store of handmade housewares, textiles and jewellery from Palestine and the wider Arab world. Each piece is handpicked by owner Adrieh Abu Shehadeh, who works with female artisans to showcase their craft and support young designers.',
    type: 'Artisan homeware and textiles',
  },
  {
    id: 19,
    nbhd: 'oldjaffa',
    name: 'Maskit',
    cat: 'shop',
    emoji: '👗',
    address: 'HaTsorfim Street 14, Jaffa',
    lat: 32.053470, lng: 34.753500,
    search: 'Maskit fashion house Jaffa Ruth Dayan Sharon Tal',
    note: 'Israel\'s storied fashion house, founded in 1954 by Ruth Dayan and revived by head designer Sharon Tal. The collections draw on traditional embroidery from local artisans, and the climate and history of Jaffa are felt in the natural, desert-toned materials.',
    type: 'Couture fashion house, founded 1954',
  },

  // ── FLEA MARKET & NOGA ────────────────────────────────────────────────────
  {
    id: 5,
    nbhd: 'fleamarket',
    name: 'Asufa',
    cat: 'shop',
    emoji: '🎨',
    address: 'Nakhman Street 2, Jaffa',
    lat: 32.053201, lng: 34.756044,
    search: 'Asufa Jaffa Israeli design store',
    note: 'A store and home for Israeli design, from design students to established names. As its Hebrew name suggests, Asufa is a collection: of products, of talent, of inspiration. The right place to find a gift for someone you love, or a small treat for yourself.',
    type: 'Israeli design store',
  },
  {
    id: 8,
    nbhd: 'fleamarket',
    name: 'Cafelix',
    cat: 'cafe',
    emoji: '☕',
    address: 'Sgula Street 13, Jaffa',
    lat: 32.056606, lng: 34.761130,
    search: 'Cafelix Jaffa artisan coffee roaster',
    note: 'A small artisan coffee roaster that takes the details seriously. Each batch is roasted with care for a clean, delicious brew. Stop in for an afternoon pick-me-up between the market stalls.',
    type: 'Artisan coffee roaster',
  },
  {
    id: 9,
    nbhd: 'fleamarket',
    name: 'Casino San Remo',
    cat: 'cafe',
    emoji: '🍳',
    address: 'Nehama Street 2, Jaffa',
    lat: 32.055853, lng: 34.760022,
    search: 'Casino San Remo Jaffa cafe Noga',
    note: 'A laid-back, artsy spot that captures the Jaffa mood: good food, music, drinks and eye-catching art. There are options for any time of day, from morning eggs and toast to evening pasta and fish.',
    type: 'All-day cafe',
  },
  {
    id: 17,
    nbhd: 'fleamarket',
    name: 'Jaffa Cinema',
    cat: 'culture',
    emoji: '🎬',
    address: 'Marzouk and Azar Street 14, Jaffa',
    lat: 32.0540, lng: 34.7575,
    search: 'Jaffa Cinema arthouse bar Israeli film',
    note: 'A cinema paired with a bar. Each month brings Israeli films with director Q&As, handpicked international screenings, and collaborations with major festivals. A complete evening out in an intimate, inspiring room.',
    type: 'Arthouse cinema and bar',
  },
  {
    id: 18,
    nbhd: 'fleamarket',
    name: 'Magasin III Jaffa',
    cat: 'culture',
    emoji: '🖼️',
    address: 'Olei Zion Street 34, Jaffa',
    lat: 32.051416, lng: 34.758351,
    search: 'Magasin III Jaffa contemporary art exhibition space',
    note: 'An exhibition space for contemporary art by international and local artists, set in a historic Jaffa building. Its architecture lets you view the exhibitions from outside, day and night. There is an art bookshop across the street.',
    type: 'Contemporary art space',
  },
  {
    id: 21,
    nbhd: 'fleamarket',
    name: 'Milk Bakery',
    cat: 'cafe',
    emoji: '🥐',
    address: 'Beit Eshel Street 5, Jaffa',
    lat: 32.054038, lng: 34.756806,
    search: 'Milk Bakery Jaffa French patisserie',
    note: 'A French patisserie tucked into the Jaffa streets, a little taste of Paris with every bite. Pause your wander through the flea market for a coffee and a pastry in the sun.',
    type: 'French patisserie',
  },
  {
    id: 22,
    nbhd: 'fleamarket',
    name: 'PUAA',
    cat: 'cafe',
    emoji: '🍽️',
    address: 'Rabbi Yohanan Street 8, Jaffa',
    lat: 32.052618, lng: 34.756154,
    search: 'Cafe Puaa Jaffa flea market vintage',
    note: 'A beloved spot in the winding flea-market streets where everything, from the food to the furniture, is handpicked. The menu plays with Middle Eastern flavours and a few surprises from further afield. Sit outside and soak up the local atmosphere.',
    type: 'All-day cafe and bistro',
  },
  {
    id: 24,
    nbhd: 'fleamarket',
    name: 'SAGA',
    cat: 'shop',
    emoji: '🪑',
    address: 'Rabi Pinkhas Street 4, Jaffa',
    lat: 32.052940, lng: 34.754709,
    search: 'Saga Jaffa design gallery Israeli',
    note: 'A design gallery and shop for art and home goods by promising local talent: product designers, ceramicists, glass artists, carpenters. Saga believes in pieces that carry a story. A must if you are looking for local design.',
    type: 'Design gallery and shop',
  },
  {
    id: 25,
    nbhd: 'fleamarket',
    name: 'Shaffa Bar',
    cat: 'bar',
    emoji: '🍺',
    address: 'Nakhman Street 2, Jaffa',
    lat: 32.053240, lng: 34.756090,
    search: 'Shaffa Bar Jaffa flea market street bar live music',
    note: 'A vibrant street bar and cafe in one of the main alleys off the flea market, minutes from the beach and the clock tower. The place to cool down with a cold drink after a day of wandering, often with live music in the evenings.',
    type: 'Street bar and cafe',
  },
  {
    id: 27,
    nbhd: 'fleamarket',
    name: 'Cantina San Remo',
    cat: 'bar',
    emoji: '🍷',
    address: 'Nehama Street 1, Jaffa',
    lat: 32.055900, lng: 34.760060,
    search: 'Cantina San Remo Jaffa wine bar Noga',
    note: 'A classic, cosy wine bar by the Gesher Theatre in the Noga quarter, from the owners of Casino San Remo across the street. Friendly and unpretentious, with small snacks, cheese boards and good wines.',
    type: 'Wine bar',
  },

  // ── NEVE TZEDEK ───────────────────────────────────────────────────────────
  {
    id: 14,
    nbhd: 'nevetzedek',
    name: 'Epicerie Fine',
    cat: 'cafe',
    emoji: '🧀',
    address: 'Shabazi Street 34, Tel Aviv',
    lat: 32.062445, lng: 34.765654,
    search: 'Epicerie Fine Neve Tzedek French deli cafe',
    note: 'A French cafe and delicatessen in the heart of Neve Tzedek: cheeses, baguettes, fresh breads and pastries at the entrance, a rustic seating area in the middle, and a small home-goods market at the back.',
    type: 'French cafe and deli',
  },
  {
    id: 15,
    nbhd: 'nevetzedek',
    name: 'Herzl 16',
    cat: 'bar',
    emoji: '🍸',
    address: 'Herzl Street 16, Tel Aviv',
    lat: 32.061845, lng: 34.770094,
    search: 'Herzl 16 Tel Aviv bar 1920s courtyard music',
    note: 'An iconic spot that is lively at all hours and a good place to meet Tel Avivians. International cuisine with a strong Asian influence, cocktails and wines, in an elegant 1920s building with an inner courtyard where musicians and DJs play.',
    type: 'Bar and kitchen',
  },
  {
    id: 20,
    nbhd: 'nevetzedek',
    name: 'Meshek Barzilay',
    cat: 'dining',
    emoji: '🌱',
    address: "Ahad Ha'Am Street 6, Tel Aviv",
    lat: 32.063314, lng: 34.768529,
    search: 'Meshek Barzilay Neve Tzedek vegan organic restaurant',
    note: 'A restaurant and deli of organic dishes so good you may forget they are vegan. One of the first places in the city to bring vegan cooking into the mainstream, on a pretty corner of Neve Tzedek, with a full sit-down menu and a deli for takeaway.',
    type: 'Organic and vegan restaurant',
  },

  // ── FLORENTIN ─────────────────────────────────────────────────────────────
  {
    id: 4,
    nbhd: 'florentin',
    name: 'Amita',
    cat: 'cafe',
    emoji: '🥐',
    address: 'Shalma Road 10, Jaffa',
    lat: 32.054520, lng: 34.762402,
    search: 'Amita patisserie Tel Aviv Jaffa pastry chefs',
    note: 'An up-and-coming patisserie from two gifted pastry chefs who joined talents to share their creations with the neighbourhood. European-inspired pastries made with local, seasonal ingredients, sweet and savoury, with something for everyone.',
    type: 'Patisserie and bakery',
  },
  {
    id: 6,
    nbhd: 'florentin',
    name: 'Beit Hanna Harabi',
    cat: 'wellness',
    emoji: '🧘',
    address: 'HaRabi MiBachrach Street 6, Tel Aviv',
    lat: 32.058138, lng: 34.766088,
    search: 'Beit Hanna Harabi Florentin wellness coworking cafe',
    note: 'A private community centre in eclectic Florentin with top-tier workout classes, a co-working space, a cafe, a restaurant and a bar. Yoga, a coffee, an evening drink or a high-intensity workout, all under one roof. Drop-in classes are available for short visits.',
    type: 'Wellness and community centre',
  },
  {
    id: 12,
    nbhd: 'florentin',
    name: 'Dalida',
    cat: 'dining',
    emoji: '🍷',
    address: 'Zevulun Street 7, Tel Aviv',
    lat: 32.059742, lng: 34.772862,
    search: 'Dalida Tel Aviv restaurant Arab Italian French courtyard',
    note: 'A meeting of East and West: a blend of Arab, Italian and French flavours, with a seasonal menu alongside the regular one. Come for a relaxed evening over a glass of wine, a romantic meal in the courtyard, or great food with friends.',
    type: 'Mediterranean restaurant',
  },
  {
    id: 13,
    nbhd: 'florentin',
    name: 'Edna House',
    cat: 'wellness',
    emoji: '🌿',
    address: 'Shalma Road 6, Jaffa',
    lat: 32.054560, lng: 34.762450,
    search: 'Edna House northern Jaffa wellness complex workshops',
    note: 'A beautiful wellness complex in northern Jaffa built around self-study and personal growth. Four studio spaces host yoga, arts and crafts, seminars and workshops, and there is a vegan cafe for a quick, healthy bite.',
    type: 'Wellness complex',
  },
  {
    id: 23,
    nbhd: 'florentin',
    name: 'Romano',
    cat: 'dining',
    emoji: '🎶',
    address: 'Jaffa Street 9, Tel Aviv',
    lat: 32.0605, lng: 34.7695,
    search: 'Romano Tel Aviv Eyal Shani Teder restaurant music',
    note: 'A magical urban gem where food and music meet, created by chef Eyal Shani with the Teder crew. Vintage furniture, classic vinyl and a custom sound system make a warm, enticing room around Shani\'s seasonal dishes.',
    type: 'Restaurant and music venue',
  },

  // ── JAFFA PORT & BEACH ────────────────────────────────────────────────────
  {
    id: 10,
    nbhd: 'jaffaport',
    name: 'Cassis',
    cat: 'dining',
    emoji: '🐟',
    address: 'Kidron Street 44, Jaffa',
    lat: 32.0490, lng: 34.7510,
    search: 'Cassis Givat Aliya beach Jaffa seafood Mediterranean',
    note: 'A seafront gem on Givat Aliya Beach: scenic ocean views, turquoise water and a seasonal menu of fresh fish and seafood straight from Jaffa. Breakfast, lunch and dinner, all changing with the season. A Mediterranean classic.',
    type: 'Seafood restaurant',
  },
  {
    id: 26,
    nbhd: 'jaffaport',
    name: 'Silvia Cafe',
    cat: 'cafe',
    emoji: '🌊',
    address: 'Retzif HaAliya HaShniya Street 1A, Jaffa',
    lat: 32.054804, lng: 34.752553,
    search: 'Silvia Cafe Jaffa port kiosk sea view coffee',
    note: 'An ocean-view kiosk minutes from the Jaffa port: delicious coffee and fresh pastries while you watch the waves. Outdoor seats face the sea, and it is one of the best places anywhere for a sunset, in any season.',
    type: 'Seaside coffee kiosk',
  },

];
