/*
  A Perfect Day in Plovdiv — curated sample for Hotel Evmolpia
  20 verified, currently-open places (English only)

  Suggested one-word image search term per place:
   1. Roman Theatre of Philippopolis .... amphitheatre
   2. Nebet Tepe ........................ fortress
   3. Regional Ethnographic Museum ...... mansion
   4. Balabanov House ................... house
   5. Ancient Stadium of Philippopolis .. stadium
   6. Dzhumaya Mosque ................... mosque
   7. Kapana Creative District ......... streetart
   8. Pavaj ............................. bistro
   9. Aylyakria ......................... gastrobar
  10. Philippopolis Restaurant-Garden ... garden
  11. Rahat Tepe ........................ tavern
  12. Smokini ........................... restaurant
  13. Hemingway ......................... grill
  14. Monkey House ...................... coffee
  15. Artnews Cafe ...................... cafe
  16. Dwell Coffee House ................ espresso
  17. Cat & Mouse ....................... beer
  18. Vino Culture ...................... wine
  19. Andromeda Art ..................... crafts
  20. SKLAD ............................. warehouse

  Note on coordinates: monuments and museums are verified to 4 decimals from
  Wikipedia/official sources. A few small venues (marked "approx" during
  research) are placed from their verified street address within the compact
  Old Town / Kapana blocks; fine-tune pins against Google Maps if needed.
*/

const PLACES = [
  {
    id: 1,
    nbhd: "oldtown",
    name: "Roman Theatre of Philippopolis",
    cat: "attraction",
    emoji: "🏛️",
    address: "Old Town, Plovdiv",
    lat: 42.1471,
    lng: 24.7512,
    search: "Roman Theatre of Philippopolis Plovdiv",
    note: "One of the best-preserved ancient Roman theatres in the world, built in the 1st century AD and still cradled in the saddle between two of the Old Town hills. From the marble tiers you look out over the city to the Rhodope Mountains beyond, and in the warmer months it comes alive again as a working stage for opera and concerts. It is a five-minute stroll uphill from the hotel and the single sight most guests remember.",
    hours: "Daily, approx 9:00-17:30 (longer in summer); check website",
    tip: "Come just before sunset, when the stone glows warm and the crowds thin out.",
    type: "Roman-era amphitheatre",
    blog: "",
    phone: "",
    website: "https://www.ancienttheaterplovdiv.eu/en/",
  },
  {
    id: 2,
    nbhd: "oldtown",
    name: "Nebet Tepe",
    cat: "attraction",
    emoji: "🏰",
    address: "Nebet Tepe, Old Town, Plovdiv",
    lat: 42.1512,
    lng: 24.7522,
    search: "Nebet Tepe Plovdiv ancient fortress",
    note: "This rocky summit is where Plovdiv began: a Thracian settlement stood here more than six thousand years ago, later fortified by the Macedonians, Romans and Byzantines. Today the weathered stone ramparts are an open-air site crowning the Old Town, and the panorama across the rooftops and hills is the finest in the city. Bring nothing but comfortable shoes and a little time.",
    tip: "It is the classic spot to watch the sunset over Plovdiv, so linger a while at the top.",
    hours: "Open-air site, freely accessible daily",
    type: "Ancient hilltop fortress ruins",
    blog: "",
    phone: "",
    website: "",
  },
  {
    id: 3,
    nbhd: "oldtown",
    name: "Regional Ethnographic Museum",
    cat: "attraction",
    emoji: "🏛️",
    address: "2 Dr. Stoyan Chomakov St, Old Town, Plovdiv",
    lat: 42.1500,
    lng: 24.7530,
    search: "Plovdiv Regional Ethnographic Museum Kuyumdzhieva House",
    note: "Housed in the striking 1847 Kuyumdzhioglu House, this is one of the most photographed buildings in the Old Town, its dark blue facade and undulating rooflines a masterpiece of Bulgarian Revival architecture. Inside, six rooms trace regional crafts, costumes, instruments and everyday life. The garden alone, with its roses and fountains, is worth the visit.",
    tip: "Step into the walled garden even if you are short on time, it is a quiet gem.",
    hours: "Tue-Sun approx 9:00-17:00 (later in summer); closed Mon",
    type: "Revival-era house museum",
    blog: "",
    phone: "+359 32 625 654",
    website: "https://ethnograph.info/en/",
  },
  {
    id: 4,
    nbhd: "oldtown",
    name: "Balabanov House",
    cat: "attraction",
    emoji: "🏠",
    address: "57 Konstantin Stoilov St, Old Town, Plovdiv",
    lat: 42.1497,
    lng: 24.7517,
    search: "Balabanov House Plovdiv Old Town",
    note: "A beautifully restored merchant's mansion from the Bulgarian Revival period, with symmetrical bay windows, painted ceilings and elegant reception rooms furnished in period style. Beyond the historic interiors it hosts art exhibitions, chamber concerts and readings throughout the year. It sits on the same lane as several other Old Town houses, making it easy to combine.",
    tip: "Check whether an evening concert is on during your stay, the acoustics are lovely.",
    hours: "Daily, approx 9:00-17:30; check locally",
    type: "Bulgarian Revival house museum",
    blog: "",
    phone: "",
    website: "https://oldplovdiv.bg/en/sights/2",
  },
  {
    id: 5,
    nbhd: "center",
    name: "Ancient Stadium of Philippopolis",
    cat: "attraction",
    emoji: "🏟️",
    address: "Dzhumaya Square, Plovdiv",
    lat: 42.1476,
    lng: 24.7480,
    search: "Ancient Stadium of Philippopolis Plovdiv",
    note: "Beneath the modern main street lie the marble tiers of a 2nd-century Roman stadium that once seated up to thirty thousand spectators for athletic games. The best-preserved northern curve is on full view at Dzhumaya Square, where you can stand at the edge and look down into antiquity. A small exhibition nearby tells the rest of the story.",
    tip: "The curved seating at Dzhumaya Square is free to admire at any hour.",
    hours: "Open-air view anytime; exhibition hours vary, check locally",
    type: "Ancient Roman stadium",
    blog: "",
    phone: "",
    website: "https://ancient-stadium-plovdiv.eu/",
  },
  {
    id: 6,
    nbhd: "center",
    name: "Dzhumaya Mosque",
    cat: "attraction",
    emoji: "🕌",
    address: "2 Zhelezarska St, Dzhumaya Square, Plovdiv",
    lat: 42.1479,
    lng: 24.7483,
    search: "Dzhumaya Mosque Plovdiv",
    note: "One of the oldest Ottoman mosques in the Balkans, dating from the 15th century, standing quietly at the head of the main street beside the Roman stadium. Its lead-domed roof, tall minaret and calligraphed interior are a reminder of the many cultures that have shaped Plovdiv. Visitors are welcome outside prayer times.",
    tip: "Dress modestly and remove your shoes; the little café beside it serves a fine traditional Turkish coffee.",
    hours: "Open daily outside prayer times",
    type: "15th-century Ottoman mosque",
    blog: "",
    phone: "",
    website: "",
  },
  {
    id: 7,
    nbhd: "kapana",
    name: "Kapana Creative District",
    cat: "attraction",
    emoji: "🎨",
    address: "Kapana Creative District, Plovdiv",
    lat: 42.1490,
    lng: 24.7490,
    search: "Kapana Creative District Plovdiv",
    note: "Once the city's old artisan quarter, this warren of narrow pedestrian lanes has become Plovdiv's creative heart, lined with galleries, studios, boutiques, cafés and bars. The name means 'the trap', for the way its little streets fold in on one another, and getting pleasantly lost is the whole point. Murals and street art turn nearly every corner into a photograph.",
    tip: "Wander without a map; the best finds here are the ones you stumble upon.",
    hours: "Streets open anytime; shops and bars keep their own hours",
    type: "Creative arts district",
    blog: "",
    phone: "",
    website: "https://visitkapana.bg/en/",
  },
  {
    id: 8,
    nbhd: "kapana",
    name: "Pavaj",
    cat: "dining",
    emoji: "🍽️",
    address: "7 Zlatarska St, Kapana, Plovdiv",
    lat: 42.1491,
    lng: 24.7488,
    search: "Pavaj restaurant Kapana Plovdiv",
    note: "A small, much-loved bistro in the middle of Kapana, serving modern takes on Bulgarian home cooking with local, seasonal ingredients. The interior is warm and eclectic, the terrace spills onto the cobbles, and it is consistently ranked among the city's very best tables. Booking ahead is wise, as it is popular with locals and visitors alike.",
    tip: "Reserve a day or two in advance, especially for a terrace table on a weekend.",
    hours: "Daily, approx 12:00-23:00",
    type: "Modern Bulgarian bistro",
    blog: "",
    phone: "+359 87 811 1876",
    website: "https://www.facebook.com/pavaj.plovdiv/",
  },
  {
    id: 9,
    nbhd: "kapana",
    name: "Aylyakria",
    cat: "dining",
    emoji: "🍽️",
    address: "3 Kozhuharska St, Kapana, Plovdiv",
    lat: 42.1493,
    lng: 24.7492,
    search: "Aylyakria gastro bar Kapana Plovdiv",
    note: "Set in a century-old building in Kapana, Aylyakria pairs traditional Plovdiv architecture with a relaxed, contemporary spirit, its very name a nod to 'aylyak', the local art of unhurried living. The kitchen blends Bulgarian classics with international touches, using craft local produce, and there is a thoughtful list of Bulgarian wines and craft beers. Choose the cosy interior or the terrace and take your time.",
    tip: "Ask the staff which Bulgarian wine they are pouring by the glass that week.",
    hours: "Check website",
    type: "Bulgarian gastro-bar",
    blog: "",
    phone: "+359 876 163 666",
    website: "https://aylyakria.com/en/",
  },
  {
    id: 10,
    nbhd: "oldtown",
    name: "Philippopolis Restaurant-Garden",
    cat: "dining",
    emoji: "🍽️",
    address: "29 Saborna St, Old Town, Plovdiv",
    lat: 42.1502,
    lng: 24.7513,
    search: "Philippopolis Restaurant Garden Plovdiv Saborna",
    note: "A refined restaurant and art gallery set in a restored 19th-century Old Town house, with a romantic garden that looks out over the Kapana rooftops. The setting is elegant and gently nostalgic, the wine list generous, and the whole place doubles as a home for a private Bulgarian art collection. It is a lovely choice for a special evening a short walk from the hotel.",
    tip: "Ask to be seated in the garden in fine weather, and leave time to see the gallery.",
    hours: "Check website",
    type: "Fine dining and art gallery",
    blog: "",
    phone: "+359 32 624 851",
    website: "https://www.philippopolis.com/en",
  },
  {
    id: 11,
    nbhd: "oldtown",
    name: "Rahat Tepe",
    cat: "dining",
    emoji: "🍽️",
    address: "18-20 Dr. Stoyan Chomakov St, Old Town, Plovdiv",
    lat: 42.1507,
    lng: 24.7524,
    search: "Rahat Tepe restaurant Plovdiv Old Town",
    note: "A long-standing Old Town tavern tucked at the foot of Nebet Tepe hill, known for hearty traditional Bulgarian cooking and a broad choice of beer. In summer the leafy garden spreads across many terraces under the trees, a welcome retreat from the heat. It is an easygoing, generous spot for a relaxed lunch or dinner.",
    tip: "The shaded summer garden is the place to be on a warm afternoon.",
    hours: "Daily, approx 9:00-24:00",
    type: "Traditional Bulgarian tavern",
    blog: "",
    phone: "+359 87 845 0259",
    website: "https://rahattepe.com/",
    resUrl: "https://apps.reservation.tools/form/iframe/index.html?businessId=f264cc128e25&locale=bg",
  },
  {
    id: 12,
    nbhd: "center",
    name: "Smokini",
    cat: "dining",
    emoji: "🍽️",
    address: "12 Otets Paisiy St, Plovdiv",
    lat: 42.1470,
    lng: 24.7489,
    search: "Smokini restaurant Plovdiv",
    note: "A city classic reborn, Smokini brings together traditional Bulgarian and modern European cooking in a cosy, welcoming room just off the main street. It is a reliable favourite among locals, consistently well reviewed, with attentive service and a comfortable terrace. A good all-rounder for lunch or dinner in the centre.",
    tip: "A short, easy walk from Dzhumaya Square; the terrace is pleasant in the evening.",
    hours: "Daily, approx 11:00-24:00",
    type: "Modern European and Bulgarian",
    blog: "",
    phone: "+359 999 000 996",
    website: "https://smokini.bg/en",
  },
  {
    id: 13,
    nbhd: "center",
    name: "Hemingway",
    cat: "dining",
    emoji: "🍽️",
    address: "10 General Gurko St, Plovdiv",
    lat: 42.1489,
    lng: 24.7499,
    search: "Hemingway restaurant Plovdiv Gurko",
    note: "A bohemian restaurant on a quiet street beside the Roman Odeon, with book-lined walls, soft music and a menu of contemporary European and Bulgarian dishes built around regional, often organic produce. Freshly baked bread and a considered wine selection round out an unhurried, romantic evening. It sits handily between the main street and the Old Town.",
    tip: "The peaceful setting by the Odeon makes it a fine choice for a slow dinner.",
    hours: "Check website",
    type: "Grill and wine restaurant",
    blog: "",
    phone: "+359 32 267350",
    website: "https://hemingway.bg/en/home/",
  },
  {
    id: 14,
    nbhd: "kapana",
    name: "Monkey House",
    cat: "cafe",
    emoji: "☕",
    address: "3 Zlatarska St, Kapana, Plovdiv",
    lat: 42.1490,
    lng: 24.7489,
    search: "Monkey House coffee Kapana Plovdiv",
    note: "A small specialty coffee bar in the heart of Kapana, beloved for carefully brewed espresso and filter coffee in a friendly, unpretentious setting. It is the kind of place where regulars linger and the barista remembers your order. A perfect pause between wandering the creative district's lanes.",
    tip: "Grab a coffee to go and enjoy it on the pedestrian street outside.",
    hours: "Check locally",
    type: "Specialty coffee bar",
    blog: "",
    phone: "+359 88 967 8333",
    website: "https://www.facebook.com/monkeyhousecafe",
  },
  {
    id: 15,
    nbhd: "center",
    name: "Artnews Cafe",
    cat: "cafe",
    emoji: "☕",
    address: "38 Otets Paisiy St, Plovdiv",
    lat: 42.1466,
    lng: 24.7492,
    search: "Artnews Cafe Plovdiv Otets Paisiy",
    note: "A cosy urban café on the colourful, pedestrian Otets Paisiy street, part of a small creative hub and a fixture of Plovdiv's cultural scene since 2008. Come for good coffee, drinks and a rotating programme of art and happenings. It has a quietly artistic, easy atmosphere that draws a loyal local crowd.",
    tip: "Sit at an outside table on Otets Paisiy for prime people-watching.",
    hours: "Check website",
    type: "Art café",
    blog: "",
    phone: "+359 88 852 0375",
    website: "https://artnewscafe.com/",
  },
  {
    id: 16,
    nbhd: "center",
    name: "Dwell Coffee House",
    cat: "cafe",
    emoji: "☕",
    address: "2 Prolet St, Plovdiv",
    lat: 42.1478,
    lng: 24.7487,
    search: "Dwell Coffee House Plovdiv",
    note: "A dedicated specialty coffee house on a side street just off the main pedestrian avenue, near the Roman Stadium. It serves freshly roasted coffee, from espresso to pour-over, alongside homemade cookies and fresh juices, with knowledgeable, welcoming staff. A calm, comfortable spot for a proper cup and a quiet moment.",
    tip: "Ask about the pour-over options if you like your coffee brewed by hand.",
    hours: "Check locally",
    type: "Specialty coffee house",
    blog: "",
    phone: "+359 89 961 7676",
    website: "https://www.facebook.com/dwell.coffee/",
  },
  {
    id: 17,
    nbhd: "kapana",
    name: "Cat & Mouse",
    cat: "bar",
    emoji: "🍺",
    address: "14 Hristo Dyukmedzhiev St, Kapana, Plovdiv",
    lat: 42.1496,
    lng: 24.7496,
    search: "Cat and Mouse craft beer bar Kapana Plovdiv",
    note: "Plovdiv's first craft beer bar and one of the most popular spots in Kapana, with a warmly designed room and a rotating range of well over a hundred Belgian, German, Czech, British, Serbian and Bulgarian beers. The mood is friendly and unhurried, equally good early evening or late. A must for anyone who enjoys a thoughtfully poured beer.",
    tip: "Not sure what to choose? The staff will happily steer you to something you will like.",
    hours: "Daily, approx 10:00-24:00",
    type: "Craft beer bar",
    blog: "",
    phone: "+359 878 313 995",
    website: "https://catandmouse.bg/",
  },
  {
    id: 18,
    nbhd: "center",
    name: "Vino Culture",
    cat: "bar",
    emoji: "🍷",
    address: "5 Otets Paisiy St, Plovdiv",
    lat: 42.1471,
    lng: 24.7490,
    search: "Vino Culture wine bar Plovdiv",
    note: "A small, eclectically designed wine bar just off the main street, a short step from the Roman Stadium and Dzhumaya Mosque. It focuses on Bulgarian wines, served with simple appetisers, and is an easy, characterful place to discover the region's cellars. The intimate setting makes it ideal for an early-evening glass.",
    tip: "The Thracian valley around Plovdiv is prime wine country, so ask for a local recommendation.",
    hours: "Check locally",
    type: "Wine bar",
    blog: "",
    phone: "+359 899 001 926",
    website: "https://www.facebook.com/vinocultureplovdiv/",
  },
  {
    id: 19,
    nbhd: "kapana",
    name: "Andromeda Art",
    cat: "craft",
    emoji: "🎨",
    address: "Kapana, Plovdiv",
    lat: 42.1487,
    lng: 24.7487,
    search: "Andromeda Art Plovdiv handmade gallery",
    note: "A gallery-shop of handmade work by Bulgarian artists, gathering jewellery, ceramics, glass, textiles and paintings under one roof. It is a lovely place to find a genuine, locally made keepsake rather than a mass-produced souvenir. A gentle browse here is a nice way to meet the city's craft tradition.",
    tip: "Ideal for a one-of-a-kind gift to take home; pieces are made by local makers.",
    hours: "Check locally",
    type: "Handmade art and gifts",
    blog: "",
    phone: "",
    website: "https://andromeda-art.com/en/",
  },
  {
    id: 20,
    nbhd: "kapana",
    name: "SKLAD",
    cat: "craft",
    emoji: "🎭",
    address: "Bratya Pulevi St, Plovdiv",
    lat: 42.1498,
    lng: 24.7478,
    search: "SKLAD creative space Plovdiv",
    note: "A multidisciplinary creative hub in a converted warehouse near Kapana, bringing together rotating art exhibitions, design studios, a record shop and a bar under one industrial roof. It captures the young, experimental energy that made Plovdiv a European Capital of Culture. Programming changes often, so it rewards a look at what is on.",
    tip: "Check what event or exhibition is running before you go, as the space shifts week to week.",
    hours: "Check locally; events typically Thu-Sun",
    type: "Creative warehouse hub",
    blog: "",
    phone: "",
    website: "https://www.instagram.com/sklad.bar/",
  },
  {
    id: 21,
    nbhd: "daytrip",
    name: "Bachkovo Monastery",
    cat: "attraction",
    emoji: "⛪",
    address: "Bachkovo village, about 30 km south of Plovdiv",
    lat: 41.9422,
    lng: 24.8494,
    search: "Bachkovo Monastery Bulgaria",
    note: "Founded in 1083, Bachkovo is the second-largest monastery in Bulgaria and one of the most loved. Set in a green Rhodope valley, its courtyards hold centuries of frescoes, a revered icon of the Virgin Mary, and a peaceful refectory. It is an easy and rewarding half-day trip from the city, and pairs naturally with Asen's Fortress nearby.",
    tip: "A 30 to 40 minute drive south. Dress modestly to enter the churches, and try to combine it with Asen's Fortress on the same outing.",
    hours: "Daily, roughly 7:00-20:00 in summer and to 19:00 in winter; check ahead on religious holidays.",
    type: "Historic monastery",
    blog: "",
    phone: "+359 879 151 818",
    website: "https://www.bachkovskimanastir.com/en/",
  },
  {
    id: 22,
    nbhd: "daytrip",
    name: "Asen's Fortress",
    cat: "attraction",
    emoji: "🏰",
    address: "Near Asenovgrad, about 19 km south of Plovdiv",
    lat: 41.9867,
    lng: 24.8733,
    search: "Asen's Fortress Asenovgrad Bulgaria",
    note: "A medieval fortress perched on a rocky ridge above the Asenitsa river, with sweeping views over the Rhodope foothills. Its jewel is the Church of the Holy Mother of God, a 12th to 13th century building that still carries 14th century murals. The short climb to the walls is part of the pleasure, and it sits just up the road from Bachkovo Monastery.",
    tip: "Wear comfortable shoes for the short uphill walk; the panorama is the reward. Easy to pair with Bachkovo Monastery on the same day.",
    hours: "Wednesday to Sunday, roughly 10:00-18:00 in the warmer months and to 17:00 in winter; closed Monday and Tuesday.",
    type: "Medieval fortress and church",
    blog: "",
    phone: "",
    website: "",
  },
];
