// A Perfect Day — The Curious Mexican / Mexico City
// data.js — 41 places curated from thecuriousmexican.com
//
// VERIFICATION KEY:
//   ✅ = Anais's exact words from thecuriousmexican.com (URL in blog: field)
//   ⚠️ = place name confirmed by Anais but no detailed article exists;
//         note is factual description only — not attributed as her words
//
// SOURCES:
//   [A] thecuriousmexican.com/favorite-spots-2024/
//   [B] thecuriousmexican.com/favorite-spots-2023/
//   [C] thecuriousmexican.com/favorite-spots-2022/
//   [D] thecuriousmexican.com/favs2019/
//   [E] thecuriousmexican.com/favs2018/
//   [F] thecuriousmexican.com/best-wine-bars-in-mexico-city/
//   [G] thecuriousmexican.com/where-to-get-mezcal-when-in-mexico-city/
//   [H] thecuriousmexican.com/mexico-citys-markets/
//
// NOTE ON LANDMARKS: Anais is a food writer. She has not published
// personal articles about the major historic sites. Their notes are
// factual descriptions only — not presented as her personal words.
//
// NOTE ON RIMESSA: The ANAIS discount code applies to Vinos Chidos,
// not Rimessa. It has been removed from this entry.

const PLACES = [

  // ─── CENTRO HISTÓRICO ─────────────────────────────────────────────────────

  {
    id: 1,
    nbhd: 'centro',
    name: 'Zócalo (Plaza de la Constitución)',
    cat: 'landmark',
    emoji: '🏛️',
    address: 'Plaza de la Constitución, Centro Histórico',
    lat: 19.4326,
    lng: -99.1332,
    search: 'Zócalo Plaza de la Constitución Mexico City',
    // ⚠️ Landmark — factual description only
    note: 'One of the largest city squares in the world and the historic heart of Mexico City. The Zócalo has been the center of power since the Aztec city of Tenochtitlán. Today it is surrounded by the Metropolitan Cathedral, the Palacio Nacional, and the ruins of the Templo Mayor.',
    hours: 'Open 24/7',
    tip: 'Arrive early on a weekday to see the square before the crowds gather.',
    type: 'Historic Main Plaza',
    blog: 'https://www.thecuriousmexican.com',
    phone: '',
    website: '',
  },

  {
    id: 2,
    nbhd: 'centro',
    name: 'Palacio Nacional — Diego Rivera Murals',
    cat: 'landmark',
    emoji: '🎨',
    address: 'Plaza de la Constitución s/n, Centro Histórico',
    lat: 19.4322,
    lng: -99.1297,
    search: 'Palacio Nacional Diego Rivera murals Mexico City',
    // ⚠️ Landmark — factual description only
    note: 'Diego Rivera spent 27 years painting the murals on the grand staircase of the National Palace. They depict a sweeping visual history of Mexico from the Aztecs to the revolution. Entry is free with ID.',
    hours: 'Tue–Sun 09:00–17:00',
    tip: 'Entry is free with ID. Photography is allowed.',
    type: 'National Palace & Art Museum',
    blog: 'https://www.thecuriousmexican.com',
    phone: '+52 55 3601 1000',
    website: 'https://www.gob.mx/palacionacional',
  },

  {
    id: 3,
    nbhd: 'centro',
    name: 'Palacio de Bellas Artes',
    cat: 'landmark',
    emoji: '🏛️',
    address: 'Av. Juárez s/n, Centro Histórico',
    lat: 19.4352,
    lng: -99.1407,
    search: 'Palacio de Bellas Artes Mexico City',
    // ⚠️ Landmark — factual description only
    note: 'A stunning Art Nouveau and Art Deco building that took 30 years to build. Inside are murals by Diego Rivera, José Clemente Orozco, and David Alfaro Siqueiros. The building hosts the Ballet Folklórico and major opera performances.',
    hours: 'Tue–Sun 10:00–18:00',
    tip: 'The permanent murals are free to see. Check the schedule for ballet and opera performances.',
    type: 'Arts Palace & Museum',
    blog: 'https://www.thecuriousmexican.com',
    phone: '+52 55 8647 6500',
    website: 'https://www.bellasartes.gob.mx',
  },

  {
    id: 4,
    nbhd: 'centro',
    name: 'Templo Mayor',
    cat: 'landmark',
    emoji: '🏺',
    address: 'Seminario 8, Centro Histórico',
    lat: 19.4353,
    lng: -99.1310,
    search: 'Templo Mayor Aztec ruins Mexico City',
    // ⚠️ Landmark — factual description only
    note: 'The great Aztec double temple at the heart of Tenochtitlán, demolished by the Spanish in 1521 and rediscovered by electrical workers in 1978. One of the most significant archaeological finds of the 20th century. The museum next door houses the stone disc of the moon goddess Coyolxauhqui.',
    hours: 'Tue–Sun 09:00–17:00',
    tip: 'Budget at least 2 hours for the ruins and the museum. Entry is around 90 MXN.',
    type: 'Aztec Archaeological Site',
    blog: 'https://www.thecuriousmexican.com',
    phone: '+52 55 4040 5600',
    website: 'https://www.templomayor.inah.gob.mx',
  },

  {
    id: 5,
    nbhd: 'centro',
    name: 'Bósforo',
    cat: 'cafe',
    emoji: '🥃',
    address: 'Luis Moya 31, Centro Histórico',
    lat: 19.4315,
    lng: -99.1449,
    search: 'Bósforo mezcal bar Centro Histórico Mexico City',
    // ✅ [A][B] exact — appears on every annual list
    note: 'A Mexico City staple in Centro Historico and still the best place to try different agave products from all over the country. Arrive early as it tends to be packed during the weekends.',
    hours: 'Mon–Sat 13:00–23:00',
    tip: 'Arrive early as it tends to be packed during the weekends.',
    type: 'Legendary Mezcal Bar',
    blog: 'https://www.thecuriousmexican.com/favorite-spots-2024/',
    phone: '',
    website: '',
  },

  {
    id: 6,
    nbhd: 'centro',
    name: 'El Huequito',
    cat: 'food',
    emoji: '🌮',
    address: 'Ayuntamiento 21, Centro Histórico',
    lat: 19.4294,
    lng: -99.1432,
    search: 'El Huequito tacos al pastor Centro Mexico City',
    // ⚠️ Place confirmed; no article with Anais's own description exists
    note: 'Tacos al pastor since 1959. The trompo of pastor spins in the window, shaved fresh onto handmade corn tortillas. One of the most consistent taco stops in Centro Histórico.',
    hours: 'Daily 09:00–00:00',
    tip: 'Multiple locations in the city. Stand at the street counter — that is the correct way. Cash only.',
    type: 'Tacos Al Pastor',
    blog: 'https://www.thecuriousmexican.com',
    phone: '',
    website: '',
  },

  {
    id: 7,
    nbhd: 'centro',
    name: 'La Lagunilla — Tianguis Dominical',
    cat: 'market',
    emoji: '🛍️',
    address: 'Comonfort & Rayón, La Lagunilla, Centro',
    lat: 19.4422,
    lng: -99.1286,
    search: 'La Lagunilla tianguis antiques flea market Mexico City',
    // ⚠️ [H] confirmed as one of Anais's featured markets; no detailed quote available
    note: 'One of the largest and most iconic Sunday tianguis in the city. Vendors sell vintage memorabilia, vinyl records, mid-century furniture, antiques, and street food. Open Sundays only.',
    hours: 'Sun 09:00–16:00',
    tip: 'Come before noon for the best selection. Stay aware of your belongings in the crowds.',
    type: 'Sunday Flea Market & Tianguis',
    blog: 'https://www.thecuriousmexican.com/mexico-citys-markets/',
    phone: '',
    website: '',
  },

  {
    id: 8,
    nbhd: 'centro',
    name: 'Cantina La Ópera',
    cat: 'cafe',
    emoji: '🍺',
    address: '5 de Mayo 10, Centro Histórico',
    lat: 19.4347,
    lng: -99.1390,
    search: 'Cantina La Opera Mexico City historic bar',
    // ⚠️ Confirmed CDMX institution; no article with Anais's own description
    note: 'One of the oldest cantinas in Mexico City, open since 1876. High ceilings, carved wooden booths, and Belle Époque décor. Classic cantina food: pozole, enchiladas, chile relleno. There is a bullet hole in the ceiling famously attributed to Pancho Villa.',
    hours: 'Mon–Sat 13:00–23:30; Sun 13:00–19:00',
    tip: 'Sit in one of the old wooden booths for the full historic atmosphere.',
    type: 'Historic Belle Époque Cantina',
    blog: 'https://www.thecuriousmexican.com',
    phone: '+52 55 5512 8959',
    website: '',
  },

  // ─── ROMA NORTE ───────────────────────────────────────────────────────────

  {
    id: 9,
    nbhd: 'roma',
    name: 'Licorería Limantour',
    cat: 'cafe',
    emoji: '🍹',
    address: 'Av. Álvaro Obregón 106, Roma Norte',
    lat: 19.4165,
    lng: -99.1633,
    search: 'Licorería Limantour cocktail bar Roma Norte Mexico City',
    // ✅ [D] exact
    note: 'The classic one. Avoid going to their brother spot in Polanco and just make your way down to Roma. Sit at the bar, talk to the tenders, have fun sipping on their extremely accurate suggestions.',
    hours: 'Mon–Thu 13:00–01:00; Fri–Sun 13:00–02:00',
    tip: 'Sit at the bar and let the bartenders guide you. Regularly placed in the World\'s 50 Best Bars.',
    type: 'World-Class Cocktail Bar',
    blog: 'https://www.thecuriousmexican.com/favs2019/',
    phone: '+52 55 5264 4122',
    website: 'https://www.limantour.tv',
  },

  {
    id: 10,
    nbhd: 'roma',
    name: 'Contramar',
    cat: 'food',
    emoji: '🐟',
    address: 'Calle de Durango 200, Roma Norte',
    lat: 19.4173,
    lng: -99.1670,
    search: 'Contramar seafood restaurant Roma Norte Mexico City',
    // ⚠️ Anais acknowledges it as a CDMX institution but intentionally doesn't write it up
    note: 'One of Mexico City\'s most iconic seafood restaurants. Famous for the tuna tostadas with chipotle mayo and avocado, and the red-and-green whole grilled fish. A CDMX institution you can find on every serious list — for good reason.',
    hours: 'Daily 13:00–19:00',
    tip: 'Reserve in advance — walk-ins during peak Sunday hours can wait over an hour.',
    type: 'Iconic Mexican Seafood',
    blog: 'https://www.thecuriousmexican.com',
    phone: '+52 55 5514 9217',
    website: 'https://contramar.com.mx',
  },

  {
    id: 11,
    nbhd: 'roma',
    name: 'Panadería Rosetta',
    cat: 'food',
    emoji: '🥐',
    address: 'Colima 166, Roma Norte',
    lat: 19.4174,
    lng: -99.1700,
    search: 'Panadería Rosetta bakery Roma Norte Mexico City',
    // ⚠️ Confirmed CDMX essential; no article with Anais's own description
    note: 'Chef Elena Reygadas\' bakery in Roma Norte. The guava roll (rollo de guayaba) — a warm, buttery spiral pastry with sweet-tart guava filling — sells out every morning. Coffee is excellent. One of the most visited bakeries in the city.',
    hours: 'Daily 07:30–19:00',
    tip: 'Go early — the guava rolls sell out. The full Rosetta restaurant is around the corner for evening dining.',
    type: 'Legendary Bakery & Café',
    blog: 'https://www.thecuriousmexican.com',
    phone: '+52 55 5533 7804',
    website: 'https://rosetta.com.mx',
  },

  {
    id: 12,
    nbhd: 'roma',
    name: 'Expendio de Maíz Sin Nombre',
    cat: 'food',
    emoji: '🫔',
    address: 'Av. Yucatán 84, Roma Norte',
    lat: 19.4162,
    lng: -99.1666,
    search: 'Expendio de Maíz Sin Nombre Michelin star Mexico City',
    // ✅ [A][B] exact
    note: 'Still at the head of my list, the ultimate Mexican Omakase: sit down, let them know food restrictions and be surprised by each dish that comes out of their beautiful, open kitchen. Remember they only take cash.',
    hours: 'Tue–Sun 12:00–18:00',
    tip: 'No menu, no reservations — arrive when they open to avoid the queue. Cash only.',
    type: 'Michelin-Starred Corn Kitchen',
    blog: 'https://www.thecuriousmexican.com/favorite-spots-2024/',
    phone: '',
    website: '',
  },

  {
    id: 13,
    nbhd: 'roma',
    name: 'La Clandestina',
    cat: 'cafe',
    emoji: '🥃',
    address: 'Av. Álvaro Obregón 298, Roma Norte',
    lat: 19.4134,
    lng: -99.1637,
    search: 'La Clandestina mezcal bar Roma Norte Mexico City',
    // ⚠️ Well-known mezcal bar; Anais has not published her own description
    note: 'One of the most established mezcal bars in Roma Norte, with a selection of around 40 artisanal mezcals from producers around the country. Knowledgeable staff, candlelit back rooms, and a menu of small plates to pair with your drinks.',
    hours: 'Mon–Sat 13:00–00:00',
    tip: 'Ask the staff for guidance through the mezcal list — they know every bottle and producer.',
    type: 'Mezcal Bar',
    blog: 'https://www.thecuriousmexican.com/where-to-get-mezcal-when-in-mexico-city/',
    phone: '+52 55 5264 2374',
    website: '',
  },

  {
    id: 14,
    nbhd: 'roma',
    name: 'Parque México',
    cat: 'nature',
    emoji: '🌳',
    address: 'Av. México & Sonora, Hipódromo Condesa',
    lat: 19.4121,
    lng: -99.1727,
    search: 'Parque México Condesa oval park Mexico City',
    // ⚠️ Landmark — factual description only
    note: 'A wide, tree-canopied oval park with Art Deco fountains and sculptures. Ringed by extraordinary Art Deco apartment buildings from the 1930s and 40s. Sunday mornings here are a highlight of the Condesa neighborhood.',
    hours: 'Open 24/7',
    tip: 'Walk the full oval on a Sunday morning with a coffee from a nearby café.',
    type: 'Art Deco Oval Park',
    blog: 'https://www.thecuriousmexican.com',
    phone: '',
    website: '',
  },

  {
    id: 15,
    nbhd: 'roma',
    name: 'Gin Chan',
    cat: 'food',
    emoji: '🍣',
    address: 'Tonalá 10, Roma Norte',
    lat: 19.4178,
    lng: -99.1680,
    search: 'Gin Chan sushi restaurant Roma Norte Mexico City',
    // ✅ [A] exact
    note: 'Often I\'m asked about the best sushi in town and for me this is it. Come sit at the bar to watch them work on your incredibly fresh food. The eel and foie nigiri is unmissable.',
    hours: 'Tue–Sun 13:30–22:30',
    tip: 'Sit at the counter bar — watching the chefs work is part of the experience. Reserve ahead for evenings.',
    type: 'Omakase Sushi Bar',
    blog: 'https://www.thecuriousmexican.com/favorite-spots-2024/',
    phone: '',
    website: '',
  },

  {
    id: 16,
    nbhd: 'roma',
    name: 'Entonces, Entonces',
    cat: 'food',
    emoji: '🍜',
    address: 'Tabasco 205, Roma Norte',
    lat: 19.4170,
    lng: -99.1660,
    search: 'Entonces entonces ramen restaurant Roma Norte Mexico City',
    // ⚠️ [A] confirmed on 2024 list; no detailed quote available
    note: 'A ramen restaurant in Roma Norte from the creators of Jametaro. Rich broths and a casual, warm setting. They also have an attached shop selling clothing and local design objects.',
    hours: 'Wed–Mon 13:00–21:30',
    tip: 'Go hungry. The classic tonkotsu ramen is the order.',
    type: 'Ramen Restaurant',
    blog: 'https://www.thecuriousmexican.com/favorite-spots-2024/',
    phone: '',
    website: '',
  },

  {
    id: 17,
    nbhd: 'roma',
    name: 'Canton Mexicalli',
    cat: 'food',
    emoji: '🥟',
    address: 'Álvaro Obregón 110, Roma Norte',
    lat: 19.4183,
    lng: -99.1640,
    search: 'Canton Mexicalli restaurant Roma Norte Mexico City Cachanilla',
    // ✅ [A] exact
    note: 'When Chinese immigrants were left out without a job after finishing railroads in the US, they ended up settling in Northern Mexico. They coined a new type of cuisine called Cachanilla, which is a mix of Chinese elements made with Mexican ingredients and techniques. This is the best spot in the city to get closer to this style of food.',
    hours: 'Tue–Sun 13:00–21:00',
    tip: 'Come with a group so you can order as much of the menu as possible.',
    type: 'Cachanilla Cuisine (Chinese-Mexican)',
    blog: 'https://www.thecuriousmexican.com/favorite-spots-2024/',
    phone: '',
    website: '',
  },

  {
    id: 18,
    nbhd: 'roma',
    name: 'Loup Bar',
    cat: 'cafe',
    emoji: '🍷',
    address: 'Sonora 180, Roma Norte',
    lat: 19.4175,
    lng: -99.1724,
    search: 'Loup Bar natural wine Roma Norte Mexico City',
    // ⚠️ [F] confirmed in her wine bars article; no direct quote available
    note: 'One of the first natural wine bars to open in Mexico City and still one of the best. A well-curated list of small-batch bottles from around Europe and Mexico. Good for a quiet evening of natural wine and small bites.',
    hours: 'Tue–Sun 14:00–00:00',
    tip: 'Trust the staff\'s recommendations — they know the list deeply.',
    type: 'Natural Wine Bar',
    blog: 'https://www.thecuriousmexican.com/best-wine-bars-in-mexico-city/',
    phone: '',
    website: '',
  },

  // ─── CONDESA ──────────────────────────────────────────────────────────────

  {
    id: 19,
    nbhd: 'condesa',
    name: 'Avenida Amsterdam',
    cat: 'nature',
    emoji: '🌿',
    address: 'Avenida Amsterdam, Hipódromo Condesa',
    lat: 19.4127,
    lng: -99.1743,
    search: 'Avenida Amsterdam Condesa oval boulevard Mexico City',
    // ⚠️ Landmark — factual description only
    note: 'A wide tree-lined boulevard that traces a complete oval around the old Hipódromo horse racing track. Ringed by Art Deco apartment buildings, boutique cafés, and street food vendors. One full circuit takes about 15 minutes.',
    hours: 'Open 24/7',
    tip: 'Start near Parque México and walk the full oval. The Art Deco apartment facades are worth photographing.',
    type: 'Art Deco Oval Boulevard',
    blog: 'https://www.thecuriousmexican.com',
    phone: '',
    website: '',
  },

  {
    id: 20,
    nbhd: 'condesa',
    name: 'Baltra Bar',
    cat: 'cafe',
    emoji: '🍸',
    address: 'Iztaccihuatl 36D, Condesa',
    lat: 19.4113,
    lng: -99.1762,
    search: 'Baltra Bar cocktails Condesa Mexico City',
    // ✅ [C] exact
    note: 'Limantour\'s little darker sister located in Condesa has the best Martini nights on Tuesdays and a very laid back, cozy vibe. Get here early as it tends to get really busy at nights.',
    hours: 'Wed–Mon 16:00–00:00',
    tip: 'Tuesday Martini nights are particularly popular. Get there early.',
    type: 'Creative Cocktail Bar',
    blog: 'https://www.thecuriousmexican.com/favorite-spots-2022/',
    phone: '+52 55 5211 1925',
    website: '',
  },

  {
    id: 21,
    nbhd: 'condesa',
    name: 'Choza',
    cat: 'food',
    emoji: '🍽️',
    address: 'Citlaltépetl 33, Condesa',
    lat: 19.4190,
    lng: -99.1793,
    search: 'Choza restaurant rooftop Condesa Mexico City Chef Tyler',
    // ✅ [C] exact
    note: 'Easily the one place I\'ve visited the most in the past year and a half. This hidden rooftop eatery is Chef Tyler\'s playground, where he gets to show off his wicked culinary skills (mostly inspired in Thai and Asian street food) with local, seasonal ingredients.',
    hours: 'Wed–Sun 14:00–22:00',
    tip: 'Reserve in advance — the space is intimate and fills quickly. No sign on the door; ring the bell.',
    type: 'Hidden Rooftop Restaurant',
    blog: 'https://www.thecuriousmexican.com/favorite-spots-2022/',
    phone: '',
    website: '',
  },

  {
    id: 22,
    nbhd: 'condesa',
    name: 'Máximo Bistrot',
    cat: 'food',
    emoji: '🥩',
    address: 'Av. Álvaro Obregón 65 Bis, Roma Norte',
    lat: 19.4162,
    lng: -99.1648,
    search: 'Máximo Bistrot farm-to-table Roma Norte Mexico City',
    // ✅ [E] exact
    note: 'By far my favorite fancy eat in the city, my favorite chef with the best, seasonal, locally sourced food. The love and care Eduardo García puts into every dish is completely noticeable.',
    hours: 'Tue–Sun 13:00–21:00',
    tip: 'Book in advance — consistently popular. Sunday brunch is a particularly special ritual.',
    type: 'Farm-to-Table Fine Dining',
    blog: 'https://www.thecuriousmexican.com/favs2018/',
    phone: '+52 55 5264 4291',
    website: 'https://www.maximobistrot.com.mx',
  },

  {
    id: 23,
    nbhd: 'condesa',
    name: 'Mari Gold',
    cat: 'food',
    emoji: '🌼',
    address: 'Jalisco 52, San Miguel Chapultepec',
    lat: 19.4180,
    lng: -99.1789,
    search: 'Mari Gold breakfast restaurant San Miguel Chapultepec Mexico City',
    // ✅ [A] exact
    note: 'I could\'ve easily written about Masala y Maíz, but the place is so good and so small that\'s quite hard to get a reso. But the next best thing, is just as good. Hidden away in San Miguel Chapultepec, this breakfast and lunch spot follows the same direction of combining Indian, African and Mexican techniques and ways of using ingredients. Please don\'t call it fusion.',
    hours: 'Wed–Sun 09:00–16:00',
    tip: 'Go for brunch on a weekday to avoid weekend queues.',
    type: 'Indian-African-Mexican Breakfast',
    blog: 'https://www.thecuriousmexican.com/favorite-spots-2024/',
    phone: '',
    website: '',
  },

  {
    id: 24,
    nbhd: 'condesa',
    name: 'Parque España',
    cat: 'nature',
    emoji: '🌲',
    address: 'Av. Sonora & Michoacán, Condesa',
    lat: 19.4152,
    lng: -99.1751,
    search: 'Parque España Condesa park Mexico City',
    // ⚠️ Landmark — factual description only
    note: 'The smaller, quieter park of Condesa. Giant ficus trees create an extraordinary canopy. Surrounded by beautiful houses and low-key café terraces. Where Condesa residents run, walk their dogs, and live out their daily routines.',
    hours: 'Open 24/7',
    tip: 'Walk between Parque España and Parque México — the route takes you through the heart of Condesa\'s best streets and architecture.',
    type: 'Neighborhood Park',
    blog: 'https://www.thecuriousmexican.com',
    phone: '',
    website: '',
  },

  // ─── POLANCO & CHAPULTEPEC ────────────────────────────────────────────────

  {
    id: 25,
    nbhd: 'polanco',
    name: 'Museo Nacional de Antropología',
    cat: 'landmark',
    emoji: '🏛️',
    address: 'Paseo de la Reforma s/n, Bosque de Chapultepec',
    lat: 19.4261,
    lng: -99.1860,
    search: 'Museo Nacional Antropología Mexico City',
    // ⚠️ Landmark — factual description only
    note: 'The greatest museum in Mexico, housing an extraordinary collection of pre-Hispanic art and artifacts from the Aztec, Maya, Olmec, Toltec, and Zapotec civilizations. The famous Aztec Sun Stone is here. Budget a full half-day minimum.',
    hours: 'Tue–Sun 09:00–19:00',
    tip: 'Buy your ticket online to skip the queue. Audio guides are available and worth it.',
    type: 'World-Class Archaeological Museum',
    blog: 'https://www.thecuriousmexican.com',
    phone: '+52 55 4040 5300',
    website: 'https://www.mna.inah.gob.mx',
  },

  {
    id: 26,
    nbhd: 'polanco',
    name: 'Bosque de Chapultepec',
    cat: 'nature',
    emoji: '🌳',
    address: 'Bosque de Chapultepec, Miguel Hidalgo',
    lat: 19.4196,
    lng: -99.1955,
    search: 'Bosque de Chapultepec park Mexico City',
    // ⚠️ Landmark — factual description only
    note: 'Over 680 hectares of urban forest in the middle of one of the world\'s largest cities. The park contains multiple museums, a castle, a zoo, and lakes. It has been a sacred site for over a thousand years. On Sunday mornings it is one of the most joyful places in Mexico City.',
    hours: 'Tue–Sun 05:00–16:30',
    tip: 'Weekday mornings are calm and ideal for museum visits. Rent a rowboat on the lake.',
    type: 'Urban Forest & Park',
    blog: 'https://www.thecuriousmexican.com',
    phone: '',
    website: '',
  },

  {
    id: 27,
    nbhd: 'polanco',
    name: 'Castillo de Chapultepec',
    cat: 'landmark',
    emoji: '🏰',
    address: 'Bosque de Chapultepec, Sección 1, Miguel Hidalgo',
    lat: 19.4202,
    lng: -99.1819,
    search: 'Castillo de Chapultepec castle Mexico City',
    // ⚠️ Landmark — factual description only
    note: 'Mexico\'s only royal castle, built on a hill in Chapultepec. Home to Emperor Maximilian and Empress Carlota in the 1860s, then served as the residence of presidents. The views of Mexico City from the terraces are among the best in the city.',
    hours: 'Tue–Sun 09:00–17:00',
    tip: 'The walk up the hill from the park entrance takes about 10 minutes. The terrace views and murals on Mexican history are the highlights.',
    type: 'Historic Royal Castle',
    blog: 'https://www.thecuriousmexican.com',
    phone: '+52 55 4040 5212',
    website: 'https://www.mnh.inah.gob.mx',
  },

  {
    id: 28,
    nbhd: 'polanco',
    name: 'Pujol',
    cat: 'food',
    emoji: '⭐',
    address: 'Tennyson 133, Polanco',
    lat: 19.4289,
    lng: -99.1942,
    search: 'Pujol restaurant Polanco Mexico City Enrique Olvera',
    // ⚠️ Anais acknowledges Pujol but intentionally excludes it from her lists
    note: 'Enrique Olvera\'s flagship restaurant, one of the most celebrated in the world and regularly on the World\'s 50 Best Restaurants list. The mole madre — a mole that has been cooking continuously since 2013 — is the centrepiece of the tasting menu. A Mexico City institution.',
    hours: 'Mon–Sat 13:30–22:00',
    tip: 'Book months in advance for the dining room. The taco bar omakase is a slightly more accessible entry point.',
    type: 'World-Class Mexican Fine Dining',
    blog: 'https://www.thecuriousmexican.com',
    phone: '+52 55 5545 4111',
    website: 'https://www.pujol.com.mx',
  },

  {
    id: 29,
    nbhd: 'polanco',
    name: 'Quintonil',
    cat: 'food',
    emoji: '🌿',
    address: 'Newton 55, Polanco',
    lat: 19.4279,
    lng: -99.2003,
    search: 'Quintonil restaurant Polanco Mexico City Jorge Vallejo',
    // ⚠️ Anais acknowledges Quintonil but intentionally excludes it from her lists
    note: 'Chef Jorge Vallejo\'s restaurant, deeply rooted in Mexican ingredients and techniques. Regularly in the World\'s 50 Best Restaurants. Known for revelatory vegetable dishes and precise use of Mexican insects. A landmark of contemporary Mexican haute cuisine.',
    hours: 'Mon–Sat 13:30–22:00',
    tip: 'Book well in advance. The tasting menu shows the full range of the kitchen.',
    type: 'Contemporary Mexican Fine Dining',
    blog: 'https://www.thecuriousmexican.com',
    phone: '+52 55 5280 1660',
    website: 'https://www.quintonil.com',
  },

  // ─── COYOACÁN ─────────────────────────────────────────────────────────────

  {
    id: 30,
    nbhd: 'coyoacan',
    name: 'Museo Frida Kahlo — Casa Azul',
    cat: 'landmark',
    emoji: '🎨',
    address: 'Londres 247, Del Carmen, Coyoacán',
    lat: 19.3556,
    lng: -99.1628,
    search: 'Museo Frida Kahlo Casa Azul Coyoacán Mexico City',
    // ⚠️ Landmark — factual description only
    note: 'The cobalt-blue house where Frida Kahlo was born, spent most of her life, and died. Her personal belongings, clothing, corsets, medicines, and studio are preserved as she left them. One of the most visited museums in Mexico.',
    hours: 'Tue–Sun 10:00–17:30; Sat 10:00–19:30',
    tip: 'Book online in advance — it sells out completely on weekends. Tuesday or Wednesday mornings are the calmest.',
    type: 'Art Museum & Historic House',
    blog: 'https://www.thecuriousmexican.com',
    phone: '+52 55 5554 5999',
    website: 'https://www.museofridakahlo.org.mx',
  },

  {
    id: 31,
    nbhd: 'coyoacan',
    name: 'Jardín Centenario & Jardín Hidalgo',
    cat: 'landmark',
    emoji: '🌺',
    address: 'Plaza Hidalgo, Coyoacán',
    lat: 19.3516,
    lng: -99.1625,
    search: 'Jardín Centenario Coyoacán plaza Mexico City',
    // ⚠️ Landmark — factual description only
    note: 'Two connected plazas at the heart of Coyoacán, lined with restaurants and cafés under flowering trees. This bohemian neighborhood still has the unhurried character of Frida Kahlo\'s era. A beautiful place for a long Sunday afternoon.',
    hours: 'Open 24/7',
    tip: 'Weekends are lively but busy. Tuesday or Wednesday gives a calmer experience.',
    type: 'Historic Colonial Plazas',
    blog: 'https://www.thecuriousmexican.com',
    phone: '',
    website: '',
  },

  {
    id: 32,
    nbhd: 'coyoacan',
    name: 'Mercado de Coyoacán',
    cat: 'market',
    emoji: '🛒',
    address: 'Ignacio Allende 21, Del Carmen, Coyoacán',
    lat: 19.3505,
    lng: -99.1606,
    search: 'Mercado de Coyoacán market Mexico City',
    // ⚠️ [H] confirmed as one of Anais's featured markets; no detailed quote
    note: 'A bright, colorful covered market — one of the best in the city for visitors. Famous tostada vendors, a remarkable chile section, and artisan shops lining the surrounding streets. The third essential stop in a Coyoacán day after Frida\'s house and the plazas.',
    hours: 'Daily 09:00–19:00',
    tip: 'Start with the tostadas toward the back — tostadas de tinga, de ceviche, de pata.',
    type: 'Traditional Covered Market',
    blog: 'https://www.thecuriousmexican.com/mexico-citys-markets/',
    phone: '',
    website: '',
  },

  {
    id: 33,
    nbhd: 'coyoacan',
    name: 'El Jarocho — Café de Olla',
    cat: 'cafe',
    emoji: '☕',
    address: 'Cuauhtémoc 134, Del Carmen, Coyoacán',
    lat: 19.3496,
    lng: -99.1614,
    search: 'El Jarocho café olla Coyoacán Mexico City coffee',
    // ⚠️ Coyoacán institution; no article with Anais's own description
    note: 'A Coyoacán institution since 1953. Coffee brewed in a clay pot with cinnamon and piloncillo, handed through a small window in a paper cup. A couple of musicians in the corner, the smell of wood burning, and the taste of sweet café de olla — an absolute Mexico City staple.',
    hours: 'Daily 06:00–23:00',
    tip: 'Order the café de olla — brewed with cinnamon and piloncillo. Walk with your cup to the Jardín Centenario next door.',
    type: 'Historic Café de Olla Stand',
    blog: 'https://www.thecuriousmexican.com',
    phone: '',
    website: '',
  },

  {
    id: 34,
    nbhd: 'coyoacan',
    name: 'Xochimilco — Trajineras',
    cat: 'nature',
    emoji: '🚣',
    address: 'Embarcadero Fernando Celada, Xochimilco',
    lat: 19.2636,
    lng: -99.1050,
    search: 'Xochimilco trajineras floating gardens Mexico City',
    // ⚠️ Landmark — factual description only
    note: 'What remains of the ancient system of canals and floating gardens (chinampas) that fed the Aztec empire. Renting a trajinera and floating through the canals is one of the most uniquely Mexican experiences in this city. Other boats come alongside selling food, flowers, and music.',
    hours: 'Daily 09:00–18:00',
    tip: 'Sunday is the most vibrant day. Consider a guided tour to navigate the most interesting sections of the canal.',
    type: 'Ancient Chinampas Canal System',
    blog: 'https://www.thecuriousmexican.com',
    phone: '',
    website: '',
  },

  // ─── JUÁREZ & SAN RAFAEL ──────────────────────────────────────────────────

  {
    id: 35,
    nbhd: 'juarez',
    name: 'Handshake Speakeasy',
    cat: 'cafe',
    emoji: '🕵️',
    address: 'Amberes 55, Juárez',
    lat: 19.4194,
    lng: -99.1540,
    search: 'Handshake Speakeasy cocktail bar Juárez Mexico City',
    // ⚠️ Named World\'s Best Bar 2024; no article with Anais\'s own description
    note: 'Named World\'s Best Bar by 50 Best in 2024. A hidden speakeasy in Juárez with one of the most inventive cocktail menus in the city. The space is small — book ahead and skip coming with a large group.',
    hours: 'Tue–Sun 18:00–23:00',
    tip: 'Book ahead — the wait at the door without a reservation can be significant.',
    type: 'Creative Speakeasy Cocktail Bar',
    blog: 'https://www.thecuriousmexican.com',
    phone: '',
    website: '',
  },

  {
    id: 36,
    nbhd: 'juarez',
    name: 'El Califa de León',
    cat: 'food',
    emoji: '🌮',
    address: 'Ribera de San Cosme 56, Santa María La Ribera',
    lat: 19.4397,
    lng: -99.1626,
    search: 'El Califa de León Michelin star taco Mexico City',
    // ⚠️ First Michelin-starred taco in Mexico; no article with Anais's own description
    note: 'In 2024 this became the first taco stand in Mexico to receive a Michelin star — operating from the same 10x10 foot counter since 1968. The menu is four things: Gaonera (filet mignon), bistec, chuleta, and costilla. You stand to eat. You pay in cash.',
    hours: 'Mon–Sat 10:00–15:00',
    tip: 'Arrive early — it sells out and the post-Michelin lines are significant. Cash only. Order the Gaonera.',
    type: 'Michelin-Starred Taquería',
    blog: 'https://www.thecuriousmexican.com',
    phone: '',
    website: '',
  },

  {
    id: 37,
    nbhd: 'juarez',
    name: 'Mariscos Orizaba',
    cat: 'food',
    emoji: '🦐',
    address: 'Liverpool 75, Juárez',
    lat: 19.4265,
    lng: -99.1537,
    search: 'Mariscos Orizaba seafood tostadas Juárez Mexico City',
    // ✅ [A] exact
    note: 'A tin stand on Liverpool street with incredibly good tostadas (and seafood dishes in general). Veracruz style dishes are served from 11am to sometime around 6pm. Their seafood tostadas are one of the best stops on our Juarez Highlights.',
    hours: 'Mon–Sat 11:00–18:00',
    tip: 'Order the mixed seafood tostada. A quick, standing meal — come hungry.',
    type: 'Seafood Tostada Stand',
    blog: 'https://www.thecuriousmexican.com/favorite-spots-2024/',
    phone: '',
    website: '',
  },

  {
    id: 38,
    nbhd: 'juarez',
    name: 'Mixiote Tacos',
    cat: 'food',
    emoji: '🌮',
    address: 'Havre 66, Juárez',
    lat: 19.4256,
    lng: -99.1562,
    search: 'Mixiote tacos street stand Juárez Mexico City',
    // ✅ [A] exact
    note: 'Been there since 1986 and still going strong. This street stand is only open Wednesday, Friday and Saturday and it\'s a must when visiting Juarez neighborhood.',
    hours: 'Wed 10:00–16:00; Fri 10:00–16:00; Sat 10:00–16:00',
    tip: 'Only open three days a week — plan your schedule around it. Arrive early because it sells out.',
    type: 'Traditional Mixiote Tacos',
    blog: 'https://www.thecuriousmexican.com/favorite-spots-2024/',
    phone: '',
    website: '',
  },

  {
    id: 39,
    nbhd: 'juarez',
    name: 'Rimessa',
    cat: 'cafe',
    emoji: '🍷',
    address: 'Amsterdam 26, Hipódromo',
    lat: 19.4216,
    lng: -99.1600,
    search: 'Rimessa natural wine shop Roma Mexico City',
    // ✅ [F] exact — note: the ANAIS discount code is for Vinos Chidos, not Rimessa
    note: 'One of the most important Natural Wine suppliers in Mexico decided to finally open a shop in Mexico City. Rimessa is a cool little shop with bottles from all around the world and a small selection of Mexican options. Stay tuned to their socials since they have tons of tastings and pop-ups with different chefs.',
    hours: 'Mon–Sat 12:00–21:00',
    tip: 'Ask the staff to help you choose. The shop hosts regular pop-up events with visiting chefs.',
    type: 'Natural Wine Shop',
    blog: 'https://www.thecuriousmexican.com/best-wine-bars-in-mexico-city/',
    phone: '',
    website: '',
  },

  {
    id: 40,
    nbhd: 'juarez',
    name: 'Xaman Bar',
    cat: 'cafe',
    emoji: '🔮',
    address: 'Amberes 32, Juárez',
    lat: 19.4236,
    lng: -99.1532,
    search: 'Xaman Bar speakeasy cocktail Juárez Mexico City',
    // ✅ [D] exact
    note: 'A little bit of a hidden location. The whole concept will make you feel like you\'re entering a world of mysticism and magic. The drinks are also made with ingredients such as roots, flowers and other great spices. They have huge drinks made to share with your companion.',
    hours: 'Tue–Sun 18:00–23:00',
    tip: 'Check Google Maps — the entrance can be easy to walk past.',
    type: 'Bohemian Cocktail Speakeasy',
    blog: 'https://www.thecuriousmexican.com/favs2019/',
    phone: '',
    website: '',
  },

  {
    id: 41,
    nbhd: 'juarez',
    name: 'Mercado Jamaica',
    cat: 'market',
    emoji: '🌸',
    address: 'Av. Congreso de la Unión 74, Jamaica',
    lat: 19.4095,
    lng: -99.1255,
    search: 'Mercado Jamaica flower market Mexico City',
    // ⚠️ [H] confirmed as one of Anais's featured markets; no detailed quote
    note: 'The largest flower market in Mexico. Over 5,000 varieties of flowers sold every single day. A central hub for Día de Muertos preparations each November. The food court has excellent breakfasts. Come before 9am when the flower wholesalers are most active.',
    hours: 'Open 24/7',
    tip: 'Come before 9am when the market is at its most extraordinary. The marigold sections in October–November are unmissable.',
    type: 'Wholesale Flower Market',
    blog: 'https://www.thecuriousmexican.com/mexico-citys-markets/',
    phone: '',
    website: '',
  },

];
