// A Perfect Day — Drizzle & Dip / Cape Town
// data.js — 43 hand-picked places by Sam Linsell
//
// ⚠️  ALL notes are Sam's actual words from drizzleanddip.com
//     Sourced directly from:
//     https://drizzleanddip.com/2017/06/29/my-guide-to-eating-out-in-cape-town/
//     and individual restaurant review posts linked in the blog field.
//     Nothing has been invented or paraphrased beyond light trimming for length.

const PLACES = [

  // ─── CITY, GREEN POINT & WOODSTOCK ───────────────────────────────────────

  {
    id: 1,
    nbhd: 'city',
    name: 'Amura by Ángel León',
    cat: 'landmark',
    emoji: '🌊',
    address: 'Mount Nelson Hotel, 76 Orange Street, Gardens',
    lat: -33.9298,
    lng: 18.4133,
    search: 'Amura Angel Leon Mount Nelson Cape Town',
    note: "Amura marks three-Michelin-starred chef Ángel León's first restaurant outside Spain, and it is one of the most significant openings Cape Town's dining scene has seen in years. The electric green plankton risotto, made with sustainably farmed phytoplankton, is one of the most unique dishes I have tasted. Langoustines are cooked tableside using a living salt technique that forms crystals across the shellfish before your eyes. Don't miss the chocolate florentines made with caramelised fish scales. Mind-bending and delicious.",
    hours: 'Check website for current hours',
    tip: 'This is not a restaurant for every week, but for a special occasion or a guest you want to impress, Amura delivers something profound. Book is strongly advised.',
    type: 'Fine Dining',
    blog: 'https://drizzleanddip.com/2025/12/12/amura-by-angel-leon-a-marine-love-letter-from-cadiz-to-cape-town/',
    phone: '',
    website: 'https://belmond.com/hotels/africa/south-africa/cape-town/belmond-mount-nelson-hotel/dining/amura/',
  },

  {
    id: 2,
    nbhd: 'city',
    name: 'Fyn',
    cat: 'landmark',
    emoji: '🍽️',
    address: 'Parliament Square, 37 Parliament Street, CBD',
    lat: -33.9276,
    lng: 18.4225,
    search: 'Fyn restaurant Cape Town Parliament Street',
    note: "This is an edgy contemporary fine-dining restaurant in the city centre, amongst Cape Town's best. Headed up by renowned chef Peter Tempelhoff, it is a refined and exciting dining adventure.",
    hours: 'Tue–Sat dinner',
    tip: 'Ramenhead, Peter Tempelhoff\'s ramen venture, is situated just below — a more casual option from the same kitchen.',
    type: 'Fine Dining',
    blog: 'https://drizzleanddip.com/2021/09/29/visit-fyn-restaurant-in-cape-town/',
    phone: '',
    website: 'https://fynrestaurant.com',
  },

  {
    id: 3,
    nbhd: 'city',
    name: 'Salon Pot Luck',
    cat: 'landmark',
    emoji: '⭐',
    address: 'The Biscuit Mill, 373–375 Albert Road, Woodstock',
    lat: -33.9291,
    lng: 18.4448,
    search: 'Salon Pot Luck Cape Town Biscuit Mill',
    note: "Luke Dale Roberts' latest fine dining tasting menu restaurant at the Biscuit Mill in Woodstock. I adore this cosy, intimate restaurant. I recently sampled their Winter 2025 Explorer menu, and it was outstanding, ranking among the top 3 fine-dining meals I enjoyed in 2025. Carla Schulze is raking in awards and is one of South Africa's best chefs.",
    hours: 'Check website for current hours',
    tip: 'Located below the Pot Luck Club at the Biscuit Mill.',
    type: 'Fine Dining',
    blog: 'https://drizzleanddip.com/2023/04/03/salon-pot-luck-opens-in-cape-town/',
    phone: '',
    website: 'https://thepotluckclub.co.za',
  },

  {
    id: 4,
    nbhd: 'city',
    name: 'Pier',
    cat: 'landmark',
    emoji: '🦞',
    address: 'Pierhead Building, V&A Waterfront',
    lat: -33.9060,
    lng: 18.4215,
    search: 'Pier restaurant V&A Waterfront Cape Town',
    note: "Pier is one of my favourite restaurants in South Africa and the best fine dining experience at the V&A Waterfront. Situated on the first floor of the Pierhead Building with floor-to-ceiling windows overlooking the working harbour. The service is impeccable, warm and knowledgeable without being stiff. The meal ends with a treasure chest of handmade chocolates. The cheesecourse is also very memorable and worth experiencing.",
    hours: 'Check website for current hours',
    tip: 'The cheesecourse is very memorable and worth experiencing.',
    type: 'Fine Dining',
    blog: 'https://drizzleanddip.com/2023/07/03/lunch-at-pier-at-the-v-a-waterfront-in-cape-town/',
    phone: '',
    website: '',
  },

  {
    id: 5,
    nbhd: 'city',
    name: 'COY',
    cat: 'landmark',
    emoji: '🎯',
    address: 'Bascule Bridge, V&A Waterfront',
    lat: -33.9055,
    lng: 18.4225,
    search: 'COY restaurant V&A Waterfront Cape Town Ryan Cole',
    note: "COY sits in a standalone building beside the Bascule Bridge, with the working harbour on one side, luxury yachts on the other, and Table Mountain filling the backdrop. The cooking is rooted in Southern African ingredients and African culinary traditions, with spice, heat, and real personality in everything.",
    hours: 'Mon–Sun from noon',
    tip: 'Available Monday to Sunday from noon. Bookings essential.',
    type: 'Fine Dining',
    blog: '',
    phone: '',
    website: 'https://coyrestaurant.com',
  },

  {
    id: 6,
    nbhd: 'city',
    name: 'Ouzeri',
    cat: 'food',
    emoji: '🫒',
    address: 'Wale Street, Cape Town CBD',
    lat: -33.9238,
    lng: 18.4148,
    search: 'Ouzeri Cypriot Greek restaurant Cape Town Wale Street',
    note: "Ouzeri is a trendy eatery on Cape Town's Wale Street, known for its contemporary Cypriot and Greek cuisine, and it's one of my absolute faves. Chef Nic Charalambous draws from his Cypriot and Greek heritage, family recipes, and culinary traditions to create a modern interpretation and incorporate carefully sourced South African produce.",
    hours: 'Check website for current hours',
    tip: 'Book ahead — it gets busy.',
    type: 'Cypriot-Greek Restaurant',
    blog: 'https://drizzleanddip.com/2023/11/07/ouzeri-a-cypriot-greek-restaurant-in-cape-town/',
    phone: '',
    website: '',
  },

  {
    id: 7,
    nbhd: 'city',
    name: 'Ongetem',
    cat: 'food',
    emoji: '🥩',
    address: 'Canopy by Hilton, Kloof Street, Gardens',
    lat: -33.9303,
    lng: 18.4128,
    search: 'Ongetem Bertus Basson Canopy Hilton Cape Town',
    note: "Ongetem at the Canopy by Hilton is Bertus Basson's bold new city spot. True to its name, meaning 'untamed,' the menu is generous, unpretentious, and meat-forward, with a focus on in-house butchery and fire cooking. Highlights include the aged sirloin with Café de Paris butter, hand-cut fries, and a table-side Waldorf salad you'll return for. This is hotel dining, reimagined and I love it.",
    hours: 'Check website for current hours',
    tip: 'The open kitchen adds energy.',
    type: 'Restaurant & Grill',
    blog: '',
    phone: '',
    website: '',
  },

  {
    id: 8,
    nbhd: 'city',
    name: 'Blondie',
    cat: 'food',
    emoji: '🌿',
    address: 'Kloof Street, Gardens',
    lat: -33.9300,
    lng: 18.4120,
    search: 'Blondie restaurant Kloof Street Cape Town',
    note: "I love the food at Blondie, which is Mediterranean-inspired and leans strongly into sharing plates, vegetables, and bold flavour. The acid salad and roast potatoes are a must. The charred whole cauliflower has become something of a signature, and deservedly so. Everything is reasonably priced. The drinks are good too, and the Paloma is the cocktail to order. It does have quite a party vibe, and it can get very busy with a younger crowd, so I prefer to go off-peak.",
    hours: 'Check website for current hours',
    tip: 'An earlier Saturday lunch or early evening is ideal.',
    type: 'Mediterranean Restaurant',
    blog: '',
    phone: '',
    website: '',
  },

  {
    id: 9,
    nbhd: 'city',
    name: 'The Pot Luck Club',
    cat: 'food',
    emoji: '🏙️',
    address: 'The Biscuit Mill, 373 Albert Road, Woodstock',
    lat: -33.9289,
    lng: 18.4445,
    search: 'Pot Luck Club Woodstock Cape Town',
    note: "Highly acclaimed Asian-inspired tapas menu. Housed at the top of a grain silo, a New York warehouse loft styled, it has magnificent views. Very popular and advisable to book in advance for evening sittings. They do the most fabulous long Sunday brunch paired with bottomless bubbly or Bloody Marys (winter months).",
    hours: 'Check website for current hours',
    tip: 'Try lunchtime if you can\'t get an evening booking.',
    type: 'Asian Tapas',
    blog: '',
    phone: '',
    website: 'https://thepotluckclub.co.za',
  },

  {
    id: 10,
    nbhd: 'city',
    name: 'El Burro',
    cat: 'food',
    emoji: '🌮',
    address: 'Green Point',
    lat: -33.9089,
    lng: 18.4037,
    search: 'El Burro Mexican restaurant Green Point Cape Town',
    note: "This is my favourite Mexican restaurant and I love their ceviche and fish tacos. The pork chilorio is also delicious if I can ever get away from the first two. Their sister restaurant El Burro Taqueria on Kloof Street is another fab spot for a quick bite on the run.",
    hours: 'Check website for current hours',
    tip: 'Booking is advisable in the evening and essential on weekend nights.',
    type: 'Mexican Restaurant',
    blog: '',
    phone: '',
    website: 'https://elburro.co.za',
  },

  {
    id: 11,
    nbhd: 'city',
    name: 'Bao Down',
    cat: 'food',
    emoji: '🥟',
    address: 'Green Point',
    lat: -33.9085,
    lng: 18.4030,
    search: 'Bao Down Cape Town Green Point',
    note: "If you like local and quirky owner-run spots, this is the best in town. Small with vintage kitsch, it is always buzzy. There is a small menu of delicious modern Asian food, which includes popular street food favourites like Bao with pulled pork. This is highly recommended, and reservations are essential.",
    hours: 'Check website for current hours',
    tip: 'Reservations are essential — it\'s a tiny space.',
    type: 'Asian Street Food',
    blog: '',
    phone: '',
    website: 'https://www.baodowncapetown.com',
  },

  {
    id: 12,
    nbhd: 'city',
    name: 'IL Leone Mastrantonio',
    cat: 'food',
    emoji: '🍝',
    address: 'Green Point',
    lat: -33.9091,
    lng: 18.4040,
    search: 'IL Leone Mastrantonio Italian restaurant Cape Town Green Point',
    note: "I have only ever had amazing pasta at this popular spot, and I always eat their seafood or prawn linguini. They serve the very best and thinnest flatbreads that are so crispy and delicious, that they are worth visiting for alone.",
    hours: 'Check website for current hours',
    tip: 'The flatbreads are worth visiting for alone.',
    type: 'Italian Restaurant',
    blog: '',
    phone: '',
    website: 'https://www.mastrantonio.com/il-leone-mastrantonio/',
  },

  {
    id: 13,
    nbhd: 'city',
    name: 'Ramenhead',
    cat: 'food',
    emoji: '🍜',
    address: 'Parliament Square, 37 Parliament Street, CBD',
    lat: -33.9278,
    lng: 18.4223,
    search: 'Ramenhead Cape Town Parliament Square',
    note: "Situated on picturesque Parliament Square in the city and below sister restaurant Fyn, Ramenhead is Peter Tempelhoff's venture, bringing traditional ramen to the Mother City. Silky house-made noodles are part of the mix, where the broth is made for days to develop an intense umami flavour.",
    hours: 'Check website for current hours',
    tip: 'A more casual option from the same kitchen as Fyn upstairs.',
    type: 'Ramen',
    blog: '',
    phone: '',
    website: 'https://www.ramenhead.co.za',
  },

  {
    id: 14,
    nbhd: 'city',
    name: 'Kyoto Garden Sushi',
    cat: 'food',
    emoji: '🍣',
    address: 'De Waterkant, Cape Town',
    lat: -33.9195,
    lng: 18.4095,
    search: 'Kyoto Garden Sushi Cape Town',
    note: "This is where you will find exquisite Japanese cuisine. It's also the only place I know that serves fresh wasabi in the city. There is a focus on quality, and the sushi is of a very high standard. It has a very calm and pampering atmosphere with good service. In winter, they offer a special menu that makes things a little more affordable.",
    hours: 'Check website for current hours',
    tip: 'In winter, ask about the special menu — it\'s better value.',
    type: 'Japanese / Sushi',
    blog: '',
    phone: '',
    website: 'https://kyotogardensushict.com',
  },

  {
    id: 15,
    nbhd: 'city',
    name: 'Galjoen',
    cat: 'food',
    emoji: '🐟',
    address: '99 Harrington Street, CBD',
    lat: -33.9285,
    lng: 18.4295,
    search: 'Galjoen seafood restaurant Cape Town Harrington Street',
    note: "From the restaurateurs behind Belly of the Beast. Head Chef Isca Stoltz draws inspiration from childhood memories of Mozambique's seafood-rich shores. Galjoen offers a set menu that changes based on seasonal availability. This is a multi-course set menu and therefore does not cater for certain dislikes or eating requirements. Best suited for fish-loving omnivores, pescatarians and vegetarians (not vegans).",
    hours: 'Currently dinner only',
    tip: 'Confirm dietary requirements when booking — set menu only.',
    type: 'Seafood Restaurant',
    blog: '',
    phone: '',
    website: 'https://www.galjoencpt.co.za',
  },

  {
    id: 16,
    nbhd: 'city',
    name: 'Hemelhuijs',
    cat: 'cafe',
    emoji: '☕',
    address: 'Waterloo Street, CBD',
    lat: -33.9240,
    lng: 18.4195,
    search: 'Hemelhuijs restaurant Cape Town breakfast lunch',
    note: "This is a great spot for breakfast or lunch in the city centre. The menu in this stylish restaurant always includes a few South African flavours and is carefully curated. Particularly popular amongst interior designers, architects and style lovers.",
    hours: 'Mon–Sat breakfast & lunch',
    tip: 'Go early on weekends — it gets busy.',
    type: 'Café & Restaurant',
    blog: '',
    phone: '',
    website: '',
  },

  {
    id: 17,
    nbhd: 'city',
    name: 'Athletic Club & Social',
    cat: 'cafe',
    emoji: '🍸',
    address: 'Cape Town CBD',
    lat: -33.9250,
    lng: 18.4170,
    search: 'Athletic Club Social Cape Town bar',
    note: "This is my current favourite place to meet for drinks in Cape Town, but the food in the restaurant is a bit mid for me. I have had a few hit-and-miss dining experiences, so I prefer it for drinks. It's Mediterranean/Middle Eastern/Greek inspired. I love the decor, the vibe, the upstairs balcony, and the downstairs lounge for a late-night razzle.",
    hours: 'Check website for current hours',
    tip: 'Come for drinks, not a full meal. The upstairs balcony is a must in summer.',
    type: 'Bar & Restaurant',
    blog: '',
    phone: '',
    website: 'https://theathletic.co.za',
  },

  {
    id: 18,
    nbhd: 'city',
    name: 'Oranjezicht City Farm Market',
    cat: 'market',
    emoji: '🥦',
    address: 'Granger Bay, V&A Waterfront',
    lat: -33.9055,
    lng: 18.4165,
    search: 'Oranjezicht City Farm Market Cape Town',
    note: "This is my preferred farmers' market. Every Saturday and Sunday 9am–2pm. In summer, they are open on a Wednesday evening too. It can get extremely busy over the summer festive season.",
    hours: 'Sat & Sun 9am–2pm; Wed evenings in summer',
    tip: 'Go early on Saturdays for the best produce.',
    type: 'Farmers Market',
    blog: 'https://drizzleanddip.com/2017/01/16/visit-oranjezicht-city-farm-market',
    phone: '',
    website: '',
  },

  {
    id: 19,
    nbhd: 'city',
    name: 'Neighbourgoods Market',
    cat: 'market',
    emoji: '🎵',
    address: 'The Biscuit Mill, 373 Albert Road, Woodstock',
    lat: -33.9292,
    lng: 18.4443,
    search: 'Neighbourgoods Market Biscuit Mill Woodstock Cape Town',
    note: "This is Cape Town's most famous food market and is worth visiting if you haven't been, and for tourists visiting the city. This is more of a lifestyle market with live music, DJ's, etc.",
    hours: 'Sat 9am–2pm',
    tip: 'Get there early — parking becomes a nightmare by 11am.',
    type: 'Food & Lifestyle Market',
    blog: '',
    phone: '',
    website: '',
  },

  // ─── SEA POINT & CAMPS BAY ────────────────────────────────────────────────

  {
    id: 20,
    nbhd: 'city',
    name: 'Arlecchino by Tashas',
    cat: 'food',
    emoji: '🇮🇹',
    address: 'Regent Road, Sea Point',
    lat: -33.9183,
    lng: 18.3889,
    search: 'Arlecchino Tashas Sea Point Cape Town Italian',
    note: "Arlecchino has arrived in Sea Point leaning into a nostalgic idea of Italian dining, where going out feels like an occasion rather than a quick meal. The pasta is a highlight, cooked perfectly with excellent ingredients. Dessert is where it really delivers. The tiramisu, made at the table with espresso-drenched madeleines under a blanket of mascarpone cream, is exactly the kind of theatre this restaurant does well. The pineapple cheesecake is sublime too.",
    hours: 'Daily breakfast, lunch & dinner',
    tip: 'The tableside tiramisu is exactly the kind of theatre this restaurant does well.',
    type: 'Italian Restaurant',
    blog: '',
    phone: '',
    website: '',
  },

  {
    id: 21,
    nbhd: 'city',
    name: "Kleinsky's Deli",
    cat: 'cafe',
    emoji: '🥯',
    address: 'Sea Point',
    lat: -33.9190,
    lng: 18.3892,
    search: "Kleinsky's deli Sea Point Cape Town bagels",
    note: "This is one of my favourite local delis and is where I get my bagels. It gets very busy at the weekend.",
    hours: 'Daily from 7am',
    tip: 'Go mid-week to avoid the weekend queues.',
    type: 'Deli & Café',
    blog: '',
    phone: '',
    website: 'https://www.kleinskys.co.za',
  },

  {
    id: 22,
    nbhd: 'city',
    name: 'He Sheng',
    cat: 'food',
    emoji: '🥟',
    address: 'Sea Point',
    lat: -33.9197,
    lng: 18.3890,
    search: 'He Sheng Chinese restaurant Sea Point Cape Town dumplings',
    note: "This is my favourite Chinese restaurant in Cape Town. They do great house-made dumplings.",
    hours: 'Check website for current hours',
    tip: 'The dumplings are the reason to come.',
    type: 'Chinese Restaurant',
    blog: '',
    phone: '',
    website: 'https://hesheng.co.za',
  },

  {
    id: 23,
    nbhd: 'city',
    name: "Sundoo's",
    cat: 'food',
    emoji: '🍛',
    address: 'Sea Point',
    lat: -33.9193,
    lng: 18.3885,
    search: "Sundoo's Indian tapas Sea Point Cape Town",
    note: "Delicious Indian tapas dishes are served at this busy local restaurant. Their Pondicherry Kingklip curry is sublime. They don't take reservations.",
    hours: 'Check website for current hours',
    tip: 'No reservations — arrive early, especially on weekends.',
    type: 'Indian Restaurant',
    blog: '',
    phone: '',
    website: 'https://seelan.co.za/sundoo/',
  },

  {
    id: 24,
    nbhd: 'city',
    name: 'Salsify at The Roundhouse',
    cat: 'landmark',
    emoji: '🌊',
    address: 'The Roundhouse, Camps Bay',
    lat: -33.9498,
    lng: 18.3770,
    search: 'Salsify Roundhouse Camps Bay Cape Town Ryan Cole',
    note: "Salsify at The Roundhouse is an award-winning fine-dining restaurant located in Cape Town's historic Roundhouse, offering panoramic views of the Atlantic Ocean and Lion's Head. Led by Chef Ryan Cole, the restaurant presents modern, seasonal dishes that highlight local and foraged ingredients, reflecting a commitment to sustainability. Salsify won Restaurant of the Year in the Eat Out Woolworths Restaurant Awards.",
    hours: 'Check website for current hours',
    tip: 'Arrive early for drinks on the terrace before heading inside.',
    type: 'Fine Dining',
    blog: '',
    phone: '',
    website: 'https://salsify.co.za',
  },

  // ─── SOUTHERN PENINSULA ───────────────────────────────────────────────────

  {
    id: 25,
    nbhd: 'peninsula',
    name: 'La Colombe',
    cat: 'landmark',
    emoji: '🏆',
    address: 'Silvermist Estate, Constantia',
    lat: -34.0481,
    lng: 18.3960,
    search: 'La Colombe Silvermist Estate Constantia Cape Town',
    note: "One of my all-time favourite restaurants in Cape Town is nestled high up on Silvermist Estate. Deservedly seen by many as the country's finest restaurant, it is an experience not to be missed. The highly innovative tasting menu changes with the seasons and is expected to delight all your senses with touches of theatrical food theatre. They also offer a really good winter and spring special menu, which is slightly pared down but still amazing.",
    hours: 'Check website for current hours',
    tip: 'The winter and spring special menu is slightly pared down but still amazing.',
    type: 'Fine Dining',
    blog: 'https://drizzleanddip.com/2022/02/28/dinner-at-la-colombe/',
    phone: '',
    website: 'https://www.lacolombe.com',
  },

  {
    id: 26,
    nbhd: 'peninsula',
    name: 'Chefs Warehouse at Beau Constantia',
    cat: 'landmark',
    emoji: '🍷',
    address: 'Beau Constantia Wine Estate, Constantia',
    lat: -34.0335,
    lng: 18.4280,
    search: 'Chefs Warehouse Beau Constantia wine estate Cape Town',
    note: "Ivor Jones heads up this Chefs Warehouse in partnership with Liam Tomlin. Located on Beau Constantia wine estate with exquisite views over the Constantia Valley. World-class food under the watchful eye of head chef Ivor Jones.",
    hours: 'Check website for current hours',
    tip: 'The views over the Constantia Valley are exquisite — go for lunch and linger.',
    type: 'Fine Dining',
    blog: 'https://drizzleanddip.com/2016/12/12/eat-at-the-chefs-warehouse-beau-constantia',
    phone: '',
    website: '',
  },

  {
    id: 27,
    nbhd: 'peninsula',
    name: 'Bistro 1682',
    cat: 'nature',
    emoji: '🌿',
    address: 'Steenberg Wine Estate, Constantia',
    lat: -34.0493,
    lng: 18.4415,
    search: 'Bistro 1682 Steenberg Estate Constantia Cape Town',
    note: "Housed on Steenberg next to the winery is a modern bistro with designer elements. I love this restaurant for breakfast, lunch or evening tapas. Here you will find delicious food with an Asian thread in a beautiful setting overlooking the mountain and vineyards. Be sure to have a wine tasting on your way in (or out).",
    hours: 'Daily breakfast, lunch & dinner',
    tip: 'Be sure to have a wine tasting on your way in (or out).',
    type: 'Wine Estate Restaurant',
    blog: '',
    phone: '',
    website: 'https://www.steenbergfarm.com/bistro1682/',
  },

  {
    id: 28,
    nbhd: 'peninsula',
    name: 'Olympia Café & Deli',
    cat: 'food',
    emoji: '🐟',
    address: 'Main Road, Kalk Bay',
    lat: -34.1268,
    lng: 18.4413,
    search: 'Olympia Cafe Deli Kalk Bay Cape Town',
    note: "Kalk Bay is one of my favourite areas to visit in Cape Town, and my all-time favourite place is Olympia Café. Slightly worn and grungy, it is like eating in your grandmother's kitchen. This 28-odd-year-old iconic eatery is super casual and focuses on amazing seafood dishes. I tend to order only the linguini di mare, a dish they have had on the menu as long as I can remember, and it's one of my tastiest dishes in Cape Town. Their mussels served with freshly baked ciabatta from their own bakery next door are also delicious.",
    hours: 'Daily from 7am',
    tip: 'The linguini di mare is one of my tastiest dishes in Cape Town.',
    type: 'Casual Seafood',
    blog: '',
    phone: '',
    website: 'https://olympiacafe.co.za',
  },

  {
    id: 29,
    nbhd: 'peninsula',
    name: 'Harbour House',
    cat: 'food',
    emoji: '⚓',
    address: 'Kalk Bay Harbour',
    lat: -34.1270,
    lng: 18.4415,
    search: 'Harbour House Kalk Bay Cape Town seafood',
    note: "Harbour House has a lofty aerial view over the Kalk Bay harbour and provides diners with a working harbour view. Crisp white tablecloths and interiors provide an opulent, relaxed experience. I love the beach house feeling that is quintessentially Cape Town, and the harbour with waves crashing right against the side of the building is noteworthy.",
    hours: 'Daily lunch & dinner',
    tip: 'Ask for a harbour-view table.',
    type: 'Seafood Restaurant',
    blog: '',
    phone: '',
    website: 'https://www.harbourhouse.co.za',
  },

  {
    id: 30,
    nbhd: 'peninsula',
    name: 'The Foodbarn',
    cat: 'food',
    emoji: '🏡',
    address: 'Noordhoek Farm Village',
    lat: -34.1031,
    lng: 18.3697,
    search: 'The Foodbarn Noordhoek Farm Village Cape Town Franck Dangereaux',
    note: "Housed in a modern barn on a farm village, you can expect a rustic yet modern atmosphere with really good service. This is one of my personal favourites, and I'm a big fan of the cooking of chef-owner Franck Dangereaux, who was at the helm of La Colombe for many years. He also does amazing cooking demonstration dinners and chef's table Friday lunches, where a menu is paired with a specific wine estate. Expect solid French cooking flair blended in with local ingredients in a stylish but casual bistro setting.",
    hours: 'Check website for current hours',
    tip: 'The Friday chef\'s table lunch paired with a wine estate is particularly special — check their schedule.',
    type: 'Bistro & Deli',
    blog: '',
    phone: '',
    website: 'https://www.thefoodbarn.co.za',
  },

  {
    id: 31,
    nbhd: 'peninsula',
    name: 'Aegir Brewery',
    cat: 'cafe',
    emoji: '🍺',
    address: 'Noordhoek',
    lat: -34.1104,
    lng: 18.3582,
    search: 'Aegir Brewery taproom Noordhoek Cape Town',
    note: "I love this very casual brewery taproom and eatery. In summer, you can show up straight off the beach. They do fantastic burgers and pizza. If this were closer, I would be going there all the time. This is one of my favourite casual eateries in Cape Town.",
    hours: 'Daily from noon',
    tip: 'In summer, you can show up straight off the beach.',
    type: 'Brewery & Eatery',
    blog: '',
    phone: '',
    website: 'https://aegirprojectbrewery.com',
  },

  {
    id: 32,
    nbhd: 'peninsula',
    name: 'Chefs Warehouse Tintswalo Atlantic',
    cat: 'landmark',
    emoji: '🌊',
    address: "Chapman's Peak Drive, Hout Bay",
    lat: -34.0638,
    lng: 18.3478,
    search: "Chefs Warehouse Tintswalo Atlantic Chapman's Peak Hout Bay",
    note: "Housed in the gorgeous Tintswalo Atlantic Lodge on Chapman's Peak Drive and literally on the water's edge, you couldn't get a better location for this lovely restaurant. A contemporary 4-course (8 dishes) tapas set menu is served at lunch and dinner as per the signature Chefswarehouse style. This one is for special occasions.",
    hours: 'Daily lunch & dinner',
    tip: 'This one is for special occasions.',
    type: 'Fine Dining',
    blog: 'https://drizzleanddip.com/2022/10/04/a-stay-at-tintswalo-atlantic/',
    phone: '',
    website: '',
  },

  // ─── STELLENBOSCH ────────────────────────────────────────────────────────

  {
    id: 33,
    nbhd: 'stellenbosch',
    name: 'Post & Pepper',
    cat: 'food',
    emoji: '🏛️',
    address: 'Old Post Office, Bird & Plein Streets, Stellenbosch',
    lat: -33.9352,
    lng: 18.8608,
    search: 'Post Pepper restaurant Stellenbosch South Africa',
    note: "Post & Pepper is a stunning eatery in Stellenbosch housed in the historic Post Office building on the corner of Bird & Plein Streets. Owner Jess van Dyk, formerly of Franschhoek's Protégé restaurant (La Colombe group) created a restaurant she would love to eat at. The dishes are balanced, inspired and with nostalgic South African flavours dotted here and there. I LOVE it!",
    hours: 'Check website for current hours',
    tip: 'One of my favourites in the Winelands.',
    type: 'Restaurant',
    blog: 'https://drizzleanddip.com/2022/03/23/post-pepper-opens-in-stellenbosch/',
    phone: '',
    website: '',
  },

  {
    id: 34,
    nbhd: 'stellenbosch',
    name: 'Arum at Boschendal',
    cat: 'landmark',
    emoji: '🔥',
    address: 'Boschendal Wine Estate, between Stellenbosch and Franschhoek',
    lat: -33.8928,
    lng: 18.9835,
    search: 'Arum restaurant Boschendal wine estate South Africa',
    note: "The historic 1812 cellar at Boschendal has been beautifully reimagined to house Arum, a farm-to-fire restaurant where smoke, char, and flame function as ingredients as much as technique. The bread course alone sets the tone. Kapokbos and olive focaccia alongside wood-fired ciabatta, the best I've tasted. For mains, a 21-day-aged T-bone cooked over flame, exceptionally good.",
    hours: 'Open for breakfast daily, lunch and dinner Wed–Sun',
    tip: 'Open for breakfast daily, lunch and dinner Wednesday to Sunday.',
    type: 'Farm-to-Fire Restaurant',
    blog: '',
    phone: '',
    website: '',
  },

  {
    id: 35,
    nbhd: 'stellenbosch',
    name: 'The Table at De Meye',
    cat: 'food',
    emoji: '🌾',
    address: 'De Meye Wine Estate, Stellenbosch',
    lat: -33.9003,
    lng: 18.8542,
    search: 'The Table De Meye wine estate Stellenbosch South Africa',
    note: "A simple 3-course set menu where all the ingredients are carefully sourced from top-quality local producers. The menu changes weekly and reflects the seasons. Everything is brought to the table and served family style. You sit outside in the shade or next to the vineyards. It's been a favourite of mine for the longest time.",
    hours: 'Fri, Sat & Sun lunch',
    tip: 'Book well in advance — only a handful of tables.',
    type: 'Farm Table Restaurant',
    blog: '',
    phone: '',
    website: 'https://thetablerestaurant.co.za',
  },

  {
    id: 36,
    nbhd: 'stellenbosch',
    name: 'Good to Gather',
    cat: 'food',
    emoji: '🌱',
    address: 'Rozendal Farm, Stellenbosch',
    lat: -33.9253,
    lng: 18.8403,
    search: 'Good to Gather Rozendal Farm Stellenbosch South Africa',
    note: "Located on Rozendal Farm, husband-and-wife Luke Grant and Jess Shepherd run a tiny farm-to-table restaurant serving seasonally inspired lunches on Saturdays and Sundays. In summer, you eat in the oak-shaded courtyard. In winter, inside the Vinegar Tasting Room with a wood-burning stove. The cooking is seasonal, honest, and served partly family style. Book well in advance. Go slowly. Stay for the whole afternoon.",
    hours: 'Sat & Sun lunch only',
    tip: 'Book well in advance. Go slowly. Stay for the whole afternoon.',
    type: 'Farm-to-Table Restaurant',
    blog: '',
    phone: '',
    website: 'https://goodtogather.co.za',
  },

  {
    id: 37,
    nbhd: 'stellenbosch',
    name: 'Delaire Graff Estate',
    cat: 'nature',
    emoji: '🍇',
    address: 'Helshoogte Pass, Stellenbosch',
    lat: -33.9421,
    lng: 18.8982,
    search: 'Delaire Graff Estate restaurant Stellenbosch South Africa',
    note: "I like nothing more than to sit on this terrace under the oak trees and gaze at the spectacular views in summer. The food ranges from casual to more fine-dining-style dishes and is delicious. They have a lovely wine-tasting room in an opulent setting, so you always feel quite spoilt when you go there.",
    hours: 'Daily lunch & dinner',
    tip: 'Hōseki, the Japanese-style restaurant on the same estate, is also well worth a visit.',
    type: 'Wine Estate & Restaurant',
    blog: 'https://drizzleanddip.com/2015/04/07/visit-delaire-graff-restaurant',
    phone: '',
    website: 'https://www.delaire.co.za',
  },

  {
    id: 38,
    nbhd: 'stellenbosch',
    name: 'Spek & Bone',
    cat: 'cafe',
    emoji: '🍷',
    address: 'Dorp Street, Stellenbosch',
    lat: -33.9345,
    lng: 18.8601,
    search: 'Spek Bone Bertus Basson Stellenbosch wine bar',
    note: "If you find yourself looking for a casual spot for lunch or supper in Stellenbosch town, Spek and Bone is another of Bertus Basson's restaurants and offers a small plate menu in a wine bar environment. Tucked away in a historic building next to Oom Samie se Winkle, it is very quaint and well worth a visit.",
    hours: 'Check website for current hours',
    tip: 'A great casual stop in Stellenbosch town.',
    type: 'Wine Bar & Restaurant',
    blog: '',
    phone: '',
    website: 'https://bertusbasson.com',
  },

  // ─── FRANSCHHOEK & PAARL ─────────────────────────────────────────────────

  {
    id: 39,
    nbhd: 'franschhoek',
    name: 'La Petite Colombe',
    cat: 'landmark',
    emoji: '🌸',
    address: 'Leeu Estate, Franschhoek',
    lat: -33.9288,
    lng: 19.1108,
    search: 'La Petite Colombe Leeu Estate Franschhoek South Africa',
    note: "The sister restaurant to La Colombe in Constantia, La Petite Colombe sits within the beautiful grounds of Leeu Estate, with floor-to-ceiling windows looking out over manicured gardens, vines, and mountain backdrop. Head chef Peter Duncan leads a kitchen that takes South African ingredients seriously and treats them with genuine creativity. The cooking has a precision and consistency that places it firmly among the best restaurants in the country.",
    hours: 'Check website for current hours',
    tip: 'Read the full review from the 2019 Spring menu on the blog.',
    type: 'Fine Dining',
    blog: 'https://drizzleanddip.com/2019/08/26/the-new-spring-menu-at-la-petite-colombe-in-franschhoek/',
    phone: '',
    website: '',
  },

  {
    id: 40,
    nbhd: 'franschhoek',
    name: 'Epice',
    cat: 'landmark',
    emoji: '✨',
    address: 'Le Quartier Francais, Franschhoek',
    lat: -33.9192,
    lng: 19.1217,
    search: 'Epice Le Quartier Francais Franschhoek South Africa fine dining',
    note: "A beautiful fine dining restaurant at Le Quartier Français in Franschhoek. The menu is a tasting menu (full or reduced) with or without wine pairing, and is outstanding.",
    hours: 'Check website for current hours',
    tip: 'The wine pairing is worth adding.',
    type: 'Fine Dining',
    blog: 'https://drizzleanddip.com/2022/06/13/epice-in-franschhoek/',
    phone: '',
    website: '',
  },

  {
    id: 41,
    nbhd: 'franschhoek',
    name: 'Chefs Warehouse Maison',
    cat: 'food',
    emoji: '🏡',
    address: 'Maison Estate, Franschhoek',
    lat: -33.9175,
    lng: 19.1248,
    search: 'Chefs Warehouse Maison Estate Franschhoek South Africa',
    note: "This is Liam Tomlin's latest Chef's Warehouse restaurant now in the old Kitchen at Maison space. Beautiful and edgy food in a lovely restored old house overlooking vineyards. Highly recommended.",
    hours: 'Check website for current hours',
    tip: 'The setting in the old house overlooking vineyards is particularly beautiful.',
    type: 'Restaurant',
    blog: '',
    phone: '',
    website: 'https://www.maisonestate.co.za/restaurant/',
  },

  {
    id: 42,
    nbhd: 'franschhoek',
    name: 'Babylonstoren',
    cat: 'nature',
    emoji: '🌺',
    address: 'Babylonstoren Farm, Simondium (Paarl)',
    lat: -33.8424,
    lng: 19.0361,
    search: 'Babylonstoren farm estate Franschhoek Paarl South Africa',
    note: "I have eaten in the restaurant, and it's a totally unique and lovely dining experience, but complicated to get into as a non-resident. They block book most of their tables for their hotel guests, but if you are prepared to take a chance, you can put your name down and hope that from about 1.30pm onwards tables will become available. A walk through their gardens is an absolute must, either way for any visitor.",
    hours: 'Daily lunch — book 2 months ahead or try walk-in from 1:30pm',
    tip: 'A walk through their gardens is an absolute must, either way for any visitor.',
    type: 'Farm Estate & Restaurant',
    blog: 'https://drizzleanddip.com/2021/08/18/a-visit-to-babylonstoren-and-a-stay-at-the-fynbos-cottages/',
    phone: '',
    website: 'https://www.babylonstoren.com',
  },

  // ─── WEST COAST ───────────────────────────────────────────────────────────

  {
    id: 43,
    nbhd: 'west-coast',
    name: 'Wolfgat',
    cat: 'landmark',
    emoji: '🌊',
    address: 'Paternoster, West Coast',
    lat: -32.9847,
    lng: 17.8872,
    search: 'Wolfgat Paternoster West Coast South Africa Kobus van der Merwe',
    note: "Hyper-local Strandveld dining experience by acclaimed chef Kobus van der Merwe. A unique and very special dining experience.",
    hours: 'Check website for current hours',
    tip: 'Book well in advance. Worth the drive from Cape Town.',
    type: 'Fine Dining / Foraging',
    blog: 'https://drizzleanddip.com/2017/03/22/a-west-coast-dining-adventure-at-wolfgat',
    phone: '',
    website: '',
  },

];
