// A Perfect Day — Cyprus
// data.js — 35 curated places
//
// v1 — May 2026
// Voice: boutique hotel concierge — direct, specific, opinionated
// Four categories: Dining · Churches & Monasteries · Heritage & Villages · Nature & Trails
//
// Curated for the Elysium Hotel, Paphos demo
// Research sources: Cyprus Tourism Organisation, UNESCO World Heritage listings,
//   Cyprus Department of Antiquities, Elysium Hotel official website,
//   local press (Cyprus Mail, In-Cyprus), verified May 2026.
// Phone numbers marked † are verified from official sources.
// Coordinates accurate to ~50m for named sites; trail heads approximate.

const PLACES = [

  // ── PAPHOS — Coast & City ─────────────────────────────────────────────────

  {
    id: 1,
    nbhd: 'paphos',
    name: 'Elysium Hotel',
    cat: 'dining',
    emoji: '🏛️',
    address: 'Queen Verenikis Street, 8045 Paphos',
    lat: 34.772922, lng: 32.405640,
    phone: '+357 2684 4444',
    website: 'https://www.elysium-hotel.com',
    search: 'Elysium Hotel Paphos Cyprus seafront luxury pool terrace',
    note: 'A Byzantine-inspired five-star set directly on the Paphos seafront, designed by the architect Giorgos Vasiliou around a sequence of pools, arched colonnades and mosaic-tiled courtyards. Eight restaurants and bars occupy the complex — from the rooftop Astria to the Japanese O\'Shin and the Italian Ristorante Bacco. The hotel is 200 metres from the Kato Pafos archaeological park. Every room faces either the sea or the gardens.',
    hours: 'Open year-round',
    tip: 'Ask for a room on the upper floors of the main building — uninterrupted sea view at the same rate as the garden-side rooms. Breakfast on the terrace overlooking the Mediterranean is worth waking early for.',
    type: 'Five-star resort hotel — Byzantine architecture, seafront',
    awards: 'TUI Global Hotel Awards 2026: Top 100 · TripAdvisor Travellers\' Choice Best of the Best 2025: 10th Best Hotel in the World, 7th Best Hotel in Europe · TUI Global Hotel Awards 2025: Top 100 · Condé Nast Readers\' Choice Awards 2025 · World Travel Awards 2025: Cyprus\'s Leading Boutique Hotel · British Airways Holidays Customer Excellence 2025 · Leading Hotels of the World',
  },

  {
    id: 2,
    nbhd: 'paphos',
    name: 'Lemonia Piazza',
    cat: 'dining',
    emoji: '🍋',
    address: 'Elysium Hotel, Queen Verenikis Street, 8045 Paphos',
    lat: 34.773461, lng: 32.405640,
    phone: '+357 2684 4444',
    website: 'https://www.elysium-hotel.com/dining/lemonia-piazza/',
    search: 'Lemonia Piazza restaurant Elysium Hotel Paphos terrace dining',
    note: 'The Elysium\'s main all-day restaurant, set around a lemon-shaded piazza at the heart of the hotel complex. The menu moves between Cypriot and Mediterranean — meze with local halloumi, grilled fish caught the same morning from the Paphos harbour, and mezze platters that work equally well for a light lunch or a long evening table. The terrace is the most reliably comfortable outdoor dining spot in the Paphos hotel district.',
    hours: 'Daily — breakfast, lunch, and dinner',
    tip: 'The Cypriot meze here is one of the better hotel versions on the island — order the full spread rather than à la carte for a first evening.',
    type: 'All-day Mediterranean and Cypriot restaurant',
  },

  {
    id: 3,
    nbhd: 'paphos',
    name: 'Epicurean Restaurant',
    cat: 'dining',
    emoji: '🍽️',
    address: 'Elysium Hotel, Queen Verenikis Street, 8045 Paphos',
    lat: 34.773302, lng: 32.406106,
    phone: '+357 2684 4444',
    website: 'https://www.elysium-hotel.com/dining/epicurean-restaurant/',
    search: 'Epicurean restaurant Elysium Hotel fine dining Paphos Cyprus',
    note: 'The Elysium\'s fine-dining flagship, focusing on contemporary Mediterranean cuisine with produce sourced from Cypriot farms and the Paphos fishing fleet. The kitchen takes seasonal seriously — the menu changes with what arrives, not the other way around. The room is quieter and more formal than the hotel\'s other venues; right for an occasion meal or a long conversation over wine.',
    hours: 'Dinner only — Tuesday to Sunday (hours subject to season)',
    tip: 'Book the corner table by the window — it faces the sea. The Commandaria dessert wine pairing at the end of the tasting menu is the local note worth keeping.',
    type: 'Fine-dining Mediterranean restaurant',
  },

  {
    id: 4,
    nbhd: 'paphos',
    name: 'Ristorante Bacco',
    cat: 'dining',
    emoji: '🍷',
    address: 'Elysium Hotel, Queen Verenikis Street, 8045 Paphos',
    lat: 34.772920, lng: 32.406299,
    phone: '+357 2684 4444',
    website: 'https://www.elysium-hotel.com/dining/ristorante-bacco/',
    search: 'Ristorante Bacco Italian restaurant Elysium Hotel Paphos',
    note: 'The Italian restaurant in the Elysium complex, serving classic Roman and Neapolitan dishes with Cypriot olive oil and local herbs substituted where it improves rather than compromises. The wine list reaches well beyond the usual hotel Italian selection — the sommelier here knows their Sicilian and Campanian bottles. Good for a relaxed evening that does not want to engage with the meze ritual.',
    hours: 'Dinner only — check current schedule at reception',
    tip: 'The truffle pasta changes with the season. Worth asking what arrived that week rather than ordering from the printed menu alone.',
    type: 'Italian restaurant',
  },

  {
    id: 5,
    nbhd: 'paphos',
    name: 'O\'Shin Japanese Restaurant',
    cat: 'dining',
    emoji: '🍣',
    address: 'Elysium Hotel, Queen Verenikis Street, 8045 Paphos',
    lat: 34.772538, lng: 32.406106,
    phone: '+357 2684 4444',
    website: 'https://www.elysium-hotel.com/dining/oshin-restaurant/',
    search: 'O\'Shin Japanese restaurant sushi Elysium Paphos Cyprus',
    note: 'The only dedicated Japanese restaurant in Paphos that consistently draws guests who are not staying at the hotel. The sushi and sashimi are made with fish from local waters where quality allows, with imported key ingredients. The robata grill is the section worth focusing on — the grilled Black Angus and the whole sea bass over charcoal are better than anything on the standard sushi menu.',
    hours: 'Dinner only — check current schedule at reception',
    tip: 'Arrive before sunset and ask for a courtyard seat. The Japanese aesthetic sits unexpectedly well next to the Byzantine stonework.',
    type: 'Japanese restaurant — sushi and robata grill',
  },

  {
    id: 6,
    nbhd: 'paphos',
    name: 'Mediterraneo Pool Bar',
    cat: 'dining',
    emoji: '🌊',
    address: 'Elysium Hotel, Queen Verenikis Street, 8045 Paphos',
    lat: 34.772379, lng: 32.405640,
    phone: '+357 2684 4444',
    website: 'https://www.elysium-hotel.com/dining/mediterraneo-restaurant/',
    search: 'Mediterraneo pool bar Elysium Hotel Paphos seafront',
    note: 'Light lunches, fresh salads and cold drinks served poolside and on the seafront terrace. The kitchen keeps things simple here by design — the point is the setting: the Elysium\'s main infinity pool with the Mediterranean directly beyond. The halloumi wrap and the fish souvlaki are what most locals order when they come in from the beach.',
    hours: 'Daily during pool hours — seasonal',
    tip: 'The best hour is around 17:00 when the sun angle drops and the terrace cools. Order a Cypriot brandy sour — the local summer drink most visitors miss.',
    type: 'Pool bar and seafront terrace',
  },

  {
    id: 7,
    nbhd: 'paphos',
    name: 'Astria Rooftop Bar',
    cat: 'dining',
    emoji: '🌅',
    address: 'Elysium Hotel, Queen Verenikis Street, 8045 Paphos',
    lat: 34.772538, lng: 32.405174,
    phone: '+357 2684 4444',
    website: 'https://www.elysium-hotel.com/dining/astria-bar/',
    search: 'Astria Bar rooftop Elysium Hotel Paphos sunset cocktails',
    note: 'The Elysium\'s cocktail bar, themed around the night sky and its constellations — the name is Greek for star. Seating inside and on a pergola-covered terrace overlooking the Lethe Spring, which the hotel illuminates after dark. The bar covers cocktails, premium whiskies and cognac, with cigars available on request. Live music on most nights of the week makes it the liveliest spot in the hotel after dinner — more intimate and unhurried than the main restaurant terraces.',
    hours: '19:00–00:30 — open nightly',
    tip: 'The best hour is after dinner when the live music is playing and the Lethe Spring terrace is lit. Ask the bartender for a Commandaria-based cocktail — the island\'s dessert wine works well as a digestif base and is something most guests miss entirely.',
    type: 'Cocktail bar — lobby level, live music nightly',
  },

  {
    id: 8,
    nbhd: 'paphos',
    name: 'Café Occidental',
    cat: 'dining',
    emoji: '☕',
    address: 'Elysium Hotel, Queen Verenikis Street, 8045 Paphos',
    lat: 34.772920, lng: 32.404981,
    phone: '+357 2684 4444',
    website: 'https://www.elysium-hotel.com/dining/cafe-occidental/',
    search: 'Cafe Occidental Elysium Hotel Paphos coffee pastries lounge',
    note: 'The hotel\'s all-day café and lounge — the right stop for a Cypriot coffee or a late-afternoon Commandaria after a morning at the archaeological park. Pastries are made in-house; the loukoumades (Cypriot honey doughnuts) come out warm in the afternoon. Good for work between sightseeing if you need a quiet table and reliable wifi.',
    hours: 'Daily — morning to late evening',
    tip: 'Order the Cypriot coffee the traditional way — sketo (without sugar) or metrio (medium) and ask for it with a small glass of cold water. The carob cake is a local speciality worth trying once.',
    type: 'All-day café and lounge',
  },

  {
    id: 9,
    nbhd: 'paphos',
    name: 'Mare Nostrum Pool Bar',
    cat: 'dining',
    emoji: '🏖️',
    address: 'Elysium Hotel, Queen Verenikis Street, 8045 Paphos',
    lat: 34.773302, lng: 32.405174,
    phone: '+357 2684 4444',
    website: 'https://www.elysium-hotel.com/dining/mare-nostrum-pool-bar/',
    search: 'Mare Nostrum pool bar Elysium Hotel Paphos Cyprus',
    note: 'The second pool bar in the Elysium complex, positioned between the lower pools and the private beach area. Light snacks, fresh juices and cold drinks only — the emphasis is on the location rather than the food. The smaller of the two pool terraces and usually quieter than the Mediterraneo. Most guests use it as a midday retreat from the beach rather than a food destination.',
    hours: 'Seasonal — pool and beach hours',
    tip: 'If the Mediterraneo terrace is busy, walk through to Mare Nostrum — same drinks, same kitchen, but without the crowd.',
    type: 'Beach-side pool bar',
  },

  {
    id: 10,
    nbhd: 'paphos',
    name: 'Kato Pafos Archaeological Park',
    cat: 'heritage',
    emoji: '🏛️',
    address: 'Kato Paphos, 8042 Paphos',
    lat: 34.7533, lng: 32.4037,
    phone: '+357 2630 6217',
    website: 'https://www.visitpaphos.eu/site/kato-paphos-archaeological-park/',
    search: 'Kato Pafos mosaic floor archaeological park UNESCO Cyprus Roman',
    note: 'One of the most important archaeological sites in the eastern Mediterranean and a UNESCO World Heritage Site since 1980. The floor mosaics here — depicting the myths of Dionysus, Theseus, Poseidon and Aion — are among the finest preserved Roman mosaics in the world. They were laid in the 3rd and 4th centuries AD in the villas of wealthy Roman nobles and survive with extraordinary colour and detail. The site also contains the medieval Saranda Kolones fortress, early Christian basilica ruins, and the Tomb of the Kings necropolis nearby. Walk the whole park: it takes about two hours to cover without rushing. UNESCO inscription criteria: (iii) exceptional testimony to Hellenistic and Roman civilisation in Cyprus; (vi) direct association with the cult of Aphrodite and the mythological birthplace of the goddess.',
    hours: 'Daily 08:00–19:30 (summer); 08:00–17:00 (winter). Closed public holidays.',
    tip: 'Go in the morning before the tour groups arrive. The House of Dionysus mosaic is the centrepiece but the House of Aion, toward the back, is quieter and has equally fine detail. Audio guides available at the entrance.',
    type: 'UNESCO World Heritage Site — Roman-era mosaics and ruins',
    awards: 'UNESCO World Heritage Site — Paphos, inscribed 1980, criteria (iii)(vi)',
  },

  {
    id: 11,
    nbhd: 'paphos',
    name: 'Sanctuary of Aphrodite, Palaepaphos',
    cat: 'heritage',
    emoji: '⚱️',
    address: 'Kouklia Village, Paphos District',
    lat: 34.70750, lng: 32.57417,
    phone: '+357 2643 2180',
    website: 'https://www.visitcyprus.com/discover-cyprus/culture/sites-and-monuments/palaipafos-kouklia-archaeological-site/',
    search: 'Palaepaphos Sanctuary Aphrodite Kouklia UNESCO Cyprus ancient temple',
    note: 'The most sacred temple of Aphrodite in the ancient world — the birthplace legend of the goddess of love places her emerging from the sea at the nearby Petra tou Romiou beach, and pilgrims travelled from across the Mediterranean to worship here for more than a thousand years. The sanctuary at Kouklia dates from the 12th century BC and remained in active worship through the Roman era. The Lusignan manor house on the site now holds the excellent Palaepaphos Museum, with finds from the excavations and a large black conical stone — the ancient cult object of Aphrodite herself, from a period before anthropomorphic deity representation.',
    hours: 'Daily 08:00–17:00 (winter), 08:00–19:30 (summer)',
    tip: 'Stop at Petra tou Romiou on the drive south — the birthplace rock is 15 minutes before Kouklia and worth the stop for the coastline view even if the legend is mythological. The combined ticket covers both the sanctuary and the museum.',
    type: 'UNESCO World Heritage Site — sanctuary and museum',
    awards: 'UNESCO World Heritage Site — Paphos, inscribed 1980, criteria (iii)(vi)',
  },

  {
    id: 12,
    nbhd: 'paphos',
    name: 'Yeroskipou Folk Art Museum',
    cat: 'heritage',
    emoji: '🧵',
    address: 'Yeroskipou Village, 8201 Paphos',
    lat: 34.7589, lng: 32.4542,
    phone: '+357 2693 0049',
    website: 'https://www.visitcyprus.com/discover-cyprus/culture/museums-galleries/local-ethnographic-museum-of-geroskipou/',
    search: 'Yeroskipou Folk Art Museum Cyprus traditional crafts silk lace',
    note: 'The village of Yeroskipou — its name from the Greek for Sacred Garden — sits five minutes east of Paphos and contains one of the best small folk art collections on the island. The museum occupies a traditional 18th-century house and covers Cypriot rural life: hand-woven textiles, embroidery, carved furniture, and the local silk weaving tradition that made Yeroskipou famous in the Ottoman period. The five-domed Byzantine church of Agia Paraskevi, in the village square next door, dates from the 9th century and has well-preserved wall paintings inside.',
    hours: 'Mon–Fri 08:00–15:00; Sat 09:00–13:00',
    tip: 'Walk the 200 metres from the museum to Agia Paraskevi church before or after. The folk museum guard is usually happy to explain the silk-making process if you ask — it is one of the last places where anyone remembers it in practice.',
    type: 'Folk art museum — Cypriot craft traditions',
  },

  {
    id: 13,
    nbhd: 'paphos',
    name: 'Filiotis by the Sea',
    cat: 'dining',
    emoji: '🐟',
    address: 'Timi Beach, 8507 Paphos',
    lat: 34.70833, lng: 32.51095,
    phone: '+357 2699 1555',
    website: 'https://www.visitcyprus.com/discover-cyprus/gastronomy/filiotis-fish-tavern/',
    search: 'Filiotis by the Sea restaurant Kissonerga Paphos fresh fish Cyprus',
    note: 'A straightforward fish taverna on the rocks north of Paphos, run by the same family for two generations. The menu is what arrived that morning — the waiter tells you what is available rather than handing you a card. The grilled octopus dried on the line outside, the sea bream from the Paphos fleet, and the homemade taramosalata are the things to order. No pretension, no hotel pricing. The terrace sits ten centimetres above the water at high tide. The Cyprus Mail reviewed it and noted the family sources their fish from their own boat moored in Paphos harbour. Elena Filiotis: \'If we don\'t have fresh fish, we close. It is as simple as that.\'',
    awards: 'Cyprus Mail recommended',
    hours: 'Daily 12:00–22:30 (approximately; closed Mondays in winter)',
    tip: 'Come for lunch on a weekday — by evening in summer the terrace fills entirely with locals from Paphos, which is the endorsement the place deserves. Order the whole fish, not the portions — they know how to cook it whole.',
    type: 'Traditional fish taverna — seafront terrace',
  },

  {
    id: 14,
    nbhd: 'paphos',
    name: 'Coral Bay Beach',
    cat: 'hike',
    emoji: '🏖️',
    address: 'Coral Bay (Corallia Beach), 8099 Paphos',
    lat: 34.857702, lng: 32.3609,
    phone: '',
    website: 'https://www.visitpaphos.eu/beaches/coral-bay/',
    search: 'Coral Bay Corallia Beach Paphos Cyprus sandy cove turquoise',
    note: 'The best sandy beach within 15 minutes of Paphos — a wide horseshoe of pale sand with calm, genuinely turquoise water in a sheltered bay. Well-organised: sun loungers, beach bars, and watersports from May through October. The protected cove cuts the wind that affects the more exposed Paphos city beaches. Snorkelling is good at the rocky edges of the bay where the sea grass beds begin.',
    hours: 'Open beach — beach facilities April to October',
    tip: 'Arrive before 10:00 in July and August to secure a spot under an umbrella without queuing. The rocky headland on the southern end of the bay has the best snorkelling — bring your own mask.',
    type: 'Sandy beach — sheltered cove with facilities',
  },

  // ── AKAMAS — Wild Northwest Peninsula ────────────────────────────────────

  {
    id: 15,
    nbhd: 'akamas',
    name: 'Avakas Gorge',
    cat: 'hike',
    emoji: '🏔️',
    address: 'Avakas Gorge Trailhead, Akamas Peninsula, Paphos',
    lat: 34.8725, lng: 32.3650,
    phone: '',
    website: 'https://www.visitcyprus.com/discover-cyprus/nature/nature-trails-2/avakas-gorge-linear-pafos-paphos-district-akamas-forest-nature-trail/',
    search: 'Avakas Gorge trail hike Akamas Cyprus limestone canyon wild',
    note: 'The most dramatic natural feature on the western coast — a narrow limestone gorge cut by the Avakas river through the Akamas plateau, with walls rising 30 metres in places to near-vertical. The 3km trail in and back follows the river bed itself, requiring several shallow crossings. The gorge narrows to a passage of two or three metres wide in the tightest sections, then opens into small meadow chambers. Wild orchids grow on the upper walls in spring; the rock formations are unlike anything else on the island. Genuinely wild — no facilities at the trailhead.',
    hours: 'Currently closed — check locally before visiting',
    tip: 'Wear shoes that can get wet — the river crossings are unavoidable and the rocks are slippery. Start by 08:00 in summer. The gorge is completely shaded until mid-morning, which makes it one of the best summer walks on the island.',
    type: 'Limestone canyon trail — 3km return',
  },

  {
    id: 16,
    nbhd: 'akamas',
    name: 'Baths of Aphrodite',
    cat: 'heritage',
    emoji: '💧',
    address: 'Akamas Peninsula, Latsi, 8840 Paphos',
    lat: 35.0560, lng: 32.3469,
    phone: '+357 2632 2841',
    website: 'https://www.visitcyprus.com/discover-cyprus/rural/nature-trails/aphrodite-circular-pafos-paphos-district-akamas-forest-nature-trail-2/',
    search: 'Baths of Aphrodite Akamas Cyprus fig tree grotto legend freshwater pool',
    note: 'A freshwater grotto beneath a centuries-old fig tree at the northern tip of the Akamas peninsula, where mythology places the bathing pool of Aphrodite and her tryst with Adonis. The site itself is modest — a shaded pool fed by a spring — but the setting and the short walk from the car park through the coastal scrubland are genuinely beautiful. The Aphrodite Nature Trail begins here and continues 7.5km through the Akamas into the peninsula interior. Even the 15-minute return walk to the grotto is worth making.',
    hours: 'Open daily — no entry fee',
    tip: 'Walk the first kilometre of the Aphrodite Trail beyond the grotto — the coastal view back over the Latsi bay and toward the Troodos is the best angle on western Cyprus you will find without a boat. Return to Latsi harbour for lunch afterward.',
    type: 'Mythological site — freshwater grotto and nature trail',
  },

  {
    id: 17,
    nbhd: 'akamas',
    name: 'Akamas National Forest Park',
    cat: 'hike',
    emoji: '🦎',
    address: 'Akamas Peninsula, Northwest Cyprus',
    lat: 35.0333, lng: 32.3000,
    phone: '',
    website: 'https://www.visitcyprus.com/index.php/en/discovercyprus/nature/natural-attractions/item/245-the-akamas-peninsula',
    search: 'Akamas Peninsula National Park Cyprus endemic plants sea turtle Loggerhead',
    note: 'Cyprus\'s most important protected landscape — a 230 km² peninsula of Paphos Forest, limestone ridges, sand dune systems and nesting beaches. The coastline here is the most significant nesting site for Loggerhead sea turtles (Caretta caretta) in the eastern Mediterranean; nesting season is June through August. The interior holds 168 endemic plant species found nowhere else. Rough tracks only — 4x4 or guided jeep tours are the practical way to reach the interior beaches including Lara Bay.',
    hours: 'Open access — no facilities in the interior',
    tip: 'The sea turtle nesting beaches at Lara Bay are accessible only by 4x4 or boat. If visiting in nesting season, stay on designated paths and do not approach the marked nest sites. The Cyprus Department of Forests runs guided conservation tours in summer.',
    type: 'National Park — wildlife reserve and wilderness coast',
  },

  {
    id: 18,
    nbhd: 'akamas',
    name: 'Tzelefos Medieval Bridge',
    cat: 'hike',
    emoji: '🌉',
    address: 'Diarizos Valley, Paphos Forest',
    lat: 34.8890, lng: 32.7476,
    phone: '',
    website: 'https://www.visitcyprus.com/index.php/en/discovercyprus/nature/trails/item/308-tzelefos-bridge-trail',
    search: 'Tzelefos Bridge Venetian medieval Cyprus Diarizos Valley stone arch',
    note: 'The largest of the Venetian-era bridges in Cyprus, spanning the Diarizos river in the pine-forested foothills of the Paphos Forest. Built in the 15th century to carry the camel-route carrying copper ore and salt between the coast and the mountain mining regions, the bridge has a single arch of 7 metres and still sits perfectly in the river. The 2km return trail follows the river bank through plane trees and wild oleander. Completely uncrowded.',
    hours: 'Open access — no facilities',
    tip: 'The riverside trail in either direction from the bridge is worth extending — the Diarizos valley is one of the least-visited green valleys in the Paphos district. Swim in the river pool below the arch if the water is flowing.',
    type: 'Medieval Venetian bridge — forest trail',
  },

  {
    id: 19,
    nbhd: 'akamas',
    name: 'Elias Medieval Bridge',
    cat: 'hike',
    emoji: '🌿',
    address: 'Paphos Forest — near Agios Nikolaos village',
    lat: 34.8959, lng: 32.7742,
    phone: '',
    website: 'https://www.visitcyprus.com/index.php/en/discovercyprus/culture/monuments/item/246-elias-bridge',
    search: 'Elias Bridge Venetian Cyprus Paphos Forest medieval stone arch trail',
    note: 'A smaller and more intimate Venetian bridge than the Tzelefos, set in a narrow ravine of the upper Diarizos tributaries. The bridge dates from the same 15th-century network and is less visited, which gives it a genuinely untouched quality. The approach involves a short walk through dense Paphos Forest on a track that closes to cars 500 metres from the bridge. Combine with the Tzelefos on the same afternoon — they are 3km apart along the valley.',
    hours: 'Open access — dirt track from Agios Nikolaos village',
    tip: 'The upper Diarizos valley in early spring is carpeted with anemones. If you are here between February and April, this is one of the most quietly beautiful drives in Cyprus.',
    type: 'Medieval Venetian bridge — forest valley',
  },

  {
    id: 20,
    nbhd: 'troodos',
    name: 'Revecca Winery',
    cat: 'winery',
    emoji: '🍇',
    address: 'Agios Mamas Village, Limassol District',
    lat: 34.8507, lng: 32.9483,
    phone: '+357 97 536910',
    website: 'https://reveccawinery.com',
    search: 'Revecca Winery Agios Mamas Commandaria Cyprus wine tasting traditional family winery',
    note: 'A family Commandaria winery in Agios Mamas, a small village in the heart of the Commandaria wine region. The family has been producing Commandaria for generations; since 2015 they have worked from Revecca\'s restored family home — a working winery, folk museum and tasting room under one roof. Two main releases: the Dieti (the classic vintage, approachable and consistent) and small-batch experimental bottlings that explore what Commandaria can do when pushed further. Commandaria is made from dried grapes — intensely sweet, amber-coloured, unlike anything else on the island — and has been produced in this region since at least 800 BC. The winery also runs occasional courtyard dinners and vineyard walks; numbers are kept deliberately small.',
    hours: 'Wed–Sun 11:00–16:00 — walk-ins welcome, reservations appreciated',
    tip: 'The Introduction to Commandaria tasting (€10 per person, about one hour) covers three styles of the wine with context on the land and the history. It is the clearest way to understand why Commandaria matters — and gives you the vocabulary to order it well for the rest of the trip.',
    type: 'Family Commandaria winery — traditional and experimental releases, folk museum',
  },

  // ── TROODOS — Mountain Heart ──────────────────────────────────────────────

  {
    id: 22,
    nbhd: 'troodos',
    name: 'Asinou Church (Panagia Forviotissa)',
    cat: 'church',
    emoji: '⛪',
    address: 'Near Nikitari Village, Nicosia District',
    lat: 34.9944, lng: 32.9367,
    phone: '+357 9961 4562',
    website: 'https://www.visitcyprus.com/discover-cyprus/culture/sites-and-monuments/panagia-asinou-church/',
    search: 'Asinou Church Panagia Forviotissa UNESCO Byzantine fresco Cyprus',
    note: 'The finest Byzantine church interior in Cyprus and one of the most important in the eastern Mediterranean. Built in 1105–06 and subsequently expanded, Asinou contains a near-complete cycle of Byzantine frescoes spanning five centuries of painting from the 12th to 17th century — a compressed history of Byzantine art on a single set of walls. The oldest layers include some of the finest Comnenian-period painting outside Constantinople. The church is tiny — barely 12 metres long — which means the frescoes, covering every centimetre of wall and vault, press close at every turn. Listed as one of 10 churches in the UNESCO-designated Painted Churches of the Troodos Region (inscribed 1985), which UNESCO describes as providing \'an overview of Byzantine and post-Byzantine painting in Cyprus over a period of 500 years.\'',
    hours: 'Daily 09:30–13:00 and 14:00–16:30. Key held by the local priest — call ahead.',
    tip: 'The priest who keeps the key is hospitable and will explain the fresco cycles in Greek or English if you ask. Allow 45 minutes inside — rushing misses the layering. The drive through the Troodos foothills to reach Asinou is itself worth the hour from Paphos.',
    type: 'UNESCO Byzantine church — 12th–17th century frescoes',
    awards: 'UNESCO World Heritage Site — Painted Churches of the Troodos Region, inscribed 1985',
  },

  {
    id: 23,
    nbhd: 'troodos',
    name: 'St Nicholas of the Roof (Agios Nikolaos tis Stegis)',
    cat: 'church',
    emoji: '🏔️',
    address: 'Near Kakopetria Village, Nicosia District',
    lat: 34.9775, lng: 32.8894,
    phone: '+357 2292 2460',
    website: 'https://www.visitcyprus.com/discover-cyprus/culture/sites-and-monuments/agios-nikolaos-tis-stegis-church/',
    search: 'Agios Nikolaos tis Stegis Kakopetria Byzantine UNESCO Cyprus fresco church',
    note: 'Named for its distinctive pitched wooden roof built over the original Byzantine dome in the 13th century to protect it from snow — a purely functional adaptation that gives the church its entirely unusual profile. Inside, Byzantine frescoes from the 11th to the 17th century cover all surfaces, including a rare 11th-century Transfiguration scene that predates most surviving Comnenian examples. The setting in a pine and plane-tree valley above Kakopetria is as striking as the church itself. UNESCO World Heritage Site.',
    hours: 'Tue–Sun 09:00–13:00 and 14:00–16:00 (winter); until 18:00 (summer)',
    tip: 'The village of Kakopetria 4km below is a good base for the Troodos churches — old stone mill houses converted to guesthouses, and a good trout restaurant by the river. Combine Agios Nikolaos with Asinou for a full day of UNESCO frescoes.',
    type: 'UNESCO Byzantine church — 11th–17th century frescoes',
    awards: 'UNESCO World Heritage Site — Painted Churches of the Troodos Region, inscribed 1985',
  },

  {
    id: 24,
    nbhd: 'troodos',
    name: 'St John Lampadistis Monastery',
    cat: 'church',
    emoji: '✝️',
    address: 'Kalopanagiotis Village, Nicosia District',
    lat: 34.9925, lng: 32.8303,
    phone: '+357 2295 2060',
    website: 'https://www.visitcyprus.com/discover-cyprus/rural/sites-monuments/agios-ioannis-lampadistis-church-2/',
    search: 'St John Lampadistis Kalopanagiotis monastery UNESCO Cyprus Byzantine Latin',
    note: 'A monastery complex containing three interconnected churches from different centuries — a rare architectural palimpsest that makes this one of the most layered sacred sites in Cyprus. The 11th-century Byzantine church, the 13th-century chapel of St Herakleidios, and the 15th-century Latin chapel (built for Catholic Lusignan pilgrims who came to venerate the Orthodox saint) sit under one roof, each with a distinct fresco tradition. The Latin chapel contains Italo-Byzantine frescoes that show the moment when eastern and western medieval painting were trying to understand each other. UNESCO World Heritage Site.',
    hours: 'Daily 09:00–13:00 and 14:00–16:30',
    tip: 'Ask the monk or caretaker to show you the Latin chapel separately — it is sometimes kept locked and the frescoes inside are the strangest and most fascinating in the complex. Kalopanagiotis village below has a good walnut-raki distillery.',
    type: 'UNESCO monastery complex — three churches, three centuries',
    awards: 'UNESCO World Heritage Site — Painted Churches of the Troodos Region, inscribed 1985',
  },

  {
    id: 25,
    nbhd: 'troodos',
    name: 'Kykkos Monastery',
    cat: 'church',
    emoji: '🛕',
    address: 'Kykkos, Troodos Mountains, Paphos District',
    lat: 34.9839, lng: 32.7411,
    phone: '+357 2294 2793',
    website: 'https://www.ikykkos.com',
    search: 'Kykkos Monastery Cyprus Byzantine icon Virgin Mary Makarios Troodos',
    note: 'The wealthiest and most influential monastery in Cyprus, founded in the 11th century and rebuilt after successive fires in its current form in the 19th–20th centuries. The monastery holds the most venerated icon in Cyprus: the Virgin Mary painted, by tradition, by St Luke, and kept permanently covered — it has not been seen by human eyes since 980 AD by decree. The treasury museum houses one of the finest collections of Byzantine ecclesiastical objects in the region. Archbishop Makarios III, the first President of Cyprus, is buried at the Throni hilltop shrine above the monastery.',
    hours: 'Daily 10:00–18:00 (summer), 10:00–16:00 (winter). Dress code: covered shoulders and knees.',
    tip: 'The monastery itself is 19th-century reconstruction — go for the icon tradition, the treasury museum, and the mountain setting, not for ancient architecture. Walk the 3km to Throni hilltop for the Makarios tomb and a view across the entire western Troodos range.',
    type: 'Active monastery — icon of the Virgin Mary',
    awards: 'Active monastery — significant national and religious institution',
  },

  {
    id: 26,
    nbhd: 'troodos',
    name: 'Millomeris Waterfall',
    cat: 'hike',
    emoji: '💦',
    address: 'Near Pano Platres, Limassol District',
    lat: 34.8838, lng: 32.8650,
    phone: '',
    website: 'https://www.visitcyprus.com/index.php/en/discovercyprus/nature/trails/item/309-millomeris-waterfall-trail',
    search: 'Millomeris Waterfall Pano Platres Cyprus highest waterfall hike Troodos',
    note: 'Cyprus\'s highest waterfall at 15 metres, dropping into a wooded gorge of eastern Troodos cedars, plane trees and strawberry trees. The 2km circular trail from Pano Platres village descends through dense forest to the falls — the walk down is easy; the return requires some climbing. In winter and early spring the waterfall runs at full volume; by July it reduces but does not stop entirely. The gorge itself remains cool and shaded even in summer.',
    hours: 'Open access — trailhead in Pano Platres village',
    tip: 'The Platres village square has good kafeneions for coffee and the local commandaria honey cake before or after the walk. Combine with Kalidonia Falls 3km further along the same trail network.',
    type: 'Waterfall trail — 2km circular, 15m falls',
  },

  {
    id: 27,
    nbhd: 'troodos',
    name: 'Kalidonia Falls',
    cat: 'hike',
    emoji: '🌊',
    address: 'Caledonia Trail, Pano Platres, Limassol District',
    lat: 34.9031, lng: 32.8699,
    phone: '',
    website: 'https://www.visitcyprus.com/discover-cyprus/nature/nature-trails-2/kalidonia-linear-lemesos-limassol-district-troodos-forest-nature-trail/',
    search: 'Kalidonia Falls Caledonia Trail Platres Cyprus waterfall hike forest stream',
    note: 'A 3km linear trail through the Kryos Potamos river gorge, descending from the presidential summer residence above Platres to the village below through a sequence of river crossings and pine and plane forest. The path passes the 12-metre Kalidonia Falls at the midpoint — the best waterfall setting in the Troodos in terms of the surrounding woodland. Named by Scottish foresters who planted the cedars here in the 19th century and found it reminded them of home. The trail is mostly downhill from top to bottom — arrange a car at each end.',
    hours: 'Open access — best spring through early summer',
    tip: 'Start at the top (by the Troodos Platres presidential residence) and walk down to Platres village — the trail is far more enjoyable in descent. The river crossings require stepping stones; passable in ordinary trainers in summer.',
    type: 'Forest waterfall trail — 3km linear descent',
  },

  {
    id: 28,
    nbhd: 'troodos',
    name: 'Cedar Valley & Stavros tis Psokas',
    cat: 'hike',
    emoji: '🍃',
    address: 'Cedar Valley, Near Stavros tis Psokas, Paphos Forest',
    lat: 34.9915, lng: 32.6885,
    phone: '',
    website: 'https://www.visitcyprus.com/discover-cyprus/nature/excursions/cedar-valley/',
    search: 'Chantara Waterfalls Cedar Valley Cyprus mouflon waterfall Paphos Forest',
    note: 'A series of small cascades in the Cedar Valley section of Paphos Forest, in the same protected zone as the last wild colony of Cyprus mouflon (wild mountain sheep). The falls themselves are modest compared to Millomeris and Kalidonia, but the Cedar Valley setting — with the endemic Cyprus cedar (Cedrus brevifolia) found nowhere else on earth — is the real reason to come. Mouflon sightings at dusk are genuinely common in the meadow above the falls.',
    hours: 'Open access — Paphos Forest is closed to vehicles in fire season (July–September)',
    tip: 'Stavros tis Psokas forestry station nearby has a small enclosure where rescued mouflon are kept — the best guarantee of a sighting if the wild colony is not visible. The cedar forest walk takes about an hour without rushing.',
    type: 'Waterfall and forest walk — endemic cedars and mouflon',
  },

  {
    id: 29,
    nbhd: 'troodos',
    name: 'Agros Village',
    cat: 'heritage',
    emoji: '🌹',
    address: 'Agros Village, Limassol District',
    lat: 34.9178, lng: 33.0181,
    phone: '',
    website: 'https://www.visitcyprus.com/discover-cyprus/rural/villages-rural/agros-village-2/',
    search: 'Agros Village Cyprus rose water distillery traditional mountain village',
    note: 'A mountain village at 1000 metres in the eastern Troodos, known throughout Cyprus for its rose-water distillery — the harvest in late April and early May fills the whole valley with scent and the village runs a small but serious rose-petal festival. The Agros Cooperative distillery has operated since 1983 and produces rose water, rose jam, rose liqueur and natural cosmetics from the Damascus rose cultivated on the hillside terraces above the village. The traditional stone architecture is almost entirely intact.',
    hours: 'Village accessible year-round; distillery open daily in season',
    tip: 'If you are there outside rose season, the distillery shop sells the preserved products year-round. The village church of the Archangel Michael has a carved wooden iconostasis of unusual quality. The drive from Platres through the valley takes 30 minutes.',
    type: 'Mountain village — rose distillery and traditional crafts',
  },

  {
    id: 30,
    nbhd: 'troodos',
    name: 'Vlassides Winery',
    cat: 'winery',
    emoji: '🍾',
    address: 'Kilani Village, Limassol District',
    lat: 34.8293, lng: 32.8510,
    phone: '+357 2547 0044',
    website: 'https://vlassideswinery.com',
    search: 'Vlassides Winery Cyprus boutique Shiraz Xynisteri Kilani wine tasting',
    note: 'The most internationally recognised of the new-generation Cyprus boutique wineries, consistently rated among the top 100 wineries in the world by Decanter. Sophocles Vlassides trained in California and returned to work with both international varieties (Shiraz, Cabernet) and indigenous Cypriot grapes. The Shiraz is the flagship and is genuinely world-class. The winery is in Kilani village in the Troodos foothills — a functioning estate with vines visible from the tasting room. Recent medals: Gold at Concours Mondial de Bruxelles 2025 and Berliner Wein Trophy 2025 both for Artion 2019; three Golds at the Cyprus Wine Competition 2026; multiple Decanter World Wine Awards medals since 2018.',
    hours: 'Mon–Sat 10:00–18:00 — tastings by appointment',
    tip: 'Book the extended tasting with the winemaker if available — Sophocles Vlassides or a senior member of the team usually conducts these personally. The Cabernet-Maratheftiko blend is the most interesting experiment currently in production.',
    type: 'Internationally recognised boutique winery',
    awards: 'Concours Mondial de Bruxelles 2025: Gold (Artion) · Berliner Wein Trophy 2025: Gold (Artion, Óroman) · Cyprus Wine Competition 2026: 3× Gold · Decanter World Wine Awards',
  },

  // ── LEFKARA & VILLAGES — Heritage and Inland ─────────────────────────────

  {
    id: 31,
    nbhd: 'lefkara',
    name: 'Pano Lefkara',
    cat: 'heritage',
    emoji: '🪡',
    address: 'Pano Lefkara Village, Larnaca District',
    lat: 34.8670, lng: 33.3000,
    phone: '',
    website: 'https://lefkara.org',
    search: 'Pano Lefkara lace embroidery Cyprus traditional village UNESCO Leonardo da Vinci',
    note: 'The most celebrated craft village in Cyprus — known for lefkaritika lace embroidery, a tradition of hand-stitched geometric patterns on linen that has been practiced here for over five centuries. Leonardo da Vinci is recorded as having visited and purchased lefkaritika cloth for Milan Cathedral in 1481. The craft is listed on UNESCO\'s Intangible Cultural Heritage list. The village itself is one of the most architecturally preserved in Cyprus — carved stone facades, cobbled alleys, and carved wooden doors. The Lefkara silversmithing tradition runs in parallel to the lace: small workshops still produce the geometric filigree work that was this village\'s second export.',
    hours: 'Village always accessible; lace workshops typically open 09:00–17:00',
    tip: 'Walk past the tourist shops on the main lane and find the elderly women working in doorways in the side alleys — these are the actual practitioners, and they are genuinely hospitable if you stop to watch. Buy directly from a maker rather than the commercial shops at the village entrance.',
    type: 'UNESCO Intangible Heritage — lace-making village',
    awards: 'UNESCO Intangible Cultural Heritage — Lefkaritika lace embroidery, inscribed 2009',
  },

  {
    id: 32,
    nbhd: 'lefkara',
    name: 'Omodos Village',
    cat: 'heritage',
    emoji: '🍷',
    address: 'Omodos Village, Limassol District',
    lat: 34.8444, lng: 32.8067,
    phone: '',
    website: 'https://www.visitcyprus.com/places-to-go/villages/omodos-village-3/',
    search: 'Omodos village Cyprus wine cobblestones Timios Stavros monastery traditional',
    note: 'A wine village in the Commandaria wine region at the southern edge of the Troodos, known for the Monastery of Timios Stavros (Holy Cross) in its central square — founded in the 8th century and holding relics of the True Cross by tradition. The village is one of the best preserved traditional settlements in Cyprus: cobblestone alleys, stone-arched houses, and wine cellars. Commandaria, the world\'s oldest named wine (documented since 800 BC), is produced in this region. The village square in the evening is one of the more civilised places on the island to drink a glass of local wine.',
    hours: 'Village and monastery accessible daily',
    tip: 'The monastery museum has a good collection of ecclesiastical embroidery and old maps. For Commandaria, ask the wine shops around the square for a tasting — several are run by families producing it traditionally on a small scale.',
    type: 'Traditional wine village — Commandaria region',
  },

  {
    id: 33,
    nbhd: 'lefkara',
    name: 'Timios Stavros Monastery, Omodos',
    cat: 'church',
    emoji: '⛪',
    address: 'Central Square, Omodos Village, Limassol District',
    lat: 34.8445, lng: 32.8068,
    phone: '+357 2594 2423',
    website: 'https://www.visitcyprus.com/index.php/en/discovercyprus/culture/sites/item/292-monastery-of-timiou-stavrou',
    search: 'Timios Stavros Monastery Omodos Cyprus Holy Cross relic Byzantine',
    note: 'An active monastery occupying the entire central square of Omodos village — the most visually striking integration of religious and civic space in Cyprus. Founded in the 8th century according to tradition; the current buildings mostly 19th century. The monastery holds relics described as fragments of the True Cross and the rope used at the Crucifixion, housed in ornate reliquaries in the church. The small museum attached to the monastery displays these objects and a collection of ecclesiastical embroidery and manuscripts. The Omodos cultural festival takes place in the monastery courtyard each August.',
    hours: 'Daily 10:00–12:30 and 14:00–18:00',
    tip: 'The monastery church itself is darker and quieter than most tourist sites on the island — a genuinely functional religious space. The museum keeps the same hours as the church and is included in the same free entry.',
    type: 'Active monastery — 8th-century foundation, Holy Cross relics',
  },

  {
    id: 34,
    nbhd: 'lefkara',
    name: 'Karseras Winery',
    cat: 'winery',
    emoji: '🌿',
    address: 'Doros Village, Limassol District',
    lat: 34.8168, lng: 32.9094,
    phone: '+357 99 589325',
    website: 'http://www.karseraswinery.com',
    search: 'Karseras Winery Koilani Cyprus indigenous varieties natural wine tasting',
    note: 'A small family winery in Koilani village working exclusively with native Cypriot grape varieties — Maratheftiko, Xynisteri, Promara and Spourtiko — that most producers had abandoned in favour of international varieties. The winery is explicitly a conservation project as much as a commercial one: the old family vines on the limestone hillside are some of the oldest ungrafted vineyards in Cyprus. The tasting is informal and usually conducted by a family member. The Maratheftiko is structured differently from other examples — higher tannin, longer on the finish, and made for ageing.',
    hours: 'Mon–Sat 10:00–17:00 — call ahead to confirm',
    tip: 'The Koilani village kafeneion next door to the winery is run by the same extended family. Lunch before the tasting is the local approach. Ask about the old-vine Spourtiko — it is rarely bottled as a single variety and is unusual.',
    type: 'Family winery — indigenous Cypriot variety conservation',
  },

  {
    id: 35,
    nbhd: 'akamas',
    name: 'Aphrodite Trail',
    cat: 'hike',
    emoji: '🦋',
    address: 'Baths of Aphrodite, Akamas Peninsula, Paphos District',
    lat: 35.0622, lng: 32.3344,
    phone: '',
    website: 'https://chooseyourcyprus.com/aphrodite-trail/',
    search: 'Aphrodite Trail Akamas Peninsula Cyprus circular hike Baths of Aphrodite Pyrgos tis Rigainas Polis Chrysochous',
    note: 'A 7.5km circular trail through the Akamas Peninsula following the mythological path of Aphrodite. Starts and ends at the Baths of Aphrodite. The route climbs to Moutti tis Sotiras (370m) through dense pine and scrubland forest, passing the ruins of Pyrgos tis Rigainas (Queen\'s Tower) — remnants of a medieval monastery where a centuries-old oak marks the spot where the goddess rested. Panoramic views open across Polis Chrysochous bay and the Paphos Forest. Two drinking water fountains on the route. The trail joins the Adonis Trail at one point, making a longer combined walk possible. Rated medium difficulty — the section between the Baths and the Queen\'s Tower is steep.',
    hours: 'Open access year-round — best October to May',
    tip: 'Start early in summer — the exposed ridge section gets very hot by mid-morning. The Adonis Trail branches off at the Queen\'s Tower ruins; stick to the Aphrodite Trail markers to stay on the circular route back to the Baths. Combine with lunch at Latchi harbour, 3km away.',
    type: 'Circular nature trail — 7.5km, 370m elevation, Akamas Peninsula',
  },

  // ── SOUTH COAST & NEW ENTRIES ─────────────────────────────────────────────

  {
    id: 36,
    nbhd: 'paphos',
    name: 'Petra tou Romiou (Aphrodite\'s Rock)',
    cat: 'heritage',
    emoji: '🌊',
    address: 'Petra tou Romiou, Kouklia Coast, Paphos District',
    lat: 34.6635, lng: 32.6270,
    phone: '',
    website: 'https://www.visitcyprus.com/discover-cyprus/culture/sites-and-monuments/birthplace-of-aphrodite-petra-tou-romiou/',
    search: 'Petra tou Romiou Aphrodite Rock Cyprus birthplace goddess sea stack Kouklia coast',
    note: 'The coastal site where, according to Greek myth, Aphrodite rose from the sea foam. Three limestone sea stacks stand offshore on a shingle beach edged by turquoise water — visually one of the most immediately striking stretches of coastline on the island. The site is on the Paphos-Limassol highway (B6), 25 kilometres east of Paphos city. A small visitor car park and café sit above the beach; the walk down takes five minutes. Swimming is possible but the sea floor is rocky and currents can be strong in rough weather. The afternoon light turns the rocks gold against the sea. The site falls within the Paphos UNESCO World Heritage area.',
    hours: 'Open access at all times. Car park and café approximately 08:00–18:00 in season.',
    tip: 'Walk east along the shoreline past the main rocks for a clear view away from the road. Sunset here is legitimately exceptional — the rocks catch the orange light and the sea goes still. Arrive 30 minutes before the sun drops.',
    type: 'Mythological landmark — birthplace of Aphrodite, pebble beach and sea stacks',
    awards: 'UNESCO World Heritage Site — Paphos, inscribed 1980, criteria (iii)(vi)',
  },

  {
    id: 37,
    nbhd: 'troodos',
    name: 'Chantara Waterfall',
    cat: 'hike',
    emoji: '💧',
    address: 'Foini Village, Limassol District (1km north on Diarizos River)',
    lat: 34.9049, lng: 32.8408,
    phone: '',
    website: 'https://www.visitcyprus.com/discover-cyprus/nature/natural-beauties/chantara-waterfall/',
    search: 'Chantara Hantara waterfall Foini Cyprus Diarizos river Troodos pine forest',
    note: 'The most dramatic waterfall in the Troodos range — 8 metres of water dropping from volcanic basalt rock onto a mossy shelf above a cold, clear pool. Set in dense pine and arbutus forest at 1,030 metres altitude on the Diarizos River, 3 kilometres south of Trooditissa Monastery and 1 kilometre north of Foini village. A smooth 1.2-kilometre dirt road from Foini leads directly to the falls, passable by any car. Steps carved into the rock beside the waterfall lead to a viewing ledge with a clean view of the full drop. Ruins of a 19th-century water mill stand at the base. The name comes from the Troodos dialect word for the sound of rushing water: \'antara\'. A trout farm sits 200 metres downstream.',
    hours: 'Open access year-round — flow is strongest October to May',
    tip: 'Walk 200 metres past the waterfall to the Chantara trout farm: grilled trout caught the same morning, eaten at wooden tables over the water. No printed menu — whatever was caught that day. One of the better meals in the mountains.',
    type: 'Waterfall — 8-metre drop, Diarizos River, 1030m altitude',
  },

  {
    id: 38,
    nbhd: 'akamas',
    name: 'Koullas Sandwiches',
    cat: 'dining',
    emoji: '🥪',
    address: 'Charalampou Fournidi 2, Pomos Village, Paphos District',
    lat: 35.1470, lng: 32.5309,
    phone: '+357 96 589533',
    website: 'https://www.facebook.com/KoullasSandwiches/',
    search: 'Koullas sandwiches Pomos Cyprus village lunch local halloumi',
    note: 'A roadside lunch institution in Pomos village that has been making sandwiches since before the village had a tourist in it. The menu changes daily with whatever arrived that morning: grilled halloumi, seasonal vegetables, local sausage, fresh herbs. Nothing complicated, nothing frozen. Pomos sits on the coastal drive between Polis and Latchi — Koullas is the natural stop after the Akamas or before heading south through Avakas Gorge. Outdoor seating with a view down to the Pomos fishing harbour. Closes when the sandwiches run out, usually early afternoon.',
    hours: 'Daily approximately 08:00–14:00 — closes when sold out',
    tip: 'The halloumi comes off a proper charcoal grill, not a press. Order two sandwiches: one immediately, one for the road. Cypriot coffee on request.',
    type: 'Roadside café — grilled sandwiches, local ingredients, harbour view',
  },

  {
    id: 39,
    nbhd: 'troodos',
    name: 'Mount Olympus (Chionistra)',
    cat: 'hike',
    emoji: '⛰️',
    address: 'Troodos Square, Troodos, Limassol District',
    lat: 34.9364, lng: 32.8631,
    phone: '',
    website: 'https://mytroodos.com/nature-trails-hiking/',
    search: 'Mount Olympus Cyprus Chionistra peak Troodos hiking summit 1952 metres Artemis trail',
    note: 'The highest point in Cyprus at 1,952 metres — the geographic and geological centre of the island. The summit itself carries military radar installations and is not fully accessible, but the Artemis Trail (7km loop of the summit ridge) and the longer Atalante Trail (12km circuit) both give panoramic views south to the Limassol coast and north toward the Kyrenia range on clear days. The forest at this altitude is cedar, black pine and golden oak — different in character from anywhere lower on the island. Snow covers the peak reliably between December and March; a small ski slope operates on the north face. The Troodos Square village at the base is the start point for all major trails and is consistently 6–8°C cooler than the coast in summer.',
    hours: 'Trails open year-round. Troodos Square facilities: daily in season.',
    tip: 'The Artemis Trail is the best single walk on the island: cedar forest, open ridge with full island views, and nearly empty on weekday mornings. Start before 09:00 in summer to avoid the midday heat. The Caledonia Trail to the Caledonia Waterfall begins 3km below — link the two for a full day in the mountains.',
    type: 'Mountain summit — 1,952m, highest point in Cyprus, marked hiking trails',
  },

  {
    id: 40,
    nbhd: 'lefkara',
    name: 'Choirokoitia Neolithic Settlement',
    cat: 'heritage',
    emoji: '🏺',
    address: 'Choirokoitia, Larnaca District, Cyprus',
    lat: 34.7954, lng: 33.3439,
    phone: '+357 2432 2710',
    website: 'https://www.visitcyprus.com/discover-cyprus/culture/sites-and-monuments/choirokoitia-archaeological-site-neolithic-settlement/',
    search: 'Choirokoitia Khirokitia Neolithic settlement Cyprus UNESCO 7000BC roundhouse tholos',
    note: 'One of the most significant prehistoric sites in the eastern Mediterranean and a UNESCO World Heritage Site since 1998. Founded around 7000 BC by some of the earliest farmers in Cyprus, on a hilltop above the Maroni River — the site was continuously occupied from the 7th to the 4th millennium BC. The circular stone-built houses (tholoi) survive as excavated foundations, with partial reconstructions built next to the originals so visitors can move through actual Neolithic domestic architecture. The excavations uncovered polished stone tools, obsidian blades traded from Anatolia, stored grain and human burials placed under house floors. Cyprus\'s three UNESCO World Heritage Sites are Paphos (1980), the Painted Churches in the Troodos (1985), and Choirokoitia (1998). This is the only one focused entirely on prehistoric settlement. UNESCO inscription criteria: (ii)(iii) — exceptional evidence of early human settlement, predating most European Neolithic cultures by two thousand years.',
    hours: 'Daily 08:30–17:00 (winter); 08:30–19:30 (summer). Closed public holidays.',
    tip: 'The reconstructed roundhouses at the entrance read as visitor-facing, but the excavated originals 100 metres up the hill are genuinely striking — the scale and density of a real 9,000-year-old settlement. Audio guide available at the entrance. The site is on the A1/A6 motorway, 40 minutes from Paphos: the most accessible of Cyprus\'s three UNESCO sites by road.',
    type: 'UNESCO World Heritage Site — Neolithic settlement, 7000 BC, tholos architecture',
    awards: 'UNESCO World Heritage Site — Choirokoitia, inscribed 1998, criteria (ii)(iii)',
  },


  // ── NEW ENTRIES — May 2026 ────────────────────────────────────────────────

  {
    id: 49,
    nbhd: 'troodos',
    name: 'Antoniades Winery',
    cat: 'winery',
    emoji: '🍇',
    address: 'Mandria Village, 4778 Limassol',
    lat: 34.8672, lng: 32.8313,
    phone: '+357 25 422638',
    website: 'https://www.antoniadeswinery.com',
    search: 'Antoniades Winery Mandria Limassol Cyprus Krasochoria Afames Xynisteri Commandaria pithari',
    note: 'A small family estate in the Krasochoria wine villages on the slopes of Afames mountain, Limassol district. The Antoniades family traces its winemaking to the 18th century; the current winery was established commercially in 1994 by Marios Antoniades, a trained wine chemist. The approach combines modern cellar practice with traditional methods — including fermentation in pithari, the ancient Cypriot clay storage jars that predate amphora use on the island. Three main wines: the Kastelani Dry White from Xynisteri, the Kastelani Dry Red blending indigenous Mavro with Cabernet Sauvignon, and a limited Cabernet Sauvignon of around 2,000 bottles per year. The winery also produces a Nama — a traditional Cypriot sweet wine in the Commandaria style, made from sun-dried grapes — which is the most distinctive and least-known of their range. Visits are personal and unhurried; Marios or a family member typically conducts the tasting himself.',
    hours: 'Mon–Thu 10:30–17:00; Fri–Sat 10:30–17:30; Sun 11:00–17:00 — call ahead to confirm',
    tip: 'Ask specifically to taste the Nama — the Commandaria-style sweet wine is not always poured on the standard tasting and is the most unusual thing the winery produces. The pithari jars in the cellar are worth seeing; the winery is one of the few that still uses them in production rather than as decoration.',
    type: 'Family winery — Krasochoria, Afames mountain, pithari fermentation, Commandaria-style Nama',
  },


  {
    id: 41,
    nbhd: 'akamas',
    name: 'Vasilikon Winery',
    cat: 'winery',
    emoji: '🍷',
    address: 'Kathikas Village, 8573 Paphos',
    lat: 34.9003, lng: 32.4148,
    phone: '+357 26 633999',
    website: 'https://vasilikon.com',
    search: 'Vasilikon Winery Kathikas Cyprus wine tasting Xynisteri Laona plateau',
    note: 'One of the better-known wineries on the Laona plateau, set in Kathikas village at 700 metres above the Paphos coast. Family-run since 1993, working with both indigenous Cypriot varieties — Xynisteri white, Maratheftiko and Mavro reds — and international grapes including Syrah and Cabernet Sauvignon. The elevation gives the wines a freshness that the lower coastal vineyards cannot match. The Xynisteri at this altitude develops more mineral tension than the valley examples. Tastings run daily and include a winery walk. The surrounding Laona plateau is one of the most intact traditional landscapes in the Paphos district — stone villages, almond orchards and old terraced vines still worked by hand.',
    hours: 'Daily 09:00–18:00',
    tip: 'Combine with the drive through the Laona villages — Arodes, Pano and Kato Akourdaleia — which sit in the same plateau and have almost no tourist traffic. The views west toward the Akamas coast from Kathikas are among the best in the Paphos district.',
    type: 'Boutique winery — indigenous and international varieties, Laona plateau',
    awards: 'Multiple Decanter World Wine Awards · Cyprus Wine Competition medals',
  },

  {
    id: 42,
    nbhd: 'paphos',
    name: 'Agios Neofytos Monastery',
    cat: 'church',
    emoji: '⛪',
    address: 'Tala Village, 8572 Paphos',
    lat: 34.8436, lng: 32.4462,
    phone: '+357 2665 2481',
    website: 'http://www.stneophytos.org.cy',
    search: 'Agios Neophytos Monastery Paphos cave enklistra Byzantine frescoes hermit',
    note: 'The monastery founded in 1159 by St Neophytos, a monk who carved his hermitage — the Enklistra — directly into the cliff face by hand. The original cave cells are the most unusual sacred space in Cyprus: three rooms hewn from rock at the end of the 12th century, their walls covered entirely in Byzantine frescoes painted under the saint\'s personal supervision, including a self-portrait. Neophytos wrote extensively from here — his texts on the Crusader occupation of Cyprus are among the most vivid eyewitness accounts of the period. The monastery church built later holds more frescoes and the preserved tomb of the saint. The Enklistra entrance is through a narrow passage in the cliff, 40 metres above the monastery level.',
    hours: 'Daily 09:00–16:00; closed Orthodox Easter and Christmas',
    tip: 'The Enklistra is the reason to come — the Byzantine frescoes inside the hand-carved cave, at close range, are among the most intimate sacred paintings in Cyprus. Allow 45 minutes for both the cave and the monastery below. Entrance fee €3.',
    type: 'Active monastery — 12th-century cliff hermitage and Byzantine frescoes',
    awards: 'Listed Ancient Monument — Cyprus Department of Antiquities',
  },

  {
    id: 43,
    nbhd: 'akamas',
    name: 'Paphos Zoo',
    cat: 'hike',
    emoji: '🦁',
    address: 'Xylomantrou Street, Peyia, 8560 Paphos',
    lat: 34.8572, lng: 32.3730,
    phone: '+357 26 813852',
    website: 'https://www.pafoszoo.com',
    search: 'Paphos Zoo Peyia Cyprus animals wildlife family',
    note: 'The largest zoo in Cyprus, set in over 100,000 square metres of landscaped grounds in Peyia, 20 kilometres north of Paphos. The zoo holds a broad range of animals from large cats, primates and parrots to reptiles and birds of prey, with daily keeper talks and feeding sessions. Well-maintained and shaded — the Peyia elevation and Mediterranean planting make it considerably cooler than the Paphos seafront on summer afternoons. A sensible half-day option for guests travelling with children or in need of a break from archaeological sites.',
    hours: 'Daily 09:00–18:00 (Apr–Oct); 09:00–17:00 (Nov–Mar); 09:00–19:00 (Aug)',
    tip: 'The bird of prey show and the primate enclosures are the strongest sections. Go in the morning before the midday heat. The zoo café is adequate for lunch; better to eat in Coral Bay or Peyia village afterward.',
    type: 'Zoo — 100,000 sq m, multiple species, daily shows',
  },

  {
    id: 44,
    nbhd: 'akamas',
    name: 'Edro III Shipwreck',
    cat: 'heritage',
    emoji: '⚓',
    address: 'Pegeia Coastline, near Sea Caves, Paphos',
    lat: 34.87305, lng: 32.33931,
    phone: '',
    website: 'https://cyprus.sustainablewrecksnetwork.com/locations/edro-iii/',
    search: 'Edro III shipwreck Paphos Cyprus Pegeia sea caves Coral Bay stranded cargo ship',
    note: 'A 80-metre cargo ship that ran aground on the rocky Pegeia coastline in October 2011 during a storm, 200 metres from the famous sea caves of Pegeia. The crew of nine were airlifted to safety; the ship has remained where it grounded, slowly settling against the limestone rock. What makes the Edro III exceptional as a sight is its setting: the hull lies tilted against a coastline of dramatic wave-cut limestone formations, sea arches and caves — the rust-orange wreck against the white rock and turquoise water is one of the most photographed landscapes on the island. Accessible from a small car park on the coastal path; the walk down takes about five minutes. The surrounding limestone sea caves are worth exploring on the same visit.',
    hours: 'Open access at all times — coastal path',
    tip: 'The best viewing angle is from the rocks to the south of the wreck, where the ship\'s full profile and the limestone formations behind it are visible together. Come in the afternoon when the light is on the west-facing hull. The sea caves 200 metres south are accessible on foot at low tide.',
    type: 'Shipwreck — 80m cargo vessel, limestone sea cave coastline',
  },

  {
    id: 45,
    nbhd: 'akamas',
    name: 'St George Chapel & Geronissos Island',
    cat: 'church',
    emoji: '⛪',
    address: 'Cape Drepanum, Agios Georgios, Peyia, 8570 Paphos',
    lat: 34.8953, lng: 32.3248,
    phone: '',
    website: 'https://thisispeyia.com/point-of-interest/agios-georgios-church/',
    search: 'Agios Georgios chapel Cape Drepanum Peyia Geronissos island basilica ruins Cyprus medieval',
    note: 'A medieval Byzantine chapel at Cape Drepanum on the northwest Paphos coast, with a second smaller 13th-century basilica chapel below it on the cliff edge — both overlooking the tiny island of Geronissos (also called Iera Nisos, Sacred Island), 200 metres offshore. Geronissos held an ancient sanctuary thought to have been dedicated to Apollo; excavations have found Hellenistic-era remains on the island. The coastal site also has early Christian basilica ruins from the 5th–6th centuries AD visible in the rock below the chapel. The setting — cliff-top chapel, uninhabited island, limestone sea caves to the south, and the Akamas coast stretching north — is one of the most dramatic on the island. Sunsets from this headland are exceptional.',
    hours: 'Open access — outdoor site',
    tip: 'Come 30 minutes before sunset. The headland faces directly west and the light on Geronissos island and the sea caves at dusk is worth timing the visit for. The lower basilica ruins are reached by a path down the cliff — passable but steep.',
    type: 'Medieval Byzantine chapel — cliff-top site overlooking Geronissos island',
  },

  {
    id: 46,
    nbhd: 'akamas',
    name: 'Skarfos Medieval Bridge',
    cat: 'hike',
    emoji: '🌉',
    address: 'Near Simou Village, Paphos District',
    lat: 34.9490, lng: 32.5880,
    phone: '',
    website: 'https://cypriot-villages.uk/skarfos-venetian-bridge/',
    search: 'Skarfos Venetian bridge Cyprus oldest dated bridge 1618 Evretou Simou Paphos',
    note: 'The oldest dated bridge in Cyprus, bearing an inscription of 1618 — making it contemporaneous with the later Venetian building tradition on the island. A single stone arch of 8.5 metres, spanning the Stavros tis Psokas river near the abandoned village of Skarfou, between Evretou and Sarama in the Paphos interior. Less visited than the Tzelefos and Elias bridges, with a genuinely untouched quality: the riverbank is overgrown with oleander and plane trees, and the stone of the arch is entirely intact. The approach from Simou village follows a rough track through the Paphos Forest foothills. Combine with the Evretou reservoir dam 3km further, which has its own good views across the valley.',
    hours: 'Open access — rough track from Simou village',
    tip: 'The bridge is the oldest dated one on the island but the least-signposted. Download the location before setting out — the track from Simou is unmarked. The riverbank in early spring is carpeted with wild anemones and cyclamen.',
    type: 'Medieval stone bridge — oldest dated bridge in Cyprus, 1618',
  },

  {
    id: 47,
    nbhd: 'akamas',
    name: 'Latsi Marina & Boat Hire',
    cat: 'hike',
    emoji: '⛵',
    address: 'Latsi Harbour, Polis Chrysochous, 8820 Paphos',
    lat: 35.0375, lng: 32.3770,
    phone: '+357 99 053488',
    website: 'https://www.latchiwatersportscentre.com',
    search: 'Latsi Latchi marina boat hire rental Cyprus Blue Lagoon sea caves Akamas',
    note: 'The small harbour at Latsi (also spelled Latchi) is the main departure point for boat excursions along the Akamas coastline — the section of coast that is only fully accessible from the sea. Options range from two-hour group boat trips to the Blue Lagoon and the Akamas sea caves, to full-day private hire. The group trips cover the limestone sea caves cut into the Akamas headland, the clear-water bay at Blue Lagoon (anchored swimming stop), and the coastline north toward the Baths of Aphrodite. Private boat hire gives access to the same route on your own schedule. The harbour itself has a row of fish tavernas on the waterfront — Latsi is a working fishing village and the seafood is direct from the boats. The drive north from Paphos along the coast road to reach Latsi takes about 40 minutes.',
    hours: 'Boat hire: daily in season (approximately April–October)',
    tip: 'The Blue Lagoon is the highlight of the sea route — turquoise water sheltered by the Akamas headland, only accessible by boat. Book morning departures for the calmest sea conditions. The harbour fish tavernas are best at lunch when the catch is freshest.',
    type: 'Marina — group boat trips and private hire, Akamas coast access',
  },

  {
    id: 48,
    nbhd: 'paphos',
    name: 'Tombs of the Kings',
    cat: 'heritage',
    emoji: '🏺',
    address: 'Tombs of the Kings Road, Kato Paphos, 8046 Paphos',
    lat: 34.7722, lng: 32.4033,
    phone: '+357 2630 6217',
    website: 'https://www.visitcyprus.com/discover-cyprus/culture/sites-and-monuments/tombs-of-the-kings/',
    search: 'Tombs of the Kings Paphos Cyprus necropolis rock-cut Hellenistic Roman UNESCO underground',
    note: 'A large rock-cut necropolis north of Paphos harbour, dating from the 4th to the 3rd century BC and continuing into the Roman period. Despite the name, no kings were buried here — the tombs held wealthy Paphian nobles and officials, whose status is evident in the scale and architectural ambition of the chambers: some have full Doric peristyle courtyards cut into the rock, with columns and atrium spaces that mimic the houses of the living. The complex covers a wide area of coastal cliff and low plateau, with eight main tomb groups and numerous smaller chambers. At peak season the area is less visited than the Kato Paphos mosaics, making it easier to move through at your own pace. Part of the Paphos UNESCO World Heritage Site (inscribed 1980). Entrance fee €2.50.',
    hours: 'Daily 08:00–19:30 (summer); 08:00–17:00 (winter). Closed Christmas, New Year, Orthodox Easter.',
    tip: 'Tomb 8 — the large peristyle tomb with Doric columns — is the architectural centrepiece and worth spending time in. Go in the early morning when the light enters the courtyard and the site is cool. The cliff-edge sections have views over the sea.',
    type: 'UNESCO World Heritage Site — Hellenistic rock-cut necropolis, 4th–3rd century BC',
    awards: 'UNESCO World Heritage Site — Paphos, inscribed 1980, criteria (iii)(vi)',
  },

];
