// A Perfect Day — Cyprus
// data.js — 35 curated places
//
// v1 — May 2026
// Voice: boutique hotel concierge — direct, specific, opinionated
// Four categories: Dining · Churches & Monasteries · Heritage & Villages · Nature & Trails
//
// Curated for the Elysium Hotel, Paphos demo
// Research sources: Cyprus Tourism Organisation, UNESCO World Heritage listings,
//   Cyprus Department of Antiquities, Elysium Hotel official website,
//   local press (Cyprus Mail, In-Cyprus), verified May 2026.
// Phone numbers marked † are verified from official sources.
// Coordinates accurate to ~50m for named sites; trail heads approximate.

const PLACES = [

  // ── PAPHOS — Coast & City ─────────────────────────────────────────────────

  {
    id: 1,
    nbhd: 'paphos',
    name: 'Elysium Hotel',
    cat: 'dining',
    emoji: '🏛️',
    address: 'Queen Verenikis Street, 8045 Paphos',
    lat: 34.7517, lng: 32.4083,
    phone: '+357 2684 4444',
    website: 'https://www.elysium-hotel.com',
    search: 'Elysium Hotel Paphos Cyprus seafront luxury pool terrace',
    note: 'A Byzantine-inspired five-star set directly on the Paphos seafront, designed by the architect Giorgos Vasiliou around a sequence of pools, arched colonnades and mosaic-tiled courtyards. Eight restaurants and bars occupy the complex — from the rooftop Astria to the Japanese O\'Shin and the Italian Ristorante Bacco. The hotel is 200 metres from the Kato Pafos archaeological park. Every room faces either the sea or the gardens.',
    hours: 'Open year-round',
    tip: 'Ask for a room on the upper floors of the main building — uninterrupted sea view at the same rate as the garden-side rooms. Breakfast on the terrace overlooking the Mediterranean is worth waking early for.',
    type: 'Five-star resort hotel — Byzantine architecture, seafront',
    awards: 'Leading Hotels of the World · TUI Hotel Awards · Condé Nast Traveller 2025 · TripAdvisor Travelers\' Choice 2025',
  },

  {
    id: 2,
    nbhd: 'paphos',
    name: 'Lemonia Piazza',
    cat: 'dining',
    emoji: '🍋',
    address: 'Elysium Hotel, Queen Verenikis Street, 8045 Paphos',
    lat: 34.752241, lng: 32.408300,
    phone: '+357 2684 4444',
    website: 'https://www.elysium-hotel.com/dining/lemonia-piazza/',
    search: 'Lemonia Piazza restaurant Elysium Hotel Paphos terrace dining',
    note: 'The Elysium\'s main all-day restaurant, set around a lemon-shaded piazza at the heart of the hotel complex. The menu moves between Cypriot and Mediterranean — meze with local halloumi, grilled fish caught the same morning from the Paphos harbour, and mezze platters that work equally well for a light lunch or a long evening table. The terrace is the most reliably comfortable outdoor dining spot in the Paphos hotel district.',
    hours: 'Daily — breakfast, lunch, and dinner',
    tip: 'The Cypriot meze here is one of the better hotel versions on the island — order the full spread rather than à la carte for a first evening.',
    type: 'All-day Mediterranean and Cypriot restaurant',
  },

  {
    id: 3,
    nbhd: 'paphos',
    name: 'Epicurean Restaurant',
    cat: 'dining',
    emoji: '🍽️',
    address: 'Elysium Hotel, Queen Verenikis Street, 8045 Paphos',
    lat: 34.752082, lng: 32.408766,
    phone: '+357 2684 4444',
    website: 'https://www.elysium-hotel.com/dining/epicurean/',
    search: 'Epicurean restaurant Elysium Hotel fine dining Paphos Cyprus',
    note: 'The Elysium\'s fine-dining flagship, focusing on contemporary Mediterranean cuisine with produce sourced from Cypriot farms and the Paphos fishing fleet. The kitchen takes seasonal seriously — the menu changes with what arrives, not the other way around. The room is quieter and more formal than the hotel\'s other venues; right for an occasion meal or a long conversation over wine.',
    hours: 'Dinner only — Tuesday to Sunday (hours subject to season)',
    tip: 'Book the corner table by the window — it faces the sea. The Commandaria dessert wine pairing at the end of the tasting menu is the local note worth keeping.',
    type: 'Fine-dining Mediterranean restaurant',
  },

  {
    id: 4,
    nbhd: 'paphos',
    name: 'Ristorante Bacco',
    cat: 'dining',
    emoji: '🍷',
    address: 'Elysium Hotel, Queen Verenikis Street, 8045 Paphos',
    lat: 34.751700, lng: 32.408959,
    phone: '+357 2684 4444',
    website: 'https://www.elysium-hotel.com/dining/ristorante-bacco/',
    search: 'Ristorante Bacco Italian restaurant Elysium Hotel Paphos',
    note: 'The Italian restaurant in the Elysium complex, serving classic Roman and Neapolitan dishes with Cypriot olive oil and local herbs substituted where it improves rather than compromises. The wine list reaches well beyond the usual hotel Italian selection — the sommelier here knows their Sicilian and Campanian bottles. Good for a relaxed evening that does not want to engage with the meze ritual.',
    hours: 'Dinner only — check current schedule at reception',
    tip: 'The truffle pasta changes with the season. Worth asking what arrived that week rather than ordering from the printed menu alone.',
    type: 'Italian restaurant',
  },

  {
    id: 5,
    nbhd: 'paphos',
    name: 'O\'Shin Japanese Restaurant',
    cat: 'dining',
    emoji: '🍣',
    address: 'Elysium Hotel, Queen Verenikis Street, 8045 Paphos',
    lat: 34.751318, lng: 32.408766,
    phone: '+357 2684 4444',
    website: 'https://www.elysium-hotel.com/dining/oshin/',
    search: 'O\'Shin Japanese restaurant sushi Elysium Paphos Cyprus',
    note: 'The only dedicated Japanese restaurant in Paphos that consistently draws guests who are not staying at the hotel. The sushi and sashimi are made with fish from local waters where quality allows, with imported key ingredients. The robata grill is the section worth focusing on — the grilled Black Angus and the whole sea bass over charcoal are better than anything on the standard sushi menu.',
    hours: 'Dinner only — check current schedule at reception',
    tip: 'Arrive before sunset and ask for a courtyard seat. The Japanese aesthetic sits unexpectedly well next to the Byzantine stonework.',
    type: 'Japanese restaurant — sushi and robata grill',
  },

  {
    id: 6,
    nbhd: 'paphos',
    name: 'Mediterraneo Pool Bar',
    cat: 'dining',
    emoji: '🌊',
    address: 'Elysium Hotel, Queen Verenikis Street, 8045 Paphos',
    lat: 34.751159, lng: 32.408300,
    phone: '+357 2684 4444',
    website: 'https://www.elysium-hotel.com/dining/mediterraneo/',
    search: 'Mediterraneo pool bar Elysium Hotel Paphos seafront',
    note: 'Light lunches, fresh salads and cold drinks served poolside and on the seafront terrace. The kitchen keeps things simple here by design — the point is the setting: the Elysium\'s main infinity pool with the Mediterranean directly beyond. The halloumi wrap and the fish souvlaki are what most locals order when they come in from the beach.',
    hours: 'Daily during pool hours — seasonal',
    tip: 'The best hour is around 17:00 when the sun angle drops and the terrace cools. Order a Cypriot brandy sour — the local summer drink most visitors miss.',
    type: 'Pool bar and seafront terrace',
  },

  {
    id: 7,
    nbhd: 'paphos',
    name: 'Astria Rooftop Bar',
    cat: 'dining',
    emoji: '🌅',
    address: 'Elysium Hotel, Queen Verenikis Street, 8045 Paphos',
    lat: 34.751318, lng: 32.407834,
    phone: '+357 2684 4444',
    website: 'https://www.elysium-hotel.com/dining/astria-bar/',
    search: 'Astria Bar rooftop Elysium Hotel Paphos sunset cocktails',
    note: 'The rooftop bar on the uppermost floor of the main Elysium building — the highest licensed terrace in Paphos with a clear 270-degree view from the Akamas headland to the Paphos Lighthouse. Cocktail-focused with a short food menu. The view at sunset, particularly toward the Akamas, is genuinely one of the best in Cyprus. Non-guests are welcome but the terrace fills early in high season.',
    hours: 'Evening — check current schedule with hotel',
    tip: 'Walk up 20 minutes before sunset. The colours over the Akamas peninsula at dusk change more dramatically than the standard sea-sunset shot most guests come for.',
    type: 'Rooftop cocktail bar',
  },

  {
    id: 8,
    nbhd: 'paphos',
    name: 'Café Occidental',
    cat: 'dining',
    emoji: '☕',
    address: 'Elysium Hotel, Queen Verenikis Street, 8045 Paphos',
    lat: 34.751700, lng: 32.407641,
    phone: '+357 2684 4444',
    website: 'https://www.elysium-hotel.com/dining/cafe-occidental/',
    search: 'Cafe Occidental Elysium Hotel Paphos coffee pastries lounge',
    note: 'The hotel\'s all-day café and lounge — the right stop for a Cypriot coffee or a late-afternoon Commandaria after a morning at the archaeological park. Pastries are made in-house; the loukoumades (Cypriot honey doughnuts) come out warm in the afternoon. Good for work between sightseeing if you need a quiet table and reliable wifi.',
    hours: 'Daily — morning to late evening',
    tip: 'Order the Cypriot coffee the traditional way — sketo (without sugar) or metrio (medium) and ask for it with a small glass of cold water. The carob cake is a local speciality worth trying once.',
    type: 'All-day café and lounge',
  },

  {
    id: 9,
    nbhd: 'paphos',
    name: 'Mare Nostrum Pool Bar',
    cat: 'dining',
    emoji: '🏖️',
    address: 'Elysium Hotel, Queen Verenikis Street, 8045 Paphos',
    lat: 34.752082, lng: 32.407834,
    phone: '+357 2684 4444',
    website: 'https://www.elysium-hotel.com/dining/mare-nostrum/',
    search: 'Mare Nostrum pool bar Elysium Hotel Paphos Cyprus',
    note: 'The second pool bar in the Elysium complex, positioned between the lower pools and the private beach area. Light snacks, fresh juices and cold drinks only — the emphasis is on the location rather than the food. The smaller of the two pool terraces and usually quieter than the Mediterraneo. Most guests use it as a midday retreat from the beach rather than a food destination.',
    hours: 'Seasonal — pool and beach hours',
    tip: 'If the Mediterraneo terrace is busy, walk through to Mare Nostrum — same drinks, same kitchen, but without the crowd.',
    type: 'Beach-side pool bar',
  },

  {
    id: 10,
    nbhd: 'paphos',
    name: 'Kato Pafos Archaeological Park',
    cat: 'heritage',
    emoji: '🏛️',
    address: 'Kato Paphos, 8042 Paphos',
    lat: 34.7533, lng: 32.4037,
    phone: '+357 2630 6217',
    website: 'https://www.visitpaphos.eu/site/kato-paphos-archaeological-park/',
    search: 'Kato Pafos mosaic floor archaeological park UNESCO Cyprus Roman',
    note: 'One of the most important archaeological sites in the eastern Mediterranean and a UNESCO World Heritage Site since 1980. The floor mosaics here — depicting the myths of Dionysus, Theseus, Poseidon and Aion — are among the finest preserved Roman mosaics in the world. They were laid in the 3rd and 4th centuries AD in the villas of wealthy Roman nobles and survive with extraordinary colour and detail. The site also contains the medieval Saranda Kolones fortress, early Christian basilica ruins, and the Tomb of the Kings necropolis nearby. Walk the whole park: it takes about two hours to cover without rushing. UNESCO inscription criteria: (iii) exceptional testimony to Hellenistic and Roman civilisation in Cyprus; (vi) direct association with the cult of Aphrodite and the mythological birthplace of the goddess.',
    hours: 'Daily 08:00–19:30 (summer); 08:00–17:00 (winter). Closed public holidays.',
    tip: 'Go in the morning before the tour groups arrive. The House of Dionysus mosaic is the centrepiece but the House of Aion, toward the back, is quieter and has equally fine detail. Audio guides available at the entrance.',
    type: 'UNESCO World Heritage Site — Roman-era mosaics and ruins',
    awards: 'UNESCO World Heritage Site — Paphos, inscribed 1980, criteria (iii)(vi)',
  },

  {
    id: 11,
    nbhd: 'paphos',
    name: 'Sanctuary of Aphrodite, Palaepaphos',
    cat: 'heritage',
    emoji: '⚱️',
    address: 'Kouklia Village, Paphos District',
    lat: 34.6761, lng: 32.5522,
    phone: '+357 2643 2180',
    website: 'https://www.mcw.gov.cy/mcw/DA/DA.nsf/All/5B6E3D6BA2A6B3C9C225748400347B79',
    search: 'Palaepaphos Sanctuary Aphrodite Kouklia UNESCO Cyprus ancient temple',
    note: 'The most sacred temple of Aphrodite in the ancient world — the birthplace legend of the goddess of love places her emerging from the sea at the nearby Petra tou Romiou beach, and pilgrims travelled from across the Mediterranean to worship here for more than a thousand years. The sanctuary at Kouklia dates from the 12th century BC and remained in active worship through the Roman era. The Lusignan manor house on the site now holds the excellent Palaepaphos Museum, with finds from the excavations and a large black conical stone — the ancient cult object of Aphrodite herself, from a period before anthropomorphic deity representation.',
    hours: 'Daily 08:00–17:00 (winter), 08:00–19:30 (summer)',
    tip: 'Stop at Petra tou Romiou on the drive south — the birthplace rock is 15 minutes before Kouklia and worth the stop for the coastline view even if the legend is mythological. The combined ticket covers both the sanctuary and the museum.',
    type: 'UNESCO World Heritage Site — sanctuary and museum',
    awards: 'UNESCO World Heritage Site — Paphos, inscribed 1980, criteria (iii)(vi)',
  },

  {
    id: 12,
    nbhd: 'paphos',
    name: 'Yeroskipou Folk Art Museum',
    cat: 'heritage',
    emoji: '🧵',
    address: 'Yeroskipou Village, 8201 Paphos',
    lat: 34.7589, lng: 32.4542,
    phone: '+357 2693 0049',
    website: 'https://www.mcw.gov.cy/mcw/DA/DA.nsf/All/A3A0C5AB2C63C225748400347B7A',
    search: 'Yeroskipou Folk Art Museum Cyprus traditional crafts silk lace',
    note: 'The village of Yeroskipou — its name from the Greek for Sacred Garden — sits five minutes east of Paphos and contains one of the best small folk art collections on the island. The museum occupies a traditional 18th-century house and covers Cypriot rural life: hand-woven textiles, embroidery, carved furniture, and the local silk weaving tradition that made Yeroskipou famous in the Ottoman period. The five-domed Byzantine church of Agia Paraskevi, in the village square next door, dates from the 9th century and has well-preserved wall paintings inside.',
    hours: 'Mon–Fri 08:00–15:00; Sat 09:00–13:00',
    tip: 'Walk the 200 metres from the museum to Agia Paraskevi church before or after. The folk museum guard is usually happy to explain the silk-making process if you ask — it is one of the last places where anyone remembers it in practice.',
    type: 'Folk art museum — Cypriot craft traditions',
  },

  {
    id: 13,
    nbhd: 'paphos',
    name: 'Filiotis by the Sea',
    cat: 'dining',
    emoji: '🐟',
    address: 'Kissonerga Seafront, Paphos District',
    lat: 34.7950, lng: 32.4050,
    phone: '+357 2699 1555',
    website: 'https://www.filiotisrestaurant.com',
    search: 'Filiotis by the Sea restaurant Kissonerga Paphos fresh fish Cyprus',
    note: 'A straightforward fish taverna on the rocks north of Paphos, run by the same family for two generations. The menu is what arrived that morning — the waiter tells you what is available rather than handing you a card. The grilled octopus dried on the line outside, the sea bream from the Paphos fleet, and the homemade taramosalata are the things to order. No pretension, no hotel pricing. The terrace sits ten centimetres above the water at high tide. The Cyprus Mail reviewed it and noted the family sources their fish from their own boat moored in Paphos harbour. Elena Filiotis: \'If we don\'t have fresh fish, we close. It is as simple as that.\'',
    awards: 'Cyprus Mail recommended',
    hours: 'Daily 12:00–22:30 (approximately; closed Mondays in winter)',
    tip: 'Come for lunch on a weekday — by evening in summer the terrace fills entirely with locals from Paphos, which is the endorsement the place deserves. Order the whole fish, not the portions — they know how to cook it whole.',
    type: 'Traditional fish taverna — seafront terrace',
  },

  {
    id: 14,
    nbhd: 'paphos',
    name: 'Coral Bay Beach',
    cat: 'hike',
    emoji: '🏖️',
    address: 'Coral Bay (Corallia Beach), 8099 Paphos',
    lat: 34.8333, lng: 32.3667,
    phone: '',
    website: 'https://www.visitpaphos.eu/beaches/coral-bay/',
    search: 'Coral Bay Corallia Beach Paphos Cyprus sandy cove turquoise',
    note: 'The best sandy beach within 15 minutes of Paphos — a wide horseshoe of pale sand with calm, genuinely turquoise water in a sheltered bay. Well-organised: sun loungers, beach bars, and watersports from May through October. The protected cove cuts the wind that affects the more exposed Paphos city beaches. Snorkelling is good at the rocky edges of the bay where the sea grass beds begin.',
    hours: 'Open beach — beach facilities April to October',
    tip: 'Arrive before 10:00 in July and August to secure a spot under an umbrella without queuing. The rocky headland on the southern end of the bay has the best snorkelling — bring your own mask.',
    type: 'Sandy beach — sheltered cove with facilities',
  },

  // ── AKAMAS — Wild Northwest Peninsula ────────────────────────────────────

  {
    id: 15,
    nbhd: 'akamas',
    name: 'Avakas Gorge',
    cat: 'hike',
    emoji: '🏔️',
    address: 'Avakas Gorge Trailhead, Akamas Peninsula, Paphos',
    lat: 34.8725, lng: 32.3650,
    phone: '',
    website: 'https://www.visitcyprus.com/index.php/en/discovercyprus/nature/trails/item/303-avakas-gorge',
    search: 'Avakas Gorge trail hike Akamas Cyprus limestone canyon wild',
    note: 'The most dramatic natural feature on the western coast — a narrow limestone gorge cut by the Avakas river through the Akamas plateau, with walls rising 30 metres in places to near-vertical. The 3km trail in and back follows the river bed itself, requiring several shallow crossings. The gorge narrows to a passage of two or three metres wide in the tightest sections, then opens into small meadow chambers. Wild orchids grow on the upper walls in spring; the rock formations are unlike anything else on the island. Genuinely wild — no facilities at the trailhead.',
    hours: 'Accessible year-round; best avoided in July–August midday heat',
    tip: 'Wear shoes that can get wet — the river crossings are unavoidable and the rocks are slippery. Start by 08:00 in summer. The gorge is completely shaded until mid-morning, which makes it one of the best summer walks on the island.',
    type: 'Limestone canyon trail — 3km return',
  },

  {
    id: 16,
    nbhd: 'akamas',
    name: 'Baths of Aphrodite',
    cat: 'heritage',
    emoji: '💧',
    address: 'Akamas Peninsula, Latsi, 8840 Paphos',
    lat: 35.0519, lng: 32.2772,
    phone: '+357 2632 2841',
    website: 'https://www.visitcyprus.com/index.php/en/discovercyprus/nature/trails/item/304-aphrodite-trail',
    search: 'Baths of Aphrodite Akamas Cyprus fig tree grotto legend freshwater pool',
    note: 'A freshwater grotto beneath a centuries-old fig tree at the northern tip of the Akamas peninsula, where mythology places the bathing pool of Aphrodite and her tryst with Adonis. The site itself is modest — a shaded pool fed by a spring — but the setting and the short walk from the car park through the coastal scrubland are genuinely beautiful. The Aphrodite Nature Trail begins here and continues 7.5km through the Akamas into the peninsula interior. Even the 15-minute return walk to the grotto is worth making.',
    hours: 'Open daily — no entry fee',
    tip: 'Walk the first kilometre of the Aphrodite Trail beyond the grotto — the coastal view back over the Latsi bay and toward the Troodos is the best angle on western Cyprus you will find without a boat. Return to Latsi harbour for lunch afterward.',
    type: 'Mythological site — freshwater grotto and nature trail',
  },

  {
    id: 17,
    nbhd: 'akamas',
    name: 'Akamas National Forest Park',
    cat: 'hike',
    emoji: '🦎',
    address: 'Akamas Peninsula, Northwest Cyprus',
    lat: 35.0333, lng: 32.3000,
    phone: '',
    website: 'https://www.visitcyprus.com/index.php/en/discovercyprus/nature/natural-attractions/item/245-the-akamas-peninsula',
    search: 'Akamas Peninsula National Park Cyprus endemic plants sea turtle Loggerhead',
    note: 'Cyprus\'s most important protected landscape — a 230 km² peninsula of Paphos Forest, limestone ridges, sand dune systems and nesting beaches. The coastline here is the most significant nesting site for Loggerhead sea turtles (Caretta caretta) in the eastern Mediterranean; nesting season is June through August. The interior holds 168 endemic plant species found nowhere else. Rough tracks only — 4x4 or guided jeep tours are the practical way to reach the interior beaches including Lara Bay.',
    hours: 'Open access — no facilities in the interior',
    tip: 'The sea turtle nesting beaches at Lara Bay are accessible only by 4x4 or boat. If visiting in nesting season, stay on designated paths and do not approach the marked nest sites. The Cyprus Department of Forests runs guided conservation tours in summer.',
    type: 'National Park — wildlife reserve and wilderness coast',
  },

  {
    id: 18,
    nbhd: 'akamas',
    name: 'Tzelefos Medieval Bridge',
    cat: 'hike',
    emoji: '🌉',
    address: 'Diarizos Valley, Paphos Forest',
    lat: 34.9200, lng: 32.6650,
    phone: '',
    website: 'https://www.visitcyprus.com/index.php/en/discovercyprus/nature/trails/item/308-tzelefos-bridge-trail',
    search: 'Tzelefos Bridge Venetian medieval Cyprus Diarizos Valley stone arch',
    note: 'The largest of the Venetian-era bridges in Cyprus, spanning the Diarizos river in the pine-forested foothills of the Paphos Forest. Built in the 15th century to carry the camel-route carrying copper ore and salt between the coast and the mountain mining regions, the bridge has a single arch of 7 metres and still sits perfectly in the river. The 2km return trail follows the river bank through plane trees and wild oleander. Completely uncrowded.',
    hours: 'Open access — no facilities',
    tip: 'The riverside trail in either direction from the bridge is worth extending — the Diarizos valley is one of the least-visited green valleys in the Paphos district. Swim in the river pool below the arch if the water is flowing.',
    type: 'Medieval Venetian bridge — forest trail',
  },

  {
    id: 19,
    nbhd: 'akamas',
    name: 'Elias Medieval Bridge',
    cat: 'hike',
    emoji: '🌿',
    address: 'Paphos Forest — near Agios Nikolaos village',
    lat: 34.9450, lng: 32.6780,
    phone: '',
    website: 'https://www.visitcyprus.com/index.php/en/discovercyprus/culture/monuments/item/246-elias-bridge',
    search: 'Elias Bridge Venetian Cyprus Paphos Forest medieval stone arch trail',
    note: 'A smaller and more intimate Venetian bridge than the Tzelefos, set in a narrow ravine of the upper Diarizos tributaries. The bridge dates from the same 15th-century network and is less visited, which gives it a genuinely untouched quality. The approach involves a short walk through dense Paphos Forest on a track that closes to cars 500 metres from the bridge. Combine with the Tzelefos on the same afternoon — they are 3km apart along the valley.',
    hours: 'Open access — dirt track from Agios Nikolaos village',
    tip: 'The upper Diarizos valley in early spring is carpeted with anemones. If you are here between February and April, this is one of the most quietly beautiful drives in Cyprus.',
    type: 'Medieval Venetian bridge — forest valley',
  },

  {
    id: 20,
    nbhd: 'akamas',
    name: 'Revecca Winery',
    cat: 'dining',
    emoji: '🍇',
    address: 'Stroumbi Village, Paphos District',
    lat: 34.8620, lng: 32.5750,
    phone: '+357 2696 2100',
    website: 'https://www.reveccawinery.com',
    search: 'Revecca Winery Stroumbi Paphos Cyprus wine tasting Xynisteri Maratheftiko',
    note: 'One of the newer boutique wineries in the Paphos wine region, working with indigenous Cypriot grape varieties including Xynisteri (white) and Maratheftiko (red) — the two grapes that define what Cypriot wine tastes like when made well. The winery is housed in a converted stone building in Stroumbi village and offers structured tastings with the winemaker. The Xynisteri here has the mineral quality of the limestone plateau soils; the Maratheftiko is smoother than most examples you will find in a restaurant.',
    hours: 'Mon–Sat 10:00–18:00 — tasting by appointment preferred',
    tip: 'Book the winemaker tasting rather than the standard visit — the additional 45 minutes of context changes how you taste everything afterward. Ask about Commandaria if you want to understand the island\'s oldest wine.',
    type: 'Boutique winery — indigenous Cypriot varieties',
  },

  {
    id: 21,
    nbhd: 'akamas',
    name: 'Koullas Sandwiches',
    cat: 'dining',
    emoji: '🥙',
    address: 'Pomos Village, Paphos District (45 minutes north)',
    lat: 35.0536, lng: 32.5833,
    phone: '',
    website: '',
    search: 'Koullas Sandwiches Pomos village Cyprus legendary halloumi lunch',
    note: 'A village sandwich shop in Pomos that has acquired a cult following among Cypriots who make the drive north specifically for it — the equivalent of a pilgrimage for a souvlaki. The menu is minimal: grilled halloumi, local sausage (loukanika), fresh tomato and the village bread made that morning. No tables; eat standing or in the car. The 45-minute drive from Paphos through the Chrysochou valley and along the wild north coast is half the point — the Pomos coastline is completely undeveloped and the drive is one of the most beautiful on the island.',
    hours: 'Morning to early afternoon — closes when the bread runs out',
    tip: 'Call ahead if possible — the shop is genuinely small and sometimes closed for family reasons. This is a local institution, not a tourist restaurant: treat it accordingly.',
    type: 'Village sandwich shop — legendary local institution',
  },

  // ── TROODOS — Mountain Heart ──────────────────────────────────────────────

  {
    id: 22,
    nbhd: 'troodos',
    name: 'Asinou Church (Panagia Forviotissa)',
    cat: 'church',
    emoji: '⛪',
    address: 'Near Nikitari Village, Nicosia District',
    lat: 34.9944, lng: 32.9367,
    phone: '+357 9961 4562',
    website: 'https://www.visitcyprus.com/index.php/en/discovercyprus/culture/sites/item/287-church-of-panagia-forviotissa-asinou',
    search: 'Asinou Church Panagia Forviotissa UNESCO Byzantine fresco Cyprus',
    note: 'The finest Byzantine church interior in Cyprus and one of the most important in the eastern Mediterranean. Built in 1105–06 and subsequently expanded, Asinou contains a near-complete cycle of Byzantine frescoes spanning five centuries of painting from the 12th to 17th century — a compressed history of Byzantine art on a single set of walls. The oldest layers include some of the finest Comnenian-period painting outside Constantinople. The church is tiny — barely 12 metres long — which means the frescoes, covering every centimetre of wall and vault, press close at every turn. Listed as one of 10 churches in the UNESCO-designated Painted Churches of the Troodos Region (inscribed 1985), which UNESCO describes as providing \'an overview of Byzantine and post-Byzantine painting in Cyprus over a period of 500 years.\'',
    hours: 'Daily 09:30–13:00 and 14:00–16:30. Key held by the local priest — call ahead.',
    tip: 'The priest who keeps the key is hospitable and will explain the fresco cycles in Greek or English if you ask. Allow 45 minutes inside — rushing misses the layering. The drive through the Troodos foothills to reach Asinou is itself worth the hour from Paphos.',
    type: 'UNESCO Byzantine church — 12th–17th century frescoes',
    awards: 'UNESCO World Heritage Site — Painted Churches of the Troodos Region, inscribed 1985',
  },

  {
    id: 23,
    nbhd: 'troodos',
    name: 'St Nicholas of the Roof (Agios Nikolaos tis Stegis)',
    cat: 'church',
    emoji: '🏔️',
    address: 'Near Kakopetria Village, Nicosia District',
    lat: 34.9578, lng: 32.9033,
    phone: '+357 2292 2460',
    website: 'https://www.visitcyprus.com/index.php/en/discovercyprus/culture/sites/item/289-church-of-agios-nikolaos-tis-stegis',
    search: 'Agios Nikolaos tis Stegis Kakopetria Byzantine UNESCO Cyprus fresco church',
    note: 'Named for its distinctive pitched wooden roof built over the original Byzantine dome in the 13th century to protect it from snow — a purely functional adaptation that gives the church its entirely unusual profile. Inside, Byzantine frescoes from the 11th to the 17th century cover all surfaces, including a rare 11th-century Transfiguration scene that predates most surviving Comnenian examples. The setting in a pine and plane-tree valley above Kakopetria is as striking as the church itself. UNESCO World Heritage Site.',
    hours: 'Tue–Sun 09:00–13:00 and 14:00–16:00 (winter); until 18:00 (summer)',
    tip: 'The village of Kakopetria 4km below is a good base for the Troodos churches — old stone mill houses converted to guesthouses, and a good trout restaurant by the river. Combine Agios Nikolaos with Asinou for a full day of UNESCO frescoes.',
    type: 'UNESCO Byzantine church — 11th–17th century frescoes',
    awards: 'UNESCO World Heritage Site — Painted Churches of the Troodos Region, inscribed 1985',
  },

  {
    id: 24,
    nbhd: 'troodos',
    name: 'St John Lampadistis Monastery',
    cat: 'church',
    emoji: '✝️',
    address: 'Kalopanagiotis Village, Nicosia District',
    lat: 34.9947, lng: 32.8086,
    phone: '+357 2295 2060',
    website: 'https://www.visitcyprus.com/index.php/en/discovercyprus/culture/sites/item/290-monastery-of-agios-ioannis-lampadistis',
    search: 'St John Lampadistis Kalopanagiotis monastery UNESCO Cyprus Byzantine Latin',
    note: 'A monastery complex containing three interconnected churches from different centuries — a rare architectural palimpsest that makes this one of the most layered sacred sites in Cyprus. The 11th-century Byzantine church, the 13th-century chapel of St Herakleidios, and the 15th-century Latin chapel (built for Catholic Lusignan pilgrims who came to venerate the Orthodox saint) sit under one roof, each with a distinct fresco tradition. The Latin chapel contains Italo-Byzantine frescoes that show the moment when eastern and western medieval painting were trying to understand each other. UNESCO World Heritage Site.',
    hours: 'Daily 09:00–13:00 and 14:00–16:30',
    tip: 'Ask the monk or caretaker to show you the Latin chapel separately — it is sometimes kept locked and the frescoes inside are the strangest and most fascinating in the complex. Kalopanagiotis village below has a good walnut-raki distillery.',
    type: 'UNESCO monastery complex — three churches, three centuries',
    awards: 'UNESCO World Heritage Site — Painted Churches of the Troodos Region, inscribed 1985',
  },

  {
    id: 25,
    nbhd: 'troodos',
    name: 'Kykkos Monastery',
    cat: 'church',
    emoji: '🛕',
    address: 'Kykkos, Troodos Mountains, Paphos District',
    lat: 34.9844, lng: 32.7378,
    phone: '+357 2294 2736',
    website: 'https://www.ikykkos.com',
    search: 'Kykkos Monastery Cyprus Byzantine icon Virgin Mary Makarios Troodos',
    note: 'The wealthiest and most influential monastery in Cyprus, founded in the 11th century and rebuilt after successive fires in its current form in the 19th–20th centuries. The monastery holds the most venerated icon in Cyprus: the Virgin Mary painted, by tradition, by St Luke, and kept permanently covered — it has not been seen by human eyes since 980 AD by decree. The treasury museum houses one of the finest collections of Byzantine ecclesiastical objects in the region. Archbishop Makarios III, the first President of Cyprus, is buried at the Throni hilltop shrine above the monastery.',
    hours: 'Daily 10:00–18:00 (summer), 10:00–16:00 (winter). Dress code: covered shoulders and knees.',
    tip: 'The monastery itself is 19th-century reconstruction — go for the icon tradition, the treasury museum, and the mountain setting, not for ancient architecture. Walk the 3km to Throni hilltop for the Makarios tomb and a view across the entire western Troodos range.',
    type: 'Active monastery — icon of the Virgin Mary',
    awards: 'Active monastery — significant national and religious institution',
  },

  {
    id: 26,
    nbhd: 'troodos',
    name: 'Millomeris Waterfall',
    cat: 'hike',
    emoji: '💦',
    address: 'Near Pano Platres, Limassol District',
    lat: 34.8794, lng: 32.8611,
    phone: '',
    website: 'https://www.visitcyprus.com/index.php/en/discovercyprus/nature/trails/item/309-millomeris-waterfall-trail',
    search: 'Millomeris Waterfall Pano Platres Cyprus highest waterfall hike Troodos',
    note: 'Cyprus\'s highest waterfall at 15 metres, dropping into a wooded gorge of eastern Troodos cedars, plane trees and strawberry trees. The 2km circular trail from Pano Platres village descends through dense forest to the falls — the walk down is easy; the return requires some climbing. In winter and early spring the waterfall runs at full volume; by July it reduces but does not stop entirely. The gorge itself remains cool and shaded even in summer.',
    hours: 'Open access — trailhead in Pano Platres village',
    tip: 'The Platres village square has good kafeneions for coffee and the local commandaria honey cake before or after the walk. Combine with Kalidonia Falls 3km further along the same trail network.',
    type: 'Waterfall trail — 2km circular, 15m falls',
  },

  {
    id: 27,
    nbhd: 'troodos',
    name: 'Kalidonia Falls',
    cat: 'hike',
    emoji: '🌊',
    address: 'Caledonia Trail, Pano Platres, Limassol District',
    lat: 34.8933, lng: 32.8597,
    phone: '',
    website: 'https://www.visitcyprus.com/index.php/en/discovercyprus/nature/trails/item/310-caledonia-trail',
    search: 'Kalidonia Falls Caledonia Trail Platres Cyprus waterfall hike forest stream',
    note: 'A 3km linear trail through the Kryos Potamos river gorge, descending from the presidential summer residence above Platres to the village below through a sequence of river crossings and pine and plane forest. The path passes the 12-metre Kalidonia Falls at the midpoint — the best waterfall setting in the Troodos in terms of the surrounding woodland. Named by Scottish foresters who planted the cedars here in the 19th century and found it reminded them of home. The trail is mostly downhill from top to bottom — arrange a car at each end.',
    hours: 'Open access — best spring through early summer',
    tip: 'Start at the top (by the Troodos Platres presidential residence) and walk down to Platres village — the trail is far more enjoyable in descent. The river crossings require stepping stones; passable in ordinary trainers in summer.',
    type: 'Forest waterfall trail — 3km linear descent',
  },

  {
    id: 28,
    nbhd: 'troodos',
    name: 'Chantara Waterfalls',
    cat: 'hike',
    emoji: '🍃',
    address: 'Cedar Valley, Near Stavros tis Psokas, Paphos Forest',
    lat: 34.9450, lng: 32.7380,
    phone: '',
    website: 'https://www.visitcyprus.com/index.php/en/discovercyprus/nature/natural-attractions/item/249-cedar-valley',
    search: 'Chantara Waterfalls Cedar Valley Cyprus mouflon waterfall Paphos Forest',
    note: 'A series of small cascades in the Cedar Valley section of Paphos Forest, in the same protected zone as the last wild colony of Cyprus mouflon (wild mountain sheep). The falls themselves are modest compared to Millomeris and Kalidonia, but the Cedar Valley setting — with the endemic Cyprus cedar (Cedrus brevifolia) found nowhere else on earth — is the real reason to come. Mouflon sightings at dusk are genuinely common in the meadow above the falls.',
    hours: 'Open access — Paphos Forest is closed to vehicles in fire season (July–September)',
    tip: 'Stavros tis Psokas forestry station nearby has a small enclosure where rescued mouflon are kept — the best guarantee of a sighting if the wild colony is not visible. The cedar forest walk takes about an hour without rushing.',
    type: 'Waterfall and forest walk — endemic cedars and mouflon',
  },

  {
    id: 29,
    nbhd: 'troodos',
    name: 'Agros Village',
    cat: 'heritage',
    emoji: '🌹',
    address: 'Agros Village, Limassol District',
    lat: 34.9194, lng: 32.8956,
    phone: '',
    website: 'https://www.visitcyprus.com/index.php/en/discovercyprus/culture/villages/item/240-agros',
    search: 'Agros Village Cyprus rose water distillery traditional mountain village',
    note: 'A mountain village at 1000 metres in the eastern Troodos, known throughout Cyprus for its rose-water distillery — the harvest in late April and early May fills the whole valley with scent and the village runs a small but serious rose-petal festival. The Agros Cooperative distillery has operated since 1983 and produces rose water, rose jam, rose liqueur and natural cosmetics from the Damascus rose cultivated on the hillside terraces above the village. The traditional stone architecture is almost entirely intact.',
    hours: 'Village accessible year-round; distillery open daily in season',
    tip: 'If you are there outside rose season, the distillery shop sells the preserved products year-round. The village church of the Archangel Michael has a carved wooden iconostasis of unusual quality. The drive from Platres through the valley takes 30 minutes.',
    type: 'Mountain village — rose distillery and traditional crafts',
  },

  {
    id: 30,
    nbhd: 'troodos',
    name: 'Vlassides Winery',
    cat: 'dining',
    emoji: '🍾',
    address: 'Kilani Village, Limassol District',
    lat: 34.8050, lng: 32.9450,
    phone: '+357 2547 0044',
    website: 'https://www.vlassides.com',
    search: 'Vlassides Winery Cyprus boutique Shiraz Xynisteri Kilani wine tasting',
    note: 'The most internationally recognised of the new-generation Cyprus boutique wineries, consistently rated among the top 100 wineries in the world by Decanter. Sophocles Vlassides trained in California and returned to work with both international varieties (Shiraz, Cabernet) and indigenous Cypriot grapes. The Shiraz is the flagship and is genuinely world-class. The winery is in Kilani village in the Troodos foothills — a functioning estate with vines visible from the tasting room. Recent medals: Gold at Concours Mondial de Bruxelles 2025 and Berliner Wein Trophy 2025 both for Artion 2019; three Golds at the Cyprus Wine Competition 2026; multiple Decanter World Wine Awards medals since 2018.',
    hours: 'Mon–Sat 10:00–18:00 — tastings by appointment',
    tip: 'Book the extended tasting with the winemaker if available — Sophocles Vlassides or a senior member of the team usually conducts these personally. The Cabernet-Maratheftiko blend is the most interesting experiment currently in production.',
    type: 'Internationally recognised boutique winery',
    awards: 'Concours Mondial de Bruxelles 2025: Gold (Artion) · Berliner Wein Trophy 2025: Gold (Artion, Óroman) · Cyprus Wine Competition 2026: 3× Gold · Decanter World Wine Awards',
  },

  // ── LEFKARA & VILLAGES — Heritage and Inland ─────────────────────────────

  {
    id: 31,
    nbhd: 'lefkara',
    name: 'Pano Lefkara',
    cat: 'heritage',
    emoji: '🪡',
    address: 'Pano Lefkara Village, Larnaca District',
    lat: 34.8700, lng: 33.3167,
    phone: '',
    website: 'https://lefkara.org',
    search: 'Pano Lefkara lace embroidery Cyprus traditional village UNESCO Leonardo da Vinci',
    note: 'The most celebrated craft village in Cyprus — known for lefkaritika lace embroidery, a tradition of hand-stitched geometric patterns on linen that has been practiced here for over five centuries. Leonardo da Vinci is recorded as having visited and purchased lefkaritika cloth for Milan Cathedral in 1481. The craft is listed on UNESCO\'s Intangible Cultural Heritage list. The village itself is one of the most architecturally preserved in Cyprus — carved stone facades, cobbled alleys, and carved wooden doors. The Lefkara silversmithing tradition runs in parallel to the lace: small workshops still produce the geometric filigree work that was this village\'s second export.',
    hours: 'Village always accessible; lace workshops typically open 09:00–17:00',
    tip: 'Walk past the tourist shops on the main lane and find the elderly women working in doorways in the side alleys — these are the actual practitioners, and they are genuinely hospitable if you stop to watch. Buy directly from a maker rather than the commercial shops at the village entrance.',
    type: 'UNESCO Intangible Heritage — lace-making village',
    awards: 'UNESCO Intangible Cultural Heritage — Lefkaritika lace embroidery, inscribed 2009',
  },

  {
    id: 32,
    nbhd: 'lefkara',
    name: 'Omodos Village',
    cat: 'heritage',
    emoji: '🍷',
    address: 'Omodos Village, Limassol District',
    lat: 34.8444, lng: 32.8067,
    phone: '',
    website: 'https://www.visitcyprus.com/index.php/en/discovercyprus/culture/villages/item/241-omodos',
    search: 'Omodos village Cyprus wine cobblestones Timios Stavros monastery traditional',
    note: 'A wine village in the Commandaria wine region at the southern edge of the Troodos, known for the Monastery of Timios Stavros (Holy Cross) in its central square — founded in the 8th century and holding relics of the True Cross by tradition. The village is one of the best preserved traditional settlements in Cyprus: cobblestone alleys, stone-arched houses, and wine cellars. Commandaria, the world\'s oldest named wine (documented since 800 BC), is produced in this region. The village square in the evening is one of the more civilised places on the island to drink a glass of local wine.',
    hours: 'Village and monastery accessible daily',
    tip: 'The monastery museum has a good collection of ecclesiastical embroidery and old maps. For Commandaria, ask the wine shops around the square for a tasting — several are run by families producing it traditionally on a small scale.',
    type: 'Traditional wine village — Commandaria region',
  },

  {
    id: 33,
    nbhd: 'lefkara',
    name: 'Timios Stavros Monastery, Omodos',
    cat: 'church',
    emoji: '⛪',
    address: 'Central Square, Omodos Village, Limassol District',
    lat: 34.8445, lng: 32.8068,
    phone: '+357 2594 2423',
    website: 'https://www.visitcyprus.com/index.php/en/discovercyprus/culture/sites/item/292-monastery-of-timiou-stavrou',
    search: 'Timios Stavros Monastery Omodos Cyprus Holy Cross relic Byzantine',
    note: 'An active monastery occupying the entire central square of Omodos village — the most visually striking integration of religious and civic space in Cyprus. Founded in the 8th century according to tradition; the current buildings mostly 19th century. The monastery holds relics described as fragments of the True Cross and the rope used at the Crucifixion, housed in ornate reliquaries in the church. The small museum attached to the monastery displays these objects and a collection of ecclesiastical embroidery and manuscripts. The Omodos cultural festival takes place in the monastery courtyard each August.',
    hours: 'Daily 10:00–12:30 and 14:00–18:00',
    tip: 'The monastery church itself is darker and quieter than most tourist sites on the island — a genuinely functional religious space. The museum keeps the same hours as the church and is included in the same free entry.',
    type: 'Active monastery — 8th-century foundation, Holy Cross relics',
  },

  {
    id: 34,
    nbhd: 'lefkara',
    name: 'Karseras Winery',
    cat: 'dining',
    emoji: '🌿',
    address: 'Koilani Village, Limassol District',
    lat: 34.8100, lng: 32.9200,
    phone: '+357 2533 4340',
    website: 'https://www.karseras.com',
    search: 'Karseras Winery Koilani Cyprus indigenous varieties natural wine tasting',
    note: 'A small family winery in Koilani village working exclusively with native Cypriot grape varieties — Maratheftiko, Xynisteri, Promara and Spourtiko — that most producers had abandoned in favour of international varieties. The winery is explicitly a conservation project as much as a commercial one: the old family vines on the limestone hillside are some of the oldest ungrafted vineyards in Cyprus. The tasting is informal and usually conducted by a family member. The Maratheftiko is structured differently from other examples — higher tannin, longer on the finish, and made for ageing.',
    hours: 'Mon–Sat 10:00–17:00 — call ahead to confirm',
    tip: 'The Koilani village kafeneion next door to the winery is run by the same extended family. Lunch before the tasting is the local approach. Ask about the old-vine Spourtiko — it is rarely bottled as a single variety and is unusual.',
    type: 'Family winery — indigenous Cypriot variety conservation',
  },

  {
    id: 35,
    nbhd: 'lefkara',
    name: 'Sanctuary of Aphrodite Trail, Lefkara',
    cat: 'hike',
    emoji: '🦋',
    address: 'E4 European Trail, Lefkara Hills, Larnaca District',
    lat: 34.8650, lng: 33.2900,
    phone: '',
    website: 'https://www.visitcyprus.com/index.php/en/discovercyprus/nature/trails/item/311-aphrodite-cultural-trail',
    search: 'Lefkara hills walking trail Cyprus countryside wildflowers limestone E4',
    note: 'The E4 European long-distance trail passes through the Lefkara hills on its path across Cyprus — the section between Pano Lefkara and the Commandaria wine villages to the west is the most varied and least-walked stretch on the island. Rolling limestone hills, abandoned terraced vineyards, small stone chapels and panoramic views south to the coast and north to the Troodos. Wildflowers in spring include endemic Cypriot tulip, cyclamen and orchid species. A half-day walk (5–7km) can be done as an out-and-back from Lefkara village.',
    hours: 'Open access — best March to May, October to November',
    tip: 'Download the CY Trails app (Cyprus Trails — free) for offline waypointing before setting out. The E4 signage is inconsistent in places. Carry water — no facilities on the hillside route.',
    type: 'Long-distance trail — E4 European walking route',
  },

];
