// A Perfect Day — Ludara / Nashville
// data.js — curated places (updated May 2026)
//
// Sources: Hotel staff recommendations, TimeOut Nashville, The Infatuation,
//          Resy, Nashville Guru, Nashville Scene, Nashville Lifestyles,
//          Nashvegas.com, Visit Nashville.
//
// All hours, addresses and GPS coordinates verified May 2026.
//
// Categories (new system):
//   breakfast | lunch | dinner | bbq | bar | music | attraction | shopping | boots | parks
//
// Neighbourhoods:
//   downtown / germantown / gulch / east / 12south / midtown / parks

const PLACES = [

  // ─── DOWNTOWN / SOBRO / BROADWAY ─────────────────────────────────────

  {
    id: 1,
    nbhd: "downtown",
    name: "Ryman Auditorium",
    cat: "attraction",
    emoji: "🎭",
    address: "116 Rep. John Lewis Way N, Downtown",
    lat: 36.1612,
    lng: -86.7785,
    search: "Ryman Auditorium Nashville",
    note: "Built in 1892 as a gospel tabernacle, the Ryman became home of the Grand Ole Opry from 1943 to 1974 and is now recognised as one of the most acoustically perfect concert venues in America. Daytime tours open the sanctuary, backstage corridors, and the very dressing rooms where Hank Williams and Patsy Cline prepared to perform. The wooden pews, stained-glass windows, and cathedral quiet make it feel sacred even when the stage is empty.",
    hours: "Daily 09:00–16:00",
    tip: "Book the backstage tour in advance — it sells out. The self-guided tour includes a photo opportunity on the famous stage.",
    type: "Historic Music Venue & Museum",
    blog: "", 
    phone: "+1 615-889-3060", 
    website: "https://www.ryman.com", 
  },

  {
    id: 2,
    nbhd: "downtown",
    name: "Country Music Hall of Fame & Museum",
    cat: "attraction",
    emoji: "🎵",
    address: "222 Rep. John Lewis Way S, Downtown",
    lat: 36.158263,
    lng: -86.776126,
    search: "Country Music Hall of Fame Nashville",
    note: "The permanent collection traces country music's roots from its Appalachian folk origins through the outlaw movement, the stadium era, and the genre's contemporary diversity — told through instruments, stage costumes, rare recordings, and the Hall of Fame rotunda where each inductee's medallion lines the curved wall. Nashvegas: 'The Hall of Fame rotunda is genuinely moving in a way that's hard to explain and easy to experience.' Recent exhibitions have covered Dolly Parton's complete archive and Johnny Cash's visual art. Allow at least three hours. Discounted tickets available at the Holston House Front Desk.",
    hours: "Daily 09:00–17:00",
    tip: "Combination tickets with RCA Studio B on Music Row offer the best value in Nashville music tourism. Book Studio B in advance — tours are limited in size.",
    type: "Music History Museum",
    blog: "", 
    phone: "+1 615-416-2001", 
    website: "https://www.countrymusichalloffame.org", 
  },

  {
    id: 3,
    nbhd: "downtown",
    name: "National Museum of African American Music",
    cat: "attraction",
    emoji: "🥁",
    address: "510 Broadway, Downtown",
    lat: 36.1606,
    lng: -86.7789,
    search: "National Museum of African American Music Nashville",
    note: "The only museum in the United States dedicated to preserving and celebrating the genres created, influenced, and inspired by African Americans — blues, jazz, gospel, R&B, soul, and hip-hop. Six immersive galleries trace over 50 musical styles through artefacts, documentary film, and interactive technology. The RiSE experience lets visitors add their own voice to the story. Quietly one of the most moving stops in all of Nashville, and persistently overlooked in favour of louder attractions nearby.",
    hours: "Mon 12:00–17:00; Tue–Sat 10:00–17:00; Sun 12:00–17:00",
    tip: "Allow two full hours. The RiSE experience is included in admission and is genuinely powerful — do not skip it.",
    type: "Cultural & Music Museum",
    blog: "", 
    phone: "+1 615-301-8724", 
    website: "https://nmaam.org", 
  },

  {
    id: 4,
    nbhd: "downtown",
    name: "Hatch Show Print",
    cat: "attraction",
    emoji: "🖨️",
    address: "224 Rep. John Lewis Way S, Downtown",
    lat: 36.157755,
    lng: -86.776395,
    search: "Hatch Show Print Nashville",
    note: "One of the oldest continuously operating letterpress print shops in America, founded in 1879. The workshop designed iconic concert posters for the Grand Ole Opry, the Ryman, and virtually every major country artist of the 20th century. You can watch printers pulling runs on century-old presses, browse the archive of original designs, and buy freshly printed posters — made minutes before you arrived. A working museum of Nashville's visual and musical heritage.",
    hours: "Daily 09:00–17:00",
    tip: "Browse the poster bins — vintage show reprints often sell for well under $30. The best souvenir in Nashville.",
    type: "Historic Letterpress Workshop",
    blog: "", 
    phone: "+1 615-577-7710",
    website: "https://hatchshowprint.com", 
  },

  {
    id: 5,
    nbhd: "downtown",
    name: "Tootsie's Orchid Lounge",
    cat: "bar",
    emoji: "🎸",
    address: "422 Broadway, Downtown",
    lat: 36.160902,
    lng: -86.778292,
    search: "Tootsies Orchid Lounge Nashville Broadway honky tonk historic",
    note: "Since 1960, when Hattie Louise 'Tootsie' Bess purchased the bar, Tootsie's remains Nashville's go-to destination for locals and visitors alike. Tootsie's has more music history per square inch than anywhere else in Music City. Fun fact: Willie Nelson got his first songwriting job after performing at Tootsie's.",
    hours: "Daily 09:30–03:00",
    tip: "A Holston House staff pick — Daniel. Go upstairs for a slightly quieter experience with a view down Broadway. Weekday afternoons are the best time to actually hear the musicians.",
    type: "Historic Honky-Tonk",
    blog: "", 
    phone: "+1 615-726-0463", 
    website: "https://tootsies.net", 
  },

  {
    id: 6,
    nbhd: "downtown",
    name: "Robert's Western World",
    cat: "bar",
    emoji: "🤠",
    address: "416 Broadway, Downtown",
    lat: 36.160987,
    lng: -86.778046,
    search: "Roberts Western World Nashville classic country rockabilly Broadway bar",
    note: "Famous for their Fried Bologna sandwich, cold beer, and country music, this is the quintessential Nashville honky tonk.",
    hours: "Daily 11:00–03:00",
    tip: "A Holston House staff pick — Phillip. The Recession Special ($10) is a Nashville institution: burger, bag of chips, a Moon Pie, and a PBR. Exactly what it sounds like — and exactly what you want.",
    type: "Classic Honky-Tonk",
    blog: "", 
    phone: "+1 615-244-9552", 
    website: "https://robertswesternworld.com", 
  },

  {
    id: 7,
    nbhd: "downtown",
    name: "Crema Coffee Roasters",
    cat: "breakfast",
    emoji: "☕",
    address: "15 Hermitage Ave, SoBro",
    lat: 36.1568,
    lng: -86.7697,
    search: "Crema Coffee Roasters Nashville SoBro specialty coffee",
    note: "The SoBro location has a large working space and a wooden loft patio facing the street. The drip coffee is the smoothest in the city; specialty drinks are interesting without masking the beans. They hold regular coffee classes in the back room and operate a zero-waste commitment. An institution that has earned its reputation every morning since 2009.",
    hours: "Mon–Fri 06:30–18:00; Sat 07:00–18:00; Sun 07:00–16:00",
    tip: "A short walk from Broadway and the Convention Center — the ideal civilised start before the honky-tonks wake up.",
    type: "Specialty Coffee Roastery",
    blog: "", 
    phone: "+1 615-255-8311", 
    website: "https://crema-coffee.com", 
  },

  {
    id: 41,
    nbhd: "downtown",
    name: "The Listening Room Cafe",
    cat: "music",
    emoji: "🎤",
    address: "618 4th Ave S, SoBro",
    lat: 36.1538,
    lng: -86.7722,
    search: "Listening Room Cafe Nashville SoBro songwriter rounds",
    note: "Nashville's most accessible songwriter showcase — a seated, dinner-and-show venue where artists perform round-style: four songwriters sitting in a circle, swapping songs and the stories behind them. This is how Nashville's music industry has worked for generations, and the Listening Room makes it visible and intimate. Performers play originals and explain the compositional choices behind them. No cover bands, no karaoke — just working songwriters revealing how country hits are actually made.",
    hours: "Daily 11:00–23:00 (Sat from 10:00)",
    tip: "Reserve a table — the room fills quickly. The songwriter round format rewards paying close attention; these are the people who actually wrote the hits you recognise.",
    type: "Songwriter Round Venue",
    blog: "", 
    phone: "+1 615-259-3600", 
    website: "https://thelisteningroomcafe.com", 
  },

  {
    id: 42,
    nbhd: "downtown",
    name: "Skull's Rainbow Room",
    cat: "music",
    emoji: "🎷",
    address: "222 Printers Alley, Downtown",
    lat: 36.164578,
    lng: -86.778830,
    search: "Skulls Rainbow Room Printers Alley Nashville jazz burlesque historic",
    note: "Hidden in Printers Alley — Nashville's storied historic nightclub district — Skull's has been operating since 1948 and is among the city's oldest continuously running live music venues. Live jazz plays every night in a room of rich mahogany, red velvet, and low lighting. On Friday and Saturday nights, the room adds a burlesque show that has been a Nashville institution for decades. First Time Visiting calls it 'a one-stop shop: come for a drink, stay for dinner and a nightly show.' Printers Alley is a short walk from Broadway but feels like a different era entirely.",
    hours: "Mon–Sat 17:00–02:00; Sun 10:00–14:00 & 17:00–02:00",
    tip: "Book the dinner-and-show package on Friday or Saturday. Arrive in the alley from Commerce St — the entrance is deliberately understated.",
    type: "Historic Jazz Club & Supper Club",
    blog: "", 
    phone: "+1 615-810-9631", 
    website: "https://skullsrainbowroom.com", 
  },

  {
    id: 45,
    nbhd: "downtown",
    name: "3rd & Lindsley",
    cat: "music",
    emoji: "🎶",
    address: "818 3rd Ave S, SoBro",
    lat: 36.1523,
    lng: -86.7698,
    search: "3rd and Lindsley Nashville SoBro music venue blues Americana roots",
    note: "Nashville's most reliable mid-size music venue for blues, Americana, and roots music — a full restaurant by day that transforms into a serious listening room by night. The programming is eclectic and consistently excellent: national touring acts, local legends, and residency nights that become Nashville events. The sight lines are good, the sound system excellent, and the kitchen serves proper food throughout the evening. A full meal and a great band for significantly less than a Broadway night out.",
    hours: "Mon–Thu 18:00–00:00; Fri–Sat 11:00–14:30 & 18:00–00:00; Sun 17:30–00:00",
    tip: "Check the weekly blues jams and residency nights — that's when the room is best. Tickets are usually $10–$25 and can be bought at the door.",
    type: "Blues & Roots Music Venue",
    blog: "", 
    phone: "+1 615-259-9891", 
    website: "https://3rdandlindsley.com", 
  },

  {
    id: 52,
    nbhd: "downtown",
    name: "Another Broken Egg Cafe",
    cat: "breakfast",
    emoji: "🍳",
    address: "208 Commerce St, Downtown",
    lat: 36.1631,
    lng: -86.7766,
    search: "Another Broken Egg Cafe Nashville",
    note: "A Southern-inspired breakfast and brunch menu featuring crispy chicken and waffles, delectable eggs benedict, savory shrimp and grits, and customizable omelets.",
    hours: "Daily 07:00–14:00",
    tip: "A Holston House staff pick — Isha.",
    type: "Breakfast & Brunch Cafe",
    blog: "", 
    phone: "+1 615-913-3923",
    website: "https://anotherbrokenegg.com", 
  },

  {
    id: 53,
    nbhd: "downtown",
    name: "The Farmhouse",
    cat: "breakfast",
    emoji: "🌽",
    address: "210 Almond St, Downtown",
    lat: 36.158901,
    lng: -86.774923,
    search: "The Farmhouse Restaurant Nashville",
    note: "Southern comfort food with a modern touch — serving premium steaks, house-baked cornbread, locally sourced produce, and craft cocktails inspired by Tennessee flavors.",
    hours: "Mon closed; Tue–Fri 16:00–22:00; Sat 10:00–22:00; Sun 10:00–14:00",
    tip: "A Holston House staff pick — Tori.",
    type: "Southern Comfort Restaurant",
    blog: "", 
    phone: "+1 615-522-0688",
    website: "https://thefarmhousetn.com",
    resUrl: "https://www.opentable.com/r/the-farm-house-nashville",
    direct_image: "https://images.squarespace-cdn.com/content/v1/5e3b0484b754a35dcb40dcfe/6b3283d2-3dbd-4512-8748-984008ec3364/Pork+Belly+Best+Happy-Hour+Nashville.jpg"
  },

  {
    id: 56,
    nbhd: "downtown",
    name: "Blue Sushi Sake Grill",
    cat: "lunch",
    emoji: "🍱",
    address: "501 Broadway (Fifth + Broadway), Downtown",
    lat: 36.160844,
    lng: -86.779919,
    search: "Blue Sushi Sake Grill Nashville",
    note: "Combining bold, sustainable ingredients and an inspired atmosphere to create a memorable Japanese tapas experience in the heart of downtown Nashville.",
    hours: "Mon–Thu 11:00–22:00; Fri–Sat 11:00–23:00; Sun 12:00–21:00",
    tip: "A Holston House staff pick — Isha.",
    type: "Japanese Tapas & Sushi",
    blog: "", 
    phone: "+1 629-226-2583",
    website: "https://bluesushisakegrill.com",
    resUrl: "https://www.opentable.com/r/blue-sushi-sake-grill-fifth-and-broadway-nashville", 
  },

  {
    id: 58,
    nbhd: "downtown",
    name: "Assembly Food Hall",
    cat: "lunch",
    emoji: "🏬",
    address: "501 Broadway (Fifth + Broadway, Level 3), Downtown",
    lat: 36.160981,
    lng: -86.779333,
    search: "Assembly Food Hall Nashville",
    note: "A bustling hub of dining featuring 20 distinct eateries spanning local cuisine to global favorites. Our staff favorites include Radish, Pharmacy Burger, The Liege Waffle Co., and Hattie Jane's Creamery for a sweet treat.",
    hours: "Mon–Wed 08:00–22:00; Thu 08:00–23:00; Fri–Sat 08:00–01:00; Sun 08:00–23:00",
    tip: "A Holston House staff pick — Lesia.",
    type: "Food Hall (20+ Eateries)",
    blog: "", 
    phone: "+1 615-800-5395",
    website: "https://assemblyfoodhall.com",
    direct_image: "https://foodhallco.com/wp-content/uploads/2021/07/Assembly-Food-Hall-Revised-copy.png"
  },

  {
    id: 59,
    nbhd: "downtown",
    name: "Pinewood Social",
    cat: "lunch",
    emoji: "🎳",
    address: "33 Peabody St, SoBro",
    lat: 36.158390,
    lng: -86.767784,
    search: "Pinewood Social Nashville",
    note: "Serving brunch and lunch in a fun setting featuring six vintage bowling lanes, outdoor patio, bocce ball, ping pong, and a pool bar serviced in a vintage Airstream.",
    hours: "Mon–Thu 09:00–22:00; Fri–Sat 09:00–23:00; Sun 09:00–22:00",
    tip: "A Holston House staff pick — Rosario.",
    type: "Restaurant, Bar & Bowling",
    blog: "", 
    phone: "+1 615-751-8111",
    website: "https://pinewoodsocial.com",
    resUrl: "https://www.opentable.com/pinewood-social",
    direct_image: "https://pinewoodsocial.com/cdn/shop/files/10.22.25-pinewoodsocial-8264_4.jpg?v=1764095550"
  },

  {
    id: 60,
    nbhd: "downtown",
    name: "Bourbon Steak",
    cat: "dinner",
    emoji: "🥩",
    address: "201 8th Ave S (JW Marriott, 34th floor), Downtown",
    lat: 36.156644,
    lng: -86.781007,
    search: "Bourbon Steak Nashville",
    note: "Michael Mina's elegant steakhouse situated on top of the 34th floor of the JW Marriott. A traditional menu featuring prime cuts of beef, seafood, and an extensive wine list with breathtaking views of downtown Nashville.",
    hours: "Sun–Thu 17:00–22:00; Fri–Sat 17:00–22:30",
    tip: "A Holston House staff pick — Tori. Reserve well ahead — the city views from floor 34 are spectacular.",
    type: "Michael Mina Steakhouse",
    blog: "", 
    phone: "+1 629-208-8440",
    website: "https://bourbonsteak.com/location/nashville",
    direct_image: "https://nashvillebourbonsteak.com/wp-content/themes/bourbon-steak/assets/img/gallery/bsnnashville.jpg"
  },

  {
    id: 63,
    nbhd: "downtown",
    name: "Eddie V's Prime Seafood",
    cat: "dinner",
    emoji: "🦞",
    address: "590 Broadway, Downtown",
    lat: 36.1601,
    lng: -86.7797,
    search: "Eddie V's Nashville",
    note: "Classical elegance meets Nashville flair — prime steak and seafood in a refined setting. A guest favorite for a special night after a day on Broadway. Enjoy live jazz in the V Lounge while sipping a craft cocktail.",
    hours: "Daily 16:00–22:00",
    tip: "The V Lounge offers live jazz and a quieter setting after an evening on Broadway.",
    type: "Upscale Steak & Seafood",
    blog: "", 
    phone: "+1 615-238-2359",
    website: "https://eddiev.com",
    resUrl: "https://www.opentable.com/r/eddie-vs-nashville",
    direct_image: "https://img.ctykit.com/cdn/tn-nashville/images/tr:w-1800/ev-homepage-golden-nights-hero-1080x1920.png"
  },

  {
    id: 65,
    nbhd: "downtown",
    name: "Martin's Bar-B-Que Joint",
    cat: "bbq",
    emoji: "🐷",
    address: "410 4th Ave S, Downtown",
    lat: 36.156772,
    lng: -86.774038,
    search: "Martin's Bar-B-Que Joint Nashville",
    note: "Since 2006, Martin's has been known throughout the South for their celebration of Tennessee whole hog BBQ — a slow-cooked tradition that defines the region's barbecue culture.",
    hours: "Mon–Wed 11:00–22:00; Thu–Sat 11:00–23:00; Sun 11:00–22:00",
    tip: "A Holston House staff pick — Daniel.",
    type: "Tennessee Whole Hog BBQ",
    blog: "", 
    phone: "+1 615-288-0880",
    website: "https://martinsbbqjoint.com",
    direct_image: "https://images.squarespace-cdn.com/content/v1/63e3d3c41a782b5807a593fc/1679331370148-T0DJEVCNA0SN56D5WTRC/martinsbbq_020722_final_0028.jpg"
  },

  {
    id: 66,
    nbhd: "downtown",
    name: "Red Phone Booth",
    cat: "bar",
    emoji: "📞",
    address: "136 Rosa L. Parks Blvd, Downtown",
    lat: 36.1601,
    lng: -86.7825,
    search: "Red Phone Booth Nashville",
    note: "1920s Speakeasy style cocktail bar, whiskey bar, and cigar lounge — featuring a menu of Neapolitan pizzas and Italian desserts in a beautifully designed underground space.",
    hours: "Mon–Wed & Sun 16:00–00:00; Thu–Sat 16:00–01:00 (confirm before visiting)",
    tip: "⚠️ As of May 2026 this venue is temporarily closed with no confirmed reopen date — confirm with the front desk before visiting. When open: A Holston House staff pick — Phillip.",
    type: "Speakeasy Cocktail & Cigar Lounge",
    blog: "", 
    phone: "+1 629-217-1930",
    website: "https://www.redphonebooth.com/locations/tn/nashville",
    direct_image: "https://popmenucloud.com/cdn-cgi/image/width=600,height=600,fit=scale-down,format=auto,quality=60/tscbiyal/cb986073-9b13-4e12-979f-c7e1e04a4898.png"
  },

  {
    id: 67,
    nbhd: "downtown",
    name: "Bourbon Street Blues and Boogie Bar",
    cat: "bar",
    emoji: "🎷",
    address: "220 Printers Alley, Downtown",
    lat: 36.164453,
    lng: -86.778849,
    search: "Bourbon Street Blues and Boogie Bar Nashville",
    note: "Located in the historic Printers Alley, this beloved spot serves Cajun and Creole eats made from scratch alongside a full bar and live music every day featuring some of Nashville's best local artists.",
    hours: "Mon–Tue 16:00–01:00; Wed–Sun 11:30–03:00",
    tip: "A Holston House staff pick — Tori. Grab an Alligator Po'Boy and enjoy the tunes. Enter Printers Alley from Church St or Commerce St.",
    type: "Live Music Cajun Bar",
    blog: "", 
    phone: "+1 615-242-5837",
    website: "https://bourbonstreetbluesandboogiebar.com",
    direct_image: "https://www.bourbonstreetbluesandboogiebar.com/slir/w1920/uploaded/banners/Ban_11.jpg"
  },

  {
    id: 68,
    nbhd: "downtown",
    name: "The Stage on Broadway",
    cat: "bar",
    emoji: "🎵",
    address: "412 Broadway, Downtown",
    lat: 36.160906,
    lng: -86.777846,
    search: "The Stage on Broadway Nashville",
    note: "An iconic honky-tonk bar in the heart of Broadway, known for lively atmosphere and top-notch live music performances featuring a mix of classic and contemporary country hits. Kitchen and bar serve cold drinks and Southern staples.",
    hours: "Daily 10:00–02:30",
    tip: "A Holston House staff pick — Phillip.",
    type: "Broadway Honky-Tonk",
    blog: "", 
    phone: "+1 615-726-0504",
    website: "https://thestageonbroadway.com",
    direct_image: "https://wst-media.sfo2.digitaloceanspaces.com/TheStage/wp-content/uploads/2025/03/22174548/MainFloor.jpg"
  },

  {
    id: 70,
    nbhd: "downtown",
    name: "Nashville Old Town Trolley Tours",
    cat: "attraction",
    emoji: "🚃",
    address: "201 Broadway, Downtown (boarding stop)",
    lat: 36.161682,
    lng: -86.775163,
    search: "Nashville Old Town Trolley Tour",
    note: "The easiest way to get a feel for Nashville's geography and history in a single outing. A hop-on, hop-off loop with 13 stops covering downtown, Music Row, Germantown, and The Gulch. Your ticket is valid all day. Live narration covers everything from the city's Civil War history to its rise as a music capital. The full loop takes about 90 minutes without stopping.",
    hours: "Daily 09:30–16:00 (closed select holidays)",
    tip: "Discounted tickets available at the Holston House Front Desk. Book online on busy weekends.",
    type: "Hop-On Hop-Off City Tour",
    blog: "", 
    phone: "+1 629-208-0200", 
    website: "https://www.trolleytours.com/nashville",
    direct_image: "https://www.historictours.com/wp-content/uploads/2023/08/OTT-nashville-tour.jpg"
  },

  {
    id: 71,
    nbhd: "downtown",
    name: "The Johnny Cash Museum",
    cat: "attraction",
    emoji: "🎸",
    address: "119 3rd Ave S, Downtown",
    lat: 36.1608,
    lng: -86.7759,
    search: "Johnny Cash Museum Nashville",
    note: "The most carefully curated music museum in Nashville, holding the largest collection of Cash artifacts in the world — personal letters, stage costumes, instruments, rare photographs, and footage from across his six-decade career. A serious tribute, not a souvenir shop with a backstory. Plan at least 90 minutes; most visitors linger longer.",
    hours: "Daily 09:00–19:00",
    tip: "Book tickets online to avoid the line on busy afternoons. The Unearthed Exhibit in the lower level is worth the extra time.",
    type: "Music Heritage Museum",
    blog: "", 
    phone: "+1 615-256-1777", 
    website: "https://www.johnnycashmuseum.com", 
  },

  {
    id: 73,
    nbhd: "downtown",
    name: "Fifth + Broadway",
    cat: "shopping",
    emoji: "🏬",
    address: "501 Broadway, Downtown",
    lat: 36.160514,
    lng: -86.779751,
    search: "Fifth and Broadway Nashville",
    note: "Nashville's largest mixed-use retail and dining complex, opened in 2021 at the corner of 5th and Broadway. Five floors hold over 20 retailers, more than 30 food and drink options in the Assembly Food Hall, and rooftop bars with views of downtown. Far better executed than most developments of this scale. One block from Broadway's honky-tonk strip — a natural stopping point before or after an evening out.",
    hours: "Mon–Sat 10:00–21:00; Sun 11:00–19:00",
    tip: "On-site parking garage. Assembly Food Hall on the upper floors is worth a visit even without shopping.",
    type: "Mixed-Use Retail & Dining Complex",
    blog: "", 
    phone: "+1 615-416-6400", 
    website: "https://fifthandb.com", 
  },

  {
    id: 74,
    nbhd: "downtown",
    name: "Boot Country",
    cat: "boots",
    emoji: "👢",
    address: "304 Broadway, Downtown",
    lat: 36.161638,
    lng: -86.776390,
    search: "Boot Country Nashville Broadway",
    note: "One of the anchor boot stores on Lower Broadway, stocking over 20,000 pairs of cowboy boots across multiple levels — from entry-level to premium brands. Known for its buy-one-get-two-free deal, which makes it a popular stop for groups outfitting everyone at once. Selection covers men's, women's, and kids's boots, along with hats and western accessories.",
    hours: "Mon–Thu 10:00–22:00; Fri–Sat 10:00–23:00; Sun 10:00–21:00",
    tip: "Great for groups — buy one pair, get two free.",
    type: "Western Boot Store",
    blog: "", 
    phone: "+1 615-259-1691", 
    website: "https://www.twofreeboots.com",
    direct_image: "https://cdn.prod.website-files.com/677bfe1c00799823e221296f/677c0435e18eefb3fa808ef9_home%20hero%20image.avif"
  },

  {
    id: 75,
    nbhd: "downtown",
    name: "Tecovas",
    cat: "boots",
    emoji: "👢",
    address: "501 Broadway (Fifth + Broadway), Downtown",
    lat: 36.160988,
    lng: -86.779235,
    search: "Tecovas Nashville",
    note: "Tecovas brought handmade cowboy boots back to a younger, style-conscious audience — direct-to-consumer, genuinely good leather, and prices that sit between fashion-brand and heritage-maker. The Fifth + Broadway store offers the full range of boots, bags, and western apparel for men and women. If you are buying your first pair of cowboy boots and want something you will actually wear at home, this is the right place to start.",
    hours: "Mon–Sat 10:00–20:00; Sun 11:00–18:00",
    tip: "No-pressure sales approach. Best option for guests new to cowboy boots.",
    type: "Handmade Western Boots & Apparel",
    blog: "", 
    phone: "+1 615-787-8027", 
    website: "https://www.tecovas.com/stores/nashville-tn-broadway",
    direct_image: "https://cdn.sanity.io/images/v8kybopt/production/438edf952cfe721c1bf6ee06c3fa7c1fddd51f06-2500x3125.png?w=1200&fit=max&auto=format"
  },

  {
    id: 76,
    nbhd: "downtown",
    name: "Boot Barn",
    cat: "boots",
    emoji: "👢",
    address: "318 Broadway, Downtown",
    lat: 36.1614,
    lng: -86.7769,
    search: "Boot Barn Nashville Broadway",
    note: "The largest western and workwear retailer in the United States, with one of its flagship stores on Broadway. The selection is extensive: cowboy boots from over a dozen brands including Ariat, Tony Lama, and Lucchese, plus hats, denim, and accessories. Staff can help with sizing — which matters more with cowboy boots than most footwear. On the same block as Boot Country, easy to compare both in one stop.",
    hours: "Mon–Wed 10:00–21:00; Thu–Sat 09:00–22:00; Sun 10:00–20:00",
    tip: "Largest brand selection on Broadway. Good for comparing multiple boot makers.",
    type: "Western & Workwear Chain",
    blog: "", 
    phone: "+1 615-742-9780", 
    website: "https://www.bootbarn.com", 
  },

  {
    id: 77,
    nbhd: "downtown",
    name: "Big Time Boots",
    cat: "boots",
    emoji: "👢",
    address: "410 Broadway, Downtown",
    lat: 36.160950,
    lng: -86.777730,
    search: "Big Time Boots Nashville",
    note: "A locally owned, family-run boot store that has been outfitting Nashville visitors for over 40 years — long before Broadway became what it is today. Claims the largest boot selection in Nashville, with full ranges from Tony Lama, Ariat, Dan Post, and others. Because it is family-owned rather than a chain, staff tend to be more knowledgeable and patient than at the big-box competitors nearby.",
    hours: "Mon–Thu 11:00–20:00; Fri–Sat 11:00–21:00; Sun 11:00–19:00",
    tip: "Family-owned and operated since the 1980s. More personal service than the chain stores.",
    type: "Family-Run Western Boot Store",
    blog: "", 
    phone: "+1 615-254-7797", 
    website: "https://www.trailwestnashville.com/big-time-boots", 
  },

  {
    id: 78,
    nbhd: "downtown",
    name: "Betty Boots",
    cat: "boots",
    emoji: "👢",
    address: "321 Broadway, Downtown",
    lat: 36.1609,
    lng: -86.7766,
    search: "Betty Boots Nashville Broadway",
    note: "Nashville's only all-women's western store — the entire inventory is stocked exclusively for women: cowboy boots in a full range of styles and price points, plus western hats, belts, jewelry, and clothing designed with a female customer in mind rather than adapted from a men's range. Part of the Trail West Nashville family, which also operates Big Time Boots nearby.",
    hours: "Mon–Tue 10:00–20:00; Wed–Sat 10:00–21:00; Sun 11:00–18:00",
    tip: "All-women's selection from boots to accessories. Part of the same family as Big Time Boots.",
    type: "Women's Western Boot & Apparel Store",
    blog: "", 
    phone: "+1 615-736-7698", 
    website: "https://www.trailwestnashville.com/betty-boots", 
  },

  // ─── GERMANTOWN ──────────────────────────────────────────────────────

  {
    id: 8,
    nbhd: "germantown",
    name: "City House",
    cat: "dinner",
    emoji: "🍕",
    address: "1222 4th Ave N, Germantown",
    lat: 36.1769,
    lng: -86.7873,
    search: "City House Nashville Germantown Tandy Wilson James Beard Award restaurant",
    note: "Chef and owner Tandy Wilson was the first Nashville chef to win the James Beard Award for Best Chef Southeast (2016). City House is where that reputation was built: rustic Italian-influenced food with a Southern American character — belly ham pizza, house-made pasta, excellent charcuterie — in a warm, unfussy room inside a converted Victorian building. Sunday Supper is a local institution worth planning around.",
    hours: "Mon–Thu 17:00–21:00; Fri–Sat 17:00–22:00; Sun 17:00–21:00",
    tip: "The belly ham pizza is the cult order. Come for Sunday Supper if you can plan ahead — it has a fiercely loyal local following.",
    type: "James Beard Italian-Southern",
    blog: "", 
    phone: "+1 615-736-5838", 
    website: "https://cityhousenashville.com",
    resUrl: "https://www.opentable.com/r/city-house-nashville", 
  },

  {
    id: 9,
    nbhd: "germantown",
    name: "Rolf & Daughters",
    cat: "dinner",
    emoji: "🍝",
    address: "700 Taylor St, Germantown",
    lat: 36.1776,
    lng: -86.7929,
    search: "Rolf and Daughters Nashville Germantown pasta Philip Krajeck restaurant",
    note: "Located in the historic 100-year-old Werthan Factory building in Germantown. Northern Italian and Mediterranean influences with Southern ingredients to create a dynamic and seasonally driven menu.",
    hours: "Daily 17:00–22:00",
    tip: "A Holston House staff pick — Phillip. Reserve at the communal table or chef's bar if you want a more spontaneous evening — they hold walk-in spots at both.",
    type: "Modern Pasta & Seasonal Cuisine",
    blog: "", 
    phone: "+1 615-866-9897", 
    website: "https://rolfanddaughters.com",
    resUrl: "https://www.opentable.com/r/rolf-and-daughters-nashville", 
  },

  {
    id: 10,
    nbhd: "germantown",
    name: "Henrietta Red",
    cat: "dinner",
    emoji: "🦪",
    address: "1200 4th Ave N, Germantown",
    lat: 36.1761,
    lng: -86.7867,
    search: "Henrietta Red Nashville oyster bar Germantown Julia Sullivan James Beard",
    note: "Chef Julia Sullivan's James Beard–nominated oyster bar has a rotating selection of freshly shucked Gulf and East Coast oysters, a beautiful enclosed patio, and a menu of fresh, seasonal sharing plates. The barroom happy hour is one of the best in Nashville. Weekend brunch draws a neighbourhood crowd that actually lives nearby.",
    hours: "Mon closed; Tue–Fri 17:00–22:00; Sat–Sun 10:00–14:00 & 17:00–22:00",
    tip: "Happy hour (Tue–Fri 5–6:30pm): half-price oysters and craft cocktails at the bar. One of the great-value evenings in Nashville.",
    type: "Oyster Bar & Seasonal Restaurant",
    blog: "", 
    phone: "+1 615-490-8042", 
    website: "https://henriettared.com",
    resUrl: "https://www.opentable.com/r/henrietta-red-nashville-3", 
  },

  {
    id: 11,
    nbhd: "germantown",
    name: "Nashville Farmers' Market",
    cat: "shopping",
    emoji: "🥦",
    address: "900 Rosa L. Parks Blvd, Germantown",
    lat: 36.170718,
    lng: -86.788879,
    search: "Nashville Farmers Market Rosa Parks Boulevard",
    note: "A year-round indoor market at the northern edge of Germantown with a farmers' section selling Tennessee-grown produce and a covered Market House with over two dozen independent food stalls — everything from authentic Vietnamese and Thai to wood-fired pizza and freshly pressed juice. The most honest cross-section of Nashville's eating habits: no marketing, no pretence, good food at fair prices in an open-air setting that rewards wandering. The weekend flea market adds vintage and handmade goods.",
    hours: "Market House daily 08:00–20:00; Farm Sheds Fri–Sun 09:00–14:00",
    tip: "Come Saturday morning for the most active produce market. The weekday lunch crowd in the food hall is excellent and completely unhurried.",
    type: "Indoor Farmers Market & Food Hall",
    blog: "", 
    phone: "+1 615-880-2001", 
    website: "https://nashvillefarmersmarket.org", 
  },

  {
    id: 13,
    nbhd: "germantown",
    name: "Babychan",
    cat: "breakfast",
    emoji: "🍡",
    address: "1313 Adams St, Neuhoff District, Germantown",
    lat: 36.1799,
    lng: -86.7836,
    search: "Babychan Nashville Germantown Japanese bakery cafe Neuhoff",
    note: "From the husband-and-wife team behind Kisser — chefs Brian Lea and Leina Horii — Babychan brings Japanese and French bakery culture to the Neuhoff District in Germantown. The all-day menu runs from technique-driven morning pastries (sesame swiss rolls, yuzu tarts, cinnamon toast on house-baked Japanese milk bread) through katsu sandwiches, curry pan, rice omelettes, and onigiri at lunch, with coffee, tea, sake, and natural wine throughout. The Infatuation calls it 'the Japanese bakery and café Nashville didn't know it desperately needed.' Named Best New Café and Bakery by the Nashville Scene 2025. The grab-and-go counter opens at 8am; full table service from 10am.",
    hours: "Mon & Wed–Sun 08:00–15:00; Tue closed",
    tip: "Come before 9am on weekends to claim a pastry case seat without waiting. The sesame swiss roll and yuzu tart sell out fast — they're worth a pre-order on their website.",
    type: "Japanese Bakery & All-Day Café",
    blog: "", 
    phone: "", 
    website: "https://www.babychancafe.com",
    resUrl: "https://www.opentable.com/r/babychan-nashville", 
  },

  // ─── THE GULCH ───────────────────────────────────────────────────────

  {
    id: 14,
    nbhd: "gulch",
    name: "Frist Art Museum",
    cat: "attraction",
    emoji: "🎨",
    address: "919 Broadway, The Gulch",
    lat: 36.157897,
    lng: -86.783853,
    search: "Frist Art Museum Nashville",
    note: "Nashville's premier art museum occupies a stunning 1933 Art Deco post office — white Georgia marble facade, decorative bronze details, soaring interior ceilings — listed on the National Register of Historic Places. The museum presents major touring exhibitions from world-class collections alongside strong regional programming. The Martin ArtQuest gallery is one of the most inventive hands-on art spaces in the South. Admission is notably reasonable for a museum of this calibre. Complimentary tickets available at the Holston House Front Desk.",
    hours: "Mon 10:00–17:30; Tue–Wed closed; Thu 10:00–20:00; Fri–Sat 10:00–17:30; Sun 13:00–17:30",
    tip: "Thursday evenings offer extended hours and are usually uncrowded. The Art Deco interior is spectacular in late afternoon light.",
    type: "Contemporary Art Museum",
    blog: "", 
    phone: "+1 615-244-3340", 
    website: "https://fristartmuseum.org", 
  },

  {
    id: 16,
    nbhd: "gulch",
    name: "The Catbird Seat",
    cat: "dinner",
    emoji: "⭐",
    address: "700 8th Ave S (5th floor, Bill Voorhees Building), Paseo South Gulch",
    lat: 36.150675,
    lng: -86.778698,
    search: "The Catbird Seat Nashville Michelin tasting menu Gulch",
    note: "Nashville's most celebrated restaurant — operating since 2011 as a deliberate culinary incubator where each chef residency brings an entirely new vision to the kitchen. The current chapter is led by husband-and-wife chefs Andy Doubrava and Tiffani Ortiz, whose 15-course tasting menu is built around Tennessee ingredients, sustainability, and zero-waste kitchen practice. The U-shaped Tennessee pink marble counter wraps around an open kitchen where every course is finished a few feet in front of you. The Infatuation currently rates it Nashville's highest-rated restaurant: 'The experimental fine dining powerhouse recently got a makeover... and the food has ascended to near untouchable heights.' One Michelin Star, 2025. The Patterson House cocktail bar is directly next door on the same floor.",
    hours: "Wed–Sat 17:30–21:00",
    tip: "Reservations open on the first of each month for the entire following month at noon CST — they sell out within minutes. Arrive early and have a pre-dinner drink at The Patterson House next door.",
    type: "Michelin-Starred Tasting Menu (15 courses)",
    blog: "", 
    phone: "+1 615-810-8200", 
    website: "https://www.thecatbirdseatrestaurant.com",
    resUrl: "https://www.opentable.com/r/the-catbird-seat",
  },

  {
    id: 17,
    nbhd: "gulch",
    name: "Biscuit Love",
    cat: "breakfast",
    emoji: "🧇",
    address: "316 11th Ave S, The Gulch",
    lat: 36.153050,
    lng: -86.783231,
    search: "Biscuit Love Nashville Gulch Southern brunch biscuits Bonuts",
    note: "Founded by husband and wife team Karl and Sarah Worley in 2012, this casual eatery's scratch made biscuits have been a favourite of locals and visitors alike. The wait times can be long, so be prepared as they do not accept reservations.",
    hours: "Daily 07:00–15:00",
    tip: "A Holston House staff pick — Isha. Arrive 15 minutes before opening on weekdays to avoid the wait. The Bonuts sell out — order them immediately on arrival.",
    type: "Southern Brunch",
    blog: "", 
    phone: "+1 615-490-9584", 
    website: "https://biscuitlove.com", 
  },

  {
    id: 18,
    nbhd: "gulch",
    name: "The Patterson House",
    cat: "bar",
    emoji: "🍸",
    address: "700 8th Ave S (5th floor, Bill Voorhees Building), Paseo South Gulch",
    lat: 36.150632,
    lng: -86.778699,
    search: "Patterson House Nashville cocktail bar Gulch Bill Voorhees 8th Ave James Beard",
    note: "The bar that set Nashville's craft cocktail standard in 2009, now in a new fifth-floor home in the Bill Voorhees Building — red oak bar, cherry wood walls, tin ceiling panels, intimate booth seating, and full downtown views. Two menus: nine rotating original drinks alongside a 150-cocktail archive of the bar's greatest hits. Multiple James Beard nominations for Outstanding Bar Programme.",
    hours: "Daily 16:00–02:00",
    tip: "The entrance is on Paseo Pl. behind the Bill Voorhees Building — not from 8th Ave directly. Paid valet Wed–Sat from 4pm. First-come, first-served; limited reservations available.",
    type: "James Beard Craft Cocktail Bar",
    blog: "", 
    phone: "+1 615-810-8200",
    website: "https://www.thepattersonnashville.com",
    resUrl: "https://www.opentable.com/r/the-patterson-house-nashville", 
  },

  {
    id: 19,
    nbhd: "gulch",
    name: "The Station Inn",
    cat: "music",
    emoji: "🎻",
    address: "402 12th Ave S, The Gulch",
    lat: 36.1526,
    lng: -86.7846,
    search: "Station Inn Nashville",
    note: "Nashville's most beloved bluegrass and acoustic music club — a low-lit concrete-block room where some of the finest pickers in the world have played since 1974. There are no big screens, no pretensions, and no cover charge on many nights. The focus is entirely on the music six feet in front of you. TimeOut Nashville lists it as one of the city's essential live music bars. Bring cash, order a beer, and let the picking begin.",
    hours: "Daily 19:00–00:00",
    tip: "Tuesday night open bluegrass jam: anyone can join. Sunday shows are most intimate. Check the schedule — programming is worth planning around.",
    type: "Bluegrass & Acoustic Music Club",
    blog: "", 
    phone: "+1 615-255-3307", 
    website: "https://www.stationinn.com", 
  },

  {
    id: 43,
    nbhd: "gulch",
    name: "Rudy's Jazz Room",
    cat: "music",
    emoji: "🎺",
    address: "809 Gleaves St, SoBro",
    lat: 36.1518,
    lng: -86.7800,
    search: "Rudys Jazz Room Nashville jazz venue SoBro intimate",
    note: "Nashville's most dedicated jazz room — an intimate venue near the Cannery Row complex that programmes traditional and contemporary jazz with genuine curatorial intent. Where the Station Inn is for bluegrass, Rudy's is for jazz: small room, close to the musicians, an audience that came to listen. Frommer's Nashville lists it alongside the Station Inn as one of the city's standard-bearing acoustic music venues. The cocktail programme is well above average for a music room.",
    hours: "Mon + Wed–Thu + Sun 17:00–23:30; Fri–Sat 17:00–01:00; Tue closed",
    tip: "Reserve a table in advance for weekend shows — the room is small and fills quickly for strong bookings. Arrive early for a drink at the bar before the set.",
    type: "Intimate Jazz Venue",
    blog: "", 
    phone: "+1 615-988-2458", 
    website: "https://rudysjazzroom.com", 
  },

  {
    id: 51,
    nbhd: "gulch",
    name: "Milk and Honey",
    cat: "breakfast",
    emoji: "🍯",
    address: "214 11th Ave S, The Gulch",
    lat: 36.1546,
    lng: -86.7846,
    search: "Milk and Honey Nashville",
    note: "Coffee shop open for breakfast and brunch seven days a week — Stumptown coffee, homemade baked goods, and fresh squeezed juices in a relaxed, welcoming space.",
    hours: "Daily 06:00–15:00",
    tip: "A Holston House staff pick — Daniel.",
    type: "Breakfast & Coffee Shop",
    blog: "", 
    phone: "+1 615-712-7466",
    website: "https://milkandhoneynashville.com",
    direct_image: "https://images.squarespace-cdn.com/content/v1/5d94b0d773c2547ae71c7d5c/1570115234163-KEFN3X12MSLBNSY315MH/milk-and-honey-nashville.jpg"
  },

  {
    id: 54,
    nbhd: "gulch",
    name: "One Kitchen",
    cat: "breakfast",
    emoji: "🌿",
    address: "710 Demonbreun St, The Gulch",
    lat: 36.1573,
    lng: -86.7807,
    search: "1 Kitchen Nashville",
    note: "Known for its fresh, local, and sustainably sourced farm-to-table cuisine, sourcing 75% of its ingredients within a 200 mile radius of Nashville.",
    hours: "Daily 07:00–14:00 & 17:00–21:00 (Fri–Sat until 22:00)",
    tip: "A Holston House staff pick — Phillip.",
    type: "Farm-to-Table All-Day Restaurant",
    blog: "", 
    phone: "+1 615-993-5988",
    website: "https://www.1hotels.com/nashville/taste/1-kitchen",
    resUrl: "https://www.opentable.com/r/1-kitchen-nashville",
    direct_image: "https://www.1hotels.com/sites/1hotels.com/files/styles/card/public/brandfolder/kkpjffxqw877ccnhbrwnfxh5/1_Hotels_NVL_1_Kitchen_Dinner_0960h2881.png?h=cfc9e117&itok=MyjynTUW"
  },

  {
    id: 57,
    nbhd: "gulch",
    name: "The Finch",
    cat: "lunch",
    emoji: "🍽️",
    address: "111 10th Ave S, The Gulch",
    lat: 36.156633,
    lng: -86.783914,
    search: "The Finch Nashville restaurant",
    note: "Modern takes on American classics in a comfortable and stylish cafe situated steps from the Frist Art Museum — a natural stopping point before or after a visit.",
    hours: "Mon–Thu 11:00–22:00; Fri 11:00–23:00; Sat 10:00–23:00; Sun 10:00–22:00",
    tip: "A Holston House staff pick — Phillip.",
    type: "American Cafe & Restaurant",
    blog: "", 
    phone: "+1 615-208-2762",
    website: "https://thefinchnashville.com",
    resUrl: "https://www.opentable.com/r/the-finch-nashville",
    direct_image: "https://images.getbento.com/accounts/5b9eaaecba84ff0a05eebe931fa7dee3/media/images/6383DSC05320_1.jpg?w=1200&fit=crop&auto=compress,format&cs=origin&crop=focalpoint&fp-x=0.5&fp-y=0.5"
  },

  {
    id: 62,
    nbhd: "gulch",
    name: "Maiz de la Vida",
    cat: "dinner",
    emoji: "🌮",
    address: "606 8th Ave S, The Gulch",
    lat: 36.151312,
    lng: -86.778814,
    search: "Maiz de la Vida Nashville",
    note: "Vibrant atmosphere and fresh, heirloom corn-based Mexican cuisine. Enjoy handcrafted dishes made with care and a full agave bar featuring an impressive selection of mezcal and tequila.",
    hours: "Mon–Sat 11:00–15:00 & 17:00–22:00; Sun 11:00–15:00 & 17:00–21:00",
    tip: "A Holston House staff pick — Phillip.",
    type: "Modern Mexican Restaurant & Agave Bar",
    blog: "", 
    phone: "+1 615-499-4248",
    website: "https://maizdelavida.com",
    resUrl: "https://www.opentable.com/r/maiz-de-la-vida-nashville",
    direct_image: "https://images.squarespace-cdn.com/content/v1/690646896fa1ec6272589e52/14dcf475-1b4e-4e98-9711-58f61ddde444/maizdlv_040226_reedit-56.jpg"
  },

  {
    id: 64,
    nbhd: "gulch",
    name: "Peg Leg Porker",
    cat: "bbq",
    emoji: "🍖",
    address: "903 Gleaves St, The Gulch",
    lat: 36.1517,
    lng: -86.7812,
    search: "Peg Leg Porker Nashville",
    note: "Famous family-owned restaurant featuring award-winning dry rub ribs, traditional Southern sides, and a vast bourbon selection. One of Nashville's most celebrated BBQ destinations.",
    hours: "Mon–Tue 11:00–21:00; Wed–Sat 11:00–22:00; Sun 11:00–16:00",
    tip: "A Holston House staff pick — Phillip. The dry rub ribs are the signature order.",
    type: "Tennessee BBQ (dry rub)",
    blog: "", 
    phone: "+1 615-829-6023",
    website: "https://peglegporker.com",
  },

  {
    id: 79,
    nbhd: "gulch",
    name: "Nashville Boot Company",
    cat: "boots",
    emoji: "👢",
    address: "603 8th Ave S, The Gulch",
    lat: 36.151561,
    lng: -86.779501,
    search: "Nashville Boot Company",
    note: "A quieter, less-touristed alternative to the Broadway boot strip, set on 8th Avenue South away from the honky-tonk crowds. The selection skews toward working boots and traditional cowboy styles. Lower foot traffic means staff have more time to help you find the right fit. No website — call ahead to confirm hours before making a trip.",
    hours: "Mon 09:00–16:00; Tue–Sat 09:00–17:00",
    tip: "Call +1 615-353-9838 before visiting. A good choice if you want a more relaxed experience away from the Broadway crowds.",
    type: "Cowboy Boots",
    blog: "",
    phone: "+1 615-353-9838",
    website: "",
    direct_image: ""
  },

  // ─── EAST NASHVILLE ──────────────────────────────────────────────────

  {
    id: 20,
    nbhd: "east",
    name: "Attaboy Nashville",
    cat: "bar",
    emoji: "🍸",
    address: "8 McFerrin Ave, East Nashville",
    lat: 36.1761,
    lng: -86.7554,
    search: "Attaboy Nashville speakeasy no-menu cocktail bar East Nashville",
    note: "Attaboy arrives in Nashville as sister bar to the legendary New York original, and the same rules apply: there is no menu. Bartenders ask your preferred spirits, flavour profiles, and mood — then deliver something bespoke every time. The dimly-lit industrial space announces quietly that this place is serious.",
    hours: "Sun–Thu 17:00–02:00; Fri–Sat 16:00–02:00",
    tip: "No menu — just tell the bartender what you like (spirit, style, mood). Come on a weeknight when the room is quiet enough for a proper conversation.",
    type: "No-Menu Speakeasy",
    blog: "", 
    phone: "", 
    website: "https://attaboy.us",
    direct_image: "https://images.squarespace-cdn.com/content/v1/64833e4a03447509e165a61d/026ab0bf-7cee-4871-98e3-01aa6a5c0f2c/_DSC8988+%281%29.jpg"
  },

  {
    id: 21,
    nbhd: "east",
    name: "Kisser",
    cat: "dinner",
    emoji: "🍜",
    address: "747 Douglas Ave, East Nashville",
    lat: 36.1938,
    lng: -86.7538,
    search: "Kisser Nashville Japanese East Nashville Highland Yards James Beard 2024",
    note: "A 2024 James Beard Award Best New Restaurant semifinalist from the team behind Folk and Rolf & Daughters. The kitchen draws on Japanese comfort food — chicken katsu sandwiches, curry dishes, creative udon — with an approachable, unhurried spirit. The Infatuation rates it among Nashville's best: 'The yellowtail collar is one of the best things you can eat in this city.' Named one of Bon Appétit's Best New Restaurants in America.",
    hours: "Mon + Thu–Fri 11:00–15:00; Sat–Sun 10:00–15:00; Tue–Wed closed",
    tip: "Order the chirashi bowl at lunch — a serious splurge for the price. The sesame swiss roll at the bakery counter is a non-negotiable purchase.",
    type: "James Beard Japanese Comfort Food",
    blog: "", 
    phone: "",
    website: "https://www.kisserrestaurant.com",
    resUrl: "https://www.opentable.com/r/kisser-nashville", 
  },

  {
    id: 23,
    nbhd: "east",
    name: "The Pharmacy Burger Parlor & Beer Garden",
    cat: "lunch",
    emoji: "🍔",
    address: "731 McFerrin Ave, East Nashville",
    lat: 36.1849,
    lng: -86.7542,
    search: "The Pharmacy Burger Nashville East Nashville beer garden McFerrin Ave",
    note: "The Pharmacy has the best burger in Nashville and one of its finest patios: a sprawling German-style beer garden with long picnic tables, string lights, and a laid-back energy that makes you want to stay for two more rounds. The menu is simple — burgers, fries, house-made sodas in flavours like ginger lemon and hibiscus — but everything is executed with real care. A local favourite that draws families and serious drinkers equally, and perfectly captures what East Nashville does best.",
    hours: "Daily 11:00–21:00 (Fri–Sat until 21:30)",
    tip: "Order a house-made soda alongside your burger — the ginger lemon is outstanding. The beer garden fills on weekend evenings.",
    type: "Craft Burger & Beer Garden",
    blog: "", 
    phone: "+1 615-712-9517", 
    website: "https://thepharmacyburger.com",
    resUrl: "https://www.exploretock.com/the-pharmacy-burger-parlor-nashville", 
  },

  {
    id: 26,
    nbhd: "east",
    name: "Bad Idea",
    cat: "dinner",
    emoji: "🍷",
    address: "1021 Russell St, East Nashville",
    lat: 36.1759,
    lng: -86.7505,
    search: "Bad Idea wine bar Nashville East Nashville Russell Street Michelin Award",
    note: "In 2024, the New York Times named Bad Idea one of the 50 Best Restaurants in America. Sommelier Alex Burch — recipient of the Michelin American South Sommelier Award 2025 — runs the wine programme from inside a tornado-damaged East Nashville church restored into one of the most beautiful dining rooms in the city. Visit Nashville: 'The lofty ceiling height, the grand arched windows, the bustling horseshoe-shaped bar, a mezzanine (once a choir loft), and clergy offices transformed into private dining rooms.' An experience unlike any other in Nashville.",
    hours: "Daily 17:00–00:00",
    tip: "Book a table for the full experience, but walk-ins are welcome at the bar. The staff will guide you through the wine programme with genuine enthusiasm.",
    type: "Michelin-Recognised Wine Bar & Restaurant",
    blog: "", 
    phone: "+1 629-729-4332", 
    website: "https://badideanashville.com",
    resUrl: "https://www.opentable.com/r/bad-idea-wine-bar-nashville", 
  },

  {
    id: 69,
    nbhd: "east",
    name: "The Basement East",
    cat: "music",
    emoji: "🎸",
    address: "917 Woodland St, East Nashville",
    lat: 36.1757,
    lng: -86.7556,
    search: "The Basement East Nashville",
    note: "East Nashville's most beloved independent music venue, set in a converted warehouse across the Cumberland River from downtown. Founded by the same family behind The Basement on 8th Ave, it draws nationally touring acts alongside emerging local talent. The room has genuine character: exposed brick, a lively pub area, and a crowd that comes to actually listen. Genres range from Americana and indie rock to soul and country that sounds nothing like Broadway.",
    hours: "Mon–Sun 19:00–02:00 (show-dependent)",
    tip: "Check the calendar before going — shows sell out. Street parking is easy on weeknights.",
    type: "Independent Music Venue",
    blog: "", 
    phone: "+1 615-645-9174", 
    website: "https://thebasementnashville.com", 
  },

  // ─── 12 SOUTH ────────────────────────────────────────────────────────

  {
    id: 29,
    nbhd: "12south",
    name: "Locust",
    cat: "dinner",
    emoji: "🍽️",
    address: "2305 12th Ave S, 12 South",
    lat: 36.127378,
    lng: -86.789370,
    search: "Locust Nashville 12 South Michelin Star Trevor Moran restaurant",
    note: "Locust earned its Michelin Star in November 2025 and is open only Friday through Sunday. Chef Trevor Moran (formerly of The Catbird Seat and Noma Copenhagen) runs an ever-changing menu of Japanese, Irish, and British-influenced food. The Infatuation: 'Order everything. There'll probably be 10–11 dishes that are easy to say yes to, like heartbreakingly tender potato bread, meaty razor clams served open on pebble ice.' The bar side accepts walk-ins and serves the full cocktail menu — a brilliant way to experience Locust without the month-ahead reservation.",
    hours: "Fri–Sun 12:00–15:00; Fri–Sun 18:00–21:00",
    tip: "Walk-ins at the bar get the full cocktail experience. Dinner reservations open one month in advance — set a calendar reminder. A deposit is required at booking.",
    type: "Michelin-Starred Seasonal Cuisine",
    blog: "", 
    phone: "", 
    website: "https://locustnashville.com",
    resUrl: "https://www.opentable.com/r/locust-nashville", 
  },

  {
    id: 32,
    nbhd: "12south",
    name: "Bastion",
    cat: "dinner",
    emoji: "🌟",
    address: "434 Houston St, Suite 110, Wedgewood-Houston",
    lat: 36.142924,
    lng: -86.766565,
    search: "Bastion Nashville Wedgewood-Houston Michelin Star cocktails restaurant nachos",
    note: "Bastion won its Michelin star in 2025 — tucked behind an unmarked entrance in Wedgewood-Houston. Nashville Guru places the atmosphere perfectly: 'Creative types sipping Old Fashioneds under twinkling strings of lights. The bar's single-item food menu (nachos) allows the seasoned staff to spend that much more time honing their craft cocktails.' The nachos are genuinely excellent; the cocktails are some of Nashville's finest. Reservations release online only.",
    hours: "Restaurant: Wed–Sat 17:00–22:00; Bar: Sun–Thu 17:00–00:00, Fri–Sat 17:00–01:00",
    tip: "Reservations for dining release online only — watch the site. The bar is walk-in and the cocktails alone justify the trip.",
    type: "Michelin-Starred Restaurant & Bar",
    blog: "", 
    phone: "+1 615-490-8434", 
    website: "https://bastionnashville.com",
    resUrl: "https://www.opentable.com/r/bastion-nashville",
    direct_image: "https://images.squarespace-cdn.com/content/v1/63c0626eaf766c4379fb79f9/82989a7d-0a3e-4bb7-8991-ddcb2a8a66fc/Bastion-February2025-71.jpg"
  },

  {
    id: 33,
    nbhd: "12south",
    name: "Fonda on 12th",
    cat: "dinner",
    emoji: "🌮",
    address: "2316 12th Ave S, 12 South",
    lat: 36.126725,
    lng: -86.789099,
    search: "Fonda on 12th Nashville 12 South Mexican restaurant Roberto Santibanez",
    note: "Chef Roberto Santibañez — born in Mexico City, trained at Le Cordon Bleu Paris — brought his acclaimed NYC Fonda concept to 12 South in May 2024. Nashville Lifestyles: 'His menu is replete with creative dishes representing the best of Old and New Worlds.' Order the crab empanadas with mango habanero salsa, the taco board (choose your protein, arrives with six tortillas and house salsas), and the watermelon-cucumber salad. Rated 4.8 on OpenTable from nearly 100 diners.",
    hours: "Mon–Wed 15:00–22:00; Thu–Fri 11:00–22:00 (Fri until 23:00); Sat 10:00–23:00; Sun 10:00–22:00",
    tip: "Happy hour runs daily with $6.50 wine and taco boards — the best value on 12th Ave. The guacamole is made to order tableside.",
    type: "Elevated Modern Mexican",
    blog: "", 
    phone: "+1 615-800-4899",
    website: "https://fondanashville.com",
    resUrl: "https://www.opentable.com/r/fonda-on-12th-nashville",
  },

  {
    id: 72,
    nbhd: "12south",
    name: "12 South",
    cat: "shopping",
    emoji: "🛍️",
    address: "12th Ave S (between Linden Ave and Kirkwood Ave), Nashville",
    lat: 36.1237,
    lng: -86.7899,
    search: "12 South Nashville shopping",
    note: "A half-mile stretch of 12th Avenue South that feels like Nashville at its most local. No honky-tonks, no bachelorette sashes — just well-edited boutiques, coffee shops, wine bars, and restaurants. Shops like White's Mercantile and Judith Bright sit alongside names like Rag & Bone and Jenni Kayne that chose 12 South for its character. Walkable end to end in 20 minutes; most people spend several hours.",
    hours: "Shops typically daily 10:00–18:00; restaurants later",
    tip: "About 10 minutes by rideshare from downtown. Parking garage at Kirkwood Ave on weekends.",
    type: "Shopping Neighborhood",
    blog: "", 
    phone: "", 
    website: "https://www.visitmusiccity.com/nashville-neighborhoods/12south",
    direct_image: "https://nashvilleguru.com/officialwebsite/wp-content/uploads/2022/09/12-South-Nashville-2021-94-1024x683.jpg"
  },

  // ─── MIDTOWN / HILLSBORO VILLAGE / MUSIC ROW ─────────────────────────

  {
    id: 34,
    nbhd: "midtown",
    name: "The Parthenon at Centennial Park",
    cat: "attraction",
    emoji: "🏛️",
    address: "2500 West End Ave, Centennial Park",
    lat: 36.1497,
    lng: -86.8133,
    search: "Parthenon Nashville Centennial Park",
    note: "Built for the 1897 Tennessee Centennial Exposition, Nashville's full-scale concrete replica of the Athenian Parthenon is the city's most arrestingly surreal landmark — a complete Greek temple in the middle of a 132-acre urban park. Inside, the Naos Gallery houses Nashville's civic art collection and the centrepiece: a 42-foot gilded statue of Athena, the tallest indoor statue in the Western Hemisphere.",
    hours: "Currently closed for renovation (reopening late June 2026). Normal hours: Mon–Thu 09:00–19:00; Fri–Sat 09:00–16:30; Sun 12:30–16:30",
    tip: "The park is beautiful at any hour. The Parthenon interior is best in morning light. The walk to Vanderbilt's campus five minutes north makes a fine combined morning.",
    type: "Full-Scale Parthenon Replica & Art Museum",
    blog: "", 
    phone: "+1 615-862-8431", 
    website: "https://www.nashvilleparthenon.com", 
  },

  {
    id: 35,
    nbhd: "midtown",
    name: "The Bluebird Cafe",
    cat: "music",
    emoji: "🎵",
    address: "4104 Hillsboro Pike, Green Hills",
    lat: 36.102076,
    lng: -86.816865,
    search: "Bluebird Cafe Nashville",
    note: "The Bluebird is the room where careers begin — a 90-seat listening room in a strip mall that has launched more country music careers than any other venue on earth. Garth Brooks was discovered here. Taylor Swift was discovered here. The house rules are strict: no talking during songs, full attention to the stage. 'In the Round' shows, where four songwriters sit together and trade original songs, reveal the craft behind the hits in a way no other Nashville experience can match.",
    hours: "Show-based: two shows nightly, doors from 18:00 (early) and ~20:30 (late). Check calendar at bluebirdcafe.com.",
    tip: "Reserve well in advance — the room seats only 90. In the Round shows on Sunday evenings are the best introduction to how Nashville songs are actually made.",
    type: "Songwriter Listening Room",
    blog: "", 
    phone: "+1 615-383-1461", 
    website: "https://www.bluebirdcafe.com", 
  },

  {
    id: 37,
    nbhd: "midtown",
    name: "Belcourt Theatre",
    cat: "attraction",
    emoji: "🎬",
    address: "2102 Belcourt Ave, Hillsboro Village",
    lat: 36.1368,
    lng: -86.8014,
    search: "Belcourt Theatre Nashville Hillsboro Village independent art house cinema 1925",
    note: "Nashville's independent cinema, operating continuously since 1925 — one of the oldest continuously running movie houses in Tennessee. The Belcourt programmes art house films, documentaries, film festivals, and live events in two beautifully restored theatres. It is the cultural anchor of Hillsboro Village — across the street from Fido, two blocks from Vanderbilt — and the programming reflects genuine curatorial intelligence. Nashvegas identifies it as one of the neighbourhood's best options for culture.",
    hours: "Showtimes vary — check calendar at belcourt.org. Box office opens 30 min before first show.",
    tip: "Check the monthly calendar for special events — retrospectives, Q&As with filmmakers, and local premieres are regular features. The popcorn is notably good.",
    type: "Independent & Art House Cinema",
    blog: "", 
    phone: "+1 615-846-3150", 
    website: "https://www.belcourt.org", 
  },

  {
    id: 39,
    nbhd: "midtown",
    name: "RCA Studio B",
    cat: "attraction",
    emoji: "🎙️",
    address: "1611 Roy Acuff Pl, Music Row",
    lat: 36.1500,
    lng: -86.7929,
    search: "RCA Studio B Nashville Music Row",
    note: "Nashvegas is unambiguous: RCA Studio B is the most historically significant recording studio in country music history. Elvis Presley, Dolly Parton, Willie Nelson, Chet Atkins, Roy Orbison, and hundreds more recorded here between 1957 and 1977. The studio's original console, isolation booth, and reverb chamber are all intact and fully operational. Tours run through the Country Music Hall of Fame and are consistently among the most informative cultural experiences Nashville offers.",
    hours: "Daily 10:30–15:30 (tours depart from Country Music Hall of Fame)",
    tip: "Book the combination ticket with the Country Music Hall of Fame. Tours are limited in size and sell out — book at least a week ahead on weekends.",
    type: "Historic Recording Studio (tours)",
    blog: "", 
    phone: "+1 615-416-2001", 
    website: "https://www.countrymusichalloffame.org/visit/rca-studio-b", 
  },

  {
    id: 40,
    nbhd: "midtown",
    name: "Pancake Pantry",
    cat: "breakfast",
    emoji: "🥞",
    address: "1796 21st Ave S, Hillsboro Village",
    lat: 36.1345,
    lng: -86.8021,
    search: "Pancake Pantry Nashville Hillsboro Village breakfast institution 1961",
    note: "Since 1961, this Nashville staple is known for its scratch made pancakes and syrup. Their menu features 16 different pancake selections, but if you are looking for a bit of everything, try the Sampler of Pancakes.",
    hours: "Daily 06:00–15:00",
    tip: "A Holston House staff pick — Phillip. Arrive before 8am on weekdays to avoid a wait. The Caribbean pancakes (coconut and pineapple syrup) are the cult order.",
    type: "Nashville Breakfast Institution (est. 1961)",
    blog: "", 
    phone: "+1 615-383-9333", 
    website: "https://www.thepancakepantry.com", 
  },

  {
    id: 55,
    nbhd: "midtown",
    name: "All'Antico Vinaio",
    cat: "lunch",
    emoji: "🥖",
    address: "1915 Broadway, Midtown",
    lat: 36.149894,
    lng: -86.797466,
    search: "All'Antico Vinaio Nashville",
    note: "World famous Florentine sandwich shop — a multitude of Italian sandwiches on their signature schiacciata bread, brought directly from Florence to Nashville.",
    hours: "Sun–Thu 11:00–20:00; Fri–Sat 11:00–22:00",
    tip: "A Holston House staff pick — Phillip.",
    type: "Florentine Sandwich Shop",
    blog: "", 
    phone: "", 
    website: "https://allanticovinaiousa.com",
    direct_image: "https://images.getbento.com/accounts/d04d8b2eaa2619a6f10fc00a10efd9ba/media/images/52290Interior-24.jpg?w=1200&fit=crop&auto=compress,format&cs=origin&h=600"
  },

  {
    id: 61,
    nbhd: "midtown",
    name: "Amerigo",
    cat: "dinner",
    emoji: "🍝",
    address: "1920 West End Ave, Midtown",
    lat: 36.151661,
    lng: -86.799182,
    search: "Amerigo Italian Restaurant Nashville",
    note: "A local Nashville favorite for over 30 years — serving authentic Italian pastas, hand-made pizzas, fresh seafood, and wood-fired steaks. Something for everyone on a menu that has earned genuine local loyalty.",
    hours: "Mon–Thu 11:00–22:00; Fri–Sat 11:00–22:30; Sun 11:00–22:00",
    tip: "A Holston House staff pick — Isha.",
    type: "Italian Pasta Restaurant",
    blog: "",
    phone: "+1 615-320-1740",
    website: "https://amerigo.net/nashville",
    resUrl: "https://www.opentable.com/r/amerigo-west-end-nashville",
    direct_image: "https://images.unsplash.com/photo-1662197480393-2a82030b7b83?fm=jpg&q=80&w=1200&auto=format&fit=crop"
  },

  // ─── GREATER NASHVILLE / PARKS & DAY TRIPS ───────────────────────────

  {
    id: 50,
    nbhd: "parks",
    name: "Cheekwood Estate & Gardens",
    cat: "attraction",
    emoji: "🌸",
    address: "1200 Forrest Park Dr, Belle Meade (20 min from downtown)",
    lat: 36.0884,
    lng: -86.8760,
    search: "Cheekwood Estate Gardens Nashville",
    note: "A 1920s Georgian Revival mansion on 55 acres of formally designed botanical gardens in Belle Meade — Nashville's most beautiful cultural institution outside the downtown museums. The estate was the home of the Maxwell House coffee fortune; its gardens range from a Japanese garden and a boxwood allée to wildflower meadows and sculptural woodlands. The interior houses a strong permanent collection of American art alongside rotating exhibitions. Cheekwood's seasonal programmes — the winter lights display, the spring tulip season — consistently draw Nashville's most enthusiastic crowds.",
    hours: "Tue–Sun 09:00–17:00",
    tip: "Book tickets online, especially for seasonal events which sell out weeks in advance. The Japanese garden is the most serene 20 minutes available in all of Nashville.",
    type: "Historic Estate, Gardens & Art Museum",
    blog: "", 
    phone: "+1 615-356-8000", 
    website: "https://cheekwood.org", 
  },

];
