// A Perfect Day — London
// london_data_v4.js — 50 curated places
//
// v7 — May 2026
// Voice: boutique hotel concierge — direct, specific, opinionated
// Six categories: Art & Design · Shop · Royal London · From the Movies · Fine Dining · Pubs & Bars
//
// v7 changes: Full structural rebuild.
//   Cut from 71 to 50 places. New categories: art, shop, royal, film, dining, pub.
//   Removed 33 entries. Added 12 new entries:
//     Kensington Palace (82), Fortnum & Mason (83), The Ritz (84), Claridge's (85),
//     Floris (86), Lock & Co (87), Saatchi Gallery (76), Serpentine Galleries (77),
//     Newport Street Gallery (78), Dover Street Market (79), Liberty London (80),
//     Bermondsey Antique Market (81).
//   Rewrote all existing entries with new category angles.
//   All facts verified May 2026. Bibendum removed (closed August 2025).

const PLACES = [

  // ── WESTMINSTER ───────────────────────────────────────────────────────────

  {
    id: 1,
    nbhd: 'westminster',
    name: 'Berry Bros. & Rudd',
    cat: 'shop',
    emoji: '🍷',
    address: '3 St James\'s St, London SW1A 1EG',
    lat: 51.5063, lng: -0.1388,
    search: 'Berry Bros Rudd wine merchant interior St James\'s London',
    note: 'Britain\'s oldest wine merchant, trading from the same St James\'s building since 1698. Walk in and nothing has been renovated for atmosphere — the Georgian panelling, the ancient coffee-weighing scales on the floor, the bare boards worn into hollows over three centuries are simply what the place looks like. They hold Royal Warrants from both King Charles III and the Prince of Wales. The basement cellars run under St James\'s Street and hold one of the finest private wine collections in the country. The staff know their inventory the way a good bookseller knows books — with genuine opinions — and will tell you exactly what to open, when, and with what. Wine courses, cellar events and private dining run from the vaulted rooms below the street. The shop itself is the reason to come before any of that.',
    hours: 'Mon–Fri 10:00–18:00; Sat 10:00–17:00; closed Sun',
    tip: 'Ask for a recommendation at your price point — the response will be specific and correct. Cellar tours and tastings bookable on the website.',
    type: 'Britain\'s oldest wine merchant (est. 1698) — St James\'s',
    website: 'https://www.bbr.com',
  },
  {
    id: 73,
    nbhd: 'westminster',
    name: 'The Connaught Bar',
    cat: 'pub',
    emoji: '🍸',
    address: 'Carlos Place, Mayfair, London W1K 2AL',
    lat: 51.5118, lng: -0.1488,
    search: 'Connaught Bar interior cocktail martini Mayfair London',
    note: 'Ranked #6 in The World\'s 50 Best Bars 2025, after holding the top position for several consecutive years — which makes it consistently one of the most discussed cocktail rooms on earth. The space is all marble, mirror and Art Deco curves, and the dry martini service arrives on a silver trolley, mixed tableside to your exact specification from a choice of vermouths and bitters. The ritual is as precise as the drink. Order whatever you want, but ask the bartender to begin with the Connaught Martini and work out from there. The room fills completely by 20:00 at weekends; book well ahead.',
    hours: 'Mon–Sat 11:00–00:00; Sun 11:00–23:00',
    tip: 'Book ahead — the bar fills completely at weekends. The dry martini trolley is the experience. Ask the bartender for their recommendation on vermouth ratio.',
    type: 'World\'s #6 cocktail bar 2025 — Mayfair, The Connaught Hotel',
    awards: '#6 The World\'s 50 Best Bars 2025',
    website: 'https://www.the-connaught.co.uk/bars-restaurant/the-connaught-bar/',
  },
  {
    id: 74,
    nbhd: 'westminster',
    name: 'Dukes Bar',
    cat: 'pub',
    emoji: '🍋',
    address: '35 St James\'s Place, London SW1A 1NY',
    lat: 51.5065, lng: -0.1418,
    search: 'Dukes Bar interior St James London cocktail martini',
    note: 'Inside Dukes Hotel in St James\'s, in a room that seats perhaps 30 people and looks unchanged since Ian Fleming drank here and worked out the formula that became James Bond\'s martini. The dry martini service is conducted tableside: frozen gin, no dilution from ice, poured with ceremony into a pre-chilled glass. Bone dry, extremely cold, served with unhurried precision. The two-martini house limit per person is genuine advice, not theatrical caution. Fleming\'s vesper — vodka, gin, Lillet — is on the menu by name. If there is a purer expression of a cocktail bar\'s reason for existing, it is not in London.',
    hours: 'Mon–Sat 12:00–23:00; Sun 12:00–22:30',
    tip: 'The two-martini rule exists for good reason. The vesper is the Fleming original. Book ahead.',
    type: 'Historic cocktail bar — the birthplace of Bond\'s martini',
    website: 'https://www.dukeshotel.com/dukes-bar',
  },
  {
    id: 59,
    nbhd: 'westminster',
    name: 'Daunt Books',
    cat: 'shop',
    emoji: '📚',
    address: '83–84 Marylebone High St, London W1U 4QW',
    lat: 51.5200, lng: -0.1533,
    search: 'Daunt Books interior skylight Marylebone London bookshop',
    note: 'The back room is what makes people come back: long oak galleries under a central skylight, books arranged by country rather than genre — fiction, history, travel writing and maps for each destination all shelved together. The 1912 Edwardian building was designed as a bookshop and has been nothing else since. The linen tote bag, sold at the counter, has become a more credible London souvenir than anything from a gift shop. The staff are genuinely well-read and have strong opinions about what is worth your time. Ask them. Marylebone High Street deserves the whole morning.',
    hours: 'Mon–Sat 09:00–19:30; Sun 11:00–18:00',
    tip: 'The back room under the skylight is the most beautiful reading space in London. Ask for recommendations — the staff read everything and are not shy about it.',
    type: 'The world\'s most beautiful independent bookshop',
    website: 'https://dauntbooks.co.uk/shops/marylebone/',
  },
  {
    id: 3,
    nbhd: 'westminster',
    name: 'Churchill War Rooms',
    cat: 'film',
    emoji: '🎬',
    address: 'Clive Steps, King Charles Street, London SW1A 2AQ',
    lat: 51.5020, lng: -0.1289,
    search: 'Churchill War Rooms bunker interior London',
    note: 'Gary Oldman won the Academy Award for Best Actor playing Winston Churchill in Darkest Hour (2017), and the filmmakers used these exact rooms as reference for every set they built. The Crown (Netflix, 2016) returned here repeatedly for its Churchill episodes. Both productions spent months recreating what you can simply walk through: the Cabinet War Rooms beneath Whitehall, sealed on VE Day 1945 and left exactly as they were — maps still pinned, phones still connected, a single light bulb burning in the Map Room that has not been switched off since the war. Every film and television production about Churchill is trying to make you feel what this building delivers in person: that wars are fought not from glory, but from a corridor with low ceilings and bad lighting. The Churchill Museum beside it is one of the most intelligent biographical exhibitions in London.',
    hours: 'Daily 09:30–18:00',
    tip: 'Two hours minimum. The Churchill Museum alongside the bunker is as compelling as the rooms themselves.',
    type: 'Preserved WWII bunker — as seen in Darkest Hour (2017) and The Crown',
    website: 'https://www.iwm.org.uk/visits/churchill-war-rooms',
  },
  {
    id: 83,
    nbhd: 'westminster',
    name: 'Fortnum & Mason',
    cat: 'royal',
    emoji: '👑',
    address: '181 Piccadilly, London W1A 1ER',
    lat: 51.5075, lng: -0.1393,
    search: 'Fortnum Mason food hall interior Piccadilly London',
    note: 'Established in 1707 by William Fortnum, a footman in Queen Anne\'s household who noticed that partly used royal candles could be collected and resold, and used his savings to open a grocery with his landlord Hugh Mason. Three centuries later the shop holds Royal Warrants from King Charles III and Queen Camilla — the 2024 Camilla warrant among the first she granted — and remains what it has always been: the most extraordinary food shop in London. The building on Piccadilly is five floors of teas, hampers, preserves, wine, chocolate and provisions arranged with an obsessive care for quality. The clock above the entrance has Mr Fortnum and Mr Mason emerging on the hour since 1964, rotating through a brief mechanical minuet before retreating. The tea department alone — 130 varieties, from single-estate Darjeeling to blends formulated for the Royal Household — justifies the visit. The St James\'s Restaurant on the fourth floor serves a properly executed afternoon tea.',
    hours: 'Mon–Sat 10:00–21:00; Sun 11:30–18:00',
    tip: 'The tea department first. The hampers make serious gifts. The fourth-floor restaurant for afternoon tea.',
    type: 'Royal grocer since 1707 — Royal Warrants from King Charles III and Queen Camilla (2024)',
    website: 'https://www.fortnumandmason.com',
  },
  {
    id: 84,
    nbhd: 'westminster',
    name: 'The Ritz',
    cat: 'royal',
    emoji: '🫖',
    address: '150 Piccadilly, London W1J 9BR',
    lat: 51.5066, lng: -0.1435,
    search: 'The Ritz Palm Court afternoon tea interior London',
    note: 'César Ritz opened this in 1906 on the model of a French château transported to Piccadilly — gilded ceilings, mirrored walls, a pink and gold Palm Court, views over Green Park. The Royal Family has used it as a private dining room for over a century. The Queen Mother was a regular until the end of her life. The afternoon tea in the Palm Court — £95 per person, jacket and tie required for gentlemen — is the most famous in the world because it is genuinely the most consistently executed: tiered stands of finger sandwiches and pastries, a trolley of cakes that moves through the room on schedule, and an atmosphere of ceremony that César Ritz built deliberately into every detail of the space. Book months ahead for weekend slots.',
    hours: 'Afternoon tea served five times daily from 11:30; last seating 19:30',
    tip: 'Book months ahead for weekends. Jacket and tie is enforced. The 11:30 seating is the quietest and most unhurried.',
    type: 'The world\'s most famous afternoon tea — Piccadilly (since 1906)',
    website: 'https://www.theritzlondon.com/dine-with-us/afternoon-tea/',
  },
  {
    id: 85,
    nbhd: 'westminster',
    name: 'Claridge\'s',
    cat: 'royal',
    emoji: '🍾',
    address: 'Brook Street, Mayfair, London W1K 4HR',
    lat: 51.5122, lng: -0.1472,
    search: 'Claridges Art Deco interior lobby Mayfair London',
    note: 'Churchill called Claridge\'s "the annexe to Buckingham Palace," and during the Second World War the metaphor became literal: exiled European royal families — the King of Yugoslavia, the Queen of the Netherlands, the King of Greece — were housed in suites here while their countries were occupied. Churchill himself held court from Suite 212, which he treated as a second office and is now known as the Churchill Suite. The Art Deco interiors, completed in the 1930s, are the finest intact example in any London hotel: the lobby\'s black and white marble floor, the sweeping staircase, the gilded ironwork of the lifts. Every royal family in Europe has stayed here, and the tradition continues. You do not need to be royalty to have tea in the Foyer, a drink in the Fumoir, or dinner in the Mirror Room; you simply need a booking.',
    hours: 'Hotel open 24 hours; Foyer afternoon tea daily 13:00–17:30',
    tip: 'Afternoon tea in the Foyer for the full experience. The Fumoir bar for a pre-dinner drink. Churchill Suite 212 if you want to sleep where wartime history was made.',
    type: 'The Royal Family\'s London hotel — Art Deco Mayfair (since 1812)',
    website: 'https://www.claridges.co.uk',
  },
  {
    id: 86,
    nbhd: 'westminster',
    name: 'Floris',
    cat: 'royal',
    emoji: '🌹',
    address: '89 Jermyn Street, London SW1Y 6JH',
    lat: 51.5060, lng: -0.1367,
    search: 'Floris perfume shop interior mahogany Jermyn Street London',
    note: 'Juan Famenias Floris arrived from Minorca in 1730, set up as a comb-maker and barber on Jermyn Street, and began blending fragrances in the room behind the shop. Nearly 300 years later, the ninth generation of the Floris family runs the business from the same address. They have held a Royal Warrant from every British monarch since George III, and currently hold one from King Charles III. The mahogany showcases inside — designed by the craftsmen who built the display cases for the Great Exhibition of 1851 and acquired directly from the exhibition — have held Floris bottles ever since. The own-blend service allows you to develop a fragrance made to your specification. The bestselling scent, No. 89 — named for the address — was created for the Duke of Edinburgh and has been in continuous production since. Walk in for the room alone.',
    hours: 'Mon–Fri 09:30–18:00; Sat 10:00–17:00; closed Sun',
    tip: 'Ask about the own-blend service if you are serious. No. 89 is the house classic and the correct introduction.',
    type: 'London\'s oldest perfumer (est. 1730) — Royal Warrant since George III',
    website: 'https://www.florislondon.com',
  },
  {
    id: 87,
    nbhd: 'westminster',
    name: 'Lock & Co Hatters',
    cat: 'royal',
    emoji: '🎩',
    address: '6 St James\'s Street, London SW1A 1EF',
    lat: 51.5063, lng: -0.1390,
    search: 'Lock Co Hatters hat shop interior St James London',
    note: 'In 1849 a Norfolk landowner named William Coke walked into Lock & Co and commissioned a hard felt hat that would protect his gamekeepers\' heads from low-hanging branches without the height of a top hat. The hat James Lock designed became known as the bowler — or, in America, the derby — and went on to outfit Charlie Chaplin, Laurel and Hardy, and the entire history of British comedy. Lock & Co has been making hats on this exact St James\'s Street address since 1676, which makes it the oldest hat shop in the world. In 2026 they celebrate 350 continuous years on the same site. Oscar Wilde was a customer. Winston Churchill. The shop holds Royal Warrants from King Charles III and the Prince of Wales. The conformateur — a 19th-century measuring instrument that maps the precise shape of your head — is still used for bespoke orders. Walk in, look at the shelves, and understand why people have been coming here for three and a half centuries.',
    hours: 'Mon–Fri 09:00–17:30; Sat 09:30–17:00; closed Sun',
    tip: 'They will measure your head and advise on the correct shape for your face. Ready-to-wear is available; bespoke takes weeks.',
    type: 'World\'s oldest hat shop (est. 1676) — 350 years on St James\'s Street in 2026',
    website: 'https://www.lockhatters.co.uk',
  },

  // ── SOUTH BANK ────────────────────────────────────────────────────────────

  {
    id: 7,
    nbhd: 'southbank',
    name: 'Tate Modern',
    cat: 'art',
    emoji: '🎨',
    address: 'Bankside, London SE1 9TG',
    lat: 51.5076, lng: -0.0994,
    search: 'Tate Modern gallery interior Turbine Hall London',
    note: 'The building is a work before the art begins: a former Bankside power station with a Turbine Hall 35 metres high and 155 metres long, the most ambitious public art space in Britain. The Turbine Hall commissions have defined contemporary art for a generation — Olafur Eliasson\'s artificial sun that turned visitors\' faces to the ceiling; Ai Weiwei\'s floor of 100 million hand-painted porcelain sunflower seeds; Louise Bourgeois\'s steel spider, Maman, her body a cage of marble eggs. The permanent collection runs free from Picasso and the Surrealists through Rothko, Basquiat and artists working now. The Rothko room — eight large dark-field canvases in controlled light, painted specifically to produce the sensation of walls pressing inward — is one of the few places in London where adults stand in complete silence and are visibly moved. Take the lift to the Blavatnik Building terraces at level 10: the finest free view of the Thames in the city, from the dome of St Paul\'s to Canary Wharf.',
    hours: 'Sun–Thu 10:00–18:00; Fri–Sat 10:00–22:00',
    tip: 'The Rothko room first, the Turbine Hall next, then the level 10 terraces. Friday evenings after 18:00 are emptier than any daytime slot and the light on the river is better.',
    type: 'Modern and contemporary art gallery — permanent collection free',
    website: 'https://www.tate.org.uk/visit/tate-modern',
  },
  {
    id: 8,
    nbhd: 'southbank',
    name: 'Shakespeare\'s Globe',
    cat: 'film',
    emoji: '🎬',
    address: '21 New Globe Walk, Bankside, London SE1 9DT',
    lat: 51.5081, lng: -0.0974,
    search: 'Shakespeare\'s Globe Theatre London',
    note: 'Shakespeare in Love (1998) — seven Academy Awards, Best Picture — was built around the story of this theatre\'s construction, and the film\'s climactic performance takes place on a stage modelled precisely on this one. The Globe opened in 1997, a year before the film\'s release, and the two are inseparable in how most people now imagine Shakespeare\'s London. But the building is not a replica built for tourism: it is a working theatre constructed from green English oak and Norfolk reed thatching using the same joinery techniques as the 1599 original, 200 metres from where that building stood. A groundling ticket — the cheapest in the house and placed at stage level in the open yard — is one of the finest evenings available in London: immediate, physical, and performed in the same weather the 1600 audience experienced, because the roof is genuinely open to the sky.',
    hours: 'Tours daily 09:30–17:00. Performances Apr–Oct',
    tip: 'Groundling tickets are inexpensive and the most immediate way to see a performance. Bring a layer — the open roof is literal. Tours on non-performance days are excellent.',
    type: 'Reconstructed Elizabethan theatre — as seen in Shakespeare in Love (1998)',
    website: 'https://www.shakespearesglobe.com',
  },
  {
    id: 9,
    nbhd: 'southbank',
    name: 'Millennium Bridge',
    cat: 'film',
    emoji: '🎬',
    address: 'Millennium Bridge, Bankside, London SE1',
    lat: 51.5098, lng: -0.0983,
    search: 'Millennium Bridge London Thames',
    note: 'Harry Potter and the Half-Blood Prince (2009) opens with Death Eaters sweeping across London and destroying the Millennium Bridge in the film\'s first dramatic minutes — it sways, buckles and collapses into the Thames. The real bridge opened in 2000 and wobbled alarmingly when crowds first walked on it, earning it the nickname "the Wobbly Bridge" before engineers fixed the resonance problem two years later. Norman Foster\'s pedestrian crossing connects St Paul\'s Cathedral directly to Tate Modern. Walk it from the north bank: the dome fills the view ahead, the Thames runs below, and the crossing takes you from medieval cathedral to power-station-turned-gallery in eight minutes. Bridget Jones crossed it. Paddington crossed it. It has been in more films depicting modern London than any other structure of the 21st century.',
    hours: 'Open 24 hours',
    tip: 'Cross from north to south at first light — St Paul\'s ahead, Tate Modern beyond. Continue east along the Southbank to Borough Market. One of London\'s best free mornings.',
    type: 'Norman Foster pedestrian bridge — as seen in Harry Potter and the Half-Blood Prince',
    website: 'https://www.london.gov.uk',
  },
  {
    id: 78,
    nbhd: 'southbank',
    name: 'Newport Street Gallery',
    cat: 'art',
    emoji: '🖼️',
    address: 'Newport Street, London SE11 6AJ',
    lat: 51.4884, lng: -0.1200,
    search: 'Newport Street Gallery interior exhibition London',
    note: 'Damien Hirst opened this gallery in Vauxhall in 2015 to show works from his personal collection — one of the largest privately held contemporary art collections in the world — alongside temporary exhibitions. The building, designed by Caruso St John Architects in a series of converted Victorian theatrical scenery-painting buildings, won the RIBA Stirling Prize for Architecture in 2016: the rare case of a gallery that is itself an architectural award-winner. Entry is always free. The collection ranges from Francis Bacon, Banksy and Jeff Koons to emerging artists Hirst has supported, and the temporary shows are often among the most ambitious single-artist exhibitions in London. The location in Vauxhall, fifteen minutes on foot from Tate Modern across the river, means almost no one finds it accidentally.',
    hours: 'Wed–Sun 10:00–18:00; closed Mon–Tue',
    tip: 'Free entry always. Check the temporary exhibition programme on the website before visiting — the shows change and are not always about Hirst\'s own work.',
    type: 'Damien Hirst\'s private collection gallery — free, Vauxhall (RIBA Stirling Prize 2016)',
    awards: 'RIBA Stirling Prize 2016 — UK\'s Best New Building',
    website: 'https://www.newportstreetgallery.com',
  },

  // ── BOROUGH & BERMONDSEY ──────────────────────────────────────────────────

  {
    id: 11,
    nbhd: 'borough',
    name: 'Borough Market',
    cat: 'shop',
    emoji: '🛒',
    address: '8 Southwark St, London SE1 1TL',
    lat: 51.5055, lng: -0.0908,
    search: 'Borough Market food stalls interior London',
    note: 'A market on this site since the 13th century, under Victorian railway arches since 1851. Come for the traders rather than the atmosphere: over 100 specialists — a cheesemaker who ages Montgomery\'s Cheddar in his own cellar, a fishmonger buying from day-boat skippers on the south coast, a charcutier curing his own salumi in Bermondsey. Buy something from each and eat it walking. The bread at Bread Ahead alone — doughnuts, sourdough, pastries baked through the morning — is worth the early arrival. Thursday mornings before 11:00 are the authentic version: quieter, traders more willing to talk, the quality exactly the same as the weekend. On Saturdays it is shoulder-to-shoulder by noon, which is a different but not necessarily a worse experience.',
    hours: 'Mon–Thu 10:00–17:00; Fri 10:00–18:00; Sat 08:00–17:00; closed Sun',
    tip: 'Thursday morning before 11:00 for the full experience with room to move. On Saturdays: arrive at opening. Ask traders what\'s exceptional today.',
    type: 'London\'s great food market (since the 13th century)',
    website: 'https://boroughmarket.org.uk',
  },
  {
    id: 19,
    nbhd: 'borough',
    name: 'White Cube Gallery',
    cat: 'art',
    emoji: '🖼️',
    address: '144–152 Bermondsey St, London SE1 3TQ',
    lat: 51.5011, lng: -0.0823,
    search: 'White Cube Gallery interior exhibition Bermondsey London',
    note: 'Walk in and the scale hits you before the art does. White walls, poured concrete floor, daylight controlled from above — a space built specifically to show work that cannot fit anywhere smaller. This is where artists come when they are ready for a room that will either justify the work or expose it. Damien Hirst\'s spot paintings covered every wall simultaneously in 2012. Antony Gormley filled the main hall with cast-iron human forms until the space felt geological. Georg Baselitz hung paintings upside down from a ceiling high enough to make the gesture mean something. The programme changes every few months, runs from quietly devastating to physically overwhelming, and is always free. The current exhibition determines the experience entirely — check the website before you come.',
    hours: 'Tue–Sat 10:00–18:00; Sun 12:00–18:00; closed Mon',
    tip: 'Free, no ticket. The main hall is the reason to come — check what is currently installed. Allow an hour minimum.',
    type: 'Major contemporary art gallery — free, Bermondsey',
    website: 'https://www.whitecube.com',
  },
  {
    id: 22,
    nbhd: 'borough',
    name: 'The Garrison',
    cat: 'pub',
    emoji: '🍺',
    address: '99–101 Bermondsey St, London SE1 3XB',
    lat: 51.5009, lng: -0.0830,
    search: 'The Garrison pub interior Bermondsey London',
    note: 'The gastropub that gave Bermondsey Street its character when it opened in 2003 and has remained the neighbourhood\'s social centre ever since. Bare brick, mismatched vintage furniture, good natural light from a tall front window. The kitchen produces elevated British food without performing the elevation — the kind of cooking where everything is correct without anything drawing attention to itself. The Sunday roast fills months in advance; Saturday breakfast before the market crowd is a reliable start to what will almost certainly be your best day in south London.',
    hours: 'Mon–Thu 08:00–23:00; Fri–Sat 08:00–midnight; Sun 08:00–22:30',
    tip: 'Sunday roast: book months ahead, not weeks. Saturday breakfast before 10:00 is quieter and just as good.',
    type: 'Neighbourhood gastropub — Bermondsey\'s anchor since 2003',
    website: 'https://thegarrison.co.uk',
  },
  {
    id: 60,
    nbhd: 'borough',
    name: 'St John Restaurant',
    cat: 'dining',
    emoji: '🦴',
    address: '26 St John St, Smithfield, London EC1M 4AY',
    lat: 51.5197, lng: -0.1013,
    search: 'St John Restaurant interior Smithfield London food',
    note: 'Fergus Henderson opened St John in a former smokehouse beside Smithfield Market in 1994 and invented a British cuisine. Nose-to-tail cooking — every part of the animal treated with equal precision — sounds like a doctrine but here it is simply a menu. The bone marrow and parsley salad on sourdough toast is one of the most consequential dishes in British food history: a single roasted marrow bone halved and set on toast with flat-leaf parsley dressed in capers and lemon, and nothing else. White walls, no music, no decoration, no performance. The food does the work entirely. Book ahead. Order the eccles cake with Lancashire cheese to finish.',
    hours: 'Mon–Fri 12:00–15:00, 18:00–22:00; Sat 12:00–15:00, 18:00–22:00',
    tip: 'The bone marrow toast is non-negotiable. Eccles cake and Lancashire cheese to finish. Book ahead.',
    type: 'The original nose-to-tail British restaurant (since 1994)',
    awards: '⭐ One Michelin Star · Condé Nast Traveller Lifetime Achievement (Fergus Henderson, 2024)',
    website: 'https://stjohnrestaurant.com',
  },
  {
    id: 81,
    nbhd: 'borough',
    name: 'Bermondsey Antique Market',
    cat: 'shop',
    emoji: '🫙',
    address: 'Long Lane, Bermondsey, London SE1 4QB',
    lat: 51.4982, lng: -0.0813,
    search: 'Bermondsey antique market stalls dealers London',
    note: 'The most serious antique market in London operates on Friday mornings on Long Lane in Bermondsey, and if you arrive after 08:00 the best pieces are already gone. Dealers who set up from 06:00 are largely professionals buying from other professionals: silver, porcelain, furniture, jewellery, maps, prints, glass. The knowledge in the market is genuine — many of these traders also supply auction houses and dealers in Mayfair. Come with cash and a specific idea of what you are looking for; or come with no idea at all and spend two hours developing one. The market winds down by noon and disappears by 14:00 as completely as if it never happened.',
    hours: 'Fridays only, 06:00–14:00',
    tip: 'Arrive by 07:30. Cash preferred. The silver and jewellery section has the most serious dealers. Nothing survives until the afternoon.',
    type: 'London\'s oldest antique market — Friday mornings only, SE1',
    website: 'https://www.bermondseysquare.co.uk',
  },

  // ── THE CITY ──────────────────────────────────────────────────────────────

  {
    id: 23,
    nbhd: 'city',
    name: 'Tower Bridge',
    cat: 'film',
    emoji: '🎬',
    address: 'Tower Bridge Rd, London SE1 2UP',
    lat: 51.5055, lng: -0.0754,
    search: 'Tower Bridge London',
    note: 'James Bond raced a speedboat beneath it in The World Is Not Enough (1999). The Dark Knight Rises. Mission: Impossible — Rogue Nation. Tower Bridge appears in more action films than any other London landmark because it photographs as a symbol rather than simply a building — the Victorian Gothic towers, the raised bascules, the suspended walkways all register as London itself, instantly and globally. The reality is more interesting than any frame: the bridge was built between 1886 and 1894, clad in Cornish granite and Portland stone at the City of London\'s insistence because an industrial structure at this location was considered unacceptable. It still raises for river traffic around 800 times a year. The paid attraction includes glass-floored high walkways 42 metres above the water and the Victorian engine rooms below, where the original hydraulic machinery is preserved entirely intact.',
    hours: 'Daily 09:30–17:30',
    tip: 'Check lift times on the website the day before — free to watch from the riverbank. The Victorian engine rooms are the underrated half of the paid ticket.',
    type: 'Victorian bascule bridge (1894) — London\'s most filmed landmark',
    website: 'https://www.towerbridge.org.uk',
  },
  {
    id: 24,
    nbhd: 'city',
    name: 'Tower of London',
    cat: 'royal',
    emoji: '👑',
    address: 'St Katharine\'s & Wapping, London EC3N 4AB',
    lat: 51.5081, lng: -0.0760,
    search: 'Tower of London Crown Jewels interior',
    note: 'Almost a thousand years of continuous royal use on the same half-mile of riverbank. William the Conqueror began it in 1078 as a demonstration of power to the city he had just conquered; every subsequent monarch added to it, used it, imprisoned in it or was imprisoned in it. The Crown Jewels are here — including the Imperial State Crown set with the Black Prince\'s Ruby, worn by Henry V at Agincourt — guarded under conditions of security that have not been tested since Colonel Blood stole the orb in 1671 and was pardoned by Charles II for the audacity of the attempt. The Yeoman Warders have guarded the Tower since 1485 and live within the walls with their families. Join a Yeoman Warder tour the moment you arrive — the stories do not appear in any guidebook. The Ceremony of the Keys has locked the Tower at 21:53 every night since the 14th century. Free to attend but requiring a booking months in advance.',
    hours: 'Tue–Sat 09:00–17:30; Sun–Mon 10:00–17:30',
    tip: 'Join a Yeoman Warder tour the moment you arrive. Book the Ceremony of the Keys months ahead. The Scaffold Site and Traitors\' Gate, not only the Jewel House.',
    type: 'Royal fortress and UNESCO World Heritage Site — nearly 1,000 years of royal history',
    website: 'https://www.hrp.org.uk/tower-of-london',
  },
  {
    id: 26,
    nbhd: 'city',
    name: 'Leadenhall Market',
    cat: 'film',
    emoji: '🎬',
    address: 'Gracechurch St, London EC3V 1LT',
    lat: 51.5135, lng: -0.0831,
    search: 'Leadenhall Market interior Victorian London ornate',
    note: 'Harry Potter and the Philosopher\'s Stone (2001): the entrance to the Leaky Cauldron — the hidden pub through which Harry enters Diagon Alley for the first time — was filmed at the optician\'s shop at 3 Bull\'s Head Passage inside Leadenhall Market. Stand at that corner and look at the painted ornamental ironwork in burgundy, green and cream, and understand why the production chose it: the market already looks like a fantasy. It was built in 1881 on a site with a market since the 14th century. On weekday mornings, suited financiers press through the amber light and the 19th century feels closer than usual. At weekends the market is almost entirely empty — a different but worthwhile version of the same space.',
    hours: 'Mon–Fri 10:00–18:00; largely empty at weekends',
    tip: 'Find 3 Bull\'s Head Passage for the Harry Potter connection. Weekday mornings for the authentic working atmosphere. Completely empty at weekends.',
    type: 'Ornate Victorian covered market (1881) — Harry Potter\'s Diagon Alley entrance',
    website: 'https://leadenhallmarket.co.uk',
  },
  {
    id: 27,
    nbhd: 'city',
    name: 'Duck and Waffle',
    cat: 'dining',
    emoji: '🧇',
    address: '110 Bishopsgate, London EC2N 4AY',
    lat: 51.5142, lng: -0.0820,
    search: 'Duck Waffle restaurant interior rooftop London City view',
    note: 'Open 24 hours on the 40th floor of Heron Tower, floor-to-ceiling windows and the full sweep of the City and Thames below. The signature — confit duck leg on a Belgian waffle with a fried duck egg and mustard maple syrup — sounds improbable and tastes inevitable. A sunrise booking at 06:30 is one of London\'s most dramatically staged breakfasts: the city waking below you, the room quieter than at any other hour, the light hitting the Thames at a low angle that makes the whole basin look liquid gold. This is the only 24-hour restaurant in London at height, and the sunrise slot is the correct way to use it.',
    hours: 'Open 24/7',
    tip: 'Book a sunrise slot weeks ahead — 06:30 means a quiet room and extraordinary light. The duck and waffle is non-negotiable.',
    type: 'London\'s only 24-hour high-rise restaurant — 40th floor City views',
    website: 'https://duckandwaffle.com',
  },
  {
    id: 28,
    nbhd: 'city',
    name: 'St Paul\'s Cathedral',
    cat: 'film',
    emoji: '🎬',
    address: 'St. Paul\'s Churchyard, London EC4M 8AD',
    lat: 51.5138, lng: -0.0984,
    search: 'St Paul\'s Cathedral interior dome Whispering Gallery London',
    note: 'The old woman on the cathedral steps sells birdseed for a tuppence a bag in Mary Poppins (1964) — that image, the steps of St Paul\'s, the dome behind her, is one of the most reproduced in British cinema. The Darkest Hour (2017), Doctor Strange (2016), The Da Vinci Code (2006) — the dome appears in so many films depicting London under threat or at its finest that Herbert Mason\'s 1940 photograph of the cathedral standing unharmed in the smoke of the Blitz became one of the defining images of the 20th century. The building Wren spent 35 years designing — he is buried in the crypt beneath it, the epitaph on the floor reading Lector, si monumentum requiris, circumspice — is worth the 528-step climb for the view alone. The Whispering Gallery inside the dome, 34 metres across, carries a whisper from one curved wall to the other in a phenomenon you have to test yourself to believe.',
    hours: 'Mon–Sat 08:30–16:30',
    tip: 'The Whispering Gallery first. Go early on a weekday for the climb without crowds. The crypt is underrated: Wellington and Nelson are both buried there.',
    type: 'Wren\'s masterpiece (1710) — as seen in Mary Poppins, Darkest Hour, and countless others',
    website: 'https://www.stpauls.co.uk',
  },
  {
    id: 62,
    nbhd: 'city',
    name: 'The Barbican',
    cat: 'art',
    emoji: '🏗️',
    address: 'Silk Street, Barbican, London EC2Y 8DS',
    lat: 51.5203, lng: -0.0928,
    search: 'Barbican Centre interior arts London concert hall gallery',
    note: 'Built on a Blitz bomb site and completed in the 1970s, the Barbican is the largest brutalist complex in Europe — three residential towers, 2,000 flats, two theatres, a concert hall, two cinemas, a gallery and an arts centre, all connected by a raised pedestrian walkway above the street. The architecture is deliberately disorienting: the walkways do not go where you expect, the courtyards open unexpectedly onto water, the lakeside terrace appears when you have given up looking for it. The arts programme is among the best in London: the resident London Symphony Orchestra is one of the finest in Europe; the gallery shows serious contemporary and design exhibitions; the cinema runs properly curated retrospectives. The glass conservatory — a tropical garden growing inside the City of London, free on Sundays — is one of the most genuinely strange and beautiful spaces in the square mile.',
    hours: 'Public walkways from 06:00; arts centre from 11:00',
    tip: 'Go without a plan and follow the walkways. The conservatory is free on Sundays and worth the trip on its own. Check the arts centre programme before visiting.',
    type: 'Brutalist arts complex — LSO, gallery, theatre, cinema (free to explore)',
    website: 'https://www.barbican.org.uk',
  },

  // ── COVENT GARDEN & SOHO ──────────────────────────────────────────────────

  {
    id: 75,
    nbhd: 'covent-garden',
    name: 'American Bar at The Savoy',
    cat: 'pub',
    emoji: '🥂',
    address: 'The Savoy, Strand, London WC2R 0EU',
    lat: 51.5104, lng: -0.1203,
    search: 'American Bar Savoy interior Art Deco cocktail London',
    note: 'The most historically significant drinking room in London. Harry Craddock wrote the Savoy Cocktail Book here in 1930 — a volume that defined the modern cocktail for a century. The Hanky Panky was invented here in 1925 by Ada Coleman, one of the first female head bartenders in London history. The Art Deco interior completed in 1927 is largely intact: the low ceiling, the piano corner, the amber light that made everything that happened in this room look like a story worth telling. The Corpse Reviver #2, from Craddock\'s original recipe, is the correct order. The piano starts at 19:30 and the service maintains standards that most contemporary cocktail bars treat as aspirational.',
    hours: 'Mon–Sat 14:00–00:00; Sun 14:00–23:00',
    tip: 'The Corpse Reviver #2 from the original Craddock recipe. Book ahead for weekends. The piano begins at 19:30.',
    type: 'Historic hotel bar — the birthplace of modern cocktail culture (1893)',
    website: 'https://www.thesavoylondon.com/restaurant/american-bar/',
  },
  {
    id: 29,
    nbhd: 'covent-garden',
    name: 'Covent Garden',
    cat: 'film',
    emoji: '🎬',
    address: 'Covent Garden, London WC2E 8RF',
    lat: 51.5117, lng: -0.1232,
    search: 'Covent Garden London',
    note: 'Audrey Hepburn sold flowers as Eliza Doolittle on these piazza steps in My Fair Lady (1964). The cobblestones appear in Oliver! (1968), in Paddington (2014), in Bridget Jones, in countless British period dramas that need a setting that reads immediately as old London. The market was saved from demolition in 1974 by one of the first successful community preservation campaigns in Britain, converting the Victorian trading floor into the covered market you walk through today. The piazza is the tourists\' London; the streets around it hold more. Cecil Court — a pedestrianised Edwardian alley of antiquarian booksellers, print dealers and map specialists one block west — has barely changed since the 1920s. Neal\'s Yard, through the alley off Short\'s Gardens, holds the finest British farmhouse cheese shop in the world.',
    hours: 'Piazza 24h; shops Mon–Sat 10:00–20:00; Sun 11:00–18:00',
    tip: 'Cecil Court for maps and prints. Neal\'s Yard for cheese. Seven Dials for independent shopping. The piazza is a starting point, not the destination.',
    type: 'Historic market piazza — as seen in My Fair Lady, Oliver!, Paddington, and others',
    website: 'https://www.coventgarden.london',
  },
  {
    id: 30,
    nbhd: 'covent-garden',
    name: 'Neal\'s Yard',
    cat: 'shop',
    emoji: '🌈',
    address: 'Neal\'s Yard, Covent Garden, London WC2H 9DP',
    lat: 51.5128, lng: -0.1262,
    search: 'Neal\'s Yard Dairy cheese shop interior London',
    note: 'A tiny courtyard accessible only through narrow alleys off Neal Street — buildings painted in clashing vivid colours around a central fountain, invisible from any main road. Neal\'s Yard Dairy occupies the corner and is the finest British farmhouse cheese shop in the world. They source whole wheels, age them in their Bermondsey cellar, and maintain direct relationships with the farms: Montgomery\'s Cheddar, Stichelton (unpasteurised Stilton), Hafod Welsh organic cheddar, Kirkham\'s Lancashire. The staff know the current condition of every wheel and will tell you exactly what is at its peak today. Buy more than you think you need.',
    hours: 'Mon–Sat 10:00–18:30; Sun 11:00–17:00',
    tip: 'Enter from Shorts Gardens or Neal Street. Ask what\'s at peak condition today and follow the answer entirely.',
    type: 'Hidden courtyard with the world\'s finest British farmhouse cheese shop',
    website: 'https://www.nealsyarddairy.co.uk',
  },
  {
    id: 31,
    nbhd: 'covent-garden',
    name: 'Clos Maggiore',
    cat: 'dining',
    emoji: '🌸',
    address: '33 King St, Covent Garden, London WC2E 8JD',
    lat: 51.5118, lng: -0.1243,
    search: 'Clos Maggiore conservatory interior blossom Covent Garden London',
    note: 'The conservatory is the reason to come, and you should say so clearly when you book. Twelve covers under a retractable glass roof with cherry blossom branches trailing overhead, candles on every table, the branches close enough to touch on warm evenings when the roof slides back. It is the most romantic dining room in London by the consistent verdict of everyone who eats there and does not stop talking about it afterward. The French cooking is serious — precisely sourced, technically disciplined — and earns its setting rather than hiding behind it. The set lunch on a weekday delivers the same kitchen at half the dinner price in a room that is quieter and, if anything, more beautiful in afternoon light. Book the conservatory table specifically, weeks ahead for weekends.',
    hours: 'Mon–Sat 12:00–14:30, 17:00–23:00; Sun 12:00–15:30, 17:00–22:00',
    tip: 'Specify the conservatory when booking — the dining room is good but not the point. Set lunch on a Tuesday or Wednesday for the quietest version of this room.',
    type: 'French restaurant — London\'s most romantic dining room',
    awards: '3 AA Rosettes (2026) · Wine Spectator Grand Award (2025) · \'Most Romantic Restaurant in the World\' — Architectural Digest',
    website: 'https://www.closmaggiore.com',
  },
  {
    id: 32,
    nbhd: 'covent-garden',
    name: 'Barrafina',
    cat: 'dining',
    emoji: '🦐',
    address: '10 Adelaide St, London WC2N 4HZ',
    lat: 51.5097, lng: -0.1239,
    search: 'Barrafina tapas counter interior London food',
    note: 'Counter seating only, no reservations, kitchen entirely open. Barrafina has been the benchmark for Spanish cooking in London since 2007 — the tortilla, the grilled fish, the cuttlefish in its own ink, the jamón carved from the leg hanging above the counter. The chefs know what is exceptional today and will tell you if you ask. Walk in, wait for a counter seat to open, and eat at it. The Adelaide Street branch is the original and still the best: the counter has the right angle to the kitchen, and the room has not changed since it opened. It held a Michelin star for over a decade — the cooking that earned it has not changed.',
    hours: 'Mon–Sat 12:00–15:00, 17:00–23:00; Sun 13:00–15:30, 17:00–22:00',
    tip: 'Walk-in only. Arrive before opening or accept the wait. Ask the chefs what they recommend today — the answer changes.',
    type: 'The benchmark for Spanish tapas in London — counter seats only, walk-in',
    website: 'https://barrafina.co.uk',
  },
  {
    id: 33,
    nbhd: 'covent-garden',
    name: 'Mr Fogg\'s Gin Parlour',
    cat: 'pub',
    emoji: '🌏',
    address: '1 New Row, London WC2N 4EA',
    lat: 51.5110, lng: -0.1241,
    search: 'Mr Fogg\'s Gin Parlour interior Victorian basement London',
    note: 'Down a staircase off New Row into a Victorian basement dressed as the private study of Phileas Fogg, hero of Around the World in Eighty Days: taxidermy, globes, butterfly specimens in cases, shelves of leather-bound books, trunks and instruments covering every surface. The inventory is over 300 gins organised by region and distillery, and the bartenders know it the way a good sommelier knows a cellar — ask what you are in the mood for and they will bring you something you would not have chosen yourself. The room holds perhaps 40 people and feels full at 20, which means it always has atmosphere and always requires a booking.',
    hours: 'Mon–Thu 15:00–midnight; Fri–Sat 12:00–01:00; Sun 12:00–midnight',
    tip: 'Book ahead — the room is small. Ask for recommendations from lesser-known distilleries. The bartenders have strong opinions.',
    type: 'Victorian gin parlour — 300+ gins, Around the World in 80 Days theme',
    website: 'https://mr-foggs.com/gin-parlour',
  },
  {
    id: 35,
    nbhd: 'covent-garden',
    name: 'Ronnie Scott\'s Jazz Club',
    cat: 'pub',
    emoji: '🎷',
    address: '47 Frith St, Soho, London W1D 4HT',
    lat: 51.5133, lng: -0.1314,
    search: 'Ronnie Scott\'s Jazz Club interior London stage performance',
    note: 'Ronnie Scott opened this basement on Frith Street in 1959 with £100 borrowed from a friend. Miles Davis played here. Nina Simone called it a second home. Jimi Hendrix gave his last ever public performance on this stage, ten days before he died. The room holds 250 and feels intimate regardless of who is on — the rectangular space and low ceiling work like a listening room, the sound collecting rather than dispersing. The late-night sessions that begin around 23:30 after the headline act are sometimes better than the show that preceded them: more spontaneous, cheaper, and the kind of thing you cannot plan for.',
    hours: 'Mon–Sat 18:00–03:00; Sun 18:00–midnight',
    tip: 'Book headline acts weeks ahead. The late session starts around 23:30 — cheaper, more spontaneous, occasionally unforgettable.',
    type: 'World-famous jazz club (since 1959) — Jimi Hendrix\'s last public performance',
    website: 'https://www.ronniescotts.co.uk',
  },
  {
    id: 37,
    nbhd: 'covent-garden',
    name: 'Opium Cocktail Bar',
    cat: 'pub',
    emoji: '🏮',
    address: '15–16 Gerrard St, London W1D 6JE',
    lat: 51.5119, lng: -0.1306,
    search: 'Opium cocktail bar interior lanterns Chinatown London',
    note: 'The door is on Gerrard Street in the middle of Chinatown, unmarked except for a small brass plate. Ring the bell, climb four flights past red silk lanterns and dark lacquered timber, and arrive in a bar that the 1920s Shanghai of imagination would have looked like. Three floors, low lighting, the smell of gardenia and warm spirits. The cocktails draw on Japanese whisky, Taiwanese gin, Chinese baijiu and Korean makgeolli in combinations that read as improbable on the menu and resolve completely in the glass. On weekends a performer takes the upper level — a Peking opera singer, a close-up magician, a jazz duo — and the evenings acquire a quality that nothing else in central London replicates.',
    hours: 'Mon–Tue 17:00–01:00; Wed–Thu 17:00–02:00; Fri–Sat 17:00–03:00; Sun 17:00–midnight',
    tip: 'Book ahead for weekends. Ask what spirit the bar manager is currently obsessed with — the answer changes and is always interesting.',
    type: '1920s Shanghai cocktail bar above Chinatown',
    website: 'https://www.opiumchinatown.com',
  },
  {
    id: 38,
    nbhd: 'covent-garden',
    name: 'Bob Bob Ricard',
    cat: 'dining',
    emoji: '🍾',
    address: '1 Upper James St, Soho, London W1F 9DF',
    lat: 51.5124, lng: -0.1389,
    search: 'Bob Bob Ricard restaurant interior booth champagne London',
    note: 'A Soho brasserie built around one brilliant conceit: a Press for Champagne button at every leather booth, connected directly to the bar. The room — lacquered blue and gold, mirrored ceilings, all the glamour of a private railway carriage — is exactly as theatrical as that button implies. The food is a serious brasserie menu of British and Russian classics: beef Wellington, lobster thermidor, chicken Kiev made correctly with the butter sealed inside. Press the button. Order the beef Wellington. That is the correct evening, and it has been the correct evening since the restaurant opened in 2008.',
    hours: 'Daily 12:30–15:00, 18:00–23:30',
    tip: 'Book ahead. The beef Wellington is the kitchen\'s signature. Budget from £70 per person with something pressed for.',
    type: 'Theatrical brasserie with champagne button at every table',
    website: 'https://bobbobricard.com',
  },
  {
    id: 72,
    nbhd: 'covent-garden',
    name: 'Rules',
    cat: 'dining',
    emoji: '🍮',
    address: '35 Maiden Lane, Covent Garden, London WC2E 7LB',
    lat: 51.5115, lng: -0.1237,
    search: 'Rules restaurant interior dining room Covent Garden London',
    note: 'Established in 1798 on Maiden Lane and still on the same site — London\'s oldest restaurant, which means the room has been serving dinner since before Waterloo, before the railways, before photography. The walls are layered with theatrical portraits, cartoons and accumulated objects from 225 years of continuous trade. Dickens was a regular. Graham Greene wrote here. King Edward VII brought Lillie Langtry to the private upstairs room he rented for the purpose. The menu is British game and traditional dishes executed with a confidence that comes from being right about them for over two centuries: potted shrimps, roast grouse in season from the restaurant\'s own Teesdale estate, suet puddings of the kind that have not survived anywhere else.',
    hours: 'Mon–Sat 12:00–23:30; Sun 12:00–22:30',
    tip: 'Order game — it is what this kitchen has done for 225 years. Potted shrimps to start, a suet pudding to finish. Book ahead for weekends.',
    type: 'London\'s oldest restaurant (established 1798)',
    website: 'https://rules.co.uk',
  },
  {
    id: 69,
    nbhd: 'covent-garden',
    name: 'The Palomar',
    cat: 'dining',
    emoji: '🫙',
    address: '34 Rupert St, Soho, London W1D 6DN',
    lat: 51.5121, lng: -0.1326,
    search: 'The Palomar restaurant interior counter Soho London food',
    note: 'The cooking draws on Jerusalem and the whole Eastern Mediterranean — the spice routes, the Ottoman inheritance, the Levantine coast — and at its best it is some of the most interesting food in London. The Jerusalem-style hummus arrives warm and silky with a pool of cold-pressed olive oil and a handful of spiced chickpeas; it is one of the finest plates in the city and costs under £10. The lamb neck is slow-cooked until it pulls apart under a fork, layered with burned yogurt and sweet charred onion. Counter seats at the open kitchen pass are where the room comes alive — the chefs explain every dish as it arrives, the kitchen runs at full speed, and the energy concentrates at those seats in a way the dining room behind cannot match. Book ahead for the dining room; try the counter walk-in at lunch.',
    hours: 'Mon–Sat 12:00–14:30, 17:30–22:30; Sun 12:00–15:30',
    tip: 'Counter seats at the pass if available. The hummus first, then the lamb neck. Ask what raw fish is on today.',
    type: 'Jerusalem and Eastern Mediterranean restaurant',
    awards: 'Michelin Bib Gourmand 2026',
    website: 'https://www.thepalomar.co.uk',
  },
  {
    id: 68,
    nbhd: 'covent-garden',
    name: 'The French House',
    cat: 'pub',
    emoji: '🥂',
    address: '49 Dean St, Soho, London W1D 5BG',
    lat: 51.5130, lng: -0.1330,
    search: 'French House Soho pub interior bar London',
    note: 'The most historically layered drinking room in Soho. De Gaulle used this as the informal London headquarters of the Free French during the Second World War — Resistance fighters, exiles and refugees drank here while London burned. After the war: Dylan Thomas, Francis Bacon, Lucian Freud. The house rules have not changed: wine and spirits only, and — uniquely in London — no pints, only halves. The room is small, crowded and exactly right. Upstairs, a restaurant runs one of the more interesting lunch menus in Soho. The building is a living memory of a city that harboured everyone it needed to.',
    hours: 'Mon–Sat 12:00–23:00; Sun 12:00–22:30',
    tip: 'The half-pint rule means order wine. Book the restaurant upstairs for lunch. Arrive before 19:00 for space at the bar.',
    type: 'Soho institution — the Free French HQ in WWII (est. 1891)',
    website: 'https://frenchhousesoho.com',
  },
  {
    id: 79,
    nbhd: 'covent-garden',
    name: 'Dover Street Market',
    cat: 'shop',
    emoji: '🛍️',
    address: '18–22 Haymarket, London SW1Y 4DQ',
    lat: 51.5073, lng: -0.1323,
    search: 'Dover Street Market interior London fashion retail',
    note: 'Rei Kawakubo of Comme des Garçons opened the original Dover Street Market in 2004 and moved it to this six-floor building on Haymarket in 2016. The concept is what she designed it to be: not a boutique and not a department store but something closer to a curated art installation that happens to sell clothes. Each floor is redesigned periodically by different creatives; the spaces change character without warning. The edit is Kawakubo\'s: Comme des Garçons in every line, Balenciaga, Gucci, Thom Browne, Y/Project, Simone Rocha, and a selection of emerging labels not available in the same room anywhere else in London. The Rose Bakery café at the top of the building is the correct place to pause.',
    hours: 'Mon–Sat 11:00–19:00; Sun 12:00–18:00',
    tip: 'Walk every floor — the edit on each is different. The Rose Bakery at the top for the break. Nothing here is cheap; most of it is not available anywhere else.',
    type: 'Rei Kawakubo\'s radical concept store — Haymarket (originally Dover Street)',
    website: 'https://london.doverstreetmarket.com',
  },
  {
    id: 80,
    nbhd: 'covent-garden',
    name: 'Liberty London',
    cat: 'shop',
    emoji: '🏰',
    address: 'Regent Street, London W1B 5AH',
    lat: 51.5138, lng: -0.1402,
    search: 'Liberty London interior Tudor atrium department store',
    note: 'Arthur Lasenby Liberty opened his first shop in 1875 selling Japanese and Oriental goods on Regent Street, and the Art Nouveau and Japanese aesthetic movements in Britain ran largely through his taste. The current Tudor Revival building — completed in 1924, constructed from the timbers of two decommissioned Royal Navy warships, HMS Hindustan and HMS Impregnable — is the most beautiful department store in the world and one of the only independently owned ones still operating in London. The Liberty print fabrics, in the distinctive small-scale florals produced since the 1870s, are sold by the metre in the haberdashery department. The rest of the building holds beauty, accessories, homeware, fashion and art presented with a curatorial intelligence that chain stores cannot replicate. Walk every floor.',
    hours: 'Mon–Sat 10:00–20:00; Sun 12:00–18:00',
    tip: 'Walk every floor. The Tudor interior — exposed beams, galleried atria — is as much the reason to come as anything for sale.',
    type: 'The world\'s most beautiful department store (est. 1875)',
    website: 'https://www.libertylondon.com',
  },

  // ── CAMDEN & KING\'S CROSS ─────────────────────────────────────────────────

  {
    id: 67,
    nbhd: 'camden',
    name: 'Coal Drops Yard',
    cat: 'shop',
    emoji: '🏗️',
    address: 'Stable St, King\'s Cross, London N1C 4AB',
    lat: 51.5357, lng: -0.1238,
    search: 'Coal Drops Yard interior architecture King\'s Cross London',
    note: 'Two Victorian coal drops from the 1850s, where barges unloaded coal into storage yards above the railway. Thomas Heatherwick converted them in 2018, arching the two Victorian iron roofs toward each other until they meet and touch at the apex — an engineering gesture that creates an outdoor retail destination unlike anything else in London. The independent edit is the best in King\'s Cross: Paul Smith, Tom Dixon, Wolf & Badger, Aesop, smaller boutiques with considered selections. Cross the canal from Granary Square and find it behind the fountains. Walk through at dusk when the roofline is lit and the iron turns warm. The architecture is always the reason to come first; what is inside is the reason to stay.',
    hours: 'Shops Mon–Sat 10:00–20:00; Sun 11:00–18:00; restaurants vary',
    tip: 'Walk through at dusk when the roofline is lit. The architecture is the point — the shops are the bonus.',
    type: 'Heatherwick-designed Victorian coal drops — independent boutiques, King\'s Cross',
    website: 'https://coaldropsyard.com',
  },
  {
    id: 40,
    nbhd: 'camden',
    name: 'Wellcome Collection',
    cat: 'art',
    emoji: '🔬',
    address: '183 Euston Rd, London NW1 2BE',
    lat: 51.5258, lng: -0.1320,
    search: 'Wellcome Collection interior exhibition museum London',
    note: 'Sir Henry Wellcome was a pharmaceutical millionaire who spent his fortune acquiring objects at the intersection of medicine, science, death and human experience. The permanent collection is unlike anything else in London: Napoleon\'s toothbrush, Darwin\'s walking stick, a 2,000-year-old Egyptian mummy\'s hair, Roman surgical instruments that still look functional, a 15th-century Italian ivory anatomical figure, Victorian electroshock equipment, a complete 18th-century apothecary\'s dispensary. They are displayed without hierarchy or sentimentality — a medieval chastity belt beside contemporary HIV medication, both treated as equally serious objects. The museum\'s refusal to arrange human experience into comfortable categories gives it a quality most institutions cannot manufacture. The temporary exhibitions are consistently the most rigorously conceived in London. Free, chronically undervisited, and two hours is genuinely not enough.',
    hours: 'Tue–Wed, Fri–Sat 10:00–18:00; Thu 10:00–20:00; Sun 11:00–18:00; closed Mon',
    tip: 'Free always. Thursday evenings for the quietest visit. Allow three hours. Follow whatever holds your attention.',
    type: 'Free museum at the intersection of medicine, science and art',
    website: 'https://wellcomecollection.org',
  },

  // ── NOTTING HILL ──────────────────────────────────────────────────────────

  {
    id: 43,
    nbhd: 'notting-hill',
    name: 'Portobello Road Market',
    cat: 'shop',
    emoji: '🎨',
    address: 'Portobello Rd, Notting Hill, London W11',
    lat: 51.5163, lng: -0.2033,
    search: 'Portobello Road antiques market stalls London',
    note: 'Over a mile of stalls through Notting Hill. On Saturdays, over 1,000 antique dealers occupy the southern section — the world\'s largest antique street market by dealer count. Victorian silver, Art Deco jewellery, Georgian furniture, vintage watches, maps, prints, curiosities of every description. The middle section runs fruit, vegetables and street food through the week. The northern end under the Westway flyover has the best vintage clothing with half the Saturday crowds. The surrounding pastel-painted terraces are what separate Portobello from every other London market neighbourhood — the shopping is the pretext for the walk.',
    hours: 'Antiques: Sat 08:00–19:00; General market: Mon–Fri 09:00–18:00',
    tip: 'Arrive before 09:00 on Saturdays for antiques. The northern end under the Westway has the best vintage with far fewer people.',
    type: 'World\'s largest antique street market — Saturdays, Notting Hill',
    website: 'https://www.portobelloroad.co.uk',
  },
  {
    id: 44,
    nbhd: 'notting-hill',
    name: 'Core by Clare Smyth',
    cat: 'dining',
    emoji: '⭐',
    address: '92 Kensington Park Rd, London W11 2PN',
    lat: 51.5176, lng: -0.2007,
    search: 'Core Clare Smyth restaurant interior Notting Hill London food',
    note: 'Clare Smyth was the first woman to hold three Michelin stars in her own name in the UK, earned at Restaurant Gordon Ramsay before she opened Core in 2017. The cooking is built on British produce treated with the rigour of classical French technique. The signature potato and roe dish — a single perfect potato slow-cooked in beef fat until the skin lacquers, topped with herring roe and coastal herbs — is simultaneously the simplest and the most technically accomplished thing on the menu. The full tasting menu runs fourteen courses and takes the better part of three hours. The set lunch at £75 delivers the same kitchen, the same sourcing and the same level of care at considerably lower cost — one of the best-value serious lunches in London. Book weeks ahead.',
    hours: 'Tue–Sat 12:00–14:00, 18:30–22:00; closed Sun–Mon',
    tip: 'The set lunch is the right entry point — same kitchen, half the tasting menu price. Book weeks ahead. The wine pairings are serious.',
    type: 'Three Michelin-star restaurant — Notting Hill',
    awards: '⭐⭐⭐ Three Michelin Stars · 5 AA Rosettes · La Liste 98/100 (2025)',
    website: 'https://corebyclaresmyth.com',
  },
  {
    id: 47,
    nbhd: 'notting-hill',
    name: 'Electric Cinema',
    cat: 'film',
    emoji: '🎬',
    address: '191 Portobello Rd, Notting Hill, London W11 2ED',
    lat: 51.5161, lng: -0.2007,
    search: 'Electric Cinema interior leather armchairs Notting Hill London',
    note: 'Julia Roberts and Hugh Grant went to the cinema in Notting Hill (1999), and it was this cinema. The Electric has been on Portobello Road since 1910, making it one of the oldest working cinemas in Britain, and the film chose it because leather armchairs, footstools, sofas and full bar service already made it unlike anywhere else in London. The double sofa seats at the front exist precisely for what you are thinking. The Edwardian building retains enough of its original character that an evening here is an occasion rather than simply a showing. The programme runs art house and mainstream releases with equal conviction. Book sofa seats for anything you particularly want to see; they sell out.',
    hours: 'Shows daily from approximately 12:00',
    tip: 'Book the double sofa seats for anything special — they sell out. Bar service runs throughout the show.',
    type: 'Luxury independent cinema (opened 1910) — as seen in Notting Hill (1999)',
    website: 'https://www.electriccinema.co.uk',
  },

  // ── KENSINGTON ────────────────────────────────────────────────────────────

  {
    id: 49,
    nbhd: 'kensington',
    name: 'Victoria & Albert Museum',
    cat: 'art',
    emoji: '🏺',
    address: 'Cromwell Rd, Kensington, London SW7 2RL',
    lat: 51.4966, lng: -0.1722,
    search: 'Victoria Albert Museum interior gallery London Cast Courts',
    note: 'The world\'s greatest museum of art and design: 2.3 million objects, 145 galleries, 5,000 years of human creative output from Japanese armour to Raphael cartoons to the wedding dress Vivienne Westwood wore in 1992. The Cast Courts on Level 1 are two Victorian halls containing plaster casts of Trajan\'s Column — split in two because the real thing is 38 metres tall — Michelangelo\'s David and every other major European monument. The ambition and scale of the Victorian project is its own kind of art. The Medieval and Renaissance Galleries run from Byzantine ivories to Holbein miniatures. The Fashion Gallery holds four centuries of dress. The design collections span Islamic tiles, Chinese ceramics, Renaissance bronzes and 20th-century industrial design in rooms that connect unexpectedly. Friday evenings after 18:00: emptier, atmospheric, often with live music in the courtyard. Free.',
    hours: 'Daily 10:00–17:45; Fri until 22:00',
    tip: 'Friday evenings after 18:00 — emptier and more atmospheric. The Cast Courts first, then follow wherever the building takes you. Two full visits is not too many.',
    type: 'World\'s greatest art and design museum (free)',
    website: 'https://www.vam.ac.uk',
  },
  {
    id: 52,
    nbhd: 'kensington',
    name: 'The Harwood Arms',
    cat: 'dining',
    emoji: '🥩',
    address: 'Walham Grove, Fulham, London SW6 1QP',
    lat: 51.4787, lng: -0.1946,
    search: 'Harwood Arms interior pub food Fulham London',
    note: 'London\'s only Michelin-starred pub, on a quiet Fulham street that looks entirely ordinary from the outside. The kitchen focuses on British game and seasonal produce handled with genuine technical precision. The venison Scotch egg — the yolk still running, the game forcemeat precisely seasoned, the coating shatteringly crisp — has accumulated more critical attention than most restaurant dishes in London. The Sunday roast books up months in advance, not weeks, which tells you everything you need to know about the quality. The weekday dinner is more accessible and the same kitchen.',
    hours: 'Mon–Fri 18:00–22:00; Sat 12:00–15:00, 18:00–22:00; Sun 12:00–15:30',
    tip: 'Sunday lunch: book months ahead. Weekday dinner is more accessible and identical quality. The venison Scotch egg.',
    type: 'London\'s only Michelin-starred pub — Fulham',
    awards: '⭐ One Michelin Star · London\'s only Michelin-starred pub · Top 50 Gastropubs UK',
    website: 'https://www.harwoodarms.com',
  },
  {
    id: 82,
    nbhd: 'kensington',
    name: 'Kensington Palace',
    cat: 'royal',
    emoji: '👑',
    address: 'Kensington Palace, Kensington Gardens, London W8 4PX',
    lat: 51.5051, lng: -0.1877,
    search: 'Kensington Palace interior state rooms London',
    note: 'William III bought this as a private residence in 1689 — he preferred it to Whitehall because the Kensington air did not aggravate his asthma — and it has been a royal residence ever since. Queen Victoria was born here in 1819, grew up under the controlling Kensington System that kept her isolated from the world, and received her first ministers in this building at 06:00 on the morning she became Queen. Princess Diana had her private apartments here until 1997; the flowers left at the gates after her death formed a pile six feet deep for a quarter-mile. The Prince and Princess of Wales live here now in Apartment 1A. The State Rooms — including Victoria\'s bedroom and the King\'s Staircase — are open to visitors, and the Sunken Garden below the south terrace, redesigned with white flowers as a memorial to Diana in 2017, is free to enter.',
    hours: 'Daily 10:00–18:00 (seasonal variations; check website)',
    tip: 'Book tickets in advance. The Sunken Garden is free and worth visiting independently. The exhibition on Queen Victoria\'s early life is unexpectedly moving.',
    type: 'Royal residence since 1689 — birthplace of Queen Victoria, home of the Prince and Princess of Wales',
    website: 'https://www.hrp.org.uk/kensington-palace',
  },
  {
    id: 77,
    nbhd: 'kensington',
    name: 'Serpentine Galleries',
    cat: 'art',
    emoji: '🏛️',
    address: 'Kensington Gardens, London W2 3XA',
    lat: 51.5054, lng: -0.1735,
    search: 'Serpentine Gallery interior contemporary art London',
    note: 'Two galleries in Kensington Gardens — the Serpentine South in a 1934 former tea pavilion, the Serpentine North across the bridge — show some of the most ambitious contemporary and experimental art programming in London, always free. The annual Serpentine Pavilion commission has run since 2000 and is one of the most significant architectural events in the world: each year a major architect who has not previously built in the UK is invited to design a temporary structure in the park. Zaha Hadid opened the series. Then Oscar Niemeyer, Frank Gehry, Herzog & de Meuron, Rem Koolhaas — the list is a complete history of 21st-century architecture. The pavilion stands from June through October alongside the gallery programme.',
    hours: 'Tue–Sun 10:00–18:00; closed Mon; Pavilion Jun–Oct',
    tip: 'Free entry always. The annual Pavilion is open June through October — visit for the building as much as the art programme.',
    type: 'Contemporary art galleries in Hyde Park — free, with annual architect-designed Pavilion (since 2000)',
    website: 'https://www.serpentinegalleries.org',
  },
  {
    id: 76,
    nbhd: 'kensington',
    name: 'Saatchi Gallery',
    cat: 'art',
    emoji: '🖌️',
    address: 'Duke of York\'s HQ, King\'s Road, Chelsea, London SW3 4SQ',
    lat: 51.4915, lng: -0.1606,
    search: 'Saatchi Gallery interior exhibition Chelsea London',
    note: 'Charles Saatchi began his gallery in 1985 and used it to introduce Damien Hirst, Tracey Emin and the Young British Artists to the world — shows that changed British art permanently. The Chelsea location, in a Georgian military building on King\'s Road, has been open since 2008 and maintains the gallery\'s position as the place where emerging international art gets its most significant early platform in London. Entry is always free. The programme mixes established names with artists making their first major institutional shows, and the scale of the building — a former parade ground converted into a sequence of high, clean galleries — allows work that commercial galleries cannot house. The current exhibition determines everything; check the website before visiting.',
    hours: 'Daily 10:00–18:00',
    tip: 'Free always. Check the website for the current exhibition — the programme changes and ranges from revelatory to important.',
    type: 'Contemporary art gallery — free, Chelsea (home of the Young British Artists)',
    website: 'https://www.saatchigallery.com',
  },

  // ── SHOREDITCH & SPITALFIELDS ─────────────────────────────────────────────

  {
    id: 63,
    nbhd: 'shoreditch',
    name: 'Dennis Severs\' House',
    cat: 'film',
    emoji: '🎬',
    address: '18 Folgate St, Spitalfields, London E1 6BX',
    lat: 51.5218, lng: -0.0758,
    search: 'Dennis Severs House interior candlelit Spitalfields London',
    note: 'The most cinematically constructed interior in London, and the most extraordinary thing in the city that almost no one knows about. In 1979 the American artist Dennis Severs bought a Georgian terraced house in Spitalfields and spent his life constructing a \'still-life drama\': ten rooms across 300 years, as if the Huguenot silk-weaver family who lived here from 1724 has just stepped out. Candles burning. Food half-eaten on the table. A coat still warm near the fire. The smell of oranges, wood smoke, damp linen. The BBC and various film and television productions have used the house as a period drama location, because nothing better has been built to replicate Georgian London. The Monday evening candlelit session — in which you move through it in complete silence — is more cinematically constructed than almost anything playing in a London cinema that week. Nothing else in any city approaches it.',
    hours: 'Sun 12:00–16:00; Mon 12:00–14:00; Mon evenings 18:00–21:00 (must book)',
    tip: 'Book the Monday evening candlelit session specifically — it is the intended experience. Nothing in London approaches it.',
    type: 'London\'s most cinematic interior — an 18th-century still-life drama in Spitalfields',
    website: 'https://www.dennissevershouse.co.uk',
  },

];
