// A Perfect Story Map — Family Edition
// familystorymap / data.js — 21 places from FamilyMemories_Part1 (written by Anna,
// mapped July 2026). Who lived where, and when — across four family branches:
//   Friedland (mother's side) · Kliot (father's side) · Lando & Schechter
//   (husband's side, incl. Roza's story) · the war years · Israel
// Text is bilingual: Hebrew first, Russian second (pre-line + plaintext bidi
// CSS in index.html renders each paragraph in its own direction).
// Regions (nbhd): belarus · russia · east · ukraine · israel
// ⚠️ nbhd keys here must match map.js NBHD_* and the bubbles in index.html.

const PLACES = [

  // ── BELARUS & LITHUANIA — the roots ──────────────────────────────────────

  {
    id: 1,
    nbhd: 'belarus',
    name: 'רצ׳יצה · Речица · Rechytsa',
    cat: 'friedland',
    emoji: '🪡',
    icon: 'shop',
    address: 'בלארוס · Беларусь · Belarus',
    years: '~1890–1910',
    lat: 52.3622, lng: 30.3910,
    search: 'Rechytsa Речица רציצה פרידלנד Friedland Sam sewing machine',
    note: 'כאן, ובבוברויסק הסמוכה, חיה משפחת פרידלנד — משפחתו של סבא זלמן (זָחַר), על אביו יוסף (יוֹסי) ואמו זינה (זישה), בעיירות עם אוכלוסייה יהודית גדולה. מכאן, סביב 1910, ברח האח הבכור בן ה־16, שנשאר בזיכרון כשמואל: הוא לקח את מכונת התפירה — הנדוניה של אחותו — מכר אותה בעיירה סמוכה, קנה כרטיס לאמריקה והשאיר פתק התנצלות. באמריקה נהיה סם פרידלנד, נגר ואחר כך איש פרסום בחלונות ראווה, החזיר את החוב ושנים אחר כך חזר לבקר — ב־1957 וב־1964.\n\nЗдесь и в соседнем Бобруйске жила семья Фридланд — семья деда Залмана (Захара), его отца Иосифа (Йоси) и матери Зины (Зиши). Отсюда около 1910 года сбежал старший брат, оставшийся в памяти семьи как Шмуэль: он взял швейную машинку — приданое сестры, — продал её в соседнем местечке, купил билет в Америку и оставил записку с извинениями. В Америке он стал Сэмом Фридландом, столяром, а затем предпринимателем в рекламе на витринах; долг семье он вернул, а спустя десятилетия приехал повидаться — в 1957 и 1964 годах.\n\nHere, and in nearby Bobruisk, lived the Friedland family: the family of grandfather Zalman (Zakhar), his father Yosef (Yosi) and mother Zina (Zisha), in shtetls with large Jewish communities. From here, around 1910, the eldest brother, remembered as Shmuel, ran away at sixteen: he took the sewing machine that was his sister\'s dowry, sold it in a nearby town, bought a ticket to America and left a note of apology. In America he became Sam Friedland, a carpenter and later a window-display advertising man; he repaid the debt, and decades later came back to visit in 1957 and in 1964.',
    book: 'שורשי משפחת פרידלנד · Корни семьи Фридланд · The roots of the Friedland family',
    noDirections: true,
    visit: 'רצ׳יצה שוכנת על נהר הדנייפר, מחוז גומל. הקהילה היהודית הגדולה שלה נספתה ברובה בשואה.\nРечица стоит на Днепре, Гомельская область. Её большая еврейская община почти вся погибла в Катастрофе.\nRechytsa stands on the Dnieper, Gomel region. Most of its large Jewish community perished in the Holocaust.',
    type: 'משפחת פרידלנד: יוסף, זינה וילדיהם · Семья Фридланд: Иосиф, Зина и их дети · The Friedland family: Yosef, Zina and their children',
  },
  {
    id: 2,
    nbhd: 'belarus',
    name: 'בוברויסק · Бобруйск · Bobruisk',
    cat: 'friedland',
    emoji: '🏘️',
    icon: 'town',
    address: 'בלארוס · Беларусь · Belarus',
    years: 'עד יוני 1941 · до июня 1941 · until June 1941',
    lat: 53.1446, lng: 29.2214,
    search: 'Bobruisk Бобруйск בוברויסק Friedland Zalman Malka Nina Nechama ghetto Ida Berezina',
    note: 'העיר של סבא זלמן (זחר) פרידלנד וסבתא מלכה — הוא התאהב בה ממבט ראשון "ואהב אותה כפי שאיש לא אהב מעולם". כאן נולדה אמא, נחמה — לימים נינה — ולמדה עד כיתה ז׳ בבית ספר יהודי ביידיש. ב־22 ביוני 1941 שמעה את הפיצוצים הראשונים בקייטנת הפיונרים; ב־28 ביוני העיר נכבשה. מי שהספיק חצה את נהר הברזינה וברח — בלה ההרה עם גיגית לתינוק, פולינה בת ה־13 בשתי שמלות זו על גבי זו, גרישה הקטן. הצבא הנסוג פוצץ את הגשר. מהמשפחה שנשארה כמעט איש לא שרד: בגטו בוברויסק נרצחה אידה, אחות סבא המדהימה ביופיה, כשהתינוק שלה בזרועותיה.\n\nГород деда Залмана (Захара) Фридланда и бабушки Малки — он влюбился в неё с первого взгляда «и любил так, как никто никогда не любил другого человека». Здесь родилась мама, Нехама — позже Нина, — училась до седьмого класса в еврейской школе на идише. 22 июня 1941 года она услышала первые взрывы в пионерском лагере; 28 июня город был захвачен. Кто успел — перешёл Березину и бежал: беременная Белла с корытом для будущего ребёнка, тринадцатилетняя Полина в двух платьях, надетых одно на другое, маленький Гриша. Отступающая армия взорвала мост. Из оставшихся в городе почти никто не выжил: в бобруйском гетто погибла Ида, красавица-сестра деда, с младенцем на руках.\n\nThe town of grandfather Zalman (Zakhar) Friedland and grandmother Malka. He fell in love at first sight "and loved her as no one ever loved another human being." Mother was born here, Nechama, later Nina, and studied through seventh grade at a Jewish school in Yiddish. On June 22, 1941 she heard the first explosions at the Pioneer summer camp; on June 28 the city fell. Those who managed crossed the Berezina and fled: pregnant Bella carrying a washtub for the baby to come, thirteen-year-old Polina wearing her two good dresses one over the other, little Grisha. The retreating army blew up the bridge. Of the family who stayed, almost no one survived: in the Bobruisk ghetto Ida, grandfather\'s strikingly beautiful sister, was murdered with her baby in her arms.',
    book: 'הבית של צד אמא, עד המלחמה · Дом маминой семьи до войны · The home of mother\'s family, until the war',
    noDirections: true,
    visit: 'בוברויסק שוחררה רק ב־29 באוגוסט 1944. כמעט כל יהודי העיר נספו בגטו.\nБобруйск был освобождён только 29 августа 1944 года. Почти все евреи города погибли в гетто.\nBobruisk was liberated only on August 29, 1944. Almost all the city\'s Jews perished in the ghetto.',
    type: 'זלמן ומלכה פרידלנד; נינה, בלה, פולינה וגרישה; אידה ז״ל · Залман и Малка Фридланд; Нина, Белла, Полина, Гриша; погибшая Ида · Zalman and Malka Friedland; Nina, Bella, Polina and Grisha; Ida z"l',
  },
  {
    id: 3,
    nbhd: 'belarus',
    name: 'דריסה · Дрисса · Drissa',
    cat: 'kliot',
    emoji: '🏡',
    icon: 'birth',
    address: 'כיום וֵרְחְנֶדְבִינְסְק, בלארוס · ныне Верхнедвинск · now Verkhnyadzvinsk, Belarus',
    years: '1910',
    lat: 55.7770, lng: 27.9400,
    search: 'Drissa Verkhnyadzvinsk Дрисса Верхнедвинск דריסה קליוט Kliot Benjamin born 1910',
    note: 'עיירה בלארוסית קטנה, כיום וֵרְחְנֶדְבִינְסְק, שבה נולד אבא — בנימין ברוך יוסיפוביץ׳ קליוט — בשנת 1910, במשפחה גדולה ונאמנה לשורשיה היהודיים. ב־1905 היו בעיירה 525 בתי עץ ו־25 בתי אבן, מפעלים, בית ספר עירוני, חדר, בית ספר למלאכה, בית חולים ובית מרקחת. אביו — סבא יוסף איציקוביץ׳ קליוט (1882–1957), אמו — אֵתה־שרה (שוֹרה) לייבובנה סבירסקי (1884–1949).\n\nМаленькое белорусское местечко, ныне Верхнедвинск, где в 1910 году родился отец — Вениамин Барух Иосифович Клиот, в большой семье, верной своим еврейским корням. В 1905 году здесь было 525 деревянных и 25 каменных домов, фабрики, городское училище, хедер, ремесленная школа, больница и аптека. Его отец — дед Иосиф Ицикович Клиот (1882–1957), мать — Эта-Сара (Шора) Лейбовна Свирская (1884–1949).\n\nA small Belarusian shtetl, today Verkhnyadzvinsk, where father, Benjamin Baruch Yosifovich Kliot, was born in 1910, into a large family faithful to its Jewish roots. In 1905 the town had 525 wooden houses and 25 of stone, factories, a town school, a cheder, a trade school, a hospital and a pharmacy. His father was grandfather Yosef Itzikovich Kliot (1882–1957); his mother was Eta-Sara (Shora) Leibovna Svirsky (1884–1949).',
    book: 'הולדת אבא, צד קליוט · Рождение отца, линия Клиот · Father\'s birth: the Kliot line',
    noDirections: true,
    visit: 'מ־3 ביולי 1941 עד 12 ביולי 1944 הייתה דריסה תחת כיבוש גרמני; כמעט כל יהודי העיירה נספו.\nС 3 июля 1941 до 12 июля 1944 года Дрисса была под немецкой оккупацией; почти все евреи местечка погибли.\nFrom July 3, 1941 to July 12, 1944 Drissa was under German occupation; almost all the town\'s Jews perished.',
    type: 'בנימין קליוט נולד כאן; הוריו יוסף ואתה־שרה · Здесь родился Вениамин Клиот; его родители Иосиф и Эта-Сара · Benjamin Kliot was born here; his parents Yosef and Eta-Sara',
  },
  {
    id: 4,
    nbhd: 'belarus',
    name: 'סְבִינְציאני · Свенцяны · Svencionys',
    cat: 'kliot',
    emoji: '🏪',
    icon: 'shop',
    address: 'שוונצ׳יוניס, ליטא · Швянчёнис, Литва · Švenčionys, Lithuania',
    years: '1910–1919',
    lat: 55.1330, lng: 26.1550,
    search: 'Svencionys Švenčionys Свенцяны סבינציאני Kliot grocery store shtetl',
    note: 'אחרי 1910 עברה משפחת קליוט לעיירה סמוכה לתחנת רכבת, כיום שוונצ׳יוניס במזרח ליטא. סבא יוסף פתח בה מכולת קטנה — והצליח בזכות הלשונות שבפיו: פולנית, ליטאית, בלארוסית, רוסית, וכמובן יידיש שבה דיברו בבית. כך תקשר בקלות עם כל מי שנכנס לקנות דברים קטנים לבית. במשפחה כזו גדל אבא עם אחיו ואחיותיו: סוניה, אפרים, מיכאל, פאניה, רבקה ורעיה.\n\nПосле 1910 года семья Клиот перебралась в местечко у железнодорожной станции — ныне Швянчёнис на востоке Литвы. Дед Иосиф открыл здесь маленькую бакалейную лавку — и преуспел благодаря языкам: польскому, литовскому, белорусскому, русскому и, конечно, идишу, на котором говорили дома. Так он легко находил общий язык с каждым покупателем. В этой семье рос отец со своими братьями и сёстрами: Соней, Эфраимом, Михаилом, Фаней, Ривкой и Раей.\n\nAfter 1910 the Kliot family moved to a shtetl by a railway station: today Švenčionys in eastern Lithuania. Grandfather Yosef opened a small grocery, and prospered thanks to his languages: Polish, Lithuanian, Belarusian, Russian and, of course, the Yiddish spoken at home. So he easily found common ground with every customer. In this family father grew up with his brothers and sisters: Sonya, Efraim, Michael, Fanya, Rivka and Raya.',
    book: 'המכולת של סבא יוסף · Лавка деда Иосифа · Grandfather Yosef\'s grocery',
    noDirections: true,
    visit: 'שוונצ׳יוניס שוכנת כ־85 ק״מ צפונית־מזרחית לווילנה; העיירה הייתה מרכז יהודי חשוב עד השואה.\nШвянчёнис находится в 85 км к северо-востоку от Вильнюса; до Катастрофы местечко было важным еврейским центром.\nŠvenčionys lies about 85 km northeast of Vilnius; until the Holocaust it was an important Jewish center.',
    type: 'יוסף ואתה־שרה קליוט וילדיהם · Иосиф и Эта-Сара Клиот с детьми · Yosef and Eta-Sara Kliot with their children',
  },
  {
    id: 5,
    nbhd: 'belarus',
    name: 'ויטבסק · Витебск · Vitebsk',
    cat: 'kliot',
    emoji: '🥛',
    icon: 'train',
    address: 'בלארוס · Беларусь · Belarus',
    years: '~1919–1941',
    lat: 55.1927, lng: 30.2064,
    search: 'Vitebsk Витебск ויטבסק Kliot Sonya last train evacuation cow',
    note: 'סביב 1919, אחרי מלחמת העולם הראשונה, עברה משפחת קליוט לוויטבסק ונשארה בה עד פרוץ המלחמה הבאה. הייתה להם פרה, וסבתא אפתה לחמניות חלביות ומכרה אותן במכולת. בשבוע הראשון של המלחמה, כשהגרמנים התקרבו, סוניה — שכבר הייתה רופאה — הצליחה להעמיס את כל המשפחה על הרכבת האחרונה שיצאה לעורף. את הכלים קברו מתחת לאסם; סבא לקח את ספרי הקודש ומגילת אסתר על קלף, שנמצאת היום אצל בוריס, נכדה של סוניה. כשרעיה ופאניה חזרו ב־1944 לעיר המשוחררת — דבר לא נשאר.\n\nОколо 1919 года, после Первой мировой, семья Клиот перебралась в Витебск и оставалась там до начала новой войны. Держали корову, бабушка пекла молочные булочки и продавала их в лавке. В первую неделю войны, когда немцы подходили к городу, Соня — уже врач — сумела посадить всю семью на последний эшелон, уходивший в тыл. Посуду закопали под сараем; дед взял с собой священные книги и свиток Эстер на пергаменте — он и сегодня хранится у Бориса, внука Сони. Когда Рая и Фаня вернулись в освобождённый город в 1944-м — не осталось ничего.\n\nAround 1919, after the First World War, the Kliot family moved to Vitebsk and stayed until the next war began. They kept a cow, and grandmother baked milk rolls and sold them in the shop. In the first week of the war, as the Germans approached the city, Sonya, already a doctor, managed to get the whole family onto the last train leaving for the rear. The dishes were buried under the barn; grandfather took the holy books and a parchment Scroll of Esther, kept to this day by Boris, Sonya\'s grandson. When Raya and Fanya returned to the liberated city in 1944, nothing remained.',
    book: 'בית קליוט בין המלחמות; ההצלה ברכבת האחרונה · Дом Клиотов между войнами; спасение последним эшелоном · The Kliot home between the wars; the rescue on the last train',
    noDirections: true,
    visit: 'ויטבסק, עירם של שאגאל ומלך היידיש הספרותי, שוחררה ביוני 1944. פאניה עבדה בבנק בעיר, רעיה כמנהלת חשבונות.\nВитебск, город Шагала, был освобождён в июне 1944 года. Фаня работала здесь в банке, Рая — бухгалтером.\nVitebsk, Chagall\'s city, was liberated in June 1944. Fanya worked here in a bank, Raisa as a bookkeeper.',
    type: 'משפחת קליוט; סוניה המצילה; רעיה ופאניה שנשארו · Семья Клиот; Соня-спасительница; Рая и Фаня, оставшиеся после войны · The Kliot family; Sonya the rescuer; Raya and Fanya, who stayed after the war',
  },

  // ── RUSSIA ────────────────────────────────────────────────────────────────

  {
    id: 6,
    nbhd: 'russia',
    name: 'טוּלה · Тула · Tula',
    cat: 'kliot',
    emoji: '📚',
    icon: 'school',
    address: 'רוסיה · Россия · Russia',
    years: 'שנות ה־20 (נא״פ) · 1920-е (НЭП) · the 1920s (NEP)',
    lat: 54.1930, lng: 37.6173,
    search: 'Tula Тула טולה bookbinding Tolstoy NEP apprentice Benjamin',
    note: 'בתקופת הנא״פ (1922–1928) נשלח בנימין הצעיר לדוד שלו בטולה, בעל חנות לכריכת ספרים. בתור שוליה הלך לשוק, קילף תפוחי אדמה וניקה דגים — אבל גם למד את המלאכה, ובערבים למד בבית ספר לפועלים צעירים. פעם הזמינה בתו של לב טולסטוי את הדוד ואת אבא לכרוך את ספריית אביה הנודע; היא ידעה שהם יהודים והגישה להם רק דבש, תה ולחם לבן — דברים שמותר להם בוודאות לאכול. הם עבדו אצלה יום אחד בלבד: הדוד לא הגיע איתה להסכמה על המחיר.\n\nВ годы НЭПа (1922–1928) юного Вениамина отправили в Тулу к дяде, державшему переплётную мастерскую. Как подмастерье он ходил на рынок, чистил картошку и рыбу — но и учился ремеслу, а вечерами занимался в школе рабочей молодёжи. Однажды дочь Льва Толстого пригласила дядю и отца переплести библиотеку её знаменитого отца; зная, что они евреи, она подала им только мёд, чай и белый хлеб — то, что им точно можно есть. Проработали они у неё всего один день: дядя не сошёлся с ней в цене.\n\n\nIn the NEP years (1922–1928) young Benjamin was sent to Tula, to an uncle who kept a bookbinding shop. As an apprentice he went to the market, peeled potatoes and cleaned fish, but he also learned the craft, and in the evenings studied at the school for young workers. One day Leo Tolstoy\'s daughter invited the uncle and father to bind the library of her famous father; knowing they were Jews, she served them only honey, tea and white bread: the things she knew for certain they were allowed to eat. They worked for her exactly one day: the uncle could not agree with her on a price.',
    book: 'נעורי אבא: שוליית כורך ספרים · Юность отца: подмастерье переплётчика · Father\'s youth: a bookbinder\'s apprentice',
    noDirections: true,
    visit: 'טולה — עיר הולדתו של טולסטוי; אחוזתו יאסנאיה פוליאנה נמצאת ממש מדרום לעיר.\nТула — родной город Толстого; его усадьба Ясная Поляна — сразу к югу от города.\nTula is Tolstoy\'s home town; his estate, Yasnaya Polyana, lies just south of the city.',
    type: 'בנימין קליוט הצעיר והדוד הכורך · Юный Вениамин Клиот и дядя-переплётчик · Young Benjamin Kliot and the bookbinder uncle',
  },
  {
    id: 7,
    nbhd: 'russia',
    name: 'מוסקבה · Москва · Moscow',
    cat: 'lando',
    emoji: '🎓',
    icon: 'town',
    address: 'רוסיה · Россия · Russia',
    years: 'שנות ה־30 – 1991 · 1930-е – 1991 · 1930s – 1991',
    lat: 55.7558, lng: 37.6173,
    search: 'Moscow Москва מוסקבה Lando Boruch Huma Mark Yakov Anna Masha Dima Lenin Library festival 1957 aliyah 1991 Benjamin chemical engineering',
    note: 'העיר של שני פרקים גדולים במשפחה. אבא בנימין הגיע לכאן ללמוד הנדסת מערכות כימיות — בגלל חבר שהבטיח "יופי של מעונות", עם זוג מכנסיים אחד שחלק עם שותפו לחדר. וכאן, אחרי המלחמה, השתקעה משפחת לנדו: סבא ברוך וסבתא חומה חזרו מהפינוי ב־1945, וכאן גדלו מישה ואחיו — מארק ויעקב. ב־1957, בפסטיבל העולמי של הצעירים, ראתה משפחת פרידלנד לראשונה את סם מאז שברח ב־1910. כאן חייתי גם אני, אנה: 20 שנה ספרנית בספרייה הממלכתית ע״ש לנין, הגדולה באירופה — אחרי שמעבדה ממשלתית סירבה להעסיק אותי בגלל יהדותי. כאן נולדו וגדלו מאשה ודימה. ומכאן, ממוסקבה הקרה והמורעבת של דצמבר 1991, יצאנו — אנה, מישה, מאשה ודימה — אל החיים החדשים בישראל.\n\nГород двух больших семейных глав. Отец Вениамин приехал сюда учиться химическому машиностроению — из-за товарища, обещавшего «отличное общежитие», с одной парой выходных брюк на двоих с соседом по комнате. И здесь после войны обосновалась семья Ландо: дед Барух и бабушка Хума вернулись из эвакуации в 1945-м, здесь выросли Миша и его братья — Марк и Яков. В 1957 году, на Всемирном фестивале молодёжи, Фридланды впервые увидели Сэма с тех пор, как он бежал в 1910-м. Здесь жила и я, Анна: 20 лет библиотекарем в Ленинке, крупнейшей библиотеке Европы — после того как государственная лаборатория отказалась взять меня из-за еврейства. Здесь родились и выросли Маша и Дима. И отсюда, из холодной и голодной Москвы декабря 1991-го, мы — Анна, Миша, Маша и Дима — уехали к новой жизни в Израиле.\n\nThe city of two great family chapters. Father Benjamin came here to study chemical engineering, because of a friend who promised "a fine dormitory," with one pair of good trousers shared with his roommate. And here, after the war, the Lando family settled: grandfather Boruch and grandmother Huma returned from evacuation in 1945, and here Misha grew up with his brothers, Mark and Yakov. In 1957, at the World Festival of Youth, the Friedlands saw Sam for the first time since he fled in 1910. Here I, Anna, lived too: twenty years a librarian at the Lenin State Library, the largest in Europe, after a state laboratory refused to hire me because I was Jewish. Here Masha and Dima were born and grew up. And from here, from the cold and hungry Moscow of December 1991, we, Anna, Misha, Masha and Dima, left for our new life in Israel.',
    book: 'בית משפחת לנדו; הספרייה; והפרידה מרוסיה · Дом семьи Ландо; библиотека; прощание с Россией · The Lando family home; the library; the farewell to Russia',
    noDirections: true,
    visit: 'הספרייה הממלכתית ע״ש לנין — היום הספרייה הרוסית הממלכתית — עומדת עדיין מול הקרמלין.\nЛенинка — ныне Российская государственная библиотека — по-прежнему стоит напротив Кремля.\nThe Lenin Library, today the Russian State Library, still stands opposite the Kremlin.',
    type: 'ברוך וחומה לנדו; מישה, מארק ויעקב; אנה; מאשה ודימה · Барух и Хума Ландо; Миша, Марк и Яков; Анна; Маша и Дима · Boruch and Huma Lando; Misha, Mark and Yakov; Anna; Masha and Dima',
  },
  {
    id: 10,
    nbhd: 'russia',
    name: 'טמבוב · Тамбов · Tambov',
    cat: 'kliot',
    emoji: '🏠',
    icon: 'home',
    address: 'רוסיה · Россия · Russia',
    years: '1941 – היום · 1941 – сегодня · 1941 – today',
    lat: 52.7212, lng: 41.4523,
    search: 'Tambov Тамбов טמבוב Kliot Anna born 1948 Komsomolets factory Jewish cemetery Sonya doctors plot Michael',
    note: 'העיר של המשפחה. אבא נשלח לכאן כמהנדס למפעל "קוֹמְסוֹמוֹלֶץ" ועבד בו כל חייו; בזמן המלחמה ייצר המפעל ציוד לחזית. ב־1944, כשוויטבסק החרבה לא הותירה לאן לחזור, נדחסה כל משפחת קליוט לשני חדרים בדירה קהילתית שקיבל. לכאן חזרה אמא נינה מהחזית בסוף 1945, כאן נישאו, וכאן נולדתי אני, אנה, בינואר 1948 — מזחלת עם סוס הביאה אותי הביתה מבית היולדות. כאן עבדה דודה סוניה כרופאת ילדים, ובמרץ 1953, בימי "משפט הרופאים", עמדה בדירתנו מזוודת חירום ארוזה. סבא יוסף ואתה־שרה קבורים בבית הקברות היהודי בעיר. כאן חי אחי מיכאל קליוט ז״ל; רעייתו נינה נשארה בעיר, מטפלת בכל המצבות ועוזרת לקהילה היהודית.\n\nГород семьи. Отца направили сюда инженером на завод «Комсомолец», где он проработал всю жизнь; в войну завод выпускал оборудование для фронта. В 1944-м, когда в разрушенный Витебск возвращаться было некуда, вся семья Клиот съехалась в две комнаты его коммунальной квартиры. Сюда мама Нина вернулась с фронта в конце 1945-го, здесь родители поженились, здесь в январе 1948 года родилась я, Анна, — из роддома меня везли домой на санях. Здесь тётя Соня работала детским врачом, и в марте 1953-го, в дни «дела врачей», в нашей квартире стоял собранный тревожный чемоданчик. Дед Иосиф и Эта-Сара похоронены на еврейском кладбище города. Здесь жил мой брат Михаил Клиот, светлой памяти; его жена Нина осталась в городе, ухаживает за всеми могилами и помогает еврейской общине.\n\nThe family\'s city. Father was sent here as an engineer to the "Komsomolets" plant and worked there all his life; during the war the plant made equipment for the front. In 1944, with ruined Vitebsk offering nothing to return to, the whole Kliot family squeezed into the two rooms of his communal apartment. Here mother Nina came back from the front at the end of 1945, here my parents married, and here I, Anna, was born in January 1948. A horse-drawn sleigh brought me home from the maternity ward. Here aunt Sonya worked as a pediatrician, and in March 1953, in the days of the "Doctors\' Plot," a packed emergency suitcase stood in our apartment. Grandfather Yosef and Eta-Sara are buried in the city\'s Jewish cemetery. Here lived my brother Michael Kliot z"l; his wife Nina stayed in the city, tends all the graves and helps the Jewish community.',
    book: 'הבית: לידתי, ההורים, הקברים, אחי · Родной дом: моё рождение, родители, могилы, брат · Home: my birth, my parents, the graves, my brother',
    visit: 'טמבוב — כ־500 ק״מ דרומית־מזרחית ממוסקבה, לילה ברכבת. בבית הקברות היהודי — קברי סבא יוסף וסבתא אתה־שרה קליוט.\nТамбов — около 500 км к юго-востоку от Москвы, ночь на поезде. На еврейском кладбище — могилы деда Иосифа и бабушки Эты-Сары Клиот.\nTambov is about 500 km southeast of Moscow, a night by train. In the Jewish cemetery: the graves of grandfather Yosef and grandmother Eta-Sara Kliot.',
    type: 'נינה ובנימין קליוט; אנה ומיכאל; סוניה וליזה; הסבים · Нина и Вениамин Клиот; Анна и Михаил; Соня с Лизой; деды · Nina and Benjamin Kliot; Anna and Michael; Sonya and Liza; the grandparents',
  },
  {
    id: 11,
    nbhd: 'russia',
    name: 'פּוֹקְרוֹבוֹ־פּריגוֹרוֹדנוֹיֶה · Покрово-Пригородное · Pokrovo-Prigorodnoye',
    cat: 'war',
    emoji: '🎩',
    icon: 'memorial',
    address: 'ליד טמבוב · под Тамбовом · near Tambov',
    years: '1941–1945',
    lat: 52.6560, lng: 41.4750,
    search: 'Pokrovo-Prigorodnoye Покрово-Пригородное Zakhar trenches hats village evacuation',
    note: 'הכפר שאליו נשלחה משפחת פרידלנד ממרכז המפונים בטמבוב, בסתיו 1941. יום־יומיים אחרי שהתמקמו גויס סבא זחר — כמעט בן 50, אב לארבעה. שלחו אותו עם אנשי הכפר לחפור שוחות ליד וורונז׳, ותוך יומיים מצאו את עצמם מכותרים. כשהמתורגמן הגרמני דרש מקומוניסטים ויהודים לצעוד קדימה, סבא כבר עמד לצעוד — אבל ראש הכפר תפס אותו במדים והחזיק בכוח: "לא היו לנו מעולם לא קומוניסטים ולא יהודים". כך ניצלו חייו. הוא חזר לכפר, שב למלאכתו הישנה — תפירת כובעים — ושלח כסף למשפחה שבאוראל. סבתא מלכה נפטרה כאן בזמן שהמשפחה נסעה מזרחה.\n\nДеревня, куда семью Фридланд направили из тамбовского эвакопункта осенью 1941 года. Через день-два деда Захара — почти пятидесятилетнего, отца четверых детей — мобилизовали. Вместе с деревенскими его отправили копать окопы под Воронеж, и через два дня они оказались в окружении. Когда немецкий переводчик велел коммунистам и евреям сделать шаг вперёд, дед уже собирался шагнуть — но стоявший рядом староста схватил его за гимнастёрку и удержал: «У нас отродясь не было ни коммунистов, ни евреев». Так он уцелел. Вернувшись в деревню, он взялся за старое ремесло — шить шапки — и посылал деньги семье на Урал. Бабушка Малка умерла здесь, пока семья ехала на восток.\n\nThe village where the Friedland family was sent from the Tambov evacuation center in the autumn of 1941. A day or two after they settled, grandfather Zakhar, nearly fifty and a father of four, was mobilized. He was sent with the villagers to dig trenches near Voronezh, and within two days they were encircled. When the German interpreter ordered communists and Jews to step forward, grandfather was about to step, but the village elder grabbed his tunic and held him fast: "We have never had any communists or Jews here." So his life was saved. Back in the village he returned to his old craft, sewing hats, and sent money to the family in the Urals. Grandmother Malka died here while the family was traveling east.',
    book: 'הצלת סבא זחר; מות סבתא מלכה · Спасение деда Захара; смерть бабушки Малки · Grandfather Zakhar\'s rescue; grandmother Malka\'s death',
    noDirections: true,
    visit: 'כיום פרבר כפרי צמוד לטמבוב מדרום.\nСегодня — пригородное село вплотную к Тамбову с юга.\nToday a rural suburb adjoining Tambov from the south.',
    type: 'סבא זחר פרידלנד; זכר סבתא מלכה · Дед Захар Фридланд; память бабушки Малки · Grandfather Zakhar Friedland; the memory of grandmother Malka',
  },
  {
    id: 14,
    nbhd: 'russia',
    name: 'סטלינגרד · Сталинград · Stalingrad',
    cat: 'war',
    emoji: '🎖️',
    icon: 'fallen-soldier',
    address: 'כיום וולגוגרד · ныне Волгоград · now Volgograd',
    years: '1942–1943',
    lat: 48.7080, lng: 44.5133,
    search: 'Stalingrad Volgograd Сталинград Волгоград סטלינגרד Yefim surgeon killed Misha missing',
    note: 'שני חוטים של הסיפור נקשרים לעיר הזאת. יפים, בנה של רוזה, רופא צעיר שכתב לסטלין וביקש להגן על העיר הנושאת את שמו, נשלח לבית חולים שדה: השלג היה שחור מרסיסים ואדום מדם. בין שני ניתוחים יצא לעשן סיגריה — ונהרג במקום מפגז. ואחיו מישה נעדר בקרבות שבסביבה בסוף 1942 — עד שהגיעה הבשורה שהוא חי.\n\nДве нити семейной истории сходятся в этом городе. Ефим, сын Розы, молодой врач, написавший Сталину с просьбой защищать город его имени, попал в полевой госпиталь: снег там был чёрным от осколков и красным от крови. Выйдя покурить между двумя операциями, он погиб на месте от снаряда. А его брат Миша пропал без вести в этих боях в конце 1942-го — пока не пришла весть, что он жив.\n\nTwo threads of the family story meet in this city. Yefim, Roza\'s son, a young doctor who wrote to Stalin asking to defend the city that bore the leader\'s name, was sent to a field hospital: the snow there was black with shrapnel and red with blood. Stepping out for a cigarette between two operations, he was killed on the spot by a shell. And his brother Misha went missing in those battles at the end of 1942, until word came that he was alive.',
    book: 'המלחמה: נפילת יפים · Война: гибель Ефима · The war: Yefim\'s death',
    noDirections: true,
    visit: 'קרב סטלינגרד היה מהקרבות הגדולים בהיסטוריה: שני הצדדים יחד ספגו כשני מיליון הרוגים, פצועים, נעדרים ושבויים. וולגוגרד של היום; אנדרטת "אם המולדת" על גבעת ממאייב מנציחה את הקרב.\nСталинградская битва — одна из крупнейших в истории: обе стороны вместе потеряли около двух миллионов убитыми, ранеными, пропавшими без вести и пленными. Сегодня это Волгоград; мемориал «Родина-мать» на Мамаевом кургане хранит память о битве.\nThe battle of Stalingrad was one of the largest in history: the two sides together lost about two million killed, wounded, missing and captured. Today it is Volgograd; the Motherland Calls memorial on Mamayev Kurgan keeps the battle\'s memory.',
    type: 'יפים ז״ל; מישה שנמצא · Погибший Ефим; нашедшийся Миша · Yefim, who fell; Misha, who was found',
  },
  {
    id: 29,
    nbhd: 'ukraine',
    name: 'חציית הדנייפר · Переправа через Днепр · The Dnieper Crossing',
    cat: 'war',
    emoji: '🌊',
    icon: 'river',
    address: 'החזית על הדנייפר · фронт на Днепре · the Dnieper front',
    years: '1943',
    lat: 49.0667, lng: 33.4167,
    search: 'Dnieper Dnepr crossing Днепр переправа דנייפר נינה Nina air observation VNOS ВНОС raft',
    note: 'אמא נינה הייתה בת שמונה עשרה.\nהיא גויסה בתחילת 1943, כשהחלו הקרבות.\nאחרי תהליך מיון שובצה למודיעין אווירי. לקחו לשם צעירות בעלות שמיעה חדה במיוחד, כאלה שהבחינו בין מטוס גרמני לסובייטי לפי הקול בלבד.\nעם יחידתה חצתה את הדנייפר בלילה, על רפסודה, תחת אש.\nהיא לא ידעה לשחות. היא פחדה מאוד.\n\nМаме Нине было восемнадцать.\nЕё призвали в начале 1943-го, когда начались бои.\nПосле отбора её направили в службу ВНОС. Туда брали девушек с особенно острым слухом, тех, кто на слух отличал немецкий самолёт от советского.\nСо своей частью она ночью переправлялась через Днепр на плоту, под обстрелом.\nПлавать она не умела. Ей было очень страшно.\n\nMother Nina was eighteen.\nShe was called up in early 1943, when the battles began.\nAfter a selection process she was sent to air observation. They took young women with unusually sharp hearing, who could tell a German plane from a Soviet one by the sound alone.\nWith her unit she crossed the Dnieper at night, on a raft, under fire.\nShe could not swim. She was terrified.',
    visit: 'רוחב אפיק הדנייפר נע מ-60 מטרים בבלארוס ועד 1,500 מטרים במורד הזרם, באוקראינה.\nШирина русла Днепра от 60 метров в Беларуси до 1500 метров ниже по течению, в Украине.\nThe Dnieper channel runs from 60 metres in Belarus to 1,500 metres downstream in Ukraine.',
    book: 'המלחמה: נינה בחזית · Война: Нина на фронте · The war: Nina at the front',
    noDirections: true,
    type: 'נינה פרידלנד החיילת · Солдат Нина Фридланд · Soldier Nina Friedland',
  },
  {
    id: 15,
    nbhd: 'russia',
    name: 'פסקוב · Псков · Pskov',
    cat: 'war',
    emoji: '🕯️',
    icon: 'memorial',
    address: 'רוסיה · Россия · Russia',
    years: '~1941–1944',
    lat: 57.8136, lng: 28.3496,
    search: 'Pskov Псков פסקוב Michael Kliot tank killed front',
    note: 'ליד העיר הזאת נפל בקרב מול הפשיסטים מיכאל קליוט, אחיו הצעיר של אבא. עם פרוץ המלחמה גויס ונשלח לבית ספר לשריון; היו לו עיטורים רבים. אחי, מיכאל קליוט, נושא את שמו.\n\nПод этим городом в бою с фашистами погиб Михаил Клиот, младший брат отца. С началом войны его призвали и направили в танковое училище; у него было много наград. Мой брат Михаил Клиот носит его имя.\n\nNear this city Michael Kliot, father\'s younger brother, fell in battle against the fascists. When the war broke out he was called up and sent to a tank school; he earned many decorations. My brother Michael Kliot bore his name.',
    book: 'נפילת מיכאל קליוט · Гибель Михаила Клиота · The death of Michael Kliot',
    noDirections: true,
    visit: 'פסקוב העתיקה שוכנת סמוך לגבול אסטוניה; סביבותיה היו חזית קשה בשנים 1941–1944.\nДревний Псков стоит у эстонской границы; его окрестности были тяжёлым фронтом в 1941–1944 годах.\nAncient Pskov stands near the Estonian border; its surroundings were a brutal front in 1941–1944.',
    type: 'מיכאל קליוט ז״ל, אחיו של אבא · Погибший Михаил Клиот, брат отца · Michael Kliot z"l, father\'s brother',
  },
  {
    id: 17,
    nbhd: 'russia',
    name: 'יארוסלבל · Ярославль · Yaroslavl',
    cat: 'friedland',
    emoji: '🎻',
    icon: 'music',
    address: 'רוסיה · Россия · Russia',
    years: 'שנות ה־60 – היום · 1960-е – сегодня · the 1960s – today',
    lat: 57.6261, lng: 39.8845,
    search: 'Yaroslavl Ярославль יארוסלבל Alisa Kagan Алиса Каган אליסה קגן violin symphony orchestra Rozenblat',
    note: 'עירה של בת דודתי אליסה — בתה של דודה בלה, שנולדה בפינוי בניז׳ני טאגיל ולמדה מוזיקה בטמבוב. ב־1962 נישאה למארק רוזנבלט, ונולדו להם בוריס ויבגני. כמעט 50 שנה ניגנה אליסה ככנרית בתזמורת הסימפונית של יארוסלבל, והיא עדיין גרה בעיר והולכת לכל ההופעות בפילהרמוניה המקומית. נכדה הבכור מיכאל סיים את תוכנית נעל״ה בישראל וכבר שנתיים לוחם בצה״ל.\n\nГород моей двоюродной сестры Алисы — дочери тёти Беллы, родившейся в эвакуации в Нижнем Тагиле и учившейся музыке в Тамбове. В 1962 году она вышла замуж за Марка Розенблата, у них родились Борис и Евгений. Почти 50 лет Алиса играла скрипачкой в Ярославском симфоническом оркестре; она и сейчас живёт в этом городе и ходит на все концерты местной филармонии. Её старший внук Михаил окончил в Израиле программу НААЛЕ и уже два года служит боец в ЦАХАЛе.\n\nThe city of my cousin Alisa, daughter of aunt Bella, born in evacuation in Nizhny Tagil, who studied music in Tambov. In 1962 she married Mark Rozenblat; their sons are Boris and Yevgeny. For almost fifty years Alisa played violin in the Yaroslavl Symphony Orchestra; she still lives in the city and goes to every concert of the local philharmonic. Her eldest grandson Michael finished the Naale program in Israel and has been serving as a combat soldier in the IDF for two years.',
    book: 'אליסה הכנרית · Алиса-скрипачка · Alisa the violinist',
    noDirections: true,
    visit: 'יארוסלבל שעל הוולגה — מערי "טבעת הזהב"; מרכזה ההיסטורי הוא אתר מורשת עולמית.\nЯрославль на Волге — город Золотого кольца; его исторический центр — объект Всемирного наследия.\nYaroslavl on the Volga is a Golden Ring city; its historic center is a World Heritage site.',
    type: 'אליסה קגן ומשפחתה · Алиса Каган и её семья · Alisa Kagan and her family',
  },
  {
    id: 18,
    nbhd: 'russia',
    name: 'לנינגרד · Ленинград · Leningrad',
    cat: 'kliot',
    emoji: '🌉',
    icon: 'river',
    address: 'כיום סנקט פטרבורג · ныне Санкт-Петербург · now Saint Petersburg',
    years: '',
    lat: 59.9343, lng: 30.3351,
    search: 'Leningrad Ленинград לנינגרד Liza ship radio operator hospital',
    note: 'לכאן עזבה ליזה, בתה של דודה סוניה, אחרי רומן ספינה: אבא קיבל שני ואוצ׳רים לשיט בים השחור, ובמקום אמא — שסבא חלה — נסעה איתו ליזה. בזמן שאבא הלך לכל ההרצאות, ליזה הלכה לדיסקוטקים והכירה אלחוטן שעבד באונייה. היא נישאה לו ועברה ללנינגרד — והוא היה רוסי, דבר שהעציב מאוד את סוניה; אבא "חטף בגדול" ונזכר בזה שנים. בלנינגרד מצאה ליזה עבודה ונולדו ילדיה. לבית החולים הצבאי של העיר, הטוב במדינה, הועבר גם בנה של גלינה מהספרייה — כשפאבל, בנה של רוזה, עזר להציל את חייו.\n\nСюда уехала Лиза, дочь тёти Сони, после корабельного романа: отцу дали две путёвки в круиз по Чёрному морю, и вместо мамы — заболел дед — с ним поехала Лиза. Пока отец ходил на все лекции, Лиза ходила на дискотеки и познакомилась с радистом, работавшим на теплоходе. Она вышла за него и уехала в Ленинград — а он был русским, что очень огорчило Соню; отцу «влетело по полной», и сердилась она на него годами. В Ленинграде Лиза нашла работу, родились дети. В ленинградский военный госпиталь, лучший в стране, перевели и сына Галины из библиотеки — когда Павел, сын Розы, помог спасти ему жизнь.\n\n\nLiza, aunt Sonya\'s daughter, left for this city after a shipboard romance: father was given two vouchers for a Black Sea cruise, and since mother could not go, because grandfather had fallen ill, Liza went with him. While father attended all the lectures, Liza went to the discos and met a radio operator who worked on the ship. She married him and moved to Leningrad, and he was Russian, which greatly saddened Sonya; father "got it" properly, and she was cross with him for years. In Leningrad Liza found work and her children were born. To the city\'s military hospital, the best in the country, Galina\'s son was also transferred, when Pavel, Roza\'s son, helped save his life.',
    book: 'ליזה עוזבת הביתה חדש · Лиза и её новый дом · Liza and her new home',
    noDirections: true,
    visit: 'סנקט פטרבורג של היום. בשנות ה־60 היו בעיר דירות קהילתיות של עשר משפחות.\nСегодня это Санкт-Петербург. В 60-е здесь были коммуналки, где жили по десять семей.\nToday it is Saint Petersburg. In the sixties there were communal flats here housing ten families.',
    type: 'ליזה קליוט ומשפחתה · Лиза Клиот и её семья · Liza Kliot and her family',
  },

  // ── THE EAST: URALS & CENTRAL ASIA — evacuation ──────────────────────────

  {
    id: 12,
    nbhd: 'east',
    name: 'ניז׳ני טאגיל · Нижний Тагил · Nizhny Tagil',
    cat: 'war',
    emoji: '🚂',
    icon: 'train',
    address: 'אוראל, רוסיה · Урал, Россия · the Urals, Russia',
    years: '1941–1943',
    lat: 57.9101, lng: 59.9813,
    search: 'Nizhny Tagil Нижний Тагил ניזני טאגיל evacuation Ural Nina accountant Alisa born potatoes',
    note: 'חודש שלם נסעה משפחת פרידלנד מטמבוב על פלטפורמות פתוחות־למחצה, עם ציוד מפעלים שפונה לאוראל; אמא ואחותה הוציאו זו לזו כינים מהשיער, כי לא היה איפה להתרחץ. במרכז המפונים קיבלה אותן אישה מקומית עם דלי מלא תפוחי אדמה מבושלים בשמן חמניות — "המנה הטעימה ביותר שאכלתי בכל חיי", אמרה אמא עד סוף ימיה. כאן, בעיר המטלורגית שהרכיבה טנקים, ניקתה נינה בת ה־17 חדר אוכל ענק בשלוש משמרות — עד שהתגלה שהיא יודעת מתמטיקה טוב יותר מכל הצוות, והפכה למנהלת חשבונות. העבודה הזאת האכילה את המשפחה. כאן נולדה אליסה, בתה של בלה.\n\nЦелый месяц семья Фридланд ехала из Тамбова на полуоткрытых платформах вместе с заводским оборудованием, эвакуированным на Урал; мама с сестрой вычёсывали друг у друга вшей — мыться было негде. В эвакопункте местная женщина встретила их ведром варёной картошки с подсолнечным маслом — «самое вкусное блюдо за всю мою жизнь», говорила мама до конца своих дней. Здесь, в металлургическом городе, где собирали танки, семнадцатилетняя Нина мыла огромную заводскую столовую в три смены — пока не выяснилось, что математику она знает лучше всех сотрудников, и её сделали бухгалтером. Эта работа кормила семью. Здесь родилась Алиса, дочь Беллы.\n\nFor a whole month the Friedland family rode from Tambov on half-open platforms with factory equipment evacuated to the Urals; mother and her sister picked lice from each other\'s hair: there was nowhere to wash. At the evacuation center a local woman met them with a bucket of boiled potatoes in sunflower oil, "the most delicious dish I ever ate in my life," mother said to the end of her days. Here, in the metallurgical city that assembled tanks, seventeen-year-old Nina cleaned a huge factory canteen in three shifts, until it emerged that she knew mathematics better than the entire staff, and she was made a bookkeeper. That job fed the family. Here Alisa, Bella\'s daughter, was born.',
    book: 'הפינוי לאוראל; דלי תפוחי האדמה · Эвакуация на Урал; ведро картошки · The evacuation to the Urals; the bucket of potatoes',
    noDirections: true,
    visit: 'ניז׳ני טאגיל נשארה מרכז מטלורגי; כאן יוצרו טנקי T-34 במלחמה.\nНижний Тагил остался металлургическим центром; в войну здесь делали танки Т-34.\nNizhny Tagil remained a metallurgical center; T-34 tanks were built here during the war.',
    type: 'נינה, בלה, פולינה וגרישה; אליסה שנולדה כאן · Нина, Белла, Полина и Гриша; родившаяся здесь Алиса · Nina, Bella, Polina and Grisha; Alisa, born here',
  },
  {
    id: 13,
    nbhd: 'east',
    name: 'קְזִיל־אוֹרדה · Кызылорда · Kyzylorda',
    cat: 'war',
    emoji: '🍼',
    icon: 'birth',
    address: 'קזחסטן · Казахстан · Kazakhstan',
    years: '1941–1945',
    lat: 44.8488, lng: 65.4823,
    search: 'Kyzylorda Кызылорда Kazakhstan Lando Yakov born 1941 Huma Schechter evacuation',
    note: 'לכאן, לעורף העמוק בקזחסטן, הצליחה חוּמה (חנה) שכטר לברוח ממוסקבה בספטמבר 1941 עם שני ילדיה — מארק בן ה־11 ומישה בן ה־3, בעלי לעתיד — בזמן שבעלה ברוך לנדו שירת בצבא האדום. כאן נולד בנובמבר 1941 הבן השלישי, יעקב. הוא נולד חלש וחולני, וחומה עשתה הכול כדי להשיג לו תרופות ואוכל: היא מכרה את כל התכשיטים שלה. ב־1944 שלחו הבנים לאבא בחזית את התצלום הראשון שלהם. המשפחה חזרה למוסקבה רק ב־1945; ברוך שוחרר מהצבא ב־1946.\n\nСюда, в глубокий тыл в Казахстане, Хума (Хана) Шехтер сумела бежать из Москвы в сентябре 1941 года с двумя детьми — одиннадцатилетним Марком и трёхлетним Мишей, моим будущим мужем, — пока её муж Барух Ландо служил в Красной армии. Здесь в ноябре 1941 года родился третий сын, Яков. Он родился слабым и болезненным, и Хума делала всё, чтобы достать ему лекарства и еду: продала все свои украшения. В 1944-м сыновья послали отцу на фронт свою первую фотографию. В Москву семья вернулась только в 1945 году; Барух демобилизовался в 1946-м.\n\nHere, to the deep rear in Kazakhstan, Huma (Hana) Schechter managed to flee from Moscow in September 1941 with her two children, eleven-year-old Mark and three-year-old Misha, my future husband, while her husband Boruch Lando served in the Red Army. Here, in November 1941, the third son was born: Yakov. He was born weak and sickly, and Huma did everything to find him medicine and food: she sold all her jewelry. In 1944 the boys sent their father at the front their first photograph. The family returned to Moscow only in 1945; Boruch was demobilized in 1946.',
    book: 'הפינוי של משפחת לנדו; הולדת יעקב · Эвакуация семьи Ландо; рождение Якова · The Lando family\'s evacuation; Yakov\'s birth',
    noDirections: true,
    visit: 'קזיל־אורדה שוכנת על נהר הסיר־דריה; במלחמה קלטה עשרות אלפי מפונים.\nКызылорда стоит на Сырдарье; в войну она приняла десятки тысяч эвакуированных.\nKyzylorda stands on the Syr Darya; during the war it took in tens of thousands of evacuees.',
    type: 'חומה שכטר; מארק, מישה ויעקב לנדו · Хума Шехтер; Марк, Миша и Яков Ландо · Huma Schechter; Mark, Misha and Yakov Lando',
  },
  {
    id: 19,
    nbhd: 'east',
    name: 'צ׳יטה · Чита · Chita',
    cat: 'lando',
    emoji: '🏥',
    icon: 'hospital',
    address: 'מזרח סיביר · Восточная Сибирь · Eastern Siberia',
    years: 'שנות ה־50 ואילך · с 1950-х · from the 1950s',
    lat: 52.0515, lng: 113.4712,
    search: 'Chita Чита ציטה Pavel doctor laboratory hospital Siberia',
    note: 'יותר מ־7,000 ק״מ מאודסה — לכאן קיבל עבודה פאבל, בנם של רוזה ושאול, רופא ביישן ונמוך קומה שסיים לימודי רפואה. הוא ניהל מעבדה בבית חולים גדול. רוזה שלחה אליו, שלב אחרי שלב, את כל ערמות הספרים שנשארו מבעלה — שאף ספר לא ילך לאיבוד. שנים אחר כך, כשבנה של גלינה, חברתי מהספרייה, גווע בבית חולים צבאי בצ׳יטה, מצאנו את פאבל דרך ורה אחותו: הוא עזר להעביר את הצעיר לבית החולים הצבאי בלנינגרד — וכך ניצלו חייו.\n\nБольше семи тысяч километров от Одессы — сюда получил распределение Павел, сын Розы и Шауля, застенчивый невысокий врач. Он заведовал лабораторией в большой больнице. Роза посылала ему, партия за партией, все стопки книг, оставшихся от мужа, — чтобы ни одна не пропала. Годы спустя, когда сын Галины, моей подруги по библиотеке, погибал в читинском военном госпитале, мы нашли Павла через его сестру Веру: он помог перевести юношу в военный госпиталь в Ленинграде — и так его жизнь была спасена.\n\nMore than seven thousand kilometers from Odessa: this is where Pavel, son of Roza and Shaul, a shy, short-statured doctor, received his posting. He headed a laboratory in a large hospital. Roza sent him, batch after batch, all the piles of books left from her husband, so that not a single one would be lost. Years later, when the son of Galina, my friend from the library, was dying in a Chita military hospital, we found Pavel through his sister Vera: he helped transfer the young man to the military hospital in Leningrad, and so his life was saved.',
    book: 'פאבל בקצה המזרח; הצלת בנה של גלינה · Павел на краю востока; спасение сына Галины · Pavel at the edge of the east; saving Galina\'s son',
    noDirections: true,
    visit: 'צ׳יטה — בירת טרנס־בייקל; באותם ימים טסו לשם, כי הנסיעה ברכב ארכה 120 שעות.\nЧита — столица Забайкалья; тогда туда летали самолётом: на машине дорога занимала 120 часов.\nChita is the capital of Transbaikal; in those days one flew there: the road took 120 hours by car.',
    type: 'ד״ר פאבל, בנה של רוזה · Доктор Павел, сын Розы · Dr. Pavel, Roza\'s son',
  },

  // ── UKRAINE ───────────────────────────────────────────────────────────────

  {
    id: 8,
    nbhd: 'ukraine',
    name: 'אודסה · Одесса · Odessa',
    cat: 'lando',
    emoji: '⚓',
    icon: 'ship',
    address: 'אוקראינה · Украина · Ukraine',
    years: 'תחילת המאה ה־20 ואילך · с начала XX века · from the early 1900s',
    lat: 46.4694, lng: 30.7409,
    search: 'Odessa Одесса אודסה Lando Schechter Roza Shaul Mark Misha born 1938 Romanian occupation',
    note: 'עיר המשפחה של בעלי. כאן ובסביבה חיו משפחות לנדו ושכטר: דויד וליה שכטר והבת חומה (חנה, ילידת 1908); ברוך (בוריס) לנדו, שבזמן המלחמה החליף את שמו — ומאז, על הנייר, בניו מישה ויעקב הם "לא אחים"; כאן נולדו מארק (1930) ומישה בעלי (1938). וכאן חיה רוזה, אחות ברוך, אחרי שנישאה לשאול — סיפורה שלה נמצא בכרטיס נפרד. העיר עמדה במצור מ־5 באוגוסט עד 16 באוקטובר 1941 ונכבשה בידי הרומנים; רוזה נמלטה באחת הספינות האחרונות. כשחזרה באפריל 1944 מצאה את דירתה תפוסה — וקיבלה דירה שדייריה היהודים נרצחו. שם ביקרנו אותה, בת 73, ועיניה זהרו כשסיפרה על שאול.\n\nГород семьи моего мужа. Здесь и рядом жили семьи Ландо и Шехтер: Давид и Лия Шехтер с дочерью Хумой (Ханой, 1908 г.р.); Барух (Борис) Ландо, сменивший имя в войну — из-за чего по документам его сыновья Миша и Яков «не братья»; здесь родились Марк (1930) и мой муж Миша (1938). И здесь жила Роза, сестра Баруха, после того как вышла замуж за Шауля — её собственная история вынесена на отдельную карточку. Город держал оборону с 5 августа по 16 октября 1941 года и был занят румынами; Роза ушла на одном из последних судов. Вернувшись в апреле 1944-го, она нашла квартиру занятой — и получила другую, жильцы которой, евреи, были убиты. Там мы навещали её, 73-летнюю, и глаза её сияли, когда она говорила о Шауле.\n\nMy husband\'s family city. Here and nearby lived the Lando and Schechter families: David and Lia Schechter with their daughter Huma (Hana, born 1908); Boruch (Boris) Lando, who changed his name during the war, which is why, on paper, his sons Misha and Yakov are "not brothers"; here Mark (1930) and my husband Misha (1938) were born. And here lived Roza, Boruch\'s sister, after she married Shaul; her own story has a card of its own. The city held out under siege from August 5 to October 16, 1941 and was occupied by the Romanians; Roza escaped on one of the last ships. Returning in April 1944, she found her apartment taken, and received another, whose Jewish tenants had been murdered. There we visited her at seventy-three, and her eyes shone whenever she spoke of Shaul.',
    book: 'משפחות לנדו ושכטר; המצור והשיבה · Семьи Ландо и Шехтер; осада и возвращение · The Lando and Schechter families; the siege and the return',
    noDirections: true,
    visit: 'רוב יהודי אודסה שנשארו בעיר נרצחו בכיבוש. רוזה נפטרה באודסה; מישה בנה היגר בשנות ה־70 לארה״ב.\nБольшинство одесских евреев, оставшихся в городе, погибли в оккупацию. Роза умерла в Одессе; её сын Миша в 70-е эмигрировал в США.\nMost of Odessa\'s Jews who stayed in the city were murdered under the occupation. Roza died in Odessa; her son Misha emigrated to the USA in the 1970s.',
    type: 'לנדו, שכטר, רוזה ושאול וילדיהם · Ландо, Шехтеры, Роза и Шауль с детьми · The Lando and Schechter families; Roza and Shaul with their children',
  },
  {
    id: 9,
    nbhd: 'ukraine',
    name: 'חרקוב · Харьков · Kharkiv',
    cat: 'lando',
    emoji: '🏛️',
    icon: 'town',
    address: 'אוקראינה · Украина · Ukraine',
    years: 'שנות ה־20–30 · 1920–30-е · the 1920s–30s',
    lat: 49.9935, lng: 36.2304,
    search: 'Kharkiv Kharkov Харьков חרקוב Shaul economist Rivka Holodomor',
    note: 'בשנים שבהן הייתה חרקוב בירת אוקראינה עבד כאן שאול, בעלה האהוב של רוזה, כלכלן מוכשר בשירות ממשלתי. כשקיבל הצעה לעבור לכאן לצמיתות, רוזה לא יכלה לעזוב את אודסה — והוא ויתר על המשרה וחזר אליה. בשנות הרעב 1932–1933, ההוֹלוֹדוֹמוֹר שגבה מיליוני חיים, ניצלה משפחתה של רוזה בזכות שכנים שחלקו איתם צנימים שרופים שקיבלו ממוסקבה. ליד חרקוב התגוררה גם רבקה, אחותו של אבא, שהתחתנה ונשארה באזור — האזור שהופגז מתחילת המלחמה הנוכחית באוקראינה.\n\nВ годы, когда Харьков был столицей Украины, здесь работал Шауль, любимый муж Розы, — способный экономист на государственной службе. Когда ему предложили перебраться сюда насовсем, Роза не смогла покинуть Одессу — и он оставил должность и вернулся к ней. В голодные 1932–1933 годы, в Голодомор, унёсший миллионы жизней, семью Розы спасли соседи, делившиеся горелыми сухарями из московских посылок. Под Харьковом жила и Ривка, сестра отца, вышедшая замуж и оставшаяся в этих краях — тех самых, что обстреливаются с начала нынешней войны в Украине.\n\nIn the years when Kharkiv was the capital of Ukraine, Shaul, Roza\'s beloved husband and a gifted economist in government service, worked here. When he was offered a permanent post, Roza could not leave Odessa, so he gave up the position and returned to her. In the famine years of 1932–1933, the Holodomor that took millions of lives, Roza\'s family was saved by neighbors who shared burnt rusks from Moscow parcels. Near Kharkiv also lived Rivka, father\'s sister, who married and stayed in the region: the same region shelled since the start of the current war in Ukraine.',
    book: 'שאול הכלכלן; רבקה; שנות הרעב · Шауль, экономист; Ривка; голодные годы · Shaul the economist; Rivka; the famine years',
    noDirections: true,
    visit: 'חרקוב הייתה בירת אוקראינה הסובייטית עד 1934.\nХарьков был столицей советской Украины до 1934 года.\nKharkiv was the capital of Soviet Ukraine until 1934.',
    type: 'שאול; רבקה קליוט ומשפחתה · Шауль; Ривка Клиот с семьёй · Shaul; Rivka Kliot and her family',
  },
  {
    id: 16,
    nbhd: 'ukraine',
    name: 'קייב · Киев · Kyiv',
    cat: 'friedland',
    emoji: '🤝',
    icon: 'meeting',
    address: 'אוקראינה · Украина · Ukraine',
    years: 'קיץ 1964 · лето 1964 · summer 1964',
    lat: 50.4501, lng: 30.5234,
    search: 'Kyiv Kiev Киев קייב Sam Dora Friedland reunion 1964',
    note: 'כאן, בקיץ 1964, נפגשה המשפחה בפעם השנייה עם סם — שמואל פרידלנד — ורעייתו דורה, שהגיעו מאמריקה לברית המועצות. אל קייב הגיעו הקרובים מרוסיה ומבלארוס: סבא זלמן, אחותו פוליה, אחי מיכאל קליאוט, בת דודתי אליסה, דוד אברם ורעייתו, ובלה. אני לא הצלחתי להגיע למפגש הזה. בשנות ה־80 שלח סם לקרובים שנשארו בבלארוס הזמנה רשמית להגר לארה״ב — אבל איש מילדי סבא לא חשב אז לעבור לאמריקה. לצערנו, אחרי העלייה לא הצלחנו לשמור על קשר עם משפחתו.\n\nЗдесь, летом 1964 года, семья во второй раз встретилась с Сэмом — Шмуэлем Фридландом — и его женой Дорой, приехавшими из Америки в СССР. В Киев съехались родные из России и Беларуси: дед Залман, его сестра Поля, мой брат Михаил Клиот, двоюродная сестра Алиса, дядя Абрам с женой и Белла. Мне попасть на эту встречу не удалось. В 80-е Сэм прислал оставшимся в Беларуси родным официальный вызов в США — но никто из детей деда тогда не думал переезжать. К сожалению, после нашей репатриации связь с его семьёй потерялась.\n\nHere, in the summer of 1964, the family met for the second time with Sam, Shmuel Friedland, and his wife Dora, who came from America to the USSR. Relatives gathered in Kyiv from Russia and Belarus: grandfather Zalman, his sister Polya, my brother Michael Kliot, my cousin Alisa, uncle Avram with his wife, and Bella. I did not manage to come to that meeting. In the 1980s Sam sent the relatives remaining in Belarus an official invitation to emigrate to the USA, but none of grandfather\'s children thought of moving then. Sadly, after our aliyah the connection with his family was lost.',
    book: 'המפגש עם סם, 1964 · Встреча с Сэмом, 1964 · The meeting with Sam, 1964',
    noDirections: true,
    visit: 'התצלום מהמפגש בקייב 1964 — עם סם ודורה, סבא זלמן, פוליה, אברם, בלה, אליסה ומיכאל — שמור בכרטיס הזה.\nФотография киевской встречи 1964 года — с Сэмом и Дорой, дедом Залманом, Полей, Абрамом, Беллой, Алисой и Михаилом — хранится на этой карточке.\nThe photograph of the 1964 Kyiv meeting, with Sam and Dora, grandfather Zalman, Polya, Avram, Bella, Alisa and Michael, is kept on this card.',
    type: 'סם ודורה; זלמן, פוליה, אברם, בלה, אליסה, מיכאל · Сэм и Дора; Залман, Поля, Абрам, Белла, Алиса, Михаил · Sam and Dora; Zalman, Polya, Avram, Bella, Alisa, Michael',
  },

  // ── ISRAEL ────────────────────────────────────────────────────────────────

  {
    id: 20,
    nbhd: 'israel',
    name: 'רחובות · Реховот · Rehovot',
    cat: 'israel',
    emoji: '🌴',
    icon: 'palm',
    address: 'ישראל · Израиль · Israel',
    years: 'דצמבר 1991 – היום · декабрь 1991 – сегодня · December 1991 – today',
    lat: 31.8928, lng: 34.8113,
    search: 'Rehovot Реховот רחובות aliyah 1991 Weizmann Masha Dima ulpan Nina',
    note: 'נחתנו בנתב״ג בלילה של דצמבר 1991: חמים, טפטוף קל, עצי תמר, תחושת שלווה. מאשה בתנו עלתה ראשונה, חודש וחצי לפנינו; אנחנו עזבנו את מוסקבה הקרה והמורעבת עשרה ימים אחרי שהתקשרה בבכי "אימא, אל תבואו, אין כאן עבודה". בדירת חמישה חדרים בלב רחובות גרו שלוש משפחות; מאחורי וילון בפינת האוכל נמצא מקום גם לאמא נינה, שהגיעה חצי שנה אחרינו. עבדתי בניקיון במשטרת רחובות בבקרים, התנדבתי בספריית מכון ויצמן — ומשם, בזכות ההמלצות, הגעתי לאוניברסיטת תל אביב ול־20 שנה במסלול האקדמי של המכללה למנהל. מאשה התקבלה למכון ויצמן; דימה סיים את תיכון קציר, שירת שלוש שנים בצה״ל ולמד במכללה. ברעננה חי דמיטרי עם רעייתו זויה; כאן גדלים גם ילדיו, מארק וניקול. מישה הצטרף אלינו כעבור שנה, דרך ורשה. ואת עבודתה הראשונה מצאה מאשה במודעה ליד המכולת — "דרושה עוזרת גננת": כל הלילה הכינה שני סיפורים, על אהבתה לילדים ועל אהבתה לפרחים, כי לא ידעה איזו "גננת" מחפשים. זה היה גן ילדים — והעבודה נתנה לה שפה ומציאות ישראלית. אנחנו כבר 30 שנה בישראל — ואין לנו חרטות.\n\nМы приземлились в Бен-Гурионе декабрьской ночью 1991 года: тепло, лёгкая морось, финиковые пальмы, ощущение покоя. Наша дочь Маша уехала первой, на полтора месяца раньше; мы покинули холодную голодную Москву через десять дней после её звонка в слезах: «Мама, не приезжайте, здесь нет работы». В пятикомнатной квартире в центре Реховота жили три семьи; за занавеской в столовом углу нашлось место и маме Нине, приехавшей через полгода после нас. По утрам я мыла полы в реховотской полиции, волонтёрила в библиотеке института Вейцмана — а оттуда, по рекомендациям, пришла в Тель-Авивский университет и на 20 лет в библиотеку Колледжа менеджмента. Маша поступила в институт Вейцмана; Дима окончил школу «Кацир», отслужил три года в ЦАХАЛе и выучился в колледже. Миша присоединился к нам через год, через Варшаву. А свою первую работу Маша нашла по объявлению у лавки — «требуется помощница ганенет»: всю ночь она готовила две истории, о любви к детям и о любви к цветам, не зная, какую «садовницу» ищут. Оказался детский сад — и эта работа дала ей язык и израильскую реальность. Мы в Израиле уже 30 лет — и ни о чём не жалеем.\n\nWe landed at Ben Gurion on a December night in 1991: warm, a light drizzle, date palms, a feeling of peace. Our daughter Masha went first, a month and a half before us; we left cold, hungry Moscow ten days after her tearful call: "Mama, don\'t come, there is no work here." In a five-room apartment in the center of Rehovot lived three families; behind a curtain in the dining corner there was room for mother Nina too, who arrived half a year after us. In the mornings I washed floors at the Rehovot police station and volunteered at the Weizmann Institute library, and from there, on recommendations, I reached Tel Aviv University and then twenty years in the library of the College of Management. Masha entered the Weizmann Institute; Dima finished the Katzir school, served three years in the IDF and studied at the college. Misha joined us a year later, through Warsaw. And Masha found her first job from a notice by the grocery that read "kindergarten assistant wanted". All night she prepared two stories, one about her love for children and one about her love for flowers, not knowing which kind of "gannenet" they were seeking. It was a kindergarten, and the job gave her the language and the Israeli reality. We have been in Israel thirty years, and have no regrets.',
    book: 'העלייה והחיים החדשים · Репатриация и новая жизнь · The aliyah and the new life',
    visit: 'אמא נינה קליאות (פרידלנד) צולמה כאן ב־1994. היום מתגוררים בישראל גם נכדיה של בת דודתי — ביניהם מיכאל, לוחם בצה״ל.\nМама Нина Клиот (Фридланд) сфотографирована здесь в 1994 году. Сегодня в Израиле живут и внуки моей двоюродной сестры — среди них Михаил, боец ЦАХАЛа.\nMother Nina Kliot (Friedland) was photographed here in 1994. Today my cousin\'s grandchildren live in Israel too, among them Michael, an IDF soldier.',
    type: 'אנה ומישה, מאשה ודימה, אמא נינה · Анна и Миша, Маша и Дима, мама Нина · Anna and Misha, Masha and Dima, mother Nina',
    website: 'https://ludara.ai/aperfectday/',
  },
  {
    id: 21,
    nbhd: 'israel',
    name: 'ירושלים · Иерусалим · Jerusalem',
    cat: 'israel',
    emoji: '💍',
    icon: 'wedding',
    address: 'ישראל · Израиль · Israel',
    years: '2009',
    lat: 31.7683, lng: 35.2137,
    search: 'Jerusalem Иерусалим ירושלים Baruch Rachel wedding 2009 Kliot',
    note: 'הדור הבא כבר כאן: ב־2009 נישאו בירושלים ברוך ורחל קליאוט. ברוך — נכדה של דודה סוניה, רופאת הילדים מטמבוב שהצילה את משפחתה ברכבת האחרונה מוויטבסק, ובנה של ליזה. במשפחה נשמרת עד היום מגילת אסתר על קלף, שסבא יוסף קליוט נשא איתו מוויטבסק אל הפינוי ב־1941 — חוט שנמתח מהעיירה הבלארוסית עד ירושלים.\n\nСледующее поколение уже здесь: в 2009 году в Иерусалиме поженились Барух и Рахель Клиот. Барух — внук тёти Сони, тамбовского детского врача, спасшей семью последним эшелоном из Витебска, сын Лизы. В семье до сих пор хранится свиток Эстер на пергаменте, который дед Иосиф Клиот вёз с собой из Витебска в эвакуацию 1941 года, — нить, протянувшаяся из белорусского местечка до Иерусалима.\n\nThe next generation is already here: in 2009 Baruch and Rachel Kliot married in Jerusalem. Baruch is the grandson of aunt Sonya, the Tambov pediatrician who saved her family on the last train from Vitebsk, and the son of Liza. The family still keeps the parchment Scroll of Esther that grandfather Yosef Kliot carried from Vitebsk into the 1941 evacuation: a thread stretching from a Belarusian shtetl all the way to Jerusalem.',
    book: 'חתונת ברוך ורחל; מגילת אסתר של סבא · Свадьба Баруха и Рахели; дедовский свиток Эстер · Baruch and Rachel\'s wedding; grandfather\'s Scroll of Esther',
    visit: 'מגילת האסתר המשפחתית שמורה בביתו של ברוך (בוריס), נכדה של דודה סוניה.\nСемейный свиток Эстер хранится в доме Баруха (Бориса), внука тёти Сони.\nThe family Scroll of Esther is kept in the home of Baruch (Boris), aunt Sonya\'s grandson.',
    type: 'ברוך ורחל קליאוט · Барух и Рахель Клиот · Baruch and Rachel Kliot',
  },


  {
    id: 22,
    nbhd: 'israel',
    name: 'מושב סתריה · Мошав Ситрия · Moshav Sitria',
    cat: 'israel',
    emoji: '💐',
    icon: 'farm',
    address: 'ישראל · Израиль · Israel',
    years: '1992',
    lat: 31.8630, lng: 34.7870,
    search: 'Sitria moshav flowers סתריה Ситрия цветы Anna first job',
    note: 'העבודה הראשונה שלי בארץ: אני וחברה מהאולפן נשלחנו לחתוך פרחים לפי תבנית — גבעולים של 50 ו־35 ס״מ, ורדים קטנים וענפים דמויי שיח מחטני לזרים. היה פברואר, וזרים מעוצבים נשלחו לאירופה; שיא הביקוש — לפני יום האישה הבינלאומי ב־8 במרץ. הרווחנו 50 שקלים ליום, הנסיעה עלתה 5 — נטו 45 שקלים על 8 שעות. אחרי חודש וחצי, בתום הפריחה, העבודה נגמרה.\n\nМоя первая работа в Израиле: нас с подругой по ульпану отправили срезать цветы по шаблону — стебли по 50 и 35 см, маленькие розы и хвойные веточки для букетов. Был февраль, готовые букеты отправляли в Европу; пик спроса — перед 8 Марта. Мы зарабатывали 50 шекелей в день, дорога стоила 5 — чистыми 45 шекелей за 8 часов. Через полтора месяца, когда цветение закончилось, кончилась и работа.\n\nMy first job in Israel: a friend from the ulpan and I were sent to cut flowers to a template: stems of 50 and 35 centimeters, small roses and conifer-like sprigs for bouquets. It was February, and the finished bouquets were shipped to Europe; demand peaked before March 8, International Women\'s Day. We earned 50 shekels a day, the ride cost 5, so 45 shekels net for eight hours. After a month and a half, when the blooming ended, so did the job.',
    book: 'העבודה הראשונה בארץ · Первая работа в Израиле · The first job in Israel',
    visit: 'מושב סתריה — דקות ספורות מרחובות.\nМошав Ситрия — в нескольких минутах от Реховота.\nMoshav Sitria is a few minutes from Rehovot.',
    type: 'אנה וחברתה מהאולפן · Анна с подругой по ульпану · Anna and her ulpan friend',
  },
  {
    id: 23,
    nbhd: 'israel',
    name: 'מכון ויצמן · Институт Вейцмана · Weizmann Institute',
    cat: 'israel',
    emoji: '🔬',
    icon: 'science',
    address: 'רחובות · Реховот · Rehovot',
    years: 'מ־1992 · с 1992 · from 1992',
    lat: 31.9070, lng: 34.8102,
    search: 'Weizmann Institute מכון ויצמן Вейцман Masha Maria library scholarship',
    note: 'עוד במוסקבה סיפר מרצה שביקר במכון ויצמן: בספרייה שלו הסטודנטים לומדים יום ולילה, לכל אחד מפתח משלו, לוקחים ספרים — ואיש אינו גונב. בשביל רוסיה, שבה נעלו הכול, זה נשמע כעולם אחר — וכך נולדה ההשראה לקבוצת הצעירים של מאשה. בארץ מאשה (מריה) התקבלה למכון, ועד מהרה גם עם מלגה — סכום עצום עבורנו אז. אני התנדבתי בספריית המכון, למדתי בה לעבוד עם מחשב, ומההמלצות משם הגעתי לאוניברסיטת תל אביב — ואחר כך ל־20 שנה בספריית המסלול האקדמי של המכללה למנהל.\n\nЕщё в Москве один преподаватель, побывавший в институте Вейцмана, рассказывал: в его библиотеке студенты занимаются день и ночь, у каждого свой ключ, книги берут — и никто не крадёт. Для России, где запирали всё, это звучало как другой мир — так родилось вдохновение у Машиной группы молодёжи. В Израиле Маша (Мария) поступила в институт, вскоре и со стипендией — огромной для нас тогда суммой. Я волонтёрила в библиотеке института, освоила там компьютер, а по рекомендациям оттуда попала в Тель-Авивский университет — и затем на 20 лет в библиотеку Колледжа менеджмента.\n\nBack in Moscow, a lecturer who had visited the Weizmann Institute told his students: in its library people study day and night, everyone has a key of their own, books are taken, and nobody steals. For Russia, where everything was kept under lock, it sounded like another world, and that is how the inspiration came to Masha\'s group of young people. In Israel Masha (Maria) was accepted to the Institute, soon with a scholarship, an enormous sum for us then. I volunteered at the Institute\'s library, learned to work with a computer there, and through its recommendations reached Tel Aviv University, and then twenty years in the library of the College of Management.',
    book: 'ההשראה לעלייה והדרך החדשה · Вдохновение алии и новая дорога · The inspiration for aliyah and the new road',
    visit: 'קמפוס מכון ויצמן פתוח למבקרים — גן המדע ובית ויצמן.\nКампус института открыт для посетителей — Сад науки и дом Вейцмана.\nThe Weizmann Institute campus is open to visitors: the Science Garden and the Weizmann House.',
    type: 'מאשה (מריה); אנה בספרייה · Маша (Мария); Анна в библиотеке · Masha (Maria); Anna in the library',
  },
  {
    id: 24,
    nbhd: 'israel',
    name: 'אשדוד · Ашдод · Ashdod',
    cat: 'israel',
    emoji: '⛵',
    icon: 'ship',
    address: 'ישראל · Израиль · Israel',
    years: 'היום · сегодня · today',
    lat: 31.8014, lng: 34.6435,
    search: 'Ashdod אשדוד Ашдод Ilya Olga Kliot Leetal Nir Ron metal yacht',
    note: 'כאן חי היום איליה קליוט עם משפחתו — בנו של מיכאל קליוט ז״ל, אחיה של אמא. איליה למד שלוש שנים באקדמיה של אביו בטמבוב, עלה לישראל, סיים את אורט סינגלובסקי ובונה מבנים ממתכת ומחומרים אחרים. העבודה המיוחדת בזיכרון: יאכטה שנבנתה במפעל עבור בעל המפעל — רחבה יותר משביל ההובלה, כך שבדרך לים הורידו זמנית עמודים. היאכטה הגיעה לחוף בשלום. באשדוד גדלים היום שלושת ילדיהם של איליה ואולגה — ליטל, ניר ורון.\n\nЗдесь сегодня живёт Илья Клиот с семьёй — сын Михаила Клиота, маминого брата. Илья отучился три года в отцовской академии в Тамбове, репатриировался, окончил ОРТ Сингаловски и строит конструкции из металла и других материалов. Самая памятная работа — яхта, построенная на заводе для владельца завода: она оказалась шире дороги, и по пути к морю временно снимали столбы. До берега яхта добралась благополучно. В Ашдоде сегодня растут трое детей Ильи и Ольги — Литаль, Нир и Рон.\n\nHere today lives Ilya Kliot with his family: the son of Michael Kliot z"l, mother\'s brother. Ilya studied three years at his father\'s academy in Tambov, made aliyah, finished ORT Singalovski and builds structures of metal and other materials. The most memorable job: a yacht built at the factory for the factory\'s owner, wider than the haul road, so poles were temporarily taken down on the way to the sea. The yacht reached the shore safely. In Ashdod today grow the three children of Ilya and Olga: Leetal, Nir and Ron.',
    book: 'איליה באשדוד · Илья в Ашдоде · Ilya in Ashdod',
    type: 'איליה ואולגה קליוט; ליטל, ניר ורון · Илья и Ольга Клиот; Литаль, Нир и Рон · Ilya and Olga Kliot; Leetal, Nir and Ron',
  },
  {
    id: 25,
    nbhd: 'israel',
    name: 'רמת השרון · Рамат-ха-Шарон · Ramat HaSharon',
    cat: 'israel',
    emoji: '🗺️',
    icon: 'town',
    address: 'ישראל · Израиль · Israel',
    years: 'היום · сегодня · today',
    lat: 32.1461, lng: 34.8394,
    search: 'Ramat Hasharon רמת השרון Рамат-ха-Шарон Maria Masha Lando Ludara Naor Nadia Nili Bar',
    note: 'כאן גרה היום מאשה — מריה לנדו — זו שיזמה את העלייה של המשפחה, מצאה את הגן מהמודעה ליד המכולת והתקבלה למכון ויצמן. היום היא מייסדת Ludara.AI — והמפה הזאת עצמה, על סיפורי המשפחה והעץ שלה, נבנתה בכלים שהיא יצרה. כאן גדלו שלושת ילדיה — נאור, נדיה ונילי בר.\n\nЗдесь сегодня живёт Маша — Мария Ландо — та, что задумала репатриацию семьи, нашла детский сад по объявлению у лавки и поступила в институт Вейцмана. Сегодня она основательница Ludara.AI — и сама эта карта, с историями семьи и её древом, построена инструментами, которые создала она. Здесь выросли трое её детей — Наор, Надя и Нили Бар.\n\nHere today lives Masha, Maria Lando, the one who set the family\'s aliyah in motion, found the kindergarten from the notice by the grocery and entered the Weizmann Institute. Today she is the founder of Ludara.AI, and this very map, with the family\'s stories and its tree, was built with the tools she created. Here her three children grew up: Naor, Nadia and Nili Bar.',
    book: 'מאשה היום · Маша сегодня · Masha today',
    type: 'מריה (מאשה) לנדו; נאור, נדיה ונילי · Мария (Маша) Ландо; Наор, Надя и Нили · Maria (Masha) Lando; Naor, Nadia and Nili',
    website: 'https://ludara.ai',
  },
  {
    id: 26,
    nbhd: 'israel',
    name: 'רעננה · Раанана · Raanana',
    cat: 'israel',
    emoji: '🏠',
    icon: 'home',
    address: 'ישראל · Израиль · Israel',
    years: 'היום · сегодня · today',
    lat: 32.1848, lng: 34.8713,
    search: 'Raanana רעננה Раанана Dima Dmitry Zoya Natasha Gurevich Mark Nikol Nicole Lando',
    note: 'כאן חי היום דימה — דמיטרי לנדו — עם משפחתו. הוא הגיע לארץ בן 17, התקבל לתיכון קציר ברחובות, עמד בפיתוי להישאר במוסקבה אצל חברו, חזר, שירת שלוש שנים בצה״ל ולמד במכללה. ברעננה חי דמיטרי עם רעייתו זויה; כאן גדלים גם ילדיו, מארק וניקול.\n\nЗдесь сегодня живёт Дима — Дмитрий Ландо — со своей семьёй. Он приехал в страну в 17 лет, поступил в школу «Кацир» в Реховоте, устоял перед соблазном остаться в Москве у друга, вернулся, отслужил три года в ЦАХАЛе и окончил колледж. В Раанане Дмитрий живёт с женой Зоей; здесь растут и его дети — Марк и Николь.\n\nHere today lives Dima, Dmitry Lando, with his family. He came to Israel at seventeen, entered the Katzir school in Rehovot, resisted the temptation to stay in Moscow with his friend, returned, served three years in the IDF and finished college. In Raanana Dmitry lives with his wife Zoya; his children, Mark and Nikol, grow up here too.',
    book: 'דימה היום · Дима сегодня · Dima today',
    type: 'דמיטרי וזויה לנדו; מארק וניקול · Дмитрий и Зоя Ландо; Марк и Николь · Dmitry and Zoya Lando; Mark and Nikol',
  },

  {
    id: 27,
    nbhd: 'america',
    name: 'לוס אנג׳לס · Лос-Анджелес · Los Angeles',
    cat: 'lando',
    emoji: '🎬',
    icon: 'wedding',
    address: 'מערב לוס אנג׳לס, קליפורניה · Западный Лос-Анджелес, Калифорния · West Los Angeles, California',
    years: '1994–1998',
    lat: 34.0518, lng: -118.3920,
    search: 'Los Angeles לוס אנג׳לס Лос-Анджелес Lando Bar Moshe USC Hollywood effects Bedford Drive Pico-Robertson Maui wedding 1997 Godzilla Starship Troopers',
    note: 'מריה לנדו ומשה בר הגיעו ללוס אנג׳לס ב־1994 ונשארו ארבע שנים. משה עשה דוקטורט בפסיכולוגיה ובמדעי המוח באוניברסיטת דרום קליפורניה. מריה עבדה בהוליווד ויצרה אפקטים מיוחדים לסרטים Multiplicity, Air Force One, Turbulence, Starship Troopers, Desperate Measures ו-Godzilla.\n\nהשנים ההן היו הקרנות בכורה, הרבה מאוד ספורט, וחברים מכל קצוות העולם.\n\nהם נישאו ב־17 באוקטובר 1997 במאווי שבהוואי. שנה לאחר מכן ערכו טקס חופה וקידושין בחצר האחורית של הדופלקס ששכרו ברחוב סאות׳ בדפורד דרייב במערב לוס אנג׳לס, עם עשרה חברים קרובים.\n\nМария Ландо и Моше Бар приехали в Лос-Анджелес в 1994 году и прожили там четыре года. Моше защищал докторскую по психологии и нейронаукам в Университете Южной Калифорнии. Мария работала в Голливуде, создавая спецэффекты для фильмов Multiplicity, Air Force One, Turbulence, Starship Troopers, Desperate Measures и Godzilla.\n\nЭти годы были премьерами, большим количеством спорта и друзьями со всех концов света.\n\nОни поженились 17 октября 1997 года на Мауи, Гавайи. Год спустя они провели еврейскую свадебную церемонию на заднем дворе дуплекса, который снимали на Саут-Бедфорд-драйв в западном Лос-Анджелесе, с десятью близкими друзьями.\n\nMaria Lando and Moshe Bar came to Los Angeles in 1994 and stayed four years. Moshe took his doctorate in psychology and neuroscience at the University of Southern California. Maria worked in Hollywood, creating special effects for Multiplicity, Air Force One, Turbulence, Starship Troopers, Desperate Measures and Godzilla.\n\nThose years were film premieres, a great deal of sport, and friends made from every part of the world.\n\nThey married on 17 October 1997 in Maui, Hawaii. A year later they held a Jewish ceremony in the back yard of the duplex they rented on South Bedford Drive in West Los Angeles, with ten close friends.',
    book: 'ארבע שנים בקליפורניה · Четыре года в Калифорнии · Four years in California',
    noDirections: true,
    visit: 'רחוב סאות׳ בדפורד דרייב יורד מבברלי הילס אל שכונת פיקו־רוברטסון שבמערב לוס אנג׳לס.\nСаут-Бедфорд-драйв спускается из Беверли-Хиллз в район Пико-Робертсон на западе Лос-Анджелеса.\nSouth Bedford Drive runs south out of Beverly Hills into the Pico-Robertson district of West Los Angeles.',
    type: 'מריה לנדו ומשה בר · Мария Ландо и Моше Бар · Maria Lando and Moshe Bar',
  },

  {
    id: 28,
    nbhd: 'america',
    name: 'בוסטון · Бостон · Boston',
    cat: 'lando',
    emoji: '🌳',
    icon: 'home',
    address: 'מסצ׳וסטס, ארצות הברית · Массачусетс, США · Massachusetts, USA',
    years: '1998–2011',
    lat: 42.2809, lng: -71.2378,
    search: 'Boston Belmont Needham בוסטון Бостон Bar Naor Nadia Harvard MGH professor TheMathMom Boston Globe Gan Yeladim SSDS Cape Cod Woods Hole tree house',
    note: 'מריה ומשה עברו לבוסטון ב־1998 ונשארו שלוש עשרה שנים, תחילה בשכירות בבלמונט ואחר כך בבית שקנו בנידהאם. משה היה פרופסור באוניברסיטת הרווארד ובבית החולים MGH. מריה עבדה בחברת מכשור רפואי וגם ניהלה את TheMathMom, שהראתה את הצד המהנה של המתמטיקה ויצרה חידות וסיפורים ל־Boston Globe.\n\nנאור בר נולד בשנת 2000 ונדיה בר בשנת 2003. שניהם למדו ב־Gan Yeladim ואחר כך ב־SSDS. משה בנה בית על העץ שהפך למקום המועדף על הילדים לבלות בו. הסבים והסבתות הגיעו לביקור פעם בשנה. החברים שנרכשו באותן שנים נשארו חברים לכל החיים.\n\nהם אהבו את קייפ קוד. קיץ אחד שלם גרו שם, כשמשה עבד במעבדה בוודס הול.\n\nМария и Моше переехали в Бостон в 1998 году и прожили там тринадцать лет: сначала снимали жильё в Белмонте, а потом купили дом в Нидеме. Моше был профессором в Гарвардском университете и в больнице MGH. Мария работала в компании медицинского оборудования и вела TheMathMom, показывая весёлую сторону математики и создавая задачи и истории для Boston Globe.\n\nНаор Бар родился в 2000 году, Надя Бар в 2003. Оба ходили в Gan Yeladim, а затем в SSDS. Моше построил домик на дереве, который стал любимым местом, где собирались дети. Бабушки и дедушки приезжали в гости раз в год. Друзья, появившиеся в те годы, остались друзьями на всю жизнь.\n\nОни любили Кейп-Код. Одно лето они прожили там целиком, пока Моше работал в лаборатории в Вудс-Хоуле.\n\nMaria and Moshe moved to Boston in 1998 and stayed thirteen years, first renting in Belmont and then bought a house in Needham. Moshe was a professor at Harvard University and at Massachusetts General Hospital. Maria worked at a medical device company and ran TheMathMom, showing the fun side of mathematics and creating puzzles and stories for the Boston Globe.\n\nNaor Bar was born in 2000 and Nadia Bar in 2003. Both went to Gan Yeladim and then SSDS. Moshe built a tree house that became a favorite place for kids to hang out. The grandparents came to visit once a year. The friends made in those years stayed friends for life.\n\nThey loved Cape Cod. One summer they lived there while Moshe worked at the Woods Hole laboratory.',
    book: 'שלוש עשרה שנים בבוסטון · Тринадцать лет в Бостоне · Thirteen years in Boston',
    noDirections: true,
    visit: 'נידהאם ובלמונט הן פרברים מערבית לבוסטון, מסצ׳וסטס.\nНидем и Белмонт: пригороды к западу от Бостона, штат Массачусетс.\nNeedham and Belmont are suburbs west of Boston, Massachusetts.',
    type: 'מריה ומשה בר; נאור ונדיה · Мария и Моше Бар; Наор и Надя · Maria and Moshe Bar; Naor and Nadia',
  },

  {
    id: 30,
    nbhd: 'ukraine',
    name: 'רוזה: העיירה שליד אודסה · Роза: местечко под Одессой · Roza: the town near Odessa',
    cat: 'lando',
    emoji: '💍',
    icon: 'wedding',
    address: 'ליד אודסה, אוקראינה · под Одессой, Украина · near Odessa, Ukraine',
    years: 'תחילת המאה ה־20 – שנות ה־20 · начало XX века – 1920-е · early 1900s – 1920s',
    lat: 46.6200, lng: 30.4400,
    search: 'Roza Роза רוזה wedding chuppah black dress Shaul Red Army divorce shiva Hersh Hana Michael Yefim Pavel Vera',
    note: 'רוזה, אחותו הצעירה של ברוך, הייתה בת שש־עשרה. המשפחה גרה אז בעיירה קטנה ליד אודסה, ואביה הרש ניהל את משקו של חוואי עשיר שלא היה יהודי. רוזה התיידדה עם צעיר משם, אולי בנו של החוואי. אחותה הבכורה חנה ראתה אותו אוחז בידה וסיפרה להורים; בעלה של חנה אמר שצריך למצוא לה בעל מיד, ולהחזיק אותה בבית עד החתונה. רוזה בכתה וניסתה לברוח. עקבו אחריה כל הזמן.\nהחתן נמצא מהר: גבר לא צעיר ולא נאה, אבל בקיא מאוד בתורה — וזה מה שמצא חן בעיני הוריה. את פניו הרשו לה לראות רגע אחד, מבעד לחלון.\nהתופרת שלקחה מידות שאלה איזו שמלה היא רוצה. רוזה פרצה בבכי ואמרה שתתחתן בשמלה שחורה. התופרת צחקה, אמרה שיש הרבה בנות שש־עשרה שאינן רוצות להתחתן ואחר כך מתרגלות, והבטיחה לתפור לה את השמלה היפה בעיר. השמלה באמת יצאה יפהפייה. רוזה לא הפסיקה לבכות.\nמתחת לחופה הרים החתן את ההינומה, ורוזה ראתה שיש לו כתם לבן בקרנית העין. היא התעלפה. האורחים שעמדו לידה תפסו אותה והחליטו שהכלה פשוט מתרגשת, ומחר הכול יהיה בסדר.\nמהנישואים האלה נולדו שני בנים: מיכאל ויפים.\nואז באה שנת 1917. לנשים ניתנה הזכות להחליט על גורלן, ולהתגרש. יום אחד הכירו לרוזה צעיר בשם שאול (שולה), נציג הצבא האדום שהיה אחראי על האוכלוסייה היהודית. הוא אמר לה שאישה שהושאה בניגוד לרצונה רשאית לפתוח בהליך גירושין. היא פחדה — לא היה לה כסף משלה ולא מקצוע — אבל הקשר ביניהם הלך והתחזק, והיא התגרשה ונישאה לו.\nהוריה ניתקו איתה כל קשר. הם אמרו לכל מכריהם שבתם הצעירה איננה עוד, וישבו עליה שבעה.\nלרוזה ולשאול נולדו פאבל וּורה. הם חיו יחד שנים רבות וקשות מאוד, באושר.\nביקרנו אותה באודסה. שאול כבר לא היה בחיים, אבל בכל פעם שדיברה עליו עיניה של האישה הזאת, בת שבעים ושלוש, זהרו כאילו הייתה צעירה ומאוהבת. זמן לא רב אחר כך נפטרה, באודסה.\n\nРозе было шестнадцать. Семья жила тогда в местечке под Одессой, а её отец Герш управлял хозяйством у богатого хуторянина, нееврея. Роза подружилась с молодым человеком оттуда — возможно, сыном хозяина. Старшая сестра Хана увидела, как он держит её за руку, и рассказала родителям; муж Ханы сказал, что мужа девушке надо найти немедленно, а до свадьбы держать её дома. Роза плакала и пыталась убежать. За ней следили постоянно.\nЖених нашёлся быстро: немолодой и некрасивый человек, но очень сведущий в Торе — именно это понравилось её родителям. Посмотреть на него ей дали одно мгновение, через окно.\nПортниха, снимавшая мерки, спросила, какое платье она хочет. Роза расплакалась и сказала, что выйдет замуж в чёрном. Портниха засмеялась, сказала, что многие шестнадцатилетние не хотят замуж, а потом привыкают, и пообещала сшить ей самое красивое платье в городе. Платье вышло действительно прекрасное. Роза не переставала плакать.\nПод хупой жених поднял фату, и Роза увидела у него белое пятно на роговице. Она потеряла сознание. Стоявшие рядом гости подхватили её и решили, что невеста просто переволновалась и завтра всё будет хорошо.\nОт этого брака родились двое сыновей: Михаил и Ефим.\nА потом настал 1917 год. Женщины получили право решать свою судьбу и разводиться. Однажды Розу познакомили с молодым человеком по имени Шауль (Шуля), представителем Красной армии, отвечавшим за еврейское население. Он сказал ей, что женщина, выданная замуж против воли, вправе начать бракоразводный процесс. Она боялась — ни своих денег, ни профессии, — но их связь крепла, и она развелась и вышла за него замуж.\nРодители порвали с ней всякую связь. Они говорили всем знакомым, что младшей дочери у них больше нет, и сидели по ней шиву.\nУ Розы и Шауля родились Павел и Вера. Они прожили вместе много очень трудных лет, и счастливых.\nМы навещали её в Одессе. Шауля уже не было в живых, но каждый раз, когда она говорила о нём, глаза этой семидесятитрёхлетней женщины сияли, как у молодой влюблённой. Вскоре после этого она умерла, в Одессе.\n\nRoza, Boruch\'s younger sister, was sixteen. The family was then living in a small town near Odessa, and her father Hersh managed the estate of a wealthy farmer who was not Jewish. Roza became close to a young man there, perhaps the farmer\'s son. Her elder sister Hana saw him take Roza\'s hand and told their parents; Hana\'s husband said a husband must be found for the girl at once, and that she must be kept at home until the wedding. Roza cried and tried to run away. She was watched constantly.\nA groom was found quickly: a man neither young nor handsome, but very learned in Torah, which is what recommended him to her parents. They let her look at his face for a single moment, through a window.\nThe dressmaker taking her measurements asked what dress she wanted. Roza burst into tears and said she would be married in a black dress. The dressmaker laughed, said there were many girls of sixteen who did not want to marry and later got used to it, and promised to sew her the most beautiful dress in the city. The dress did come out beautiful. Roza did not stop crying.\nUnder the chuppah the groom lifted the veil, and Roza saw that he had a white spot on his cornea. She fainted. The guests standing beside her caught her and decided the bride was simply overcome, and that tomorrow all would be well.\nTwo sons came of that marriage: Michael and Yefim.\nThen came 1917. Women were given the right to decide their own fate, and to divorce. One day Roza was introduced to a young man named Shaul (Shula), a Red Army representative responsible for the Jewish population. He told her that a woman married against her will was entitled to begin divorce proceedings. She was afraid, having neither money of her own nor a profession, but the bond between them grew stronger, and she divorced and married him.\nHer parents cut off all contact. They told everyone they knew that their younger daughter was no more, and they sat shiva for her.\nRoza and Shaul had Pavel and Vera. They lived together for many very hard years, and happy ones.\nWe visited her in Odessa. Shaul was no longer alive, but every time she spoke of him the eyes of this woman of seventy three shone as though she were young and in love. Not long afterwards she died, in Odessa.',
    book: 'רוזה: השמלה השחורה, החופה והגירושין · Роза: чёрное платье, хупа и развод · Roza: the black dress, the chuppah and the divorce',
    noDirections: true,
    visit: 'שם העיירה אינו נזכר בזיכרונות; לאודסה עברה המשפחה מאוחר יותר.\nМестечко в воспоминаниях не названо; в Одессу семья перебралась позже.\nThe memoir does not name the town; the family moved to Odessa later.',
    type: 'סיפורה של רוזה, אחות ברוך · История Розы, сестры Баруха · The story of Roza, Boruch\'s sister',
  },

  {
    id: 31,
    nbhd: 'russia',
    name: 'הכיכר האדומה · Красная площадь · Red Square',
    cat: 'lando',
    emoji: '🎩',
    icon: 'memorial',
    address: 'מוסקבה, רוסיה · Москва, Россия · Moscow, Russia',
    years: 'דצמבר 1934 · декабрь 1934 · December 1934',
    lat: 55.7539, lng: 37.6208,
    search: 'Red Square Красная площадь הכיכר האדומה Kirov Киров funeral 1934 Stalin hat coat Yefim Komsomol delegation',
    note: 'ב־1 בדצמבר 1934 נרצח סרגיי קירוב, ממנהיגיה הידועים של ברית המועצות. הלווייתו במוסקבה הייתה עצומה, ומכל רפובליקה נשלחה משלחת: פועלים, פעילי מפלגה, סטודנטים ותלמידי תיכון. יפים, בנה של רוזה מנישואיה הראשונים, תלמיד מצטיין ופעיל קומסומול, נסע במשלחת האוקראינית.\nהמשפחה חייתה בצנעה רבה. היה לו מעיל פשוט, וכובע לא היה לו כלל — בקור של דצמבר במוסקבה.\nהמשלחת צעדה בכיכר האדומה אחרי ארונו של קירוב. בתצלום נראים סטלין והבכירים האחרים נושאים את הארון.\n"לא ברור לי איך סטלין שם לב ליפים הצעיר," כותבת אנה, "אבל למחרת הוא וכל אנשי המשלחת הוזמנו ללשכתו של סטלין." שם נמסר להם כי סטלין הבחין בנער שצעד בלי כובע, אבל עם עיניים בוערות, וביקש שיקנו לו כובע ומעיל.\nאת הכובע קנו בחנות הכלבו המרכזית. את המעיל העדיפו לתפור במפעל שבו עבדה אמו. בכסף שנשאר קנה יפים מתנות למשפחה, וחזר הביתה.\nשמונה שנים אחר כך הוא ביקש מסטלין דבר אחר: להישלח להגן על העיר שנשאה את שמו.\n\n1 декабря 1934 года был убит Сергей Киров, один из известных руководителей Советского Союза. Похороны в Москве были огромными, и из каждой республики прислали делегацию: рабочие, партийные активисты, студенты и школьники. Ефим, сын Розы от первого брака, отличник и активист комсомола, поехал в украинской делегации.\nСемья жила очень скромно. У него было простое пальто, а шапки не было вовсе — в московский декабрьский мороз.\nДелегация шла по Красной площади за гробом Кирова. На фотографии видно, как Сталин и другие руководители несут гроб.\n«Мне непонятно, как Сталин заметил юного Ефима, — пишет Анна, — но на следующий день его и всю делегацию пригласили в кабинет Сталина.» Там им передали, что Сталин обратил внимание на мальчика, шедшего без шапки, но с горящими глазами, и просил купить ему шапку и пальто.\nШапку купили в центральном универмаге. Пальто предпочли сшить на фабрике, где работала его мать. На оставшиеся деньги Ефим купил подарки для семьи и вернулся домой.\nВосемь лет спустя он попросил у Сталина другое: чтобы его послали защищать город, носивший его имя.\n\nOn 1 December 1934 Sergei Kirov, one of the best-known leaders of the Soviet Union, was assassinated. His funeral in Moscow was enormous, and every republic sent a delegation: workers, party activists, students and schoolchildren. Yefim, Roza\'s son from her first marriage, an outstanding pupil and a Komsomol activist, travelled with the Ukrainian delegation.\nThe family lived very modestly. He had a plain coat, and no hat at all, in the cold of a Moscow December.\nThe delegation marched across Red Square behind Kirov\'s coffin. In the photograph you can see Stalin and the other leaders carrying it.\n"It is not clear to me how Stalin noticed young Yefim," Anna writes, "but the next day he and the whole delegation were invited to Stalin\'s office." There they were told that Stalin had noticed the boy who marched without a hat but with burning eyes, and had asked that a hat and a coat be bought for him.\nThe hat was bought at the main department store. The coat they preferred to have sewn at the factory where his mother worked. With the money that was left Yefim bought presents for his family and went home.\nEight years later he asked Stalin for something else: to be sent to defend the city that bore his name.',
    book: 'הנער בלי הכובע · Мальчик без шапки · The boy without a hat',
    noDirections: true,
    visit: 'הכיכר האדומה עומדת כשהייתה. רצח קירוב, ב־1 בדצמבר 1934, סימן את תחילתן של שנות הטיהורים.\nКрасная площадь стоит как стояла. Убийство Кирова 1 декабря 1934 года стало началом эпохи чисток.\nRed Square stands as it was. Kirov\'s murder on 1 December 1934 marked the beginning of the years of the purges.',
    type: 'יפים, בנה של רוזה · Ефим, сын Розы · Yefim, Roza\'s son',
  },

];
