// ── HLO LONDON GUIDE DATA ────────────────────────────────────────────────────
// Hand Luggage Only — London
// Places curated from handluggageonly.co.uk

const PLACES = [

  // ── WESTMINSTER ──────────────────────────────────────────────────────────
  {
    id: 1,
    nbhd: "westminster",
    name: "Buckingham Palace",
    cat: "landmark",
    emoji: "👑",
    address: "Buckingham Palace, Westminster, London SW1A 1AA",
    lat: 51.5014, lng: -0.1419,
    search: "Buckingham Palace London",
    note: "Everyone's heard of Buckingham Palace, and visiting is one of the best things to do in London if you love the Royal family. In summer, you can book tickets to head inside and wander the State Rooms, see the Throne Room and explore the Gardens. We've visited twice and loved it!",
    hours: "Summer only (July–Sep): Daily 09:30–19:30",
    tip: "Book tickets in advance to enter the State Rooms and see the Royal Collection. Arrive early for the Changing of the Guard.",
    type: "Royal palace",
    blog: "https://handluggageonly.co.uk/28-very-best-things-to-do-in-london/",
    website: "https://www.rct.uk/visit/buckinghampalace"
  },
  {
    id: 2,
    nbhd: "westminster",
    name: "Westminster Abbey",
    cat: "church",
    emoji: "⛪",
    address: "20 Deans Yard, Westminster, London SW1P 3PA",
    lat: 51.4994, lng: -0.1276,
    search: "Westminster Abbey London",
    note: "One of London's most famous places to visit, and a UNESCO World Heritage Site. Home to centuries of royal history. Book a guided tour to get straight inside and skip the queues — you'll have a certified guide detailing the most important pieces of history within the Abbey.",
    hours: "Mon–Sat 09:30–15:30 (last entry); closed Sun for public",
    tip: "Book tickets well in advance to avoid queues. A guided tour is well worth it for the context and stories.",
    type: "Gothic abbey & royal church",
    blog: "https://handluggageonly.co.uk/28-very-best-things-to-do-in-london/",
    website: "https://www.westminster-abbey.org"
  },
  {
    id: 3,
    nbhd: "westminster",
    name: "Churchill War Rooms",
    cat: "landmark",
    emoji: "🏛️",
    address: "Clive Steps, King Charles Street, London SW1A 2AQ",
    lat: 51.5020, lng: -0.1289,
    search: "Churchill War Rooms London",
    note: "The underground bunker where Churchill directed Britain's war effort. Pretty incredible to see — you walk through the preserved Cabinet War Rooms exactly as they were left on VE Day in 1945. It's a totally atmospheric slice of history.",
    hours: "Daily 09:30–18:00",
    tip: "Combine with a walk along Downing Street and a visit to Westminster Abbey for a full Westminster day.",
    type: "Museum & historic bunker",
    blog: "https://handluggageonly.co.uk/28-very-best-things-to-do-in-london/",
    website: "https://www.iwm.org.uk/visits/churchill-war-rooms"
  },
  {
    id: 4,
    nbhd: "westminster",
    name: "Houses of Parliament",
    cat: "landmark",
    emoji: "🏰",
    address: "Palace of Westminster, London SW1A 0AA",
    lat: 51.4997, lng: -0.1247,
    search: "Houses of Parliament Palace of Westminster London",
    note: "The Palace of Westminster is one of London's most iconic sights. UK residents can organise a free tour with your MP — the medieval Great Hall and the debating chambers are totally awe-inspiring. Even from the outside (across Westminster Bridge), the view is stunning.",
    hours: "Tours available Sat and most weekdays when Parliament is in recess",
    tip: "If you're a UK resident, contact your MP for a free tour. Otherwise, book a weekend tour ticket in advance.",
    type: "Parliament building & landmark",
    blog: "https://handluggageonly.co.uk/15-of-the-best-areas-in-london-you-have-to-visit/",
    website: "https://www.parliament.uk/visiting"
  },
  {
    id: 5,
    nbhd: "westminster",
    name: "St James's Park",
    cat: "nature",
    emoji: "🌿",
    address: "St James's Park, London SW1A 2BJ",
    lat: 51.5025, lng: -0.1353,
    search: "St James's Park London",
    note: "One of London's most beautiful Royal Parks, right in the heart of the city. The lake, the pelicans (they've been here since 1664!), and the view of Buckingham Palace across the water are picture-perfect. A lovely place to stroll between Westminster sights.",
    hours: "Daily 05:00–midnight",
    tip: "The bridge across the lake offers one of the best free views of Buckingham Palace in London. Head here around sunset.",
    type: "Royal park",
    blog: "https://handluggageonly.co.uk/28-very-best-things-to-do-in-london/",
    website: "https://www.royalparks.org.uk/parks/st-jamess-park"
  },

  // ── SOUTHBANK ─────────────────────────────────────────────────────────────
  {
    id: 6,
    nbhd: "southbank",
    name: "London Eye",
    cat: "landmark",
    emoji: "🎡",
    address: "Riverside Building, County Hall, London SE1 7PB",
    lat: 51.5033, lng: -0.1196,
    search: "London Eye London",
    note: "The view from the London Eye is particularly great for Westminster and the St Paul's area. My advice: get a spot near the window as soon as you get in so you don't have to struggle with other people. The best time to go is at sunset for amazing orange hues across the city.",
    hours: "Daily 11:00–18:00 (varies seasonally, check website)",
    tip: "Book fast-track tickets in advance, especially for sunset. Arrive 15 minutes early to board promptly.",
    type: "Observation wheel & iconic landmark",
    blog: "https://handluggageonly.co.uk/14-places-with-the-best-views-of-london-all-you-need-to-know-about-visiting-these-places/",
    website: "https://www.londoneye.com"
  },
  {
    id: 7,
    nbhd: "southbank",
    name: "Tate Modern",
    cat: "landmark",
    emoji: "🎨",
    address: "Bankside, London SE1 9TG",
    lat: 51.5076, lng: -0.0994,
    search: "Tate Modern London",
    note: "One of the most visited modern art galleries in the world — and the permanent collection is totally free. Stroll over the Millennium Bridge from St Paul's and walk right in. The building itself, a converted power station, is as impressive as what's inside.",
    hours: "Sun–Thu 10:00–18:00; Fri–Sat 10:00–22:00",
    tip: "Free entry for the permanent collection. Temporary exhibitions are ticketed — book ahead. The Blavatnik Building's top floor has incredible free views over the Thames.",
    type: "Modern art gallery",
    blog: "https://handluggageonly.co.uk/28-very-best-things-to-do-in-london/",
    website: "https://www.tate.org.uk/visit/tate-modern"
  },
  {
    id: 8,
    nbhd: "southbank",
    name: "Shakespeare's Globe",
    cat: "landmark",
    emoji: "🎭",
    address: "21 New Globe Walk, Bankside, London SE1 9DT",
    lat: 51.5081, lng: -0.0974,
    search: "Shakespeare's Globe Theatre London",
    note: "A faithful reconstruction of the original Elizabethan playhouse where Shakespeare's works were first performed. You can take a fantastic tour of the space, or better yet book a standing 'groundling' ticket to see a performance in summer — it's one of London's most memorable experiences.",
    hours: "Tours: Daily 09:30–17:00. Performances: Apr–Oct",
    tip: "Standing 'groundling' tickets are very cheap and give you the most atmospheric experience. Pack a small umbrella in case of rain!",
    type: "Historic theatre & attraction",
    blog: "https://handluggageonly.co.uk/13-best-things-to-do-in-south-london/",
    website: "https://www.shakespearesglobe.com"
  },
  {
    id: 9,
    nbhd: "southbank",
    name: "Millennium Bridge",
    cat: "nature",
    emoji: "🌉",
    address: "Millennium Bridge, Bankside, London SE1",
    lat: 51.5098, lng: -0.0983,
    search: "Millennium Bridge London Thames",
    note: "The pedestrian bridge linking St Paul's Cathedral to the Tate Modern offers one of London's best free views. Walk across at dawn for an utterly magical, crowd-free experience with the dome of St Paul's perfectly framed. It's called the 'Blade of Light' and it earns that name.",
    hours: "Open 24 hours",
    tip: "Walk from St Paul's side across to Tate Modern and onwards to Borough Market — this is one of London's best short walks.",
    type: "Iconic pedestrian bridge",
    blog: "https://handluggageonly.co.uk/28-very-best-things-to-do-in-london/",
    website: "https://www.london.gov.uk"
  },
  {
    id: 10,
    nbhd: "southbank",
    name: "OXO Tower Wharf",
    cat: "food",
    emoji: "🍽️",
    address: "Barge House St, South Bank, London SE1 9PH",
    lat: 51.5077, lng: -0.1124,
    search: "OXO Tower Restaurant London",
    note: "The OXO Tower is most definitely food with a view. Pretty much everyone who's been here loves it. The eighth-floor restaurant and brasserie offer stunning Thames views alongside great food. Even just heading up for a drink on the terrace is worth it.",
    hours: "Restaurant: Daily 12:00–22:30",
    tip: "Book the brasserie for a more affordable option than the restaurant. The terrace views at dusk are spectacular.",
    type: "Restaurant with panoramic Thames views",
    blog: "https://handluggageonly.co.uk/14-places-with-the-best-views-of-london-all-you-need-to-know-about-visiting-these-places/",
    website: "https://www.harveynichols.com/restaurants/oxo-tower"
  },

  // ── BOROUGH ──────────────────────────────────────────────────────────────
  {
    id: 11,
    nbhd: "borough",
    name: "Borough Market",
    cat: "market",
    emoji: "🛒",
    address: "8 Southwark St, London SE1 1TL",
    lat: 51.5055, lng: -0.0908,
    search: "Borough Market London",
    note: "Borough Market might just be one of the city's most iconic foodie markets and a place you absolutely cannot miss. Just shy of London Bridge, there's a heap of fresh produce stalls, eateries and little restaurants. Yes, it gets busy and bustling — but that's all part of the experience.",
    hours: "Mon–Thu 10:00–17:00; Fri 10:00–18:00; Sat 08:00–17:00; closed Sun",
    tip: "Go on a weekday morning to avoid the worst crowds. Don't miss Monmouth Coffee, Neal's Yard Dairy and Gelateria 3Bis right next door.",
    type: "Iconic food market",
    blog: "https://handluggageonly.co.uk/28-very-best-things-to-do-in-london/",
    website: "https://boroughmarket.org.uk"
  },
  {
    id: 12,
    nbhd: "borough",
    name: "El Pastor",
    cat: "food",
    emoji: "🌮",
    address: "7A Stoney St, London SE1 9AA",
    lat: 51.5055, lng: -0.0913,
    search: "El Pastor Borough Market London",
    note: "Right next to Borough Market, El Pastor does some of the tastiest Mexican food in London. Their tacos al pastor — marinated pork cooked on a vertical spit — are genuinely incredible. It's casual, buzzy and absolutely delicious. Perfect for a Borough Market lunch.",
    hours: "Mon–Fri 12:00–22:30; Sat 11:00–22:30; Sun 12:00–21:30",
    tip: "Don't miss the house margarita. Queue for a seat at the counter for the best views of the kitchen.",
    type: "Mexican tacos & mezcal bar",
    blog: "https://handluggageonly.co.uk/28-very-best-things-to-do-in-london/",
    website: "https://tacoselpastor.co.uk"
  },
  {
    id: 13,
    nbhd: "borough",
    name: "Padella",
    cat: "food",
    emoji: "🍝",
    address: "6 Southwark St, London SE1 1TQ",
    lat: 51.5054, lng: -0.0904,
    search: "Padella Pasta Borough Market London",
    note: "Padella does the most delicious homemade pasta dishes at Borough Market — it's totally incredible and always has a queue. The pici cacio e pepe and tagliarini with San Marzano tomatoes are legendary. Be prepared to wait, but it absolutely is worth it.",
    hours: "Mon–Sat 12:00–21:30; Sun 12:00–21:00",
    tip: "There's no booking — arrive right at opening (noon) or join the queue early. The wait is rarely more than 30–45 minutes and utterly worth it.",
    type: "Homemade pasta restaurant",
    blog: "https://handluggageonly.co.uk/28-very-best-things-to-do-in-london/",
    website: "https://padella.co"
  },
  {
    id: 14,
    nbhd: "borough",
    name: "Monmouth Coffee",
    cat: "cafe",
    emoji: "☕",
    address: "2 Park St, London SE1 9AB",
    lat: 51.5055, lng: -0.0924,
    search: "Monmouth Coffee Borough Market London",
    note: "A London institution for specialty coffee lovers. The Borough Market branch is small and cosy, but the coffee is hands-down some of the best in the city. Their single-origin filter and flat whites are exceptional. A perfect pit stop before or after exploring the market.",
    hours: "Mon–Sat 07:30–18:00; closed Sun",
    tip: "Get there early on Saturdays before the queues build. Their pastries are also excellent.",
    type: "Specialty coffee",
    blog: "https://handluggageonly.co.uk/28-very-best-things-to-do-in-london/",
    website: "https://www.monmouthcoffee.co.uk"
  },
  {
    id: 15,
    nbhd: "borough",
    name: "Gelateria 3Bis",
    cat: "cafe",
    emoji: "🍦",
    address: "Stoney St, London SE1",
    lat: 51.5053, lng: -0.0907,
    search: "Gelateria 3Bis Borough Market London",
    note: "A few metres from the bustling heart of Borough Market, Gelateria 3Bis makes some of the most delicious ice cream in all of London. With small two-litre batches made throughout the day, you can expect the freshest, fluffiest treat you've ever had. Ask for the warm chocolate sauce!",
    hours: "Mon–Sat 10:00–18:00; Sun 11:00–17:00",
    tip: "Don't leave without asking for warm chocolate sauce on your gelato. The pistachio and salted caramel flavours are outstanding.",
    type: "Artisan gelato",
    blog: "https://handluggageonly.co.uk/5-unique-and-off-beat-places-you-have-to-experience-in-london/",
    website: "https://gelateria3bis.com"
  },
  {
    id: 16,
    nbhd: "borough",
    name: "Bermondsey Street",
    cat: "landmark",
    emoji: "🏘️",
    address: "Bermondsey Street, London SE1",
    lat: 51.5001, lng: -0.0809,
    search: "Bermondsey Street London",
    note: "One of my favourite places in Central London. It's got a totally gorgeous village feel whilst being a short walk from the riverfront at London Bridge. It's a great place to visit on a weekend afternoon when all the independent shops and intimate galleries are open. Totally gorgeous.",
    hours: "Open all hours; shops and galleries vary",
    tip: "Visit on a Saturday morning to catch White Cube gallery and the independent boutiques at their best. End with a coffee at WatchHouse.",
    type: "Vibrant independent street",
    blog: "https://handluggageonly.co.uk/28-very-best-things-to-do-in-london/",
    website: "https://www.bermondseystreet.net"
  },
  {
    id: 17,
    nbhd: "borough",
    name: "WatchHouse Bermondsey",
    cat: "cafe",
    emoji: "⌚",
    address: "199 Bermondsey St, London SE1 3UW",
    lat: 51.5003, lng: -0.0793,
    search: "WatchHouse Bermondsey coffee London",
    note: "The WatchHouse is the tiniest of London's coffee houses but serves some of the most fragrant coffee in all of South London. Originally built as a guard post for watching over nearby land, the historic Victorian watchhouse is a cosy little spot to chill after a morning exploring Bermondsey.",
    hours: "Mon–Fri 07:00–17:00; Sat–Sun 08:30–17:00",
    tip: "Grab a window seat if you can. Their pour-overs are exceptional. The walls are adorned with works from local artists.",
    type: "Specialty coffee in a Victorian watchhouse",
    blog: "https://handluggageonly.co.uk/5-unique-and-off-beat-places-you-have-to-experience-in-london/",
    website: "https://watchhouse.com"
  },
  {
    id: 18,
    nbhd: "borough",
    name: "José Bermondsey",
    cat: "food",
    emoji: "🥘",
    address: "104 Bermondsey St, London SE1 3UB",
    lat: 51.5007, lng: -0.0821,
    search: "José Tapas Bermondsey London",
    note: "Some of the best tapas in South London, right on Bermondsey Street. It's totally informal — you stand at the bar — but the food is absolutely incredible. Chef José Pizarro has created something really special here. Can get really busy, so plan ahead.",
    hours: "Tue–Sat 12:00–22:30; Sun 12:00–16:00; closed Mon",
    tip: "No bookings — arrive at opening time or expect to wait. Try the croquetas, jamón and grilled prawns. The Sherry list is exceptional.",
    type: "Spanish tapas bar",
    blog: "https://handluggageonly.co.uk/28-very-best-things-to-do-in-london/",
    website: "https://josepizarro.com/jose-tapas-bar"
  },
  {
    id: 19,
    nbhd: "borough",
    name: "White Cube Gallery",
    cat: "landmark",
    emoji: "🖼️",
    address: "144–152 Bermondsey St, London SE1 3TQ",
    lat: 51.5011, lng: -0.0823,
    search: "White Cube Gallery Bermondsey London",
    note: "One of London's most important contemporary art galleries, and admission is free. The exhibitions change regularly and are always thought-provoking — this is a forever-changing space that I love. Perfectly situated on Bermondsey Street for a cultural afternoon.",
    hours: "Tue–Sat 10:00–18:00; Sun 12:00–18:00; closed Mon",
    tip: "Free entry always. Check their website for current exhibitions before visiting — some opening events are spectacular.",
    type: "Contemporary art gallery",
    blog: "https://handluggageonly.co.uk/13-best-things-to-do-in-south-london/",
    website: "https://www.whitecube.com"
  },
  {
    id: 20,
    nbhd: "borough",
    name: "London Glassblowing",
    cat: "landmark",
    emoji: "🫙",
    address: "62–66 Bermondsey St, London SE1 3UD",
    lat: 51.5009, lng: -0.0831,
    search: "London Glassblowing Studio Bermondsey",
    note: "Established in 1976, the London Glassblowing Studios has become one of my favourite places to wander around. This studio and artistic space on Bermondsey Street houses some of the best works of art made within the studio itself. Take a glassblowing masterclass and make your own creation.",
    hours: "Mon–Sat 10:00–18:00",
    tip: "Book a glassblowing masterclass well in advance — they're incredibly popular and a truly unique London experience. Great for a gift or souvenir.",
    type: "Glassblowing studio & gallery",
    blog: "https://handluggageonly.co.uk/5-unique-and-off-beat-places-you-have-to-experience-in-london/",
    website: "https://www.londonglassblowing.co.uk"
  },
  {
    id: 21,
    nbhd: "borough",
    name: "M. Manze Pie & Mash",
    cat: "food",
    emoji: "🥧",
    address: "87 Tower Bridge Rd, London SE1 4TW",
    lat: 51.4997, lng: -0.0756,
    search: "M Manze pie mash London",
    note: "Still family-owned and over 100 years old, M. Manze is London's oldest pie and mash restaurant. Don't expect a posh affair — this is a total throwback to old London. They even serve jellied eels. Whether you love it or loathe it, it's a part of London you just have to try.",
    hours: "Mon 11:00–14:00; Tue–Thu 10:30–14:30; Fri 10:00–15:00; Sat 10:00–14:45",
    tip: "Get the pie, mash and liquor (parsley sauce) — the classic working-class London meal. The jellied eels are brave but worth trying at least once.",
    type: "London's oldest pie & mash shop",
    blog: "https://handluggageonly.co.uk/9-unusual-unique-restaurants-try-london/",
    website: "https://www.manze.co.uk"
  },
  {
    id: 22,
    nbhd: "borough",
    name: "The Garrison",
    cat: "pub",
    emoji: "🍺",
    address: "99–101 Bermondsey St, London SE1 3XB",
    lat: 51.5009, lng: -0.0830,
    search: "The Garrison pub Bermondsey London",
    note: "One of Bermondsey Street's best pubs — a gorgeous neighbourhood spot with a warm, welcoming feel. They serve excellent British pub grub and have a great selection of ales and wines. A brilliant place to rest your feet after exploring Bermondsey Street.",
    hours: "Mon–Thu 08:00–23:00; Fri–Sat 08:00–midnight; Sun 08:00–22:30",
    tip: "The Sunday roast here is very popular — book well in advance for a weekend lunch.",
    type: "British gastropub",
    blog: "https://handluggageonly.co.uk/15-of-the-best-areas-in-london-you-have-to-visit/",
    website: "https://thegarrison.co.uk"
  },

  // ── CITY OF LONDON ────────────────────────────────────────────────────────
  {
    id: 23,
    nbhd: "city",
    name: "Tower Bridge",
    cat: "landmark",
    emoji: "🌉",
    address: "Tower Bridge Rd, London SE1 2UP",
    lat: 51.5055, lng: -0.0754,
    search: "Tower Bridge London",
    note: "You can take a stroll across Tower Bridge, but you can also buy tickets and head inside the inner workings of the towers and walk along the suspended glass walkway high above the Thames. A visit takes around 45 minutes and is a perfect place for a more unique perspective of London's most famous bridge.",
    hours: "Daily 09:30–17:30",
    tip: "The glass walkway (45m above the Thames) is thrilling. Visit at dusk for the best photographs with the City skyline.",
    type: "Victorian bascule bridge & museum",
    blog: "https://handluggageonly.co.uk/28-very-best-things-to-do-in-london/",
    website: "https://www.towerbridge.org.uk"
  },
  {
    id: 24,
    nbhd: "city",
    name: "Tower of London",
    cat: "landmark",
    emoji: "🏰",
    address: "St Katharine's & Wapping, London EC3N 4AB",
    lat: 51.5081, lng: -0.0760,
    search: "Tower of London",
    note: "Book tickets to get inside and check out the Crown Jewels within the massive vaulted safe — they're incredible. Stroll through the Medieval Palace and learn more about the Bloody Tower. For something totally unique, book yourself in for the 'Ceremony of the Keys' — the oldest surviving military ceremony in the world.",
    hours: "Tue–Sat 09:00–17:30; Sun–Mon 10:00–17:30",
    tip: "The Yeoman Warder tours are free with entry and are fantastic. Book the Ceremony of the Keys months in advance — free tickets go fast.",
    type: "Historic royal fortress & UNESCO site",
    blog: "https://handluggageonly.co.uk/28-very-best-things-to-do-in-london/",
    website: "https://www.hrp.org.uk/tower-of-london"
  },
  {
    id: 25,
    nbhd: "city",
    name: "Sky Garden",
    cat: "nature",
    emoji: "🌿",
    address: "1 Sky Garden Walk, London EC3M 8AF",
    lat: 51.5111, lng: -0.0838,
    search: "Sky Garden London Walkie Talkie",
    note: "There is an amazing free view from the Sky Garden all over London. The landscaped garden on the 35th floor of the Walkie Talkie building offers 360-degree views across the city, and it's completely free. One of London's best-kept secrets for visitors who don't know about it.",
    hours: "Mon–Fri 10:00–18:00; Sat–Sun 11:00–21:00",
    tip: "You MUST book in advance — the free tickets go very fast. There's also a restaurant and bar if you want to linger.",
    type: "Free sky-high public garden & viewpoint",
    blog: "https://handluggageonly.co.uk/14-places-with-the-best-views-of-london-all-you-need-to-know-about-visiting-these-places/",
    website: "https://skygarden.london"
  },
  {
    id: 26,
    nbhd: "city",
    name: "Leadenhall Market",
    cat: "market",
    emoji: "🏛️",
    address: "Gracechurch St, London EC3V 1LT",
    lat: 51.5135, lng: -0.0831,
    search: "Leadenhall Market London",
    note: "A stone's throw from the Sky Garden, Leadenhall Market is one of London's oldest markets — it dates all the way back to the 1300s! The ornate Victorian covered arcade with its colourful painted ironwork is breathtaking, and Harry Potter fans will recognise it as Diagon Alley from the films.",
    hours: "Market: Mon–Fri 10:00–18:00; Pubs open longer",
    tip: "Visit early morning on a weekday when the City workers are arriving for the best atmosphere. The pubs here are old-school City watering holes.",
    type: "Historic Victorian covered market",
    blog: "https://handluggageonly.co.uk/28-very-best-things-to-do-in-london/",
    website: "https://leadenhallmarket.co.uk"
  },
  {
    id: 27,
    nbhd: "city",
    name: "Duck and Waffle",
    cat: "food",
    emoji: "🧇",
    address: "110 Bishopsgate, London EC2N 4AY",
    lat: 51.5142, lng: -0.0820,
    search: "Duck and Waffle restaurant London",
    note: "A lovely restaurant with an amazing view of London — perfect for sunrise or sunset as it's open 24 hours. The signature dish (duck confit on a waffle with a fried duck egg) is genuinely extraordinary. The 40th-floor views over the City and the Thames are spectacular.",
    hours: "Open 24/7",
    tip: "Book a sunrise slot for something truly magical — watching the city wake up from 40 floors up is unforgettable. The duck and waffle is non-negotiable.",
    type: "24-hour restaurant with skyline views",
    blog: "https://handluggageonly.co.uk/14-places-with-the-best-views-of-london-all-you-need-to-know-about-visiting-these-places/",
    website: "https://duckandwaffle.com"
  },
  {
    id: 28,
    nbhd: "city",
    name: "St Paul's Cathedral",
    cat: "church",
    emoji: "⛪",
    address: "St. Paul's Churchyard, London EC4M 8AD",
    lat: 51.5138, lng: -0.0984,
    search: "St Paul's Cathedral London",
    note: "Sir Christopher Wren's masterpiece is one of the most recognisable sights on the London skyline. Book tickets to enter and climb the 528 steps to the Golden Gallery for one of the best views in London. The Whispering Gallery inside the dome is a unique highlight — whisper into the wall and be heard on the other side.",
    hours: "Mon–Sat 08:30–16:30",
    tip: "Book tickets in advance. The climb to the top is worth every step. For the best exterior shot, stand on the Millennium Bridge.",
    type: "Iconic Baroque cathedral",
    blog: "https://handluggageonly.co.uk/28-very-best-things-to-do-in-london/",
    website: "https://www.stpauls.co.uk"
  },

  // ── COVENT GARDEN / SOHO ──────────────────────────────────────────────────
  {
    id: 29,
    nbhd: "covent-garden",
    name: "Covent Garden",
    cat: "market",
    emoji: "🌹",
    address: "Covent Garden, London WC2E 8RF",
    lat: 51.5117, lng: -0.1232,
    search: "Covent Garden London",
    note: "One of the best areas in London — packed with amazing restaurants, alleys to explore and brilliant street performers in the piazza. A trip to London wouldn't be complete without a wander through the Apple Market. Also don't miss Neal's Yard, a quirky hidden courtyard tucked away nearby.",
    hours: "Piazza open 24h; Market & shops: Mon–Sat 10:00–20:00; Sun 11:00–18:00",
    tip: "Arrive before 11am to see the Apple Market before it fills up. For the best street performers, come mid-afternoon.",
    type: "Historic market piazza & entertainment hub",
    blog: "https://handluggageonly.co.uk/londons-most-famous-district-covent-garden-what-to-see-eat-do/",
    website: "https://www.coventgarden.london"
  },
  {
    id: 30,
    nbhd: "covent-garden",
    name: "Neal's Yard",
    cat: "landmark",
    emoji: "🌈",
    address: "Neal's Yard, Covent Garden, London WC2H 9DP",
    lat: 51.5128, lng: -0.1262,
    search: "Neal's Yard Covent Garden London",
    note: "A tiny, vibrant courtyard tucked away behind Covent Garden that most visitors walk straight past. Its brightly painted walls and eclectic mix of health food shops and cafés make it one of the most photogenic corners of London. Find Neal's Yard Dairy here — the cheeses are extraordinary.",
    hours: "Shops open Mon–Sat 10:00–18:00",
    tip: "Look for the tiny alleyway entrances from Shorts Gardens or Neal Street. Neal's Yard Dairy is a must for cheese lovers.",
    type: "Hidden colourful courtyard",
    blog: "https://handluggageonly.co.uk/londons-most-famous-district-covent-garden-what-to-see-eat-do/",
    website: "https://www.nealsyard.co.uk"
  },
  {
    id: 31,
    nbhd: "covent-garden",
    name: "Clos Maggiore",
    cat: "food",
    emoji: "🌸",
    address: "33 King St, Covent Garden, London WC2E 8JD",
    lat: 51.5118, lng: -0.1243,
    search: "Clos Maggiore restaurant Covent Garden London",
    note: "One of my favourite restaurants in Covent Garden and totally worthy of visiting more than once. The restaurant atrium is gorgeously decorated with a retractable glass roof and flowering vines, and the food is incredible — some of the best contemporary French dishes in London. For lunch, it's a little cheaper and easier to get a table.",
    hours: "Mon–Sat 12:00–14:30, 17:00–23:00; Sun 12:00–15:30, 17:00–22:00",
    tip: "Book the main atrium for the most spectacular setting. The set lunch menu is excellent value. This is the most romantic restaurant in London.",
    type: "Award-winning French restaurant",
    blog: "https://handluggageonly.co.uk/11-amazing-restaurants-to-eat-at-in-london/",
    website: "https://www.closmaggiore.com"
  },
  {
    id: 32,
    nbhd: "covent-garden",
    name: "Barrafina",
    cat: "food",
    emoji: "🦐",
    address: "10 Adelaide St, London WC2N 4HZ",
    lat: 51.5097, lng: -0.1239,
    search: "Barrafina tapas London",
    note: "You can't reserve a table here — arrive just before midday and I guarantee your wait won't be too long. Once inside, you could be fooled into thinking you'd arrived in Spain. Make sure to try their fresh fish plates and the house tortilla. Although lunch here is pricier than other tapas joints, it is absolutely worth every penny.",
    hours: "Mon–Sat 12:00–15:00, 17:00–23:00; Sun 13:00–15:30, 17:00–22:00",
    tip: "No reservations — this is a walk-in only spot. Sit at the counter to watch the chefs. The ortiguillas (sea anemones) are adventurous but spectacular.",
    type: "Acclaimed Spanish tapas bar",
    blog: "https://handluggageonly.co.uk/11-amazing-restaurants-to-eat-at-in-london/",
    website: "https://barrafina.co.uk"
  },
  {
    id: 33,
    nbhd: "covent-garden",
    name: "Mr Fogg's Gin Parlour",
    cat: "pub",
    emoji: "🍸",
    address: "1 New Row, London WC2N 4EA",
    lat: 51.5110, lng: -0.1241,
    search: "Mr Fogg's Gin Parlour London",
    note: "One of the best gin parlours in all of London. They have every sort of gin cocktail you could ever imagine, with gins from all over the world. Inspired by Phileas Fogg's fictional travels, the décor is extraordinary — stuffed animals, antiques and globes everywhere. Just make sure to book a table — it fills up fast.",
    hours: "Mon–Thu 15:00–midnight; Fri–Sat 12:00–01:00; Sun 12:00–midnight",
    tip: "Book ahead — it's relatively small and gets very busy at weekends. Try the Aviation or Negroni with a rare gin. You will be pleasantly tipsy!",
    type: "Victorian gin & cocktail bar",
    blog: "https://handluggageonly.co.uk/londons-most-famous-district-covent-garden-what-to-see-eat-do/",
    website: "https://mr-foggs.com/gin-parlour"
  },
  {
    id: 34,
    nbhd: "covent-garden",
    name: "St Paul's Covent Garden",
    cat: "church",
    emoji: "⛪",
    address: "Bedford St, Covent Garden, London WC2E 9ED",
    lat: 51.5116, lng: -0.1231,
    search: "St Paul's Church Covent Garden London",
    note: "Built in the 1600s, St Paul's Covent Garden is often called the 'actors' church' because of its centuries-long affiliation with the performing arts community. Famous plaques line the walls — Vivien Leigh, Boris Karloff, Charlie Chaplin all commemated here. The small gardens inside are a lovely, peaceful escape.",
    hours: "Mon–Fri 08:30–17:00; Sun service 11:00",
    tip: "Free to enter. The garden entrance faces the Covent Garden piazza — perfect for watching street performers from the steps.",
    type: "Historic church of the arts",
    blog: "https://handluggageonly.co.uk/londons-most-famous-district-covent-garden-what-to-see-eat-do/",
    website: "https://www.actorschurch.org"
  },
  {
    id: 35,
    nbhd: "covent-garden",
    name: "Ronnie Scott's Jazz Club",
    cat: "pub",
    emoji: "🎷",
    address: "47 Frith St, Soho, London W1D 4HT",
    lat: 51.5133, lng: -0.1314,
    search: "Ronnie Scott's Jazz Club London",
    note: "One of the oldest and most famous jazz clubs in the world, right in the heart of Soho. Ronnie Scott's has hosted everyone from Miles Davis to Nina Simone since 1959. The atmosphere is always electric and totally unique — an unmissable London night out.",
    hours: "Mon–Sat 18:00–03:00; Sun 18:00–midnight",
    tip: "Book well in advance for headline acts. The late-night sets after the main show are often more intimate and cheaper.",
    type: "World-famous jazz club",
    blog: "https://handluggageonly.co.uk/28-very-best-things-to-do-in-london/",
    website: "https://www.ronniescotts.co.uk"
  },
  {
    id: 36,
    nbhd: "covent-garden",
    name: "Chinatown",
    cat: "food",
    emoji: "🏮",
    address: "Gerrard St, Chinatown, London W1D 5PT",
    lat: 51.5118, lng: -0.1311,
    search: "Chinatown London Gerrard Street",
    note: "Wander over to nearby Chinatown with all the tasty Asian restaurants and cool little bars that line the street. The red lanterns, the buzz and the sheer variety of food are fantastic. From dim sum to hot pot, it's one of the most exciting and affordable eating areas in central London.",
    hours: "Restaurants open daily from approx 11:00 to midnight",
    tip: "Head to Gerrard Street and the surrounding alleys. For cocktails with a 1920s Shanghai vibe, book Opium on Gerrard Street — totally incredible.",
    type: "Historic cultural quarter & food street",
    blog: "https://handluggageonly.co.uk/28-very-best-things-to-do-in-london/",
    website: "https://chinatownlondon.org"
  },
  {
    id: 37,
    nbhd: "covent-garden",
    name: "Opium Cocktail Bar",
    cat: "pub",
    emoji: "🍵",
    address: "15–16 Gerrard St, London W1D 6JE",
    lat: 51.5119, lng: -0.1306,
    search: "Opium cocktail bar Chinatown London",
    note: "Make a reservation at Opium for some cocktails that harken back to 1920s Shanghai. Tucked above Chinatown's Gerrard Street, this multi-floor bar has the most extraordinary atmosphere — neon, pounding music and dancers on the roof area. It's surreal and one of the best bars in London.",
    hours: "Mon–Thu 17:00–01:00; Fri 16:00–02:00; Sat 14:00–02:00; Sun 14:00–midnight",
    tip: "Book in advance — it fills up quickly on weekends. Try the signature 'Dragon' cocktail. The rooftop area is only open in summer.",
    type: "1920s Shanghai-inspired cocktail bar",
    blog: "https://handluggageonly.co.uk/28-very-best-things-to-do-in-london/",
    website: "https://www.opiumchinatown.com"
  },
  {
    id: 38,
    nbhd: "covent-garden",
    name: "Bob Bob Ricard",
    cat: "food",
    emoji: "🍾",
    address: "1 Upper James St, Soho, London W1F 9DF",
    lat: 51.5124, lng: -0.1389,
    search: "Bob Bob Ricard restaurant London",
    note: "Each table has a 'press for champagne' button — pop inside, press it and get an endless supply of bubbles. Just keep an eye on the costs! This completely unique Soho restaurant with its 1930s Orient Express décor is one of the most fun dining experiences in London.",
    hours: "Daily 12:30–15:00, 18:00–23:30",
    tip: "Make a reservation — this is a very popular spot. The beef Wellington and mac & cheese are legendary. Costs from £70+ pp but worth every penny.",
    type: "Champagne-button supper club",
    blog: "https://handluggageonly.co.uk/9-unusual-unique-restaurants-try-london/",
    website: "https://bobbobricard.com"
  },

  // ── CAMDEN ────────────────────────────────────────────────────────────────
  {
    id: 39,
    nbhd: "camden",
    name: "Camden Market",
    cat: "market",
    emoji: "🎸",
    address: "Camden Market, Camden High St, London NW1 8NH",
    lat: 51.5418, lng: -0.1455,
    search: "Camden Market London",
    note: "Perched just north of Kings Cross, the neighbourhood of Camden is one of London's most alternative and electric areas to explore. Camden Market is buzzing with life — from rock and roll fashion stalls, to street food from around the world, to vintage clothing. It's chaotic, colourful and totally brilliant.",
    hours: "Daily 10:00–18:00",
    tip: "The Stables Market section (past the Lock) is the best for authentic vintage finds and street food. Go on a weekday for a more relaxed experience.",
    type: "Iconic alternative market",
    blog: "https://handluggageonly.co.uk/28-very-best-things-to-do-in-london/",
    website: "https://www.camdenmarket.com"
  },
  {
    id: 40,
    nbhd: "camden",
    name: "Wellcome Collection",
    cat: "landmark",
    emoji: "🔬",
    address: "183 Euston Rd, London NW1 2BE",
    lat: 51.5258, lng: -0.1320,
    search: "Wellcome Collection museum London",
    note: "See the extraordinary curiosities collected by Sir Henry Wellcome over the years. This free museum at the intersection of medicine, life and art is utterly fascinating. From ancient surgical tools to stunning contemporary art, it's one of London's most thought-provoking and underrated museums.",
    hours: "Tue–Sun 10:00–18:00; Thu until 21:00; closed Mon",
    tip: "Free entry. Allow 2–3 hours to properly explore. The permanent 'Medicine Man' collection and the temporary exhibitions are both exceptional.",
    type: "Free museum of medicine & art",
    blog: "https://handluggageonly.co.uk/15-of-the-best-areas-in-london-you-have-to-visit/",
    website: "https://wellcomecollection.org"
  },
  {
    id: 41,
    nbhd: "camden",
    name: "The Roundhouse",
    cat: "landmark",
    emoji: "🎶",
    address: "Chalk Farm Rd, London NW1 8EH",
    lat: 51.5435, lng: -0.1466,
    search: "Roundhouse Camden London concert venue",
    note: "One of London's most iconic live music and performance venues, housed in a spectacular Victorian railway turntable shed. From Jimi Hendrix to Arctic Monkeys, the Roundhouse has been the spiritual home of London's alternative music scene since the 1960s. Even the building alone is worth seeing.",
    hours: "Varies per event; café open daily",
    tip: "Check the programme before visiting — there's almost always something on. The circular interior makes every seat feel close to the stage.",
    type: "Iconic circular live music venue",
    blog: "https://handluggageonly.co.uk/15-of-the-best-areas-in-london-you-have-to-visit/",
    website: "https://www.roundhouse.org.uk"
  },
  {
    id: 42,
    nbhd: "camden",
    name: "German Gymnasium",
    cat: "food",
    emoji: "🥩",
    address: "1 King's Blvd, King's Cross, London N1C 4BU",
    lat: 51.5308, lng: -0.1200,
    search: "German Gymnasium restaurant King's Cross London",
    note: "One of the prettiest restaurants in the King's Cross area, housed in Britain's first purpose-built gym (1865). They serve up some tasty Continental European food — the wiener schnitzel and braised pork knuckle are particularly good. Grand Café vibes with a brilliant atmosphere.",
    hours: "Mon–Fri 07:00–23:00; Sat–Sun 08:00–23:00",
    tip: "Great for a special weekend brunch or pre-theatre dinner. Booking is strongly advised.",
    type: "Grand café in a Victorian gymnasium",
    blog: "https://handluggageonly.co.uk/15-of-the-best-areas-in-london-you-have-to-visit/",
    website: "https://www.germangymnasium.com"
  },

  // ── NOTTING HILL ──────────────────────────────────────────────────────────
  {
    id: 43,
    nbhd: "notting-hill",
    name: "Portobello Road Market",
    cat: "market",
    emoji: "🎨",
    address: "Portobello Rd, Notting Hill, London W11",
    lat: 51.5163, lng: -0.2033,
    search: "Portobello Road Market Notting Hill London",
    note: "Beyond the colourful streets of Notting Hill is one of London's most famous street markets. Portobello Road is an epic wander — antiques, vintage clothing, fresh fruit and vegetables, street food and everything in between. The whole street has a gorgeous energy, especially on a Saturday.",
    hours: "Antiques: Sat 08:00–19:00; General market: Mon–Wed, Fri 09:00–18:00; Thu 09:00–13:00",
    tip: "Saturday is the big antiques day — arrive before 9am for the best finds. The northern end has the best vintage clothes stalls.",
    type: "Famous antiques & street market",
    blog: "https://handluggageonly.co.uk/15-of-the-best-areas-in-london-you-have-to-visit/",
    website: "https://www.portobelloroad.co.uk"
  },
  {
    id: 44,
    nbhd: "notting-hill",
    name: "Core by Clare Smyth",
    cat: "food",
    emoji: "⭐",
    address: "92 Kensington Park Rd, London W11 2PN",
    lat: 51.5176, lng: -0.2007,
    search: "Core by Clare Smyth restaurant Notting Hill",
    note: "If you are looking for a fine dining experience with flare, this is it. Clare Smyth's restaurant serves some of the tastiest seasonal menus in London. The 'Core Classic' tasting menu is extraordinary — about £125 for seven courses, but genuinely unforgettable. Not all about style over substance — this is the real deal.",
    hours: "Tue–Sat 12:00–14:00, 18:30–22:00; closed Sun–Mon",
    tip: "Book weeks in advance, especially for weekends. The shorter lunch menu is a great way to experience it at a slightly more accessible price.",
    type: "Three Michelin-star fine dining",
    blog: "https://handluggageonly.co.uk/secret-eats-in-london-where-to-eat-delicious-food-in-notting-hill/",
    website: "https://corebyclaresmyth.com"
  },
  {
    id: 45,
    nbhd: "notting-hill",
    name: "Luna Rossa",
    cat: "food",
    emoji: "🍕",
    address: "192 Kensington Park Rd, London W11 2ES",
    lat: 51.5163, lng: -0.2038,
    search: "Luna Rossa Italian restaurant Notting Hill London",
    note: "One of the best Italian restaurants in Notting Hill — and honestly one of the best Italians in London generally. The service in this relatively small restaurant is totally warm and lovely. Just make sure to leave plenty of room for their Cannoli Siciliani. It's a neighbourhood gem that locals guard jealously.",
    hours: "Daily 12:00–14:30, 18:30–22:30",
    tip: "Book in advance. Try the handmade tagliolini and the tiramisu — both are outstanding. The truffle dishes are seasonal and extraordinary.",
    type: "Authentic Italian neighbourhood restaurant",
    blog: "https://handluggageonly.co.uk/secret-eats-in-london-where-to-eat-delicious-food-in-notting-hill/",
    phone: "+44 20 7229 0482"
  },
  {
    id: 46,
    nbhd: "notting-hill",
    name: "Kalamaras Greek Taverna",
    cat: "food",
    emoji: "🧆",
    address: "76–78 Inverness Mews, London W2 3JQ",
    lat: 51.5172, lng: -0.1955,
    search: "Kalamaras Greek Taverna Notting Hill London",
    note: "Nestled within Inverness Mews, Kalamaras is probably one of the best restaurants in Notting Hill for Greek food. They have the tastiest mezze and Kléftiko which is perfect if you love roasted lamb. With just one mouthful of their Stifádo (a rich beef and onion stew), you'll be transported straight to a Greek island.",
    hours: "Tue–Sun 18:30–22:30; closed Mon",
    tip: "The mezze selection is the best way to sample everything. Order the house wine — it's excellent value. Booking essential.",
    type: "Traditional Greek taverna",
    blog: "https://handluggageonly.co.uk/secret-eats-in-london-where-to-eat-delicious-food-in-notting-hill/",
    phone: "+44 20 7727 9122"
  },
  {
    id: 47,
    nbhd: "notting-hill",
    name: "Electric Cinema",
    cat: "landmark",
    emoji: "🎬",
    address: "191 Portobello Rd, Notting Hill, London W11 2ED",
    lat: 51.5161, lng: -0.2007,
    search: "Electric Cinema Notting Hill London",
    note: "One of the UK's oldest cinemas (opened 1911) and still one of London's most special. With plush sofas, footstools and a full bar service, watching a film here is an experience in itself. The perfect end to a Portobello Road market day.",
    hours: "Shows daily from 12:00; bar opens 30 mins before first show",
    tip: "Book the double seats in the front rows for a date. The armchair seating in the back rows is also exceptional. Pre-book always.",
    type: "London's most stylish cinema",
    blog: "https://handluggageonly.co.uk/15-of-the-best-areas-in-london-you-have-to-visit/",
    website: "https://www.electriccinema.co.uk"
  },

  // ── KENSINGTON ────────────────────────────────────────────────────────────
  {
    id: 48,
    nbhd: "kensington",
    name: "Natural History Museum",
    cat: "landmark",
    emoji: "🦕",
    address: "Cromwell Rd, Kensington, London SW7 5BD",
    lat: 51.4967, lng: -0.1764,
    search: "Natural History Museum London",
    note: "One of London's absolute must-sees — and totally free! The spectacular Romanesque building alone is worth visiting. Inside, the blue whale skeleton in the Hintze Hall is jaw-dropping. You can spend hours and hours just exploring. Just make sure to plan your visit in advance.",
    hours: "Daily 10:00–17:50",
    tip: "Book a free timed entry in advance to guarantee entry. The Dinosaurs gallery and the Human Evolution section are highlights. Café inside for lunch.",
    type: "World-class natural history museum (free)",
    blog: "https://handluggageonly.co.uk/13-very-best-things-to-do-in-central-london/",
    website: "https://www.nhm.ac.uk"
  },
  {
    id: 49,
    nbhd: "kensington",
    name: "Victoria & Albert Museum",
    cat: "landmark",
    emoji: "🏺",
    address: "Cromwell Rd, Kensington, London SW7 2RL",
    lat: 51.4966, lng: -0.1722,
    search: "Victoria and Albert Museum London",
    note: "The V&A is the world's greatest museum of art, design and performance. From 5,000-year-old artefacts to 21st-century installations, the sheer breadth is staggering. The Cast Courts, the jewellery galleries and the fashion collection are all extraordinary. Free entry to the permanent collections.",
    hours: "Daily 10:00–17:45; Fri until 22:00",
    tip: "Free entry. The Friday late nights are much quieter and a great time to visit. Don't miss the Raphael Cartoons and the Cast Courts.",
    type: "World's greatest decorative arts museum (free)",
    blog: "https://handluggageonly.co.uk/28-very-best-things-to-do-in-london/",
    website: "https://www.vam.ac.uk"
  },
  {
    id: 50,
    nbhd: "kensington",
    name: "Science Museum",
    cat: "landmark",
    emoji: "🚀",
    address: "Exhibition Rd, Kensington, London SW7 2DD",
    lat: 51.4978, lng: -0.1748,
    search: "Science Museum London",
    note: "An incredible museum for all ages — you can easily spend half a day here. The Space Exploration gallery, the IMAX cinema and the interactive Wonderlab are highlights. The Apollo 10 command module that orbited the Moon is genuinely awe-inspiring to stand next to.",
    hours: "Daily 10:00–18:00",
    tip: "Free entry for the main galleries. Book the IMAX in advance. The Wonderlab is brilliant for families. Allow at least 3 hours.",
    type: "World-class science & technology museum (free)",
    blog: "https://handluggageonly.co.uk/28-very-best-things-to-do-in-london/",
    website: "https://www.sciencemuseum.org.uk"
  },
  {
    id: 51,
    nbhd: "kensington",
    name: "Harrods",
    cat: "market",
    emoji: "🛍️",
    address: "87–135 Brompton Rd, Knightsbridge, London SW1X 7XL",
    lat: 51.4994, lng: -0.1631,
    search: "Harrods Knightsbridge London",
    note: "The world's most famous department store and a London institution since 1849. Even if you're not shopping, exploring the food halls is a fantastic experience — the Egyptian Room, the chocolate hall and the fish counter are all extraordinary. A totally unique London landmark.",
    hours: "Mon–Sat 10:00–21:00; Sun 11:30–18:00",
    tip: "The basement food halls are absolutely worth exploring even if you're not buying. The ice cream parlour and the wine shop are personal favourites.",
    type: "World-famous luxury department store",
    blog: "https://handluggageonly.co.uk/28-very-best-things-to-do-in-london/",
    website: "https://www.harrods.com"
  },
  {
    id: 52,
    nbhd: "kensington",
    name: "The Harwood Arms",
    cat: "food",
    emoji: "🥩",
    address: "Walham Grove, Fulham, London SW6 1QP",
    lat: 51.4787, lng: -0.1946,
    search: "Harwood Arms Fulham London Sunday roast",
    note: "The Harwood Arms in Fulham makes an epic Sunday roast — and it's the only pub in London with a Michelin star. Mountains of veggies, golden roast potatoes, exceptional beef or lamb, Yorkshire pudding and the most incredible gravy. One of the best Sunday lunches you'll ever have.",
    hours: "Mon–Fri 18:00–22:00; Sat 12:00–15:00, 18:00–22:00; Sun 12:00–15:30",
    tip: "Book well in advance for Sunday lunch — it fills up months ahead. The venison Scotch egg as a starter is outstanding.",
    type: "Michelin-starred British gastropub",
    blog: "https://handluggageonly.co.uk/11-amazing-restaurants-to-eat-at-in-london/",
    website: "https://www.harwoodarms.com"
  },

  // ── GREENWICH ─────────────────────────────────────────────────────────────
  {
    id: 53,
    nbhd: "greenwich",
    name: "Royal Naval College",
    cat: "landmark",
    emoji: "⚓",
    address: "King William Walk, Greenwich, London SE10 9NN",
    lat: 51.4828, lng: -0.0073,
    search: "Royal Naval College Greenwich London",
    note: "Designed by Christopher Wren and one of London's most magnificent baroque complexes. The Painted Hall — often called 'the Sistine Chapel of the UK' — is utterly breathtaking. Walk through the twin domes and explore the grounds that stretch along the Thames. Free entry to much of the site.",
    hours: "Grounds: Daily 08:00–18:00; Painted Hall: Daily 10:00–17:00",
    tip: "Don't miss the Painted Hall — it's the highlight and honestly one of the most spectacular interiors in all of Britain. Arrive early to avoid tour groups.",
    type: "World Heritage baroque architecture",
    blog: "https://handluggageonly.co.uk/28-very-best-things-to-do-in-london/",
    website: "https://ornc.org"
  },
  {
    id: 54,
    nbhd: "greenwich",
    name: "Cutty Sark",
    cat: "landmark",
    emoji: "⛵",
    address: "King William Walk, Greenwich, London SE10 9HT",
    lat: 51.4831, lng: -0.0094,
    search: "Cutty Sark Greenwich London",
    note: "Built in 1869, the Cutty Sark is a British tea clipper ship steeped in history. One of the last tea clippers ever built, it's set in pride of place in the heart of Royal Greenwich. The restored ship is elevated so you can walk underneath the copper hull — a totally unique experience.",
    hours: "Daily 10:00–17:00",
    tip: "Walk under the ship's hull for the most dramatic view — quite extraordinary. The interactive exhibits about the clipper trade are genuinely engaging.",
    type: "Historic Victorian tea clipper",
    blog: "https://handluggageonly.co.uk/13-best-things-to-do-in-south-london/",
    website: "https://www.rmg.co.uk/cutty-sark"
  },
  {
    id: 55,
    nbhd: "greenwich",
    name: "National Maritime Museum",
    cat: "landmark",
    emoji: "🧭",
    address: "Romney Rd, Greenwich, London SE10 9NF",
    lat: 51.4813, lng: -0.0052,
    search: "National Maritime Museum Greenwich London",
    note: "The world's largest maritime museum and one of the best free museums in London. The collection traces Britain's relationship with the sea from Tudor times to the present day — Nelson's uniform from Trafalgar, charts from Cook's Pacific voyages and extraordinary ship models. Brilliant for adults and children.",
    hours: "Daily 10:00–17:00",
    tip: "Free entry. The Voyagers gallery and the Nelson's Navy section are both exceptional. Allow at least 2 hours and combine with the Royal Observatory next door.",
    type: "World's largest maritime museum (free)",
    blog: "https://handluggageonly.co.uk/11-best-things-to-do-in-greenwich-london/",
    website: "https://www.rmg.co.uk/national-maritime-museum"
  },
  {
    id: 56,
    nbhd: "greenwich",
    name: "Royal Observatory",
    cat: "nature",
    emoji: "🔭",
    address: "Blackheath Ave, Greenwich, London SE10 8XJ",
    lat: 51.4778, lng: 0.0015,
    search: "Royal Observatory Greenwich prime meridian London",
    note: "Stand at the Prime Meridian of the World (longitude 0°) and have your photo taken straddling both hemispheres! The views over Canary Wharf and London from the hilltop are stunning. Inside, the Meridian Line, Harrison's marine chronometers and the camera obscura are all extraordinary.",
    hours: "Daily 10:00–17:00",
    tip: "The view from the hilltop is one of London's best — and it's free even without entering the museum. Check the laser meridian at night which shoots north across the sky.",
    type: "Historic astronomical observatory & meridian line",
    blog: "https://handluggageonly.co.uk/11-best-things-to-do-in-greenwich-london/",
    website: "https://www.rmg.co.uk/royal-observatory"
  },
  {
    id: 57,
    nbhd: "greenwich",
    name: "Greenwich Market",
    cat: "market",
    emoji: "🎪",
    address: "5B Greenwich Market, London SE10 9HZ",
    lat: 51.4824, lng: -0.0093,
    search: "Greenwich Market London",
    note: "One of London's most charming covered markets, right in the heart of Greenwich. From artisan food and crafts to antiques and arts, the stalls are always interesting. It's a perfect lunchtime stop when exploring the area — the street food options are brilliant.",
    hours: "Daily 10:00–17:30",
    tip: "Food stalls tend to be busiest at lunchtime. The craft and antique sections on weekends are the most interesting.",
    type: "Covered artisan market",
    blog: "https://handluggageonly.co.uk/11-best-things-to-do-in-greenwich-london/",
    website: "https://greenwichmarket.london"
  },
  {
    id: 58,
    nbhd: "greenwich",
    name: "Greenwich Park",
    cat: "nature",
    emoji: "🌳",
    address: "Greenwich Park, London SE10 8QY",
    lat: 51.4785, lng: -0.0024,
    search: "Greenwich Park London views",
    note: "One of London's Royal Parks and arguably the most beautiful for views. Walk up the hill through the park for the most spectacular panorama over Canary Wharf, the Thames, and the City skyline. It's utterly magnificent. The deer enclosure is also a lovely surprise in the heart of southeast London.",
    hours: "Daily 06:00–21:00 (summer) / 06:00–18:00 (winter)",
    tip: "The hilltop view (near the Observatory) is one of the best free viewpoints in all of London. Visit early morning for fewer crowds and incredible light.",
    type: "Historic Royal Park with panoramic views",
    blog: "https://handluggageonly.co.uk/11-best-things-to-do-in-greenwich-london/",
    website: "https://www.royalparks.org.uk/parks/greenwich-park"
  }
];

// ── GLOBALS (do not rename — used across all platform files) ──
let map, markers={}, placesService, AID=null, AF='all', ANF='all';

// Category colours
const CC = {
  landmark:'#e8724a', food:'#f0c060', cafe:'#6b9e6e',
  church:'#6090c8',   market:'#c08060', pub:'#9080a8', nature:'#50906a'
};

// Category labels
const CL = {
  landmark:'Landmark & Sight', food:'Restaurant', cafe:'Café & Coffee',
  church:'Church & Heritage', market:'Market', pub:'Pub & Bar',
  nature:'Nature & Views'
};

// localStorage key — unique per guide
const FAVS_KEY      = 'london-favs';
const BLOGGER_NAME  = 'Hand Luggage Only';
const GUIDE_CITY    = 'London';
