// A Perfect Day — MUZA, Eretz Israel Museum (Tel Aviv)
// data.js — bilingual EN/HE. Each place carries en{} and he{} (and optionally ru{}, ar{}…);
//   i18n.js copies the active language into p.name / p.type / p.note / p.tip / p.address,
//   falling back to English for any field a language hasn't translated yet.
// Coordinates from OpenStreetMap building centroids. Exhibitions current as of 26 Jun 2026.

const PLACES = [
  {
    id: 1, nbhd: "east", cat: "pavilion", emoji: "🏺",
    lat: 32.1028378, lng: 34.7978806,
    website: "https://www.eretzmuseum.org.il/en/the-ceramics-pavilion/",
    en: { name: "Ceramics Pavilion", role: "Permanent collection", zone: "Eastern pavilions",
         desc: "Opened in 1966, the pavilion traces ceramics across seven sections — from the first fired-clay vessels of the Neolithic and Chalcolithic periods, through manufacturing, decoration and the role of pottery in early writing, to ritual art. Highlights: painted Neolithic potsherds, clay ossuaries, Greek black- and red-figure vessels, Islamic blue-glazed pottery, finds from the temples of Tell Qasile, and a full-scale reconstruction of a 3,000-year-old Israelite “Four-Room House”. The renewed courtyard adds contemporary works by Lidia Zavadsky and Uriel Caspi.",
         tip: "" },
    he: { name: "ביתן הקרמיקה", role: "תצוגת קבע", zone: "מתחם הביתנים המזרחי",
         desc: "הביתן, שנפתח ב-1966, מתחקה אחר תולדות הקרמיקה בשבעה חלקים — מכלי החרס השרופים הראשונים של התקופות הניאוליתית והכלקוליתית, דרך טכניקות ייצור ועיטור ותפקיד החרס בראשית הכתב, ועד אמנות ופולחן. בין המוצגים: שברי כלים ניאוליתיים מצוירים, גלוסקמאות חרס, כלים יווניים בטכניקת הדמויות השחורות והאדומות, קרמיקה אסלאמית בזיגוג כחול, ממצאים ממקדשי תל קסילה, ושחזור בגודל מלא של “בית ארבעת המרחבים” הישראלי בן 3,000 השנה. בחצר המחודשת מוצגות עבודות עכשוויות של לידיה זבצקי ואוריאל כספי.",
         tip: "" },
    ru: { name: "Павильон керамики", role: "Постоянная экспозиция", zone: "Восточные павильоны",
         desc: "Открытый в 1966 году павильон прослеживает историю керамики в семи разделах — от первых обожжённых глиняных сосудов неолита и халколита, через производство, декор и роль керамики в зарождении письма, до ритуального искусства. Среди экспонатов: расписные неолитические черепки, глиняные оссуарии, греческие чернофигурные и краснофигурные сосуды, исламская керамика с синей глазурью, находки из храмов Телль-Касиле и полноразмерная реконструкция израильского «четырёхкомнатного дома» возрастом 3000 лет. В обновлённом дворе добавлены современные работы Лидии Завадски и Уриэля Каспи.",
         tip: "" },
    ar: { name: "جناح الخزف", role: "مجموعة دائمة", zone: "الأجنحة الشرقية",
         desc: "افتُتح الجناح عام 1966، ويتتبّع تاريخ الخزف عبر سبعة أقسام — من أوائل الأواني الفخّارية المحروقة في العصرين الحجري الحديث والنحاسي، مروراً بالتصنيع والزخرفة ودور الفخّار في بدايات الكتابة، وصولاً إلى الفن الطقسي. من أبرز المعروضات: شقف فخّارية منقوشة من العصر الحجري الحديث، ونواويس طينية، وأوانٍ يونانية بالأشكال السوداء والحمراء، وخزف إسلامي بطلاء أزرق، مكتشفات من معابد تل قسيلة، ونموذج كامل الحجم لـ«بيت الغرف الأربع» الإسرائيلي الذي يعود إلى 3000 عام. ويضيف الفناء المجدَّد أعمالاً معاصرة لليديا زافادسكي وأوريئيل كاسبي.",
         tip: "" },
  },
  {
    id: 2, nbhd: "east", cat: "pavilion", emoji: "🫙",
    lat: 32.1024233, lng: 34.7972721,
    website: "https://www.eretzmuseum.org.il/en/the-glass-pavilion/",
    en: { name: "Glass Pavilion", role: "Permanent collection", zone: "Eastern pavilions",
         desc: "Built in 1959 around founder Dr. Walter Moses’s collection, this is one of the world’s finest collections of ancient glass — a permanent display spanning 3,000 years, from the ancient Near East to the decline of Islamic glass around 1400 CE. It runs from pre-blown glass through Roman and Byzantine blown glass to the Islamic period, ending at a Crusader-era glass furnace. Star pieces: Ennion’s signed Blue Jug, a rare Roman drinking horn, a gold-glass mosaic panel from Caesarea, and a 14th-century Mamluk mosque lamp.",
         tip: "Lit low to protect the glass — give your eyes a moment." },
    he: { name: "ביתן הזכוכית", role: "תצוגת קבע", zone: "מתחם הביתנים המזרחי",
         desc: "ביתן הזכוכית, שנבנה ב-1959 על בסיס אוסף מייסד המוזיאון ד’ר ולטר מוזס, מציג את אחד מאוספי הזכוכית העתיקה המשובחים בעולם — תצוגת קבע הפרושה על פני 3,000 שנה, מן המזרח הקדום ועד שקיעת זכוכית האסלאם סביב שנת 1400. התצוגה נעה מזכוכית טרום-ניפוח, דרך זכוכית מנופחת מן התקופות הרומית והביזנטית, ועד התקופה האסלאמית, ומסתיימת בכבשן זכוכית מן התקופה הצלבנית. בין פריטי המופת: הפך הכחול החתום של אניון, קרן שתייה רומית נדירה, לוח זכוכית-זהב ופסיפס מקיסריה, ומנורת מסגד ממלוכית מן המאה ה-14.",
         tip: "התצוגה מוארת בעמעום כדי להגן על הזכוכית — תנו לעיניים רגע להתרגל." },
    ru: { name: "Павильон стекла", role: "Постоянная экспозиция", zone: "Восточные павильоны",
         desc: "Созданный в 1959 году вокруг коллекции основателя музея д-ра Вальтера Мозеса, это одно из лучших в мире собраний древнего стекла — постоянная экспозиция охватывает 3000 лет, от древнего Ближнего Востока до заката исламского стекла около 1400 года. Она ведёт от стекла эпохи до выдувания, через римское и византийское выдувное стекло к исламскому периоду, и завершается стеклоплавильной печью эпохи крестоносцев. Жемчужины собрания: подписанный синий кувшин Энниона, редкий римский питьевой рог, панно из золотого стекла и мозаики из Кесарии и мамлюкская мечетная лампа XIV века.",
         tip: "Освещение приглушено, чтобы защитить стекло, — дайте глазам привыкнуть." },
    ar: { name: "جناح الزجاج", role: "مجموعة دائمة", zone: "الأجنحة الشرقية",
         desc: "أُنشئ الجناح عام 1959 حول مجموعة مؤسس المتحف د. والتر موزس، وهو من أرقى مجموعات الزجاج القديم في العالم — عرض دائم يمتد على 3000 عام، من الشرق الأدنى القديم حتى نهاية حقبة الزجاج الإسلامي نحو عام 1400م. يبدأ من الزجاج السابق للنفخ، مروراً بالزجاج المنفوخ الروماني والبيزنطي، إلى الفترة الإسلامية، وينتهي بفرن زجاج من عصر الصليبيين. من أبرز القطع: إبريق إينيون الأزرق الموقَّع، وقرن شراب روماني نادر، ولوحة من فسيفساء الزجاج الذهبي من قيسارية، ومصباح مسجد مملوكي من القرن الرابع عشر.",
         tip: "الإضاءة خافتة لحماية الزجاج — امنح عينيك لحظة حتى تعتاد." },
  },
  {
    id: 3, nbhd: "east", cat: "pavilion", emoji: "🪙",
    lat: 32.1031281, lng: 34.7970486,
    website: "https://www.eretzmuseum.org.il/en/kadman-numismatic-pavilion/",
    en: { name: "Kadman Numismatic Pavilion", role: "Permanent collection", zone: "Eastern pavilions",
         desc: "Inaugurated in 1962 around the collection of Leo Kadman, this is the largest numismatic collection in Israel and one of the largest in the world — tens of thousands of coins, banknotes, weights and medals. The display follows means of payment from pre-coinage barter (salt, shells, hacksilver) through the first Greek coins, the coins minted in the Land of Israel (Yehud, Hasmonean, Herodian, the Jewish War and Bar Kokhba Revolt), and the region under foreign rule, up to modern Israeli coins that echo ancient Jewish designs.",
         tip: "" },
    he: { name: "ביתן קדמן למטבעות", role: "תצוגת קבע", zone: "מתחם הביתנים המזרחי",
         desc: "הביתן, שנחנך ב-1962 סביב אוסף המטבעות של ליאו קדמן, הוא אוסף המטבעות הגדול בישראל ומן הגדולים בעולם — עשרות אלפי מטבעות, שטרות, משקלות ומדליות. התצוגה עוקבת אחר אמצעי התשלום מסחר-החליפין שקדם למטבע (מלח, צדפים, נתחי כסף), דרך המטבעות היווניים הראשונים, המטבעות שהוטבעו בארץ ישראל (יהוד, חשמונאי, הורדוסי, מרד החורבן ומרד בר-כוכבא), והארץ תחת שלטון זר, ועד מטבעות מדינת ישראל המודרניים, שעיצובם שואב מן המטבעות היהודיים הקדומים.",
         tip: "" },
    ru: { name: "Нумизматический павильон Кадмана", role: "Постоянная экспозиция", zone: "Восточные павильоны",
         desc: "Открытый в 1962 году вокруг коллекции Лео Кадмана, это крупнейшее нумизматическое собрание в Израиле и одно из крупнейших в мире — десятки тысяч монет, банкнот, гирь и медалей. Экспозиция прослеживает средства платежа от домонетного обмена (соль, раковины, обрезки серебра), через первые греческие монеты, монеты, чеканившиеся в Земле Израиля (Йехуд, Хасмонеи, Ирод, Иудейская война и восстание Бар-Кохбы), и регион под чужим владычеством, вплоть до современных израильских монет, перекликающихся с древнееврейскими образцами.",
         tip: "" },
    ar: { name: "جناح قدمان للمسكوكات", role: "مجموعة دائمة", zone: "الأجنحة الشرقية",
         desc: "افتُتح الجناح عام 1962 حول مجموعة ليو قدمان، وهو أكبر مجموعة مسكوكات في إسرائيل ومن أكبرها في العالم — عشرات الآلاف من العملات والأوراق النقدية والصنجات والميداليات. يتتبّع العرض وسائل الدفع من المقايضة السابقة للعملة (الملح والأصداف وقطع الفضة)، مروراً بأوائل العملات اليونانية، والعملات التي سُكّت في أرض إسرائيل (يهود، والحشمونائيم، والهيرودسيون، وحرب اليهود وثورة بار كوخبا)، والمنطقة تحت الحكم الأجنبي، وصولاً إلى العملات الإسرائيلية الحديثة التي تستلهم التصاميم اليهودية القديمة.",
         tip: "" },
  },
  {
    id: 4, nbhd: "east", cat: "pavilion", emoji: "⚒️",
    lat: 32.1025605, lng: 34.7976444,
    website: "https://www.eretzmuseum.org.il/en/nehushtan-pavilion/",
    en: { name: "Nehushtan Pavilion", role: "Copper & metallurgy", zone: "Eastern pavilions",
         desc: "The pavilion tells the story of ancient copper, based on excavations at Timna and Sinai — a reconstructed copper mine at the entrance, smelting furnaces from the Chalcolithic through the Iron Age, and rare organic finds (wood, textiles) preserved by the desert. It also shows “Midianite” Qurayyah painted pottery and finds from the Timna shrine of the Egyptian goddess Hathor, patroness of the miners.\n\n● Now showing:\n— Judgment Day, 2018–2022 — Neta Harari-Navon",
         tip: "" },
    he: { name: "ביתן נחושתן", role: "נחושת ומטלורגיה", zone: "מתחם הביתנים המזרחי",
         desc: "הביתן מספר את סיפור הפקת הנחושת הקדומה, על בסיס מחקר בתמנע (הערבה הדרומית) ובסיני — מכרה נחושת משוחזר בכניסה, כבשני היתוך מן התקופה הכלקוליתית ועד תקופת הברזל, וממצאים אורגניים נדירים (עץ ובדים) שנשתמרו בזכות יובש המדבר. כן מוצגים כלי חרס מדייניים מצוירים (קוריה) וממצאים ממקדש האלה המצרית חתחור, פטרונית הכורים, שהוקם במאות ה-13–12 לפנה”ס.\n\n● מציג עכשיו\n— יום דין 2018–2022 — נטע הררי־נבון (עד 30.4.2027)",
         tip: "" },
    ru: { name: "Павильон Нехуштан", role: "Медь и металлургия", zone: "Восточные павильоны",
         desc: "Павильон рассказывает историю древней меди на основе раскопок в Тимне и на Синае — реконструированный медный рудник у входа, плавильные печи от халколита до железного века и редкие органические находки (дерево, ткани), сохранённые пустыней. Здесь также показаны «мадианитянская» расписная керамика Курайя и находки из тимнского святилища египетской богини Хатхор, покровительницы рудокопов.\n\n● Сейчас в экспозиции:\n— «Судный день», 2018–2022 — Нета Харари-Навон",
         tip: "" },
    ar: { name: "جناح نحوشتان", role: "النحاس والميتالورجيا", zone: "الأجنحة الشرقية",
         desc: "يروي الجناح قصة النحاس القديم استناداً إلى الحفريات في تمناع وسيناء — منجم نحاس مُعاد بناؤه عند المدخل، وأفران صهر من العصر النحاسي حتى العصر الحديدي، مكتشفات عضوية نادرة (خشب وأنسجة) حفظها جفاف الصحراء. كما يعرض الفخّار المنقوش «المدياني» من قرية، مكتشفات من معبد الإلهة المصرية حتحور في تمناع، راعية عمّال المناجم.\n\n● يُعرض الآن:\n— يوم الدين، 2018–2022 — نيتا هراري-نافون",
         tip: "" },
  },
  {
    id: 5, nbhd: "core", cat: "pavilion", emoji: "🧰",
    lat: 32.1026292, lng: 34.796075,
    website: "https://www.eretzmuseum.org.il/en/the-man-and-his-work-center/",
    en: { name: "Man and His Work Center", role: "Crafts & ancient technology", zone: "Central core",
         desc: "Established in 1982 and named after Prof. Shmuel Avitzur, this ethnographic center preserves a vanishing world of traditional crafts across three areas. The Pavilion shows tools and installations of daily life up to early industrialization (food, building, spinning and weaving); the Crafts Arcade reconstructs eleven domed workshops — blacksmith, cobbler, potter, weaver, tinker, baker and more; and the outdoor Bread Courtyard centers on a reconstructed threshing floor with ploughs and threshing boards.",
         tip: "Look for the eleven reconstructed craft workshops in the domed arcade." },
    he: { name: "מרכז אדם ועמלו", role: "מלאכות וטכנולוגיה קדומה", zone: "מתחם המרכז",
         desc: "מרכז “אדם ועמלו”, שנוסד ב-1982 וקרוי על שם פרופ’ שמואל אביצור, משמר עולם נעלם של מלאכות יד ועבודה מסורתיות בשלושה אזורים. הביתן מציג כלים ומתקנים מחיי היום-יום עד ראשית התיעוש (עיבוד מזון, בנייה, טווייה ואריגה); שדרת בעלי המלאכה משחזרת אחת-עשרה כיפות סדנה — נפח, סנדלר, קדר, אורג, פחח ואופה ועוד; וחצר הלחם שבחוץ נסובה סביב גורן משוחזרת ובה מחרשות ולוחות דיש.",
         tip: "חפשו את 11 כיפות בעלי המלאכה בשדרה המקורה." },
    ru: { name: "Центр «Человек и его труд»", role: "Ремёсла и древние технологии", zone: "Центральная часть",
         desc: "Основанный в 1982 году и названный в честь профессора Шмуэля Авицура, этот этнографический центр сохраняет исчезающий мир традиционных ремёсел в трёх зонах. Павильон показывает орудия и установки повседневной жизни вплоть до ранней индустриализации (пища, строительство, прядение и ткачество); «Ремесленный пассаж» воссоздаёт одиннадцать купольных мастерских — кузнеца, сапожника, гончара, ткача, лудильщика, пекаря и других; а «Хлебный двор» под открытым небом устроен вокруг реконструированного гумна с плугами и молотильными досками.",
         tip: "Найдите одиннадцать воссозданных мастерских в купольном пассаже." },
    ar: { name: "مركز الإنسان وعمله", role: "الحِرف والتقنيات القديمة", zone: "المنطقة المركزية",
         desc: "تأسّس المركز عام 1982 وسُمّي باسم البروفيسور شموئيل أفيتسور، وهو مركز إثنوغرافي يحفظ عالماً آخذاً في الزوال من الحِرف التقليدية في ثلاثة أقسام. يعرض الجناح أدوات ومنشآت الحياة اليومية حتى بدايات التصنيع (الغذاء والبناء والغزل والنسيج)؛ ويعيد رواق الحِرف بناء إحدى عشرة ورشة مقبّبة — حدّاد، وإسكافي، وفخّاري، ونسّاج، وسمكري، وخبّاز وغيرهم؛ ويتمحور «فناء الخبز» في الهواء الطلق حول بيدر مُعاد بناؤه مع محاريث وألواح درس.",
         tip: "ابحث عن ورش الحِرف الإحدى عشرة المُعاد بناؤها في الرواق المقبّب." },
  },
  {
    id: 6, nbhd: "park", cat: "pavilion", emoji: "🕎",
    lat: 32.1009395, lng: 34.7946903,
    website: "https://www.eretzmuseum.org.il/en/jewish-culture-and-folklore-pavilion/",
    en: { name: "Jewish Culture & Folklore Pavilion", role: "Judaica & folklore", zone: "Western park",
         desc: "Judaica, ethnography and folklore from the museum’s collection, shown alongside contemporary art. One display traces local Judaica made here from the late 19th century to the 1960s; another gathers festival and life-cycle objects from communities worldwide — tefillin cases, tallitot, wedding costumes, jewelry, amulets and decorated ketubot. A special room holds an 18th-century Baroque-Rococo Torah Ark brought from Trino Vercellese in Piedmont, Italy — the only one of its kind in Israel. Reopened June 2024 after a full renovation.\n\nNote: the ketubot display is temporarily closed for the Biennale.",
         tip: "It sits inside the free public park — reachable even without a museum ticket." },
    he: { name: "הביתן לתרבות יהודית ולפולקלור", role: "יודאיקה ופולקלור", zone: "מתחם הבוסתן המערבי",
         desc: "הביתן מציג יודאיקה, אתנוגרפיה ופולקלור מאוסף המוזיאון לצד אמנות עכשווית. תצוגה אחת מתחקה אחר יודאיקה מקומית שנוצרה בארץ מסוף המאה ה-19 ועד שנות ה-60 ותפקידה בעיצוב הזהות היהודית-ישראלית; אחרת מאגדת חפצי חג ומעגל החיים מקהילות בעולם — בתי תפילין, טליתות, לבושי חתונה, תכשיטים, קמעות וכתובות מעוטרות. בחלל מיוחד ניצב ארון קודש (“היכל”) בסגנון בארוק-רוקוקו מן המאה ה-18, שהובא מטרינו ורצ’לזה שבפיימונטה, איטליה — היחיד מסוגו בישראל. נפתח מחדש ביוני 2024 לאחר שיפוץ מקיף.\n\nשימו לב: תצוגת הכתובות סגורה זמנית בשל הביאנלה.",
         tip: "נמצא בתוך הפארק הציבורי החופשי — נגיש גם בלי כרטיס למוזיאון." },
    ru: { name: "Павильон еврейской культуры и фольклора", role: "Иудаика и фольклор", zone: "Западный парк",
         desc: "Иудаика, этнография и фольклор из собрания музея, показанные рядом с современным искусством. Одна экспозиция прослеживает местную иудаику, созданную здесь с конца XIX века до 1960-х годов; другая собирает праздничные и обрядовые предметы из общин со всего мира — футляры для тфилин, талиты, свадебные наряды, украшения, амулеты и украшенные ктубы. В отдельном зале стоит ковчег Торы в стиле барокко-рококо XVIII века, привезённый из Трино-Верчеллезе в Пьемонте (Италия), — единственный такой в Израиле. Вновь открыт в июне 2024 года после полной реставрации.\n\nОбратите внимание: экспозиция ктуб временно закрыта из-за биеннале.",
         tip: "Находится в бесплатном общественном парке — доступен даже без билета в музей." },
    ar: { name: "جناح الثقافة اليهودية والفولكلور", role: "اليهوديات والفولكلور", zone: "الحديقة الغربية",
         desc: "يهوديات وإثنوغرافيا وفولكلور من مجموعة المتحف، تُعرض إلى جانب الفن المعاصر. يتتبّع أحد المعروضات اليهوديات المحلية التي صُنعت هنا من أواخر القرن التاسع عشر حتى الستينيات؛ ويجمع آخر أغراض الأعياد ودورة الحياة من جاليات حول العالم — علب تفيلين، وطاليتوت، وأزياء أعراس، وحُليّ، وتمائم، وعقود زواج (كتوبوت) مزخرفة. وتضمّ قاعة خاصة تابوت توراة بطراز الباروك-الروكوكو من القرن الثامن عشر، أُحضر من ترينو فيرتشيليزي في بييمونتي بإيطاليا — وهو الوحيد من نوعه في إسرائيل. أُعيد افتتاح الجناح في يونيو 2024 بعد ترميم شامل.\n\nملاحظة: عرض عقود الزواج مغلق مؤقتاً بسبب البيناليه.",
         tip: "يقع داخل الحديقة العامة المجانية — يمكن الوصول إليه حتى دون تذكرة المتحف." },
  },
  {
    id: 7, nbhd: "east", cat: "pavilion", emoji: "📮",
    lat: 32.1033136, lng: 34.79758,
    website: "https://www.eretzmuseum.org.il/en/alexander-pavilion-of-postal-history-and-philately/",
    en: { name: "Alexander Pavilion of Postal History & Philately", role: "Postal history", zone: "Eastern pavilions",
         desc: "Founded in 1998 for Israel’s 50th anniversary, the pavilion presents the history of the post in the Land of Israel — from the Ottoman period through the British Mandate to statehood and the first Doar Ivri stamps — with envelopes, letters, postcards and seals. Centerpieces: a 1949 red Ford F1 mail truck with Israel Post’s running-gazelle logo, 1930s–60s telephones, and the Planeta press that printed the state’s first stamp series. (The lower-level philately display, incl. the Zvi Alexander Collection, is temporarily closed.) The pavilion also hosts several of the museum’s temporary exhibitions.\n\n● Now showing:\n— Layers of Light: Analog Cameras\n— Postcards without Borders\n— Werner Braun: Between Water and Sky\n— Worth the Wait",
         tip: "" },
    he: { name: "ביתן אלכסנדר לתולדות הדואר והבולאות", role: "תולדות הדואר והבולאות", zone: "מתחם הביתנים המזרחי",
         desc: "הביתן, שנוסד ב-1998 לרגל שנת ה-50 למדינה, מציג את תולדות הדואר בארץ ישראל — מן התקופה העות’מאנית, דרך המנדט הבריטי, ועד הקמת המדינה ובולי “דואר עברי” הראשונים — בלוויית מעטפות, מכתבים, גלויות, חותמות ותצלומים. בין פריטי המרכז: משאית דואר אדומה מסוג פורד F1 משנת 1949 ועליה סמל הצבי הדוהר של דואר ישראל, אוסף טלפונים משנות ה-30 עד ה-60, ומכבש הדפוס “פלנטה” שבו הודפסה סדרת הבולים הראשונה של המדינה. (תצוגת הבולאות בקומה התחתונה, ובכללה אוסף צבי אלכסנדר, סגורה זמנית.) הביתן מארח גם כמה מן התערוכות המתחלפות של המוזיאון.\n\n● מציג עכשיו\n— תל אור: מצלמות אנלוגיות, 1860–2000 (עד 21.11.2026)\n— גלויות ללא גבולות, 1870–1930 (עד 3.10.2026)\n— ורנר בראון: בין מים לשמיים — ננעלת 30.6.2026\n— שווה לחכות, תערוכה לכל המשפחה (עד 31.7.2026)",
         tip: "" },
    ru: { name: "Павильон Александера: история почты и филателия", role: "История почты", zone: "Восточные павильоны",
         desc: "Основанный в 1998 году к 50-летию Израиля, павильон представляет историю почты в Земле Израиля — от османского периода через британский мандат до создания государства и первых марок «Доар Иври» — с конвертами, письмами, открытками и печатями. В центре экспозиции: красный почтовый грузовик Ford F1 1949 года с эмблемой бегущей газели Почты Израиля, телефоны 1930–60-х годов и печатный станок «Планета», на котором отпечатали первую серию марок государства. (Филателистическая экспозиция на нижнем уровне, включая коллекцию Цви Александера, временно закрыта.) В павильоне также проходят несколько временных выставок музея.\n\n● Сейчас в экспозиции:\n— «Слои света: аналоговые камеры»\n— «Открытки без границ»\n— «Вернер Браун: между водой и небом»\n— «Стоит подождать»",
         tip: "" },
    ar: { name: "جناح ألكسندر لتاريخ البريد والطوابع", role: "تاريخ البريد", zone: "الأجنحة الشرقية",
         desc: "تأسّس الجناح عام 1998 بمناسبة الذكرى الخمسين لإسرائيل، ويعرض تاريخ البريد في أرض إسرائيل — من العهد العثماني، مروراً بالانتداب البريطاني، إلى قيام الدولة وأوائل طوابع «دوآر عِفري» — مع مظاريف ورسائل وبطاقات بريدية وأختام. من أبرز المعروضات: شاحنة بريد حمراء من طراز فورد F1 عام 1949 تحمل شعار الغزال العادي لبريد إسرائيل، وهواتف من ثلاثينيات حتى ستينيات القرن العشرين، ومطبعة «بلانيتا» التي طُبعت بها أول سلسلة طوابع للدولة. (عرض الطوابع في الطابق السفلي، بما فيه مجموعة تسفي ألكسندر، مغلق مؤقتاً.) كما يستضيف الجناح عدداً من معارض المتحف المؤقتة.\n\n● يُعرض الآن:\n— طبقات الضوء: كاميرات أنالوغية\n— بطاقات بريدية بلا حدود\n— فيرنر براون: بين الماء والسماء\n— يستحق الانتظار",
         tip: "" },
  },
  {
    id: 8, nbhd: "core", cat: "hall", emoji: "🖼️",
    lat: 32.1022894, lng: 34.7958946,
    website: "https://www.eretzmuseum.org.il/en/the-tel-aviv-biennale-of-crafts-and-design-2026/",
    en: { name: "Rothschild Center & Main Exhibition Hall", role: "Main hall", zone: "Central core",
         desc: "The museum’s main hall for large temporary exhibitions, with an auditorium. It is the central hub of the 2026 Tel Aviv Biennale of Crafts & Design, whose works are spread across several pavilions.\n\n● Now showing:\n— Tel Aviv Biennale of Crafts & Design 2026: Works and Days",
         tip: "" },
    he: { name: "מרכז רוטשילד ואולם התערוכות המרכזי", role: "אולם ראשי", zone: "מתחם המרכז",
         desc: "אולם התערוכות המרכזי של המוזיאון לתערוכות זמניות גדולות, ובו אודיטוריום. הוא לב הביאנלה של תל אביב לאומנויות ולעיצוב 2026, שעבודותיה פרושות על פני כמה ביתנים.\n\n● מציג עכשיו\n— הביאנלה לאומנויות ולעיצוב תל אביב 2026: מעשים וימים (עד 30.11.2026)",
         tip: "" },
    ru: { name: "Центр Ротшильда и главный выставочный зал", role: "Главный зал", zone: "Центральная часть",
         desc: "Главный зал музея для крупных временных выставок, с аудиторией. Это центральная площадка Тель-Авивской биеннале ремёсел и дизайна 2026 года, работы которой размещены в нескольких павильонах.\n\n● Сейчас в экспозиции:\n— Тель-Авивская биеннале ремёсел и дизайна 2026: «Труды и дни»",
         tip: "" },
    ar: { name: "مركز روتشيلد والقاعة الرئيسية للمعارض", role: "القاعة الرئيسية", zone: "المنطقة المركزية",
         desc: "القاعة الرئيسية في المتحف للمعارض المؤقتة الكبرى، وبها قاعة محاضرات. وهي المركز الرئيسي لبيناليه تل أبيب للحِرف والتصميم 2026، التي تنتشر أعمالها عبر عدّة أجنحة.\n\n● يُعرض الآن:\n— بيناليه تل أبيب للحِرف والتصميم 2026: أعمال وأيام",
         tip: "" },
  },
  {
    id: 9, nbhd: "east", cat: "hall", emoji: "🎨",
    lat: 32.1023628, lng: 34.7975515,
    website: "https://www.eretzmuseum.org.il/en/exhibitions/",
    en: { name: "Migdal Gallery", role: "Exhibition gallery", zone: "Eastern pavilions",
         desc: "An exhibition gallery beside the Nehushtan and Ceramics pavilions, used for changing displays.",
         tip: "Easy to miss between the larger pavilions — look just west of Nehushtan." },
    he: { name: "גלריית מגדל", role: "גלריית תצוגה", zone: "מתחם הביתנים המזרחי",
         desc: "גלריית תצוגה לצד ביתני נחושתן והקרמיקה, המשמשת לתערוכות מתחלפות.",
         tip: "קל לפספס בין הביתנים הגדולים — מצויה ממש ממערב לנחושתן." },
    ru: { name: "Галерея Мигдаль", role: "Выставочная галерея", zone: "Восточные павильоны",
         desc: "Выставочная галерея рядом с павильонами Нехуштан и керамики, используемая для сменных экспозиций.",
         tip: "Легко пропустить между крупными павильонами — ищите сразу к западу от Нехуштана." },
    ar: { name: "صالة مغدال", role: "صالة عرض", zone: "الأجنحة الشرقية",
         desc: "صالة عرض بجوار جناحَي نحوشتان والخزف، تُستخدم للمعارض المتغيّرة.",
         tip: "يسهل تفويتها بين الأجنحة الكبرى — انظر إلى الغرب مباشرةً من نحوشتان." },
  },
  {
    id: 10, nbhd: "core", cat: "hall", emoji: "🎭",
    lat: 32.1027887, lng: 34.7955134,
    website: "https://www.eretzmuseum.org.il/en/exhibitions/postcards-from-yesterday/",
    en: { name: "Klatchkin Center & Auditorium", role: "Exhibition & auditorium", zone: "Central core",
         desc: "An exhibition space and auditorium just north of Tell Qasile, used for changing displays and for talks and screenings.\n\n● Now showing:\n— Postcards from Yesterday — Vera Vladimirsky",
         tip: "Check the auditorium programme for talks and screenings." },
    he: { name: "מרכז ואודיטוריום קלצ’קין", role: "תצוגה ואודיטוריום", zone: "מתחם המרכז",
         desc: "חלל תצוגה ואודיטוריום מצפון לתל קסילה, המשמש לתערוכות מתחלפות וכן להרצאות והקרנות.\n\n● מציג עכשיו\n— גלויות מאתמול — ורה ולדימירסקי (עד 31.12.2026)",
         tip: "בדקו את לוח האירועים של האודיטוריום להרצאות והקרנות." },
    ru: { name: "Центр и аудитория Клячкина", role: "Выставка и аудитория", zone: "Центральная часть",
         desc: "Выставочное пространство и аудитория к северу от Телль-Касиле, используемые для сменных экспозиций, лекций и показов.\n\n● Сейчас в экспозиции:\n— «Открытки из вчера» — Вера Владимирски",
         tip: "Посмотрите программу аудитории — лекции и показы." },
    ar: { name: "مركز وقاعة كلاتشكين", role: "عرض وقاعة محاضرات", zone: "المنطقة المركزية",
         desc: "مساحة عرض وقاعة محاضرات شمالي تل قسيلة، تُستخدم للمعارض المتغيّرة وللمحاضرات والعروض.\n\n● يُعرض الآن:\n— بطاقات من الأمس — فيرا فلاديميرسكي",
         tip: "اطّلع على برنامج القاعة لمعرفة المحاضرات والعروض." },
  },
  {
    id: 11, nbhd: "core", cat: "heritage", emoji: "⛰️",
    lat: 32.1019525, lng: 34.7952746,
    website: "https://www.eretzmuseum.org.il/en/open-spaces/",
    en: { name: "Tell Qasile", role: "Archaeological tell", zone: "Central core",
         desc: "A 3,000-year-old archaeological tell at the heart of the museum, with twelve layers of settlement and an ancient sacred complex of three temples built one atop another. Excavated from 1948 (the first dig permit issued by the State of Israel) by B. Mazar and later A. Mazar, it yielded rare ritual vessels — many now displayed in the Ceramics Pavilion — and is debated as a possible Philistine centre.",
         tip: "Climb to the top for the best overview of the whole campus." },
    he: { name: "תל קסילה", role: "תל ארכאולוגי", zone: "מתחם המרכז",
         desc: "תל ארכאולוגי בן 3,000 שנה בלב המוזיאון, ובו שתים-עשרה שכבות יישוב ומתחם מקדשים קדום של שלושה מקדשים שנבנו זה על גבי זה. נחפר החל מ-1948 (היתר החפירה הראשון שהעניקה מדינת ישראל) בידי בנימין מזר ולאחר מכן אמיחי מזר, והעלה כלי פולחן נדירים — רבים מהם מוצגים כיום בביתן הקרמיקה. זהותו כמרכז פלשתי אפשרי עדיין נדונה במחקר.",
         tip: "עלו לראש התל לתצפית הטובה ביותר על כל המתחם." },
    ru: { name: "Телль-Касиле", role: "Археологический телль", zone: "Центральная часть",
         desc: "Археологический телль возрастом 3000 лет в самом сердце музея, с двенадцатью слоями поселения и древним священным комплексом из трёх храмов, построенных один над другим. Раскопки велись с 1948 года (первое разрешение на раскопки, выданное Государством Израиль) Б. Мазаром, а затем А. Мазаром; здесь найдены редкие ритуальные сосуды — многие из них теперь выставлены в Павильоне керамики, — а его статус возможного филистимского центра обсуждается в науке.",
         tip: "Поднимитесь на вершину — лучший обзор всей территории." },
    ar: { name: "تل قسيلة", role: "تل أثري", zone: "المنطقة المركزية",
         desc: "تل أثري عمره 3000 عام في قلب المتحف، يضمّ اثنتي عشرة طبقة استيطانية ومجمّعاً مقدّساً قديماً من ثلاثة معابد بُنيت الواحد فوق الآخر. حُفر التل منذ عام 1948 (أول تصريح حفر تصدره دولة إسرائيل) على يد ب. مازار ثم أ. مازار، وكشف عن أوانٍ طقسية نادرة — يُعرض كثير منها الآن في جناح الخزف — ولا يزال احتمال كونه مركزاً فلستياً موضع نقاش علمي.",
         tip: "اصعد إلى القمة لتحظى بأفضل إطلالة على المكان بأكمله." },
  },
  {
    id: 12, nbhd: "core", cat: "heritage", emoji: "🛕",
    lat: 32.1019974, lng: 34.7956553,
    website: "https://www.eretzmuseum.org.il/en/open-spaces/",
    en: { name: "The Temples (Tell Qasile)", role: "Reconstructed sacred complex", zone: "Central core",
         desc: "The reconstructed sacred complex at the top of the tell — three temples built one above the other, of sun-dried brick with plastered benches. Offering and ritual vessels found here (some rare and unique) are on display in the Ceramics Pavilion; an altar surrounded by ash and animal bones points to sacrifice and communal feasting.",
         tip: "Pair this with the Ceramics Pavilion to see the finds in context." },
    he: { name: "המקדשים", role: "מתחם מקדשים משוחזר", zone: "מתחם המרכז",
         desc: "מתחם המקדשים המשוחזר בראש התל — שלושה מקדשים שנבנו זה על גבי זה, מלבני בוץ מיובשים בשמש ולהם ספסלים מטויחים. כלי הקרבה והפולחן שנמצאו כאן (חלקם נדירים וייחודיים) מוצגים בביתן הקרמיקה; מזבח שסביבו אפר ועצמות בעלי חיים מעיד על הקרבת קורבנות וסעודות קהילתיות.",
         tip: "שלבו ביקור כאן עם ביתן הקרמיקה כדי לראות את הממצאים בהקשרם." },
    ru: { name: "Храмы (Телль-Касиле)", role: "Реконструированный священный комплекс", zone: "Центральная часть",
         desc: "Реконструированный священный комплекс на вершине телля — три храма, построенные один над другим, из высушенного на солнце кирпича со скамьями, покрытыми штукатуркой. Найденные здесь жертвенные и ритуальные сосуды (некоторые редкие и уникальные) выставлены в Павильоне керамики; алтарь, окружённый золой и костями животных, указывает на жертвоприношения и общинные трапезы.",
         tip: "Совместите с Павильоном керамики, чтобы увидеть находки в контексте." },
    ar: { name: "المعابد (تل قسيلة)", role: "مجمّع مقدّس مُعاد بناؤه", zone: "المنطقة المركزية",
         desc: "المجمّع المقدّس المُعاد بناؤه في أعلى التل — ثلاثة معابد بُنيت الواحد فوق الآخر من الطوب المجفَّف بالشمس مع مصاطب مكسوّة بالجص. تُعرض أواني القرابين والطقوس التي عُثر عليها هنا (بعضها نادر وفريد) في جناح الخزف؛ ويشير مذبح محاط بالرماد وعظام الحيوانات إلى تقديم القرابين والولائم الجماعية.",
         tip: "اجمع بينه وبين جناح الخزف لرؤية المكتشفات في سياقها." },
  },
  {
    id: 13, nbhd: "core", cat: "heritage", emoji: "🧩",
    lat: 32.1030522, lng: 34.7957828,
    website: "https://www.eretzmuseum.org.il/en/open-spaces/",
    en: { name: "Square of Mosaic Floors", role: "Ancient mosaics", zone: "Central core",
         desc: "Ancient mosaic floors gathered from sites across Israel and laid out together in the open air — among them a 6th-century Samaritan prayer-house floor (in situ), a hunting-scene floor from Beit Guvrin, a Tiberias synagogue floor with lulavim and etrogim, and a Muslim prayer-house floor from Ramla. Together they testify to the many cultures — Samaritan, Jewish, Christian and Muslim — that lived here.",
         tip: "" },
    he: { name: "כיכר הפסיפסים", role: "פסיפסים עתיקים", zone: "מתחם המרכז",
         desc: "רצפות פסיפס עתיקות שנאספו מאתרים ברחבי הארץ והוצבו יחד תחת כיפת השמיים — ביניהן רצפת בית-תפילה שומרוני מן המאה ה-6 (במקומה המקורי), רצפת סצנות ציד מבית גוברין, רצפת בית כנסת מטבריה ובה לולבים ואתרוגים, ורצפת בית-תפילה מוסלמי מרמלה. יחד הן מעידות על שלל התרבויות — שומרונית, יהודית, נוצרית ומוסלמית — שחיו כאן.",
         tip: "" },
    ru: { name: "Площадь мозаичных полов", role: "Древние мозаики", zone: "Центральная часть",
         desc: "Древние мозаичные полы, собранные с памятников по всему Израилю и выложенные вместе под открытым небом, — среди них пол самаритянского молитвенного дома VI века (на исходном месте), пол со сценой охоты из Бейт-Гуврина, пол синагоги из Тверии с лулавами и этрогами и пол мусульманского молитвенного дома из Рамлы. Вместе они свидетельствуют о множестве культур — самаритянской, еврейской, христианской и мусульманской, — живших здесь.",
         tip: "" },
    ar: { name: "ساحة أرضيات الفسيفساء", role: "فسيفساء قديمة", zone: "المنطقة المركزية",
         desc: "أرضيات فسيفساء قديمة جُمعت من مواقع في أنحاء إسرائيل ورُصفت معاً في الهواء الطلق — منها أرضية دار صلاة سامرية من القرن السادس (في موضعها الأصلي)، وأرضية بمشهد صيد من بيت جبرين، وأرضية كنيس من طبريا تحمل اللولاف والأترج، وأرضية دار صلاة إسلامية من الرملة. وهي معاً تشهد على الثقافات العديدة — السامرية واليهودية والمسيحية والإسلامية — التي عاشت هنا.",
         tip: "" },
  },
  {
    id: 14, nbhd: "park", cat: "heritage", emoji: "🫒",
    lat: 32.1014195, lng: 34.7942218,
    website: "https://www.eretzmuseum.org.il/en/open-spaces/",
    en: { name: "Olive Press (Beit Ha’Bad)", role: "Reconstructed olive-oil plant", zone: "Western park",
         desc: "Reconstructed olive-oil installations spanning the Iron Age to the modern era — an Iron-Age beam-and-weights press from Tell Batash, a traditional Arab press with one of the largest known press beams (from Iksal in the Galilee), and 19th-century iron equipment, with crushing stones, weights and storage jars around the courtyard.",
         tip: "" },
    he: { name: "בית הבד", role: "בית בד משוחזר", zone: "מתחם הבוסתן המערבי",
         desc: "מתקני בית בד משוחזרים הפרושים מתקופת הברזל ועד העת החדשה — בית בד מסוג קורה ומשקלות מתל בטש (תקופת הברזל), בית בד ערבי מסורתי ובו אחת מקורות הבד הגדולות הידועות בארץ (מאכסאל שבגליל), וציוד ברזל מן המאה ה-19, ולצדם אבני כתישה, משקלות וקנקני אחסון בחצר.",
         tip: "" },
    ru: { name: "Маслодавильня (Бейт ха-Бад)", role: "Реконструированная маслобойня", zone: "Западный парк",
         desc: "Реконструированные установки для производства оливкового масла — от железного века до Нового времени: пресс с балкой и грузами железного века из Телль-Баташа, традиционный арабский пресс с одной из крупнейших известных давильных балок (из Иксаля в Галилее) и железное оборудование XIX века, а также давильные камни, грузы и сосуды для хранения во дворе.",
         tip: "" },
    ar: { name: "معصرة الزيتون (بيت البدّ)", role: "منشأة زيت زيتون مُعاد بناؤها", zone: "الحديقة الغربية",
         desc: "منشآت لعصر الزيتون مُعاد بناؤها تمتد من العصر الحديدي إلى العصر الحديث — معصرة بعارضة وأثقال من العصر الحديدي من تل بطاش، ومعصرة عربية تقليدية بإحدى أكبر عوارض العصر المعروفة (من إكسال في الجليل)، ومعدّات حديدية من القرن التاسع عشر، مع أحجار سحق وأثقال وجِرار تخزين حول الفناء.",
         tip: "" },
  },
  {
    id: 15, nbhd: "park", cat: "heritage", emoji: "⚙️",
    lat: 32.1008115, lng: 34.795315,
    website: "https://www.eretzmuseum.org.il/en/open-spaces/",
    en: { name: "Flour Mill", role: "Reconstructed watermill", zone: "Western park",
         desc: "A reconstructed water-powered flour mill at the foot of Tell Qasile, modelled on the mills that worked in northern Israel for centuries — water diverted through a conduit turns a wheel that drives the upper millstone. Such mills produced 30–50 kg of flour an hour and were vital social and economic centres.",
         tip: "" },
    he: { name: "טחנת קמח", role: "טחנת קמח משוחזרת", zone: "מתחם הבוסתן המערבי",
         desc: "טחנת קמח משוחזרת המונעת בכוח המים, למרגלות תל קסילה, על פי הטחנות שפעלו בצפון הארץ במשך מאות שנים — מים המוטים דרך תעלה מסובבים גלגל המניע את אבן הריחיים העליונה. טחנות כאלה הפיקו 30–50 ק”ג קמח בשעה והיו מרכזים חברתיים וכלכליים חיוניים.",
         tip: "" },
    ru: { name: "Мукомольная мельница", role: "Реконструированная водяная мельница", zone: "Западный парк",
         desc: "Реконструированная водяная мукомольная мельница у подножия Телль-Касиле, созданная по образцу мельниц, веками работавших на севере Израиля, — вода, отведённая по каналу, вращает колесо, приводящее в движение верхний жёрнов. Такие мельницы давали 30–50 кг муки в час и были важными социальными и экономическими центрами.",
         tip: "" },
    ar: { name: "طاحونة الدقيق", role: "ناعورة مُعاد بناؤها", zone: "الحديقة الغربية",
         desc: "طاحونة دقيق تعمل بالماء مُعاد بناؤها عند سفح تل قسيلة، على غرار الطواحين التي عملت في شمال إسرائيل لقرون — يُحوَّل الماء عبر قناة فيدير عجلة تحرّك حجر الرحى العلوي. كانت هذه الطواحين تنتج 30–50 كغ من الدقيق في الساعة وتُعدّ مراكز اجتماعية واقتصادية حيوية.",
         tip: "" },
  },
  {
    id: 16, nbhd: "park", cat: "heritage", emoji: "☀️",
    lat: 32.1023741, lng: 34.7934427,
    website: "https://www.eretzmuseum.org.il/en/open-spaces/",
    en: { name: "Sundial Square", role: "Square of sundials", zone: "Western park",
         desc: "A plaza of sundials beside the western gate, showing how time was once measured by the sun.",
         tip: "" },
    he: { name: "כיכר שעוני השמש", role: "כיכר שעוני שמש", zone: "מתחם הבוסתן המערבי",
         desc: "כיכר ובה שעוני שמש, ליד השער המערבי, הממחישה כיצד נמדד הזמן בעבר לפי השמש.",
         tip: "" },
    ru: { name: "Площадь солнечных часов", role: "Площадь солнечных часов", zone: "Западный парк",
         desc: "Площадь с солнечными часами у западных ворот, показывающая, как когда-то измеряли время по солнцу.",
         tip: "" },
    ar: { name: "ساحة المزاول الشمسية", role: "ساحة مزاول شمسية", zone: "الحديقة الغربية",
         desc: "ساحة بها مزاول شمسية بجوار البوابة الغربية، تُظهر كيف كان الزمن يُقاس قديماً بالشمس.",
         tip: "" },
  },
  {
    id: 17, nbhd: "core", cat: "heritage", emoji: "🍇",
    lat: 32.1027345, lng: 34.7964179,
    website: "https://www.eretzmuseum.org.il/en/open-spaces/",
    en: { name: "Wine Press", role: "Ancient rock-cut wine press", zone: "Central core",
         desc: "An ancient rock-cut wine press, one of several agricultural installations preserved across the grounds beside the crafts arcade.",
         tip: "" },
    he: { name: "גת", role: "גת עתיקה", zone: "מתחם המרכז",
         desc: "גת עתיקה חצובה בסלע, אחת מכמה מתקני חקלאות שנשתמרו במתחם, סמוך לשדרת בעלי המלאכה.",
         tip: "" },
    ru: { name: "Винодавильня", role: "Древняя винодавильня в скале", zone: "Центральная часть",
         desc: "Древняя винодавильня, высеченная в скале, — одна из нескольких сельскохозяйственных установок, сохранённых на территории рядом с ремесленным пассажем.",
         tip: "" },
    ar: { name: "معصرة النبيذ", role: "معصرة نبيذ قديمة منحوتة في الصخر", zone: "المنطقة المركزية",
         desc: "معصرة نبيذ قديمة منحوتة في الصخر، إحدى عدّة منشآت زراعية محفوظة في أرجاء المتحف بجوار رواق الحِرف.",
         tip: "" },
  },
  {
    id: 18, nbhd: "park", cat: "outdoor", emoji: "🌳",
    lat: 32.1015512, lng: 34.7947573,
    website: "https://www.eretzmuseum.org.il/en/muza-park/",
    en: { name: "MUZA Park (Bustan)", role: "Public park", zone: "Western park",
         desc: "The Jack, Joseph & Morton Mandel public park in the western grounds — free to enter, with a pond, an orchard and shaded “sheep-track” paths lined with seating, fountains, grapevine trellises and native Mediterranean planting. Within it: the Park Pond, the Olive Press and Flour Mill, the Planetarium, Sundial Square and the Folklore Pavilion.",
         tip: "Open 08:00–20:00, free of charge, through five gates around the grounds." },
    he: { name: "בוסתן מוז“א", role: "פארק ציבורי", zone: "מתחם הבוסתן המערבי",
         desc: "הפארק הציבורי ע”ש ג’ק, ג’וזף ומורטון מנדל בשטח המערבי — כניסה חופשית, ובו בריכה, בוסתן ושבילי “דרך הצאן” מוצלים ולצדם פינות ישיבה, מזרקות, סוכות גפנים וצמחייה ים-תיכונית מקומית. בתוכו: בריכת הפארק, בית הבד וטחנת הקמח, הפלנטריום, כיכר שעוני השמש והביתן לתרבות יהודית ולפולקלור.",
         tip: "פתוח 08:00–20:00, ללא תשלום, דרך חמישה שערים סביב המתחם." },
    ru: { name: "Парк МУЗА (Бустан)", role: "Общественный парк", zone: "Западный парк",
         desc: "Общественный парк имени Джека, Джозефа и Мортона Мандел в западной части — вход свободный, с прудом, садом и тенистыми тропами «овечьей тропы», вдоль которых расставлены скамьи, фонтаны, виноградные перголы и местные средиземноморские растения. В нём: пруд парка, маслодавильня и мукомольная мельница, планетарий, площадь солнечных часов и павильон фольклора.",
         tip: "Открыт 08:00–20:00, бесплатно, через пять ворот по периметру." },
    ar: { name: "حديقة موزا (البستان)", role: "حديقة عامة", zone: "الحديقة الغربية",
         desc: "حديقة جاك وجوزيف ومورتون مانديل العامة في الجهة الغربية — الدخول مجاني، وبها بركة وبستان ومسارات «درب الغنم» المظلّلة تحيط بها المقاعد والنوافير وتعريشات الكروم ونباتات متوسطية محلية. وتضمّ: بركة الحديقة، ومعصرة الزيتون وطاحونة الدقيق، والقبة الفلكية، وساحة المزاول الشمسية، وجناح الفولكلور.",
         tip: "مفتوحة 08:00–20:00 مجاناً، عبر خمس بوابات حول المتحف." },
  },
  {
    id: 19, nbhd: "park", cat: "outdoor", emoji: "🌿",
    lat: 32.1018744, lng: 34.794149,
    website: "https://www.eretzmuseum.org.il/en/open-spaces/",
    en: { name: "Jotam’s Parable Garden", role: "Themed garden", zone: "Western park",
         desc: "A small themed garden within the grounds, planted around the biblical parable of Jotam (the trees that sought a king).",
         tip: "A shaded detour between Sundial Square and the Folklore Pavilion." },
    he: { name: "גינת משל יותם", role: "גינה נושאית", zone: "מתחם הבוסתן המערבי",
         desc: "גינה נושאית קטנה במתחם, נטועה סביב משל יותם המקראי (העצים שביקשו להם מלך).",
         tip: "עצירה מוצלת בין כיכר שעוני השמש לביתן הפולקלור." },
    ru: { name: "Сад притчи Иотама", role: "Тематический сад", zone: "Западный парк",
         desc: "Небольшой тематический сад на территории, разбитый вокруг библейской притчи Иотама (о деревьях, искавших себе царя).",
         tip: "Тенистая остановка между площадью солнечных часов и павильоном фольклора." },
    ar: { name: "حديقة مَثَل يوتام", role: "حديقة موضوعية", zone: "الحديقة الغربية",
         desc: "حديقة موضوعية صغيرة داخل المتحف، غُرست حول مَثَل )قصة رمزية( يوتام التوراتي (الأشجار التي بحثت عن مَلِك).",
         tip: "محطة مظلَّلة بين ساحة المزاول الشمسية وجناح الفولكلور." },
  },
  {
    id: 20, nbhd: "core", cat: "outdoor", emoji: "🎪",
    lat: 32.1025127, lng: 34.7965899,
    website: "https://www.eretzmuseum.org.il/en/events/",
    en: { name: "Open-Air Theater", role: "Amphitheatre", zone: "Central core",
         desc: "An open-air amphitheatre used for concerts, performances and events through the season.",
         tip: "Check the events calendar for evening programmes." },
    he: { name: "תיאטרון פתוח", role: "אמפיתיאטרון", zone: "מתחם המרכז",
         desc: "אמפיתיאטרון פתוח המשמש לקונצרטים, הופעות ואירועים לאורך העונה.",
         tip: "בדקו את לוח האירועים לתוכניות ערב." },
    ru: { name: "Открытый театр", role: "Амфитеатр", zone: "Центральная часть",
         desc: "Амфитеатр под открытым небом для концертов, спектаклей и мероприятий в течение сезона.",
         tip: "Посмотрите календарь мероприятий — вечерние программы." },
    ar: { name: "المسرح المكشوف", role: "مدرّج", zone: "المنطقة المركزية",
         desc: "مدرّج في الهواء الطلق يُستخدم للحفلات والعروض والفعاليات على مدار الموسم.",
         tip: "اطّلع على روزنامة الفعاليات لمعرفة برامج المساء." },
  },
  {
    id: 21, nbhd: "park", cat: "service", emoji: "🪐",
    lat: 32.1023938, lng: 34.7939174,
    website: "https://www.eretzmuseum.org.il/en/planetarium/",
    en: { name: "Laski Planetarium", role: "Planetarium", zone: "Western park",
         desc: "Dedicated in 1968 and donated by Harry and Sadie Lasky, the planetarium projects an artificial sky onto a 12-metre dome — Israel’s largest domed screen — using a state-of-the-art Digistar 7 laser system, with seating for 110. It runs short shows for ages 5 and up, including “Stars” (a voyage across galaxies and the life and death of stars) and “Astronaut” (how astronauts train for spaceflight).",
         tip: "Shows run to a schedule and may need a separate ticket — check times at the entrance." },
    he: { name: "פלנטריום ע“ש לסקי", role: "פלנטריום", zone: "מתחם הבוסתן המערבי",
         desc: "הפלנטריום, שנחנך ב-1968 בתרומת הארי וסיידי לסקי, מקרין שמיים מלאכותיים על כיפה בקוטר 12 מטר — מסך הכיפה הגדול בישראל — באמצעות מערכת לייזר Digistar 7 מתקדמת, ובו 110 מושבים. מוצגות בו תוכניות קצרות לכל המשפחה מגיל 5 ומעלה, ובהן “כוכבים” (מסע בין גלקסיות וסיפור חייהם ומותם של כוכבים) ו“אסטרונאוט” (כיצד מתאמנים אסטרונאוטים לקראת טיסה לחלל).",
         tip: "ההקרנות לפי לוח זמנים ועשויות לדרוש כרטיס נפרד — בדקו שעות בכניסה." },
    ru: { name: "Планетарий Ласки", role: "Планетарий", zone: "Западный парк",
         desc: "Открытый в 1968 году и подаренный Гарри и Сэйди Ласки, планетарий проецирует искусственное небо на 12-метровый купол — крупнейший купольный экран Израиля — с помощью современной лазерной системы Digistar 7; зал на 110 мест. Здесь идут короткие программы для зрителей от 5 лет, в том числе «Звёзды» (путешествие по галактикам и история жизни и гибели звёзд) и «Астронавт» (как астронавты готовятся к полёту в космос).",
         tip: "Сеансы идут по расписанию и могут требовать отдельного билета — уточните время у входа." },
    ar: { name: "قبة لاسكي الفلكية", role: "قبة فلكية", zone: "الحديقة الغربية",
         desc: "افتُتحت القبة عام 1968 بتبرّع من هاري وسيدي لاسكي، وتعرض سماءً اصطناعية على قبة قطرها 12 متراً — أكبر شاشة قبّية في إسرائيل — باستخدام نظام ليزر متطوّر من طراز Digistar 7، وتتّسع لـ110 مقاعد. تُقدّم عروضاً قصيرة لمن هم في الخامسة فما فوق، منها «نجوم» (رحلة عبر المجرّات وقصة حياة النجوم وموتها) و«رائد فضاء» (كيف يتدرّب روّاد الفضاء استعداداً للرحلة).",
         tip: "تُعرض الجلسات وفق جدول وقد تتطلّب تذكرة منفصلة — تحقّق من المواعيد عند المدخل." },
  },
  {
    id: 22, nbhd: "core", cat: "service", emoji: "🎟️",
    lat: 32.1033125, lng: 34.7964146,
    website: "https://www.eretzmuseum.org.il/en/visit/",
    en: { name: "Main Entrance & Ticket Office", role: "Tickets & information", zone: "Northern entrance",
         desc: "Main entrance, ticketing and information, off Haim Levanon Street.",
         tip: "Pick up a printed map here and ask about the day’s guided tours." },
    he: { name: "כניסה ראשית וקופה", role: "כרטיסים ומידע", zone: "הכניסה הצפונית",
         desc: "הכניסה הראשית, הקופה והמידע, מרחוב חיים לבנון.",
         tip: "קחו מפה מודפסת ושאלו על הסיורים המודרכים של היום." },
    ru: { name: "Главный вход и касса", role: "Билеты и информация", zone: "Северный вход",
         desc: "Главный вход, касса и информация, со стороны улицы Хаим Леванон.",
         tip: "Возьмите здесь печатную карту и спросите о сегодняшних экскурсиях." },
    ar: { name: "المدخل الرئيسي وشبّاك التذاكر", role: "التذاكر والمعلومات", zone: "المدخل الشمالي",
         desc: "المدخل الرئيسي وشبّاك التذاكر والاستعلامات، من شارع حاييم ليفانون.",
         tip: "خذ خريطة مطبوعة من هنا واسأل عن الجولات المرشدة لهذا اليوم." },
  },
  {
    id: 23, nbhd: "core", cat: "service", emoji: "🛍️",
    lat: 32.103155, lng: 34.7962115,
    website: "https://www.muzashop.biz/",
    en: { name: "Museum Shop", role: "Books & gifts", zone: "Northern entrance",
         desc: "Books, gifts and exhibition catalogues, near the entrance and café.",
         tip: "" },
    he: { name: "חנות המוזיאון", role: "ספרים ומתנות", zone: "הכניסה הצפונית",
         desc: "ספרים, מתנות וקטלוגי תערוכות, ליד הכניסה ובית הקפה.",
         tip: "" },
    ru: { name: "Магазин музея", role: "Книги и подарки", zone: "Северный вход",
         desc: "Книги, подарки и каталоги выставок, рядом со входом и кафе.",
         tip: "" },
    ar: { name: "متجر المتحف", role: "كتب وهدايا", zone: "المدخل الشمالي",
         desc: "كتب وهدايا وكتالوجات المعارض، بالقرب من المدخل والمقهى.",
         tip: "" },
  },
  {
    id: 24, nbhd: "core", cat: "service", emoji: "☕",
    lat: 32.1031986, lng: 34.7960694,
    website: "https://www.instagram.com/artsicafe_il/",
    en: { name: "Artsi Café & Restaurant", role: "Café & restaurant", zone: "Northern entrance",
         desc: "At the entrance to the museum, Artsi Café by Petit Food offers a light, fresh menu — a pleasant spot to sit with friends or family in the open spaces of MUZA.",
         tip: "Shaded outdoor seating faces the grounds." },
    he: { name: "קפה ארטסי", role: "קפה ומסעדה", zone: "הכניסה הצפונית",
         desc: "בכניסה למוזיאון, קפה ארטסי של פטיט פוד מציע תפריט קליל וטרי — מקום נעים לשבת עם חברים או משפחה במרחבים הפתוחים של מוז“א.",
         tip: "ישיבה מוצלת בחוץ הפונה אל המתחם." },
    ru: { name: "Кафе и ресторан «Артси»", role: "Кафе и ресторан", zone: "Северный вход",
         desc: "У входа в музей кафе «Артси» от Petit Food предлагает лёгкое свежее меню — приятное место, чтобы посидеть с друзьями или семьёй на открытых пространствах МУЗА.",
         tip: "Тенистые места на улице с видом на территорию." },
    ar: { name: "مقهى ومطعم أرتسي", role: "مقهى ومطعم", zone: "المدخل الشمالي",
         desc: "عند مدخل المتحف، يقدّم مقهى أرتسي من Petit Food قائمة خفيفة وطازجة — مكان لطيف للجلوس مع الأصدقاء أو العائلة في فضاءات موزا المفتوحة.",
         tip: "مقاعد خارجية مظلَّلة تطلّ على أرجاء المتحف." },
  },
  {
    id: 25, nbhd: "core", cat: "service", emoji: "🏛️",
    lat: 32.102678, lng: 34.7956342,
    website: "https://www.eretzmuseum.org.il/en/hall-rental/",
    en: { name: "Nofim Hall", role: "Lecture & events hall", zone: "Central core",
         desc: "A lecture and events hall used for programmes and private functions.",
         tip: "Usually open only during scheduled events." },
    he: { name: "אולם נופים", role: "אולם הרצאות ואירועים", zone: "מתחם המרכז",
         desc: "אולם הרצאות ואירועים, המשמש לתוכניות ולאירועים פרטיים.",
         tip: "פתוח בדרך כלל רק במהלך אירועים מתוכננים." },
    ru: { name: "Зал «Нофим»", role: "Зал лекций и мероприятий", zone: "Центральная часть",
         desc: "Зал лекций и мероприятий, используемый для программ и частных событий.",
         tip: "Обычно открыт только во время запланированных мероприятий." },
    ar: { name: "قاعة نوفيم", role: "قاعة محاضرات وفعاليات", zone: "المنطقة المركزية",
         desc: "قاعة محاضرات وفعاليات تُستخدم للبرامج والمناسبات الخاصة.",
         tip: "تُفتح عادةً أثناء الفعاليات المخططة فقط." },
  },
  {
    id: 26, nbhd: "core", cat: "heritage", emoji: "🕊️",
    lat: 32.1022, lng: 34.79495,
    website: "https://www.eretzmuseum.org.il/en/open-spaces/",
    en: { name: "Yael Garden (The Bird Mosaic)", role: "The Bird Mosaic", zone: "Central core",
         desc: "At the heart of the museum, Yael Garden sets a stunning section of a mosaic found at Beit Guvrin — known as “The Bird Mosaic.” Made in the Byzantine period about 1,500 years ago (6th century CE), it is considered one of the most beautiful mosaics found in this country: vine tendrils spring from an amphora to form eight medallions of birds, with two peacocks holding a wreath above a Greek inscription honouring “Jesus, king of the world,” by the priest Obodianus. Restored by the Israel Antiquities Authority and UNESCO; the garden was established by the Olenik family in memory of Yael and Asher Olenik.",
         tip: "At the heart of the grounds — look for the peacocks and birds in the mosaic." },
    he: { name: "גן יעל", role: "פסיפס הציפורים", zone: "מתחם המרכז",
         desc: "בלב המוזיאון שוכן גן יעל, ובו משובץ קטע מרהיב מפסיפס שהתגלה בבית גוברין, הידוע כ“פסיפס הציפורים”. הפסיפס נוצר בתקופה הביזנטית לפני כ-1,500 שנה (המאה ה-6 לספירה) ונחשב עד היום לאחד היפים והמרשימים שנמצאו בארץ. הוא מעוטר בענפי גפן היוצאים מאמפורה ויוצרים שמונה מדליונים ובהם בעלי כנף, ולמעלה שני טווסים אוחזים זֵר, ולצדם כתובת יוונית לכבוד “ישו מלך העולם” מאת הכומר אובודיאנוס. הפסיפס שוחזר בידי רשות העתיקות ואונסק”ו; הגן הוקם בתרומת משפחת אולניק לזכר יעל ואשר אולניק.",
         tip: "בלב המתחם — חפשו את הטווסים והציפורים בפסיפס." },
    ru: { name: "Сад Яэль (Мозаика птиц)", role: "Мозаика птиц", zone: "Центральная часть",
         desc: "В сердце музея сад Яэль хранит великолепный фрагмент мозаики, найденной в Бейт-Гуврине и известной как «Мозаика птиц». Созданная в византийский период около 1500 лет назад (VI век н. э.), она считается одной из красивейших мозаик, найденных в стране: побеги виноградной лозы выходят из амфоры, образуя восемь медальонов с птицами, а вверху два павлина держат венок над греческой надписью в честь «Иисуса, царя мира», сделанной священником Ободианом. Отреставрирована Управлением древностей Израиля и ЮНЕСКО; сад создан семьёй Оленик в память о Яэль и Ашере Оленик.",
         tip: "В сердце территории — найдите павлинов и птиц в мозаике." },
    ar: { name: "حديقة ياعيل (فسيفساء الطيور)", role: "فسيفساء الطيور", zone: "المنطقة المركزية",
         desc: "في قلب المتحف، تضمّ حديقة ياعيل قطعة بديعة من فسيفساء عُثر عليها في بيت جبرين، تُعرف بـ«فسيفساء الطيور». صُنعت في الفترة البيزنطية قبل نحو 1500 عام (القرن السادس الميلادي)، وتُعدّ من أجمل ما عُثر عليه من فسيفساء في البلاد: تنطلق أغصان الكرمة من جرّة (أمفورا) لتشكّل ثماني ميداليات من الطيور، وفي الأعلى طاووسان يحملان إكليلاً فوق نقش يوناني يُكرّم «يسوع، ملك العالم» بقلم الكاهن أوبوديانوس. رُمّمت بإشراف سلطة الآثار الإسرائيلية واليونسكو؛ وأنشأت عائلة أولينيك الحديقة إحياءً لذكرى ياعيل وآشر أولينيك.",
         tip: "في قلب المتحف — ابحث عن الطاووسين والطيور في الفسيفساء." },
  },
  {
    id: 27, nbhd: "core", cat: "restroom", emoji: "🚻",
    lat: 32.1029867, lng: 34.7967841,
    website: "",
    img: "data:image/svg+xml,%3Csvg%20xmlns%3D%27http%3A//www.w3.org/2000/svg%27%20viewBox%3D%270%200%20400%20260%27%3E%3Crect%20width%3D%27400%27%20height%3D%27260%27%20fill%3D%27%235b7b8a%27/%3E%3Crect%20x%3D%27198%27%20y%3D%2755%27%20width%3D%274%27%20height%3D%27150%27%20fill%3D%27%23e6c34d%27/%3E%3Cg%20fill%3D%27%23f7f1e8%27%3E%3Ccircle%20cx%3D%27140%27%20cy%3D%2772%27%20r%3D%2717%27/%3E%3Crect%20x%3D%27123%27%20y%3D%2796%27%20width%3D%2734%27%20height%3D%2752%27%20rx%3D%278%27/%3E%3Crect%20x%3D%27128%27%20y%3D%27142%27%20width%3D%2710%27%20height%3D%2758%27%20rx%3D%273%27/%3E%3Crect%20x%3D%27142%27%20y%3D%27142%27%20width%3D%2710%27%20height%3D%2758%27%20rx%3D%273%27/%3E%3C/g%3E%3Cg%20fill%3D%27%23f7f1e8%27%3E%3Ccircle%20cx%3D%27260%27%20cy%3D%2772%27%20r%3D%2717%27/%3E%3Cpath%20d%3D%27M260%2094%20L232%20164%20H288%20Z%27/%3E%3Crect%20x%3D%27250%27%20y%3D%27160%27%20width%3D%279%27%20height%3D%2748%27%20rx%3D%273%27/%3E%3Crect%20x%3D%27261%27%20y%3D%27160%27%20width%3D%279%27%20height%3D%2748%27%20rx%3D%273%27/%3E%3C/g%3E%3C/svg%3E",
    en: { name: "Restrooms · Entrance", role: "Public restrooms", zone: "Northern entrance",
         desc: "Public restrooms near the main entrance, museum shop and café.",
         tip: "" },
    he: { name: "שירותים · הכניסה", role: "שירותים ציבוריים", zone: "הכניסה הצפונית",
         desc: "שירותים ציבוריים סמוך לכניסה הראשית, לחנות המוזיאון ולבית הקפה.",
         tip: "" },
    ru: { name: "Туалеты · Вход", role: "Общественные туалеты", zone: "Северный вход",
         desc: "Общественные туалеты рядом с главным входом, магазином и кафе.",
         tip: "" },
    ar: { name: "دورات المياه · المدخل", role: "دورات مياه عامة", zone: "المدخل الشمالي",
         desc: "دورات مياه عامة قرب المدخل الرئيسي ومتجر المتحف والمقهى.",
         tip: "" },
  },
  {
    id: 28, nbhd: "park", cat: "restroom", emoji: "🚻",
    lat: 32.1009229, lng: 34.7946082,
    website: "",
    img: "data:image/svg+xml,%3Csvg%20xmlns%3D%27http%3A//www.w3.org/2000/svg%27%20viewBox%3D%270%200%20400%20260%27%3E%3Crect%20width%3D%27400%27%20height%3D%27260%27%20fill%3D%27%235b7b8a%27/%3E%3Crect%20x%3D%27198%27%20y%3D%2755%27%20width%3D%274%27%20height%3D%27150%27%20fill%3D%27%23e6c34d%27/%3E%3Cg%20fill%3D%27%23f7f1e8%27%3E%3Ccircle%20cx%3D%27140%27%20cy%3D%2772%27%20r%3D%2717%27/%3E%3Crect%20x%3D%27123%27%20y%3D%2796%27%20width%3D%2734%27%20height%3D%2752%27%20rx%3D%278%27/%3E%3Crect%20x%3D%27128%27%20y%3D%27142%27%20width%3D%2710%27%20height%3D%2758%27%20rx%3D%273%27/%3E%3Crect%20x%3D%27142%27%20y%3D%27142%27%20width%3D%2710%27%20height%3D%2758%27%20rx%3D%273%27/%3E%3C/g%3E%3Cg%20fill%3D%27%23f7f1e8%27%3E%3Ccircle%20cx%3D%27260%27%20cy%3D%2772%27%20r%3D%2717%27/%3E%3Cpath%20d%3D%27M260%2094%20L232%20164%20H288%20Z%27/%3E%3Crect%20x%3D%27250%27%20y%3D%27160%27%20width%3D%279%27%20height%3D%2748%27%20rx%3D%273%27/%3E%3Crect%20x%3D%27261%27%20y%3D%27160%27%20width%3D%279%27%20height%3D%2748%27%20rx%3D%273%27/%3E%3C/g%3E%3C/svg%3E",
    en: { name: "Restrooms · Folklore Pavilion", role: "Public restrooms", zone: "Western Park",
         desc: "Public restrooms by the Jewish Culture & Folklore Pavilion, in the western park.",
         tip: "" },
    he: { name: "שירותים · ביתן הפולקלור", role: "שירותים ציבוריים", zone: "הפארק המערבי",
         desc: "שירותים ציבוריים ליד ביתן התרבות והפולקלור היהודי, בפארק המערבי.",
         tip: "" },
    ru: { name: "Туалеты · Павильон фольклора", role: "Общественные туалеты", zone: "Западный парк",
         desc: "Общественные туалеты у Павильона еврейской культуры и фольклора, в западном парке.",
         tip: "" },
    ar: { name: "دورات المياه · جناح الفولكلور", role: "دورات مياه عامة", zone: "الحديقة الغربية",
         desc: "دورات مياه عامة بجانب جناح الثقافة والفولكلور اليهودي، في الحديقة الغربية.",
         tip: "" },
  },
  {
    id: 29, nbhd: "park", cat: "restroom", emoji: "🚻",
    lat: 32.1006262, lng: 34.7943128,
    website: "",
    img: "data:image/svg+xml,%3Csvg%20xmlns%3D%27http%3A//www.w3.org/2000/svg%27%20viewBox%3D%270%200%20400%20260%27%3E%3Crect%20width%3D%27400%27%20height%3D%27260%27%20fill%3D%27%235b7b8a%27/%3E%3Crect%20x%3D%27198%27%20y%3D%2755%27%20width%3D%274%27%20height%3D%27150%27%20fill%3D%27%23e6c34d%27/%3E%3Cg%20fill%3D%27%23f7f1e8%27%3E%3Ccircle%20cx%3D%27140%27%20cy%3D%2772%27%20r%3D%2717%27/%3E%3Crect%20x%3D%27123%27%20y%3D%2796%27%20width%3D%2734%27%20height%3D%2752%27%20rx%3D%278%27/%3E%3Crect%20x%3D%27128%27%20y%3D%27142%27%20width%3D%2710%27%20height%3D%2758%27%20rx%3D%273%27/%3E%3Crect%20x%3D%27142%27%20y%3D%27142%27%20width%3D%2710%27%20height%3D%2758%27%20rx%3D%273%27/%3E%3C/g%3E%3Cg%20fill%3D%27%23f7f1e8%27%3E%3Ccircle%20cx%3D%27260%27%20cy%3D%2772%27%20r%3D%2717%27/%3E%3Cpath%20d%3D%27M260%2094%20L232%20164%20H288%20Z%27/%3E%3Crect%20x%3D%27250%27%20y%3D%27160%27%20width%3D%279%27%20height%3D%2748%27%20rx%3D%273%27/%3E%3Crect%20x%3D%27261%27%20y%3D%27160%27%20width%3D%279%27%20height%3D%2748%27%20rx%3D%273%27/%3E%3C/g%3E%3C/svg%3E",
    en: { name: "Restrooms · Western Park", role: "Public restrooms", zone: "Western Park",
         desc: "Public restrooms in the western park, near the Flour Mill and Olive Press.",
         tip: "" },
    he: { name: "שירותים · הפארק המערבי", role: "שירותים ציבוריים", zone: "הפארק המערבי",
         desc: "שירותים ציבוריים בפארק המערבי, סמוך לטחנת הקמח ולבית הבד.",
         tip: "" },
    ru: { name: "Туалеты · Западный парк", role: "Общественные туалеты", zone: "Западный парк",
         desc: "Общественные туалеты в западном парке, рядом с мельницей и маслобойней.",
         tip: "" },
    ar: { name: "دورات المياه · الحديقة الغربية", role: "دورات مياه عامة", zone: "الحديقة الغربية",
         desc: "دورات مياه عامة في الحديقة الغربية، قرب مطحنة الدقيق ومعصرة الزيتون.",
         tip: "" },
  },
];
