// A Perfect Day — London
// london_data_v4.js — 50 curated places
//
// v7 — May 2026
// Voice: boutique hotel concierge — direct, specific, opinionated
// Six categories: Art & Design · Shop · Royal London · From the Movies · Fine Dining · Pubs & Bars
//
// v7 changes: Full structural rebuild.
//   Cut from 71 to 50 places. New categories: art, shop, royal, film, dining, pub.
//   Removed 33 entries. Added 12 new entries:
//     Kensington Palace (82), Fortnum & Mason (83), The Ritz (84), Claridge's (85),
//     Floris (86), Lock & Co (87), Saatchi Gallery (76), Serpentine Galleries (77),
//     Newport Street Gallery (78), Dover Street Market (79), Liberty London (80),
//     Bermondsey Antique Market (81).
//   Rewrote all existing entries with new category angles.
//   All facts verified May 2026. Bibendum removed (closed August 2025).

const PLACES = [

  // ── WESTMINSTER ───────────────────────────────────────────────────────────

  {
    id: 1,
    nbhd: 'westminster',
    name: 'Berry Bros. & Rudd',
    cat: 'shop',
    emoji: '🍷',
    address: '3 St James\'s St, London SW1A 1EG',
    lat: 51.5063, lng: -0.1388,
    search: 'Berry Bros Rudd wine merchant interior St James\'s London',
    note: 'Britain\'s oldest wine merchant, trading from the same St James\'s building since 1698. Walk in and nothing has been renovated for atmosphere — the Georgian panelling, the ancient coffee-weighing scales on the floor, the bare boards worn into hollows over three centuries are simply what the place looks like. They hold Royal Warrants from both King Charles III and the Prince of Wales. The basement cellars run under St James\'s Street and hold one of the finest private wine collections in the country. The staff know their inventory the way a good bookseller knows books — with genuine opinions — and will tell you exactly what to open, when, and with what. Wine courses, cellar events and private dining run from the vaulted rooms below the street. The shop itself is the reason to come before any of that.',
    hours: 'Mon–Fri 10:00–18:00; Sat 10:00–17:00; closed Sun',
    tip: 'Ask for a recommendation at your price point — the response will be specific and correct. Cellar tours and tastings bookable on the website.',
    type: 'Britain\'s oldest wine merchant (est. 1698) — St James\'s',
    website: 'https://www.bbr.com',
  },
  {
    id: 73,
    nbhd: 'westminster',
    name: 'The Connaught Bar',
    cat: 'pub',
    emoji: '🍸',
    address: 'Carlos Place, Mayfair, London W1K 2AL',
    lat: 51.5118, lng: -0.1488,
    search: 'Connaught Bar martini trolley Art Deco interior',
    note: 'Ranked #6 in The World\'s 50 Best Bars 2025, after holding the top position for several consecutive years — which makes it consistently one of the most discussed cocktail rooms on earth. The space is all marble, mirror and Art Deco curves, and the dry martini service arrives on a silver trolley, mixed tableside to your exact specification from a choice of vermouths and bitters. The ritual is as precise as the drink. Order whatever you want, but ask the bartender to begin with the Connaught Martini and work out from there. The room fills completely by 20:00 at weekends; book well ahead.',
    hours: 'Mon–Sat 11:00–00:00; Sun 11:00–23:00',
    tip: 'Book ahead — the bar fills completely at weekends. The dry martini trolley is the experience. Ask the bartender for their recommendation on vermouth ratio.',
    type: 'World\'s #6 cocktail bar 2025 — Mayfair, The Connaught Hotel',
    awards: '#6 The World\'s 50 Best Bars 2025',
    website: 'https://www.the-connaught.co.uk/bars-restaurant/the-connaught-bar/',
  },
  {
    id: 74,
    nbhd: 'westminster',
    name: 'Dukes Bar',
    cat: 'pub',
    emoji: '🍋',
    address: '35 St James\'s Place, London SW1A 1NY',
    lat: 51.5065, lng: -0.1418,
    search: 'Dukes Bar interior St James London cocktail martini',
    note: 'Inside Dukes Hotel in St James\'s, in a room that seats perhaps 30 people and looks unchanged since Ian Fleming drank here and worked out the formula that became James Bond\'s martini. The dry martini service is conducted tableside: frozen gin, no dilution from ice, poured with ceremony into a pre-chilled glass. Bone dry, extremely cold, served with unhurried precision. The two-martini house limit per person is genuine advice, not theatrical caution. Fleming\'s vesper — vodka, gin, Lillet — is on the menu by name. If there is a purer expression of a cocktail bar\'s reason for existing, it is not in London.',
    hours: 'Mon–Sat 12:00–23:00; Sun 12:00–22:30',
    tip: 'The two-martini rule exists for good reason. The vesper is the Fleming original. Book ahead.',
    type: 'Historic cocktail bar — the birthplace of Bond\'s martini',
    website: 'https://www.dukeshotel.com/dukes-bar',
  },
  {
    id: 59,
    nbhd: 'westminster',
    name: 'Daunt Books',
    cat: 'shop',
    emoji: '📚',
    address: '83–84 Marylebone High St, London W1U 4QW',
    lat: 51.5200, lng: -0.1533,
    search: 'Daunt Books interior skylight Marylebone London bookshop',
    note: 'The back room is what makes people come back: long oak galleries under a central skylight, books arranged by country rather than genre — fiction, history, travel writing and maps for each destination all shelved together. The 1912 Edwardian building was designed as a bookshop and has been nothing else since. The linen tote bag, sold at the counter, has become a more credible London souvenir than anything from a gift shop. The staff are genuinely well-read and have strong opinions about what is worth your time. Ask them. Marylebone High Street deserves the whole morning.',
    hours: 'Mon–Sat 09:00–19:30; Sun 11:00–18:00',
    tip: 'The back room under the skylight is the most beautiful reading space in London. Ask for recommendations — the staff read everything and are not shy about it.',
    type: 'The world\'s most beautiful independent bookshop',
    website: 'https://dauntbooks.co.uk/shops/marylebone/',
  },
  {
    id: 3,
    nbhd: 'westminster',
    name: 'Churchill War Rooms',
    cat: 'film',
    emoji: '🎬',
    address: 'Clive Steps, King Charles Street, London SW1A 2AQ',
    lat: 51.5020, lng: -0.1289,
    search: 'Churchill War Rooms Map Room bunker London wartime',
    note: 'Gary Oldman won the Academy Award for Best Actor playing Winston Churchill in Darkest Hour (2017), and the filmmakers used these exact rooms as reference for every set they built. The Crown (Netflix, 2016) returned here repeatedly for its Churchill episodes. Both productions spent months recreating what you can simply walk through: the Cabinet War Rooms beneath Whitehall, sealed on VE Day 1945 and left exactly as they were — maps still pinned, phones still connected, a single light bulb burning in the Map Room that has not been switched off since the war. Every film and television production about Churchill is trying to make you feel what this building delivers in person: that wars are fought not from glory, but from a corridor with low ceilings and bad lighting. The Churchill Museum beside it is one of the most intelligent biographical exhibitions in London.',
    hours: 'Daily 09:30–18:00',
    tip: 'Two hours minimum. The Churchill Museum alongside the bunker is as compelling as the rooms themselves.',
    type: 'Preserved WWII bunker — as seen in Darkest Hour (2017) and The Crown',
    website: 'https://www.iwm.org.uk/visits/churchill-war-rooms',
  },
  {
    id: 83,
    nbhd: 'westminster',
    name: 'Fortnum & Mason',
    cat: 'royal',
    emoji: '👑',
    address: '181 Piccadilly, London W1A 1ER',
    lat: 51.5075, lng: -0.1393,
    search: 'Fortnum Mason food hall interior Piccadilly London hampers',
    note: 'Established in 1707 by William Fortnum, a footman in Queen Anne\'s household who noticed that partly used royal candles could be collected and resold, and used his savings to open a grocery with his landlord Hugh Mason. Three centuries later the shop holds Royal Warrants from King Charles III and Queen Camilla — the 2024 Camilla warrant among the first she granted — and remains what it has always been: the most extraordinary food shop in London. The building on Piccadilly is five floors of teas, hampers, preserves, wine, chocolate and provisions arranged with an obsessive care for quality. The clock above the entrance has Mr Fortnum and Mr Mason emerging on the hour since 1964, rotating through a brief mechanical minuet before retreating. The tea department alone — 130 varieties, from single-estate Darjeeling to blends formulated for the Royal Household — justifies the visit. The St James\'s Restaurant on the fourth floor serves a properly executed afternoon tea.',
    hours: 'Mon–Sat 10:00–21:00; Sun 11:30–18:00',
    tip: 'The tea department first. The hampers make serious gifts. The fourth-floor restaurant for afternoon tea.',
    type: 'Royal grocer since 1707 — Royal Warrants from King Charles III and Queen Camilla (2024)',
    website: 'https://www.fortnumandmason.com',
  },
  {
    id: 84,
    nbhd: 'westminster',
    name: 'The Ritz',
    cat: 'royal',
    emoji: '🫖',
    address: '150 Piccadilly, London W1J 9BR',
    lat: 51.5066, lng: -0.1435,
    search: 'The Ritz Palm Court afternoon tea interior London',
    note: 'César Ritz opened this in 1906 on the model of a French château transported to Piccadilly — gilded ceilings, mirrored walls, a pink and gold Palm Court, views over Green Park. The Royal Family has used it as a private dining room for over a century. The Queen Mother was a regular until the end of her life. The afternoon tea in the Palm Court — £95 per person, jacket and tie required for gentlemen — is the most famous in the world because it is genuinely the most consistently executed: tiered stands of finger sandwiches and pastries, a trolley of cakes that moves through the room on schedule, and an atmosphere of ceremony that César Ritz built deliberately into every detail of the space. Book months ahead for weekend slots.',
    hours: 'Afternoon tea served five times daily from 11:30; last seating 19:30',
    tip: 'Book months ahead for weekends. Jacket and tie is enforced. The 11:30 seating is the quietest and most unhurried.',
    type: 'The world\'s most famous afternoon tea — Piccadilly (since 1906)',
    website: 'https://www.theritzlondon.com/dine-with-us/afternoon-tea/',
  },
  {
    id: 85,
    nbhd: 'westminster',
    name: 'Claridge\'s',
    cat: 'royal',
    emoji: '🍾',
    address: 'Brook Street, Mayfair, London W1K 4HR',
    lat: 51.5122, lng: -0.1472,
    search: 'Claridges Art Deco interior lobby black white marble staircase',
    note: 'Churchill called Claridge\'s "the annexe to Buckingham Palace," and during the Second World War the metaphor became literal: exiled European royal families — the King of Yugoslavia, the Queen of the Netherlands, the King of Greece — were housed in suites here while their countries were occupied. Churchill himself held court from Suite 212, which he treated as a second office and is now known as the Churchill Suite. The Art Deco interiors, completed in the 1930s, are the finest intact example in any London hotel: the lobby\'s black and white marble floor, the sweeping staircase, the gilded ironwork of the lifts. Every royal family in Europe has stayed here, and the tradition continues. You do not need to be royalty to have tea in the Foyer, a drink in the Fumoir, or dinner in the Mirror Room; you simply need a booking.',
    hours: 'Hotel open 24 hours; Foyer afternoon tea daily 13:00–17:30',
    tip: 'Afternoon tea in the Foyer for the full experience. The Fumoir bar for a pre-dinner drink. Churchill Suite 212 if you want to sleep where wartime history was made.',
    type: 'The Royal Family\'s London hotel — Art Deco Mayfair (since 1812)',
    website: 'https://www.claridges.co.uk',
  },
  {
    id: 86,
    nbhd: 'westminster',
    name: 'Floris',
    cat: 'royal',
    emoji: '🌹',
    address: '89 Jermyn Street, London SW1Y 6JH',
    lat: 51.5060, lng: -0.1367,
    search: 'Floris perfume shop interior mahogany Jermyn Street London',
    note: 'Juan Famenias Floris arrived from Minorca in 1730, set up as a comb-maker and barber on Jermyn Street, and began blending fragrances in the room behind the shop. Nearly 300 years later, the ninth generation of the Floris family runs the business from the same address. They have held a Royal Warrant from every British monarch since George III, and currently hold one from King Charles III. The mahogany showcases inside — designed by the craftsmen who built the display cases for the Great Exhibition of 1851 and acquired directly from the exhibition — have held Floris bottles ever since. The own-blend service allows you to develop a fragrance made to your specification. The bestselling scent, No. 89 — named for the address — was created for the Duke of Edinburgh and has been in continuous production since. Walk in for the room alone.',
    hours: 'Mon–Fri 09:30–18:00; Sat 10:00–17:00; closed Sun',
    tip: 'Ask about the own-blend service if you are serious. No. 89 is the house classic and the correct introduction.',
    type: 'London\'s oldest perfumer (est. 1730) — Royal Warrant since George III',
    website: 'https://www.florislondon.com',
  },
  {
    id: 87,
    nbhd: 'westminster',
    name: 'Lock & Co Hatters',
    cat: 'royal',
    emoji: '🎩',
    address: '6 St James\'s Street, London SW1A 1EF',
    lat: 51.5063, lng: -0.1390,
    search: 'Lock Co Hatters shop interior hats St James London',
    note: 'In 1849 a Norfolk landowner named William Coke walked into Lock & Co and commissioned a hard felt hat that would protect his gamekeepers\' heads from low-hanging branches without the height of a top hat. The hat James Lock designed became known as the bowler — or, in America, the derby — and went on to outfit Charlie Chaplin, Laurel and Hardy, and the entire history of British comedy. Lock & Co has been making hats on this exact St James\'s Street address since 1676, which makes it the oldest hat shop in the world. In 2026 they celebrate 350 continuous years on the same site. Oscar Wilde was a customer. Winston Churchill. The shop holds Royal Warrants from King Charles III and the Prince of Wales. The conformateur — a 19th-century measuring instrument that maps the precise shape of your head — is still used for bespoke orders. Walk in, look at the shelves, and understand why people have been coming here for three and a half centuries.',
    hours: 'Mon–Fri 09:00–17:30; Sat 09:30–17:00; closed Sun',
    tip: 'They will measure your head and advise on the correct shape for your face. Ready-to-wear is available; bespoke takes weeks.',
    type: 'World\'s oldest hat shop (est. 1676) — 350 years on St James\'s Street in 2026',
    website: 'https://www.lockhatters.co.uk',
  },

  // ── SOUTH BANK ────────────────────────────────────────────────────────────

  {
    id: 7,
    nbhd: 'southbank',
    name: 'Tate Modern',
    cat: 'art',
    emoji: '🎨',
    address: 'Bankside, London SE1 9TG',
    lat: 51.5076, lng: -0.0994,
    search: 'Tate Modern Turbine Hall interior installation art',
    note: 'The building is a work before the art begins: a former Bankside power station with a Turbine Hall 35 metres high and 155 metres long, the most ambitious public art space in Britain. The Turbine Hall commissions have defined contemporary art for a generation — Olafur Eliasson\'s artificial sun that turned visitors\' faces to the ceiling; Ai Weiwei\'s floor of 100 million hand-painted porcelain sunflower seeds; Louise Bourgeois\'s steel spider, Maman, her body a cage of marble eggs. The permanent collection runs free from Picasso and the Surrealists through Rothko, Basquiat and artists working now. The Rothko room — eight large dark-field canvases in controlled light, painted specifically to produce the sensation of walls pressing inward — is one of the few places in London where adults stand in complete silence and are visibly moved. Take the lift to the Blavatnik Building terraces at level 10: the finest free view of the Thames in the city, from the dome of St Paul\'s to Canary Wharf.',
    hours: 'Sun–Thu 10:00–18:00; Fri–Sat 10:00–22:00',
    tip: 'The Rothko room first, the Turbine Hall next, then the level 10 terraces. Friday evenings after 18:00 are emptier than any daytime slot and the light on the river is better.',
    type: 'Modern and contemporary art gallery — permanent collection free',
    website: 'https://www.tate.org.uk/visit/tate-modern',
  },
  {
    id: 8,
    nbhd: 'southbank',
    name: 'Shakespeare\'s Globe',
    cat: 'film',
    emoji: '🎬',
    address: '21 New Globe Walk, Bankside, London SE1 9DT',
    lat: 51.5081, lng: -0.0974,
    search: 'Shakespeare\'s Globe Theatre London',
    note: 'Shakespeare in Love (1998) — seven Academy Awards, Best Picture — was built around the story of this theatre\'s construction, and the film\'s climactic performance takes place on a stage modelled precisely on this one. The Globe opened in 1997, a year before the film\'s release, and the two are inseparable in how most people now imagine Shakespeare\'s London. But the building is not a replica built for tourism: it is a working theatre constructed from green English oak and Norfolk reed thatching using the same joinery techniques as the 1599 original, 200 metres from where that building stood. A groundling ticket — the cheapest in the house and placed at stage level in the open yard — is one of the finest evenings available in London: immediate, physical, and performed in the same weather the 1600 audience experienced, because the roof is genuinely open to the sky.',
    hours: 'Tours daily 09:30–17:00. Performances Apr–Oct',
    tip: 'Groundling tickets are inexpensive and the most immediate way to see a performance. Bring a layer — the open roof is literal. Tours on non-performance days are excellent.',
    type: 'Reconstructed Elizabethan theatre — as seen in Shakespeare in Love (1998)',
    website: 'https://www.shakespearesglobe.com',
  },
  {
    id: 9,
    nbhd: 'southbank',
    name: 'Millennium Bridge',
    cat: 'film',
    emoji: '🎬',
    address: 'Millennium Bridge, Bankside, London SE1',
    lat: 51.5098, lng: -0.0983,
    search: 'Millennium Bridge London Thames',
    note: 'Harry Potter and the Half-Blood Prince (2009) opens with Death Eaters sweeping across London and destroying the Millennium Bridge in the film\'s first dramatic minutes — it sways, buckles and collapses into the Thames. The real bridge opened in 2000 and wobbled alarmingly when crowds first walked on it, earning it the nickname "the Wobbly Bridge" before engineers fixed the resonance problem two years later. Norman Foster\'s pedestrian crossing connects St Paul\'s Cathedral directly to Tate Modern. Walk it from the north bank: the dome fills the view ahead, the Thames runs below, and the crossing takes you from medieval cathedral to power-station-turned-gallery in eight minutes. Bridget Jones crossed it. Paddington crossed it. It has been in more films depicting modern London than any other structure of the 21st century.',
    hours: 'Open 24 hours',
    tip: 'Cross from north to south at first light — St Paul\'s ahead, Tate Modern beyond. Continue east along the Southbank to Borough Market. One of London\'s best free mornings.',
    type: 'Norman Foster pedestrian bridge — as seen in Harry Potter and the Half-Blood Prince',
    website: 'https://www.london.gov.uk',
  },
  {
    id: 78,
    nbhd: 'southbank',
    name: 'Newport Street Gallery',
    cat: 'art',
    emoji: '🖼️',
    address: 'Newport Street, London SE11 6AJ',
    lat: 51.4884, lng: -0.1200,
    search: 'Newport Street Gallery interior exhibition London',
    note: 'Damien Hirst opened this gallery in Vauxhall in 2015 to show works from his personal collection — one of the largest privately held contemporary art collections in the world — alongside temporary exhibitions. The building, designed by Caruso St John Architects in a series of converted Victorian theatrical scenery-painting buildings, won the RIBA Stirling Prize for Architecture in 2016: the rare case of a gallery that is itself an architectural award-winner. Entry is always free. The collection ranges from Francis Bacon, Banksy and Jeff Koons to emerging artists Hirst has supported, and the temporary shows are often among the most ambitious single-artist exhibitions in London. The location in Vauxhall, fifteen minutes on foot from Tate Modern across the river, means almost no one finds it accidentally.',
    hours: 'Wed–Sun 10:00–18:00; closed Mon–Tue',
    tip: 'Free entry always. Check the temporary exhibition programme on the website before visiting — the shows change and are not always about Hirst\'s own work.',
    type: 'Damien Hirst\'s private collection gallery — free, Vauxhall (RIBA Stirling Prize 2016)',
    awards: 'RIBA Stirling Prize 2016 — UK\'s Best New Building',
    website: 'https://www.newportstreetgallery.com',
  },

  // ── BOROUGH & BERMONDSEY ──────────────────────────────────────────────────

  {
    id: 11,
    nbhd: 'borough',
    name: 'Borough Market',
    cat: 'shop',
    emoji: '🛒',
    address: '8 Southwark St, London SE1 1TL',
    lat: 51.5055, lng: -0.0908,
    search: 'Borough Market food stalls interior London',
    note: 'A market on this site since the 13th century, under Victorian railway arches since 1851. Come for the traders rather than the atmosphere: over 100 specialists — a cheesemaker who ages Montgomery\'s Cheddar in his own cellar, a fishmonger buying from day-boat skippers on the south coast, a charcutier curing his own salumi in Bermondsey. Buy something from each and eat it walking. The bread at Bread Ahead alone — doughnuts, sourdough, pastries baked through the morning — is worth the early arrival. Thursday mornings before 11:00 are the authentic version: quieter, traders more willing to talk, the quality exactly the same as the weekend. On Saturdays it is shoulder-to-shoulder by noon, which is a different but not necessarily a worse experience.',
    hours: 'Mon–Thu 10:00–17:00; Fri 10:00–18:00; Sat 08:00–17:00; closed Sun',
    tip: 'Thursday morning before 11:00 for the full experience with room to move. On Saturdays: arrive at opening. Ask traders what\'s exceptional today.',
    type: 'London\'s great food market (since the 13th century)',
    website: 'https://boroughmarket.org.uk',
  },
  {
    id: 19,
    nbhd: 'borough',
    name: 'White Cube Gallery',
    cat: 'art',
    emoji: '🖼️',
    address: '144–152 Bermondsey St, London SE1 3TQ',
    lat: 51.5011, lng: -0.0823,
    search: 'White Cube Gallery Bermondsey interior exhibition contemporary art',
    note: 'Walk in and the scale hits you before the art does. White walls, poured concrete floor, daylight controlled from above — a space built specifically to show work that cannot fit anywhere smaller. This is where artists come when they are ready for a room that will either justify the work or expose it. Damien Hirst\'s spot paintings covered every wall simultaneously in 2012. Antony Gormley filled the main hall with cast-iron human forms until the space felt geological. Georg Baselitz hung paintings upside down from a ceiling high enough to make the gesture mean something. The programme changes every few months, runs from quietly devastating to physically overwhelming, and is always free. The current exhibition determines the experience entirely — check the website before you come.',
    hours: 'Tue–Sat 10:00–18:00; Sun 12:00–18:00; closed Mon',
    tip: 'Free, no ticket. The main hall is the reason to come — check what is currently installed. Allow an hour minimum.',
    type: 'Major contemporary art gallery — free, Bermondsey',
    website: 'https://www.whitecube.com',
  },
  {
    id: 22,
    nbhd: 'borough',
    name: 'The Garrison',
    cat: 'pub',
    emoji: '🍺',
    address: '99–101 Bermondsey St, London SE1 3XB',
    lat: 51.5009, lng: -0.0830,
    search: 'The Garrison pub interior Bermondsey London',
    note: 'The gastropub that gave Bermondsey Street its character when it opened in 2003 and has remained the neighbourhood\'s social centre ever since. Bare brick, mismatched vintage furniture, good natural light from a tall front window. The kitchen produces elevated British food without performing the elevation — the kind of cooking where everything is correct without anything drawing attention to itself. The Sunday roast fills months in advance; Saturday breakfast before the market crowd is a reliable start to what will almost certainly be your best day in south London.',
    hours: 'Mon–Thu 08:00–23:00; Fri–Sat 08:00–midnight; Sun 08:00–22:30',
    tip: 'Sunday roast: book months ahead, not weeks. Saturday breakfast before 10:00 is quieter and just as good.',
    type: 'Neighbourhood gastropub — Bermondsey\'s anchor since 2003',
    website: 'https://thegarrison.co.uk',
  },
  {
    id: 60,
    nbhd: 'borough',
    name: 'St John Restaurant',
    cat: 'dining',
    emoji: '🦴',
    address: '26 St John St, Smithfield, London EC1M 4AY',
    lat: 51.5197, lng: -0.1013,
    search: 'St John Restaurant interior Smithfield London food',
    note: 'Fergus Henderson opened St John in a former smokehouse beside Smithfield Market in 1994 and invented a British cuisine. Nose-to-tail cooking — every part of the animal treated with equal precision — sounds like a doctrine but here it is simply a menu. The bone marrow and parsley salad on sourdough toast is one of the most consequential dishes in British food history: a single roasted marrow bone halved and set on toast with flat-leaf parsley dressed in capers and lemon, and nothing else. White walls, no music, no decoration, no performance. The food does the work entirely. Book ahead. Order the eccles cake with Lancashire cheese to finish.',
    hours: 'Mon–Fri 12:00–15:00, 18:00–22:00; Sat 12:00–15:00, 18:00–22:00',
    tip: 'The bone marrow toast is non-negotiable. Eccles cake and Lancashire cheese to finish. Book ahead.',
    type: 'The original nose-to-tail British restaurant (since 1994)',
    awards: '⭐ One Michelin Star · Condé Nast Traveller Lifetime Achievement (Fergus Henderson, 2024)',
    website: 'https://stjohnrestaurant.com',
  },
  {
    id: 81,
    nbhd: 'borough',
    name: 'Bermondsey Antique Market',
    cat: 'shop',
    emoji: '🫙',
    address: 'Long Lane, Bermondsey, London SE1 4QB',
    lat: 51.4982, lng: -0.0813,
    search: 'Bermondsey antique market stalls dealers London',
    note: 'The most serious antique market in London operates on Friday mornings on Long Lane in Bermondsey, and if you arrive after 08:00 the best pieces are already gone. Dealers who set up from 06:00 are largely professionals buying from other professionals: silver, porcelain, furniture, jewellery, maps, prints, glass. The knowledge in the market is genuine — many of these traders also supply auction houses and dealers in Mayfair. Come with cash and a specific idea of what you are looking for; or come with no idea at all and spend two hours developing one. The market winds down by noon and disappears by 14:00 as completely as if it never happened.',
    hours: 'Fridays only, 06:00–14:00',
    tip: 'Arrive by 07:30. Cash preferred. The silver and jewellery section has the most serious dealers. Nothing survives until the afternoon.',
    type: 'London\'s oldest antique market — Friday mornings only, SE1',
    website: 'https://www.bermondseysquare.co.uk',
  },

  // ── THE CITY ──────────────────────────────────────────────────────────────

  {
    id: 23,
    nbhd: 'city',
    name: 'Tower Bridge',
    cat: 'film',
    emoji: '🎬',
    address: 'Tower Bridge Rd, London SE1 2UP',
    lat: 51.5055, lng: -0.0754,
    search: 'Tower Bridge London',
    note: 'James Bond raced a speedboat beneath it in The World Is Not Enough (1999). The Dark Knight Rises. Mission: Impossible — Rogue Nation. Tower Bridge appears in more action films than any other London landmark because it photographs as a symbol rather than simply a building — the Victorian Gothic towers, the raised bascules, the suspended walkways all register as London itself, instantly and globally. The reality is more interesting than any frame: the bridge was built between 1886 and 1894, clad in Cornish granite and Portland stone at the City of London\'s insistence because an industrial structure at this location was considered unacceptable. It still raises for river traffic around 800 times a year. The paid attraction includes glass-floored high walkways 42 metres above the water and the Victorian engine rooms below, where the original hydraulic machinery is preserved entirely intact.',
    hours: 'Daily 09:30–17:30',
    tip: 'Check lift times on the website the day before — free to watch from the riverbank. The Victorian engine rooms are the underrated half of the paid ticket.',
    type: 'Victorian bascule bridge (1894) — London\'s most filmed landmark',
    website: 'https://www.towerbridge.org.uk',
  },
  {
    id: 24,
    nbhd: 'city',
    name: 'Tower of London',
    cat: 'royal',
    emoji: '👑',
    address: 'St Katharine\'s & Wapping, London EC3N 4AB',
    lat: 51.5081, lng: -0.0760,
    search: 'Tower of London Crown Jewels interior',
    note: 'Almost a thousand years of continuous royal use on the same half-mile of riverbank. William the Conqueror began it in 1078 as a demonstration of power to the city he had just conquered; every subsequent monarch added to it, used it, imprisoned in it or was imprisoned in it. The Crown Jewels are here — including the Imperial State Crown set with the Black Prince\'s Ruby, worn by Henry V at Agincourt — guarded under conditions of security that have not been tested since Colonel Blood stole the orb in 1671 and was pardoned by Charles II for the audacity of the attempt. The Yeoman Warders have guarded the Tower since 1485 and live within the walls with their families. Join a Yeoman Warder tour the moment you arrive — the stories do not appear in any guidebook. The Ceremony of the Keys has locked the Tower at 21:53 every night since the 14th century. Free to attend but requiring a booking months in advance.',
    hours: 'Tue–Sat 09:00–17:30; Sun–Mon 10:00–17:30',
    tip: 'Join a Yeoman Warder tour the moment you arrive. Book the Ceremony of the Keys months ahead. The Scaffold Site and Traitors\' Gate, not only the Jewel House.',
    type: 'Royal fortress and UNESCO World Heritage Site — nearly 1,000 years of royal history',
    website: 'https://www.hrp.org.uk/tower-of-london',
  },
  {
    id: 26,
    nbhd: 'city',
    name: 'Leadenhall Market',
    cat: 'film',
    emoji: '🎬',
    address: 'Gracechurch St, London EC3V 1LT',
    lat: 51.5135, lng: -0.0831,
    search: 'Leadenhall Market interior Victorian London ornate',
    note: 'Harry Potter and the Philosopher\'s Stone (2001): the entrance to the Leaky Cauldron — the hidden pub through which Harry enters Diagon Alley for the first time — was filmed at the optician\'s shop at 3 Bull\'s Head Passage inside Leadenhall Market. Stand at that corner and look at the painted ornamental ironwork in burgundy, green and cream, and understand why the production chose it: the market already looks like a fantasy. It was built in 1881 on a site with a market since the 14th century. On weekday mornings, suited financiers press through the amber light and the 19th century feels closer than usual. At weekends the market is almost entirely empty — a different but worthwhile version of the same space.',
    hours: 'Mon–Fri 10:00–18:00; largely empty at weekends',
    tip: 'Find 3 Bull\'s Head Passage for the Harry Potter connection. Weekday mornings for the authentic working atmosphere. Completely empty at weekends.',
    type: 'Ornate Victorian covered market (1881) — Harry Potter\'s Diagon Alley entrance',
    website: 'https://leadenhallmarket.co.uk',
  },
  {
    id: 27,
    nbhd: 'city',
    name: 'Duck and Waffle',
    cat: 'dining',
    emoji: '🧇',
    address: '110 Bishopsgate, London EC2N 4AY',
    lat: 51.5142, lng: -0.0820,
    search: 'Duck Waffle restaurant interior rooftop London City view',
    note: 'Open 24 hours on the 40th floor of Heron Tower, floor-to-ceiling windows and the full sweep of the City and Thames below. The signature — confit duck leg on a Belgian waffle with a fried duck egg and mustard maple syrup — sounds improbable and tastes inevitable. A sunrise booking at 06:30 is one of London\'s most dramatically staged breakfasts: the city waking below you, the room quieter than at any other hour, the light hitting the Thames at a low angle that makes the whole basin look liquid gold. This is the only 24-hour restaurant in London at height, and the sunrise slot is the correct way to use it.',
    hours: 'Open 24/7',
    tip: 'Book a sunrise slot weeks ahead — 06:30 means a quiet room and extraordinary light. The duck and waffle is non-negotiable.',
    type: 'London\'s only 24-hour high-rise restaurant — 40th floor City views',
    website: 'https://duckandwaffle.com',
  },
  {
    id: 28,
    nbhd: 'city',
    name: 'St Paul\'s Cathedral',
    cat: 'film',
    emoji: '🎬',
    address: 'St. Paul\'s Churchyard, London EC4M 8AD',
    lat: 51.5138, lng: -0.0984,
    search: 'St Paul\'s Cathedral interior dome Whispering Gallery London',
    note: 'The old woman on the cathedral steps sells birdseed for a tuppence a bag in Mary Poppins (1964) — that image, the steps of St Paul\'s, the dome behind her, is one of the most reproduced in British cinema. The Darkest Hour (2017), Doctor Strange (2016), The Da Vinci Code (2006) — the dome appears in so many films depicting London under threat or at its finest that Herbert Mason\'s 1940 photograph of the cathedral standing unharmed in the smoke of the Blitz became one of the defining images of the 20th century. The building Wren spent 35 years designing — he is buried in the crypt beneath it, the epitaph on the floor reading Lector, si monumentum requiris, circumspice — is worth the 528-step climb for the view alone. The Whispering Gallery inside the dome, 34 metres across, carries a whisper from one curved wall to the other in a phenomenon you have to test yourself to believe.',
    hours: 'Mon–Sat 08:30–16:30',
    tip: 'The Whispering Gallery first. Go early on a weekday for the climb without crowds. The crypt is underrated: Wellington and Nelson are both buried there.',
    type: 'Wren\'s masterpiece (1710) — as seen in Mary Poppins, Darkest Hour, and countless others',
    website: 'https://www.stpauls.co.uk',
  },
  {
    id: 62,
    nbhd: 'city',
    name: 'The Barbican',
    cat: 'art',
    emoji: '🏗️',
    address: 'Silk Street, Barbican, London EC2Y 8DS',
    lat: 51.5203, lng: -0.0928,
    search: 'Barbican Centre interior arts London concert hall gallery',
    note: 'Built on a Blitz bomb site and completed in the 1970s, the Barbican is the largest brutalist complex in Europe — three residential towers, 2,000 flats, two theatres, a concert hall, two cinemas, a gallery and an arts centre, all connected by a raised pedestrian walkway above the street. The architecture is deliberately disorienting: the walkways do not go where you expect, the courtyards open unexpectedly onto water, the lakeside terrace appears when you have given up looking for it. The arts programme is among the best in London: the resident London Symphony Orchestra is one of the finest in Europe; the gallery shows serious contemporary and design exhibitions; the cinema runs properly curated retrospectives. The glass conservatory — a tropical garden growing inside the City of London, free on Sundays — is one of the most genuinely strange and beautiful spaces in the square mile.',
    hours: 'Public walkways from 06:00; arts centre from 11:00',
    tip: 'Go without a plan and follow the walkways. The conservatory is free on Sundays and worth the trip on its own. Check the arts centre programme before visiting.',
    type: 'Brutalist arts complex — LSO, gallery, theatre, cinema (free to explore)',
    website: 'https://www.barbican.org.uk',
  },

  // ── COVENT GARDEN & SOHO ──────────────────────────────────────────────────

  {
    id: 75,
    nbhd: 'covent-garden',
    name: 'American Bar at The Savoy',
    cat: 'pub',
    emoji: '🥂',
    address: 'The Savoy, Strand, London WC2R 0EU',
    lat: 51.5104, lng: -0.1203,
    search: 'American Bar Savoy interior Art Deco cocktail London',
    note: 'The most historically significant drinking room in London. Harry Craddock wrote the Savoy Cocktail Book here in 1930 — a volume that defined the modern cocktail for a century. The Hanky Panky was invented here in 1925 by Ada Coleman, one of the first female head bartenders in London history. The Art Deco interior completed in 1927 is largely intact: the low ceiling, the piano corner, the amber light that made everything that happened in this room look like a story worth telling. The Corpse Reviver #2, from Craddock\'s original recipe, is the correct order. The piano starts at 19:30 and the service maintains standards that most contemporary cocktail bars treat as aspirational.',
    hours: 'Mon–Sat 14:00–00:00; Sun 14:00–23:00',
    tip: 'The Corpse Reviver #2 from the original Craddock recipe. Book ahead for weekends. The piano begins at 19:30.',
    type: 'Historic hotel bar — the birthplace of modern cocktail culture (1893)',
    website: 'https://www.thesavoylondon.com/restaurant/american-bar/',
  },
  {
    id: 29,
    nbhd: 'covent-garden',
    name: 'Covent Garden',
    cat: 'film',
    emoji: '🎬',
    address: 'Covent Garden, London WC2E 8RF',
    lat: 51.5117, lng: -0.1232,
    search: 'Covent Garden London',
    note: 'Audrey Hepburn sold flowers as Eliza Doolittle on these piazza steps in My Fair Lady (1964). The cobblestones appear in Oliver! (1968), in Paddington (2014), in Bridget Jones, in countless British period dramas that need a setting that reads immediately as old London. The market was saved from demolition in 1974 by one of the first successful community preservation campaigns in Britain, converting the Victorian trading floor into the covered market you walk through today. The piazza is the tourists\' London; the streets around it hold more. Cecil Court — a pedestrianised Edwardian alley of antiquarian booksellers, print dealers and map specialists one block west — has barely changed since the 1920s. Neal\'s Yard, through the alley off Short\'s Gardens, holds the finest British farmhouse cheese shop in the world.',
    hours: 'Piazza 24h; shops Mon–Sat 10:00–20:00; Sun 11:00–18:00',
    tip: 'Cecil Court for maps and prints. Neal\'s Yard for cheese. Seven Dials for independent shopping. The piazza is a starting point, not the destination.',
    type: 'Historic market piazza — as seen in My Fair Lady, Oliver!, Paddington, and others',
    website: 'https://www.coventgarden.london',
  },
  {
    id: 30,
    nbhd: 'covent-garden',
    name: 'Neal\'s Yard',
    cat: 'shop',
    emoji: '🌈',
    address: 'Neal\'s Yard, Covent Garden, London WC2H 9DP',
    lat: 51.5128, lng: -0.1262,
    search: 'Neal\'s Yard Dairy cheese shop interior London',
    note: 'A tiny courtyard accessible only through narrow alleys off Neal Street — buildings painted in clashing vivid colours around a central fountain, invisible from any main road. Neal\'s Yard Dairy occupies the corner and is the finest British farmhouse cheese shop in the world. They source whole wheels, age them in their Bermondsey cellar, and maintain direct relationships with the farms: Montgomery\'s Cheddar, Stichelton (unpasteurised Stilton), Hafod Welsh organic cheddar, Kirkham\'s Lancashire. The staff know the current condition of every wheel and will tell you exactly what is at its peak today. Buy more than you think you need.',
    hours: 'Mon–Sat 10:00–18:30; Sun 11:00–17:00',
    tip: 'Enter from Shorts Gardens or Neal Street. Ask what\'s at peak condition today and follow the answer entirely.',
    type: 'Hidden courtyard with the world\'s finest British farmhouse cheese shop',
    website: 'https://www.nealsyarddairy.co.uk',
  },
  {
    id: 31,
    nbhd: 'covent-garden',
    name: 'Clos Maggiore',
    cat: 'dining',
    emoji: '🌸',
    address: '33 King St, Covent Garden, London WC2E 8JD',
    lat: 51.5118, lng: -0.1243,
    search: 'Clos Maggiore conservatory interior blossom Covent Garden London',
    note: 'The conservatory is the reason to come, and you should say so clearly when you book. Twelve covers under a retractable glass roof with cherry blossom branches trailing overhead, candles on every table, the branches close enough to touch on warm evenings when the roof slides back. It is the most romantic dining room in London by the consistent verdict of everyone who eats there and does not stop talking about it afterward. The French cooking is serious — precisely sourced, technically disciplined — and earns its setting rather than hiding behind it. The set lunch on a weekday delivers the same kitchen at half the dinner price in a room that is quieter and, if anything, more beautiful in afternoon light. Book the conservatory table specifically, weeks ahead for weekends.',
    hours: 'Mon–Sat 12:00–14:30, 17:00–23:00; Sun 12:00–15:30, 17:00–22:00',
    tip: 'Specify the conservatory when booking — the dining room is good but not the point. Set lunch on a Tuesday or Wednesday for the quietest version of this room.',
    type: 'French restaurant — London\'s most romantic dining room',
    awards: '3 AA Rosettes (2026) · Wine Spectator Grand Award (2025) · \'Most Romantic Restaurant in the World\' — Architectural Digest',
    website: 'https://www.closmaggiore.com',
  },
  {
    id: 32,
    nbhd: 'covent-garden',
    name: 'Barrafina',
    cat: 'dining',
    emoji: '🦐',
    address: '10 Adelaide St, London WC2N 4HZ',
    lat: 51.5097, lng: -0.1239,
    search: 'Barrafina tapas counter interior London food',
    note: 'Counter seating only, no reservations, kitchen entirely open. Barrafina has been the benchmark for Spanish cooking in London since 2007 — the tortilla, the grilled fish, the cuttlefish in its own ink, the jamón carved from the leg hanging above the counter. The chefs know what is exceptional today and will tell you if you ask. Walk in, wait for a counter seat to open, and eat at it. The Adelaide Street branch is the original and still the best: the counter has the right angle to the kitchen, and the room has not changed since it opened. It held a Michelin star for over a decade — the cooking that earned it has not changed.',
    hours: 'Mon–Sat 12:00–15:00, 17:00–23:00; Sun 13:00–15:30, 17:00–22:00',
    tip: 'Walk-in only. Arrive before opening or accept the wait. Ask the chefs what they recommend today — the answer changes.',
    type: 'The benchmark for Spanish tapas in London — counter seats only, walk-in',
    website: 'https://barrafina.co.uk',
  },
  {
    id: 33,
    nbhd: 'covent-garden',
    name: 'Mr Fogg\'s Gin Parlour',
    cat: 'pub',
    emoji: '🌏',
    address: '1 New Row, London WC2N 4EA',
    lat: 51.5110, lng: -0.1241,
    search: 'Mr Fogg\'s Gin Parlour bar interior Covent Garden',
    note: 'Down a staircase off New Row into a Victorian basement dressed as the private study of Phileas Fogg, hero of Around the World in Eighty Days: taxidermy, globes, butterfly specimens in cases, shelves of leather-bound books, trunks and instruments covering every surface. The inventory is over 300 gins organised by region and distillery, and the bartenders know it the way a good sommelier knows a cellar — ask what you are in the mood for and they will bring you something you would not have chosen yourself. The room holds perhaps 40 people and feels full at 20, which means it always has atmosphere and always requires a booking.',
    hours: 'Mon–Thu 15:00–midnight; Fri–Sat 12:00–01:00; Sun 12:00–midnight',
    tip: 'Book ahead — the room is small. Ask for recommendations from lesser-known distilleries. The bartenders have strong opinions.',
    type: 'Victorian gin parlour — 300+ gins, Around the World in 80 Days theme',
    website: 'https://mr-foggs.com/gin-parlour',
  },
  {
    id: 35,
    nbhd: 'covent-garden',
    name: 'Ronnie Scott\'s Jazz Club',
    cat: 'music',
    emoji: '🎷',
    address: '47 Frith St, Soho, London W1D 4HT',
    lat: 51.5133, lng: -0.1314,
    search: 'Ronnie Scott\'s jazz club stage interior London',
    note: 'Ronnie Scott opened this basement on Frith Street in 1959 with £100 borrowed from a friend. Miles Davis played here. Nina Simone called it a second home. Jimi Hendrix gave his last ever public performance on this stage, ten days before he died. The room holds 250 and feels intimate regardless of who is on — the rectangular space and low ceiling work like a listening room, the sound collecting rather than dispersing. The late-night sessions that begin around 23:30 after the headline act are sometimes better than the show that preceded them: more spontaneous, cheaper, and the kind of thing you cannot plan for.',
    hours: 'Mon–Sat 18:00–03:00; Sun 18:00–midnight',
    tip: 'Book headline acts weeks ahead. The late session starts around 23:30 — cheaper, more spontaneous, occasionally unforgettable.',
    type: 'World-famous jazz club (since 1959) — Jimi Hendrix\'s last public performance',
    website: 'https://www.ronniescotts.co.uk',
  },
  {
    id: 37,
    nbhd: 'covent-garden',
    name: 'Opium Cocktail Bar',
    cat: 'pub',
    emoji: '🏮',
    address: '15–16 Gerrard St, London W1D 6JE',
    lat: 51.5119, lng: -0.1306,
    search: 'Opium cocktail bar red lanterns interior Chinatown London',
    note: 'The door is on Gerrard Street in the middle of Chinatown, unmarked except for a small brass plate. Ring the bell, climb four flights past red silk lanterns and dark lacquered timber, and arrive in a bar that the 1920s Shanghai of imagination would have looked like. Three floors, low lighting, the smell of gardenia and warm spirits. The cocktails draw on Japanese whisky, Taiwanese gin, Chinese baijiu and Korean makgeolli in combinations that read as improbable on the menu and resolve completely in the glass. On weekends a performer takes the upper level — a Peking opera singer, a close-up magician, a jazz duo — and the evenings acquire a quality that nothing else in central London replicates.',
    hours: 'Mon–Tue 17:00–01:00; Wed–Thu 17:00–02:00; Fri–Sat 17:00–03:00; Sun 17:00–midnight',
    tip: 'Book ahead for weekends. Ask what spirit the bar manager is currently obsessed with — the answer changes and is always interesting.',
    type: '1920s Shanghai cocktail bar above Chinatown',
    website: 'https://www.opiumchinatown.com',
  },
  {
    id: 38,
    nbhd: 'covent-garden',
    name: 'Bob Bob Ricard',
    cat: 'dining',
    emoji: '🍾',
    address: '1 Upper James St, Soho, London W1F 9DF',
    lat: 51.5124, lng: -0.1389,
    search: 'Bob Bob Ricard restaurant booth interior Soho London',
    note: 'A Soho brasserie built around one brilliant conceit: a Press for Champagne button at every leather booth, connected directly to the bar. The room — lacquered blue and gold, mirrored ceilings, all the glamour of a private railway carriage — is exactly as theatrical as that button implies. The food is a serious brasserie menu of British and Russian classics: beef Wellington, lobster thermidor, chicken Kiev made correctly with the butter sealed inside. Press the button. Order the beef Wellington. That is the correct evening, and it has been the correct evening since the restaurant opened in 2008.',
    hours: 'Daily 12:30–15:00, 18:00–23:30',
    tip: 'Book ahead. The beef Wellington is the kitchen\'s signature. Budget from £70 per person with something pressed for.',
    type: 'Theatrical brasserie with champagne button at every table',
    website: 'https://bobbobricard.com',
  },
  {
    id: 72,
    nbhd: 'covent-garden',
    name: 'Rules',
    cat: 'dining',
    emoji: '🍮',
    address: '35 Maiden Lane, Covent Garden, London WC2E 7LB',
    lat: 51.5115, lng: -0.1237,
    search: 'Rules restaurant interior dining room Covent Garden London',
    note: 'Established in 1798 on Maiden Lane and still on the same site — London\'s oldest restaurant, which means the room has been serving dinner since before Waterloo, before the railways, before photography. The walls are layered with theatrical portraits, cartoons and accumulated objects from 225 years of continuous trade. Dickens was a regular. Graham Greene wrote here. King Edward VII brought Lillie Langtry to the private upstairs room he rented for the purpose. The menu is British game and traditional dishes executed with a confidence that comes from being right about them for over two centuries: potted shrimps, roast grouse in season from the restaurant\'s own Teesdale estate, suet puddings of the kind that have not survived anywhere else.',
    hours: 'Mon–Sat 12:00–23:30; Sun 12:00–22:30',
    tip: 'Order game — it is what this kitchen has done for 225 years. Potted shrimps to start, a suet pudding to finish. Book ahead for weekends.',
    type: 'London\'s oldest restaurant (established 1798)',
    website: 'https://rules.co.uk',
  },
  {
    id: 69,
    nbhd: 'covent-garden',
    name: 'The Palomar',
    cat: 'dining',
    emoji: '🫙',
    address: '34 Rupert St, Soho, London W1D 6DN',
    lat: 51.5121, lng: -0.1326,
    search: 'The Palomar hummus Jerusalem restaurant London',
    note: 'The cooking draws on Jerusalem and the whole Eastern Mediterranean — the spice routes, the Ottoman inheritance, the Levantine coast — and at its best it is some of the most interesting food in London. The Jerusalem-style hummus arrives warm and silky with a pool of cold-pressed olive oil and a handful of spiced chickpeas; it is one of the finest plates in the city and costs under £10. The lamb neck is slow-cooked until it pulls apart under a fork, layered with burned yogurt and sweet charred onion. Counter seats at the open kitchen pass are where the room comes alive — the chefs explain every dish as it arrives, the kitchen runs at full speed, and the energy concentrates at those seats in a way the dining room behind cannot match. Book ahead for the dining room; try the counter walk-in at lunch.',
    hours: 'Mon–Sat 12:00–14:30, 17:30–22:30; Sun 12:00–15:30',
    tip: 'Counter seats at the pass if available. The hummus first, then the lamb neck. Ask what raw fish is on today.',
    type: 'Jerusalem and Eastern Mediterranean restaurant',
    awards: 'Michelin Bib Gourmand 2026',
    website: 'https://www.thepalomar.co.uk',
  },
  {
    id: 68,
    nbhd: 'covent-garden',
    name: 'The French House',
    cat: 'pub',
    emoji: '🥂',
    address: '49 Dean St, Soho, London W1D 5BG',
    lat: 51.5130, lng: -0.1330,
    search: 'French House Soho pub bar interior Dean Street',
    note: 'The most historically layered drinking room in Soho. De Gaulle used this as the informal London headquarters of the Free French during the Second World War — Resistance fighters, exiles and refugees drank here while London burned. After the war: Dylan Thomas, Francis Bacon, Lucian Freud. The house rules have not changed: wine and spirits only, and — uniquely in London — no pints, only halves. The room is small, crowded and exactly right. Upstairs, a restaurant runs one of the more interesting lunch menus in Soho. The building is a living memory of a city that harboured everyone it needed to.',
    hours: 'Mon–Sat 12:00–23:00; Sun 12:00–22:30',
    tip: 'The half-pint rule means order wine. Book the restaurant upstairs for lunch. Arrive before 19:00 for space at the bar.',
    type: 'Soho institution — the Free French HQ in WWII (est. 1891)',
    website: 'https://frenchhousesoho.com',
  },
  {
    id: 79,
    nbhd: 'covent-garden',
    name: 'Dover Street Market',
    cat: 'shop',
    emoji: '🛍️',
    address: '18–22 Haymarket, London SW1Y 4DQ',
    lat: 51.5073, lng: -0.1323,
    search: 'Dover Street Market Comme des Garcons fashion interior London',
    note: 'Rei Kawakubo of Comme des Garçons opened the original Dover Street Market in 2004 and moved it to this six-floor building on Haymarket in 2016. The concept is what she designed it to be: not a boutique and not a department store but something closer to a curated art installation that happens to sell clothes. Each floor is redesigned periodically by different creatives; the spaces change character without warning. The edit is Kawakubo\'s: Comme des Garçons in every line, Balenciaga, Gucci, Thom Browne, Y/Project, Simone Rocha, and a selection of emerging labels not available in the same room anywhere else in London. The Rose Bakery café at the top of the building is the correct place to pause.',
    hours: 'Mon–Sat 11:00–19:00; Sun 12:00–18:00',
    tip: 'Walk every floor — the edit on each is different. The Rose Bakery at the top for the break. Nothing here is cheap; most of it is not available anywhere else.',
    type: 'Rei Kawakubo\'s radical concept store — Haymarket (originally Dover Street)',
    website: 'https://london.doverstreetmarket.com',
  },
  {
    id: 80,
    nbhd: 'covent-garden',
    name: 'Liberty London',
    cat: 'shop',
    emoji: '🏰',
    address: 'Regent Street, London W1B 5AH',
    lat: 51.5138, lng: -0.1402,
    search: 'Liberty London Tudor interior atrium galleried floors',
    note: 'Arthur Lasenby Liberty opened his first shop in 1875 selling Japanese and Oriental goods on Regent Street, and the Art Nouveau and Japanese aesthetic movements in Britain ran largely through his taste. The current Tudor Revival building — completed in 1924, constructed from the timbers of two decommissioned Royal Navy warships, HMS Hindustan and HMS Impregnable — is the most beautiful department store in the world and one of the only independently owned ones still operating in London. The Liberty print fabrics, in the distinctive small-scale florals produced since the 1870s, are sold by the metre in the haberdashery department. The rest of the building holds beauty, accessories, homeware, fashion and art presented with a curatorial intelligence that chain stores cannot replicate. Walk every floor.',
    hours: 'Mon–Sat 10:00–20:00; Sun 12:00–18:00',
    tip: 'Walk every floor. The Tudor interior — exposed beams, galleried atria — is as much the reason to come as anything for sale.',
    type: 'The world\'s most beautiful department store (est. 1875)',
    website: 'https://www.libertylondon.com',
  },

  // ── CAMDEN & KING\'S CROSS ─────────────────────────────────────────────────

  {
    id: 67,
    nbhd: 'camden',
    name: 'Coal Drops Yard',
    cat: 'shop',
    emoji: '🏗️',
    address: 'Stable St, King\'s Cross, London N1C 4AB',
    lat: 51.5357, lng: -0.1238,
    search: 'Coal Drops Yard interior architecture King\'s Cross London',
    note: 'Two Victorian coal drops from the 1850s, where barges unloaded coal into storage yards above the railway. Thomas Heatherwick converted them in 2018, arching the two Victorian iron roofs toward each other until they meet and touch at the apex — an engineering gesture that creates an outdoor retail destination unlike anything else in London. The independent edit is the best in King\'s Cross: Paul Smith, Tom Dixon, Wolf & Badger, Aesop, smaller boutiques with considered selections. Cross the canal from Granary Square and find it behind the fountains. Walk through at dusk when the roofline is lit and the iron turns warm. The architecture is always the reason to come first; what is inside is the reason to stay.',
    hours: 'Shops Mon–Sat 10:00–20:00; Sun 11:00–18:00; restaurants vary',
    tip: 'Walk through at dusk when the roofline is lit. The architecture is the point — the shops are the bonus.',
    type: 'Heatherwick-designed Victorian coal drops — independent boutiques, King\'s Cross',
    website: 'https://coaldropsyard.com',
  },
  {
    id: 40,
    nbhd: 'camden',
    name: 'Wellcome Collection',
    cat: 'art',
    emoji: '🔬',
    address: '183 Euston Rd, London NW1 2BE',
    lat: 51.5258, lng: -0.1320,
    search: 'Wellcome Collection museum interior Henry Wellcome objects',
    note: 'Sir Henry Wellcome was a pharmaceutical millionaire who spent his fortune acquiring objects at the intersection of medicine, science, death and human experience. The permanent collection is unlike anything else in London: Napoleon\'s toothbrush, Darwin\'s walking stick, a 2,000-year-old Egyptian mummy\'s hair, Roman surgical instruments that still look functional, a 15th-century Italian ivory anatomical figure, Victorian electroshock equipment, a complete 18th-century apothecary\'s dispensary. They are displayed without hierarchy or sentimentality — a medieval chastity belt beside contemporary HIV medication, both treated as equally serious objects. The museum\'s refusal to arrange human experience into comfortable categories gives it a quality most institutions cannot manufacture. The temporary exhibitions are consistently the most rigorously conceived in London. Free, chronically undervisited, and two hours is genuinely not enough.',
    hours: 'Tue–Wed, Fri–Sat 10:00–18:00; Thu 10:00–20:00; Sun 11:00–18:00; closed Mon',
    tip: 'Free always. Thursday evenings for the quietest visit. Allow three hours. Follow whatever holds your attention.',
    type: 'Free museum at the intersection of medicine, science and art',
    website: 'https://wellcomecollection.org',
  },

  // ── NOTTING HILL ──────────────────────────────────────────────────────────

  {
    id: 43,
    nbhd: 'notting-hill',
    name: 'Portobello Road Market',
    cat: 'shop',
    emoji: '🎨',
    address: 'Portobello Rd, Notting Hill, London W11',
    lat: 51.5163, lng: -0.2033,
    search: 'Portobello Road antique market stalls Notting Hill',
    note: 'Over a mile of stalls through Notting Hill. On Saturdays, over 1,000 antique dealers occupy the southern section — the world\'s largest antique street market by dealer count. Victorian silver, Art Deco jewellery, Georgian furniture, vintage watches, maps, prints, curiosities of every description. The middle section runs fruit, vegetables and street food through the week. The northern end under the Westway flyover has the best vintage clothing with half the Saturday crowds. The surrounding pastel-painted terraces are what separate Portobello from every other London market neighbourhood — the shopping is the pretext for the walk.',
    hours: 'Antiques: Sat 08:00–19:00; General market: Mon–Fri 09:00–18:00',
    tip: 'Arrive before 09:00 on Saturdays for antiques. The northern end under the Westway has the best vintage with far fewer people.',
    type: 'World\'s largest antique street market — Saturdays, Notting Hill',
    website: 'https://www.portobelloroad.co.uk',
    direct_image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Portobello_Road_Market_in_London,_spring_2013_(4).JPG',
  },
  {
    id: 44,
    nbhd: 'notting-hill',
    name: 'Core by Clare Smyth',
    cat: 'dining',
    emoji: '⭐',
    address: '92 Kensington Park Rd, London W11 2PN',
    lat: 51.5176, lng: -0.2007,
    search: 'Clare Smyth potato roe dish fine dining',
    note: 'Clare Smyth was the first woman to hold three Michelin stars in her own name in the UK, earned at Restaurant Gordon Ramsay before she opened Core in 2017. The cooking is built on British produce treated with the rigour of classical French technique. The signature potato and roe dish — a single perfect potato slow-cooked in beef fat until the skin lacquers, topped with herring roe and coastal herbs — is simultaneously the simplest and the most technically accomplished thing on the menu. The full tasting menu runs fourteen courses and takes the better part of three hours. The set lunch at £75 delivers the same kitchen, the same sourcing and the same level of care at considerably lower cost — one of the best-value serious lunches in London. Book weeks ahead.',
    hours: 'Tue–Sat 12:00–14:00, 18:30–22:00; closed Sun–Mon',
    tip: 'The set lunch is the right entry point — same kitchen, half the tasting menu price. Book weeks ahead. The wine pairings are serious.',
    type: 'Three Michelin-star restaurant — Notting Hill',
    awards: '⭐⭐⭐ Three Michelin Stars · 5 AA Rosettes · La Liste 98/100 (2025)',
    website: 'https://corebyclaresmyth.com',
  },
  {
    id: 47,
    nbhd: 'notting-hill',
    name: 'Electric Cinema',
    cat: 'film',
    emoji: '🎬',
    address: '191 Portobello Rd, Notting Hill, London W11 2ED',
    lat: 51.5161, lng: -0.2007,
    search: 'Electric Cinema Notting Hill interior leather armchairs',
    note: 'Julia Roberts and Hugh Grant went to the cinema in Notting Hill (1999), and it was this cinema. The Electric has been on Portobello Road since 1910, making it one of the oldest working cinemas in Britain, and the film chose it because leather armchairs, footstools, sofas and full bar service already made it unlike anywhere else in London. The double sofa seats at the front exist precisely for what you are thinking. The Edwardian building retains enough of its original character that an evening here is an occasion rather than simply a showing. The programme runs art house and mainstream releases with equal conviction. Book sofa seats for anything you particularly want to see; they sell out.',
    hours: 'Shows daily from approximately 12:00',
    tip: 'Book the double sofa seats for anything special — they sell out. Bar service runs throughout the show.',
    type: 'Luxury independent cinema (opened 1910) — as seen in Notting Hill (1999)',
    website: 'https://www.electriccinema.co.uk',
  },

  // ── KENSINGTON ────────────────────────────────────────────────────────────

  {
    id: 49,
    nbhd: 'kensington',
    name: 'Victoria & Albert Museum',
    cat: 'art',
    emoji: '🏺',
    address: 'Cromwell Rd, Kensington, London SW7 2RL',
    lat: 51.4966, lng: -0.1722,
    search: 'Victoria Albert Museum Cast Courts Trajan Column interior',
    note: 'The world\'s greatest museum of art and design: 2.3 million objects, 145 galleries, 5,000 years of human creative output from Japanese armour to Raphael cartoons to the wedding dress Vivienne Westwood wore in 1992. The Cast Courts on Level 1 are two Victorian halls containing plaster casts of Trajan\'s Column — split in two because the real thing is 38 metres tall — Michelangelo\'s David and every other major European monument. The ambition and scale of the Victorian project is its own kind of art. The Medieval and Renaissance Galleries run from Byzantine ivories to Holbein miniatures. The Fashion Gallery holds four centuries of dress. The design collections span Islamic tiles, Chinese ceramics, Renaissance bronzes and 20th-century industrial design in rooms that connect unexpectedly. Friday evenings after 18:00: emptier, atmospheric, often with live music in the courtyard. Free.',
    hours: 'Daily 10:00–17:45; Fri until 22:00',
    tip: 'Friday evenings after 18:00 — emptier and more atmospheric. The Cast Courts first, then follow wherever the building takes you. Two full visits is not too many.',
    type: 'World\'s greatest art and design museum (free)',
    website: 'https://www.vam.ac.uk',
    direct_image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Weston_Cast_Court_in_the_Victoria_and_Albert_Museum.JPG',
  },
  {
    id: 52,
    nbhd: 'kensington',
    name: 'The Harwood Arms',
    cat: 'dining',
    emoji: '🥩',
    address: 'Walham Grove, Fulham, London SW6 1QP',
    lat: 51.4787, lng: -0.1946,
    search: 'Harwood Arms venison Scotch egg food Fulham',
    note: 'London\'s only Michelin-starred pub, on a quiet Fulham street that looks entirely ordinary from the outside. The kitchen focuses on British game and seasonal produce handled with genuine technical precision. The venison Scotch egg — the yolk still running, the game forcemeat precisely seasoned, the coating shatteringly crisp — has accumulated more critical attention than most restaurant dishes in London. The Sunday roast books up months in advance, not weeks, which tells you everything you need to know about the quality. The weekday dinner is more accessible and the same kitchen.',
    hours: 'Mon–Fri 18:00–22:00; Sat 12:00–15:00, 18:00–22:00; Sun 12:00–15:30',
    tip: 'Sunday lunch: book months ahead. Weekday dinner is more accessible and identical quality. The venison Scotch egg.',
    type: 'London\'s only Michelin-starred pub — Fulham',
    awards: '⭐ One Michelin Star · London\'s only Michelin-starred pub · Top 50 Gastropubs UK',
    website: 'https://www.harwoodarms.com',
  },
  {
    id: 82,
    nbhd: 'kensington',
    name: 'Kensington Palace',
    cat: 'royal',
    emoji: '👑',
    address: 'Kensington Palace, Kensington Gardens, London W8 4PX',
    lat: 51.5051, lng: -0.1877,
    search: 'Kensington Palace Sunken Garden Diana memorial flowers',
    note: 'William III bought this as a private residence in 1689 — he preferred it to Whitehall because the Kensington air did not aggravate his asthma — and it has been a royal residence ever since. Queen Victoria was born here in 1819, grew up under the controlling Kensington System that kept her isolated from the world, and received her first ministers in this building at 06:00 on the morning she became Queen. Princess Diana had her private apartments here until 1997; the flowers left at the gates after her death formed a pile six feet deep for a quarter-mile. The Prince and Princess of Wales live here now in Apartment 1A. The State Rooms — including Victoria\'s bedroom and the King\'s Staircase — are open to visitors, and the Sunken Garden below the south terrace, redesigned with white flowers as a memorial to Diana in 2017, is free to enter.',
    hours: 'Daily 10:00–18:00 (seasonal variations; check website)',
    tip: 'Book tickets in advance. The Sunken Garden is free and worth visiting independently. The exhibition on Queen Victoria\'s early life is unexpectedly moving.',
    type: 'Royal residence since 1689 — birthplace of Queen Victoria, home of the Prince and Princess of Wales',
    website: 'https://www.hrp.org.uk/kensington-palace',
  },
  {
    id: 77,
    nbhd: 'kensington',
    name: 'Serpentine Galleries',
    cat: 'art',
    emoji: '🏛️',
    address: 'Kensington Gardens, London W2 3XA',
    lat: 51.5054, lng: -0.1735,
    search: 'Serpentine Pavilion contemporary architecture Hyde Park',
    note: 'Two galleries in Kensington Gardens — the Serpentine South in a 1934 former tea pavilion, the Serpentine North across the bridge — show some of the most ambitious contemporary and experimental art programming in London, always free. The annual Serpentine Pavilion commission has run since 2000 and is one of the most significant architectural events in the world: each year a major architect who has not previously built in the UK is invited to design a temporary structure in the park. Zaha Hadid opened the series. Then Oscar Niemeyer, Frank Gehry, Herzog & de Meuron, Rem Koolhaas — the list is a complete history of 21st-century architecture. The pavilion stands from June through October alongside the gallery programme.',
    hours: 'Tue–Sun 10:00–18:00; closed Mon; Pavilion Jun–Oct',
    tip: 'Free entry always. The annual Pavilion is open June through October — visit for the building as much as the art programme.',
    type: 'Contemporary art galleries in Hyde Park — free, with annual architect-designed Pavilion (since 2000)',
    website: 'https://www.serpentinegalleries.org',
  },
  {
    id: 76,
    nbhd: 'kensington',
    name: 'Saatchi Gallery',
    cat: 'art',
    emoji: '🖌️',
    address: 'Duke of York\'s HQ, King\'s Road, Chelsea, London SW3 4SQ',
    lat: 51.4915, lng: -0.1606,
    search: 'Saatchi Gallery interior exhibition Chelsea London',
    note: 'Charles Saatchi began his gallery in 1985 and used it to introduce Damien Hirst, Tracey Emin and the Young British Artists to the world — shows that changed British art permanently. The Chelsea location, in a Georgian military building on King\'s Road, has been open since 2008 and maintains the gallery\'s position as the place where emerging international art gets its most significant early platform in London. Entry is always free. The programme mixes established names with artists making their first major institutional shows, and the scale of the building — a former parade ground converted into a sequence of high, clean galleries — allows work that commercial galleries cannot house. The current exhibition determines everything; check the website before visiting.',
    hours: 'Daily 10:00–18:00',
    tip: 'Free always. Check the website for the current exhibition — the programme changes and ranges from revelatory to important.',
    type: 'Contemporary art gallery — free, Chelsea (home of the Young British Artists)',
    website: 'https://www.saatchigallery.com',
  },

  // ── SHOREDITCH & SPITALFIELDS ─────────────────────────────────────────────

  {
    id: 63,
    nbhd: 'shoreditch',
    name: 'Dennis Severs\' House',
    cat: 'film',
    emoji: '🎬',
    address: '18 Folgate St, Spitalfields, London E1 6BX',
    lat: 51.5218, lng: -0.0758,
    search: 'Dennis Severs House interior candlelit Georgian Spitalfields',
    note: 'The most cinematically constructed interior in London, and the most extraordinary thing in the city that almost no one knows about. In 1979 the American artist Dennis Severs bought a Georgian terraced house in Spitalfields and spent his life constructing a \'still-life drama\': ten rooms across 300 years, as if the Huguenot silk-weaver family who lived here from 1724 has just stepped out. Candles burning. Food half-eaten on the table. A coat still warm near the fire. The smell of oranges, wood smoke, damp linen. The BBC and various film and television productions have used the house as a period drama location, because nothing better has been built to replicate Georgian London. The Monday evening candlelit session — in which you move through it in complete silence — is more cinematically constructed than almost anything playing in a London cinema that week. Nothing else in any city approaches it.',
    hours: 'Sun 12:00–16:00; Mon 12:00–14:00; Mon evenings 18:00–21:00 (must book)',
    tip: 'Book the Monday evening candlelit session specifically — it is the intended experience. Nothing in London approaches it.',
    type: 'London\'s most cinematic interior — an 18th-century still-life drama in Spitalfields',
    website: 'https://www.dennissevershouse.co.uk',
  },

  {
    id: 88,
    nbhd: 'st-johns-wood',
    name: 'Abbey Road Crossing',
    cat: 'music',
    emoji: '🎼',
    address: 'Abbey Road, London NW8 9AY',
    lat: 51.5320,
    lng: -0.1776,
    search: 'Abbey Road zebra crossing Beatles four figures striped road iconic',
    note: 'On 8 August 1969, photographer Iain Macmillan stood on a stepladder in the middle of this road for ten minutes while four Beatles walked back and forth across the zebra crossing. The resulting photograph — taken in just six shots — became the cover of their last recorded album and one of the most imitated images in history. Abbey Road Studios, directly behind the gates, has been in continuous use since 1931 and its walls have absorbed sessions by Pink Floyd, Radiohead, Adele, and the scores of virtually every major British film of the past fifty years. The fan-written wall outside is repainted monthly. The shop sells studio-exclusive merchandise you cannot buy elsewhere.',
    hours: 'Crossing always accessible; shop Mon–Sat 9:30–17:30, Sun 10:00–17:00',
    tip: 'Go before 9am for an empty crossing. The live webcam at abbeyroad.com/crossing lets someone at home watch you cross in real time.',
    type: 'Music history landmark & studio shop (est. 1931)',
    website: 'https://www.abbeyroad.com',
  },
  {
    id: 89,
    nbhd: 'soho',
    name: 'The 100 Club',
    cat: 'music',
    emoji: '🎸',
    address: '100 Oxford Street, London W1D 1LL',
    lat: 51.5163,
    lng: -0.1318,
    search: '100 Club Oxford Street basement jazz blues live music London',
    note: 'Opened in 1942 in a basement on Oxford Street and has not stopped since. The Rolling Stones played their first London gig in this room in 1962. In September 1976, The 100 Club Punk Festival — two nights, The Sex Pistols, The Clash, Siouxsie and the Banshees, The Buzzcocks — effectively launched British punk as a public movement. Muddy Waters and Louis Armstrong played here. Oasis, Amy Winehouse, and The White Stripes played here. The ceiling is low, the walls carry eighty years of atmosphere, and the music calendar runs most nights across jazz, blues, soul, and indie. When Mick Jagger helped fund its survival in 2011, he was preserving something genuinely irreplaceable.',
    hours: 'Most evenings from 19:30; check website for schedule',
    tip: 'Tickets rarely exceed £20 even for well-known acts. The front area by the stage fills first — arrive early if you want to be close to the music.',
    type: 'Live music basement — jazz, blues, rock (est. 1942)',
    website: 'https://www.the100club.co.uk',
  },
  {
    id: 90,
    nbhd: 'south-kensington',
    name: 'Royal Albert Hall',
    cat: 'music',
    emoji: '🎻',
    address: 'Kensington Gore, London SW7 2AP',
    lat: 51.5009,
    lng: -0.1775,
    search: 'Royal Albert Hall interior auditorium Victorian architecture concert',
    note: 'Queen Victoria opened it in 1871, completing the vision of Prince Albert, who died before he could see it built. The drum-shaped Victorian hall seats 5,272 people beneath a vast glass and wrought-iron dome, and the BBC Proms have filled it every summer since 1895 — the longest-running classical music festival in the world. Guided tours (daily, from £18) take you through the main auditorium, the Royal Box, the Queen\'s private suite, and backstage spaces that are never accessible during performances. Standing in that empty room while a guide describes Sinatra, Hendrix, and Churchill gives the space a completely different weight than a concert does.',
    hours: 'Tours daily 10:00–15:30 (departures throughout); check for concert schedule',
    tip: 'Book a daytime tour even if you have a concert ticket — you access entirely different parts of the building, including the Queen\'s private suite.',
    type: 'Concert hall & heritage tour (opened 1871)',
    website: 'https://www.royalalberthall.com',
  },
  {
    id: 91,
    nbhd: 'soho',
    name: 'Denmark Street',
    cat: 'music',
    emoji: '🎵',
    address: 'Denmark Street, London WC2H 8NL',
    lat: 51.5159,
    lng: -0.1278,
    search: 'Denmark Street guitar shops music history London Tin Pan Alley',
    note: 'A single block between Charing Cross Road and St Giles High Street that shaped British popular music for sixty years. The Rolling Stones recorded their first single at No. 4 in 1963. David Bowie made his first recording at No. 24. The Kinks, The Who, and The Beatles all passed through rehearsal rooms along this stretch. The Sex Pistols lived and rehearsed at No. 6 in 1975 and 1976 — graffiti they left on the walls was preserved when the building was later renovated. Independent guitar and instrument shops have lined the street since the 1950s and most remain. Ten minutes to walk end to end; a century to absorb.',
    hours: 'Always accessible; instrument shops generally Mon–Sat 10:00–18:00',
    tip: 'Guitar shops here welcome browsers — you can play most instruments without any obligation to buy. Ask the staff about the history of their specific building.',
    type: 'Tin Pan Alley — instrument shops & music history street',
    website: 'https://en.wikipedia.org/wiki/Denmark_Street',
  },
  {
    id: 92,
    nbhd: 'camden',
    name: 'KOKO',
    cat: 'music',
    emoji: '🎤',
    address: '1A Camden High Street, London NW1 7JE',
    lat: 51.5388,
    lng: -0.1430,
    search: 'KOKO Camden theatre Victorian interior ornate balcony gilded concert',
    note: 'Built in 1900 as the Camden Theatre — a Victorian variety hall with ornate plasterwork, gilded boxes, and a raked auditorium — it ran as a BBC television studio in the 1950s before becoming one of London\'s defining rock venues. Madonna played a secret show here in 2006. Prince performed here. David Bowie, The Clash, Coldplay, and Daft Punk all played KOKO shows. After a fire, it closed in 2020 and reopened in 2022 following a £70 million restoration that rebuilt the Victorian interior precisely and added a rooftop bar with views over Camden. It holds around 1,500 people and remains one of the most beautiful mid-size concert rooms in Britain.',
    hours: 'Event nights only; rooftop bar open selected evenings',
    tip: 'The upper gallery levels give the best view of the Victorian interior. Worth booking a show you are only half-interested in just to be in the room.',
    type: 'Victorian concert venue (est. 1900, restored 2022)',
    website: 'https://koko.uk.com',
  },
  {
    id: 93,
    nbhd: 'marylebone',
    name: 'Wigmore Hall',
    cat: 'music',
    emoji: '🎹',
    address: '36 Wigmore Street, London W1U 2BP',
    lat: 51.5158,
    lng: -0.1502,
    search: 'Wigmore Hall interior chamber music concert hall London',
    note: 'Bechstein, the German piano manufacturer, built this room in 1901 as a private showroom — a recital hall designed to sell pianos to wealthy Londoners. When the First World War made that untenable, it was sold and reopened in 1917 as a public concert hall. The cupola above the stage — shell-pink marble, alabaster, and a mosaic of the Soul of Music by Gérard Moira — is one of the most beautiful ceilings in London. The acoustics are considered among the finest anywhere for chamber music, and the 550-seat room means you are always close to the performers. Consistently ranked among the great chamber music venues in the world, quietly, without making a fuss about it.',
    hours: 'Varies by event; Sun morning coffee concerts from 11:30',
    tip: 'Sunday morning coffee concerts (from £15) are the best-value classical music in London — no dress code, doors open at 10:45, licensed café in the hall.',
    type: 'World-class chamber music hall (est. 1901)',
    website: 'https://www.wigmore-hall.org.uk',
  },
  {
    id: 94,
    nbhd: 'camden',
    name: 'The Roundhouse',
    cat: 'music',
    emoji: '🥁',
    address: 'Chalk Farm Road, London NW1 8EH',
    lat: 51.5434,
    lng: -0.1519,
    search: 'Roundhouse Camden concert hall circular interior iron columns Victorian',
    note: 'Built in 1847 as a steam engine turntable shed — a circular iron and brick structure designed to rotate locomotives — it sat empty for decades before the Centre 42 arts movement opened it as a performance space in 1966. Jimi Hendrix and Pink Floyd played the opening nights. The Doors brought Jim Morrison here for one of only two British appearances. Led Zeppelin, The Ramones, and Patti Smith all played here in the years that followed. Restored and reopened as a producing arts venue in 2006, it now holds 3,300 people inside what is still, visibly, an iron-columned Victorian engine shed. The circular architecture and exposed brick make every show feel different from any other venue in the city.',
    hours: 'Event nights and some daytime shows; check calendar',
    tip: 'The circular floor means almost no bad position — the room is designed so the whole space becomes the stage. Standing tickets give you the freedom to move.',
    type: 'Circular Victorian arts venue (opened as music space 1966)',
    website: 'https://www.roundhouse.org.uk',
  },
  {
    id: 95,
    nbhd: 'southbank',
    name: 'Shakespeare\'s Globe',
    cat: 'books',
    emoji: '📜',
    address: '21 New Globe Walk, London SE1 9DT',
    lat: 51.5081,
    lng: -0.0972,
    search: 'Shakespeare Globe Theatre interior wooden stage groundlings gallery Elizabethan',
    note: 'The original Globe was built by Shakespeare\'s company in 1599 using timber salvaged from an earlier playhouse. It burned down in 1613 when a stage cannon misfired during a performance of Henry VIII and set the thatched roof alight. The replica that opened in 1997 stands 230 metres from the original site, built with green oak and water reed thatch using Elizabethan construction methods — and is the only thatched building permitted in London since the Great Fire of 1666. Performances are open-air, the groundlings stand as they did in Shakespeare\'s time, and rain is not a reason to cancel. The adjacent Sam Wanamaker Playhouse hosts candlelit indoor productions in winter. Tours run daily year-round.',
    hours: 'Tours daily 10:00–17:00; performance season April–October',
    tip: 'Standing groundling tickets start at £5 and put you closest to the stage. Wooden benches are authentic to the period in every sense — bring a cushion if you book seated.',
    type: 'Reconstructed Elizabethan theatre & literary landmark (opened 1997)',
    website: 'https://www.shakespearesglobe.com',
  },
  {
    id: 96,
    nbhd: 'kings-cross',
    name: 'The British Library',
    cat: 'books',
    emoji: '📚',
    address: '96 Euston Road, London NW1 2DB',
    lat: 51.5298,
    lng: -0.1276,
    search: 'British Library Treasures Gallery Magna Carta manuscripts interior',
    note: 'The largest library in the world by number of items — over 170 million pieces, growing by three million a year. The Sir John Ritblat Treasure Gallery is free and contains things that stop you mid-step: one of four surviving copies of Magna Carta (1215); the Lindisfarne Gospels from 715 AD; the Gutenberg Bible; John Lennon\'s handwritten lyrics on a notepad; Jane Austen\'s writing desk and the notebook in which she drafted her novels. Lewis Carroll\'s own annotated copy of Alice\'s Adventures in Wonderland. The building itself — opened 1998, designed by Colin St John Wilson — is one of the finest public buildings in London, its central tower housing six floors of George III\'s 65,000 books visible through glass.',
    hours: 'Mon–Thu 09:30–20:00; Fri 09:30–18:00; Sat 09:30–17:00; Sun 11:00–17:00. Treasure Gallery free.',
    tip: 'No booking needed for the Treasure Gallery. Go straight there first — the manuscripts are extraordinary up close and it takes about an hour.',
    type: 'World\'s largest library — free Treasure Gallery (opened 1998)',
    website: 'https://www.bl.uk',
  },
  {
    id: 97,
    nbhd: 'city',
    name: 'Ye Olde Cheshire Cheese',
    cat: 'books',
    emoji: '🖋️',
    address: '145 Fleet Street, London EC4A 2BU',
    lat: 51.5142,
    lng: -0.1082,
    search: 'Ye Olde Cheshire Cheese pub interior bar panelled historic low ceiling',
    note: 'Rebuilt in 1667 on a site licensed for drinking since at least the 15th century — one year after the Great Fire of London destroyed everything around it. The warren of low-ceilinged, sawdust-floored rooms has barely changed since. Samuel Johnson drank here while compiling his Dictionary in the house just behind Fleet Street. Charles Dickens drank here; it appears in A Tale of Two Cities. Mark Twain drank here during his London visits. W.B. Yeats, Alfred Lord Tennyson, and Arthur Conan Doyle all came regularly. It is the most literary pub in London — which is saying a great deal — and the building survived the Blitz intact.',
    hours: 'Mon–Sat 12:00–23:00; closed Sunday',
    tip: 'Go down to the cellar bar — it is the oldest part of the building and the most atmospheric. The chop and steak puddings have been on the menu for over a century.',
    type: 'Historic pub rebuilt 1667 — Dickens, Johnson, Twain, Yeats',
    website: 'https://ye-olde-cheshire-cheese.co.uk',
  },
  {
    id: 98,
    nbhd: 'city',
    name: 'Dr Johnson\'s House',
    cat: 'books',
    emoji: '📖',
    address: '17 Gough Square, London EC4A 3DE',
    lat: 51.5143,
    lng: -0.1079,
    search: 'Dr Johnson House interior Georgian study desk books museum period',
    note: 'Samuel Johnson compiled the first great dictionary of the English language in this house between 1748 and 1755 — a task he performed largely alone, working in the garret with six amanuenses, taking nine years to do what the French Académie had attempted with forty scholars over sixty years. The result defined 42,773 words with 114,000 supporting quotations from English literature. The house, a rare Georgian townhouse tucked behind Fleet Street, is now a small museum with Johnson\'s portrait by Joshua Reynolds, first editions, and personal objects. Intimate, quiet, and easy to miss — which is part of its appeal.',
    hours: 'Mon–Sat 11:00–17:30 (Oct–Apr closes 17:00); closed Sunday. Admission £7.50 adults.',
    tip: 'Hidden down Gough Square off Fleet Street — follow signs from Fetter Lane. Visit takes about 45 minutes. Often empty on weekday mornings.',
    type: 'Georgian townhouse museum — where Johnson wrote his Dictionary (est. 1911 as museum)',
    website: 'https://www.drjohnsonshouse.org',
  },
  {
    id: 99,
    nbhd: 'marylebone',
    name: 'Daunt Books',
    cat: 'books',
    emoji: '🔖',
    address: '83 Marylebone High Street, London W1U 4QW',
    lat: 51.5196,
    lng: -0.1534,
    search: 'Daunt Books Marylebone interior galleried Edwardian skylight bookshop',
    note: 'Built in 1910 as an Edwardian bookshop with a long galleried hall beneath a barrel-vaulted skylight — oak galleries on three levels, natural light flooding down from above, stained-glass windows at the far end. It is the most beautiful bookshop in London. The Marylebone branch organises its travel books by country rather than by author — a system so obviously correct that it is surprising no one else does it. Independent, seriously curated, and the kind of shop that reliably makes you buy books you had no intention of buying. Author events run most evenings.',
    hours: 'Mon–Sat 09:00–19:30; Sun 11:00–18:00',
    tip: 'The rear gallery under the skylight — beyond the travel section — is the reason to come. Check the events calendar for evening author talks.',
    type: 'Edwardian galleried bookshop (est. 1990, building 1910)',
    website: 'https://dauntbooks.co.uk',
  },
  {
    id: 100,
    nbhd: 'hampstead',
    name: 'Keats House',
    cat: 'books',
    emoji: '🌿',
    address: '10 Keats Grove, London NW3 2RR',
    lat: 51.5552,
    lng: -0.1690,
    search: 'Keats House Hampstead garden Regency museum interior sitting room',
    note: 'John Keats moved into the ground-floor rooms of this Regency villa in December 1818 at the age of 23. In the garden, beside the plum tree, he wrote Ode to a Nightingale in a single sitting on a spring morning in 1819. He also wrote Ode on a Grecian Urn, Ode to Autumn, and The Eve of St Agnes here. His neighbour Fanny Brawne became his fiancée; the engagement ring he gave her is in the house. He left for Rome in September 1820 and died there of tuberculosis at 25. The house preserves his rooms, his letters, his annotated books, and the feeling of a life suspended — quiet, very small, and one of the most affecting literary museums in England.',
    hours: 'Wed–Sun 11:00–17:00; closed Mon–Tue. Admission £9 adults; garden free.',
    tip: 'The garden is free. Combine with Hampstead village — five minutes\' walk, some of the best cafés in London.',
    type: 'Regency literary museum — home of John Keats 1818–1820',
    website: 'https://www.cityoflondon.gov.uk/things-to-do/green-spaces/hampstead-heath/keats-house',
  },
  {
    id: 101,
    nbhd: 'kew',
    name: 'Kew Gardens',
    cat: 'parks',
    emoji: '🌿',
    address: 'Royal Botanic Gardens, Kew, Richmond TW9 3AE',
    lat: 51.4785,
    lng: -0.2956,
    search: 'Kew Gardens Palm House Victorian glasshouse botanical interior',
    note: 'The Royal Botanic Gardens hold the most diverse collection of living plants on earth — 50,000 species across 132 hectares, a UNESCO World Heritage Site since 2003. The Victorian Palm House, completed in 1848, is the finest surviving example of Victorian glass and iron architecture in the world; the oldest pot plant in existence, an Eastern Cape cycad collected in 1773, grows inside it. The Treetop Walkway carries visitors 18 metres into the canopy of chestnut and oak. The 1762 Pagoda, built for Princess Augusta, was recently restored. The Temperate House — the largest Victorian glasshouse in the world — reopened after a five-year restoration in 2018. At a certain point you stop cataloguing what Kew contains and accept that it is one of the great places in London.',
    hours: 'Daily 10:00–18:00 (summer) to 10:00–16:00 (winter). Admission from £22 adults.',
    tip: 'The Japanese garden and the Waterlily House are quieter than the main glasshouses. Allow at least three hours — four in summer. The Christmas light trail (November–January) is spectacular.',
    type: 'Royal Botanic Gardens — UNESCO World Heritage Site (est. 1759)',
    website: 'https://www.kew.org',
  },
  {
    id: 102,
    nbhd: 'chelsea',
    name: 'Chelsea Physic Garden',
    cat: 'parks',
    emoji: '🌱',
    address: '66 Royal Hospital Road, London SW3 4HS',
    lat: 51.4857,
    lng: -0.1677,
    search: 'Chelsea Physic Garden walled botanical garden interior London',
    note: 'Founded in 1673 by the Worshipful Society of Apothecaries as a place to grow medicinal plants for training apothecaries — the second-oldest botanical garden in England. The four-acre walled garden on the Chelsea Embankment is invisible from the street: you enter through a small gate and find a dense, labelled world of 5,000 plants arranged by their uses in medicine, perfumery, dye production, and food. Cotton seeds distributed from this garden in 1732 helped establish the cotton industry in Georgia. A statue of Hans Sloane, who saved the garden from closure in 1722, stands at its centre. One of London\'s best-kept secrets, opened to the public in the 1980s after three centuries of restricted access.',
    hours: 'Sun–Fri 11:00–17:00; closed Saturday. Admission £5–£15 (free guided tour included).',
    tip: 'The Garden Café is excellent — one of the most peaceful lunches in London. Go mid-week when it is nearly empty.',
    type: 'Walled medicinal garden — London\'s oldest botanical secret (est. 1673)',
    website: 'https://www.chelseaphysicgarden.co.uk',
  },
  {
    id: 103,
    nbhd: 'hampstead',
    name: 'Hampstead Heath',
    cat: 'parks',
    emoji: '🌳',
    address: 'Hampstead Heath, London NW3',
    lat: 51.5621,
    lng: -0.1665,
    search: 'Hampstead Heath Parliament Hill panoramic London skyline view',
    note: '320 hectares of ancient woodland, meadow, and swimming ponds on a hill north of the city — the highest point in London, with an unobstructed skyline view from Parliament Hill that has been protected since 1829. The Heath has never been formally landscaped: it looks as it did when it was common land because it essentially still is. The swimming ponds — separate enclosures for men, women, and mixed — have been in use since the 18th century and remain open year-round, including through winter. Kenwood House at the north edge holds a free collection that includes a Rembrandt self-portrait and a Vermeer. The Heath feels like countryside. It is 25 minutes from central London by Underground.',
    hours: 'Open at all times, free. Kenwood House daily 10:00–17:00 (free).',
    tip: 'Parliament Hill at dawn or dusk before the crowds. The Ladies\' Pond is a London institution — members swim through January. Kenwood is often overlooked and never crowded.',
    type: 'Ancient common land — ponds, woodland & city\'s finest skyline view',
    website: 'https://www.cityoflondon.gov.uk/things-to-do/green-spaces/hampstead-heath',
  },
  {
    id: 104,
    nbhd: 'westminster',
    name: 'St James\'s Park',
    cat: 'parks',
    emoji: '🦢',
    address: 'St James\'s Park, London SW1A 2BJ',
    lat: 51.5024,
    lng: -0.1340,
    search: 'St James\'s Park pelicans lake Buckingham Palace view London',
    note: 'The oldest of London\'s royal parks, laid out by Charles II in 1660 after his return from French exile, with a formal lake at its centre. Henry VIII had used the land for deer; before him it was a marsh. The ornamental lake is home to a colony of pelicans — a gift from the Russian ambassador in 1664, replaced by their descendants ever since. The view across the water toward the London Eye and Foreign Office is one of the most composed in the city. The park connects Buckingham Palace to Westminster and is best experienced in early morning, before the tourists arrive, when the pelicans feed on the bridge and the light hits the water without obstruction.',
    hours: 'Daily 05:00–24:00 (free)',
    tip: 'Pelican feeding takes place around 14:30 daily near Duck Island. The bridge view is best in morning light. The park is at its most beautiful in late April when the trees are in blossom.',
    type: 'Royal park — pelicans, lake & London\'s finest central garden (est. 1660)',
    website: 'https://www.royalparks.org.uk/parks/st-jamess-park',
  },
  {
    id: 105,
    nbhd: 'richmond',
    name: 'Richmond Park',
    cat: 'parks',
    emoji: '🦌',
    address: 'Richmond Park, Richmond TW10 5HS',
    lat: 51.4408,
    lng: -0.2729,
    search: 'Richmond Park deer ancient oaks parkland landscape London',
    note: 'The largest royal park in London — 1,000 hectares of ancient parkland enclosed by Charles I in 1637 as a hunting ground. Six hundred red and fallow deer roam freely through bracken and ancient oaks, some of which were already old when the park was enclosed. From Henry VIII\'s Mound, a protected sightline unobstructed by development since 1710, the view extends 16 kilometres to the dome of St Paul\'s Cathedral. The Isabella Plantation — a woodland garden inside the park — is one of the best places in London to see azaleas and rhododendrons in late April. The park is 30 minutes from central London by rail and feels like another country.',
    hours: 'Daily 07:00–dusk (free)',
    tip: 'Hire a bicycle at Richmond Gate and cover the park properly — on foot it is too large to do justice. In October, the deer rut is extraordinary to watch from a safe distance.',
    type: 'Ancient royal deer park — 600 deer, ancient oaks, 16km palace views (est. 1637)',
    website: 'https://www.royalparks.org.uk/parks/richmond-park',
  },
  {
    id: 106,
    nbhd: 'city',
    name: 'Sky Garden',
    cat: 'parks',
    emoji: '🌇',
    address: '20 Fenchurch Street, London EC3M 3BY',
    lat: 51.5107,
    lng: -0.0832,
    search: 'Sky Garden London interior subtropical plants ferns panoramic city view',
    note: 'Three floors of public gardens open to the sky beneath a glass dome at the summit of 20 Fenchurch Street — the building nicknamed the Walkie-Talkie for its deliberately widening profile. Entry is free but requires timed booking. The gardens are planted with Mediterranean and South African species; the panoramic views at 155 metres extend across the Thames in every direction from the Shard to St Paul\'s to Canary Wharf. The building became notorious in 2013 when its concave glass facade focused sunlight hot enough to melt the bodywork of cars parked below — a design flaw corrected by a permanent sunshade. The garden, opened in 2015, is its considerable redemption.',
    hours: 'Mon–Fri 10:00–18:00; Sat–Sun 11:00–21:00 (free, must book in advance at skygarden.london)',
    tip: 'Book the earliest weekday slot for the best light and an empty garden. Evening weekend slots have a bar and better atmosphere — book weeks ahead.',
    type: 'Free public rooftop garden — 155m above London (opened 2015)',
    website: 'https://skygarden.london',
  },
];
   