// A Perfect Day — London
// data.js — 71 curated places
//
// v5 — May 2026
// Voice: boutique hotel concierge — direct, specific, opinionated
// v4 changes: Removed 6 generic tourist entries; added Berry Bros & Rudd (1),
//   The Wolseley (4), Quo Vadis (36), Bibendum (50), Coal Drops Yard (67),
//   The French House (68). Improved descriptions: Tower of London (24),
//   Covent Garden (29), Greenwich Market (57). Fixed Millennium Bridge category.
// v5 changes: Rewrote 10 descriptions to tour-guide quality: White Cube (19),
//   Gelateria 3Bis (15), Mr Fogg's (33), Opium (37), Clos Maggiore (31),
//   German Gymnasium (42), Sky Garden (25), The Roundhouse (41),
//   Luna Rossa (45), Kalamaras (46), Hoppers (70).
// v6 changes: Rewrote 10 more descriptions: Westminster Abbey (2),
//   WatchHouse Bermondsey (17), Tower Bridge (23), St Paul's Cathedral (28),
//   Tate Modern (7), The Barbican (62), Royal Observatory (56),
//   The Palomar (69), Wellcome Collection (40), Core by Clare Smyth (44).

const PLACES = [

  // ── WESTMINSTER ───────────────────────────────────────────────────────────

  {
    id: 1,
    nbhd: 'westminster',
    name: 'Berry Bros. & Rudd',
    cat: 'shop',
    emoji: '🍷',
    address: '3 St James\'s St, London SW1A 1EG',
    lat: 51.5063, lng: -0.1388,
    search: 'Berry Bros Rudd wine merchant St James\'s London',
    note: 'Britain\'s oldest wine merchant, trading from the same St James\'s building since 1698. Walk in and nothing has been renovated for atmosphere — the Georgian panelling, the ancient weighing scales on the floor (used originally to weigh customers as well as coffee), the bare floorboards worn into hollows over three centuries. They hold the Royal Warrants of both the King and the Prince of Wales. The basement cellars run under St James\'s Street and hold one of the finest private wine collections in the world. The staff know their inventory in the way that booksellers know books — with genuine opinions — and will tell you exactly what to open and when.',
    hours: 'Mon–Fri 10:00–18:00; Sat 10:00–17:00; closed Sun',
    tip: 'The shop itself is the reason to come — the room is a preserved piece of Regency London. Ask about current fine wine recommendations for gifts. Tastings and cellar events on the website.',
    type: 'Britain\'s oldest wine merchant (est. 1698) — St James\'s',
    website: 'https://www.bbr.com',
  },
  {
    id: 2,
    nbhd: 'westminster',
    name: 'Westminster Abbey',
    cat: 'church',
    emoji: '⛪',
    address: '20 Deans Yard, Westminster, London SW1P 3PA',
    lat: 51.4994, lng: -0.1276,
    search: 'Westminster Abbey London',
    note: 'Every English monarch since 1066 has been crowned on the same spot inside this building. The nave is the tallest Gothic nave in England, and on a quiet weekday morning — before the school groups arrive — the scale of it, the quality of the stone and the particular silence that centuries of use have settled into the place do something that photographs cannot convey. Henry V is buried here. Mary Queen of Scots. Isaac Newton is in the nave and Charles Darwin is ten feet from him, which says something about the breadth of what England decided to venerate. Poets\' Corner takes an hour on its own if you read the stones — Chaucer, Dickens, Hardy, Kipling — and most visitors walk through in ten minutes and miss all of it. The audio guide matters here more than almost anywhere else in London: every flagstone has a story, and the guide is the only way to find it.',
    hours: 'Mon–Sat 09:30–15:30 (last entry); closed to tourists on Sundays',
    tip: 'Book online to skip the queue. Take the audio guide — it is not optional here. Go early on a weekday for the nave without the crowds.',
    type: 'Gothic abbey & coronation church (UNESCO World Heritage Site)',
    website: 'https://www.westminster-abbey.org',
  },
  {
    id: 3,
    nbhd: 'westminster',
    name: 'Churchill War Rooms',
    cat: 'culture',
    emoji: '🏛️',
    address: 'Clive Steps, King Charles Street, London SW1A 2AQ',
    lat: 51.5020, lng: -0.1289,
    search: 'Churchill War Rooms London',
    note: 'The Cabinet War Rooms beneath Whitehall were sealed on VE Day in 1945 and left exactly as they were — maps still pinned, phones still connected, a single bulb burning in the Map Room. Walk through and you understand something about how wars are actually run: not from glory, but from a corridor with low ceilings and bad lighting. The Churchill Museum beside it is one of the most intelligent biographical exhibitions in London. Do not skip it.',
    hours: 'Daily 09:30–18:00',
    tip: 'Two hours minimum. The Churchill Museum is as compelling as the bunker — allow time for both.',
    type: 'Preserved wartime bunker & museum (IWM)',
    website: 'https://www.iwm.org.uk/visits/churchill-war-rooms',
  },
  {
    id: 4,
    nbhd: 'westminster',
    name: 'The Wolseley',
    cat: 'food',
    emoji: '🥐',
    address: '160 Piccadilly, London W1J 9EB',
    lat: 51.5073, lng: -0.1428,
    search: 'The Wolseley restaurant Piccadilly London breakfast',
    note: 'A grand café-brasserie occupying what was built as a Wolseley car showroom in 1921 — the arched windows, black-and-white marble floor and vaulted ceiling have been put to their correct purpose now. Breakfast here is the most civilised in London: properly made eggs, a full pastry counter, newspapers, unhurried service and a room that fills with Mayfair hotel guests, publishers and people who have been coming for twenty years. Lunch and dinner are reliably excellent across a long brasserie menu. Book ahead for a good table; the bar counter takes walk-ins.',
    hours: 'Mon–Fri 07:00–midnight; Sat 08:00–midnight; Sun 08:00–23:00',
    tip: 'Breakfast before 09:00 is the quietest and most civilised hour. The wiener schnitzel at lunch, the eggs Benedict at breakfast — both non-negotiable depending on the time. Book a table for dinner; bar seats are walk-in.',
    type: 'All-day grand café-brasserie — Piccadilly (breakfast from 07:00)',
    website: 'https://www.thewolseley.com',
  },
  {
    id: 5,
    nbhd: 'westminster',
    name: 'St James\'s Park',
    cat: 'nature',
    emoji: '🌿',
    address: 'St James\'s Park, London SW1A 2BJ',
    lat: 51.5025, lng: -0.1353,
    search: 'St James\'s Park London',
    note: 'Stand on the bridge over the lake and you have two views simultaneously: Buckingham Palace to the west, the gilded roofscapes and turrets of Whitehall to the east. The pelicans have been here since 1664 and are fed near the island each afternoon at around 14:30. The park connects Green Park to Hyde Park — a two-mile walk from the Palace to Kensington Gardens without leaving green.',
    hours: 'Daily 05:00–midnight',
    tip: 'The bridge is the finest free viewpoint for the Palace in London. Walk east to the Mall and on toward St James\'s Palace.',
    type: 'London\'s oldest Royal Park',
    website: 'https://www.royalparks.org.uk/parks/st-jamess-park',
  },
  {
    id: 73,
    nbhd: 'westminster',
    name: 'The Connaught Bar',
    cat: 'pub',
    emoji: '🍸',
    address: 'Carlos Place, Mayfair, London W1K 2AL',
    lat: 51.5118, lng: -0.1488,
    search: 'The Connaught Bar Mayfair London',
    note: 'Consistently voted the world\'s best bar. The room is all marble, mirror and Art Deco curves, and the dry martini service arrives on a silver trolley — mixed tableside to your exact specification from a choice of vermouths and bitters. The ritual is as precise as the drink. The Connaught Martini is one of the most discussed cocktails in the world; the service that surrounds it is faultless.',
    hours: 'Mon–Sat 11:00–00:00; Sun 11:00–23:00',
    tip: 'Book ahead — the bar fills completely by 20:00 at weekends. The dry martini trolley is the experience. Ask the bartender for their recommendation on vermouth ratio.',
    type: 'World\'s #1 cocktail bar (Mayfair, The Connaught Hotel)',
    website: 'https://www.the-connaught.co.uk/bars-restaurant/the-connaught-bar/',
  },
  {
    id: 74,
    nbhd: 'westminster',
    name: 'Dukes Bar',
    cat: 'pub',
    emoji: '🍋',
    address: '35 St James\'s Place, London SW1A 1NY',
    lat: 51.5065, lng: -0.1418,
    search: 'Dukes Bar St James\'s London martini',
    note: 'Inside Dukes Hotel in St James\'s, in a room that seats perhaps 30 people and looks unchanged since Ian Fleming drank here and worked out the formula that became James Bond\'s martini. The dry martini service is conducted tableside: frozen gin, no dilution from ice, poured with ceremony into a pre-chilled glass. Bone dry, extremely cold and served with unhurried precision. Two-martini limit per person. This is genuine advice, not theatrical caution.',
    hours: 'Mon–Sat 12:00–23:00; Sun 12:00–22:30',
    tip: 'The two-martini house rule exists for good reason. The vesper — vodka, gin, Lillet — is the Fleming original. Book ahead.',
    type: 'Historic cocktail bar — the birthplace of Bond\'s martini',
    website: 'https://www.dukeshotel.com/dukes-bar',
  },
  {
    id: 59,
    nbhd: 'westminster',
    name: 'Daunt Books',
    cat: 'shop',
    emoji: '📚',
    address: '83–84 Marylebone High St, London W1U 4QW',
    lat: 51.5200, lng: -0.1533,
    search: 'Daunt Books Marylebone London bookshop',
    note: 'The back room is what brings people back: long oak galleries under a skylight, books arranged by country rather than genre — the fiction, history, travel writing and maps for each destination all together in one section. The 1912 Edwardian building was designed as a bookshop and has been nothing else since. The cloth bag has become a more credible London souvenir than anything sold in a gift shop. Marylebone High Street is worth the whole morning.',
    hours: 'Mon–Sat 09:00–19:30; Sun 11:00–18:00',
    tip: 'The back room under the skylight is the most beautiful reading space in London. Ask the staff for recommendations — they are genuinely well-read and have strong opinions.',
    type: 'The world\'s most beautiful independent bookshop',
    website: 'https://dauntbooks.co.uk/shops/marylebone/',
  },

  // ── SOUTH BANK ────────────────────────────────────────────────────────────

  {
    id: 7,
    nbhd: 'southbank',
    name: 'Tate Modern',
    cat: 'culture',
    emoji: '🎨',
    address: 'Bankside, London SE1 9TG',
    lat: 51.5076, lng: -0.0994,
    search: 'Tate Modern London',
    note: 'The building alone justifies the visit: a former power station on the South Bank with a Turbine Hall 35 metres high and 155 metres long, which has been the site of some of the most significant public art commissions of the past 25 years — Olafur Eliasson\'s artificial sun that turned visitors\' faces to the ceiling; Ai Weiwei\'s floor of 100 million hand-painted porcelain sunflower seeds; Louise Bourgeois\'s steel spiders, each the height of a house. The permanent collection runs from Picasso and the Surrealists through Rothko, Beuys and Basquiat to artists working now, entirely free. The Rothko room — eight large-format canvases in near-darkness, painted specifically to induce the sensation of a room pressing inward — is one of the few places in London where adults stand in complete silence and are visibly moved. Take the lift to the Blavatnik Building terraces at level 10: the finest free panorama of the Thames in the city, from St Paul\'s to Canary Wharf, with the river below.',
    hours: 'Sun–Thu 10:00–18:00; Fri–Sat 10:00–22:00',
    tip: 'The Rothko room first, then the Turbine Hall, then the Blavatnik terraces. Friday evenings after 18:00 are emptier than any daytime slot.',
    type: 'Modern & contemporary art gallery (permanent collection free)',
    website: 'https://www.tate.org.uk/visit/tate-modern',
  },
  {
    id: 8,
    nbhd: 'southbank',
    name: 'Shakespeare\'s Globe',
    cat: 'culture',
    emoji: '🎭',
    address: '21 New Globe Walk, Bankside, London SE1 9DT',
    lat: 51.5081, lng: -0.0974,
    search: 'Shakespeare\'s Globe Theatre London',
    note: 'A reconstruction of the 1599 Globe in green oak and Norfolk reed, built 200 metres from the original site. The open roof means performances happen in whatever weather the city provides, which is the point. A standing groundling ticket puts you in the yard at stage level, surrounded by a full circular house, with the immediacy that no roofed theatre can replicate. One of the cheapest and best evenings you can spend in London.',
    hours: 'Tours daily 09:30–17:00. Performances Apr–Oct',
    tip: 'Groundling tickets are inexpensive and the most immediate way to see a show. Bring a layer — the open roof is literal. Tours on non-performance days are excellent.',
    type: 'Reconstructed Elizabethan open-air theatre',
    website: 'https://www.shakespearesglobe.com',
  },
  {
    id: 9,
    nbhd: 'southbank',
    name: 'Millennium Bridge',
    cat: 'experience',
    emoji: '🌉',
    address: 'Millennium Bridge, Bankside, London SE1',
    lat: 51.5098, lng: -0.0983,
    search: 'Millennium Bridge London Thames',
    note: 'Norman Foster\'s pedestrian bridge connects St Paul\'s to Tate Modern in a single crossing. Walk it from the north bank at first light when the city is quiet, the dome directly ahead, the Thames below. Then continue: Globe, Borough Market, east along the river to Bermondsey Street. That sequence, starting at 08:00, is the best free morning London offers.',
    hours: 'Open 24 hours',
    tip: 'Cross north to south at first light, then walk east along the Southbank to Borough Market. The best free morning in London.',
    type: 'Pedestrian bridge connecting St Paul\'s to Tate Modern',
    website: 'https://www.london.gov.uk',
  },

  // ── BOROUGH & BERMONDSEY ──────────────────────────────────────────────────

  {
    id: 11,
    nbhd: 'borough',
    name: 'Borough Market',
    cat: 'market',
    emoji: '🛒',
    address: '8 Southwark St, London SE1 1TL',
    lat: 51.5055, lng: -0.0908,
    search: 'Borough Market London',
    note: 'A market on this site since the 13th century. Under Victorian railway arches: over 100 specialist traders — fishmongers, cheesemakers, bakers, charcutiers, coffee roasters — selling things they\'ve grown, cured, brewed or made. Come on a Thursday morning before the weekend crowds transform it into something else. The traders will tell you what\'s exceptional today if you ask.',
    hours: 'Mon–Thu 10:00–17:00; Fri 10:00–18:00; Sat 08:00–17:00; closed Sun',
    tip: 'Thursday morning before 11:00 is the authentic experience. On Saturdays it\'s shoulder-to-shoulder. Go early, or head to Maltby Street instead.',
    type: 'Historic food market (since the 13th century)',
    website: 'https://boroughmarket.org.uk',
  },
  {
    id: 12,
    nbhd: 'borough',
    name: 'El Pastor',
    cat: 'food',
    emoji: '🌮',
    address: '7A Stoney St, London SE1 9AA',
    lat: 51.5055, lng: -0.0913,
    search: 'El Pastor Borough Market London',
    note: 'The trompo is visible from every counter seat: a vertical spit of marinated pork rotating slowly, shaved to order into corn tortillas with pineapple, onion and coriander in the Mexico City style. Counter seats facing the spit are the ones to request. The mezcal list is serious and the kitchen is theatrical. Come hungry.',
    hours: 'Mon–Fri 12:00–22:30; Sat 11:00–22:30; Sun 12:00–21:30',
    tip: 'Counter seats facing the trompo. The al pastor taco is non-negotiable. The house margarita too.',
    type: 'Mexican taqueria & mezcal bar',
    website: 'https://tacoselpastor.co.uk',
  },
  {
    id: 13,
    nbhd: 'borough',
    name: 'Padella',
    cat: 'food',
    emoji: '🍝',
    address: '6 Southwark St, London SE1 1TQ',
    lat: 51.5054, lng: -0.0904,
    search: 'Padella Pasta Borough Market London',
    note: 'Fresh pasta made each morning, nothing over £15, no reservations. The pici cacio e pepe — thick hand-rolled pasta in a sauce of aged pecorino and black pepper — has been written about more than almost anything else in London for good reason. Queue at noon or shortly before; the wait is rarely more than 45 minutes and the room turns quickly. Simple, serious and entirely reliable.',
    hours: 'Mon–Sat 12:00–21:30; Sun 12:00–21:00',
    tip: 'Arrive at noon. The pici cacio e pepe first, the tagliarini with slow-cooked tomato second.',
    type: 'Fresh pasta — walk-in only, no reservations',
    website: 'https://padella.co',
  },
  {
    id: 14,
    nbhd: 'borough',
    name: 'Monmouth Coffee',
    cat: 'cafe',
    emoji: '☕',
    address: '2 Park St, London SE1 9AB',
    lat: 51.5055, lng: -0.0924,
    search: 'Monmouth Coffee Borough Market London',
    note: 'Monmouth has been roasting in Borough since the 1970s and this small dark shop on Park Street is where London\'s specialty coffee culture started. They source directly from small farms, publish the farmers\' names on every bag, and have not materially changed their approach in fifty years. The Saturday queue is one of the most reliable quality indicators in the city.',
    hours: 'Mon–Sat 07:30–18:00; closed Sun',
    tip: 'The beans to take home are a better souvenir than anything from a gift shop. Ask about whichever single origin they\'re currently featuring.',
    type: 'Specialty coffee roaster — where London\'s coffee culture began',
    website: 'https://www.monmouthcoffee.co.uk',
  },
  {
    id: 15,
    nbhd: 'borough',
    name: 'Gelateria 3Bis',
    cat: 'cafe',
    emoji: '🍦',
    address: 'Stoney St, London SE1',
    lat: 51.5053, lng: -0.0907,
    search: 'Gelateria 3Bis Borough Market London',
    note: 'A stall in the Borough Market arches that opens as the market does and disappears with it. The gelato is made in small batches each morning — dense without being heavy, flavoured without tipping into sweetness. The pistachio uses Bronte nuts from Sicily and carries a slight natural bitterness that separates it immediately from anything made with paste. The salted caramel is among the best single scoops in London. Ask for warm chocolate sauce poured over the top, take it out through the Stoney Street arch, and eat it walking west toward the river. That is the correct way to leave Borough Market.',
    hours: 'Mon–Sat 10:00–18:00; Sun 11:00–17:00',
    tip: 'Pistachio or salted caramel. Ask for the warm chocolate sauce. Eat it walking.',
    type: 'Artisan gelato stall',
    website: 'https://gelateria3bis.com',
  },
  {
    id: 16,
    nbhd: 'borough',
    name: 'Bermondsey Street',
    cat: 'experience',
    emoji: '🏘️',
    address: 'Bermondsey Street, London SE1',
    lat: 51.5001, lng: -0.0809,
    search: 'Bermondsey Street London',
    note: 'A medieval pilgrim route that has become one of London\'s most interesting half-miles without attracting the attention it deserves. White Cube gallery, José tapas bar, WatchHouse coffee, independent restaurants and antique shops — all on a street that still feels like a neighbourhood. Ten minutes from London Bridge and most visitors walk straight past the turning. That\'s exactly the point.',
    hours: 'Open all hours; individual businesses vary',
    tip: 'Saturday formula: WatchHouse for coffee at 09:00, White Cube at 10:00, José for tapas at noon. That is a near-perfect Bermondsey morning.',
    type: 'Independent street — galleries, restaurants, coffee',
    website: 'https://www.bermondseystreet.net',
  },
  {
    id: 17,
    nbhd: 'borough',
    name: 'WatchHouse Bermondsey',
    cat: 'cafe',
    emoji: '⌚',
    address: '199 Bermondsey St, London SE1 3UW',
    lat: 51.5003, lng: -0.0793,
    search: 'WatchHouse Bermondsey coffee London',
    note: 'The first WatchHouse, and still the best. The building is a Victorian parish watchhouse — the room where constables guarded the recently dead to prevent grave robbers from taking them — converted into a coffee bar with the original stone walls, arched windows and heavy door intact. The newer WatchHouse branches have better light, more comfortable seating and none of this atmosphere. The batch brew is carefully sourced and honestly made. The pour-overs take time and reward patience. Come before 09:00 on a Saturday to claim a stone windowsill seat before Bermondsey Street wakes up: White Cube opens at 10:00, José opens for tapas at noon. This is where the morning begins.',
    hours: 'Mon–Fri 07:00–17:00; Sat–Sun 08:30–17:00',
    tip: 'Saturday before 09:00 for the window seat and the quiet. Pour-over over batch if you have the time. The original branch only — the newer ones are not the same.',
    type: 'Specialty coffee in a Victorian watchhouse',
    website: 'https://watchhouse.com',
  },
  {
    id: 18,
    nbhd: 'borough',
    name: 'José Bermondsey',
    cat: 'food',
    emoji: '🥘',
    address: '104 Bermondsey St, London SE1 3UB',
    lat: 51.5007, lng: -0.0821,
    search: 'José Tapas Bermondsey London',
    note: 'Standing room only, no bookings, a menu of fifteen things and all of them exactly as they should be. José Pizarro opened this counter in 2011 and it remains London\'s closest equivalent to a proper Spanish bar — croquetas that shatter correctly, jamón at the right temperature, grilled prawns with enough char. The sherry list is the finest in London. Arrive at opening or accept the wait.',
    hours: 'Tue–Sat 12:00–22:30; Sun 12:00–16:00; closed Mon',
    tip: 'Opening time or accept a wait. Croquetas first. Ask what sherries they have open.',
    type: 'Spanish tapas bar — standing only, no bookings',
    website: 'https://josepizarro.com/jose-tapas-bar',
  },
  {
    id: 19,
    nbhd: 'borough',
    name: 'White Cube Gallery',
    cat: 'culture',
    emoji: '🖼️',
    address: '144–152 Bermondsey St, London SE1 3TQ',
    lat: 51.5011, lng: -0.0823,
    search: 'White Cube Gallery Bermondsey London',
    note: 'Walk in and the scale hits you before the art does. White walls, poured concrete floor, daylight controlled from above — a space built specifically to show work that cannot fit anywhere smaller. This is where artists come when they are ready for a room that will either justify the work or expose it. Damien Hirst\'s spot paintings covered every wall here simultaneously in 2012. Antony Gormley filled the main hall with cast-iron human forms until the space felt geological. Georg Baselitz hung his paintings upside down from the ceiling and the ceiling was high enough to make it mean something. The shows change every few months and range from quietly devastating to physically overwhelming. Check the website before you come — the current exhibition determines the experience entirely.',
    hours: 'Tue–Sat 10:00–18:00; Sun 12:00–18:00; closed Mon',
    tip: 'Free, no ticket. The main hall is the reason to come — check what is currently installed before visiting. Allow an hour.',
    type: 'Major contemporary art gallery (free)',
    website: 'https://www.whitecube.com',
  },
  {
    id: 20,
    nbhd: 'borough',
    name: 'London Glassblowing',
    cat: 'experience',
    emoji: '🫙',
    address: '62–66 Bermondsey St, London SE1 3UD',
    lat: 51.5009, lng: -0.0831,
    search: 'London Glassblowing Studio Bermondsey',
    note: 'One of Britain\'s longest-running glassblowing studios, on Bermondsey Street since 1976. Watch through the studio windows at any time: the furnaces, the irons, the process. The gallery displays resident and visiting artists\' work. Glassblowing masterclasses — where you make something yourself under a tutor\'s guidance — book weeks ahead and produce a singular London object to take home.',
    hours: 'Mon–Sat 10:00–18:00',
    tip: 'Book a masterclass well ahead — they fill quickly. A working glass object you made yourself travels better than most souvenirs.',
    type: 'Working glassblowing studio & gallery (since 1976)',
    website: 'https://www.londonglassblowing.co.uk',
  },
  {
    id: 21,
    nbhd: 'borough',
    name: 'M. Manze Pie & Mash',
    cat: 'food',
    emoji: '🥧',
    address: '87 Tower Bridge Rd, London SE1 4TW',
    lat: 51.4997, lng: -0.0756,
    search: 'M Manze pie mash London',
    note: 'Operating since 1902 and unchanged since approximately 1930. The tiled Edwardian interior is intact, the dish is the same — minced beef pie, mashed potato, liquor (a green parsley sauce particular to this tradition) — and the prices have not moved far. London\'s oldest surviving pie and mash shop and one of the only places in the city where absolutely nothing has been updated for atmosphere. Cash only, lunchtimes only.',
    hours: 'Mon 11:00–14:00; Tue–Thu 10:30–14:30; Fri 10:00–15:00; Sat 10:00–14:45',
    tip: 'Pie, mash and liquor. Sit in — the room is as interesting as the food. Cash only.',
    type: 'London\'s oldest pie & mash shop (est. 1902)',
    website: 'https://www.manze.co.uk',
  },
  {
    id: 22,
    nbhd: 'borough',
    name: 'The Garrison',
    cat: 'pub',
    emoji: '🍺',
    address: '99–101 Bermondsey St, London SE1 3XB',
    lat: 51.5009, lng: -0.0830,
    search: 'The Garrison pub Bermondsey London',
    note: 'The gastropub that anchored Bermondsey Street\'s character when it opened in 2003 and has remained the neighbourhood\'s social centre ever since. Bare brick, mismatched vintage furniture, good light. The kitchen produces elevated British food without trying too hard about it. The Sunday roast fills months in advance. Saturday breakfast before the market crowd is a reliable start to the best day you can have in south London.',
    hours: 'Mon–Thu 08:00–23:00; Fri–Sat 08:00–midnight; Sun 08:00–22:30',
    tip: 'Sunday roast: book months ahead, not weeks. Saturday breakfast before 10:00 is quieter and just as good.',
    type: 'British gastropub (Bermondsey\'s neighbourhood anchor)',
    website: 'https://thegarrison.co.uk',
  },
  {
    id: 60,
    nbhd: 'borough',
    name: 'St John Restaurant',
    cat: 'food',
    emoji: '🦴',
    address: '26 St John St, Smithfield, London EC1M 4AY',
    lat: 51.5197, lng: -0.1013,
    search: 'St John Restaurant Smithfield London',
    note: 'Fergus Henderson opened St John in a former smokehouse beside Smithfield Market in 1994 and invented a cuisine. Nose-to-tail cooking — every part of the animal treated with equal precision — sounds like a philosophy but here it is simply a menu. The bone marrow and parsley salad on sourdough toast is one of the most consequential dishes in British food history. White walls, no music, no decoration. Nothing is performing except the food, which does so completely.',
    hours: 'Mon–Fri 12:00–15:00, 18:00–22:00; Sat 12:00–15:00, 18:00–22:00',
    tip: 'The bone marrow toast is non-negotiable. Finish with the eccles cake and Lancashire cheese. Book ahead.',
    type: 'The original nose-to-tail British restaurant (since 1994)',
    awards: '⭐ One Michelin Star · Condé Nast Traveller Lifetime Achievement Award (Fergus Henderson, 2024)',
    website: 'https://stjohnrestaurant.com',
  },
  {
    id: 61,
    nbhd: 'borough',
    name: 'Maltby Street Market',
    cat: 'market',
    emoji: '🧺',
    address: 'Maltby St, Bermondsey, London SE1 3PA',
    lat: 51.5007, lng: -0.0822,
    search: 'Maltby Street Market Bermondsey London',
    note: 'Under the railway arches on Maltby Street at weekends — this is what Borough Market was before it became what it is now. A fraction of the crowds, better prices, and producers who are often more interesting than their Borough neighbours. Oysters, charcuterie, cheese, natural wine, fresh pasta. Come here instead of Borough on weekends and tell no one.',
    hours: 'Sat 09:00–16:00; Sun 11:00–16:00',
    tip: 'Come here instead of Borough Market on weekends. The oyster stall and the natural wine bar under the arches are the starting points.',
    type: 'Artisan street food market under railway arches',
    website: 'https://maltbystreet.com',
  },

  // ── THE CITY ──────────────────────────────────────────────────────────────

  {
    id: 23,
    nbhd: 'city',
    name: 'Tower Bridge',
    cat: 'experience',
    emoji: '🌉',
    address: 'Tower Bridge Rd, London SE1 2UP',
    lat: 51.5055, lng: -0.0754,
    search: 'Tower Bridge London',
    note: 'The bascule bridge took eight years to build and opened in 1894. The City of London insisted it be clad in stone — Cornish granite and Portland stone over a steel frame — because an industrial structure at this location was considered unacceptable. The result is one of the most recognisable silhouettes in the world. It still raises for river traffic around 800 times a year: two counterweights of 1,000 tonnes each swing upward, the roadway parts, and the whole operation takes three minutes. Lift times are published on the website 24 hours ahead and watching from the north or south embankment costs nothing. The paid attraction includes the glass-floored high walkways 42 metres above the water and the Victorian steam engine rooms below, where the original hydraulic machinery that powered the lifts is preserved intact and still extraordinary. The best photograph: south bank at dusk, looking northeast — bridge framing the lit towers of the City behind it.',
    hours: 'Daily 09:30–17:30',
    tip: 'Check lift times online the day before. The Victorian engine rooms are the underrated half of the paid ticket. Best photographed from the south bank at dusk.',
    type: 'Victorian bascule bridge (1894)',
    website: 'https://www.towerbridge.org.uk',
  },
  {
    id: 24,
    nbhd: 'city',
    name: 'Tower of London',
    cat: 'culture',
    emoji: '🏰',
    address: 'St Katharine\'s & Wapping, London EC3N 4AB',
    lat: 51.5081, lng: -0.0760,
    search: 'Tower of London',
    note: 'Almost a thousand years of continuous use — palace, prison, mint, armoury — on the same half-mile of riverbank. Most visitors go straight to the Crown Jewels and miss what is actually interesting: Traitors\' Gate at river level, the medieval White Tower, the Scaffold Site on Tower Green where Anne Boleyn was executed and the ground is still marked. Join a Yeoman Warder tour immediately on arrival — they leave from the gate hourly, they are the finest free guided experience in London, and the stories do not appear in any guidebook. The Ceremony of the Keys happens every night at 21:53, uninterrupted since the 14th century, free to attend but requiring a booking months in advance.',
    hours: 'Tue–Sat 09:00–17:30; Sun–Mon 10:00–17:30',
    tip: 'Join a Yeoman Warder tour the moment you arrive. The Scaffold Site and Traitors\' Gate, not only the Jewel House. Ceremony of the Keys: book months ahead, worth every effort.',
    type: 'Historic royal fortress & UNESCO World Heritage Site',
    website: 'https://www.hrp.org.uk/tower-of-london',
  },
  {
    id: 25,
    nbhd: 'city',
    name: 'Sky Garden',
    cat: 'nature',
    emoji: '🌿',
    address: '1 Sky Garden Walk, London EC3M 8AF',
    lat: 51.5111, lng: -0.0838,
    search: 'Sky Garden London Walkie Talkie',
    note: 'The Walkie Talkie is one of the most controversial buildings in London — in 2013 its curved glass facade concentrated sunlight onto the street below and melted parked cars. The free public garden on its top three floors is the building\'s partial atonement, and it is extraordinary. Subtropical planting, a bar, a restaurant, and exterior terraces at 155 metres that give an unobstructed 360-degree view: Canary Wharf banking to the east, Tower Bridge almost directly below, St Paul\'s dome at eye level to the west, the green smear of the parks beyond. Free tickets must be booked in advance on the website, which is the detail that keeps it genuinely uncrowded — most London viewpoints charge £30 and still have queues. Book an evening slot in clear weather, arrive before sunset and stay as the City lights come on beneath you.',
    hours: 'Mon–Fri 10:00–18:00; Sat–Sun 11:00–21:00',
    tip: 'Book online ahead — free but limited. Evening slots on clear days, arrive before sunset. The exterior terrace is the destination.',
    type: 'Free 35th-floor public garden & 360° viewpoint',
    website: 'https://skygarden.london',
  },
  {
    id: 26,
    nbhd: 'city',
    name: 'Leadenhall Market',
    cat: 'market',
    emoji: '🏛️',
    address: 'Gracechurch St, London EC3V 1LT',
    lat: 51.5135, lng: -0.0831,
    search: 'Leadenhall Market London',
    note: 'A Victorian covered market in the heart of the City, built in 1881 on a site with a market since the 14th century. The painted ornamental ironwork — burgundy, green and cream — creates one of the most theatrical interiors in London. On weekday mornings, City workers pressing through for coffee in the low amber light create an atmosphere in which the 19th century feels closer than usual. Harry Potter chose it for Diagon Alley for good reason.',
    hours: 'Mon–Fri 10:00–18:00; pubs open longer',
    tip: 'Weekday mornings for the authentic atmosphere. Completely empty at weekends.',
    type: 'Ornate Victorian covered market (1881)',
    website: 'https://leadenhallmarket.co.uk',
  },
  {
    id: 27,
    nbhd: 'city',
    name: 'Duck and Waffle',
    cat: 'food',
    emoji: '🧇',
    address: '110 Bishopsgate, London EC2N 4AY',
    lat: 51.5142, lng: -0.0820,
    search: 'Duck and Waffle restaurant London',
    note: 'Open 24 hours on the 40th floor of Heron Tower, floor-to-ceiling windows, the full sweep of the City and Thames below. The signature dish — confit duck leg on a Belgian waffle with a fried duck egg and mustard maple syrup — sounds improbable and tastes inevitable. A sunrise booking at 06:30 is one of London\'s most dramatically staged breakfasts: the city waking below you, the room quieter than at any other hour.',
    hours: 'Open 24/7',
    tip: 'Book a sunrise slot weeks ahead — 06:30 means quiet room, extraordinary light. The duck and waffle is non-negotiable.',
    type: '24-hour restaurant with 40th-floor City views',
    website: 'https://duckandwaffle.com',
  },
  {
    id: 28,
    nbhd: 'city',
    name: 'St Paul\'s Cathedral',
    cat: 'church',
    emoji: '⛪',
    address: 'St. Paul\'s Churchyard, London EC4M 8AD',
    lat: 51.5138, lng: -0.0984,
    search: 'St Paul\'s Cathedral London',
    note: 'The medieval cathedral on this site burned for four days in the Great Fire of 1666. Wren spent 35 years designing and building this one, and is buried in the crypt beneath it. His son wrote the epitaph carved above the crypt entrance: Lector, si monumentum requiris, circumspice — Reader, if you seek his monument, look around you. The interior is one of the most perfectly proportioned spaces in Europe: the dome rises to 111 metres and the quality of the light changes completely with the hour and season. The climb is 528 steps and comes in three stages. The Whispering Gallery is the first stop — inside the dome, whisper into the curved wall and the words carry intact through the still air to someone on the far side 34 metres away. The Stone Gallery is outside at mid-height, exposed to the city. The Golden Gallery at the summit opens the full Thames basin: east to Canary Wharf, west toward the parks, the dome you climbed curving away below your feet.',
    hours: 'Mon–Sat 08:30–16:30',
    tip: 'The Whispering Gallery stop is not optional. Go early on a weekday — the climb is peaceful before the tourist groups start. The crypt is underrated: Wellington and Nelson are both buried there.',
    type: 'Baroque cathedral (Wren, 1710)',
    website: 'https://www.stpauls.co.uk',
  },
  {
    id: 62,
    nbhd: 'city',
    name: 'The Barbican',
    cat: 'culture',
    emoji: '🏗️',
    address: 'Silk Street, Barbican, London EC2Y 8DS',
    lat: 51.5203, lng: -0.0928,
    search: 'Barbican Centre London arts complex',
    note: 'Built on a bomb site left by the Blitz and completed in the 1970s after two decades of construction, the Barbican is the largest brutalist residential complex in Europe and one of London\'s most argued-about buildings. Three towers, 2,000 flats, two theatres, a concert hall, two cinemas, a gallery and an arts centre — all connected by a raised network of walkways, podium gardens, an ornamental lake and a heated glass conservatory growing tropical plants in the middle of the City of London. The estate is disorienting by design: the walkways do not go where you expect, the courtyards open unexpectedly onto water, and the residential gardens between the towers are some of the quietest places in the square mile. Come without a plan. Take the elevated walkways above street level. Find the lakeside terrace. The conservatory opens free on Sundays and is one of the most genuinely strange and beautiful spaces in London.',
    hours: 'Public walkways from 06:00; arts centre 11:00–23:00',
    tip: 'Go without a plan and follow the walkways. The conservatory is free on Sundays — it is worth the trip on its own. Check the arts centre programme: the resident London Symphony Orchestra is one of the finest in the world.',
    type: 'Brutalist arts complex & residential estate (free to explore)',
    website: 'https://www.barbican.org.uk',
  },

  // ── COVENT GARDEN & SOHO ──────────────────────────────────────────────────

  {
    id: 75,
    nbhd: 'covent-garden',
    name: 'American Bar at The Savoy',
    cat: 'pub',
    emoji: '🥂',
    address: 'The Savoy, Strand, London WC2R 0EU',
    lat: 51.5104, lng: -0.1203,
    search: 'American Bar Savoy Hotel London cocktail',
    note: 'The most historically significant drinking room in London. Harry Craddock wrote the Savoy Cocktail Book here in 1930 — a volume that defined cocktail culture for a century. The Hanky Panky was invented at this bar in 1925. The Art Deco interior completed in 1927 is largely intact. The Corpse Reviver #2 from Craddock\'s original recipe is the correct order. The piano starts at 19:30 and the service maintains standards that most modern cocktail bars treat as aspirational.',
    hours: 'Mon–Sat 14:00–00:00; Sun 14:00–23:00',
    tip: 'The Corpse Reviver #2 from Craddock\'s original recipe. Book ahead — the bar fills completely at weekends. The piano begins at 19:30.',
    type: 'Historic hotel bar — the birthplace of modern cocktail culture (1893)',
    website: 'https://www.thesavoylondon.com/restaurant/american-bar/',
  },
  {
    id: 29,
    nbhd: 'covent-garden',
    name: 'Covent Garden',
    cat: 'market',
    emoji: '🌹',
    address: 'Covent Garden, London WC2E 8RF',
    lat: 51.5117, lng: -0.1232,
    search: 'Covent Garden London',
    note: 'The wholesale market that supplied London\'s restaurants for 300 years — saved from demolition in 1974 by one of the first successful community preservation campaigns in Britain. The main piazza is the tourists\' London; the streets around it hold more. Cecil Court, one block west — a pedestrianised Edwardian alley of antiquarian booksellers, print dealers and map specialists — has barely changed since the 1920s. The Amphitheatre Restaurant at the Royal Opera House is open for breakfast, lunch and dinner whether or not you are attending a performance; the terrace above Bow Street is one of the least known good views in the neighbourhood. Seven Dials, five minutes north, is the serious independent shopping destination. Neal\'s Yard is through the alley off Short\'s Gardens.',
    hours: 'Piazza 24h; shops Mon–Sat 10:00–20:00; Sun 11:00–18:00',
    tip: 'Cecil Court for prints and maps — specific and remarkable. The ROH Amphitheatre bar for a drink with a view. Neal\'s Yard for the cheese. Seven Dials for the shopping.',
    type: 'Historic market piazza — use the streets around it, not only the square',
    website: 'https://www.coventgarden.london',
  },
  {
    id: 30,
    nbhd: 'covent-garden',
    name: 'Neal\'s Yard',
    cat: 'shop',
    emoji: '🌈',
    address: 'Neal\'s Yard, Covent Garden, London WC2H 9DP',
    lat: 51.5128, lng: -0.1262,
    search: 'Neal\'s Yard Covent Garden London',
    note: 'A tiny courtyard hidden behind Covent Garden, accessible only through narrow alleys off Neal Street, with buildings painted in clashing vivid colours. Neal\'s Yard Dairy in the corner is the finest British farmhouse cheese shop in the world — they age whole wheels in their Bermondsey cellar and the staff can tell you the exact farm, the current age, the reason to eat it now. Ask what\'s in best condition today and trust the answer entirely.',
    hours: 'Shops Mon–Sat 10:00–18:00',
    tip: 'Enter from Shorts Gardens or Neal Street. Ask the staff at Neal\'s Yard Dairy what\'s at its peak today. Buy more than you think you need.',
    type: 'Hidden courtyard & world-class British cheese shop',
    website: 'https://www.nealsyard.co.uk',
  },
  {
    id: 31,
    nbhd: 'covent-garden',
    name: 'Clos Maggiore',
    cat: 'food',
    emoji: '🌸',
    address: '33 King St, Covent Garden, London WC2E 8JD',
    lat: 51.5118, lng: -0.1243,
    search: 'Clos Maggiore restaurant Covent Garden London',
    note: 'The conservatory is the reason to come, and you should say so clearly when you book. Twelve covers under a retractable glass roof with cherry blossom branches trailing overhead, candles on every table, the branches close enough to touch on warm evenings when the roof slides back. It is the most romantic dining room in London by the consistent verdict of everyone who eats there and refuses to stop talking about it afterward. The French cooking is serious — precisely sourced, technically disciplined — and earns its setting rather than hiding behind it. The set lunch on a weekday delivers the same kitchen at half the dinner price in a room that is quieter and, if anything, more beautiful in afternoon light. Book the conservatory table specifically, in writing if possible, weeks ahead for weekends.',
    hours: 'Mon–Sat 12:00–14:30, 17:00–23:00; Sun 12:00–15:30, 17:00–22:00',
    tip: 'Specify the conservatory when booking — the dining room is good but not the point. Set lunch on a Tuesday or Wednesday for the quietest and most atmospheric version of this room.',
    type: 'French restaurant — London\'s most romantic dining room',
    awards: '3 AA Rosettes (2026) · Wine Spectator Grand Award (2025) · \'Most romantic restaurant in the world\' — Architectural Digest',
    website: 'https://www.closmaggiore.com',
  },
  {
    id: 32,
    nbhd: 'covent-garden',
    name: 'Barrafina',
    cat: 'food',
    emoji: '🦐',
    address: '10 Adelaide St, London WC2N 4HZ',
    lat: 51.5097, lng: -0.1239,
    search: 'Barrafina tapas London',
    note: 'Counter seating only, no reservations, kitchen completely open. Barrafina has been the benchmark for Spanish cooking in London since 2007 — the tortilla, the grilled fish, the cuttlefish, the jamón. The chefs know what\'s exceptional today and will tell you if you ask. Stand across the road and wait for a counter seat to open. It is always worth it.',
    hours: 'Mon–Sat 12:00–15:00, 17:00–23:00; Sun 13:00–15:30, 17:00–22:00',
    tip: 'Walk-in only. Arrive before opening or accept the wait. Sit at the counter and ask the chefs what they recommend today.',
    type: 'Acclaimed Spanish counter restaurant',
    website: 'https://barrafina.co.uk',
  },
  {
    id: 33,
    nbhd: 'covent-garden',
    name: 'Mr Fogg\'s Gin Parlour',
    cat: 'pub',
    emoji: '🍸',
    address: '1 New Row, London WC2N 4EA',
    lat: 51.5110, lng: -0.1241,
    search: 'Mr Fogg\'s Gin Parlour London',
    note: 'Down a staircase off New Row into a Victorian basement dressed as the private study of a 19th-century explorer: taxidermy, globes, butterfly specimens pinned in cases, shelves of leather-bound books, trunks and instruments on every surface. The inventory is over 300 gins organised by region and distillery, and the bartenders know it the way a good sommelier knows a cellar — they will ask what you are in the mood for and bring you something you would not have chosen yourself. The room holds perhaps 40 people and feels full at 20, which means it always has atmosphere and always requires booking.',
    hours: 'Mon–Thu 15:00–midnight; Fri–Sat 12:00–01:00; Sun 12:00–midnight',
    tip: 'Book ahead — the room is small and fills quickly. Ask for recommendations from lesser-known distilleries. The bartenders have strong opinions.',
    type: 'Victorian gin parlour (300+ gins)',
    website: 'https://mr-foggs.com/gin-parlour',
  },
  {
    id: 34,
    nbhd: 'covent-garden',
    name: 'St Paul\'s Covent Garden',
    cat: 'church',
    emoji: '⛪',
    address: 'Bedford St, Covent Garden, London WC2E 9ED',
    lat: 51.5116, lng: -0.1231,
    search: 'St Paul\'s Church Covent Garden London',
    note: 'Inigo Jones built this in 1633 and oriented it backwards — the imposing portico faces the piazza but is not the entrance. It has been the Actors\' Church since the Restoration: Vivien Leigh, Charlie Chaplin, Noel Coward are all commemorated inside. The garden is a genuinely quiet escape from the piazza ten metres away. The portico steps are where the best street performers set up, using the acoustic overhang.',
    hours: 'Mon–Fri 08:30–17:00; Sun service 11:00',
    tip: 'Free entry. The memorial plaques inside are worth reading slowly. The garden through the side entrance.',
    type: 'The Actors\' Church (Inigo Jones, 1633)',
    website: 'https://www.actorschurch.org',
  },
  {
    id: 35,
    nbhd: 'covent-garden',
    name: 'Ronnie Scott\'s Jazz Club',
    cat: 'pub',
    emoji: '🎷',
    address: '47 Frith St, Soho, London W1D 4HT',
    lat: 51.5133, lng: -0.1314,
    search: 'Ronnie Scott\'s Jazz Club London',
    note: 'Ronnie Scott opened this basement on Frith Street in 1959 with £100 borrowed from a friend. Miles Davis played here. Nina Simone called it a second home. The room holds 250 and feels intimate regardless of who is on. The late-night sets that begin around 23:30 after the headline act — often more spontaneous and cheaper — are sometimes better than the show that preceded them.',
    hours: 'Mon–Sat 18:00–03:00; Sun 18:00–midnight',
    tip: 'Book for headline acts. The late session starts around 23:30, after the main show — cheaper, more spontaneous and often the best thing in the room.',
    type: 'World-famous jazz club (since 1959)',
    website: 'https://www.ronniescotts.co.uk',
  },
  {
    id: 36,
    nbhd: 'covent-garden',
    name: 'Quo Vadis',
    cat: 'food',
    emoji: '🦞',
    address: '26–29 Dean St, Soho, London W1D 3LL',
    lat: 51.5130, lng: -0.1320,
    search: 'Quo Vadis restaurant Soho London Jeremy Lee',
    note: 'Karl Marx lived in this building from 1851 to 1856 — a plaque on the front wall marks it, which tells you something about how long Soho has been absorbing history without making a fuss. Jeremy Lee\'s kitchen is one of the most admired in London: seasonal British cooking with Mediterranean intelligence, never performative, always exactly right. The smoked eel sandwich at the bar is one of the great small London dishes. Book the dining room for dinner; the bar counter takes walk-ins and is worth visiting in its own right.',
    hours: 'Mon–Sat 12:00–15:00, 17:30–23:00; closed Sun',
    tip: 'Book the dining room ahead. The smoked eel sandwich at the bar is the correct first order. Tuesday through Thursday is quieter than the weekend.',
    type: 'Soho institution — seasonal British cooking (Jeremy Lee)',
    website: 'https://quovadissoho.co.uk',
  },
  {
    id: 37,
    nbhd: 'covent-garden',
    name: 'Opium Cocktail Bar',
    cat: 'pub',
    emoji: '🍵',
    address: '15–16 Gerrard St, London W1D 6JE',
    lat: 51.5119, lng: -0.1306,
    search: 'Opium cocktail bar Chinatown London',
    note: 'The door is on Gerrard Street in the middle of Chinatown, unmarked except for a small brass plate. Ring the bell, climb four flights past red silk lanterns and walls of dark lacquered timber, and arrive in a bar that the 1920s Shanghai of your imagination would have looked like. Three floors: low lighting, warm wood, the smell of gardenia and warm spirits. The cocktails draw on Japanese whisky, Chinese baijiu, Taiwanese gin and Korean makgeolli in combinations that read as improbable on the menu and make complete sense in the glass. On weekends a performer takes the upper level — a Peking opera singer, a close-up magician, a jazz duo — and the evenings take on a surreal quality that nothing else in central London replicates. Arrive early on a Friday, settle in and drink slowly.',
    hours: 'Mon–Tue 17:00–01:00; Wed–Thu 17:00–02:00; Fri–Sat 17:00–03:00; Sun 17:00–midnight',
    tip: 'Book ahead for weekends. The Dragon (dragon fruit, Sichuan pepper) is the house signature. Ask about whatever spirit the bar manager is currently obsessed with.',
    type: '1920s Shanghai cocktail bar above Chinatown',
    website: 'https://www.opiumchinatown.com',
  },
  {
    id: 38,
    nbhd: 'covent-garden',
    name: 'Bob Bob Ricard',
    cat: 'food',
    emoji: '🍾',
    address: '1 Upper James St, Soho, London W1F 9DF',
    lat: 51.5124, lng: -0.1389,
    search: 'Bob Bob Ricard restaurant London',
    note: 'A Soho brasserie built around one brilliant conceit: a Press for Champagne button at every leather booth, connected directly to the bar. The room — lacquered blue and gold, mirrored ceilings — is as glamorous as that implies. The food is a serious take on British and Russian brasserie classics. Press the button. Order the beef Wellington. That is the correct evening.',
    hours: 'Daily 12:30–15:00, 18:00–23:30',
    tip: 'Book ahead. Press the button. The beef Wellington is the kitchen\'s signature. Budget from £70 per person.',
    type: 'Theatrical brasserie with champagne button at every table',
    website: 'https://bobbobricard.com',
  },
  {
    id: 72,
    nbhd: 'covent-garden',
    name: 'Rules',
    cat: 'food',
    emoji: '🍮',
    address: '35 Maiden Lane, Covent Garden, London WC2E 7LB',
    lat: 51.5115, lng: -0.1237,
    search: 'Rules restaurant Covent Garden London oldest',
    note: 'Established in 1798, London\'s oldest restaurant — still on the same Maiden Lane site, still serving British game from the restaurant\'s own Teesdale estate, still decorated with the theatrical portraits and cartoons accumulated across 225 years. Dickens was a regular. Graham Greene wrote here. The potted shrimps, the roast grouse in season, the suet puddings: this is the cooking of British history served in a room that witnessed most of it.',
    hours: 'Mon–Sat 12:00–23:30; Sun 12:00–22:30',
    tip: 'Order game — it is what this kitchen has done for 225 years. Potted shrimps to start. A suet pudding to finish. Book ahead for weekends.',
    type: 'London\'s oldest restaurant (established 1798)',
    website: 'https://rules.co.uk',
  },
  {
    id: 69,
    nbhd: 'covent-garden',
    name: 'The Palomar',
    cat: 'food',
    emoji: '🫙',
    address: '34 Rupert St, Soho, London W1D 6DN',
    lat: 51.5121, lng: -0.1326,
    search: 'The Palomar restaurant Soho London Jerusalem',
    note: 'The cooking draws on Jerusalem and the whole Eastern Mediterranean — the spice routes, the Ottoman inheritance, the Levantine coast — and at its best it is some of the most interesting food in London. The Jerusalem-style hummus arrives warm and silky with a pool of cold-pressed olive oil and a handful of spiced chickpeas on top; it is one of the finest plates of food in the city and costs under £10. The lamb neck is slow-cooked until it pulls apart under a fork, layered with burned yogurt and sweet charred onion. The raw fish changes each day and is always worth asking about. Counter seats at the open kitchen pass are where the room comes alive — the chefs explain every dish as it comes up, the kitchen runs at full speed and the energy concentrates at those seats in a way the dining room behind cannot match. Book ahead for the dining room; try the counter walk-in at lunch.',
    hours: 'Mon–Sat 12:00–14:30, 17:30–22:30; Sun 12:00–15:30',
    tip: 'Counter seats at the pass, if available. The hummus first, then the lamb neck. Ask what raw fish is on today.',
    type: 'Jerusalem & Eastern Mediterranean restaurant',
    website: 'https://www.thepalomar.co.uk',
  },
  {
    id: 70,
    nbhd: 'covent-garden',
    name: 'Hoppers',
    cat: 'food',
    emoji: '🥣',
    address: '49 Frith St, Soho, London W1D 4SG',
    lat: 51.5131, lng: -0.1312,
    search: 'Hoppers restaurant Soho London Sri Lankan',
    note: 'Sri Lanka\'s street breakfast brought to a Soho basement. The hopper itself — fermented rice and coconut batter cooked in a small wok until the edges crisp and the centre stays soft and yielding — arrives with a fried egg in the middle, three chutneys and a spoon. It is one of the most complete small meals in London. The bone marrow varuval is slow-roasted with Jaffna spices until the marrow loosens and the bone darkens; you eat it with bread and feel like you have discovered something. The kottu roti is shredded flatbread cooked on a flat iron with egg, vegetables and curry sauce — the sound of the cleavers working the iron carries from the kitchen across the room. Counter seats facing the pass are the ones to ask for. The room is tight, warm and loud in the way that kitchens cooking at full stretch always are. Book for dinner; walk in for a weekday lunch.',
    hours: 'Mon–Sat 12:00–14:30, 17:30–22:30; closed Sun',
    tip: 'Counter seats facing the kitchen. Egg hopper first, then the bone marrow varuval. The house chai at the end is non-negotiable.',
    type: 'Sri Lankan restaurant — hoppers & kottu specialists',
    website: 'https://www.hopperslondon.com',
  },
  {
    id: 68,
    nbhd: 'covent-garden',
    name: 'The French House',
    cat: 'pub',
    emoji: '🥂',
    address: '49 Dean St, Soho, London W1D 5BG',
    lat: 51.5130, lng: -0.1330,
    search: 'French House Soho London pub Dean Street',
    note: 'The most historically layered drinking room in Soho. De Gaulle used this as the informal London headquarters of the Free French in the Second World War — Resistance fighters, exiles and refugees drank here while London burned. After the war: Dylan Thomas, Francis Bacon, Lucian Freud made it their own. The house rules have not changed: wine and spirits only, and — uniquely for a London pub — no pints, only halves. The room is small, crowded and exactly right. Upstairs, the restaurant run by Margot Henderson (also behind Rochelle Canteen) serves one of the most interesting lunch menus in Soho.',
    hours: 'Mon–Sat 12:00–23:00; Sun 12:00–22:30',
    tip: 'The half-pint rule is non-negotiable — order wine instead. Book the restaurant upstairs for lunch. The bar is walk-in; arrive before 19:00 for space.',
    type: 'Soho institution — the Free French HQ in WWII (est. 1891)',
    website: 'https://frenchhousesoho.com',
  },

  // ── CAMDEN & KING\'S CROSS ─────────────────────────────────────────────────

  {
    id: 67,
    nbhd: 'camden',
    name: 'Coal Drops Yard',
    cat: 'experience',
    emoji: '🏗️',
    address: 'Stable St, King\'s Cross, London N1C 4AB',
    lat: 51.5357, lng: -0.1238,
    search: 'Coal Drops Yard King\'s Cross London shopping',
    note: 'Two Victorian coal drops from the 1850s, converted by Thomas Heatherwick into a shopping and restaurant destination that opened in 2018. The engineering drama is overhead: the two Victorian iron roofs arch together and touch at the apex, creating a covered outdoor yard unlike anything else in London. Independent boutiques — Paul Smith, Tom Dixon, Wolf & Badger, Aesop — sit beside serious restaurants. Cross the canal from Granary Square and find it behind the fountains. The building alone justifies the walk.',
    hours: 'Shops Mon–Sat 10:00–20:00; Sun 11:00–18:00; restaurants vary',
    tip: 'Walk through at dusk when the roofline is lit. The Barrafina branch here tends to have shorter queues than the Adelaide Street original — try for a counter seat at lunch.',
    type: 'Heatherwick-designed Victorian coal drops — boutiques & restaurants',
    website: 'https://coaldropsyard.com',
  },
  {
    id: 40,
    nbhd: 'camden',
    name: 'Wellcome Collection',
    cat: 'culture',
    emoji: '🔬',
    address: '183 Euston Rd, London NW1 2BE',
    lat: 51.5258, lng: -0.1320,
    search: 'Wellcome Collection museum London',
    note: 'Sir Henry Wellcome was a pharmaceutical millionaire who spent his fortune buying objects that interested him at the intersection of medicine, science, death and human experience. The permanent collection is unlike anything else in London: Napoleon\'s toothbrush, Darwin\'s walking stick, a 2,000-year-old Egyptian mummy\'s hair, Roman surgical instruments that still look functional, a 15th-century Italian ivory anatomical figure, shrunken heads, Victorian electroshock equipment, a complete 18th-century apothecary\'s dispensary. They are displayed without hierarchy and without sentimentality — a medieval chastity belt next to a contemporary HIV medication, both treated as equally serious objects. The museum\'s refusal to arrange human experience into comfortable categories gives it a quality most institutions cannot manufacture. The temporary exhibitions are consistently the most rigorously thought through in London. It is entirely free, chronically undervisited, and two hours is not enough.',
    hours: 'Tue–Wed, Fri–Sat 10:00–18:00; Thu 10:00–20:00; Sun 11:00–18:00; closed Mon',
    tip: 'Free always. Thursday evenings for the quietest visit. Allow three hours and follow whatever holds your attention — the permanent collection rewards slow looking.',
    type: 'Free museum at the intersection of medicine, science & art',
    website: 'https://wellcomecollection.org',
  },
  {
    id: 41,
    nbhd: 'camden',
    name: 'The Roundhouse',
    cat: 'culture',
    emoji: '🎶',
    address: 'Chalk Farm Rd, London NW1 8EH',
    lat: 51.5435, lng: -0.1466,
    search: 'Roundhouse Camden London concert venue',
    note: 'The engine shed was built in 1847 to rotate steam locomotives too large to reverse — a circular track inside the building turned them for the return journey. By 1869 the engines had grown too wide for the building and it sat empty until the 1960s, when Arnold Wesker and Charles Marowitz staged the first Happening in Britain inside it and changed what the space was for. Pink Floyd played some of their earliest London shows here. The Doors played their only UK performance on this stage. Led Zeppelin recorded live here. The circular form does something that rectangular halls simply cannot: the stage sits in the round and the distance from any seat to the performance feels closer than the geometry suggests, because you are never looking at a back wall, only at each other and what is happening in the centre. The programme now runs from the RSC to avant-garde electronic artists to major touring acts. There is almost always something worth seeing.',
    hours: 'Event-dependent; café open daily',
    tip: 'Check the programme before your trip at roundhouse.org.uk. The Victorian brick exterior rising above Chalk Farm Road is worth a photograph regardless.',
    type: 'Victorian circular live music venue (since 1966)',
    website: 'https://www.roundhouse.org.uk',
  },
  {
    id: 42,
    nbhd: 'camden',
    name: 'German Gymnasium',
    cat: 'food',
    emoji: '🥩',
    address: '1 King\'s Blvd, King\'s Cross, London N1C 4BU',
    lat: 51.5308, lng: -0.1200,
    search: 'German Gymnasium restaurant King\'s Cross London',
    note: 'Built in 1865 as Britain\'s first purpose-built gymnasium, specifically to prepare athletes for the 1866 Olympics. The ceiling is original Victorian ironwork at 15 metres. The wraparound gallery — from which spectators once watched gymnasts below — still has its viewing rails. The room does all the decorating. The kitchen cooks Central European with the confidence of somewhere that has nothing to prove: wiener schnitzel pounded thin, pan-fried until it blisters from the meat, served with lemon and anchovy butter; slow-braised red cabbage; sauerkraut made in-house; dumplings. Weekend brunch is a specific pleasure — eggs and good bread in a Victorian sports hall, the arched windows sending morning light across 160 years of stripped wood and iron.',
    hours: 'Mon–Fri 07:00–23:00; Sat–Sun 08:00–23:00',
    tip: 'The wiener schnitzel. Weekend brunch before 10:00 for the light and the quiet. Book ahead for dinner.',
    type: 'Continental brasserie in a Victorian gymnasium (1865)',
    website: 'https://www.germangymnasium.com',
  },

  // ── NOTTING HILL ──────────────────────────────────────────────────────────

  {
    id: 43,
    nbhd: 'notting-hill',
    name: 'Portobello Road Market',
    cat: 'market',
    emoji: '🎨',
    address: 'Portobello Rd, Notting Hill, London W11',
    lat: 51.5163, lng: -0.2033,
    search: 'Portobello Road Market Notting Hill London',
    note: 'Over a mile of stalls through Notting Hill. On Saturdays, over 1,000 antique dealers occupy the southern section — the world\'s largest antique street market. The middle section runs fruit, vegetables and street food all week. The northern end under the Westway flyover has the most interesting vintage clothing with half the crowds. The surrounding pastel-painted terraces are what separates Notting Hill from every other London market neighbourhood.',
    hours: 'Antiques: Sat 08:00–19:00; General market: Mon–Fri 09:00–18:00',
    tip: 'Arrive before 09:00 on Saturdays for antiques. The northern end under the Westway has the best vintage and is far less crowded than the tourist end.',
    type: 'World\'s largest antique street market',
    website: 'https://www.portobelloroad.co.uk',
  },
  {
    id: 44,
    nbhd: 'notting-hill',
    name: 'Core by Clare Smyth',
    cat: 'food',
    emoji: '⭐',
    address: '92 Kensington Park Rd, London W11 2PN',
    lat: 51.5176, lng: -0.2007,
    search: 'Core by Clare Smyth restaurant Notting Hill',
    note: 'Clare Smyth became the first woman in the UK to hold three Michelin stars in her own name. The cooking is built around British produce treated with the rigour of French classical technique, and the results are consistently described as some of the most precise food being made in the country. The signature potato and roe dish — a single perfect potato slow-cooked in beef fat until the skin lacquers, topped with herring roe and coastal herbs — is simultaneously the simplest and the most technically accomplished thing on the menu, and it has been written about by food critics who do not usually find themselves writing about vegetables. The full tasting menu runs fourteen courses and takes the better part of three hours. The set lunch at £75 delivers the same kitchen, the same sourcing and the same level of care at considerably lower cost — it is one of the best-value serious lunches in London. Book weeks ahead.',
    hours: 'Tue–Sat 12:00–14:00, 18:30–22:00; closed Sun–Mon',
    tip: 'The set lunch is the right entry point — same kitchen, same sourcing, half the dinner price. Book weeks ahead. The wine pairings are serious and worth it.',
    type: 'Three Michelin-star restaurant',
    awards: '⭐⭐⭐ Three Michelin Stars · 5 AA Rosettes · La Liste 98/100 (2025) · World\'s 50 Best #71 (2023)',
    website: 'https://corebyclaresmyth.com',
  },
  {
    id: 45,
    nbhd: 'notting-hill',
    name: 'Luna Rossa',
    cat: 'food',
    emoji: '🍝',
    address: '192 Kensington Park Rd, London W11 2ES',
    lat: 51.5163, lng: -0.2038,
    search: 'Luna Rossa Italian restaurant Notting Hill London',
    note: 'On Kensington Park Road where the houses are painted white and the plane trees meet overhead, this small Italian has been feeding the same neighbourhood for long enough that the regulars greet the waiters by name. The pasta is made each morning. The carbonara is made correctly: guanciale, not bacon; aged pecorino, not parmesan; the egg yolk left slightly loose, no cream anywhere near the pan. The cacio e pepe has the right amount of pepper, which is more than you expect. The tiramisu comes in a deep ceramic dish, heavily soaked in espresso, and is the version you will compare other tiramisus against. The room is small, warm and unhurried. The service knows when you want another glass without asking.',
    hours: 'Mon 18:00–23:30; Tue–Fri 12:00–16:00, 18:00–23:30; Sat 11:30–23:30; Sun 12:00–22:30',
    tip: 'Book ahead — it fills. Carbonara or cacio e pepe, then the tiramisu. The house wine is reliable and fairly priced.',
    type: 'Traditional Italian neighbourhood restaurant',
    phone: '+44 20 7229 0482',
  },
  {
    id: 46,
    nbhd: 'notting-hill',
    name: 'Kalamaras Greek Taverna',
    cat: 'food',
    emoji: '🧆',
    address: '66 Inverness Mews, London W2 3JQ',
    lat: 51.5172, lng: -0.1955,
    search: 'Kalamaras Greek Taverna Notting Hill London',
    note: 'Turn off Bayswater Road into Inverness Mews — a short cobbled lane of Victorian stable buildings that time has largely left alone — and follow it to the end. Kalamaras has been in this basement since 1966. The room is low-ceilinged, candlelit and decorated as Greek restaurants were decorated before anyone thought about interior design: whitewashed walls, terracotta, old wine jugs, photographs of islands. The taramasalata is made in-house — ivory-coloured, smoky and intensely savoury, nothing like the pink version sold in supermarkets. The whole sea bass arrives grilled over charcoal with olive oil and lemon. The lamb shoulder has been slow-roasting for hours and pulls apart without effort. The wine is Greek and the owner will point you toward something good. Order mezze first, then fish or lamb, and take your time. This is a room that rewards unhurried evenings.',
    hours: 'Daily 17:00–22:30',
    tip: 'Booking essential. Taramasalata and mezze to begin, then the whole sea bass or the lamb shoulder. The owner\'s wine recommendation is worth following.',
    type: 'Traditional Greek taverna (since 1966)',
    phone: '+44 20 7727 9122',
  },
  {
    id: 47,
    nbhd: 'notting-hill',
    name: 'Electric Cinema',
    cat: 'experience',
    emoji: '🎬',
    address: '191 Portobello Rd, Notting Hill, London W11 2ED',
    lat: 51.5161, lng: -0.2007,
    search: 'Electric Cinema Notting Hill London',
    note: 'Opened in 1910, making it one of Britain\'s oldest working cinemas, and still the most comfortable in London. Leather sofas, footstools, armchairs and a full bar service that runs throughout. Enough of the Edwardian building\'s original character remains that an evening here feels like an occasion rather than simply watching a film. The double sofa seats at the front exist precisely for what you\'re thinking.',
    hours: 'Shows daily from approximately 12:00',
    tip: 'Book the double sofa seats for a special occasion. Pre-book always — they sell out.',
    type: 'Luxury independent cinema (opened 1910)',
    website: 'https://www.electriccinema.co.uk',
  },

  // ── KENSINGTON ────────────────────────────────────────────────────────────

  {
    id: 48,
    nbhd: 'kensington',
    name: 'Natural History Museum',
    cat: 'culture',
    emoji: '🦕',
    address: 'Cromwell Rd, Kensington, London SW7 5BD',
    lat: 51.4967, lng: -0.1764,
    search: 'Natural History Museum London',
    note: 'Alfred Waterhouse\'s Romanesque terracotta building is extraordinary before you\'ve seen a single exhibit. Inside: 80 million specimens across three billion years. The blue whale skeleton in the Hintze Hall. The T.rex in the Dinosaurs gallery. The basement mineral and meteorite collection — which most visitors never reach — holds some of the most visually extraordinary objects in the building. Entirely free, and impossible to exhaust.',
    hours: 'Daily 10:00–17:50',
    tip: 'Pre-book a free timed entry in school holidays. The basement mineralogy and meteorite galleries are extraordinary and usually half-empty.',
    type: 'World-class natural history museum (free)',
    website: 'https://www.nhm.ac.uk',
  },
  {
    id: 49,
    nbhd: 'kensington',
    name: 'Victoria & Albert Museum',
    cat: 'culture',
    emoji: '🏺',
    address: 'Cromwell Rd, Kensington, London SW7 2RL',
    lat: 51.4966, lng: -0.1722,
    search: 'Victoria and Albert Museum London',
    note: 'The world\'s largest museum of decorative arts: 2.3 million objects, 145 galleries, 5,000 years of human creative output. The Cast Courts on Level 1 — two vast Victorian halls containing plaster casts of Trajan\'s Column, Michelangelo\'s David and every other major European sculpture — are genuinely overwhelming. Friday evenings after 18:00 are the best time: emptier, atmospheric, often with live music in the courtyard. Free.',
    hours: 'Daily 10:00–17:45; Fri until 22:00',
    tip: 'Friday evenings after 18:00: emptier and more atmospheric than any other time. The Cast Courts first, then follow wherever the building takes you.',
    type: 'World\'s greatest decorative arts museum (free)',
    website: 'https://www.vam.ac.uk',
  },
  {
    id: 50,
    nbhd: 'kensington',
    name: 'Bibendum',
    cat: 'food',
    emoji: '🍽️',
    address: 'Michelin House, 81 Fulham Rd, London SW3 6RD',
    lat: 51.4900, lng: -0.1685,
    search: 'Bibendum restaurant Michelin House South Kensington London',
    note: 'The Michelin Building (1911) is one of London\'s finest examples of Art Nouveau commercial architecture — the tiled Michelin Man panels, the stained glass windows, the whole structure built around the mythology of a tyre company. Claude Bosi\'s restaurant on the first floor holds two Michelin stars and delivers cooking of serious technical precision without ever feeling austere. The Oyster Bar on the ground floor operates without reservations at more accessible prices. The Conran Shop occupies the building below — worth the visit alongside either restaurant.',
    hours: 'Restaurant: Tue–Sat 12:00–14:30, 18:30–21:30; closed Sun–Mon. Oyster Bar: daily 12:00–22:30',
    tip: 'The Oyster Bar for an excellent unbooked lunch. The main restaurant for a serious dinner — book well ahead. Look at the Michelin Man stained glass windows from outside before you enter.',
    type: 'Two Michelin-star restaurant in the Michelin Building (1911)',
    awards: '⭐⭐ Two Michelin Stars (Claude Bosi)',
    website: 'https://bibendum.co.uk',
  },
  {
    id: 52,
    nbhd: 'kensington',
    name: 'The Harwood Arms',
    cat: 'food',
    emoji: '🥩',
    address: 'Walham Grove, Fulham, London SW6 1QP',
    lat: 51.4787, lng: -0.1946,
    search: 'Harwood Arms Fulham London Sunday roast',
    note: 'London\'s only Michelin-starred pub, on a quiet Fulham street that looks entirely ordinary from the outside. The kitchen focuses on British game and seasonal produce with technical precision. The venison Scotch egg has accumulated serious critical attention. The Sunday roast books up months in advance — not weeks, months — which tells you what you need to know about the quality.',
    hours: 'Mon–Fri 18:00–22:00; Sat 12:00–15:00, 18:00–22:00; Sun 12:00–15:30',
    tip: 'Sunday lunch: book months ahead. The weekday dinner is more accessible and the same quality.',
    type: 'London\'s only Michelin-starred pub',
    awards: '⭐ One Michelin Star · London\'s only Michelin-starred pub · NRA UK Top 100 (2024) · Top 50 Gastropubs UK #1 (2020)',
    website: 'https://www.harwoodarms.com',
  },

  // ── GREENWICH ─────────────────────────────────────────────────────────────

  {
    id: 53,
    nbhd: 'greenwich',
    name: 'Royal Naval College',
    cat: 'culture',
    emoji: '⚓',
    address: 'King William Walk, Greenwich, London SE10 9NN',
    lat: 51.4828, lng: -0.0073,
    search: 'Royal Naval College Greenwich London',
    note: 'Christopher Wren\'s greatest secular building, UNESCO World Heritage Site, generally overlooked by visitors hurrying to the Observatory. Stand at the river gate and look: twin domed baroque buildings framing the Queen\'s House, the park rising to the Observatory behind — the most perfectly composed view in London, entirely free. The Painted Hall inside the east wing took James Thornhill 19 years to paint. It is called the Sistine Chapel of Britain for a reason.',
    hours: 'Grounds daily 08:00–18:00; Painted Hall daily 10:00–17:00',
    tip: 'The Painted Hall first — arrive before tour groups. The river approach to the grounds gives the best view of the composition.',
    type: 'UNESCO World Heritage baroque complex — Wren\'s masterpiece (free)',
    website: 'https://ornc.org',
  },
  {
    id: 54,
    nbhd: 'greenwich',
    name: 'Cutty Sark',
    cat: 'experience',
    emoji: '⛵',
    address: 'King William Walk, Greenwich, London SE10 9HT',
    lat: 51.4831, lng: -0.0094,
    search: 'Cutty Sark Greenwich London',
    note: 'Built in 1869 and the world\'s only surviving tea clipper, now raised on a glass base after a 2007 fire that nearly ended her. Walk beneath the copper hull and understand what 17-knot average speeds on the Australia wool run looked like from below. The hydrodynamic hull form is only properly visible from underneath — it is the reason to come.',
    hours: 'Daily 10:00–17:00',
    tip: 'Walk beneath the hull before boarding. The hull form seen from below is the reason to come. Combine with the Royal Naval College next door.',
    type: 'World\'s only surviving tea clipper (1869)',
    website: 'https://www.rmg.co.uk/cutty-sark',
  },
  {
    id: 55,
    nbhd: 'greenwich',
    name: 'National Maritime Museum',
    cat: 'culture',
    emoji: '🧭',
    address: 'Romney Rd, Greenwich, London SE10 9NF',
    lat: 51.4813, lng: -0.0052,
    search: 'National Maritime Museum Greenwich London',
    note: 'The world\'s largest maritime museum. Nelson\'s uniform from Trafalgar is here — the bullet hole in the left shoulder exactly where Collingwood\'s account places it. Charts from Cook\'s Pacific voyages. A 17th-century brass astrolabe. Shackleton\'s Endurance equipment. Five hundred years of Britain and the sea, told with the emotional range of great history. Free.',
    hours: 'Daily 10:00–17:00',
    tip: 'Free entry. Nelson, Navy, Nation gallery for the emotional core. Two hours minimum.',
    type: 'World\'s largest maritime museum (free)',
    website: 'https://www.rmg.co.uk/national-maritime-museum',
  },
  {
    id: 56,
    nbhd: 'greenwich',
    name: 'Royal Observatory',
    cat: 'nature',
    emoji: '🔭',
    address: 'Blackheath Ave, Greenwich, London SE10 8XJ',
    lat: 51.4778, lng: 0.0015,
    search: 'Royal Observatory Greenwich prime meridian London',
    note: 'Wren designed this for Charles II in 1675 — the king needed a fixed reference point to help British sailors calculate longitude at sea. The red Time Ball on the roof has dropped at exactly 13:00 every day since 1833, giving ships on the Thames a visible signal to set their chronometers before they sailed. Stand on the brass Meridian Line in the courtyard: one foot in the eastern hemisphere, one in the western, at the precise longitude that 41 nations agreed in Washington in 1884 would be called 0°. It sounds like a tourist gimmick and it is also genuinely one of the most significant spots on earth — every GPS satellite calibrates to a meridian that runs through this specific cobblestone. The hilltop panorama is free without a museum ticket: the Thames visible through the chestnut trees, Canary Wharf to the east, the dome of St Paul\'s on the horizon. At night a green laser fires due north along the meridian, visible for miles across the city.',
    hours: 'Daily 10:00–17:00',
    tip: 'The hilltop panorama requires no museum ticket. Visit at golden hour. The Time Ball drops at 13:00 exactly — worth timing if you are there.',
    type: 'Royal Observatory & Prime Meridian — 0° longitude',
    website: 'https://www.rmg.co.uk/royal-observatory',
  },
  {
    id: 57,
    nbhd: 'greenwich',
    name: 'Greenwich Market',
    cat: 'market',
    emoji: '🎪',
    address: '5B Greenwich Market, London SE10 9HZ',
    lat: 51.4824, lng: -0.0093,
    search: 'Greenwich Market London',
    note: 'Operating since 1737, on the only logical route between the Royal Naval College and the Cutty Sark. Pause before you browse: the Victorian ironwork market hall is worth looking at — the scale of the structure and the quality of the roof are unusual even by London standards. Weekday lunchtimes bring the street food vendors and fewer crowds; weekends shift toward craft and art stalls and the tourists who come for them. The surrounding streets — Nevada Street and Greenwich Church Street — still have the independent shops that have disappeared from most London high streets.',
    hours: 'Daily 10:00–17:30',
    tip: 'Weekday lunch for the food vendors and the space to move. The market hall architecture is the first thing to look at, before the stalls.',
    type: 'Historic covered artisan market (since 1737)',
    website: 'https://greenwichmarket.london',
  },
  {
    id: 58,
    nbhd: 'greenwich',
    name: 'Greenwich Park',
    cat: 'nature',
    emoji: '🌳',
    address: 'Greenwich Park, London SE10 8QY',
    lat: 51.4785, lng: -0.0024,
    search: 'Greenwich Park London views',
    note: 'The oldest enclosed Royal Park in London, designed by Le Nôtre for Charles II. Walk up through the avenue of chestnut trees to the hilltop near the Observatory and turn north: Canary Wharf, the O2, the Thames bending east, the City towers. One of the finest free views in Britain. In the deer enclosure in the northeast corner — which almost no visitor finds — fallow deer graze under ancient oaks as if the city is happening on another planet.',
    hours: 'Daily 06:00–21:00 (summer) / 06:00–18:00 (winter)',
    tip: 'The hilltop panorama is one of the best free things in London. The deer enclosure in the northeast corner is almost always empty of visitors.',
    type: 'Royal park with panoramic London views (Le Nôtre, 1660s)',
    website: 'https://www.royalparks.org.uk/parks/greenwich-park',
  },

  // ── SHOREDITCH & SPITALFIELDS ─────────────────────────────────────────────

  {
    id: 63,
    nbhd: 'shoreditch',
    name: 'Dennis Severs\' House',
    cat: 'experience',
    emoji: '🕯️',
    address: '18 Folgate St, Spitalfields, London E1 6BX',
    lat: 51.5218, lng: -0.0758,
    search: 'Dennis Severs House Spitalfields London',
    note: 'The most extraordinary thing in London that almost no one knows about. In 1979 the American artist Dennis Severs bought a Georgian terraced house in Spitalfields and spent his life creating a \'still-life drama\': ten rooms across 300 years, as if the Huguenot silk-weaver family who lived here from 1724 has just stepped out. Candles burning. Food half-eaten. Fires glowing. You move through it in silence. The Monday evening candlelit session is one of the most singular experiences available in any city anywhere.',
    hours: 'Sun 12:00–16:00; Mon 12:00–14:00; Mon evenings 18:00–21:00 (must book)',
    tip: 'Book the Monday evening candlelit session specifically. It is the intended experience. Nothing in London approaches it.',
    type: 'Immersive 18th-century Georgian time capsule — utterly unique',
    website: 'https://www.dennissevershouse.co.uk',
  },
  {
    id: 64,
    nbhd: 'shoreditch',
    name: 'Columbia Road Flower Market',
    cat: 'market',
    emoji: '🌺',
    address: 'Columbia Rd, Bethnal Green, London E2 7RG',
    lat: 51.5288, lng: -0.0726,
    search: 'Columbia Road Flower Market London Sunday',
    note: 'Every Sunday morning a narrow Victorian street in Bethnal Green becomes 60 stalls of cut flowers, bulbs, trees and plants — the most atmospherically specific market in London. The traders bellow prices in the East End tradition. The surrounding independent shops — ceramics, vintage, coffee — only open on market day. Go early for the energy and full selection; go at noon for the deals.',
    hours: 'Sundays only, 08:00–15:00',
    tip: 'Arrive by 09:00. The independent shops on Columbia Road only open on Sundays — the ceramics shop in particular is worth seeking out.',
    type: 'Sunday flower market (Sundays only)',
    website: 'https://columbiaroad.info',
  },
  {
    id: 65,
    nbhd: 'shoreditch',
    name: 'Beigel Bake',
    cat: 'cafe',
    emoji: '🥯',
    address: '159 Brick Lane, London E1 6SB',
    lat: 51.5227, lng: -0.0720,
    search: 'Beigel Bake Brick Lane London salt beef',
    note: 'Open 24 hours every day since 1977, apparently without closing once. The salt beef beigel — hand-formed bread, slow-cooked beef, yellow mustard, pickled cucumber — costs under £5 and is one of the most purely satisfying things you can eat in London at any hour. Cash only. No ambience. The queue at 02:00 on a Saturday morning is a London institution that predates the neighbourhood\'s gentrification by 30 years.',
    hours: 'Open 24 hours, 7 days',
    tip: 'Salt beef beigel, mustard, extra pickle. Cash only. Correct at any hour.',
    type: '24-hour bakery — open since 1977, cash only',
    website: 'https://bricklanebeigel.co.uk',
  },
  {
    id: 66,
    nbhd: 'shoreditch',
    name: 'Dishoom Shoreditch',
    cat: 'food',
    emoji: '🍛',
    address: '7 Boundary St, Shoreditch, London E2 7JE',
    lat: 51.5238, lng: -0.0739,
    search: 'Dishoom Shoreditch London Bombay café',
    note: 'Modelled on the Irani cafés of Bombay — all-day restaurants established by the Persian Zoroastrian community in the early 20th century. The Shoreditch branch on Boundary Street is the most atmospheric of the London sites, in a converted warehouse with a raised mezzanine. The black dhal has been slow-cooked for 24 hours every day since they opened. The bacon naan at breakfast is a separate pilgrimage.',
    hours: 'Mon–Thu 08:00–23:00; Fri 08:00–midnight; Sat 09:00–midnight; Sun 09:00–23:00',
    tip: 'The black dhal, the lamb chops, the bacon naan at breakfast. Weekday breakfast for the quietest time.',
    type: 'Bombay Irani café — all-day restaurant',
    website: 'https://www.dishoom.com/shoreditch/',
  },
  {
    id: 71,
    nbhd: 'shoreditch',
    name: 'Rochelle Canteen',
    cat: 'food',
    emoji: '🔔',
    address: 'Arnold Circus, Shoreditch, London E2 7ES',
    lat: 51.5252, lng: -0.0762,
    search: 'Rochelle Canteen Arnold Circus Shoreditch London',
    note: 'Hidden inside a converted Victorian school bike shed on Arnold Circus, behind a locked gate with a bell you ring to enter. Margot Henderson and Melanie Arnold opened it in 2004 as a canteen for the artists and designers working in the surrounding building. A short blackboard menu, a courtyard garden, seasonal British cooking of the most honest kind. Almost no tourists know it exists. Weekday lunch only.',
    hours: 'Mon–Fri 09:00–15:30 (lunch 12:00–15:00); closed weekends',
    tip: 'Ring the bell at the Arnold Circus gate. Weekday lunch only. Order whatever is written on the board.',
    type: 'Hidden seasonal British canteen — ring the bell to enter',
    website: 'https://www.arnoldandhenderson.com/rochelle-canteen',
  },

];
