// A Perfect Day — London
// data.js — 62 curated places
//
// v2 — March 2026
// Changes from v1:
//   Removed: London Eye, OXO Tower, Camden Market, Harrods (generic/tourist-facing)
//   Added neighbourhood: Shoreditch & Spitalfields (4 places: ids 63–66)
//   Added to existing neighbourhoods: Daunt Books (59), St John (60), Maltby St (61), Barbican (62)
//   All notes rewritten for voice and specificity

const PLACES = [

  // ── WESTMINSTER ───────────────────────────────────────────────────────────

  {
    id: 1,
    nbhd: 'westminster',
    name: 'Buckingham Palace',
    cat: 'landmark',
    emoji: '👑',
    address: 'Buckingham Palace, Westminster, London SW1A 1AA',
    lat: 51.5014, lng: -0.1419,
    search: 'Buckingham Palace London',
    note: 'The official London residence of the monarch since 1837, most famous as a façade with a balcony and a guard — though the State Rooms open to visitors in summer and are worth the entry: the Throne Room, the Picture Gallery and the Grand Staircase are all extraordinary. The Changing of the Guard remains one of the great free spectacles of any city on earth.',
    hours: 'State Rooms: late July–Sep, daily 09:30–19:30',
    tip: 'Book State Rooms tickets well in advance for July and August. Check the official site for Changing of the Guard schedule — it does not run every day.',
    type: 'Royal palace',
    website: 'https://www.rct.uk/visit/buckinghampalace',
  },
  {
    id: 2,
    nbhd: 'westminster',
    name: 'Westminster Abbey',
    cat: 'church',
    emoji: '⛪',
    address: '20 Deans Yard, Westminster, London SW1P 3PA',
    lat: 51.4994, lng: -0.1276,
    search: 'Westminster Abbey London',
    note: 'Every English monarch since William the Conqueror has been crowned in this building. Newton, Darwin, Dickens, Handel, Chaucer, Mary Queen of Scots are all here — buried or commemorated in a building that doubles as the country\'s most extraordinary narrative. The Poets\' Corner alone is worth the entry. One of the rare London landmarks that genuinely delivers on its reputation.',
    hours: 'Mon–Sat 09:30–15:30 (last entry); closed to tourists on Sundays',
    tip: 'Book tickets online. The audio guide tells the individual stories behind the graves — genuinely compelling.',
    type: 'Gothic abbey & coronation church',
    website: 'https://www.westminster-abbey.org',
  },
  {
    id: 3,
    nbhd: 'westminster',
    name: 'Churchill War Rooms',
    cat: 'landmark',
    emoji: '🏛️',
    address: 'Clive Steps, King Charles Street, London SW1A 2AQ',
    lat: 51.5020, lng: -0.1289,
    search: 'Churchill War Rooms London',
    note: 'The underground bunker beneath Whitehall where Churchill and his cabinet ran the Second World War. The rooms have been preserved exactly as they were left on VE Day 1945 — maps still pinned, phones still connected, a single bare bulb burning in the Map Room. The Churchill Museum beside it is one of the most intelligent biographical exhibitions in London. Consistently underrated.',
    hours: 'Daily 09:30–18:00',
    tip: 'Allow two hours. The Churchill Museum is as compelling as the bunker — don\'t skip it.',
    type: 'Preserved wartime bunker & museum',
    website: 'https://www.iwm.org.uk/visits/churchill-war-rooms',
  },
  {
    id: 4,
    nbhd: 'westminster',
    name: 'Houses of Parliament',
    cat: 'landmark',
    emoji: '🏰',
    address: 'Palace of Westminster, London SW1A 0AA',
    lat: 51.4997, lng: -0.1247,
    search: 'Houses of Parliament Palace of Westminster London',
    note: 'Barry and Pugin\'s Gothic Revival masterpiece, 30 years in the building and still one of the most dramatic buildings on any river in the world. UK residents can arrange free guided tours through their MP. For everyone else, weekend tours run when Parliament is in recess and take you through the medieval Great Hall and both debating chambers. The view from Westminster Bridge at dusk is worth a trip regardless.',
    hours: 'Weekend tours when Parliament is in recess — check online',
    tip: 'The South Bank view at dusk — river in front, the whole lit façade reflected — is one of the great free London sights.',
    type: 'Parliament building & UNESCO World Heritage Site',
    website: 'https://www.parliament.uk/visiting',
  },
  {
    id: 5,
    nbhd: 'westminster',
    name: 'St James\'s Park',
    cat: 'nature',
    emoji: '🌿',
    address: 'St James\'s Park, London SW1A 2BJ',
    lat: 51.5025, lng: -0.1353,
    search: 'St James\'s Park London',
    note: 'The oldest Royal Park in London and the most strategically placed. Stand on the bridge over the lake and you get two of the city\'s finest views simultaneously: Buckingham Palace to the west, the turrets and gilded roofscapes of Whitehall to the east. The pelicans have been here since 1664. The park connects to Green Park and Hyde Park for a two-mile walk from the Palace to Kensington Gardens.',
    hours: 'Daily 05:00–midnight',
    tip: 'The bridge is the best free viewpoint for Buckingham Palace in London. Pelicans fed around 14:30 daily near the island.',
    type: 'Royal park (the oldest in London)',
    website: 'https://www.royalparks.org.uk/parks/st-jamess-park',
  },
  {
    id: 59,
    nbhd: 'westminster',
    name: 'Daunt Books',
    cat: 'landmark',
    emoji: '📚',
    address: '83–84 Marylebone High St, London W1U 4QW',
    lat: 51.5200, lng: -0.1533,
    search: 'Daunt Books Marylebone London bookshop',
    note: 'The most beautiful bookshop in London, possibly in the world. The 1912 Edwardian building has long oak galleries, a skylight running the length of the back room, stained glass at the rear and William Morris prints along the walls. Books are arranged by country rather than genre — so the fiction, history, travel writing and maps for Japan sit side by side. Recently named the world\'s most popular bookshop. The cloth Daunt bag has become a better London souvenir than anything in a gift shop.',
    hours: 'Mon–Sat 09:00–19:30; Sun 11:00–18:00',
    tip: 'The back room under the skylight is the most beautiful reading space in London. The travel section downstairs is extraordinary — you will spend longer here than planned.',
    type: 'The world\'s most beautiful independent bookshop',
    website: 'https://dauntbooks.co.uk/shops/marylebone/',
  },

  // ── SOUTH BANK ────────────────────────────────────────────────────────────

  {
    id: 7,
    nbhd: 'southbank',
    name: 'Tate Modern',
    cat: 'landmark',
    emoji: '🎨',
    address: 'Bankside, London SE1 9TG',
    lat: 51.5076, lng: -0.0994,
    search: 'Tate Modern London',
    note: 'Giles Gilbert Scott\'s former Bankside Power Station — a vast, brooding machine-age building opened as a gallery in 2000 and still the most exciting museum space in London. The permanent collection, entirely free, takes you from the Surrealists through Rothko and Beuys to the present. Walk into the Turbine Hall and look up at 35 metres of raw air. The Blavatnik Building\'s 10th-floor terraces have the finest free panorama of the Thames in the city.',
    hours: 'Sun–Thu 10:00–18:00; Fri–Sat 10:00–22:00',
    tip: 'Free for the permanent collection. The viewing terraces are accessible without a gallery ticket. Friday evenings are significantly quieter.',
    type: 'Modern & contemporary art gallery (free)',
    website: 'https://www.tate.org.uk/visit/tate-modern',
  },
  {
    id: 8,
    nbhd: 'southbank',
    name: 'Shakespeare\'s Globe',
    cat: 'landmark',
    emoji: '🎭',
    address: '21 New Globe Walk, Bankside, London SE1 9DT',
    lat: 51.5081, lng: -0.0974,
    search: 'Shakespeare\'s Globe Theatre London',
    note: 'A reconstruction of the 1599 Globe, built 200 metres from the original site using the same materials — green oak, Norfolk reed thatch, lime plaster. The open roof means performances happen in whatever weather London provides, which is the point. A standing groundling ticket puts you in the yard at stage height, surrounded by a full circular house. No theatre experience in London feels as immediate or as alive.',
    hours: 'Tours daily 09:30–17:00. Performances Apr–Oct',
    tip: 'Groundling tickets are cheap and the most immersive way to see a show. Bring a layer. Tours are excellent on non-performance days.',
    type: 'Reconstructed Elizabethan open-air theatre',
    website: 'https://www.shakespearesglobe.com',
  },
  {
    id: 9,
    nbhd: 'southbank',
    name: 'Millennium Bridge',
    cat: 'nature',
    emoji: '🌉',
    address: 'Millennium Bridge, Bankside, London SE1',
    lat: 51.5098, lng: -0.0983,
    search: 'Millennium Bridge London Thames',
    note: 'Norman Foster\'s pedestrian suspension bridge connects St Paul\'s to Tate Modern and the Globe in a single five-minute crossing. Walk it from the north at dawn — the dome directly ahead, the Thames silver below, the city entirely quiet. From here: Globe → Borough Market → Bermondsey Street. This is the best free morning walk in London.',
    hours: 'Open 24 hours',
    tip: 'Cross north to south at sunrise. Continue east to Borough Market and south to Bermondsey Street — the perfect south London morning.',
    type: 'Pedestrian bridge & Thames crossing',
    website: 'https://www.london.gov.uk',
  },

  // ── BOROUGH & BERMONDSEY ──────────────────────────────────────────────────

  {
    id: 11,
    nbhd: 'borough',
    name: 'Borough Market',
    cat: 'market',
    emoji: '🛒',
    address: '8 Southwark St, London SE1 1TL',
    lat: 51.5055, lng: -0.0908,
    search: 'Borough Market London',
    note: 'A market on this site since the 13th century. Under the Victorian railway arches: over 100 traders, most of them specialists — fishmongers, cheesemakers, bakers, charcutiers, coffee roasters — selling things they have grown, cured, brewed or made. Come on a Thursday morning before the weekend crowds. The noise and the density and the smell of it is unlike any supermarket experience on earth.',
    hours: 'Mon–Thu 10:00–17:00; Fri 10:00–18:00; Sat 08:00–17:00; closed Sun',
    tip: 'Weekday mornings are the authentic experience. On Saturdays it\'s shoulder to shoulder — go early or head to Maltby Street Market instead (10 minutes away).',
    type: 'Historic food market (since the 13th century)',
    website: 'https://boroughmarket.org.uk',
  },
  {
    id: 12,
    nbhd: 'borough',
    name: 'El Pastor',
    cat: 'food',
    emoji: '🌮',
    address: '7A Stoney St, London SE1 9AA',
    lat: 51.5055, lng: -0.0913,
    search: 'El Pastor Borough Market London',
    note: 'Under the railway arches beside Borough Market, El Pastor serves tacos al pastor — marinated pork shaved from a vertical trompo in the traditional Mexico City style. The kitchen is open and theatrical, the mezcal list is serious, and the tacos are among the best in London. Counter seats facing the trompo are the best in the house.',
    hours: 'Mon–Fri 12:00–22:30; Sat 11:00–22:30; Sun 12:00–21:30',
    tip: 'Counter seats facing the spit. The al pastor taco is non-negotiable. The house margarita too.',
    type: 'Mexican taqueria & mezcal bar',
    website: 'https://tacoselpastor.co.uk',
  },
  {
    id: 13,
    nbhd: 'borough',
    name: 'Padella',
    cat: 'food',
    emoji: '🍝',
    address: '6 Southwark St, London SE1 1TQ',
    lat: 51.5054, lng: -0.0904,
    search: 'Padella Pasta Borough Market London',
    note: 'A small no-reservations pasta restaurant opposite Borough Market that has had a queue since its first week in 2016 and shows no sign of slowing down. Pasta made fresh each morning. Menu changes daily. Nothing over £15. The pici cacio e pepe and the tagliarini with 8-hour slow-cooked tomato are the reasons people come back. The simplicity is the point and the execution is faultless.',
    hours: 'Mon–Sat 12:00–21:30; Sun 12:00–21:00',
    tip: 'Walk-in only. Arrive at noon. The wait is usually under 45 minutes and completely worth it.',
    type: 'Fresh pasta restaurant — walk-in only',
    website: 'https://padella.co',
  },
  {
    id: 14,
    nbhd: 'borough',
    name: 'Monmouth Coffee',
    cat: 'cafe',
    emoji: '☕',
    address: '2 Park St, London SE1 9AB',
    lat: 51.5055, lng: -0.0924,
    search: 'Monmouth Coffee Borough Market London',
    note: 'Monmouth has been roasting in Borough since the 1970s and this small dark shop on Park Street is where London\'s specialty coffee culture began. They source directly from small farms, roast at their Bermondsey facility, and have not changed the approach in 50 years. The Saturday queue is a reliable indicator of quality.',
    hours: 'Mon–Sat 07:30–18:00; closed Sun',
    tip: 'The beans make a better London souvenir than anything in a gift shop.',
    type: 'Specialty coffee roaster — the original',
    website: 'https://www.monmouthcoffee.co.uk',
  },
  {
    id: 15,
    nbhd: 'borough',
    name: 'Gelateria 3Bis',
    cat: 'cafe',
    emoji: '🍦',
    address: 'Stoney St, London SE1',
    lat: 51.5053, lng: -0.0907,
    search: 'Gelateria 3Bis Borough Market London',
    note: 'A stall under the Borough Market railway arches making gelato in small batches all day. Unusually light and intensely flavoured. The pistachio uses Sicilian nuts. The salted caramel is confident. Ask for warm chocolate sauce and eat it walking toward the Millennium Bridge.',
    hours: 'Mon–Sat 10:00–18:00; Sun 11:00–17:00',
    tip: 'Ask for warm chocolate sauce. Pistachio or salted caramel.',
    type: 'Artisan gelato',
    website: 'https://gelateria3bis.com',
  },
  {
    id: 16,
    nbhd: 'borough',
    name: 'Bermondsey Street',
    cat: 'landmark',
    emoji: '🏘️',
    address: 'Bermondsey Street, London SE1',
    lat: 51.5001, lng: -0.0809,
    search: 'Bermondsey Street London',
    note: 'A medieval pilgrim route that has become one of London\'s most interesting half-miles without many people noticing. Independent restaurants, the White Cube gallery, WatchHouse coffee, José tapas — on a street that still manages to feel like a neighbourhood. Ten minutes south of London Bridge and most visitors walk straight past it. That\'s exactly the point.',
    hours: 'Open all hours; shops and galleries vary',
    tip: 'The Saturday formula: WatchHouse for coffee, White Cube at 10, José for tapas at noon. That is a perfect Bermondsey morning.',
    type: 'Independent street — galleries, restaurants, coffee',
    website: 'https://www.bermondseystreet.net',
  },
  {
    id: 17,
    nbhd: 'borough',
    name: 'WatchHouse Bermondsey',
    cat: 'cafe',
    emoji: '⌚',
    address: '199 Bermondsey St, London SE1 3UW',
    lat: 51.5003, lng: -0.0793,
    search: 'WatchHouse Bermondsey coffee London',
    note: 'The original WatchHouse, in a converted Victorian watchhouse on Bermondsey Street — stone walls, arched windows, an entirely appropriate atmosphere for what is genuinely excellent coffee. The London chain has since expanded, but this is the one with the character. Pour-overs and batch brews are the orders.',
    hours: 'Mon–Fri 07:00–17:00; Sat–Sun 08:30–17:00',
    tip: 'The pour-overs are the main event. Saturday morning before the Bermondsey market crowd arrives.',
    type: 'Specialty coffee in a Victorian watchhouse',
    website: 'https://watchhouse.com',
  },
  {
    id: 18,
    nbhd: 'borough',
    name: 'José Bermondsey',
    cat: 'food',
    emoji: '🥘',
    address: '104 Bermondsey St, London SE1 3UB',
    lat: 51.5007, lng: -0.0821,
    search: 'José Tapas Bermondsey London',
    note: 'Standing room only. No bookings. A menu of maybe fifteen things, all of them exactly what they should be. José Pizarro opened this in 2011 and it remains London\'s closest equivalent to a proper Spanish counter — croquetas that shatter correctly, jamón at the right temperature, grilled prawns with enough char. The sherry list is the best in London. Arrive at opening.',
    hours: 'Tue–Sat 12:00–22:30; Sun 12:00–16:00; closed Mon',
    tip: 'Opening time or accept a wait. Croquetas first, then whatever fish they have. Ask about the sherries.',
    type: 'Spanish tapas bar — standing only, no bookings',
    website: 'https://josepizarro.com/jose-tapas-bar',
  },
  {
    id: 19,
    nbhd: 'borough',
    name: 'White Cube Gallery',
    cat: 'landmark',
    emoji: '🖼️',
    address: '144–152 Bermondsey St, London SE1 3TQ',
    lat: 51.5011, lng: -0.0823,
    search: 'White Cube Gallery Bermondsey London',
    note: 'The largest of White Cube\'s London spaces — 6,000 square metres, purpose-built in 2011, large enough to show monumental work at a scale most commercial galleries cannot match. Damien Hirst, Tracey Emin, Antony Gormley, Georg Baselitz. Free entry, always.',
    hours: 'Tue–Sat 10:00–18:00; Sun 12:00–18:00; closed Mon',
    tip: 'Free always. Check website for current exhibitions before visiting.',
    type: 'Major contemporary art gallery (free)',
    website: 'https://www.whitecube.com',
  },
  {
    id: 20,
    nbhd: 'borough',
    name: 'London Glassblowing',
    cat: 'landmark',
    emoji: '🫙',
    address: '62–66 Bermondsey St, London SE1 3UD',
    lat: 51.5009, lng: -0.0831,
    search: 'London Glassblowing Studio Bermondsey',
    note: 'One of Britain\'s longest-running glassblowing studios, on Bermondsey Street since 1976. Watch through the studio windows at any time. The gallery displays resident and visiting artists\' work for sale. Glassblowing masterclasses — where you make something yourself — are booked weeks ahead and make a genuinely unusual London experience.',
    hours: 'Mon–Sat 10:00–18:00',
    tip: 'Book a masterclass well ahead. The gallery is worth browsing regardless.',
    type: 'Working glassblowing studio & gallery',
    website: 'https://www.londonglassblowing.co.uk',
  },
  {
    id: 21,
    nbhd: 'borough',
    name: 'M. Manze Pie & Mash',
    cat: 'food',
    emoji: '🥧',
    address: '87 Tower Bridge Rd, London SE1 4TW',
    lat: 51.4997, lng: -0.0756,
    search: 'M Manze pie mash London',
    note: 'Operating since 1902 and unchanged since at least 1930. The tiled Edwardian interior is intact, the dish is the same — minced beef pie, mashed potato, liquor (a green parsley sauce unique to this tradition) — and the prices have barely moved. London\'s oldest surviving pie and mash shop and one of the only places in the city where absolutely nothing has been updated for atmosphere. Cash only, lunchtimes only.',
    hours: 'Mon 11:00–14:00; Tue–Thu 10:30–14:30; Fri 10:00–15:00; Sat 10:00–14:45',
    tip: 'Pie, mash and liquor. Cash only. Sit in. The room is as interesting as the food.',
    type: 'London\'s oldest pie & mash shop (est. 1902)',
    website: 'https://www.manze.co.uk',
  },
  {
    id: 22,
    nbhd: 'borough',
    name: 'The Garrison',
    cat: 'pub',
    emoji: '🍺',
    address: '99–101 Bermondsey St, London SE1 3XB',
    lat: 51.5009, lng: -0.0830,
    search: 'The Garrison pub Bermondsey London',
    note: 'The gastropub that helped define Bermondsey Street\'s character when it opened in 2003 and has remained the neighbourhood\'s social anchor ever since. Bare brick, mismatched vintage furniture, good natural light. The kitchen does elevated British cooking without ever feeling like it\'s trying too hard. The Sunday roast books up well in advance.',
    hours: 'Mon–Thu 08:00–23:00; Fri–Sat 08:00–midnight; Sun 08:00–22:30',
    tip: 'Book Sunday roast ahead. Breakfast on Saturday before the market opens is a particularly good start to a Bermondsey day.',
    type: 'British gastropub',
    website: 'https://thegarrison.co.uk',
  },
  {
    id: 60,
    nbhd: 'borough',
    name: 'St John Restaurant',
    cat: 'food',
    emoji: '🦴',
    address: '26 St John St, Smithfield, London EC1M 4AY',
    lat: 51.5197, lng: -0.1013,
    search: 'St John Restaurant Smithfield London',
    note: 'Fergus Henderson opened St John in a former smokehouse beside Smithfield Market in 1994 and invented a cuisine. Nose-to-tail eating — every part of the animal, treated with the same respect — sounds like a philosophy but here it is simply a menu. The bone marrow and parsley salad on sourdough toast is one of the most important dishes in British food history. White walls, bare wood, no music, no decoration. Nothing is trying to impress you except the food, which does so completely.',
    hours: 'Mon–Fri 12:00–15:00, 18:00–22:00; Sat 12:00–15:00, 18:00–22:00',
    tip: 'The bone marrow toast is non-negotiable. The eccles cake with Lancashire cheese at the end is obligatory. Book ahead.',
    type: 'The original nose-to-tail restaurant (since 1994)',
    website: 'https://stjohnrestaurant.com',
  },
  {
    id: 61,
    nbhd: 'borough',
    name: 'Maltby Street Market',
    cat: 'market',
    emoji: '🧺',
    address: 'Maltby St, Bermondsey, London SE1 3PA',
    lat: 51.5007, lng: -0.0822,
    search: 'Maltby Street Market Bermondsey London',
    note: 'The insider\'s alternative to Borough Market, running under the railway arches on Maltby Street on Saturdays and Sundays. A fraction of the crowds, better value, and producers who are often more interesting than their Borough neighbours. Cheese, charcuterie, oysters, fresh pasta, natural wine, coffee. Locals come here when Borough Market has become too much.',
    hours: 'Sat 09:00–16:00; Sun 11:00–16:00',
    tip: 'Come here instead of Borough Market on weekends for a calmer and equally good experience. The oyster stall and the coffee roaster under the arches are both excellent.',
    type: 'Artisan street food market under railway arches',
    website: 'https://maltbystreet.com',
  },

  // ── THE CITY ──────────────────────────────────────────────────────────────

  {
    id: 23,
    nbhd: 'city',
    name: 'Tower Bridge',
    cat: 'landmark',
    emoji: '🌉',
    address: 'Tower Bridge Rd, London SE1 2UP',
    lat: 51.5055, lng: -0.0754,
    search: 'Tower Bridge London',
    note: 'Completed in 1894, the bascule bridge still raises for river traffic — scheduled lift times are published on the website and watching it open is free from the banks. The paid attraction includes the glass-floored high-level walkways 42 metres above the Thames and the Victorian Engine Rooms. The finest photograph of it is from the south bank at dusk, looking northeast: Tower Bridge, the Thames, and the glow of the City behind it.',
    hours: 'Daily 09:30–17:30',
    tip: 'Bridge lift times are published online at least 24 hours ahead — worth timing a visit. Best photography from the riverbank, not from inside.',
    type: 'Victorian bascule bridge (1894)',
    website: 'https://www.towerbridge.org.uk',
  },
  {
    id: 24,
    nbhd: 'city',
    name: 'Tower of London',
    cat: 'landmark',
    emoji: '🏰',
    address: 'St Katharine\'s & Wapping, London EC3N 4AB',
    lat: 51.5081, lng: -0.0760,
    search: 'Tower of London',
    note: 'Almost a thousand years of continuous use. The Crown Jewels — the Imperial State Crown with its 2,868 diamonds, the Orb, the Coronation Spoon from 1349 — are housed in the Jewel House. The free Yeoman Warder tours are among the best guided experiences in London. The Ceremony of the Keys, the oldest military ceremony in the world, takes place every night at 21:53 and is free to attend — but requires booking months ahead.',
    hours: 'Tue–Sat 09:00–17:30; Sun–Mon 10:00–17:30',
    tip: 'Ceremony of the Keys tickets: book months ahead, completely free. Yeoman Warder tours leave hourly from the gate — join one.',
    type: 'Historic royal fortress & UNESCO World Heritage Site',
    website: 'https://www.hrp.org.uk/tower-of-london',
  },
  {
    id: 25,
    nbhd: 'city',
    name: 'Sky Garden',
    cat: 'nature',
    emoji: '🌿',
    address: '1 Sky Garden Walk, London EC3M 8AF',
    lat: 51.5111, lng: -0.0838,
    search: 'Sky Garden London Walkie Talkie',
    note: 'A free public garden on floors 35–37 of the Walkie Talkie building — 360 degrees, 155 metres up, no glass for most of the exterior views. On a clear day you can see Heathrow to the west and the Olympic Park to the east. Requires advance booking, which keeps it from ever feeling crowded. One of London\'s most underused great experiences.',
    hours: 'Mon–Fri 10:00–18:00; Sat–Sun 11:00–21:00',
    tip: 'Free tickets must be booked on the website and go fast. Evening slots on clear nights are spectacular.',
    type: 'Free 35th-floor public garden & 360° viewpoint',
    website: 'https://skygarden.london',
  },
  {
    id: 26,
    nbhd: 'city',
    name: 'Leadenhall Market',
    cat: 'market',
    emoji: '🏛️',
    address: 'Gracechurch St, London EC3V 1LT',
    lat: 51.5135, lng: -0.0831,
    search: 'Leadenhall Market London',
    note: 'A covered Victorian market in the middle of the City, built in 1881 on a site with a market since the 14th century. The painted ornamental ironwork — burgundy, green and cream — creates one of the most theatrical interiors in London. On weekday mornings, City workers in suits pressing through for coffee creates an atmosphere that feels like Victorian London has not entirely ended. Harry Potter chose it for Diagon Alley for a reason.',
    hours: 'Mon–Fri 10:00–18:00; pubs open longer',
    tip: 'Weekday mornings for the authentic atmosphere. Empty at weekends.',
    type: 'Ornate Victorian covered market (1881)',
    website: 'https://leadenhallmarket.co.uk',
  },
  {
    id: 27,
    nbhd: 'city',
    name: 'Duck and Waffle',
    cat: 'food',
    emoji: '🧇',
    address: '110 Bishopsgate, London EC2N 4AY',
    lat: 51.5142, lng: -0.0820,
    search: 'Duck and Waffle restaurant London',
    note: 'Open 24 hours on the 40th floor of Heron Tower, floor-to-ceiling windows, the full sweep of the City and Thames below. The signature dish — confit duck leg on a Belgian waffle with a fried duck egg and mustard maple syrup — is one of those combinations that sounds improbable and tastes inevitable. Book a sunrise slot around 06:30 for the most dramatic view, a quieter room and lower prices.',
    hours: 'Open 24/7',
    tip: 'A sunrise booking is one of London\'s great breakfast experiences. Watch the city wake up from 40 floors. Book weeks ahead.',
    type: '24-hour restaurant with 40th-floor City views',
    website: 'https://duckandwaffle.com',
  },
  {
    id: 28,
    nbhd: 'city',
    name: 'St Paul\'s Cathedral',
    cat: 'church',
    emoji: '⛪',
    address: 'St. Paul\'s Churchyard, London EC4M 8AD',
    lat: 51.5138, lng: -0.0984,
    search: 'St Paul\'s Cathedral London',
    note: 'Christopher Wren built this after the previous cathedral burned in the Great Fire of 1666, working on it for 35 years. The dome — still the fourth largest in the world — defines the south side of the London skyline. Climb 528 steps to the Golden Gallery for one of the finest elevated views in the city. The Whispering Gallery inside the dome, 30 metres up, demonstrates an acoustic phenomenon: whisper into the wall and be heard clearly on the other side.',
    hours: 'Mon–Sat 08:30–16:30',
    tip: 'Book in advance. The Whispering Gallery is the surprising highlight. The Golden Gallery at the top is worth every step of the climb.',
    type: 'Baroque cathedral (Christopher Wren, 1710)',
    website: 'https://www.stpauls.co.uk',
  },
  {
    id: 62,
    nbhd: 'city',
    name: 'The Barbican',
    cat: 'landmark',
    emoji: '🏗️',
    address: 'Silk Street, Barbican, London EC2Y 8DS',
    lat: 51.5203, lng: -0.0928,
    search: 'Barbican Centre London arts complex',
    note: 'The largest brutalist complex in Europe and one of the most architecturally ambitious things ever built in Britain — a city within the City, with elevated walkways, lakes, a conservatory and gardens woven between 2,000 flats and a major arts centre. The concert hall, two theatres, cinema and art gallery are inside a building that looks designed for a planet with slightly different physical laws. The Lakeside Terrace café on a quiet weekday afternoon is one of London\'s most underrated places to sit and think. Free to explore.',
    hours: 'Public walkways from 06:00. Arts centre 11:00–23:00',
    tip: 'Get lost in the elevated walkways — that is the correct approach. The Barbican Estate garden inside the complex is hidden and beautiful in spring.',
    type: 'Brutalist arts complex & residential estate (free to explore)',
    website: 'https://www.barbican.org.uk',
  },

  // ── COVENT GARDEN & SOHO ──────────────────────────────────────────────────

  {
    id: 29,
    nbhd: 'covent-garden',
    name: 'Covent Garden',
    cat: 'market',
    emoji: '🌹',
    address: 'Covent Garden, London WC2E 8RF',
    lat: 51.5117, lng: -0.1232,
    search: 'Covent Garden London',
    note: 'The former wholesale fruit and vegetable market — saved from demolition in the 1970s by one of London\'s first successful community campaigns — is now one of the city\'s most visited destinations. The covered Apple Market, the Piazza and the surrounding alleys reward more time than most visitors give them. The performers who work the central stage are among the best street acts in Europe. Find Neal\'s Yard before you leave.',
    hours: 'Piazza 24h; Market & shops: Mon–Sat 10:00–20:00; Sun 11:00–18:00',
    tip: 'Best performers arrive mid-afternoon at the main stage. Neal\'s Yard is hidden off Shorts Gardens — most people walk straight past the entrance.',
    type: 'Historic market piazza & entertainment district',
    website: 'https://www.coventgarden.london',
  },
  {
    id: 30,
    nbhd: 'covent-garden',
    name: 'Neal\'s Yard',
    cat: 'landmark',
    emoji: '🌈',
    address: 'Neal\'s Yard, Covent Garden, London WC2H 9DP',
    lat: 51.5128, lng: -0.1262,
    search: 'Neal\'s Yard Covent Garden London',
    note: 'A tiny courtyard accessible only through narrow alleys off Neal Street, with buildings painted in clashing vivid colours that seem to belong to a different city. Neal\'s Yard Dairy occupies the corner and is, without qualification, one of the finest cheese shops in the world — they mature wheels of British farmhouse cheese in their cellars and the staff know everything about each one. The courtyard has kept its bohemian character since the 1970s.',
    hours: 'Shops open Mon–Sat 10:00–18:00',
    tip: 'Find it from Shorts Gardens or Neal Street. Neal\'s Yard Dairy: ask what\'s in best condition today. Trust the answer.',
    type: 'Hidden colourful courtyard & world-class cheese shop',
    website: 'https://www.nealsyard.co.uk',
  },
  {
    id: 31,
    nbhd: 'covent-garden',
    name: 'Clos Maggiore',
    cat: 'food',
    emoji: '🌸',
    address: '33 King St, Covent Garden, London WC2E 8JD',
    lat: 51.5118, lng: -0.1243,
    search: 'Clos Maggiore restaurant Covent Garden London',
    note: 'The most romantic dining room in London: a conservatory with a retractable glass roof, cherry blossom overhead, candlelight, and French cooking that earns its setting. It sounds theatrical because it is. Ask for the conservatory when booking. The set lunch is the best-value route into one of London\'s most celebrated kitchens.',
    hours: 'Mon–Sat 12:00–14:30, 17:00–23:00; Sun 12:00–15:30, 17:00–22:00',
    tip: 'Request the conservatory when booking. The set lunch menu is excellent value. Book well ahead for weekends.',
    type: 'French restaurant — one of London\'s most romantic rooms',
    website: 'https://www.closmaggiore.com',
  },
  {
    id: 32,
    nbhd: 'covent-garden',
    name: 'Barrafina',
    cat: 'food',
    emoji: '🦐',
    address: '10 Adelaide St, London WC2N 4HZ',
    lat: 51.5097, lng: -0.1239,
    search: 'Barrafina tapas London',
    note: 'Counter seating only, no reservations, kitchen visible from every seat. Barrafina has been the benchmark for Spanish cooking in London since 2007 — the tortilla, the grilled fish, the cuttlefish, the jamón. The chefs know what\'s good that day and will tell you if you ask. Stand at a bar across the road and wait for a counter seat: it is always worth it.',
    hours: 'Mon–Sat 12:00–15:00, 17:00–23:00; Sun 13:00–15:30, 17:00–22:00',
    tip: 'Walk-in only. Arrive before opening or accept the wait. Ask the chefs for their recommendations.',
    type: 'Acclaimed Spanish counter restaurant',
    website: 'https://barrafina.co.uk',
  },
  {
    id: 33,
    nbhd: 'covent-garden',
    name: 'Mr Fogg\'s Gin Parlour',
    cat: 'pub',
    emoji: '🍸',
    address: '1 New Row, London WC2N 4EA',
    lat: 51.5110, lng: -0.1241,
    search: 'Mr Fogg\'s Gin Parlour London',
    note: 'An extremely small Victorian gin bar in Covent Garden dressed as the study of a 19th-century explorer: stuffed animals, antique globes, butterfly cases, bookshelves. Over 300 gins and bartenders who treat the inventory with the seriousness of a sommelier. Small enough that booking is essential, atmospheric enough to justify the effort.',
    hours: 'Mon–Thu 15:00–midnight; Fri–Sat 12:00–01:00; Sun 12:00–midnight',
    tip: 'Book ahead. Ask the bartender for recommendations from lesser-known distilleries — they will have strong opinions.',
    type: 'Victorian gin parlour (300+ gins)',
    website: 'https://mr-foggs.com/gin-parlour',
  },
  {
    id: 34,
    nbhd: 'covent-garden',
    name: 'St Paul\'s Covent Garden',
    cat: 'church',
    emoji: '⛪',
    address: 'Bedford St, Covent Garden, London WC2E 9ED',
    lat: 51.5116, lng: -0.1231,
    search: 'St Paul\'s Church Covent Garden London',
    note: 'Inigo Jones built this in 1633 and oriented it backwards — the grand portico faces the piazza but is not the entrance. It has been the Actors\' Church ever since: Vivien Leigh, Charlie Chaplin, Boris Karloff, Noel Coward are all commemorated inside. The garden is a quiet green escape from the piazza directly outside. The portico steps are where the best street performers set up.',
    hours: 'Mon–Fri 08:30–17:00; Sun service 11:00',
    tip: 'Free entry. The memorial plaques inside are worth reading. The portico gives the best view of the piazza performers.',
    type: 'The Actors\' Church (Inigo Jones, 1633)',
    website: 'https://www.actorschurch.org',
  },
  {
    id: 35,
    nbhd: 'covent-garden',
    name: 'Ronnie Scott\'s Jazz Club',
    cat: 'pub',
    emoji: '🎷',
    address: '47 Frith St, Soho, London W1D 4HT',
    lat: 51.5133, lng: -0.1314,
    search: 'Ronnie Scott\'s Jazz Club London',
    note: 'Ronnie Scott opened this basement on Frith Street in 1959 with £100 borrowed from a friend. Miles Davis played here. Jimi Hendrix performed one of his last concerts on this stage. Nina Simone called it a second home. The room holds 250 people and feels intimate regardless of who is on. The late-night sessions that begin after the main act — around 23:30 — are often more interesting than the headliner.',
    hours: 'Mon–Sat 18:00–03:00; Sun 18:00–midnight',
    tip: 'Book ahead for headline acts. The late-night sessions (after the main show) are cheaper, more spontaneous and often better.',
    type: 'World-famous jazz club (since 1959)',
    website: 'https://www.ronniescotts.co.uk',
  },
  {
    id: 36,
    nbhd: 'covent-garden',
    name: 'Chinatown',
    cat: 'food',
    emoji: '🏮',
    address: 'Gerrard St, Chinatown, London W1D 5PT',
    lat: 51.5118, lng: -0.1311,
    search: 'Chinatown London Gerrard Street',
    note: 'Gerrard Street and the alleys around it have been the heart of London\'s Chinese community since the 1950s. The concentration of good food — Cantonese, Shanghainese, Sichuan, dim sum — at prices that have not risen at the rate of the rest of central London is still remarkable. Explore beyond Gerrard Street into Lisle Street and Newport Place for restaurants with fewer tourists and equally good food.',
    hours: 'Restaurants open daily from approx 11:00 to midnight',
    tip: 'Dim sum at lunch. The side streets off Gerrard Street have better value than the main drag.',
    type: 'Historic cultural quarter & food destination',
    website: 'https://chinatownlondon.org',
  },
  {
    id: 37,
    nbhd: 'covent-garden',
    name: 'Opium Cocktail Bar',
    cat: 'pub',
    emoji: '🍵',
    address: '15–16 Gerrard St, London W1D 6JE',
    lat: 51.5119, lng: -0.1306,
    search: 'Opium cocktail bar Chinatown London',
    note: 'Hidden above Chinatown\'s Gerrard Street — find the door, take the stairs up past the red lanterns. Opium is spread across three floors of a 1920s Shanghai-themed bar with neon, dark wood and a theatrical atmosphere that intensifies on Friday nights. The cocktail menu is inventive, drawing on Asian spirits and ingredients. Performers on the upper floors at weekends. Surreal and entirely unlike anything else in central London.',
    hours: 'Mon–Tue 17:00–01:00; Wed–Thu 17:00–02:00; Fri–Sat 17:00–03:00; Sun 17:00–midnight',
    tip: 'Book ahead at weekends. The Dragon cocktail is the house signature. Rooftop level in summer.',
    type: '1920s Shanghai cocktail bar above Chinatown',
    website: 'https://www.opiumchinatown.com',
  },
  {
    id: 38,
    nbhd: 'covent-garden',
    name: 'Bob Bob Ricard',
    cat: 'food',
    emoji: '🍾',
    address: '1 Upper James St, Soho, London W1F 9DF',
    lat: 51.5124, lng: -0.1389,
    search: 'Bob Bob Ricard restaurant London',
    note: 'A Soho restaurant built around a single, brilliant conceit: a Press for Champagne button at every booth, connected directly to the bar. The room — lacquered blue and gold, mirrored ceilings, leather booths — is as glamorous as that implies. The menu is a serious take on British and Russian brasserie classics. Not cheap, but the experience is impossible to replicate.',
    hours: 'Daily 12:30–15:00, 18:00–23:30',
    tip: 'Reserve ahead. Press the button. The beef Wellington is the kitchen signature.',
    type: 'Theatrical brasserie with champagne button at every table',
    website: 'https://bobbobricard.com',
  },

  // ── CAMDEN & KING'S CROSS ─────────────────────────────────────────────────

  {
    id: 40,
    nbhd: 'camden',
    name: 'Wellcome Collection',
    cat: 'landmark',
    emoji: '🔬',
    address: '183 Euston Rd, London NW1 2BE',
    lat: 51.5258, lng: -0.1320,
    search: 'Wellcome Collection museum London',
    note: 'A free museum on Euston Road at the intersection of medicine, life and art. Henry Wellcome\'s personal collection is remarkable — Napoleon\'s toothbrush, Darwin\'s walking stick, ancient surgical instruments, tribal medicine objects from across the world. The temporary exhibitions are consistently the most thought-provoking in London. Chronically undervisited for its quality.',
    hours: 'Tue–Wed, Fri–Sat 10:00–18:00; Thu 10:00–20:00; Sun 11:00–18:00; closed Mon',
    tip: 'Free entry always. Thursday late openings are quieter. Allow 2–3 hours.',
    type: 'Free museum of medicine, science & art',
    website: 'https://wellcomecollection.org',
  },
  {
    id: 41,
    nbhd: 'camden',
    name: 'The Roundhouse',
    cat: 'landmark',
    emoji: '🎶',
    address: 'Chalk Farm Rd, London NW1 8EH',
    lat: 51.5435, lng: -0.1466,
    search: 'Roundhouse Camden London concert venue',
    note: 'A Victorian railway engine shed on Chalk Farm Road, built in 1847 to turn locomotives, converted to an arts venue in 1966 when Charles Marowitz staged the first Happening in Britain inside it. Pink Floyd, The Doors, Jimi Hendrix and Led Zeppelin all played early shows here. The circular architecture makes it one of the very few London venues where the building adds something to every performance inside it.',
    hours: 'Event-dependent; café open daily',
    tip: 'Check roundhouse.org.uk — almost always something on. The building is worth seeing from outside even without a ticket.',
    type: 'Victorian circular live music venue (since 1966)',
    website: 'https://www.roundhouse.org.uk',
  },
  {
    id: 42,
    nbhd: 'camden',
    name: 'German Gymnasium',
    cat: 'food',
    emoji: '🥩',
    address: '1 King\'s Blvd, King\'s Cross, London N1C 4BU',
    lat: 51.5308, lng: -0.1200,
    search: 'German Gymnasium restaurant King\'s Cross London',
    note: 'Britain\'s first purpose-built gymnasium, built in 1865 for the German Gymnastics Society to train British athletes for the 1866 Olympic Games. The double-height Victorian space — original gallery rails, arched windows, exposed ironwork — is now one of the most atmospheric dining rooms in London. Contemporary Central European cooking in a room that has genuinely earned its character.',
    hours: 'Mon–Fri 07:00–23:00; Sat–Sun 08:00–23:00',
    tip: 'Book ahead for weekends. The schnitzel and the braised dishes are the kitchen\'s strengths.',
    type: 'Continental brasserie in a Victorian gymnasium (1865)',
    website: 'https://www.germangymnasium.com',
  },

  // ── NOTTING HILL ──────────────────────────────────────────────────────────

  {
    id: 43,
    nbhd: 'notting-hill',
    name: 'Portobello Road Market',
    cat: 'market',
    emoji: '🎨',
    address: 'Portobello Rd, Notting Hill, London W11',
    lat: 51.5163, lng: -0.2033,
    search: 'Portobello Road Market Notting Hill London',
    note: 'Over a mile of stalls through Notting Hill. On Saturdays over 1,000 antique dealers set up in the southern section — the world\'s largest antique street market. The middle section runs fruit, vegetables and street food all week. The northern end under the Westway flyover has the best vintage clothing. The surrounding pastel-painted terraces are what separates Notting Hill from every other London market neighbourhood.',
    hours: 'Antiques: Sat 08:00–19:00; General market: Mon–Fri 09:00–18:00',
    tip: 'Arrive before 09:00 on Saturdays for antiques. The northern vintage section under the Westway is less crowded and more interesting than the tourist end.',
    type: 'World\'s largest antique street market',
    website: 'https://www.portobelloroad.co.uk',
  },
  {
    id: 44,
    nbhd: 'notting-hill',
    name: 'Core by Clare Smyth',
    cat: 'food',
    emoji: '⭐',
    address: '92 Kensington Park Rd, London W11 2PN',
    lat: 51.5176, lng: -0.2007,
    search: 'Core by Clare Smyth restaurant Notting Hill',
    note: 'Clare Smyth holds three Michelin stars and was the first woman in the UK to do so. Her Notting Hill restaurant is the benchmark for fine dining in London. The cooking is technically impeccable and emotionally resonant — the potato dish has been written about extensively by people who do not usually write about potatoes. The set lunch is the most accessible route into a kitchen at the absolute top of its game.',
    hours: 'Tue–Sat 12:00–14:00, 18:30–22:00; closed Sun–Mon',
    tip: 'Book weeks ahead. The lunch menu at a significantly lower price delivers the same cooking. The wine pairings are exceptional.',
    type: 'Three Michelin-star restaurant',
    website: 'https://corebyclaresmyth.com',
  },
  {
    id: 45,
    nbhd: 'notting-hill',
    name: 'Luna Rossa',
    cat: 'food',
    emoji: '🍕',
    address: '192 Kensington Park Rd, London W11 2ES',
    lat: 51.5163, lng: -0.2038,
    search: 'Luna Rossa Italian restaurant Notting Hill London',
    note: 'A small neighbourhood Italian on Kensington Park Road with real regulars, real warmth and a kitchen that has settled into what it does best. Handmade pasta, excellent tiramisu, the kind of unhurried service that characterises a local place that knows it doesn\'t need to perform. A reliable excellent meal on one of London\'s most pleasant streets.',
    hours: 'Mon 18:00–23:30; Tue–Fri 12:00–16:00, 18:00–23:30; Sat 11:30–23:30; Sun 12:00–22:30',
    tip: 'Book in advance. The pasta and the tiramisu are the orders.',
    type: 'Traditional Italian neighbourhood restaurant',
    phone: '+44 20 7229 0482',
  },
  {
    id: 46,
    nbhd: 'notting-hill',
    name: 'Kalamaras Greek Taverna',
    cat: 'food',
    emoji: '🧆',
    address: '66 Inverness Mews, London W2 3JQ',
    lat: 51.5172, lng: -0.1955,
    search: 'Kalamaras Greek Taverna Notting Hill London',
    note: 'Hidden in Inverness Mews — a cobbled alley near Bayswater that most neighbourhood residents have never found. Kalamaras has been here since 1966 and the room looks it, in the best possible way. Orthodox Greek: mezze, grilled fish, slow-cooked lamb, proper stifado. Survives entirely on quality and word of mouth, in a mews that requires determination to locate.',
    hours: 'Daily 17:00–22:30',
    tip: 'Find the mews first — it\'s genuinely hidden. Booking essential. The mezze selection for two is the approach.',
    type: 'Traditional Greek taverna (since 1966)',
    phone: '+44 20 7727 9122',
  },
  {
    id: 47,
    nbhd: 'notting-hill',
    name: 'Electric Cinema',
    cat: 'landmark',
    emoji: '🎬',
    address: '191 Portobello Rd, Notting Hill, London W11 2ED',
    lat: 51.5161, lng: -0.2007,
    search: 'Electric Cinema Notting Hill London',
    note: 'Opened in 1910, making it one of Britain\'s oldest working cinemas, and still the most comfortable place to watch a film in London. Leather sofas, footstools and armchairs replaced conventional seats, a full bar service runs throughout, and just enough of the Edwardian building\'s character remains to make an evening here feel like a genuine occasion.',
    hours: 'Shows daily from approximately 12:00',
    tip: 'Book the double sofa seats at the front for a special occasion. Pre-book always — they sell out.',
    type: 'Luxury independent cinema (opened 1910)',
    website: 'https://www.electriccinema.co.uk',
  },

  // ── KENSINGTON ────────────────────────────────────────────────────────────

  {
    id: 48,
    nbhd: 'kensington',
    name: 'Natural History Museum',
    cat: 'landmark',
    emoji: '🦕',
    address: 'Cromwell Rd, Kensington, London SW7 5BD',
    lat: 51.4967, lng: -0.1764,
    search: 'Natural History Museum London',
    note: 'Alfred Waterhouse\'s Romanesque terracotta building is extraordinary before you\'ve seen a single exhibit. Inside: 80 million specimens across three billion years of life on earth. The blue whale skeleton in the Hintze Hall. The T.rex in the Dinosaurs gallery. The earthquake simulator. The basement meteorite collection that most visitors never reach. Entirely free, and impossible to exhaust.',
    hours: 'Daily 10:00–17:50',
    tip: 'Pre-book a free timed entry ticket in school holidays. The basement meteorite and mineralogy galleries are extraordinary and chronically empty.',
    type: 'World-class natural history museum (free)',
    website: 'https://www.nhm.ac.uk',
  },
  {
    id: 49,
    nbhd: 'kensington',
    name: 'Victoria & Albert Museum',
    cat: 'landmark',
    emoji: '🏺',
    address: 'Cromwell Rd, Kensington, London SW7 2RL',
    lat: 51.4966, lng: -0.1722,
    search: 'Victoria and Albert Museum London',
    note: 'The world\'s largest museum of decorative arts and design: 2.3 million objects, 145 galleries, 5,000 years of human creativity. The Cast Courts — two vast Victorian halls containing plaster casts of every major European sculpture, including a full-scale replica of Michelangelo\'s David — are genuinely overwhelming. The Friday late evenings are the time to come: quieter, atmospheric, often with live music in the courtyard. Entirely free.',
    hours: 'Daily 10:00–17:45; Fri until 22:00',
    tip: 'Friday evenings: emptier, atmospheric. The Cast Courts on Level 1 first, then follow wherever the building takes you.',
    type: 'World\'s greatest decorative arts museum (free)',
    website: 'https://www.vam.ac.uk',
  },
  {
    id: 50,
    nbhd: 'kensington',
    name: 'Science Museum',
    cat: 'landmark',
    emoji: '🚀',
    address: 'Exhibition Rd, Kensington, London SW7 2DD',
    lat: 51.4978, lng: -0.1748,
    search: 'Science Museum London',
    note: 'The Apollo 10 command module that orbited the Moon in 1969 is here, in a case you can walk around, looking battered and impossibly small. So is Stephenson\'s original Rocket, Crick and Watson\'s DNA model and the first prototype of the World Wide Web. The Space Gallery alone justifies the journey. Entirely free for the main galleries.',
    hours: 'Daily 10:00–18:00',
    tip: 'Free for permanent galleries. The Space Gallery and Making the Modern World at ground level are the first stops.',
    type: 'World-class science & technology museum (free)',
    website: 'https://www.sciencemuseum.org.uk',
  },
  {
    id: 52,
    nbhd: 'kensington',
    name: 'The Harwood Arms',
    cat: 'food',
    emoji: '🥩',
    address: 'Walham Grove, Fulham, London SW6 1QP',
    lat: 51.4787, lng: -0.1946,
    search: 'Harwood Arms Fulham London Sunday roast',
    note: 'The only pub in London with a Michelin star, sitting on a quiet Fulham street and looking, from the outside, entirely like a normal neighbourhood pub. The kitchen focuses on British game and seasonal produce with a precision that most restaurants twice the price cannot match. The venison Scotch egg is a London dish in itself. The Sunday roast books up months in advance.',
    hours: 'Mon–Fri 18:00–22:00; Sat 12:00–15:00, 18:00–22:00; Sun 12:00–15:30',
    tip: 'Sunday lunch: book months ahead, not weeks. The set weekday dinner is accessible and the same quality.',
    type: 'London\'s only Michelin-starred pub',
    website: 'https://www.harwoodarms.com',
  },

  // ── GREENWICH ─────────────────────────────────────────────────────────────

  {
    id: 53,
    nbhd: 'greenwich',
    name: 'Royal Naval College',
    cat: 'landmark',
    emoji: '⚓',
    address: 'King William Walk, Greenwich, London SE10 9NN',
    lat: 51.4828, lng: -0.0073,
    search: 'Royal Naval College Greenwich London',
    note: 'Christopher Wren\'s greatest secular building — a UNESCO World Heritage Site, generally overlooked by visitors hurrying to the Observatory. The twin domed buildings framing the Queen\'s House create the most perfectly composed view in London, best seen from the river. The Painted Hall inside is called the Sistine Chapel of Britain: James Thornhill spent 19 years painting the ceiling and walls. Free to enter.',
    hours: 'Grounds daily 08:00–18:00; Painted Hall daily 10:00–17:00',
    tip: 'The Painted Hall first — arrive early. The grounds are free at any time.',
    type: 'UNESCO World Heritage baroque complex (free)',
    website: 'https://ornc.org',
  },
  {
    id: 54,
    nbhd: 'greenwich',
    name: 'Cutty Sark',
    cat: 'landmark',
    emoji: '⛵',
    address: 'King William Walk, Greenwich, London SE10 9HT',
    lat: 51.4831, lng: -0.0094,
    search: 'Cutty Sark Greenwich London',
    note: 'Built in 1869 and the world\'s sole surviving tea clipper. After a fire in 2007 she was restored and raised on a glass base — walk beneath the copper hull and understand why this ship averaged 17 knots on the Australia wool run. The extraordinary hydrodynamic form is only properly visible from below.',
    hours: 'Daily 10:00–17:00',
    tip: 'Walk beneath the hull for the most dramatic perspective. Combine with the Royal Naval College next door.',
    type: 'Restored 1869 tea clipper — the world\'s last',
    website: 'https://www.rmg.co.uk/cutty-sark',
  },
  {
    id: 55,
    nbhd: 'greenwich',
    name: 'National Maritime Museum',
    cat: 'landmark',
    emoji: '🧭',
    address: 'Romney Rd, Greenwich, London SE10 9NF',
    lat: 51.4813, lng: -0.0052,
    search: 'National Maritime Museum Greenwich London',
    note: 'The world\'s largest maritime museum. Nelson\'s uniform from Trafalgar is here — the bullet hole in the left shoulder perfectly preserved. So are charts from Cook\'s Pacific voyages, a 17th-century brass astrolabe, and a complete ship\'s binnacle from Shackleton\'s Endurance. 500 years of Britain and the sea, with the emotional range and depth of great storytelling. Free.',
    hours: 'Daily 10:00–17:00',
    tip: 'Free entry. The Nelson, Navy, Nation gallery is the emotional core. Allow two hours minimum.',
    type: 'World\'s largest maritime museum (free)',
    website: 'https://www.rmg.co.uk/national-maritime-museum',
  },
  {
    id: 56,
    nbhd: 'greenwich',
    name: 'Royal Observatory',
    cat: 'nature',
    emoji: '🔭',
    address: 'Blackheath Ave, Greenwich, London SE10 8XJ',
    lat: 51.4778, lng: 0.0015,
    search: 'Royal Observatory Greenwich prime meridian London',
    note: 'Christopher Wren built this for Charles II in 1675, and from this point the world\'s clocks are set. Stand on the brass Meridian Line at longitude 0° 0\' 0\" — one foot in the eastern hemisphere, one in the western. The hilltop gives one of the finest free panoramas in London: Canary Wharf, the Thames bending east, the City towers on the horizon. At night a green laser shoots north from the building along the meridian.',
    hours: 'Daily 10:00–17:00',
    tip: 'The panorama is free — no museum ticket needed. Visit at golden hour for the best light over the city.',
    type: 'Royal Observatory & Prime Meridian — 0° longitude',
    website: 'https://www.rmg.co.uk/royal-observatory',
  },
  {
    id: 57,
    nbhd: 'greenwich',
    name: 'Greenwich Market',
    cat: 'market',
    emoji: '🎪',
    address: '5B Greenwich Market, London SE10 9HZ',
    lat: 51.4824, lng: -0.0093,
    search: 'Greenwich Market London',
    note: 'A covered market operating since 1737, now housing around 120 stalls under a Victorian building at the heart of Greenwich\'s heritage district. Street food at lunchtime (some of the best in south London), craft and art at weekends, antiques scattered throughout. Small enough to do properly in an hour, perfectly placed between the Royal Naval College and the Cutty Sark.',
    hours: 'Daily 10:00–17:30',
    tip: 'Lunchtime on a weekday: street food stalls at full capacity, manageable crowds.',
    type: 'Historic covered artisan market (since 1737)',
    website: 'https://greenwichmarket.london',
  },
  {
    id: 58,
    nbhd: 'greenwich',
    name: 'Greenwich Park',
    cat: 'nature',
    emoji: '🌳',
    address: 'Greenwich Park, London SE10 8QY',
    lat: 51.4785, lng: -0.0024,
    search: 'Greenwich Park London views',
    note: 'The oldest enclosed Royal Park in London. Walk up through the avenue of chestnut trees to the hilltop and turn around: Canary Wharf, the O2, the Thames bending east, the City towers. One of the finest free views in Britain. In the deer enclosure in the northeast corner — often missed entirely — fallow deer graze under ancient oaks as if the city does not exist.',
    hours: 'Daily 06:00–21:00 (summer) / 06:00–18:00 (winter)',
    tip: 'Hilltop near the Observatory for the view. Early morning for the light. Find the deer enclosure in the northeast corner — empty, peaceful, easy to miss.',
    type: 'Royal park with panoramic London views',
    website: 'https://www.royalparks.org.uk/parks/greenwich-park',
  },

  // ── SHOREDITCH & SPITALFIELDS ─────────────────────────────────────────────

  {
    id: 63,
    nbhd: 'shoreditch',
    name: 'Dennis Severs\' House',
    cat: 'landmark',
    emoji: '🕯️',
    address: '18 Folgate St, Spitalfields, London E1 6BX',
    lat: 51.5218, lng: -0.0758,
    search: 'Dennis Severs House Spitalfields London',
    note: 'The most extraordinary thing in London that almost no one knows about. In 1979, the American artist Dennis Severs bought a Georgian terraced house in Spitalfields and spent his life arranging it as a \'still-life drama\': ten rooms across 300 years, as if the Huguenot silk-weaver family who lived there from 1724 has just stepped out. Candles burning. Food half-eaten. Coals glowing. A cat asleep. You move through it in silence. The Monday evening candlelit session is one of the most singular experiences available in any city.',
    hours: 'Sun 12:00–16:00; Mon 12:00–14:00; Mon evenings (candlelit) 18:00–21:00 — must book',
    tip: 'Book the Monday evening candlelit session. It is the intended experience and nothing in London approaches it.',
    type: 'An immersive 18th-century Georgian time capsule — unique',
    website: 'https://www.dennissevershouse.co.uk',
  },
  {
    id: 64,
    nbhd: 'shoreditch',
    name: 'Columbia Road Flower Market',
    cat: 'market',
    emoji: '🌺',
    address: 'Columbia Rd, Bethnal Green, London E2 7RG',
    lat: 51.5288, lng: -0.0726,
    search: 'Columbia Road Flower Market London Sunday',
    note: 'Every Sunday morning, a narrow Victorian street in Bethnal Green becomes 60 stalls of cut flowers, bulbs, trees and plants — the most atmospheric market in London. The surrounding independent shops (ceramics, vintage, coffee) open only on market day. The traders, bellowing prices over each other in the East End tradition, are as much a part of the experience as the flowers. Go early for the energy. Go at noon for the deals.',
    hours: 'Sundays only, 08:00–15:00',
    tip: 'Sunday only, arrive by 09:00. Stay for the independent shops on Columbia Road — they only open on market day.',
    type: 'Sunday flower market (Sundays only)',
    website: 'https://columbiaroad.info',
  },
  {
    id: 65,
    nbhd: 'shoreditch',
    name: 'Beigel Bake',
    cat: 'cafe',
    emoji: '🥯',
    address: '159 Brick Lane, London E1 6SB',
    lat: 51.5227, lng: -0.0720,
    search: 'Beigel Bake Brick Lane London salt beef',
    note: 'Open 24 hours a day, every day, since 1977 — apparently never closed once. The salt beef beigel (hand-formed bread, slow-cooked beef, mustard, pickled cucumber) costs well under £5 and is one of the most purely satisfying things you can eat in London at any hour. Cash only. The queue at 02:00 on a Saturday is a London institution.',
    hours: 'Open 24 hours, 7 days',
    tip: 'Salt beef beigel, mustard, extra pickle. Cash only. No ambience. That is entirely correct.',
    type: '24-hour bakery — open since 1977, cash only',
    website: 'https://bricklanebeigel.co.uk',
  },
  {
    id: 66,
    nbhd: 'shoreditch',
    name: 'Dishoom Shoreditch',
    cat: 'food',
    emoji: '🍛',
    address: '7 Boundary St, Shoreditch, London E2 7JE',
    lat: 51.5238, lng: -0.0739,
    search: 'Dishoom Shoreditch London Bombay café',
    note: 'Modelled on the Irani cafés of Bombay — all-day dining rooms established by the Persian Zoroastrian community in the early 20th century. The Shoreditch branch on Boundary Street is the most atmospheric of the London sites, in a converted warehouse with a raised mezzanine and the particular low-lit noise of a room doing everything right. The black dhal has been slow-cooked for 24 hours every day since they opened. The bacon naan at breakfast is a separate pilgrimage.',
    hours: 'Mon–Thu 08:00–23:00; Fri 08:00–midnight; Sat 09:00–midnight; Sun 09:00–23:00',
    tip: 'The black dhal, the lamb chops, the bacon naan at breakfast. The house chai. Queues form but move. Breakfast is the quieter option.',
    type: 'Bombay Irani café — all-day restaurant',
    website: 'https://www.dishoom.com/shoreditch/',
  },

  // ── HARRY POTTER & NEW RESTAURANTS ───────────────────────────────────────

  {
    id: 67,
    nbhd: 'camden',
    name: 'Platform 9¾',
    cat: 'landmark',
    emoji: '🪄',
    address: 'King\'s Cross Station, London N1C 4AP',
    lat: 51.5322, lng: -0.1237,
    search: 'Platform 9¾ King\'s Cross London Harry Potter',
    note: 'The trolley vanishing through the wall between platforms 9 and 10 at King\'s Cross is one of the most recognisable images in contemporary fiction, and the real location is here — a bronze trolley embedded in the station\'s western wall, with a scarf fluttering halfway through the brickwork. The Harry Potter shop beside it is absurdly well-stocked for something tucked inside a working train station. Free to visit and always busy, but the queue for the photo moves quickly.',
    hours: 'Daily during station opening hours (approx 05:00–midnight). Shop: Mon–Sat 08:00–22:00; Sun 09:00–21:00',
    tip: 'A member of staff holds the scarf for the photo — join the queue and they\'ll throw it dramatically. Busiest at weekends; early weekday mornings are much quieter.',
    type: 'Harry Potter filming location & shop',
    website: 'https://www.harrypotterplatform934.com',
  },
  {
    id: 68,
    nbhd: 'covent-garden',
    name: 'Australia House',
    cat: 'landmark',
    emoji: '🏦',
    address: 'The Strand, London WC2B 4LA',
    lat: 51.5128, lng: -0.1168,
    search: 'Australia House Strand London Gringotts Harry Potter',
    note: 'The grand Edwardian building on the Strand that served as Gringotts Wizarding Bank in the first Harry Potter films. The Great Hall interior — marble columns, chandeliers, the entire banking chamber — was used exactly as seen on screen. Australia House is the Australian High Commission and opens to the public on selected days, particularly around ANZAC Day and during open house events. The exterior and the banking hall entrance are photogenic from the pavement at any time.',
    hours: 'Exterior always accessible. Interior open on selected public days — check australiahc.org.uk',
    tip: 'Even without entering, the Strand façade is unmistakably Gringotts. The interior open days are announced in advance and worth timing a visit around.',
    type: 'Harry Potter filming location — Gringotts Bank exterior & interior',
    website: 'https://uk.embassy.gov.au/lhlh/australiahouse.html',
  },
  {
    id: 69,
    nbhd: 'covent-garden',
    name: 'The Palomar',
    cat: 'food',
    emoji: '🫙',
    address: '34 Rupert St, Soho, London W1D 6DN',
    lat: 51.5121, lng: -0.1326,
    search: 'The Palomar restaurant Soho London Jerusalem',
    note: 'A small Soho restaurant drawing on the cooking of Jerusalem and the Eastern Mediterranean — silky hummus, slow-cooked lamb, yogurt-dressed vegetables, raw fish with bold seasoning. The counter seats at the open kitchen are the most sought-after in the house: you watch everything being made and the chefs talk you through it. Loud, intimate, exhilarating. Widely considered one of the best restaurants in London.',
    hours: 'Mon–Sat 12:00–14:30, 17:30–22:30; Sun 12:00–15:30',
    tip: 'Book the counter seats for the full experience. The lamb neck and the raw fish preparations are the dishes to order. Go hungry.',
    type: 'Jerusalem & Eastern Mediterranean restaurant',
    website: 'https://www.thepalomar.co.uk',
  },
  {
    id: 70,
    nbhd: 'covent-garden',
    name: 'Hoppers',
    cat: 'food',
    emoji: '🥣',
    address: '49 Frith St, Soho, London W1D 4SG',
    lat: 51.5131, lng: -0.1312,
    search: 'Hoppers restaurant Soho London Sri Lankan',
    note: 'Named after the hopper — a bowl-shaped fermented rice and coconut crêpe that is the foundation of Sri Lankan breakfast — Hoppers opened in Soho in 2015 and immediately had queues around the corner that have not really stopped. Michelin Bib Gourmand every year since 2016. The egg hopper (a whole egg cooked in the centre of the bowl) with three chutneys and a bone marrow varuval on the side is one of the most distinctive lunch dishes in London. The kottu roti is the other unmissable order.',
    hours: 'Mon–Sat 12:00–14:30, 17:30–22:30; closed Sun',
    tip: 'Reservations now available online — book ahead for weekends. Walk-ins join a virtual queue via their website on arrival. The egg hopper and the bone marrow varuval are non-negotiable.',
    type: 'Sri Lankan restaurant — hoppers & kottu specialists',
    website: 'https://www.hopperslondon.com',
  },
  {
    id: 71,
    nbhd: 'shoreditch',
    name: 'Rochelle Canteen',
    cat: 'food',
    emoji: '🔔',
    address: 'Arnold Circus, Shoreditch, London E2 7ES',
    lat: 51.5252, lng: -0.0762,
    search: 'Rochelle Canteen Arnold Circus Shoreditch London',
    note: 'Hidden inside a converted Victorian school bike shed on Arnold Circus, behind a locked gate with a bell you have to ring to enter. Margot Henderson and Melanie Arnold opened it in 2004 as a canteen for the designers and artists working in the school building around it, and it has remained almost unchanged ever since: a blackboard menu, a courtyard garden, seasonal British cooking of the most honest kind. Almost no tourists know it exists. One of the most genuinely local places in London.',
    hours: 'Mon–Fri 09:00–15:30 (lunch 12:00–15:00); closed weekends',
    tip: 'Ring the bell at the gate on Arnold Circus. Lunch only on weekdays. The menu is short, seasonal and changes daily — order whatever is written on the board.',
    type: 'Hidden seasonal British canteen — ring the bell to enter',
    website: 'https://www.arnoldandhenderson.com/rochelle-canteen',
  },
  {
    id: 72,
    nbhd: 'covent-garden',
    name: 'Rules',
    cat: 'food',
    emoji: '🍮',
    address: '35 Maiden Lane, Covent Garden, London WC2E 7LB',
    lat: 51.5115, lng: -0.1237,
    search: 'Rules restaurant Covent Garden London oldest',
    note: 'Established in 1798, Rules is London\'s oldest restaurant — still on the same Maiden Lane site, still serving British game, pies and puddings, still decorated with the cartoons and theatrical portraits that have accumulated across two and a half centuries. Charles Dickens was a regular. Graham Greene wrote here. The game comes from the restaurant\'s own Teesdale estate. The suet puddings, the potted shrimps, the roast grouse in season: this is the cooking of British history served in a room that has witnessed most of it.',
    hours: 'Mon–Sat 12:00–23:30; Sun 12:00–22:30',
    tip: 'Order game — it\'s what the kitchen has done for 225 years. The potted shrimps to start and a suet pudding to finish are obligatory. Book ahead for weekends.',
    type: 'London\'s oldest restaurant (established 1798)',
    website: 'https://rules.co.uk',
  },

];
