// A Perfect Day — Ludara / Nashville
// data.js — 50 curated places
//
// Demo guide for A Perfect Day platform.
// Sources: TimeOut Nashville, The Infatuation, Resy, Nashville Guru, Nashville Scene,
//          Nashville Lifestyles, Nashvegas.com, Visit Nashville, Tennessee State Parks.
//
// All hours, addresses and GPS coordinates verified April 2026.
//
// Neighbourhoods:
//   downtown / germantown / gulch / east / 12south / midtown / parks

const PLACES = [

  // ─── DOWNTOWN / SOBRO ─────────────────────────────────────────────────────

  {
    id: 1,
    nbhd: "downtown",
    name: "Ryman Auditorium",
    cat: "landmark",
    emoji: "🎭",
    address: "116 Rep. John Lewis Way N, Downtown",
    lat: 36.1616,
    lng: -86.7785,
    search: "Ryman Auditorium Nashville",
    note: "Built in 1892 as a gospel tabernacle, the Ryman became home of the Grand Ole Opry from 1943 to 1974 and is now recognised as one of the most acoustically perfect concert venues in America. Daytime tours open the sanctuary, backstage corridors, and the very dressing rooms where Hank Williams and Patsy Cline prepared to perform. As Nashvegas records: 'The Ryman was restored in the 1990s and now operates as one of the most acoustically perfect concert venues in America.' The wooden pews, stained-glass windows, and cathedral quiet make it feel sacred even when the stage is empty.",
    hours: "Daily 9am–4pm; shows most evenings",
    tip: "Book the backstage tour in advance — it sells out. The self-guided tour includes a photo opportunity on the famous stage.",
    type: "Historic Music Venue & Museum",
    blog: "",
    phone: "+1 615-889-3060",
    website: "https://www.ryman.com",
  },

  {
    id: 2,
    nbhd: "downtown",
    name: "Country Music Hall of Fame & Museum",
    cat: "landmark",
    emoji: "🎵",
    address: "222 Rep. John Lewis Way S, Downtown",
    lat: 36.1577,
    lng: -86.7764,
    search: "Country Music Hall of Fame Nashville",
    note: "The permanent collection traces country music's roots from its Appalachian folk origins through the outlaw movement, the stadium era, and the genre's contemporary diversity — told through instruments, stage costumes, rare recordings, and the Hall of Fame rotunda where each inductee's medallion lines the curved wall. Nashvegas: 'The Hall of Fame rotunda is genuinely moving in a way that's hard to explain and easy to experience.' Recent exhibitions have covered Dolly Parton's complete archive and Johnny Cash's visual art. Allow at least three hours.",
    hours: "Daily 9am–5pm",
    tip: "Combination tickets with RCA Studio B on Music Row offer the best value in Nashville music tourism. Book Studio B in advance — tours are limited in size.",
    type: "Music History Museum",
    blog: "",
    phone: "+1 615-416-2001",
    website: "https://www.countrymusichalloffame.org",
  },

  {
    id: 3,
    nbhd: "downtown",
    name: "National Museum of African American Music",
    cat: "landmark",
    emoji: "🥁",
    address: "510 Broadway, Downtown",
    lat: 36.1588,
    lng: -86.7791,
    search: "National Museum of African American Music Nashville",
    note: "The only museum in the United States dedicated to preserving and celebrating the genres created, influenced, and inspired by African Americans — blues, jazz, gospel, R&B, soul, and hip-hop. Six immersive galleries trace over 50 musical styles through artefacts, documentary film, and interactive technology. The RiSE experience lets visitors add their own voice to the story. Quietly one of the most moving stops in all of Nashville, and persistently overlooked in favour of louder attractions nearby.",
    hours: "Tue–Sat 9am–5pm, Sun 12pm–5pm",
    tip: "Allow two full hours. The RiSE experience is included in admission and is genuinely powerful — do not skip it.",
    type: "Cultural & Music Museum",
    blog: "",
    phone: "+1 615-301-8724",
    website: "https://nmaam.org",
  },

  {
    id: 4,
    nbhd: "downtown",
    name: "Hatch Show Print",
    cat: "market",
    emoji: "🖨️",
    address: "224 Rep. John Lewis Way S, Downtown",
    lat: 36.1576,
    lng: -86.7766,
    search: "Hatch Show Print Nashville",
    note: "One of the oldest continuously operating letterpress print shops in America, founded in 1879. The workshop designed iconic concert posters for the Grand Ole Opry, the Ryman, and virtually every major country artist of the 20th century. You can watch printers pulling runs on century-old presses, browse the archive of original designs, and buy freshly printed posters — made minutes before you arrived. A working museum of Nashville's visual and musical heritage.",
    hours: "Mon–Sat 9am–5pm, Sun 10am–5pm",
    tip: "Browse the poster bins — vintage show reprints often sell for well under $30. The best souvenir in Nashville.",
    type: "Historic Letterpress Workshop",
    blog: "",
    phone: "+1 615-577-7910",
    website: "https://hatchshowprint.com",
  },

  {
    id: 5,
    nbhd: "downtown",
    name: "Tootsie's Orchid Lounge",
    cat: "pub",
    emoji: "🎸",
    address: "422 Broadway, Downtown",
    lat: 36.1601,
    lng: -86.7789,
    search: "Tootsies Orchid Lounge Nashville Broadway honky tonk historic",
    note: "For decades, Tootsie's served as the unofficial backstage of the Grand Ole Opry — a narrow alley connecting directly to the Ryman's stage door, where Hank Williams, Willie Nelson, and Kris Kristofferson nursed drinks between sets. Nashvegas: 'Tootsie's has a documented history of serving as the unofficial backstage for Opry performers who needed a drink between sets during the Ryman years.' The walls are covered in photographs and memorabilia. Music starts before noon and runs to 3am. It's loud, it's purple, and it's the most historically significant bar on Broadway.",
    hours: "Daily 10am–3am (live music from open)",
    tip: "Go upstairs for a slightly quieter experience with a view down Broadway. Weekday afternoons are the best time to actually hear the musicians.",
    type: "Historic Honky-Tonk",
    blog: "",
    phone: "+1 615-726-0463",
    website: "https://tootsies.net",
  },

  {
    id: 6,
    nbhd: "downtown",
    name: "Robert's Western World",
    cat: "pub",
    emoji: "🤠",
    address: "416 Broadway, Downtown",
    lat: 36.1601,
    lng: -86.7788,
    search: "Roberts Western World Nashville classic country rockabilly Broadway bar",
    note: "As close to the real thing as Broadway gets. Robert's is where locals direct visitors who want authentic classic country — not bro-country or cover bands, but the genuine lineage: honky-tonk, rockabilly, and country swing by musicians who actually know the music. TimeOut Nashville: 'Robert's is as close to historic as it gets on Broadway.' The boot shop that used to occupy the space still provides the décor. Order a Recession Special (burger, chips, Moon Pie, and PBR) and settle in.",
    hours: "Daily 11am–3am (live music from open)",
    tip: "The Recession Special ($10) is a Nashville institution: burger, bag of chips, a Moon Pie, and a PBR. Exactly what it sounds like — and exactly what you want.",
    type: "Classic Honky-Tonk",
    blog: "",
    phone: "+1 615-244-9552",
    website: "https://robertswesternworld.com",
  },

  {
    id: 7,
    nbhd: "downtown",
    name: "Crema Coffee Roasters",
    cat: "cafe",
    emoji: "☕",
    address: "15 Lea Ave, SoBro",
    lat: 36.1568,
    lng: -86.7764,
    search: "Crema Coffee Roasters Nashville SoBro specialty coffee",
    note: "The Infatuation puts it plainly: leaving Crema off a Nashville coffee guide would be a crime akin to insulting Dolly Parton. The SoBro location has a large working space and a wooden loft patio facing the street. The drip coffee is the smoothest in the city; specialty drinks are interesting without masking the beans. They hold regular coffee classes in the back room and operate a zero-waste commitment. An institution that has earned its reputation every morning since 2009.",
    hours: "Mon–Fri 7am–5pm, Sat–Sun 8am–5pm",
    tip: "A short walk from Broadway and the Convention Center — the ideal civilised start before the honky-tonks wake up.",
    type: "Specialty Coffee Roastery",
    blog: "",
    phone: "+1 615-255-8311",
    website: "https://crema-coffee.com",
  },

  {
    id: 41,
    nbhd: "downtown",
    name: "The Listening Room Cafe",
    cat: "pub",
    emoji: "🎤",
    address: "233 4th Ave S, SoBro",
    lat: 36.1573,
    lng: -86.7754,
    search: "Listening Room Cafe Nashville SoBro songwriter rounds",
    note: "Nashville's most accessible songwriter showcase — a seated, dinner-and-show venue where artists perform round-style: four songwriters sitting in a circle, swapping songs and the stories behind them. This is how Nashville's music industry has worked for generations, and the Listening Room makes it visible and intimate. Performers play originals and explain the compositional choices behind them. No cover bands, no karaoke — just working songwriters revealing how country hits are actually made.",
    hours: "Shows most nights; dinner from 5pm. Check schedule online",
    tip: "Reserve a table — the room fills quickly. The songwriter round format rewards paying close attention; these are the people who actually wrote the hits you recognise.",
    type: "Songwriter Round Venue",
    blog: "",
    phone: "+1 615-259-3600",
    website: "https://thelisteningroomcafe.com",
  },

  {
    id: 42,
    nbhd: "downtown",
    name: "Skull's Rainbow Room",
    direct_image: "https://static.wixstatic.com/media/88a28e_3891e119e24248288d36a7cd052d22db~mv2_d_4608_3456_s_4_2.jpg",
    cat: "pub",
    emoji: "🎷",
    address: "222 Printers Alley, Downtown",
    lat: 36.1631,
    lng: -86.7793,
    search: "Skulls Rainbow Room Printers Alley Nashville jazz burlesque historic",
    note: "Hidden in Printers Alley — Nashville's storied historic nightclub district — Skull's has been operating since 1948 and is among the city's oldest continuously running live music venues. Live jazz plays every night in a room of rich mahogany, red velvet, and low lighting. On Friday and Saturday nights, the room adds a burlesque show that has been a Nashville institution for decades. First Time Visiting calls it 'a one-stop shop: come for a drink, stay for dinner and a nightly show.' Printers Alley is a short walk from Broadway but feels like a different era entirely.",
    hours: "Tue–Sat 5pm–2am; burlesque shows Fri–Sat nights",
    tip: "Book the dinner-and-show package on Friday or Saturday. Arrive in the alley from Commerce St — the entrance is deliberately understated.",
    type: "Historic Jazz Club & Supper Club",
    blog: "",
    phone: "+1 615-810-9631",
    website: "https://skullsrainbowroom.com",
  },

  {
    id: 45,
    nbhd: "downtown",
    name: "3rd & Lindsley",
    cat: "pub",
    emoji: "🎶",
    address: "818 3rd Ave S, SoBro",
    lat: 36.1552,
    lng: -86.7743,
    search: "3rd and Lindsley Nashville SoBro music venue blues Americana roots",
    note: "Nashville's most reliable mid-size music venue for blues, Americana, and roots music — a full restaurant by day that transforms into a serious listening room by night. The programming is eclectic and consistently excellent: national touring acts, local legends, and residency nights that become Nashville events. The sight lines are good, the sound system excellent, and the kitchen serves proper food throughout the evening. A full meal and a great band for significantly less than a Broadway night out.",
    hours: "Mon–Sat from 5pm; shows most nights. Check schedule",
    tip: "Check the weekly blues jams and residency nights — that's when the room is best. Tickets are usually $10–$25 and can be bought at the door.",
    type: "Blues & Roots Music Venue",
    blog: "",
    phone: "+1 615-259-9891",
    website: "https://3rdandlindsley.com",
  },

  {
    id: 46,
    nbhd: "downtown",
    name: "Cumberland Riverfront Park",
    cat: "nature",
    emoji: "🌊",
    address: "1 Riverfront Park, Downtown",
    lat: 36.1651,
    lng: -86.7725,
    search: "Cumberland Riverfront Park Nashville",
    direct_image: "https://upload.wikimedia.org/wikipedia/commons/9/9b/4th_of_July_Riverfront_Park_2010_001.jpg",
    note: "The downtown waterfront stretches along the west bank of the Cumberland River from the Seigenthaler Pedestrian Bridge south to the Ascend Amphitheater. The riverwalk offers the best unobstructed views of the Nashville skyline and connects directly to the Shelby Street Pedestrian Bridge — a ten-minute walk to East Nashville's Five Points area. On summer evenings the amphitheater's lawn shows and the waterfront food trucks create a genuinely festive open-air scene that costs nothing to join.",
    hours: "Open daily, dawn to dusk",
    tip: "Walk north to the John Seigenthaler Pedestrian Bridge at dusk for the best skyline view in Nashville. Free, uncrowded, and genuinely beautiful.",
    type: "Waterfront Park",
    blog: "",
    phone: "",
    website: "",
  },

  // ─── GERMANTOWN ───────────────────────────────────────────────────────────

  {
    id: 8,
    nbhd: "germantown",
    name: "City House",
    cat: "food",
    emoji: "🍕",
    address: "1222 4th Ave N, Germantown",
    lat: 36.1711,
    lng: -86.7830,
    search: "City House Nashville Germantown Tandy Wilson James Beard Award restaurant",
    note: "Chef and owner Tandy Wilson was the first Nashville chef to win the James Beard Award for Best Chef Southeast (2016). City House is where that reputation was built: rustic Italian-influenced food with a Southern American character — belly ham pizza, house-made pasta, excellent charcuterie — in a warm, unfussy room inside a converted Victorian building. As one TripAdvisor regular writes: 'Tandy Wilson has a true gift. I'd say he is probably one of the best.' Sunday Supper is a local institution worth planning around.",
    hours: "Mon–Thu 5–10pm, Fri–Sun 5–11pm",
    tip: "The belly ham pizza is the cult order. Come for Sunday Supper if you can plan ahead — it has a fiercely loyal local following.",
    type: "James Beard Italian-Southern",
    blog: "",
    phone: "+1 615-736-5838",
    website: "https://cityhouserestaurant.com",
  },

  {
    id: 9,
    nbhd: "germantown",
    name: "Rolf & Daughters",
    cat: "food",
    emoji: "🍝",
    address: "700 Taylor St, Germantown",
    lat: 36.1699,
    lng: -86.7833,
    search: "Rolf and Daughters Nashville Germantown pasta Philip Krajeck restaurant",
    note: "Installed inside the historic Werthan factory building, Philip Krajeck's Germantown flagship was named one of America's Best New Restaurants by both Bon Appétit and Esquire shortly after opening. A decade on it has only deepened its identity: handmade pastas, seasonal vegetables treated with imagination, a natural wine list that rewards exploration, and a room that buzzes with the particular energy of a restaurant that knows exactly what it is. Resy counts it among Nashville's stalwarts that 'continue to shine with inspired takes on local ingredients.'",
    hours: "Tue–Thu 5–10pm, Fri–Sat 5–11pm, Sun 5–9pm",
    tip: "Reserve at the communal table or chef's bar if you want a more spontaneous evening — they hold walk-in spots at both.",
    type: "Modern Pasta & Seasonal Cuisine",
    blog: "",
    phone: "+1 615-866-9897",
    website: "https://rolfanddaughters.com",
  },

  {
    id: 10,
    nbhd: "germantown",
    name: "Henrietta Red",
    cat: "food",
    emoji: "🦪",
    address: "1200 4th Ave N, Germantown",
    lat: 36.1712,
    lng: -86.7832,
    search: "Henrietta Red Nashville oyster bar Germantown Julia Sullivan James Beard",
    direct_image: "https://resizer.otstatic.com/v4/photos/65574446-3?width=800&height=600&format=jpeg",
    note: "Chef Julia Sullivan's James Beard–nominated oyster bar has a rotating selection of freshly shucked Gulf and East Coast oysters, a beautiful enclosed patio, and a menu of fresh, seasonal sharing plates. The barroom happy hour is one of the best in Nashville. OpenTable describes the restaurant's approach as 'fostering an inviting atmosphere ideal for meals with familiar and new friends.' Weekend brunch draws a neighbourhood crowd that actually lives nearby.",
    hours: "Tue–Thu 5–10pm, Fri 5–11pm, Sat–Sun 10am–11pm",
    tip: "Happy hour (Tue–Fri 5–6:30pm): half-price oysters and craft cocktails at the bar. One of the great-value evenings in Nashville.",
    type: "Oyster Bar & Seasonal Restaurant",
    blog: "",
    phone: "+1 615-490-8042",
    website: "https://henriettared.com",
  },

  {
    id: 11,
    nbhd: "germantown",
    name: "Nashville Farmers' Market",
    cat: "market",
    emoji: "🥦",
    address: "900 Rosa L. Parks Blvd, Germantown",
    lat: 36.1747,
    lng: -86.7844,
    search: "Nashville Farmers Market Rosa Parks Boulevard",
    note: "A year-round indoor market at the northern edge of Germantown with a farmers' section selling Tennessee-grown produce and a covered Market House with over two dozen independent food stalls — everything from authentic Vietnamese and Thai to wood-fired pizza and freshly pressed juice. The most honest cross-section of Nashville's eating habits: no marketing, no pretence, good food at fair prices in an open-air setting that rewards wandering. The weekend flea market adds vintage and handmade goods.",
    hours: "Daily 8am–6pm (Farm Market); Food stalls from 10am",
    tip: "Come Saturday morning for the most active produce market. The weekday lunch crowd in the food hall is excellent and completely unhurried.",
    type: "Indoor Farmers Market & Food Hall",
    blog: "",
    phone: "+1 615-880-2001",
    website: "https://nashvillefarmersmarket.org",
  },

  {
    id: 12,
    nbhd: "germantown",
    name: "Bicentennial Capitol Mall State Park",
    cat: "nature",
    emoji: "🌿",
    address: "600 James Robertson Pkwy, Germantown",
    lat: 36.1674,
    lng: -86.7847,
    search: "Bicentennial Capitol Mall Nashville Tennessee",
    note: "A 19-acre linear park stretching along the north face of the Tennessee State Capitol, designed as a living history lesson. A 200-foot granite map of Tennessee is embedded in the ground at its heart; 95 fountains represent the state's river system; a 300-foot timeline wall traces Tennessee's history from 1796 to today. The views looking up to the Capitol dome are striking. On weekday mornings it's almost entirely quiet — one of the most underrated outdoor spaces in all of downtown Nashville.",
    hours: "Open daily, dawn to dusk",
    tip: "Walk through on a clear morning for the best view up the mall to the Capitol dome. Combine with the Farmers' Market five minutes north.",
    type: "State Park & Historic Mall",
    blog: "",
    phone: "+1 615-741-5280",
    website: "https://tnstateparks.com/parks/bicentennial-capitol-mall",
  },

  {
    id: 13,
    nbhd: "germantown",
    name: "Babychan",
    cat: "cafe",
    emoji: "🍡",
    address: "1313 Adams St, Neuhoff District, Germantown",
    lat: 36.1700,
    lng: -86.7800,
    search: "Babychan Nashville Germantown Japanese bakery cafe Neuhoff",
    note: "From the husband-and-wife team behind Kisser — chefs Brian Lea and Leina Horii — Babychan brings Japanese and French bakery culture to the Neuhoff District in Germantown. The all-day menu runs from technique-driven morning pastries (sesame swiss rolls, yuzu tarts, cinnamon toast on house-baked Japanese milk bread) through katsu sandwiches, curry pan, rice omelettes, and onigiri at lunch, with coffee, tea, sake, and natural wine throughout. The Infatuation calls it 'the Japanese bakery and café Nashville didn't know it desperately needed.' Named Best New Café and Bakery by the Nashville Scene 2025. The grab-and-go counter opens at 8am; full table service from 10am.",
    hours: "Mon & Wed–Fri 8am–3pm, Sat–Sun 8am–3pm (closed Tue); table service from 10am",
    tip: "Come before 9am on weekends to claim a pastry case seat without waiting. The sesame swiss roll and yuzu tart sell out fast — they're worth a pre-order on their website.",
    type: "Japanese Bakery & All-Day Café",
    blog: "",
    phone: "",
    website: "https://www.babychancafe.com",
  },

  // ─── THE GULCH ────────────────────────────────────────────────────────────

  {
    id: 14,
    nbhd: "gulch",
    name: "Frist Art Museum",
    cat: "landmark",
    emoji: "🎨",
    address: "919 Broadway, The Gulch",
    lat: 36.1532,
    lng: -86.7791,
    search: "Frist Art Museum Nashville",
    note: "Nashville's premier art museum occupies a stunning 1933 Art Deco post office — white Georgia marble facade, decorative bronze details, soaring interior ceilings — listed on the National Register of Historic Places. The museum presents major touring exhibitions from world-class collections alongside strong regional programming. The Martin ArtQuest gallery is one of the most inventive hands-on art spaces in the South. Admission is notably reasonable for a museum of this calibre.",
    hours: "Mon–Wed & Fri–Sat 10am–5:30pm, Thu 10am–8pm, Sun 1–5:30pm",
    tip: "Thursday evenings offer extended hours and are usually uncrowded. The Art Deco interior is spectacular in late afternoon light.",
    type: "Contemporary Art Museum",
    blog: "",
    phone: "+1 615-244-3340",
    website: "https://fristartmuseum.org",
  },

  {
    id: 15,
    nbhd: "gulch",
    name: "L.A. Jackson",
    cat: "pub",
    emoji: "🍹",
    address: "401 11th Ave S, The Gulch (Thompson Hotel rooftop)",
    lat: 36.1537,
    lng: -86.7873,
    search: "LA Jackson rooftop bar Thompson Hotel Nashville Gulch skyline",
    note: "The Infatuation's pick for Nashville's quintessential rooftop bar, perched atop the Thompson Hotel with a sprawling outdoor patio, a signature spreading tree, and cocktails made with sorrel, sassafras, shrubs, and local botanicals. The skyline view stretches across the Gulch and downtown. Come in the afternoon for the best seats; weekends after 9pm become DJ-fuelled rooftop parties. The drinks are the star — and genuinely excellent.",
    hours: "Mon–Thu 4pm–midnight, Fri 3pm–1am, Sat 12pm–1am, Sun 12pm–midnight",
    tip: "Arrive before 6pm on weekday evenings for the best seats without a wait. The view at golden hour is exceptional.",
    type: "Rooftop Cocktail Bar",
    blog: "",
    phone: "+1 615-262-6007",
    website: "https://thompsonhotels.com/hotels/nashville/la-jackson",
  },

  {
    id: 16,
    nbhd: "gulch",
    name: "The Catbird Seat",
    cat: "food",
    emoji: "⭐",
    address: "700 8th Ave S (5th floor, Bill Voorhees Building), Paseo South Gulch",
    lat: 36.1513,
    lng: -86.7862,
    search: "The Catbird Seat Nashville Michelin tasting menu Gulch",
    note: "Nashville's most celebrated restaurant — operating since 2011 as a deliberate culinary incubator where each chef residency brings an entirely new vision to the kitchen. The current chapter is led by husband-and-wife chefs Andy Doubrava and Tiffani Ortiz, whose 15-course tasting menu is built around Tennessee ingredients, sustainability, and zero-waste kitchen practice. The U-shaped Tennessee pink marble counter wraps around an open kitchen where every course is finished a few feet in front of you. The Infatuation currently rates it Nashville's highest-rated restaurant: 'The experimental fine dining powerhouse recently got a makeover... and the food has ascended to near untouchable heights.' One Michelin Star, 2025. The Patterson House cocktail bar is directly next door on the same floor.",
    hours: "Wed–Sat evenings; two seatings. Check website for current schedule",
    tip: "Reservations open on the first of each month for the entire following month at noon CST — they sell out within minutes. Arrive early and have a pre-dinner drink at The Patterson House next door.",
    type: "Michelin-Starred Tasting Menu (15 courses)",
    blog: "",
    phone: "+1 615-810-8200",
    website: "https://www.thecatbirdseatrestaurant.com",
  },

  {
    id: 17,
    nbhd: "gulch",
    name: "Biscuit Love",
    cat: "cafe",
    emoji: "🧇",
    address: "316 11th Ave S, The Gulch",
    lat: 36.1534,
    lng: -86.7876,
    search: "Biscuit Love Nashville Gulch Southern brunch biscuits Bonuts",
    note: "Nashville's most celebrated brunch destination — and the first thing locals name when asked about The Gulch. The menu is built around fresh-milled Southern biscuits topped with fried chicken, sausage gravy, eggs, and seasonal accompaniments. The Bonuts (biscuit doughnuts with lemon mascarpone and blueberry compote) have a devoted following of their own. PODS travel notes: 'Tourists love the Gulch... not least for Biscuit Love, where you'll unfailingly find a line of hopeful breakfasters.' Weekday mornings are considerably more manageable than weekends.",
    hours: "Daily 7am–3pm",
    tip: "Arrive 15 minutes before opening on weekdays to avoid the wait. The Bonuts sell out — order them immediately on arrival.",
    type: "Southern Brunch",
    blog: "",
    phone: "+1 615-490-9584",
    website: "https://biscuitlove.com",
  },

  {
    id: 18,
    nbhd: "gulch",
    name: "The Patterson House",
    cat: "pub",
    emoji: "🍸",
    address: "700 8th Ave S (5th floor, Bill Voorhees Building), Paseo South Gulch",
    lat: 36.1512,
    lng: -86.7864,
    search: "Patterson House Nashville cocktail bar Gulch Bill Voorhees 8th Ave James Beard",
    note: "The bar that set Nashville's craft cocktail standard in 2009, now in a new fifth-floor home in the Bill Voorhees Building. Nashville Guru describes the new space: 'red oak bar, cherry wood walls, tin ceiling panels, intimate booth seating — full downtown views.' Two menus: nine rotating original drinks alongside a 150-cocktail archive of the bar's greatest hits. As Axios Nashville confirms: 'They now have a space where they can realise their full creative vision.' Multiple James Beard nominations for Outstanding Bar Programme.",
    hours: "Daily 4pm–2am (kitchen until midnight)",
    tip: "The entrance is on Paseo Pl. behind the Bill Voorhees Building — not from 8th Ave directly. Paid valet Wed–Sat from 4pm. First-come, first-served; limited reservations available.",
    type: "James Beard Craft Cocktail Bar",
    blog: "",
    phone: "",
    website: "https://www.thepattersonnashville.com",
  },

  {
    id: 19,
    nbhd: "gulch",
    name: "The Station Inn",
    cat: "pub",
    emoji: "🎻",
    address: "402 12th Ave S, The Gulch",
    lat: 36.1549,
    lng: -86.7873,
    search: "Station Inn Nashville",
    note: "Nashville's most beloved bluegrass and acoustic music club — a low-lit concrete-block room where some of the finest pickers in the world have played since 1974. There are no big screens, no pretensions, and no cover charge on many nights. The focus is entirely on the music six feet in front of you. TimeOut Nashville lists it as one of the city's essential live music bars. Bring cash, order a beer, and let the picking begin.",
    hours: "Open most nights from 9pm; hours vary by show",
    tip: "Tuesday night open bluegrass jam: anyone can join. Sunday shows are most intimate. Check the schedule — programming is worth planning around.",
    type: "Bluegrass & Acoustic Music Club",
    blog: "",
    phone: "+1 615-255-3307",
    website: "https://www.stationinn.com",
  },

  {
    id: 43,
    nbhd: "gulch",
    name: "Rudy's Jazz Room",
    cat: "pub",
    emoji: "🎺",
    address: "809 Gleaves St, SoBro",
    lat: 36.1527,
    lng: -86.7832,
    search: "Rudys Jazz Room Nashville jazz venue SoBro intimate",
    note: "Nashville's most dedicated jazz room — an intimate venue near the Cannery Row complex that programmes traditional and contemporary jazz with genuine curatorial intent. Where the Station Inn is for bluegrass, Rudy's is for jazz: small room, close to the musicians, an audience that came to listen. Frommer's Nashville lists it alongside the Station Inn as one of the city's standard-bearing acoustic music venues. The cocktail programme is well above average for a music room.",
    hours: "Mon & Wed–Thu 5–11:30pm, Fri–Sat 5pm–1am, Sun 5–11:30pm (closed Tue)",
    tip: "Reserve a table in advance for weekend shows — the room is small and fills quickly for strong bookings. Arrive early for a drink at the bar before the set.",
    type: "Intimate Jazz Venue",
    blog: "",
    phone: "+1 615-988-2458",
    website: "https://rudysjazzroom.com",
  },

  // ─── EAST NASHVILLE ───────────────────────────────────────────────────────

  {
    id: 20,
    nbhd: "east",
    name: "Attaboy Nashville",
    cat: "pub",
    emoji: "🍸",
    address: "8 McFerrin Ave, East Nashville",
    lat: 36.1802,
    lng: -86.7615,
    search: "Attaboy Nashville speakeasy no-menu cocktail bar East Nashville",
    note: "Attaboy arrives in Nashville as sister bar to the legendary New York original, and the same rules apply: there is no menu. Bartenders ask your preferred spirits, flavour profiles, and mood — then deliver something bespoke every time. A Google reviewer describes it: 'You share what you're feeling. And what you get back is alchemy. First pour: A custom-named Jewel Thief — Dickel Rye, Averna, Benedictine. Bitter, herbal, smooth, dead-on what I wanted.' The dimly-lit industrial space announces quietly that this place is serious.",
    hours: "Daily 5pm–2am",
    tip: "No menu — just tell the bartender what you like (spirit, style, mood). Come on a weeknight when the room is quiet enough for a proper conversation.",
    type: "No-Menu Speakeasy",
    blog: "",
    phone: "",
    website: "https://attaboynashville.com",
  },

  {
    id: 21,
    nbhd: "east",
    name: "Kisser",
    direct_image: "https://res.cloudinary.com/the-infatuation/image/upload/c_fill,w_1200,ar_4:3,g_center,f_auto/images/20D839C5-362A-41C6-A238-3CC1B65F2E4A_gslcis",
    cat: "food",
    emoji: "🍜",
    address: "747 Douglas Ave, East Nashville",
    lat: 36.1794,
    lng: -86.7559,
    search: "Kisser Nashville Japanese East Nashville Highland Yards James Beard 2024",
    note: "A 2024 James Beard Award Best New Restaurant semifinalist from the team behind Folk and Rolf & Daughters. The kitchen draws on Japanese comfort food — chicken katsu sandwiches, curry dishes, creative udon — with an approachable, unhurried spirit. The Infatuation rates it among Nashville's best: 'The yellowtail collar is one of the best things you can eat in this city.' Named one of Bon Appétit's Best New Restaurants in America.",
    hours: "Wed–Mon 11am–3pm & 5–10pm (closed Tue)",
    tip: "Order the chirashi bowl at lunch — a serious splurge for the price. The sesame swiss roll at the bakery counter is a non-negotiable purchase.",
    type: "James Beard Japanese Comfort Food",
    blog: "",
    phone: "+1 615-913-8888",
    website: "https://www.kisserrestaurant.com",
  },

  {
    id: 22,
    nbhd: "east",
    name: "Butcher & Bee",
    cat: "food",
    emoji: "🥗",
    address: "902 Main St, East Nashville",
    lat: 36.1762,
    lng: -86.7683,
    search: "Butcher and Bee Nashville East Nashville Main Street Middle Eastern sharing plates",
    note: "After a decade in Nashville, Butcher & Bee has grown fully into its own identity — no longer a Charleston offshoot but the city's essential Middle Eastern-influenced restaurant. Resy writes: 'The cooks have the freedom to experiment more — whipped feta with fermented honey and avocado crispy rice never fall off the menu, but everything around them keeps moving.' The menu revolves around seasonal local ingredients, sharing plates, and a kitchen that rewards repeat visits.",
    hours: "Mon–Thu 5–10pm, Fri 5–11pm, Sat–Sun 10am–2pm & 5–10pm",
    tip: "The whipped feta with fermented honey is a non-negotiable first order. Weekend brunch is one of East Nashville's best-kept secrets.",
    type: "Modern Middle Eastern Sharing Plates",
    blog: "",
    phone: "+1 615-226-3322",
    website: "https://butcherandbee.com/nashville",
  },

  {
    id: 23,
    nbhd: "east",
    name: "The Pharmacy Burger Parlor & Beer Garden",
    cat: "food",
    emoji: "🍔",
    address: "731 McFerrin Ave, East Nashville",
    lat: 36.1809,
    lng: -86.7599,
    search: "The Pharmacy Burger Nashville East Nashville beer garden McFerrin Ave",
    note: "The Pharmacy has the best burger in Nashville and one of its finest patios: a sprawling German-style beer garden with long picnic tables, string lights, and a laid-back energy that makes you want to stay for two more rounds. The menu is simple — burgers, fries, house-made sodas in flavours like ginger lemon and hibiscus — but everything is executed with real care. A local favourite that draws families and serious drinkers equally, and perfectly captures what East Nashville does best.",
    hours: "Mon–Fri 11am–10pm, Sat–Sun 10am–10pm",
    tip: "Order a house-made soda alongside your burger — the ginger lemon is outstanding. The beer garden fills on weekend evenings.",
    type: "Craft Burger & Beer Garden",
    blog: "",
    phone: "+1 615-712-9517",
    website: "https://www.thepharmacynashville.com",
  },

  {
    id: 24,
    nbhd: "east",
    name: "Barista Parlor",
    cat: "cafe",
    emoji: "☕",
    address: "519B Gallatin Ave, East Nashville",
    lat: 36.1812,
    lng: -86.7619,
    search: "Barista Parlor Nashville East Nashville original Gallatin Ave third-wave coffee",
    note: "Nashville's original third-wave coffee destination — a converted East Nashville garage with soaring ceilings and raw industrial aesthetic, open since 2012. After consolidating its other locations in early 2026, Barista Parlor has returned fully to its roots here at 519 Gallatin Ave: manual brew methods, locally roasted coffee, and the focused craft that made it Nashville's first genuinely world-class café. The Wooden Plank — one coffee prepared as espresso, cortado, and pour-over — remains the signature experience for understanding what sets the beans apart. Travellemming: 'best known for providing high-quality coffee in a cool atmosphere — a must-visit for coffee enthusiasts.'",
    hours: "Daily 7am–7pm",
    tip: "Ask for the wooden plank: one coffee prepared three ways — espresso, cortado, pour-over. The best way to understand what makes the beans special.",
    type: "Third-Wave Coffee Destination",
    blog: "",
    phone: "+1 615-712-9766",
    website: "https://baristaparlor.com",
  },

  {
    id: 25,
    nbhd: "east",
    name: "Mas Tacos Por Favor",
    cat: "food",
    emoji: "🌮",
    address: "732 McFerrin Ave, East Nashville",
    lat: 36.1810,
    lng: -86.7600,
    search: "Mas Tacos Por Favor Nashville East Nashville McFerrin taqueria",
    note: "What began as a truck parked in the Five Points area became a permanent East Nashville institution with a cult following. The tacos are simple, honest, and excellent — slow-cooked meats, homemade salsas, fresh tortillas — in a cash-only storefront with a covered terrace. Nashville's local food tour guide summarises it plainly: 'Cheap, fast, delicious, legendary.' The line at lunch still wraps outside. The fried avocado taco is the devotee-maker.",
    hours: "Mon–Fri 11am–3pm (cash only; sell out regularly)",
    tip: "Cash only, and they sell out early. Arrive before noon on weekdays. The fried avocado taco is the must-order.",
    type: "Legendary Local Taqueria",
    blog: "",
    phone: "+1 615-543-6580",
    website: "",
  },

  {
    id: 26,
    nbhd: "east",
    name: "Bad Idea",
    cat: "pub",
    emoji: "🍷",
    address: "1021 Russell St, East Nashville",
    lat: 36.1759,
    lng: -86.7505,
    search: "Bad Idea wine bar Nashville East Nashville Russell Street Michelin Award",
    note: "In 2024, the New York Times named Bad Idea one of the 50 Best Restaurants in America. Sommelier Alex Burch — recipient of the Michelin American South Sommelier Award 2025 — runs the wine programme from inside a tornado-damaged East Nashville church restored into one of the most beautiful dining rooms in the city. Visit Nashville: 'The lofty ceiling height, the grand arched windows, the bustling horseshoe-shaped bar, a mezzanine (once a choir loft), and clergy offices transformed into private dining rooms.' An experience unlike any other in Nashville.",
    hours: "Mon–Sun 5pm–midnight",
    tip: "Book a table for the full experience, but walk-ins are welcome at the bar. The staff will guide you through the wine programme with genuine enthusiasm.",
    type: "Michelin-Recognised Wine Bar & Restaurant",
    blog: "",
    phone: "+1 629-729-4332",
    website: "https://badideanashville.com",
  },

  {
    id: 27,
    nbhd: "east",
    name: "Shelby Bottoms Greenway",
    cat: "nature",
    emoji: "🌿",
    address: "1900 Davidson St, East Nashville",
    lat: 36.1742,
    lng: -86.7471,
    search: "Shelby Bottoms Nashville Cumberland River",
    note: "A 980-acre natural greenway following the Cumberland River through East Nashville — the city's finest urban wilderness. Paved and unpaved trails wind through old-growth forest, open meadows, and riverside wetlands. The nature centre explains the ecology of the Cumberland basin and the bird-watching is excellent year-round. Nashvegas recommends arriving via the Shelby Street pedestrian bridge from downtown: a ten-minute walk with one of the best unobstructed views of the Nashville skyline.",
    hours: "Daily, dawn to dusk",
    tip: "Walk over from downtown via the Shelby Street pedestrian bridge for one of the best free skyline views in the city. Bring binoculars for the birds.",
    type: "Urban Greenway & Nature Park",
    blog: "",
    phone: "",
    website: "https://nashvillegreenways.com",
  },

  {
    id: 44,
    nbhd: "east",
    name: "The 5 Spot",
    cat: "pub",
    emoji: "🎵",
    address: "1006 Forrest Ave, East Nashville",
    lat: 36.1836,
    lng: -86.7530,
    search: "The 5 Spot Nashville East Nashville Forrest Ave live music neighbourhood venue",
    note: "East Nashville's beloved neighbourhood music venue — a no-pretence, low-cover bar that programmes the most eclectic mix in the city: funk nights, alt-country residencies, hip-hop, indie rock, and the occasional surprise. Where the Station Inn preserves tradition, the 5 Spot discovers what's next. Nashvegas lists it among the venues 'where the bar scene is more interesting than downtown without the cover charges.' Locals have been coming since 2007 and still find the programming genuinely surprising.",
    hours: "Daily from 5pm; music most nights from 9pm. No cover most nights",
    tip: "Monday Motown nights are a neighbourhood institution — $0 cover, all ages, and everyone dances. Check the schedule for programming highlights.",
    type: "Neighbourhood Music Venue",
    blog: "",
    phone: "+1 615-650-9333",
    website: "https://the5spot.club",
  },

  // ─── 12 SOUTH ─────────────────────────────────────────────────────────────

  {
    id: 28,
    nbhd: "12south",
    name: "Frothy Monkey",
    cat: "cafe",
    emoji: "☕",
    address: "2509 12th Ave S, 12 South",
    lat: 36.1260,
    lng: -86.7862,
    search: "Frothy Monkey Nashville 12 South coffee neighbourhood all-day cafe",
    note: "The 12 South original — a warm, quirky coffee house that functions as the living room of 12th Avenue South. Travel & Brew: 'Warm, a little quirky, and genuinely welcoming, like a true neighbourhood hangout rather than just a coffee stop.' The maple latte and banana bread are the canonical order. Beyond coffee, Frothy Monkey serves a full menu from breakfast through dinner. Beans are roasted locally in Nashville.",
    hours: "Daily 7am–10pm",
    tip: "The upstairs area has couches and a street view — the quietest seat in 12 South on weekend mornings.",
    type: "Neighbourhood Coffee House & Café",
    blog: "",
    phone: "+1 615-600-4756",
    website: "https://frothymonkey.com",
  },

  {
    id: 29,
    nbhd: "12south",
    name: "Locust",
    cat: "food",
    emoji: "🍽️",
    address: "2305 12th Ave S, 12 South",
    lat: 36.1275,
    lng: -86.7873,
    search: "Locust Nashville 12 South Michelin Star Trevor Moran restaurant",
    note: "Locust earned its Michelin Star in November 2025 and is open only Friday through Sunday. Chef Trevor Moran (formerly of The Catbird Seat and Noma Copenhagen) runs an ever-changing menu of Japanese, Irish, and British-influenced food. The Infatuation: 'Order everything. There'll probably be 10–11 dishes that are easy to say yes to, like heartbreakingly tender potato bread, meaty razor clams served open on pebble ice.' The bar side accepts walk-ins and serves the full cocktail menu — a brilliant way to experience Locust without the month-ahead reservation.",
    hours: "Fri–Sun 12pm–3pm (lunch) & 6–9pm (dinner)",
    tip: "Walk-ins at the bar get the full cocktail experience. Dinner reservations open one month in advance — set a calendar reminder. A deposit is required at booking.",
    type: "Michelin-Starred Seasonal Cuisine",
    blog: "",
    phone: "",
    website: "https://locustnashville.com",
  },

  {
    id: 30,
    nbhd: "12south",
    name: "Five Daughters Bakery",
    cat: "cafe",
    emoji: "🍩",
    address: "2605 12th Ave S, 12 South",
    lat: 36.1218,
    lng: -86.7852,
    search: "Five Daughters Bakery Nashville 12 South 100-layer croissant donuts",
    note: "Five Daughters became Nashville's most celebrated bakery on the strength of one product: the 100-layer croissant doughnut. The pastry team makes a rotating selection of laminated and enriched doughs that sell out every morning — seasonal fruit-filled croissants, kouign-amann, brioche doughnuts with inventive glazes. The 12 South shop fills quickly on weekend mornings. A Nashville food institution that has earned every word of its reputation.",
    hours: "Mon–Sat 7am–3pm, Sun 8am–3pm (sells out most days)",
    tip: "Arrive before 9am on weekends for the full selection. Follow their Instagram the night before — they post next day's specials in the evening.",
    type: "Artisan Bakery & Pastry",
    blog: "",
    phone: "+1 615-490-6554",
    website: "https://fivedaughtersbakery.com",
  },

  {
    id: 31,
    nbhd: "12south",
    name: "Sevier Park",
    cat: "nature",
    emoji: "🌳",
    address: "3021 Linden Ave, 12 South",
    lat: 36.1257,
    lng: -86.7855,
    search: "Sevier Park Nashville",
    note: "The green heart of 12 South — a beautifully maintained urban park with mature trees, a winding creek, walking paths, and open lawns used for picnics and weekend farmers markets. The park has a genuine neighbourhood character: dog walkers, families on blankets, runners. The Saturday morning 12 South Farmers Market, held in the adjacent school carpark from spring through autumn, is among the most convivial in the city.",
    hours: "Open daily, dawn to dusk",
    tip: "The 12 South Farmers Market runs Saturday mornings (spring–autumn) next to the park. Grab coffee from Frothy Monkey three blocks over and walk it over.",
    type: "Neighbourhood Park",
    blog: "",
    phone: "",
    website: "",
  },

  {
    id: 32,
    nbhd: "12south",
    name: "Bastion",
    cat: "food",
    emoji: "🌟",
    address: "434 Houston St, Suite 110, Wedgewood-Houston",
    lat: 36.1281,
    lng: -86.7934,
    search: "Bastion Nashville Wedgewood-Houston Michelin Star cocktails restaurant nachos",
    note: "Bastion won its Michelin star in 2025 — tucked behind an unmarked entrance in Wedgewood-Houston. Nashville Guru places the atmosphere perfectly: 'Creative types sipping Old Fashioneds under twinkling strings of lights. The bar's single-item food menu (nachos) allows the seasoned staff to spend that much more time honing their craft cocktails.' The nachos are genuinely excellent; the cocktails are some of Nashville's finest. Reservations release online only.",
    hours: "Tue–Sat 5pm–midnight (dining); bar walk-ins welcome",
    tip: "Reservations for dining release online only — watch the site. The bar is walk-in and the cocktails alone justify the trip.",
    type: "Michelin-Starred Restaurant & Bar",
    blog: "",
    phone: "+1 615-490-8434",
    website: "https://bastionnashville.com",
  },

  {
    id: 33,
    nbhd: "12south",
    name: "Fonda on 12th",
    cat: "food",
    emoji: "🌮",
    address: "2316 12th Ave S, 12 South",
    lat: 36.1270,
    lng: -86.7876,
    search: "Fonda on 12th Nashville 12 South Mexican restaurant Roberto Santibanez",
    direct_image: "https://resizer.otstatic.com/v4/photos/64518905-3?width=800&height=600&format=jpeg",
    note: "Chef Roberto Santibañez — born in Mexico City, trained at Le Cordon Bleu Paris — brought his acclaimed NYC Fonda concept to 12 South in May 2024. Nashville Lifestyles: 'His menu is replete with creative dishes representing the best of Old and New Worlds.' Order the crab empanadas with mango habanero salsa, the taco board (choose your protein, arrives with six tortillas and house salsas), and the watermelon-cucumber salad. Rated 4.8 on OpenTable from nearly 100 diners.",
    hours: "Mon–Tue 3–9pm, Wed–Thu 11am–9pm, Fri 11am–10pm, Sat 10am–10pm, Sun 10am–9pm",
    tip: "Happy hour runs daily with $6.50 wine and taco boards — the best value on 12th Ave. The guacamole is made to order tableside.",
    type: "Elevated Modern Mexican",
    blog: "",
    phone: "+1 615-800-4899",
    website: "https://fondanashville.com",
  },

  // ─── MIDTOWN / WEST END / HILLSBORO VILLAGE ───────────────────────────────

  {
    id: 34,
    nbhd: "midtown",
    name: "The Parthenon at Centennial Park",
    cat: "landmark",
    emoji: "🏛️",
    address: "2500 West End Ave, Centennial Park",
    lat: 36.1480,
    lng: -86.8136,
    search: "Parthenon Nashville Centennial Park",
    direct_image: "https://upload.wikimedia.org/wikipedia/commons/7/79/Parthenon,_Nashville.JPG",
    note: "Built for the 1897 Tennessee Centennial Exposition, Nashville's full-scale concrete replica of the Athenian Parthenon is the city's most arrestingly surreal landmark — a complete Greek temple in the middle of a 132-acre urban park. Inside, the Naos Gallery houses Nashville's civic art collection and the centrepiece: a 42-foot gilded statue of Athena, the tallest indoor statue in the Western Hemisphere. The Ryman notes: 'The Parthenon brings ancient Greece to the Athens of the South.'",
    hours: "Tue–Sat 9am–4:30pm; Park open daily, dawn to dusk",
    tip: "The park is beautiful at any hour. The Parthenon interior is best in morning light. The walk to Vanderbilt's campus five minutes north makes a fine combined morning.",
    type: "Full-Scale Parthenon Replica & Art Museum",
    blog: "",
    phone: "+1 615-862-8431",
    website: "https://nashville.gov/parks/parthenon",
  },

  {
    id: 35,
    nbhd: "midtown",
    name: "The Bluebird Cafe",
    cat: "landmark",
    emoji: "🎵",
    address: "4104 Hillsboro Pike, Green Hills",
    lat: 36.1063,
    lng: -86.8168,
    search: "Bluebird Cafe Nashville",
    note: "The Bluebird is the room where careers begin — a 90-seat listening room in a strip mall that has launched more country music careers than any other venue on earth. Garth Brooks was discovered here. Taylor Swift was discovered here. The house rules are strict: no talking during songs, full attention to the stage. 'In the Round' shows, where four songwriters sit together and trade original songs, reveal the craft behind the hits in a way no other Nashville experience can match.",
    hours: "Shows most evenings; check schedule online",
    tip: "Reserve well in advance — the room seats only 90. In the Round shows on Sunday evenings are the best introduction to how Nashville songs are actually made.",
    type: "Songwriter Listening Room",
    blog: "",
    phone: "+1 615-383-1461",
    website: "https://www.bluebirdcafe.com",
  },

  {
    id: 36,
    nbhd: "midtown",
    name: "Fido",
    cat: "cafe",
    emoji: "☕",
    address: "1812 21st Ave S, Hillsboro Village",
    lat: 36.1345,
    lng: -86.8026,
    search: "Fido coffee Nashville Hillsboro Village all-day cafe restaurant",
    note: "Fido is Hillsboro Village's living room — an always-buzzing coffee house and all-day restaurant that has anchored this corner of Midtown since 1996. Nashville Guru notes it draws a youthful crowd of students and creatives from nearby Belmont and Vanderbilt, and that 'the food is just as good as the coffee.' Full breakfast, lunch, and dinner service; full bar in the evenings. A reliable hub for a slow morning or a long working afternoon in a neighbourhood with genuine character.",
    hours: "Daily 7am–10pm",
    tip: "The back room is quieter for working. Arrive before 9am on weekends to claim a table; the egg dishes at brunch are reliably excellent.",
    type: "Neighbourhood Coffee House & All-Day Café",
    blog: "",
    phone: "+1 615-777-3436",
    website: "https://bongojava.com/fido",
  },

  {
    id: 37,
    nbhd: "midtown",
    name: "Belcourt Theatre",
    cat: "landmark",
    emoji: "🎬",
    address: "2102 Belcourt Ave, Hillsboro Village",
    lat: 36.1310,
    lng: -86.8001,
    search: "Belcourt Theatre Nashville Hillsboro Village independent art house cinema 1925",
    note: "Nashville's independent cinema, operating continuously since 1925 — one of the oldest continuously running movie houses in Tennessee. The Belcourt programmes art house films, documentaries, film festivals, and live events in two beautifully restored theatres. It is the cultural anchor of Hillsboro Village — across the street from Fido, two blocks from Vanderbilt — and the programming reflects genuine curatorial intelligence. Nashvegas identifies it as one of the neighbourhood's best options for culture.",
    hours: "Shows daily; box office opens 30 min before first film",
    tip: "Check the monthly calendar for special events — retrospectives, Q&As with filmmakers, and local premieres are regular features. The popcorn is notably good.",
    type: "Independent & Art House Cinema",
    blog: "",
    phone: "+1 615-846-3150",
    website: "https://www.belcourt.org",
  },

  {
    id: 38,
    nbhd: "midtown",
    name: "Nelson's Green Brier Distillery",
    cat: "pub",
    emoji: "🥃",
    address: "1414 Clinton St, Marathon Village",
    lat: 36.1580,
    lng: -86.7977,
    search: "Nelsons Green Brier Distillery Nashville Tennessee whiskey Marathon Village tour",
    note: "TimeOut notes that Nelson's Green Brier revived a recipe nearly lost to Prohibition in the Tennessee hills. Owners Andy and Charlie Nelson are great-great-great-grandsons of the original founder, Charles Nelson. The Nashville tasting room sits inside Marathon Village — the converted Marathon Motorworks factory — with exposed brick, barrel displays, and a cocktail bar serving drinks made entirely from house-distilled spirits. Weekend tours, sometimes led by the Nelsons themselves, are among the most personal distillery experiences in Tennessee.",
    hours: "Tue–Sat 12pm–8pm; Tours Sat & Sun 1pm & 3pm",
    tip: "Book a weekend tour in advance — Andy or Charlie Nelson sometimes lead them personally. The straight Tennessee whiskey is the serious drinker's choice.",
    type: "Historic Tennessee Whiskey Distillery",
    blog: "",
    phone: "+1 615-913-8800",
    website: "https://www.nelsonsgreenbriar.com",
  },

  {
    id: 39,
    nbhd: "midtown",
    name: "RCA Studio B",
    cat: "landmark",
    emoji: "🎙️",
    address: "1611 Roy Acuff Pl, Music Row",
    lat: 36.1448,
    lng: -86.7937,
    search: "RCA Studio B Nashville Music Row",
    note: "Nashvegas is unambiguous: RCA Studio B is the most historically significant recording studio in country music history. Elvis Presley, Dolly Parton, Willie Nelson, Chet Atkins, Roy Orbison, and hundreds more recorded here between 1957 and 1977. The studio's original console, isolation booth, and reverb chamber are all intact and fully operational. Tours run through the Country Music Hall of Fame and are consistently among the most informative cultural experiences Nashville offers.",
    hours: "Tours by booking only through CMHOF; multiple daily departures",
    tip: "Book the combination ticket with the Country Music Hall of Fame. Tours are limited in size and sell out — book at least a week ahead on weekends.",
    type: "Historic Recording Studio (tours)",
    blog: "",
    phone: "+1 615-416-2001",
    website: "https://www.countrymusichalloffame.org/visit/rca-studio-b",
  },

  {
    id: 40,
    nbhd: "midtown",
    name: "Pancake Pantry",
    direct_image: "https://res.cloudinary.com/the-infatuation/image/upload/c_fill,w_1200,ar_4:3,g_center,f_auto/PancakePantry_Table1_CaseyIrwin_Nashville_ce4h9p",
    cat: "cafe",
    emoji: "🥞",
    address: "1796 21st Ave S, Hillsboro Village",
    lat: 36.1345,
    lng: -86.8021,
    search: "Pancake Pantry Nashville Hillsboro Village breakfast institution 1961",
    note: "Open since 1961, the Pancake Pantry is Nashville's oldest and most beloved breakfast institution — confirmed every weekend morning by the line that wraps around the block before 8am. The menu runs to over two dozen pancake varieties: sweet potato, Caribbean, Tennessee buckwheat, and many more. The room has not changed much in decades: waiters who have been here for 30 years, the same copper fixtures, the same familiar regulars. Entirely Nashville, entirely irreplaceable.",
    hours: "Mon–Fri 6am–3pm, Sat–Sun 6am–4pm (line forms early on weekends)",
    tip: "Arrive before 8am on weekdays to avoid a wait. The Caribbean pancakes (coconut and pineapple syrup) are the cult order.",
    type: "Nashville Breakfast Institution (est. 1961)",
    blog: "",
    phone: "+1 615-383-9333",
    website: "https://www.thepancakepantry.com",
  },

  // ─── PARKS & GREATER NASHVILLE ────────────────────────────────────────────

  {
    id: 47,
    nbhd: "parks",
    name: "Grand Ole Opry",
    cat: "landmark",
    emoji: "🌟",
    address: "2804 Opryland Dr, Opryland (15 min from downtown)",
    lat: 36.1952,
    lng: -86.6963,
    search: "Grand Ole Opry Nashville",
    note: "The Grand Ole Opry Show has run continuously since 1927, making it the longest-running live radio programme in American history. The modern Opry House seats 4,400 and runs shows on Friday and Saturday nights most of the year, with additional weeknight performances in peak season. The Ryman's own documentation notes: 'A six-foot circle of the original Ryman stage wood was removed and placed in the centre of the Opry stage as a tribute to its former home.' Standing in that circle during a backstage tour is one of Nashville's most quietly moving moments.",
    hours: "Shows Fri–Sat nights year-round; additional Tue–Thu shows in season",
    tip: "The backstage tour is excellent — you get your photo taken inside the famous circle of Ryman stage wood at the centre of the stage. Book shows well in advance.",
    type: "Historic Country Music Venue",
    blog: "",
    phone: "+1 615-871-6779",
    website: "https://www.opry.com",
  },

  {
    id: 48,
    nbhd: "parks",
    name: "Percy Warner Park",
    cat: "nature",
    emoji: "🌲",
    address: "7311 Highway 100, Belle Meade (20 min from downtown)",
    lat: 36.0849,
    lng: -86.8960,
    search: "Percy Warner Park Nashville Tennessee",
    direct_image: "https://upload.wikimedia.org/wikipedia/commons/f/f0/Edwin_Warner_Park_05.jpg",
    note: "At 3,400 acres, Percy Warner is one of the largest urban parks in the United States — a sweep of forested ridgelines, scenic overlooks, equestrian and hiking trails, and the historic Iroquois Steeplechase course. The park connects to adjacent Edwin Warner Park for nearly 70 miles of combined trail. The WPA-era stonework and stone shelters throughout give it a sense of permanence that the city's newer green spaces cannot match. A 20-minute drive from downtown and worth every minute.",
    hours: "Daily, dawn to dusk (year-round)",
    tip: "The Mossy Ridge Trail (3.5 miles, moderate) is the best introduction — excellent ridgeline views and a stone shelter at the top. Bring water; no amenity buildings on trail.",
    type: "Urban Wilderness Park (3,400 acres)",
    blog: "",
    phone: "+1 615-370-8051",
    website: "https://nashville.gov/parks/percy-warner-park",
  },

  {
    id: 49,
    nbhd: "parks",
    name: "Radnor Lake State Natural Area",
    cat: "nature",
    emoji: "🦅",
    address: "1160 Otter Creek Rd, Nashville (25 min from downtown)",
    lat: 36.0716,
    lng: -86.8074,
    search: "Radnor Lake Nashville Tennessee",
    note: "Tennessee's most beloved urban wildlife sanctuary — 1,332 acres of hardwood forest, wetlands, and a natural lake 25 minutes from downtown Nashville. Radnor is strictly no dogs, no bikes, no picnicking: conservation is the priority, and the wildlife shows it. Great blue herons, osprey, white-tailed deer, and occasionally river otters are reliably visible from the lakeside trail. Tennessee State Parks rates it 'among the most visited state natural areas in Tennessee.' It feels genuinely wild in a way no city park manages.",
    hours: "Daily 6am–dusk; trail access closes at dusk",
    tip: "Come early on weekday mornings for the best wildlife viewing. The Lake Trail (2.1 miles, flat) circles the lake and gives the best chance of seeing herons and otters.",
    type: "State Natural Area & Wildlife Sanctuary",
    blog: "",
    phone: "+1 615-373-3467",
    website: "https://tnstateparks.com/parks/radnor-lake",
  },

  {
    id: 50,
    nbhd: "parks",
    name: "Cheekwood Estate & Gardens",
    cat: "landmark",
    emoji: "🌸",
    address: "1200 Forrest Park Dr, Belle Meade (20 min from downtown)",
    lat: 36.0966,
    lng: -86.8754,
    search: "Cheekwood Estate Gardens Nashville",
    note: "A 1920s Georgian Revival mansion on 55 acres of formally designed botanical gardens in Belle Meade — Nashville's most beautiful cultural institution outside the downtown museums. The estate was the home of the Maxwell House coffee fortune; its gardens range from a Japanese garden and a boxwood allée to wildflower meadows and sculptural woodlands. The interior houses a strong permanent collection of American art alongside rotating exhibitions. Cheekwood's seasonal programmes — the winter lights display, the spring tulip season — consistently draw Nashville's most enthusiastic crowds.",
    hours: "Tue–Sun 9am–5pm (last entry 4pm)",
    tip: "Book tickets online, especially for seasonal events which sell out weeks in advance. The Japanese garden is the most serene 20 minutes available in all of Nashville.",
    type: "Historic Estate, Gardens & Art Museum",
    blog: "",
    phone: "+1 615-356-8000",
    website: "https://cheekwood.org",
  },

];
