// A Perfect Day — Nomadic Matt / Bangkok
// data.js — 53 places curated from nomadicmatt.com
// DO NOT add GUIDE_CITY, BLOGGER_NAME, FAVS_KEY, map, or global state here.

const PLACES = [

  // ─── OLD CITY / RATTANAKOSIN ─────────────────────────────────────────────

  {
    id: 1,
    nbhd: "old-city",
    name: "Grand Palace & Wat Phra Kaew",
    cat: "landmark",
    emoji: "🏛️",
    address: "Na Phra Lan Road, Phra Nakhon",
    lat: 13.7500,
    lng: 100.4913,
    search: "Grand Palace Bangkok",
    note: "The undisputed must-see of Bangkok — and one of the most dazzling places I've been anywhere in the world. Built by King Rama I in 1782, the Grand Palace is a labyrinth of golden temples, towering chedis, and mythological statues hidden behind massive white walls. Inside is Wat Phra Kaew and the revered Emerald Buddha, whose golden robes are changed by Thailand's king himself three times a year. Even after dozens of visits, it still makes my jaw drop. Go first thing in the morning before the tour groups flood in.",
    hours: "Daily 8:30am–3:30pm",
    tip: "Dress code is strictly enforced — legs and shoulders must be covered. Sarongs are available to borrow at the entrance. Skip the tuk-tuk touts outside who claim it's closed — it never is. That's a classic Bangkok scam.",
    type: "Palace & Temple Complex",
    blog: "https://www.nomadicmatt.com/travel-guides/thailand-travel-tips/bangkok/",
    phone: "+66 2 623 5500",
    website: "https://www.royalgrandpalace.th",
  },

  {
    id: 2,
    nbhd: "old-city",
    name: "Wat Pho (Reclining Buddha)",
    cat: "church",
    emoji: "⛩️",
    address: "2 Sanamchai Road, Grand Palace Subdistrict",
    lat: 13.7465,
    lng: 100.4928,
    search: "Wat Pho Reclining Buddha Bangkok",
    note: "Immediately next door to the Grand Palace, Wat Pho is home to one of Bangkok's most iconic sights: a 46-meter long, gold-plated reclining Buddha that fills an entire building. The statue is 15 meters tall and his feet alone are 5 meters long. But here's my real reason to come: the prestigious Thai Traditional Medical and Massage School on the grounds. After a morning of sightseeing, queue up for a traditional Thai massage from trained students. It's genuinely one of the best massages I've had anywhere in Asia.",
    hours: "Daily 8:00am–6:30pm",
    tip: "Go early morning or late afternoon for a massage — midday waits can hit 45 minutes. Cost is 300 THB for 30 minutes, 420 THB for 60 minutes. Worth every baht.",
    type: "Buddhist Temple",
    blog: "https://www.nomadicmatt.com/travel-blogs/best-things-to-do-bangkok/",
    phone: "+66 2 662 3553",
    website: "https://www.watpho.com",
  },

  {
    id: 3,
    nbhd: "old-city",
    name: "Wat Arun (Temple of the Dawn)",
    cat: "church",
    emoji: "⛩️",
    address: "158 Wang Doem Road, Wat Arun, Bangkok Yai",
    lat: 13.7437,
    lng: 100.4890,
    search: "Wat Arun Temple of the Dawn Bangkok",
    note: "This is my favorite temple in Bangkok. Wat Arun sits right on the Chao Phraya River opposite the Grand Palace, its stunning tiered spire encrusted with colorful porcelain and seashell mosaics that shimmer in the light. It's so iconic it appears on the Thai 10-baht coin. The main prang is climbable via steep stone stairs, and the views from the top over the river are extraordinary. Sunrise and sunset here are unforgettable.",
    hours: "Daily 8:00am–6:00pm",
    tip: "Take the 5 THB ferry from Tha Tien pier (right next to Wat Pho) — Wat Arun is directly across the river. Sunset is the magic hour here. The light on the porcelain tiles turns everything gold.",
    type: "Buddhist Temple",
    blog: "https://www.nomadicmatt.com/travel-blogs/best-things-to-do-bangkok/",
    phone: "+66 2 891 2185",
    website: "https://www.watarun.net",
  },

  {
    id: 4,
    nbhd: "old-city",
    name: "Museum of Siam",
    cat: "landmark",
    emoji: "🏛️",
    address: "4 Maha Rat Road, Phra Nakhon",
    lat: 13.7460,
    lng: 100.4952,
    search: "Museum of Siam Bangkok",
    note: "One of Bangkok's most underrated attractions — and I never hear enough people talking about it. Opened in 2007 and housed in a gorgeous 19th-century European-style building, this interactive museum tells the story of Thai identity, culture, and history in a genuinely engaging way. Movies, games, multimedia displays, and hands-on galleries cover Buddhism, warfare, and modern Thailand. It's more fun than any textbook and makes a perfect introduction to the country.",
    hours: "Tue–Sun 10:00am–6:00pm",
    tip: "Admission is only 100 THB — extraordinary value. Great for kids and adults equally. Easily combined with the Grand Palace and Wat Pho into one full Old City day.",
    type: "Cultural Museum",
    blog: "https://www.nomadicmatt.com/travel-guides/thailand-travel-tips/bangkok/",
    phone: "+66 2 225 2777",
    website: "https://www.museumsiam.org",
  },

  {
    id: 5,
    nbhd: "old-city",
    name: "National Museum Bangkok",
    cat: "landmark",
    emoji: "🏛️",
    address: "Na Phra That Alley, Phra Nakhon",
    lat: 13.7579,
    lng: 100.4931,
    search: "National Museum Bangkok Thailand",
    note: "Established in 1874, this is the largest museum in Southeast Asia — a vast collection of Thai art, ancient artifacts, royal funeral chariots, traditional musical instruments, and priceless Buddha images. Some sections still lack full English translations, but the sheer scale and quality of what's here is impressive. The royal funeral chariot pavilion alone is jaw-dropping: massive gilded chariots used to carry Thai monarchs to their cremation.",
    hours: "Wed–Sun 9:00am–4:00pm",
    tip: "Free English-language guided tours run at 9:30am on Wednesdays and Thursdays — highly recommended. Allow at least 2 hours. Admission is 200 THB.",
    type: "National Museum",
    blog: "https://www.nomadicmatt.com/travel-guides/thailand-travel-tips/bangkok/",
    phone: "+66 2 224 1333",
    website: "https://www.finearts.go.th",
  },

  {
    id: 6,
    nbhd: "old-city",
    name: "Wat Suthat & the Giant Swing",
    cat: "church",
    emoji: "⛩️",
    address: "146 Bamrung Mueang Road, Phra Nakhon",
    lat: 13.7524,
    lng: 100.5013,
    search: "Wat Suthat Giant Swing Bangkok",
    note: "One of Bangkok's most visually striking temple entrances anywhere in the city. The massive crimson Giant Swing at the entrance was first built in 1784 and was once used in a Brahmin ceremony where men swung 25 meters in the air to grab bags of gold coins. The original was replaced with a golden teak version in 2005. The temple behind it is equally beautiful: a magnificent traditional roof, ancient murals, and hand-carved teak door panels that are considered among the finest in Thailand.",
    hours: "Daily 9:00am–6:00pm",
    tip: "The Giant Swing is free to photograph from outside. Entering the temple complex costs 20 THB. Often uncrowded compared to the Grand Palace area — excellent for photography without fighting tour groups.",
    type: "Temple & Historic Monument",
    blog: "https://www.nomadicmatt.com/travel-guides/thailand-travel-tips/bangkok/",
    phone: "+66 2 221 4804",
    website: "",
  },

  {
    id: 7,
    nbhd: "old-city",
    name: "Wat Saket (Temple of the Golden Mount)",
    cat: "church",
    emoji: "⛩️",
    address: "344 Chakkraphatdi Phong Road, Pom Prap Sattru Phai",
    lat: 13.7539,
    lng: 100.5064,
    search: "Wat Saket Golden Mount Bangkok",
    note: "One of my absolute favorite spots in the city — and one that most visitors walk right past. The Golden Mount is an artificial hill crowned by a gleaming gold chedi containing Buddhist relics. The climb spirals up through hanging bells and small shrines in the shade of old trees, then opens suddenly to sweeping panoramic views of Bangkok's old city rooftops. At the base of the hill lies a slightly eerie cemetery for 18th-century plague victims. It's a beautiful, meditative little world apart from the chaos outside.",
    hours: "Daily 8:00am–5:00pm",
    tip: "Temple entry is free; climbing the chedi costs 50 THB. Sunset views over the Old City are some of the best in Bangkok. Ring the bells along the path — each one is said to bring good luck.",
    type: "Temple & Viewpoint",
    blog: "https://www.nomadicmatt.com/travel-guides/thailand-travel-tips/bangkok/",
    phone: "+66 2 621 0576",
    website: "",
  },

  {
    id: 8,
    nbhd: "old-city",
    name: "Khao San Road",
    cat: "cafe",
    emoji: "🍻",
    address: "Khao San Road, Banglamphu, Phra Nakhon",
    lat: 13.7582,
    lng: 100.4971,
    search: "Khao San Road Bangkok backpacker street",
    note: "The world's most famous backpacker street. Khao San Road has been the hub of Bangkok's traveler scene since the 1980s and while it's changed enormously since then — more local Thais than backpackers these days — it's still an essential Bangkok experience. The non-stop mix of street food, souvenir stalls, bars blasting music, hair braiding, and people-watching is unlike anywhere else on earth. Grab a 60-baht pad thai, order something cold, and watch the circus go by.",
    hours: "Active all day; peaks from 8pm onwards",
    tip: "For a calmer, more local version of the same energy, duck around the corner to Soi Rambuttri. Same vibe, quieter music, better bars. Brick Bar does live music every night and is a Bangkok institution.",
    type: "Backpacker Street & Nightlife",
    blog: "https://www.nomadicmatt.com/travel-guides/thailand-travel-tips/bangkok/",
    phone: "",
    website: "",
  },

  {
    id: 9,
    nbhd: "old-city",
    name: "Rajadamnern Muay Thai Stadium",
    cat: "landmark",
    emoji: "🥊",
    address: "1 Ratchadamnoen Nok Road, Pom Prap Sattru Phai",
    lat: 13.7617,
    lng: 100.5051,
    search: "Rajadamnoen Stadium Muay Thai Bangkok",
    note: "Watching live Muay Thai at Rajadamnern — the oldest and most prestigious Muay Thai stadium in the country — is one of the most electric evenings Bangkok offers. There are typically 7–9 bouts per night, each 5 rounds, with intense crowd betting happening in the stands throughout. The ritual pre-fight wai kru dance performed by each fighter is beautiful and hypnotic. The sheer athleticism and violence of the sport in its home stadium is something I've never forgotten.",
    hours: "Fight nights: Mon, Wed, Thu at 6:30pm; Sun at 3:30pm",
    tip: "Book directly on the stadium website to avoid touts who'll charge you double outside. Ringside seats cost more but you feel the impact of every strike. Don't miss the wai kru pre-fight ritual — it's extraordinary.",
    type: "Muay Thai Stadium",
    blog: "https://www.nomadicmatt.com/travel-blogs/best-things-to-do-bangkok/",
    phone: "+66 2 281 4205",
    website: "https://rajadamnern.com",
  },

  {
    id: 10,
    nbhd: "old-city",
    name: "Wat Benchamabophit (Marble Temple)",
    cat: "church",
    emoji: "⛩️",
    address: "69 Rama V Road, Dusit",
    lat: 13.7653,
    lng: 100.5117,
    search: "Wat Benchamabophit Marble Temple Bangkok",
    note: "Bangkok's most photogenic temple — and arguably its most serene. Built in 1899 using Italian Carrara marble, the exterior gleams white in the sunlight and reflects beautifully in the surrounding canal. The courtyard contains 53 Buddha statues representing different mudras from Buddhist traditions across Asia. It's far less crowded than the Old City temples and has a genuine atmosphere of peace and contemplation. It appears on the Thai 5-baht coin.",
    hours: "Daily 8:00am–6:00pm",
    tip: "Come early morning to see monks walking the canals collecting alms — one of the most atmospheric sights in the city. Admission is 20 THB. Combine with a Dusit Palace visit if you're in the area.",
    type: "Buddhist Temple",
    blog: "https://www.nomadicmatt.com/travel-blogs/best-things-to-do-bangkok/",
    phone: "+66 2 628 6300",
    website: "",
  },

  {
    id: 11,
    nbhd: "old-city",
    name: "Jay Fai (ร้านเจ๊ไฝ)",
    cat: "food",
    emoji: "🍳",
    address: "327 Maha Chai Road, Phra Nakhon",
    lat: 13.7533,
    lng: 100.5018,
    search: "Jay Fai restaurant Michelin Bangkok",
    note: "The most famous street food in Bangkok — maybe in all of Asia. Ratchanok Khangkhanarat, known as Jay Fai, has been cooking her legendary crab omelettes and drunken noodles over screaming-hot charcoal woks while wearing ski goggles (to protect from oil splatter) since the 1980s. She received a Michelin star in 2017 and her food fully deserves it. The crab omelette is enormous, golden, and stuffed with crab meat. This is the kind of place you tell people about for years.",
    hours: "Tue–Sat 2:00pm–midnight (closed Mon & Sun)",
    tip: "Book a table in advance on the website — walk-in waits regularly hit 4+ hours. The crab omelette is 1,000 THB but it's the size of a small pillow and worth every baht. Cash only.",
    type: "Michelin-Starred Street Food",
    blog: "https://www.nomadicmatt.com/travel-guides/thailand-travel-tips/bangkok/",
    phone: "+66 2 223 9384",
    website: "https://www.jayfaibangkok.com",
  },

  // ─── CHINATOWN / YAOWARAT ────────────────────────────────────────────────

  {
    id: 12,
    nbhd: "chinatown",
    name: "Yaowarat Road (Chinatown)",
    cat: "food",
    emoji: "🍜",
    address: "Yaowarat Road, Samphanthawong",
    lat: 13.7400,
    lng: 100.5144,
    search: "Yaowarat Chinatown food Bangkok",
    note: "Bangkok's Chinatown is one of the largest in the world, and Yaowarat Road is its neon-lit, blazing-hot main artery. I always end up here when I want to eat brilliantly without spending much. The street comes alive at night with seafood vendors grilling prawns and crab, roast duck shops with glazed birds hanging in the windows, dim sum baskets steaming at tiny counters, and dessert carts selling tong yip and khanom krok. Wander the side sois — the real action is always in the alleys.",
    hours: "Best from 6pm onwards",
    tip: "Skip the big air-conditioned restaurants on Yaowarat itself. The best food is in the narrow sois (alleys) running off the main road. Look for plastic stool shops with a crowd of locals — no English menu usually means something great.",
    type: "Chinatown Food Street",
    blog: "https://www.nomadicmatt.com/travel-guides/thailand-travel-tips/bangkok/",
    phone: "",
    website: "",
  },

  {
    id: 13,
    nbhd: "chinatown",
    name: "Pak Klong Talad (Flower Market)",
    cat: "market",
    emoji: "🌸",
    address: "Chak Phet Road, Phra Nakhon, Bangkok",
    lat: 13.7373,
    lng: 100.5004,
    search: "Pak Klong Talad flower market Bangkok",
    note: "Bangkok's main wholesale flower market, and one of the most sensory experiences the city offers. Boats arrive through the night loaded with orchids, birds of paradise, lotus blossoms, jasmine garlands, and roses from farms across Thailand. The market operates around the clock but is most alive between midnight and 6am when the wholesale buying happens. Towers of marigolds, seas of jasmine, rivers of lotus — it's genuinely magical if you can drag yourself out of bed for it.",
    hours: "Open 24 hours (best midnight–6am)",
    tip: "This is a wholesale market so prices are insanely low — a huge bunch of orchids costs almost nothing. Pair it with a late-night Chinatown food crawl for one of the most quintessentially Bangkok evenings possible.",
    type: "Wholesale Flower Market",
    blog: "https://www.nomadicmatt.com/travel-guides/thailand-travel-tips/bangkok/",
    phone: "",
    website: "",
  },

  {
    id: 14,
    nbhd: "chinatown",
    name: "Wat Traimit (Temple of the Golden Buddha)",
    cat: "church",
    emoji: "⛩️",
    address: "661 Charoen Krung Road, Samphanthawong",
    lat: 13.7384,
    lng: 100.5151,
    search: "Wat Traimit Golden Buddha Chinatown Bangkok",
    note: "Home to the world's largest solid-gold Buddha statue — a 3-meter tall, 5.5-ton image that was discovered completely by accident in 1955 when a plaster statue being moved by crane cracked open to reveal solid gold underneath. The statue dates to the Sukhothai period (13th–14th century) and was plastered over, historians believe, to protect it from Burmese invaders. The backstory is extraordinary. The statue itself, up close, is genuinely awe-inspiring.",
    hours: "Daily 8:00am–5:00pm",
    tip: "Admission is 40 THB for the main gold Buddha hall. The museum floors below tell the fascinating story of the statue's accidental discovery. Rarely crowded — a Chinatown gem that most visitors walk right past.",
    type: "Buddhist Temple",
    blog: "https://www.nomadicmatt.com/travel-blogs/best-things-to-do-bangkok/",
    phone: "+66 2 623 1227",
    website: "",
  },

  {
    id: 15,
    nbhd: "chinatown",
    name: "Soi Nana Chinatown (Bar Street)",
    cat: "cafe",
    emoji: "🍸",
    address: "Soi Nana, Charoen Krung Road, Samphanthawong",
    lat: 13.7415,
    lng: 100.5138,
    search: "Soi Nana Chinatown bars Bangkok cocktails",
    note: "Not to be confused with the seedier Sukhumvit Soi Nana — this Chinatown version is one of Bangkok's coolest bar streets. A narrow lantern-lit alley packed with craft cocktail bars, Chinese-inspired speakeasies, and tiny gallery spaces. Teens of Thailand was the city's first gin bar and is still brilliant. Ba Hao is a wild four-floor Chinese bar. El Chiringuito does Spanish tapas and natural wine. Pijiu serves Chinese craft beer. The vibe is creative, young, and genuinely fun.",
    hours: "Best 7pm–midnight",
    tip: "Go on a Tuesday or Wednesday to actually get seats. On weekends it becomes shoulder-to-shoulder. My personal order: start with a gin and tonic at Teens of Thailand, eat tapas at El Chiringuito, finish with cocktails at Ba Hao.",
    type: "Bar Street",
    blog: "https://www.nomadicmatt.com/travel-blogs/best-things-to-do-bangkok/",
    phone: "",
    website: "",
  },

  {
    id: 16,
    nbhd: "chinatown",
    name: "Thaling Chan Floating Market",
    cat: "market",
    emoji: "🛶",
    address: "Chak Phra Road, Taling Chan, Bangkok",
    lat: 13.7836,
    lng: 100.4641,
    search: "Taling Chan floating market Bangkok weekend",
    note: "Bangkok's most accessible floating market, and the most genuinely fun. Vendors paddle small wooden boats loaded with fresh fruit, grilled seafood, pad thai, and sticky rice sweets along the canal while you eat from the waterside terraces. It's the kind of chaotic, aromatic, loud Thai experience that's genuinely hard to find anymore without taking a 2-hour tour bus. Come completely empty-stomached. I always overate at Thaling Chan and had no regrets.",
    hours: "Sat–Sun 9:00am–4:00pm",
    tip: "Arrive by 9am to beat tour groups and get first pick of the boats. Only accessible on weekends. Takes about 30 minutes by Grab from central Bangkok — not accessible by BTS, so budget for the ride.",
    type: "Floating Market",
    blog: "https://www.nomadicmatt.com/travel-blogs/best-things-to-do-bangkok/",
    phone: "",
    website: "",
  },

  // ─── SILOM & SIAM ────────────────────────────────────────────────────────

  {
    id: 17,
    nbhd: "silom",
    name: "Lumpini Park",
    cat: "nature",
    emoji: "🌿",
    address: "192 Wireless Road, Lumphini, Pathum Wan",
    lat: 13.7285,
    lng: 100.5408,
    search: "Lumpini Park Bangkok green space",
    note: "In a city that desperately needs breathing room, Lumpini Park is Bangkok's lungs — 57 hectares of lakes, jogging paths, tai chi classes, chess tables, and monitor lizards the size of large dogs (seriously — don't be alarmed). When I lived in Bangkok I used to come here on weekends, pack a lunch, and just lie under the trees watching the world go by. It's the most human moment this frenetic city offers. Non-smoking area too, which is a genuine luxury.",
    hours: "Daily 4:30am–9:00pm",
    tip: "Evening tai chi and mass aerobics classes happen on the central lawn at around 5pm — locals of all ages join in and visitors are welcome. Rent a paddleboat on the lake for 40 THB/hour. The monitor lizards near the lake are absolutely massive but completely harmless.",
    type: "City Park",
    blog: "https://www.nomadicmatt.com/travel-blogs/best-things-to-do-bangkok/",
    phone: "+66 2 252 7006",
    website: "",
  },

  {
    id: 18,
    nbhd: "silom",
    name: "Jim Thompson's House",
    cat: "landmark",
    emoji: "🏠",
    address: "6 Kasemsan 2 Alley, Rama I Road, Pathum Wan",
    lat: 13.7457,
    lng: 100.5283,
    search: "Jim Thompson House Bangkok museum",
    note: "One of my absolute favorite things to do in Bangkok — and I recommend it to absolutely everyone. Jim Thompson was an American OSS spy turned silk merchant who single-handedly revived Thailand's silk industry in the 1950s, then mysteriously vanished in Malaysia's Cameron Highlands in 1967. His traditional Thai home — actually six antique wooden houses joined together — is packed with gorgeous teak carvings, Asian antiquities, and tropical gardens. The guided tour is superb. Admission funds programs for underprivileged children.",
    hours: "Daily 10:00am–6:00pm",
    tip: "The guided tour is included in admission and runs every 20 minutes in English — do not skip it. The silk shop next door sells beautiful products. Easily reached from National Stadium BTS station — one stop from Siam.",
    type: "Historic House Museum",
    blog: "https://www.nomadicmatt.com/travel-guides/thailand-travel-tips/bangkok/",
    phone: "+66 2 216 7368",
    website: "https://www.jimthompsonhouse.com",
  },

  {
    id: 19,
    nbhd: "silom",
    name: "Bangkok Art & Culture Center (BACC)",
    cat: "landmark",
    emoji: "🎨",
    address: "939 Rama I Road, Wang Mai, Pathum Wan",
    lat: 13.7464,
    lng: 100.5287,
    search: "Bangkok Art Culture Center BACC Siam",
    note: "Bangkok's best contemporary art museum — a spiraling white building right at Siam BTS station with nine floors of galleries, performance spaces, cinema, bookstore, and café. The building's architecture is dramatic: a hollow atrium with ramps spiraling upward through the galleries. The temporary exhibitions and live performances here are consistently excellent, and admission to browse the galleries is free. Always check what's on while you're in town.",
    hours: "Tue–Sun 10:00am–8:00pm",
    tip: "Gallery admission is free. Events and performances are ticketed separately — check the website in advance. Take the spiral ramp up through all floors for the full architectural experience. Open late, making it perfect for a pre-dinner culture fix.",
    type: "Contemporary Art Center",
    blog: "https://www.nomadicmatt.com/travel-blogs/best-things-to-do-bangkok/",
    phone: "+66 2 214 6630",
    website: "https://www.bacc.or.th",
  },

  {
    id: 20,
    nbhd: "silom",
    name: "MBK Center",
    cat: "landmark",
    emoji: "🛍️",
    address: "444 Phayathai Road, Wang Mai, Pathum Wan",
    lat: 13.7463,
    lng: 100.5298,
    search: "MBK Center Bangkok shopping mall",
    note: "If you want to experience Bangkok mall culture at its most chaotic and democratic, MBK is your place. This eight-floor labyrinth is Bangkok's best source for cheap electronics, phone accessories, fashion knockoffs, second-hand cameras, and SIM cards — plus a genuinely excellent top-floor food court. It's not glamorous but it's endlessly entertaining. I always end up here when I need a cheap replacement charger or want to browse gadgets I've never seen anywhere else.",
    hours: "Daily 10:00am–10:00pm",
    tip: "The top-floor food court is a Bangkok institution. Get tokens at the entrance and load up on Thai dishes for 60–80 THB each. The electronics floors are pure beautifully organized chaos. Right at National Stadium BTS.",
    type: "Budget Shopping Mall",
    blog: "https://www.nomadicmatt.com/travel-guides/thailand-travel-tips/bangkok/",
    phone: "+66 2 620 9000",
    website: "https://www.mbk-center.th",
  },

  {
    id: 21,
    nbhd: "silom",
    name: "Silom Thai Cooking School",
    cat: "food",
    emoji: "👩‍🍳",
    address: "68/1 Pan Road, Silom, Bang Rak",
    lat: 13.7230,
    lng: 100.5240,
    search: "Silom Thai Cooking School Bangkok class",
    note: "Thai cuisine is one of the most complex and delicious in the world, and learning to make it is one of the best things I've ever done in this city. The Silom school runs small-group classes that begin with a market visit to pick fresh ingredients, then guide you through 4–5 classic dishes — pad thai, green curry, tom kha, mango sticky rice. The instructor-to-student ratio is low and the instruction is genuinely good. Then you sit down and eat everything you made.",
    hours: "Morning class 9:00am–1:00pm; Afternoon 2:00pm–6:00pm",
    tip: "Book online in advance — classes fill up fast. Around 1,000–1,500 THB including the market visit, ingredients, and recipe booklet to take home. Exceptional value for the experience.",
    type: "Thai Cooking Class",
    blog: "https://www.nomadicmatt.com/travel-blogs/best-things-to-do-bangkok/",
    phone: "+66 2 632 5734",
    website: "https://www.silomthaicooking.com",
  },

  // ─── SUKHUMVIT ───────────────────────────────────────────────────────────

  {
    id: 22,
    nbhd: "sukhumvit",
    name: "Terminal 21",
    cat: "landmark",
    emoji: "🛍️",
    address: "88 Sukhumvit Soi 19, Khlong Toei Nuea, Watthana",
    lat: 13.7374,
    lng: 100.5601,
    search: "Terminal 21 Bangkok airport themed mall",
    note: "My favorite mall in Bangkok — and I've been to most of them. Terminal 21 is designed like an international airport, with each floor themed as a different world city: Tokyo, Istanbul, Rome, Hollywood, London, San Francisco. The design details are obsessively thorough and genuinely extraordinary. But the main reason every local will tell you to come here is the Pier 21 food court on the top floor — one of the best and cheapest places to eat in Sukhumvit. Great Thai dishes for around 60–80 THB.",
    hours: "Daily 10:00am–10:00pm",
    tip: "Pier 21 food court (top floor): get a card at the entrance, load it with money, and spend it on excellent Thai dishes at prices so low you'll double-check them. Right at Asok BTS and Sukhumvit MRT stations.",
    type: "Shopping Mall",
    blog: "https://www.nomadicmatt.com/travel-guides/thailand-travel-tips/bangkok/",
    phone: "+66 2 108 0888",
    website: "https://www.terminal21.co.th",
  },

  {
    id: 23,
    nbhd: "sukhumvit",
    name: "Chatuchak Weekend Market",
    cat: "market",
    emoji: "🛒",
    address: "Kamphaeng Phet 2 Road, Chatuchak, Bangkok",
    lat: 13.7999,
    lng: 100.5500,
    search: "Chatuchak Weekend Market Bangkok JJ Market",
    note: "One of the largest outdoor markets in the world — over 15,000 stalls spread across a massive compound selling everything imaginable: handmade jewelry, vintage Levi's, ceramics, rare plants, antique Buddha images, street food, live animals, handwoven textiles, and knockoff sneakers. Come with no plan and just wander. I've spent entire mornings here and barely covered a quarter of it. It's loud, hot, chaotic, and absolutely magnificent.",
    hours: "Sat–Sun 9:00am–6:00pm",
    tip: "Photograph a market map when you arrive — you will get lost. Sections 2 and 3 are best for vintage clothing and crafts. Arrive early before it gets swelteringly hot. Bring cash only. Mo Chit BTS station drops you right at the entrance.",
    type: "Outdoor Weekend Market",
    blog: "https://www.nomadicmatt.com/travel-blogs/best-things-to-do-bangkok/",
    phone: "+66 2 272 4813",
    website: "https://www.chatuchakmarket.org",
  },

  {
    id: 24,
    nbhd: "sukhumvit",
    name: "Rot Fai Train Night Market",
    cat: "market",
    emoji: "🌙",
    address: "Srinakarin Road, Prawet, Bangkok",
    lat: 13.7038,
    lng: 100.6440,
    search: "Rot Fai Train Night Market Bangkok vintage",
    note: "The coolest night market in Bangkok — and one of the city's most genuine. Rot Fai (Train Market) is an enormous outdoor bazaar on the grounds of an old train yard, selling vintage American cars, 1950s memorabilia, vinyl records, antique military gear, Mao kitsch, hippy fashion, and some of the best street food in the city. The vibe is creative and completely untouristy. My expat friends in Bangkok treated this as their regular Thursday night hangout.",
    hours: "Thu–Sun 5:00pm–1:00am",
    tip: "Takes around 30 minutes by Grab from central Sukhumvit. Bring cash. The food section in the center has excellent variety. The vintage car and motorcycle collection is extraordinary — and people actually drive the cars here.",
    type: "Night Market",
    blog: "https://www.nomadicmatt.com/travel-guides/thailand-travel-tips/bangkok/",
    phone: "",
    website: "",
  },

  // ─── RIVERSIDE / CHAO PHRAYA ─────────────────────────────────────────────

  {
    id: 25,
    nbhd: "riverside",
    name: "Chao Phraya River (Express Boat)",
    cat: "landmark",
    emoji: "⛵",
    address: "Sathorn Pier (Central Pier), Bang Rak",
    lat: 13.7219,
    lng: 100.5133,
    search: "Chao Phraya River express boat Bangkok",
    note: "The best value tour in Bangkok, and the one most visitors completely overlook. Instead of paying for an expensive river cruise, just hop on the regular orange-flag Chao Phraya Express Boat from Sathorn Pier. For just 15 THB you get an incredible ride past Wat Arun, the Grand Palace, Chinatown's riverside, old wooden temples on stilts, and traditional life along the riverbanks. Ride to the end of the line and back — about 90 minutes of pure, unfiltered Bangkok.",
    hours: "Daily 6:00am–7:00pm",
    tip: "Take the orange-flag boats (15 THB flat-rate, stops at all piers). Avoid the tourist boats that cost 10x as much for the same view. The covered rear of the boat is the best position for photos without getting splashed.",
    type: "River Sightseeing",
    blog: "https://www.nomadicmatt.com/travel-blogs/best-things-to-do-bangkok/",
    phone: "",
    website: "https://www.chaophrayaexpressboat.com",
  },

  {
    id: 26,
    nbhd: "riverside",
    name: "ICONSIAM",
    cat: "landmark",
    emoji: "🛍️",
    address: "299 Charoen Nakhon Road, Khlong San",
    lat: 13.7256,
    lng: 100.5087,
    search: "ICONSIAM Bangkok riverside luxury mall",
    note: "Bangkok's most spectacular mall — which is saying something in a city this obsessed with malls. ICONSIAM sits dramatically on the Chao Phraya with river views from every floor. The real draw is SookSiam on the ground floor: a recreated indoor floating market with canals, traditional food stalls representing different Thai regions, and craft vendors from across the country. Even if you don't shop, it's worth visiting just for the architecture and the food.",
    hours: "Daily 10:00am–10:00pm",
    tip: "Take the free shuttle boat from Sathorn Pier — it runs every 15 minutes and is far faster than road traffic. Emsphere next door has restaurants open until 3am. Riverside terrace outside is excellent for sunset views.",
    type: "Riverside Luxury Mall",
    blog: "https://www.nomadicmatt.com/travel-guides/thailand-travel-tips/bangkok/",
    phone: "+66 2 495 7080",
    website: "https://www.iconsiam.com",
  },

  {
    id: 27,
    nbhd: "riverside",
    name: "Calypso Cabaret",
    cat: "cafe",
    emoji: "🎭",
    address: "2194 Charoen Krung Road, Asiatique, Bang Kho Laem",
    lat: 13.7220,
    lng: 100.5175,
    search: "Calypso Cabaret Bangkok ladyboy show Asiatique",
    note: "Bangkok's most celebrated cabaret show — and genuinely one of the most entertaining evenings you can spend in the city. Founded in 1988, Calypso features outstanding ladyboy performers in elaborate costumes performing show tunes, K-pop, traditional Thai dance, and full musical productions with slick choreography and bigger-than-life costumes. It's Las Vegas energy transplanted to a Bangkok riverside warehouse. The performers are extraordinary and the audience energy is electric.",
    hours: "Performances at 7:45pm and 9:30pm daily",
    tip: "Book online in advance — it sells out regularly. Located in Asiatique the Riverfront, which makes for a great pre-show dinner and wander. After the show, grab street food at the Asiatique night market.",
    type: "Cabaret Show",
    blog: "https://www.nomadicmatt.com/travel-blogs/best-things-to-do-bangkok/",
    phone: "+66 2 688 1415",
    website: "https://www.calypsocabaret.com",
  },

  {
    id: 28,
    nbhd: "riverside",
    name: "Asiatique The Riverfront",
    cat: "market",
    emoji: "🌙",
    address: "2194 Charoen Krung Road, Wat Phraya Krai, Bang Kho Laem",
    lat: 13.7198,
    lng: 100.5136,
    search: "Asiatique Riverfront Bangkok night market",
    note: "A sprawling open-air night market built in converted early-20th century riverside warehouses, with a giant Ferris wheel that glows over the Chao Phraya after dark. More than 1,500 shops sell clothing, accessories, handcrafts, and art, and the food and bar scene along the riverside is genuinely excellent. It's more sophisticated than most Bangkok night markets — popular with locals and visitors equally. The riverside setting at night is particularly beautiful.",
    hours: "Daily 5:00pm–midnight",
    tip: "Take the free shuttle boat from Sathorn Pier. Arrive around 5:30pm as the market opens for the best atmosphere and to beat the evening rush. The riverside restaurants are perfect for dinner with river views.",
    type: "Riverside Night Market",
    blog: "https://www.nomadicmatt.com/travel-guides/thailand-travel-tips/bangkok/",
    phone: "+66 2 108 4488",
    website: "https://www.asiatiquethailand.com",
  },

  // ─── THONG LO / EKKAMAI ──────────────────────────────────────────────────

  {
    id: 29,
    nbhd: "thonglor",
    name: "Thong Lo (Sukhumvit Soi 55)",
    cat: "cafe",
    emoji: "🍸",
    address: "Sukhumvit Soi 55 (Thong Lo), Watthana",
    lat: 13.7228,
    lng: 100.5847,
    search: "Thong Lo Bangkok nightlife dining district",
    note: "The neighborhood where Bangkok goes when it wants to dress up and be seen. Thong Lo is the city's most fashionable district — packed with rooftop bars, excellent Japanese restaurants, boutique coffee shops, wine bars, and clubs where Bangkok's young upper class comes to spend money and look good. The vibe is more Tokyo than Southeast Asia. When I want a sophisticated evening rather than a chaotic one, Thong Lo is where I come. Walkable, energetic, and genuinely stylish.",
    hours: "Active from 6pm onwards",
    tip: "Beer Belly has excellent craft beer and 2-for-1 happy hour 5–8pm. Rabbit Hole is the most serious cocktail bar in the neighborhood. Park your money in Ekkamai (next soi over) for a more laid-back vibe with excellent street food.",
    type: "Upscale Dining & Bar District",
    blog: "https://www.nomadicmatt.com/travel-guides/thailand-travel-tips/bangkok/",
    phone: "",
    website: "",
  },

  {
    id: 30,
    nbhd: "thonglor",
    name: "Rabbit Hole Bar",
    cat: "cafe",
    emoji: "🍹",
    address: "125 Sukhumvit Soi 55 (Thong Lo), Watthana",
    lat: 13.7286,
    lng: 100.5848,
    search: "Rabbit Hole cocktail bar Thong Lo Bangkok",
    note: "The swankiest cocktail bar in Thong Lo and one of my favorite places to drink in all of Bangkok. Rabbit Hole is a moody, dimly-lit space that feels like the world's most stylish underground club, with bartenders who treat cocktail-making as genuine craft. Ask for their recommendations and trust them completely — they rotate the menu seasonally and know what they're doing. This is where I take people when I want to show off what Bangkok drinks when it gets serious.",
    hours: "Daily 6:00pm–2:00am",
    tip: "No reservations needed but arrive before 9pm if you want a table on weekends. The menu changes seasonally. Dress smart — it's not strictly enforced but you'll feel out of place in flip-flops.",
    type: "Craft Cocktail Bar",
    blog: "https://www.nomadicmatt.com/travel-guides/thailand-travel-tips/bangkok/",
    phone: "",
    website: "",
  },

  {
    id: 31,
    nbhd: "thonglor",
    name: "Beer Belly",
    cat: "cafe",
    emoji: "🍺",
    address: "Sukhumvit Soi 55 (Thong Lo), Watthana",
    lat: 13.7248,
    lng: 100.5857,
    search: "Beer Belly craft beer bar Thong Lo Bangkok",
    note: "Bangkok's best craft beer bar and one of my go-to spots when I'm in the city. Beer Belly has a rotating selection of excellent Thai and international craft beers on draft, a casual outdoor terrace perfect for Bangkok evenings, and a genuinely fun crowd. Happy hour runs 5–8pm with 2-for-1 on everything — one of the best happy hours in the city. There's beer pong in the back if you want to make friends fast. I've had some of my best Bangkok nights starting here.",
    hours: "Daily 5:00pm–midnight",
    tip: "2-for-1 happy hour 5–8pm — mark it in your calendar. The outdoor terrace is perfect when the weather cooperates. Pair with street food from the stalls near Thong Lo BTS.",
    type: "Craft Beer Bar",
    blog: "https://www.nomadicmatt.com/travel-guides/thailand-travel-tips/bangkok/",
    phone: "",
    website: "",
  },

  {
    id: 32,
    nbhd: "thonglor",
    name: "Ekkamai Street Food",
    cat: "food",
    emoji: "🍢",
    address: "Sukhumvit Soi 63 (Ekkamai), Watthana",
    lat: 13.7157,
    lng: 100.5844,
    search: "Ekkamai street food Bangkok night market",
    note: "Thong Lo's grittier, more affordable sibling. Ekkamai has a brilliant street food scene clustered around the BTS station — grilled seafood, noodle shops, mango sticky rice stands, and some of Bangkok's best local-style restaurants where nobody is trying to translate the menu for you. There's also a great night market on weekends. Far fewer tourists, better food at lower prices. This is where the Thong Lo crowd comes to eat cheaply and well.",
    hours: "Evening from 5pm; market Thu–Sun",
    tip: "Try the grilled seafood stalls near Ekkamai BTS — order by pointing at what looks good. The chicken satay with peanut sauce is exceptional. Two BTS stops from Asok — fast and cheap to get here.",
    type: "Street Food Area",
    blog: "https://www.nomadicmatt.com/travel-guides/thailand-travel-tips/bangkok/",
    phone: "",
    website: "",
  },

  {
    id: 33,
    nbhd: "thonglor",
    name: "Siam Paragon",
    cat: "landmark",
    emoji: "🛍️",
    address: "991 Rama I Road, Pathum Wan",
    lat: 13.7461,
    lng: 100.5348,
    search: "Siam Paragon Bangkok luxury mall food hall",
    note: "The jewel of Bangkok's extraordinary mall scene. Siam Paragon is enormous, ice-cold air-conditioned, and sells everything from Ferrari to fine dining. For visitors, the real draws are the basement Gourmet Market (an outstanding food hall with cuisines from across Thailand and Asia), the SEA LIFE Bangkok aquarium, and the cinema complex. It's also a world-class people-watching spot — Bangkok's entire social spectrum passes through on weekends. The basement food hall alone is worth the visit.",
    hours: "Daily 10:00am–10:00pm",
    tip: "The Gourmet Market basement is excellent for lunch or stocking up on exotic Thai snacks and ingredients. The SEA LIFE aquarium is genuinely world-class if you're traveling with kids. Right at Siam BTS — the most central point in all of Bangkok.",
    type: "Luxury Shopping Mall",
    blog: "https://www.nomadicmatt.com/travel-guides/thailand-travel-tips/bangkok/",
    phone: "+66 2 690 1000",
    website: "https://www.siamparagon.co.th",
  },

  // ─── OLD CITY (additional) ──────────────────────────────────────────────────

  {
    id: 34,
    nbhd: "old-city",
    name: "Pad Thai Thip Samai",
    cat: "food",
    emoji: "🍜",
    address: "313 Maha Chai Road, Samran Rat, Phra Nakhon",
    lat: 13.7534,
    lng: 100.5019,
    search: "Pad Thai Thip Samai Bangkok",
    note: "If you eat pad thai once in Bangkok, eat it here. Thip Samai has been frying noodles on this Old City street since 1966 and is universally considered the finest pad thai in the city — which makes it probably the best pad thai on earth. The signature version is wrapped in a thin egg omelette and stuffed with fat river prawns. The queue runs down the street every night. Worth every minute of the wait.",
    hours: "Daily 5:00pm–2:00am (closed alternate Tuesdays)",
    tip: "Order the pad thai wrapped in egg — it's the signature dish. Arrive before 6pm to beat the main queue. Cash only. They also press excellent fresh orange juice to order.",
    type: "Legendary Pad Thai Restaurant",
    blog: "https://www.nomadicmatt.com/travel-guides/thailand-travel-tips/bangkok/",
    phone: "+66 2 221 6280",
    website: "https://www.thipsamai.com",
  },

  {
    id: 35,
    nbhd: "old-city",
    name: "Soi Rambuttri",
    cat: "cafe",
    emoji: "🍻",
    address: "Soi Rambuttri, Banglamphu, Phra Nakhon",
    lat: 13.7591,
    lng: 100.4968,
    search: "Soi Rambuttri Bangkok bars nightlife",
    note: "Khao San Road's quieter, more likeable sibling — and honestly where I prefer to spend evenings in the Old City. Soi Rambuttri runs parallel to Khao San and has all the energy with a fraction of the noise. The bars play music at a volume where you can still have a conversation. The street food is better, the crowds friendlier. My favourite spot for a long evening beer with other travellers.",
    hours: "Active from 5pm; peaks 9pm onwards",
    tip: "Brick Bar at the far end has live bands every night — no cover charge, just buy drinks. One of the best music venues in Bangkok.",
    type: "Bar Street",
    blog: "https://www.nomadicmatt.com/travel-guides/thailand-travel-tips/bangkok/",
    phone: "",
    website: "",
  },

  {
    id: 36,
    nbhd: "old-city",
    name: "Brick Bar",
    cat: "cafe",
    emoji: "🎵",
    address: "265 Khao San Road, Banglamphu, Phra Nakhon",
    lat: 13.7588,
    lng: 100.4975,
    search: "Brick Bar Bangkok live music Khao San",
    note: "The best live music bar in the Khao San area and one of my favourite places to spend an evening in Bangkok. Live bands play Thai and international music every single night from around 9pm with no cover charge — just buy drinks. The crowd is a great mix of travellers and locals. I have ended up here accidentally more times than I can count and stayed until 2am every time.",
    hours: "Daily 6:00pm–2:00am",
    tip: "No cover charge — just buy drinks. Get there before 9:30pm to grab a table near the stage. Bands start around 9pm and play until closing.",
    type: "Live Music Bar",
    blog: "https://www.nomadicmatt.com/travel-guides/thailand-travel-tips/bangkok/",
    phone: "+66 2 629 4477",
    website: "",
  },

  {
    id: 37,
    nbhd: "old-city",
    name: "Wat Mahathat",
    cat: "church",
    emoji: "⛩️",
    address: "3 Na Phra That Alley, Phra Nakhon",
    lat: 13.7573,
    lng: 100.4921,
    search: "Wat Mahathat Bangkok royal temple amulet market",
    note: "One of Bangkok's oldest and most important royal temples, with a lived-in monastery feeling the more famous tourist temples lack. What makes it especially interesting is the amulet market that springs up in the surrounding alleys every weekend — hundreds of vendors selling Buddhist amulets for luck, love, money, and protection. The amulet trade is a deeply serious Thai cultural practice and fascinating to witness even if you buy nothing.",
    hours: "Daily 9:00am–6:00pm",
    tip: "The weekend amulet market in the alleys is one of the most authentic markets in Bangkok. Come Saturday or Sunday morning. Admission is 50 THB.",
    type: "Royal Buddhist Temple",
    blog: "https://www.nomadicmatt.com/travel-blogs/best-things-to-do-bangkok/",
    phone: "",
    website: "",
  },

  {
    id: 38,
    nbhd: "old-city",
    name: "Wat Ratchanatdaram (Loha Prasat)",
    cat: "church",
    emoji: "⛩️",
    address: "2 Maha Chai Road, Wat Bowon Niwet, Phra Nakhon",
    lat: 13.7557,
    lng: 100.5044,
    search: "Wat Ratchanatdaram Loha Prasat Bangkok metal roof temple",
    note: "One of the most architecturally extraordinary temples in Thailand — and almost completely overlooked by visitors. Built in the 1840s by King Rama III, this is one of only a handful of temples in the world with a bronze roof. The spired metal structure called Loha Prasat rises 36 metres with 37 metal spires representing the 37 virtues needed to attain enlightenment. Extraordinary to look at. Free entry. Combines perfectly with Wat Saket directly across the road.",
    hours: "Daily 9:00am–5:00pm",
    tip: "Free entry. Almost never crowded despite being close to the Grand Palace. Best photographed in the early morning light. Right across from Wat Saket — easy to combine both in one visit.",
    type: "Buddhist Temple",
    blog: "https://www.nomadicmatt.com/travel-blogs/best-things-to-do-bangkok/",
    phone: "",
    website: "",
  },

  // ─── CHINATOWN (additional) ──────────────────────────────────────────────────

  {
    id: 39,
    nbhd: "chinatown",
    name: "T&K Seafood (Soi Texas)",
    cat: "food",
    emoji: "🦐",
    address: "49-51 Soi Phadung Dao, Samphanthawong",
    lat: 13.7399,
    lng: 100.5126,
    search: "T&K Seafood Bangkok Chinatown Soi Texas",
    note: "The most famous seafood tables on Soi Texas — Chinatown's legendary seafood alley — and the place that epitomises the Bangkok Chinatown eating experience. T&K and its neighbour Lek & Rut face each other across a narrow lane, both doing roaring business every night with grilled prawns, crab, oyster omelettes, and steamed fish over charcoal. Plastic stools, fluorescent lights, shouted orders, incredible food at prices that seem wrong. Bangkok eating at its most gloriously chaotic.",
    hours: "Daily 4:00pm–midnight",
    tip: "Arrive before 7pm for a table — the alley fills completely after dark. Order the grilled river prawns and the oyster omelette. Cold Singha beer is the only accompaniment you need.",
    type: "Chinatown Seafood Restaurant",
    blog: "https://www.nomadicmatt.com/travel-guides/thailand-travel-tips/bangkok/",
    phone: "+66 2 223 4519",
    website: "",
  },

  // ─── SILOM & SIAM (additional) ───────────────────────────────────────────────

  {
    id: 40,
    nbhd: "silom",
    name: "Central World",
    cat: "landmark",
    emoji: "🛍️",
    address: "999/9 Rama I Road, Pathum Wan",
    lat: 13.7469,
    lng: 100.5388,
    search: "Central World Bangkok shopping mall",
    note: "One of the largest shopping malls in Southeast Asia — and a genuine Bangkok landmark. Over 600 stores, multiple dining floors, a rooftop bar, and direct connections to Siam and Chit Lom BTS. The outdoor plaza hosts major public events including Bangkok's biggest New Year's Eve countdown. Emsphere next door has restaurants open until 3am. More than a mall — it's a city hub.",
    hours: "Daily 10:00am–10:00pm",
    tip: "The food floors have excellent value set lunch deals on weekdays. Directly connected to Chit Lom BTS — no need to step outside.",
    type: "Mega Shopping Mall",
    blog: "https://www.nomadicmatt.com/travel-guides/thailand-travel-tips/bangkok/",
    phone: "+66 2 021 9999",
    website: "https://www.centralworld.co.th",
  },

  {
    id: 41,
    nbhd: "silom",
    name: "Platinum Fashion Mall",
    cat: "landmark",
    emoji: "👗",
    address: "222 Phetchaburi Road, Ratchathewi",
    lat: 13.7521,
    lng: 100.5394,
    search: "Platinum Fashion Mall Bangkok Pratunam cheap clothes",
    note: "The best place in Bangkok to buy cheap, trendy clothing — a wholesale garment market disguised as a mall. Floor upon floor of small stalls selling knockoff streetwear and surprisingly decent basics at prices that seem impossible. It is cash-and-carry, no-nonsense, and packed with locals stocking up and travellers filling an extra bag. The street food stalls outside are excellent too.",
    hours: "Daily 9:00am–8:00pm",
    tip: "Bring cash — almost no stalls take cards. Prices are already very low but some vendors will negotiate on multiples. The surrounding Pratunam Market streets have even cheaper food stalls.",
    type: "Budget Fashion Mall",
    blog: "https://www.nomadicmatt.com/travel-guides/thailand-travel-tips/bangkok/",
    phone: "+66 2 121 8000",
    website: "https://www.platinumfashionmall.com",
  },

  {
    id: 42,
    nbhd: "silom",
    name: "Saxophone Pub",
    cat: "cafe",
    emoji: "🎷",
    address: "3/8 Phaya Thai Road, Ratchathewi",
    lat: 13.7619,
    lng: 100.5371,
    search: "Saxophone Pub Bangkok Victory Monument live jazz",
    note: "Bangkok's most beloved live music venue — a genuine institution open for over 35 years. A low-ceilinged, dimly-lit pub near Victory Monument with live jazz, blues, and rock bands every single night. It draws an older crowd of locals, expats, and music lovers who come for the music rather than the scene. In a city that can feel relentlessly trendy, Saxophone is reassuringly timeless. I come here on every long Bangkok visit.",
    hours: "Daily 6:00pm–2:00am",
    tip: "Live music starts around 9pm. No cover charge — just buy drinks. Get there early for a good table. Victory Monument BTS is 2 minutes walk.",
    type: "Live Music Jazz Bar",
    blog: "https://www.nomadicmatt.com/travel-guides/thailand-travel-tips/bangkok/",
    phone: "+66 2 246 5472",
    website: "https://www.saxophonepub.com",
  },

  {
    id: 43,
    nbhd: "silom",
    name: "Victory Monument Street Food",
    cat: "food",
    emoji: "🍱",
    address: "Victory Monument Roundabout, Ratchathewi",
    lat: 13.7629,
    lng: 100.5374,
    search: "Victory Monument Bangkok street food boat noodles",
    note: "One of Bangkok's great street food hubs — a massive transport roundabout ringed with food stalls and noodle shops serving thousands of commuters daily. The northeast side is famous for boat noodle alley: tiny bowls of rich spiced pork or beef broth, ordered in sets of 3 or 4. The surrounding sois have some of the most authentic and affordable eating in the city. This is where Bangkok locals eat, not tourists.",
    hours: "Stalls open 7am; peaks 11am–2pm and 5pm–9pm",
    tip: "The boat noodle alley is on the northeast side of the monument. Order at least 4 bowls — they're small by design. A full meal costs about 60–80 THB. Victory Monument BTS is right above.",
    type: "Street Food Hub",
    blog: "https://www.nomadicmatt.com/travel-guides/thailand-travel-tips/bangkok/",
    phone: "",
    website: "",
  },

  // ─── SUKHUMVIT (additional) ──────────────────────────────────────────────────

  {
    id: 44,
    nbhd: "sukhumvit",
    name: "Sukhumvit Soi 38 Street Food",
    cat: "food",
    emoji: "🌙",
    address: "Sukhumvit Soi 38, Khlong Toei, Bangkok",
    lat: 13.7249,
    lng: 100.5703,
    search: "Sukhumvit Soi 38 Bangkok street food night",
    note: "The most accessible street food strip in Sukhumvit — a perfect introduction to Bangkok night eating for anyone staying in this part of town. Soi 38 comes alive after dark with stalls serving pad thai, grilled satay, tom yum, mango sticky rice, and fresh fruit shakes. I have had more midnight pad thais here than I can count. The mango sticky rice stall near the entrance is one of the best in Bangkok.",
    hours: "Daily 5:00pm–2:00am",
    tip: "Two BTS stops from Asok. Good option when you want quality street food without trekking to Chinatown. Prices are fair — no need to negotiate.",
    type: "Street Food Strip",
    blog: "https://www.nomadicmatt.com/travel-guides/thailand-travel-tips/bangkok/",
    phone: "",
    website: "",
  },

  {
    id: 45,
    nbhd: "sukhumvit",
    name: "Cheap Charlie's",
    cat: "cafe",
    emoji: "🍺",
    address: "Sukhumvit Soi 11, Khlong Toei Nuea, Watthana",
    lat: 13.7428,
    lng: 100.5524,
    search: "Cheap Charlies bar Bangkok Sukhumvit Soi 11",
    note: "The most famous dive bar in Bangkok. Cheap Charlie's is a tiny open-air bar on Sukhumvit Soi 11, covered wall to ceiling in antiques, trinkets, old photos and bizarre memorabilia accumulated over decades. No stools inside — you stand on the pavement with your beer like everyone else. Cold beer, extremely low prices, excellent people-watching, and a crowd of regulars that tells you everything about the Bangkok expat scene.",
    hours: "Mon–Sat 5:00pm–midnight (closed Sunday)",
    tip: "Cash only. Get there before 8pm or you will be three deep on the pavement. Leo beer is about 60 THB — one of the cheapest cold beers in this part of town.",
    type: "Legendary Dive Bar",
    blog: "https://www.nomadicmatt.com/travel-guides/thailand-travel-tips/bangkok/",
    phone: "",
    website: "",
  },

  {
    id: 46,
    nbhd: "sukhumvit",
    name: "Jodd Fairs Ratchada Night Market",
    cat: "market",
    emoji: "🌃",
    address: "Ratchadaphisek Road, Din Daeng, Bangkok",
    lat: 13.7626,
    lng: 100.5605,
    search: "Jodd Fairs Ratchada Bangkok night market",
    note: "The hottest night market in Bangkok right now — and one of the best designed. Hundreds of stalls sell street food, designer knock-offs, handmade jewellery, and vintage clothing in a well-organised layout that is refreshingly easy to navigate. The food variety is extraordinary — I counted stalls from at least 15 cuisines on my last visit. The neon lighting and general vibe is deeply photogenic.",
    hours: "Thu–Sun 5:00pm–midnight",
    tip: "Thailand Cultural Centre MRT is right outside — much faster than a cab from Sukhumvit. Thursday and Sunday evenings are less crowded. The grilled seafood section near the back is excellent.",
    type: "Night Market",
    blog: "https://www.nomadicmatt.com/travel-guides/thailand-travel-tips/bangkok/",
    phone: "",
    website: "",
  },

  {
    id: 47,
    nbhd: "sukhumvit",
    name: "Bangkok Butterfly Garden & Insectarium",
    cat: "nature",
    emoji: "🦋",
    address: "Kamphaeng Phet 3 Road, Chatuchak, Bangkok",
    lat: 13.8073,
    lng: 100.5518,
    search: "Bangkok Butterfly Garden Insectarium Chatuchak free",
    note: "A wonderful and completely unexpected escape tucked behind the Chatuchak Weekend Market — and almost always empty of tourists. A domed enclosure houses over 500 live butterflies flying freely among tropical flowers, ferns, and small waterfalls. Genuinely beautiful and takes about 45 minutes. The Insectarium next door has beetles, stick insects, and scorpions. The surrounding Chatuchak, Queen Sirikit, and Rod Fai parks make this a perfect half-day nature break.",
    hours: "Tue–Sun 8:30am–4:30pm",
    tip: "Free entry — one of the best free attractions in Bangkok. Mo Chit BTS or Chatuchak Park MRT. Combine with the weekend market for a full day in the area.",
    type: "Butterfly Garden",
    blog: "https://www.nomadicmatt.com/travel-guides/thailand-travel-tips/bangkok/",
    phone: "+66 2 272 4359",
    website: "",
  },

  // ─── RIVERSIDE (additional) ──────────────────────────────────────────────────

  {
    id: 48,
    nbhd: "riverside",
    name: "Bangkokian Museum",
    cat: "landmark",
    emoji: "🏠",
    address: "273 Soi Charoen Krung 43, Bang Rak",
    lat: 13.7262,
    lng: 100.5168,
    search: "Bangkokian Museum Bangkok folk history",
    note: "One of Bangkok's most intimate museums — and one almost no visitors know about. Three beautifully preserved wooden houses from the 1930s and 40s, filled with the personal belongings of the middle-class Thai family who lived there: furniture, clothing, medicine, kitchen equipment, photographs. It gives a rare, human-scale picture of what Bangkok domestic life actually looked like in the mid-20th century. Free entry with guided tour included.",
    hours: "Wed–Sun 10:00am–4:00pm",
    tip: "Free entry, guided tour included. Takes about 45 minutes. Close to Saphan Taksin BTS — easy to combine with a riverside walk or Asiatique.",
    type: "Folk History Museum",
    blog: "https://www.nomadicmatt.com/travel-guides/thailand-travel-tips/bangkok/",
    phone: "+66 2 234 6058",
    website: "",
  },

  {
    id: 49,
    nbhd: "riverside",
    name: "Joe Louis Thai Puppet Theatre",
    cat: "landmark",
    emoji: "🎭",
    address: "Asiatique The Riverfront, Zone G, Charoen Krung Road",
    lat: 13.7204,
    lng: 100.5143,
    search: "Joe Louis Thai Puppet Theatre Bangkok Asiatique",
    note: "Thailand's most accomplished traditional puppet theatre. Founded by master puppeteer Sakorn Yang-keawsot, the troupe performs with extraordinary three-person marionettes that take years to master. Each puppet requires three operators moving in perfect synchronisation. The performances draw on the Ramakien, Thailand's epic national poem, and the artistry is genuinely breathtaking. Housed at Asiatique, making it easy to combine with dinner.",
    hours: "Shows at 7:30pm and 9:00pm daily",
    tip: "Book ahead — shows sell out. Arrive early for dinner at Asiatique before the show. The puppets used in performances are also displayed in the entrance — extraordinary objects up close.",
    type: "Traditional Puppet Theatre",
    blog: "https://www.nomadicmatt.com/travel-guides/thailand-travel-tips/bangkok/",
    phone: "+66 2 108 4488",
    website: "https://www.joelouistheatre.com",
  },

  {
    id: 50,
    nbhd: "riverside",
    name: "Mahanakhon SkyWalk",
    cat: "landmark",
    emoji: "🏙️",
    address: "114 Narathiwat Ratchanakharin Road, Silom, Bang Rak",
    lat: 13.7222,
    lng: 100.5280,
    search: "Mahanakhon SkyWalk Bangkok rooftop observation deck",
    note: "The highest observation deck in Bangkok, on the 78th floor of the city's tallest building. The glass-floor tray puts you directly above a 314-metre drop to the street below. The 360-degree views over Bangkok on a clear day are extraordinary — from the old city to the Chao Phraya and beyond. The Sky Beach rooftop bar on the same floor is an excellent spot for sunset drinks.",
    hours: "Daily 10:00am–midnight",
    tip: "Book online to skip the queue. Arrive 1 hour before sunset for the best light. Tickets are 850 THB and include a drink at the bar. Chong Nonsi BTS is 5 minutes walk.",
    type: "Observation Deck & Rooftop Bar",
    blog: "https://www.nomadicmatt.com/travel-guides/thailand-travel-tips/bangkok/",
    phone: "+66 2 677 8721",
    website: "https://www.kingpowermahanakhon.co.th",
  },

  // ─── THONG LO (additional) ───────────────────────────────────────────────────

  {
    id: 51,
    nbhd: "thonglor",
    name: "J.Boroski",
    cat: "cafe",
    emoji: "🍹",
    address: "Sukhumvit Soi 49/9, Khlong Toei Nuea, Watthana",
    lat: 13.7347,
    lng: 100.5787,
    search: "J Boroski Bangkok speakeasy cocktail bar no menu",
    note: "Bangkok's most legendary cocktail bar — a no-menu speakeasy that requires a reservation and serves only custom cocktails designed around your personal tastes. You tell the bartender what you like, and they create something entirely unique for you. Founded by American bartender Joseph Boroski, it has consistently appeared on Asia's 50 Best Bars list. Expensive by Bangkok standards but the craft and experience are extraordinary. One of my favourite bars in all of Asia.",
    hours: "Mon–Sat 8:00pm–2:00am (reservation required)",
    tip: "Reservations essential — book via their website. No printed menu. Be honest about your flavour preferences — the bartenders take their craft extremely seriously. Budget around 500–700 THB per cocktail.",
    type: "No-Menu Cocktail Speakeasy",
    blog: "https://www.nomadicmatt.com/travel-guides/thailand-travel-tips/bangkok/",
    phone: "",
    website: "https://www.josephboroski.com",
  },

  {
    id: 52,
    nbhd: "thonglor",
    name: "Craft Bangkok",
    cat: "cafe",
    emoji: "🍺",
    address: "Sukhumvit Soi 23, Khlong Toei Nuea, Watthana",
    lat: 13.7382,
    lng: 100.5649,
    search: "Craft Bangkok craft beer bar Sukhumvit",
    note: "The best dedicated craft beer bar in Bangkok — the place that really introduced the craft beer movement to the city. Outstanding rotating tap list of Thai and international craft beers, a proper food menu, and a comfortable design-forward interior. For anyone who drinks craft beer at home and assumes Bangkok means nothing but Chang and Singha, Craft is a revelation.",
    hours: "Daily 11:00am–midnight",
    tip: "Ask the staff for a recommendation — they know their beers extremely well. The food is genuinely good. Easy walk from Asok or Phrom Phong BTS.",
    type: "Craft Beer Bar",
    blog: "https://www.nomadicmatt.com/travel-guides/thailand-travel-tips/bangkok/",
    phone: "+66 2 662 4478",
    website: "https://www.craftbkk.com",
  },

  {
    id: 53,
    nbhd: "thonglor",
    name: "Khlong Toei Market",
    cat: "market",
    emoji: "🥬",
    address: "Khlong Toei, Bangkok",
    lat: 13.7233,
    lng: 100.5577,
    search: "Khlong Toei Market Bangkok wet market fresh produce",
    note: "Bangkok's largest and most intense wet market — the best place to experience the true scale of Thai food culture. Every morning this enormous market receives fresh produce, seafood, meat, and dry goods from across Thailand. The sheer variety of ingredients — chillies, fermented pastes, live eels, exotic fruits, mountains of fresh herbs — gives you a completely different understanding of Thai cuisine than any restaurant can. Come before 8am for the full experience.",
    hours: "Daily 3:00am–noon (best before 8am)",
    tip: "Come early — by 9am the best produce is gone. Wear shoes you don't mind getting wet. Food stalls on the market perimeter serve excellent cheap breakfasts to market workers from about 5am.",
    type: "Wholesale Wet Market",
    blog: "https://www.nomadicmatt.com/travel-guides/thailand-travel-tips/bangkok/",
    phone: "",
    website: "",
  },


];
