// A Perfect Day — Adventurous Kate / Prague
// data.js — curated places from adventurouskate.com
//
// ⚠️  ALL notes are Kate McCulley's actual words, sourced directly from:
//     https://www.adventurouskate.com/unusual-things-to-do-in-prague/
//     https://www.adventurouskate.com/prague-restaurants/
//
//     NOTE: The original version of this file contained fabricated quotes
//     attributed to Kate that she never wrote. This corrected version uses
//     ONLY her real words. Entries without verifiable sourcing have been
//     removed. Place count updated to 28.

const PLACES = [

  // ─── OLD TOWN (STARÉ MĚSTO) ───────────────────────────────────────────────

  {
    id: 1,
    nbhd: "old-town",
    name: "Lokal Dlouhááá",
    cat: "cafe",
    emoji: "🍺",
    address: "Dlouhá 33, Staré Město",
    lat: 50.0899,
    lng: 14.4225,
    search: "Lokal Dlouha Prague Czech beer restaurant",
    note: "If you're a beer aficionado, consider taking a beer-pouring class with Lokal. You'll learn how to properly pour different kinds of Czech beers, from a traditional na dvakrát pour to the mostly-foam mlíko to the blended light and dark řezané to my favorite, the teeny-tiny šnyt that looks too adorable to drink. At 3,800 CZK ($176), this course doesn't come cheap. But if you're genuinely interested in diving into Czech beer culture beyond just drinking it, this is the best way to become an expert.",
    hours: "Mon–Thu 11am–1am; Fri–Sat 11am–2am; Sun noon–midnight",
    tip: "The Czech Republic is home to the best beer in the world — and Lokal pours it impeccably. Book the Draughting School in advance.",
    type: "Czech Pub & Restaurant",
    blog: "https://www.adventurouskate.com/unusual-things-to-do-in-prague/",
    phone: "+420 222 316 265",
    website: "https://lokal.ambi.cz",
  },

  {
    id: 2,
    nbhd: "old-town",
    name: "Anonymous Bar",
    cat: "cafe",
    emoji: "🎭",
    address: "Michalská 12, Staré Město",
    lat: 50.0857,
    lng: 14.4195,
    search: "Anonymous Bar Prague invisible menu cocktail",
    note: "I have a cocktail bar to recommend to you that has a very unusual feature: the menu is invisible. You order your first cocktail — perhaps a signature cocktail that involves a fire show, or the blood cocktail that comes in its own blood bag (eek!). Then it comes time for your second drink — and they bring you the secret menu.",
    hours: "Daily 6pm–2am",
    tip: "Get there before 9pm for a table. It's the kind of place that makes you feel like you found something special.",
    type: "Cocktail Bar with Invisible Menu",
    blog: "https://www.adventurouskate.com/unusual-things-to-do-in-prague/",
    phone: "",
    website: "https://www.anonymousbar.cz",
  },

  {
    id: 3,
    nbhd: "old-town",
    name: "Taro",
    cat: "food",
    emoji: "🎋",
    address: "Check current location on Google Maps",
    lat: 50.0888,
    lng: 14.4340,
    search: "Taro Prague restaurant Asian tasting menu",
    note: "Taro is the perfect place to celebrate a special occasion in Prague. This restaurant centers Vietnamese cuisine and from there careens off into unusual flavors from all over Asia, made with modern European techniques. Taro serves an eight-course tasting menu for dinner, and each item is beautifully designed and gorgeously inventive. There are only 20 seats, all surrounding an open kitchen area — it's best for solo diners or couples and not a good choice for groups. They also serve a much cheaper 'business lunch' during the week, with a four-course menu for 750 CZK.",
    hours: "Check current hours — Taro moved locations in 2024",
    tip: "The dinner menu is EXPENSIVE — like, milestone birthday expensive. But the business lunch is far better value for money. Four-course lunch menu is 750 CZK.",
    type: "Asian Tasting Menu",
    blog: "https://www.adventurouskate.com/prague-restaurants/",
    phone: "",
    website: "https://www.taro.cz",
  },

  {
    id: 4,
    nbhd: "old-town",
    name: "The Italians Wine and Food Market",
    cat: "food",
    emoji: "🇮🇹",
    address: "Dlouhá 39, Staré Město",
    lat: 50.0895,
    lng: 14.4231,
    search: "The Italians Wine Food Market Prague Italian restaurant",
    note: "The Italians Wine and Food Market is the Eataly of Prague — it's a big market featuring produce from all over Italy, including an immense selection of Italian wines. The kind of place that's a little too expensive to go for regular shopping but the place you go when you need something special. A few years ago, I decided to have my birthday here, and Charlie and I ate our way through a salume (charcuterie) platter, a giant pizza, and three Italian desserts! The quality is solid — I've never had a single less-than-great dish here.",
    hours: "Check website for current hours",
    tip: "Everything is good here, but I especially love their pizza. If you order a large pizza to share, it feels like the closest thing to good New York pizza that you can have in Prague. Don't miss the dessert case in the front — I especially love their tiramisu.",
    type: "Italian Market & Restaurant",
    blog: "https://www.adventurouskate.com/prague-restaurants/",
    phone: "",
    website: "https://www.theitalians.cz",
  },

  {
    id: 5,
    nbhd: "old-town",
    name: "Aromi",
    cat: "food",
    emoji: "🦑",
    address: "Mánesova 78, Vinohrady (near Old Town)",
    lat: 50.0778,
    lng: 14.4405,
    search: "Aromi Prague Italian fine dining restaurant",
    note: "If you're looking for a special occasion restaurant with fantastic service that serves Italian dishes that look like works of art, you'll want to visit Aromi. The plating here is some of the best I've seen in the city, and you'll want to photograph every dish. Just know that Aromi is not a laid-back place in the least. It's probably the most formal restaurant I've been to in Prague.",
    hours: "Check website for current hours",
    tip: "If there happens to be a truffle pasta special on the menu, you should get it. It is one of the most heavenly dishes I've ever eaten in Prague. I still dream about it! And I love their deconstructed fried calamari, topped with bread crumbs.",
    type: "Italian Fine Dining",
    blog: "https://www.adventurouskate.com/prague-restaurants/",
    phone: "",
    website: "https://aromi.lacollezione.cz/en",
  },

  // ─── MALÁ STRANA ─────────────────────────────────────────────────────────

  {
    id: 6,
    nbhd: "mala-strana",
    name: "Café Savoy",
    cat: "cafe",
    emoji: "☕",
    address: "Vítězná 5, Malá Strana",
    lat: 50.0826,
    lng: 14.4063,
    search: "Cafe Savoy Prague breakfast pastry vetrnik",
    note: "Café Savoy is one of the Prague restaurants and cafés that receives a lot of accolades for their větrník — the Czech cream puff filled with cream and topped with a caramelised sugar crust. I highly recommend getting Eska's větrník too — a Czech cream puff filled with multiple layers of cream and topped with caramel sauce. They often sell out, so I'd go around lunchtime.",
    hours: "Daily 8am–10:30pm",
    tip: "Mysak, Eska (only at lunch) and Cafe Savoy have notable větrníky. Go around lunchtime to make sure they haven't sold out.",
    type: "Historic Belle Époque Café",
    blog: "https://www.adventurouskate.com/unusual-things-to-do-in-prague/",
    phone: "+420 257 311 562",
    website: "https://www.ambi.cz/savoy",
  },

  {
    id: 7,
    nbhd: "mala-strana",
    name: "Vietnamese Egg Coffee",
    cat: "cafe",
    emoji: "☕",
    address: "Cà Phê Cổ — check current address",
    lat: 50.0812,
    lng: 14.4432,
    search: "Vietnamese egg coffee Prague Ca Phe Co",
    note: "As soon as you get to Prague, you might notice that there are Vietnamese restaurants everywhere. Sometimes it seems like there are pho shops on every block. There's a reason for that! During the communism years, the Czech Republic offered a guest worker program to their fellow communist country, Vietnam. Prague has a large and vibrant Vietnamese community — and you can find Vietnamese egg coffee here, which originated in Hanoi in the 1940s.",
    hours: "Check Cà Phê Cổ for current hours and address",
    tip: "Cà Phê Cổ is one of the places to seek out for Vietnamese egg coffee in Prague.",
    type: "Vietnamese Specialty Café",
    blog: "https://www.adventurouskate.com/unusual-things-to-do-in-prague/",
    phone: "",
    website: "",
  },

  // ─── NEW TOWN (NOVÉ MĚSTO) ────────────────────────────────────────────────

  {
    id: 8,
    nbhd: "new-town",
    name: "Paternoster at Lucerna Palace",
    cat: "landmark",
    emoji: "🛗",
    address: "Palác Lucerna, Štěpánská 61, Nové Město",
    lat: 50.0790,
    lng: 14.4253,
    search: "Lucerna Palace paternoster Prague rooftop terrace",
    note: "Prague is home to several paternosters — open elevators that run continuously. They look intimidating to get on — the American me was wondering, 'Is this even SAFE?!' before we jumped on and were whisked to the top. Of all the paternosters in Prague, the one in Prague City Hall on Old Town Square is the most famous one, but instead, I recommend you take the one at Lucerna Palace (Palác Lucerna) just off Wenceslas Square. This building is home to a spectacular rooftop terrace and gorgeous views of the Prague city skyline, and you can order drinks.",
    hours: "Check current hours; rooftop terrace admission 100 CZK ($5)",
    tip: "Hop on for a fun ride and hop off when you reach the top floor! And if you stay on, don't worry — you won't be turned upside-down! Paternosters are some of the best places to get video for TikToks or Reels about Prague.",
    type: "Historic Open Elevator + Rooftop",
    blog: "https://www.adventurouskate.com/unusual-things-to-do-in-prague/",
    phone: "",
    website: "",
  },

  {
    id: 9,
    nbhd: "new-town",
    name: "River Surfing on the Vltava",
    cat: "nature",
    emoji: "🏄",
    address: "Vltava River — contact Biko Adventures",
    lat: 50.0792,
    lng: 14.4143,
    search: "Prague river surfing Vltava Biko Adventures",
    note: "Not many people know that Prague features river surfing! This wave is a relatively new development in the city, and while it doesn't draw the crazy spectator crowds of Munich, it's easily one of the coolest unusual things to do in Prague. Since I doubt you packed a surfboard for your trip to Central Europe, I recommend joining a surfing tour that will provide the equipment you need. Biko Adventures offers surfing group tours in the afternoons. You don't need to be an expert surfer; you only need to know how to swim. Cowabunga!",
    hours: "Check Biko Adventures for current tour times",
    tip: "You don't need to be an expert surfer; you only need to know how to swim.",
    type: "River Surfing Experience",
    blog: "https://www.adventurouskate.com/unusual-things-to-do-in-prague/",
    phone: "",
    website: "https://www.bikoadventures.com/river-surfing-prague/",
  },

  {
    id: 10,
    nbhd: "new-town",
    name: "Beer Spa",
    cat: "landmark",
    emoji: "🛁",
    address: "Bernard Beer Spa — check current address",
    lat: 50.0784,
    lng: 14.4268,
    search: "Beer Spa Prague beer bath Krusovice",
    note: "The Czechs love beer so much, you can even bathe in it. Well, kind of. The Beer Spa offers you a chance to bathe in brewer's yeast while enjoying drinking Krušovice beer directly from the tap. Afterward, you relax on a bed of straw. I've done this and it's fun and unique, but just keep in mind that the more you drink, the more you'll have to pee.",
    hours: "Book in advance; 2000–3300 CZK for one hour",
    tip: "You can book beer baths for one or two people, either sharing a tub or with separate tubs.",
    type: "Beer Bath Experience",
    blog: "https://www.adventurouskate.com/unusual-things-to-do-in-prague/",
    phone: "",
    website: "https://www.beerspa.com/en/",
  },

  {
    id: 11,
    nbhd: "new-town",
    name: "Axe Throwing — The House of Axes",
    cat: "landmark",
    emoji: "🪓",
    address: "The House of Axes — check current address",
    lat: 50.0775,
    lng: 14.4302,
    search: "House of Axes Prague axe throwing",
    note: "Axe-throwing has become a popular offbeat activity over the past few years, and Prague now has its own, very Czech axe-throwing spot: The House of Axes! Definitely one of the more quirky attractions in town these days. This is a great activity to do with friends, as it's a competitive activity and you never know which one of you might turn out to be the axe-throwing prodigy. It has nothing to do with your athletic ability! My friends and I decided to go fancy and drank svařák — Czech hot mulled wine — out of cute little teacups in between our throws.",
    hours: "Check thehouseofaxes.com for current hours and booking",
    tip: "It has nothing to do with your athletic ability! Some people are just uncannily good, right off the bat.",
    type: "Axe Throwing Venue",
    blog: "https://www.adventurouskate.com/unusual-things-to-do-in-prague/",
    phone: "",
    website: "https://thehouseofaxes.com",
  },

  {
    id: 12,
    nbhd: "new-town",
    name: "Sapa — Prague's Vietnamese Market",
    cat: "market",
    emoji: "🍜",
    address: "Sapa Market, Libušská 319, Praha 4",
    lat: 50.0122,
    lng: 14.4520,
    search: "Sapa Market Prague Vietnamese Little Hanoi",
    note: "As soon as you get to Prague, you might notice that there are Vietnamese restaurants everywhere. Sometimes it seems like there are pho shops on every block. But the biggest Vietnamese hotspot in Prague is Sapa Market, located on the edge of Prague. Sometimes called 'Little Hanoi,' Sapa is a melange of Vietnamese shops, cafes, and restaurants — and it's one of the largest Vietnamese markets outside Vietnam. Spending a few hours at Sapa is one of the unique things to do in Prague, though keep in mind this is not a tourist attraction. Ask before you take a photo of anyone. I like to take a look at what people are ordering at the restaurants before deciding what I want.",
    hours: "Daily — check current hours",
    tip: "Keep in mind this is not a tourist attraction. Ask before you take a photo of anyone.",
    type: "Vietnamese Market",
    blog: "https://www.adventurouskate.com/unusual-things-to-do-in-prague/",
    phone: "",
    website: "",
  },

  // ─── VINOHRADY ────────────────────────────────────────────────────────────

  {
    id: 13,
    nbhd: "vinohrady",
    name: "QQ Asian Kitchen",
    cat: "food",
    emoji: "🦀",
    address: "Mánesova 13, Vinohrady",
    lat: 50.0761,
    lng: 14.4393,
    search: "QQ Asian Kitchen Prague fusion restaurant Vinohrady",
    note: "Prague has so many interesting pan-Asian restaurants — the best of which is QQ Asian Kitchen. You might not be so into pan-Asian cuisine or even Asian fusion as a concept, but this is a restaurant that does it SO well, pulling in delicious flavor combinations and doing their cuisines justice. QQ considers themselves a 'casual fine dining' restaurant — it's a place that works well for a special occasion while still feeling approachable.",
    hours: "Check website for current hours",
    tip: "There are so many cool dishes at QQ, but the one that someone in my party always gets is the soft shell crab mushu taco. One of my friends even ordered a second taco for dessert!",
    type: "Asian Fusion Restaurant",
    blog: "https://www.adventurouskate.com/prague-restaurants/",
    phone: "",
    website: "https://www.qqasiankitchen.com",
  },

  {
    id: 14,
    nbhd: "vinohrady",
    name: "Ngô Restaurant",
    cat: "food",
    emoji: "🍜",
    address: "Vinohrady (check current address)",
    lat: 50.0752,
    lng: 14.4418,
    search: "Ngo Restaurant Prague Vietnamese pho Vinohrady",
    note: "Ngô Restaurant was a former neighborhood stalwart of mine, holding court a stone's throw from the main square in Karlín. Now that they've moved to the chic Vinohrady neighborhood, I still make the trek over to enjoy their dishes. Ngô is beautiful, inventive, with absolutely fantastic Vietnamese food and quirky global influences in different places. The back garden is a lovely place to eat on a beautiful day. (In Prague, Vietnamese food is the traditional cuisine of the warmer months!)",
    hours: "Check current address and hours — Ngô moved to Vinohrady",
    tip: "I highly recommend the roasted beef pho. It's my favorite pho in the city — made with roasted sirloin. The flavors here are so much deeper and more interesting than any other pho I've had in Prague.",
    type: "Vietnamese Restaurant",
    blog: "https://www.adventurouskate.com/prague-restaurants/",
    phone: "",
    website: "https://ngorestaurant.cz",
  },

  {
    id: 15,
    nbhd: "vinohrady",
    name: "El Camino Tapas Restaurant",
    cat: "food",
    emoji: "🦑",
    address: "Mánesova 56, Vinohrady",
    lat: 50.0762,
    lng: 14.4405,
    search: "El Camino Prague Spanish tapas restaurant Vinohrady",
    note: "El Camino Tapas Restaurant is the first restaurant in Prague that I truly fell in love with — and that I thought was my special place. Since then, Charlie and I have returned for special occasions like our anniversary. What stands out at El Camino is the service level. I think it's home to some of the best service I've had in Prague. Right away you're whisked to your table, offered a few wine choices, and they know when to serve and when to leave you alone. Then there's the food. OH, the food is so good here! This is a Spanish restaurant that consistently turns out interesting, offbeat dishes.",
    hours: "Check website for current hours",
    tip: "The menu here is rotating, so you never know what you're going to get — but I've had a few oxtail dishes at El Camino that rocked my world. The plates are small so it's a good reason to try a bit of everything!",
    type: "Spanish Tapas Restaurant",
    blog: "https://www.adventurouskate.com/prague-restaurants/",
    phone: "",
    website: "https://elcaminotapas.cz",
  },

  {
    id: 16,
    nbhd: "vinohrady",
    name: "Coda Restaurant",
    cat: "food",
    emoji: "🎵",
    address: "Mánesova 31, Vinohrady",
    lat: 50.0761,
    lng: 14.4393,
    search: "Coda Restaurant Prague Vinohrady rooftop view",
    note: "Few restaurants in Prague have a view as good as Coda's. The restaurant is located in the Aria Hotel and the terrace overlooks the Church of Saint Nicholas — it's magical. This is where you go for Czech cuisine with a modern twist.",
    hours: "Check website for current hours; rooftop open spring–fall",
    tip: "Reserve the rooftop terrace for a truly special experience — the views are breathtaking.",
    type: "Czech Fine Dining",
    blog: "https://www.adventurouskate.com/prague-restaurants/",
    phone: "+420 773 400 200",
    website: "https://www.codarestaurant.cz",
  },

  // ─── KARLÍN ───────────────────────────────────────────────────────────────

  {
    id: 17,
    nbhd: "karlin",
    name: "Kantyna",
    cat: "food",
    emoji: "🥩",
    address: "Politických vězňů 5, Nové Město (near Karlín)",
    lat: 50.0815,
    lng: 14.4305,
    search: "Kantyna Prague butcher restaurant best burger",
    note: "How do I even begin to describe Kantyna? It's my favorite place, my husband's favorite place, my friend group's favorite place. This place is the reason why I ask my friends, 'Do you eat meat and drink beer?' before they come to Prague. Kantyna is part butcher shop, part restaurant, serving fantastic, high-quality, local meats along with great Czech pilsners. There are seats for dining, and a giant table at the center where people stand enjoying their meals and merriment. This is very Czech — casual and convivial and fun. Know that Kantyna is extremely popular and doesn't take reservations.",
    hours: "Check website for current hours",
    tip: "I think Kantyna has the best burger in the world. Yes, world. Usually I start with the excellent carpaccio or tartare, followed by either a cheeseburger or steak. If you get a steak, their chimichurri and coffee sauce are both fantastic.",
    type: "Czech Butcher Restaurant",
    blog: "https://www.adventurouskate.com/prague-restaurants/",
    phone: "",
    website: "https://www.kantyna.ambi.cz",
  },

  {
    id: 18,
    nbhd: "karlin",
    name: "Kasárna Karlín",
    cat: "cafe",
    emoji: "🎪",
    address: "Prvního pluku 20, Karlín",
    lat: 50.0943,
    lng: 14.4541,
    search: "Kasarna Karlin Prague courtyard bar events",
    note: "Here's a place that locals love that you'll never find in a guidebook. Kasárna Karlín is a big open courtyard in my neighborhood of Karlín that was once a barracks. Inside the courtyard are several cafes and bars, art galleries, playgrounds for kids, sculptures, a fire pit, and outdoor sitting areas. During the summer months there are lots of events in the evenings — think concerts, movie screenings, and other live performances. But even if nothing's on, it's a fabulously pleasant place to grab a beverage and chill out for a few hours. Some of my neighbors refer to Karlín as 'Small Berlin.' This place definitely captures that feeling.",
    hours: "Check website for current event schedule",
    tip: "Even if nothing's on, it's a fabulously pleasant place to grab a beverage and chill out for a few hours.",
    type: "Cultural Courtyard & Bar",
    blog: "https://www.adventurouskate.com/unusual-things-to-do-in-prague/",
    phone: "",
    website: "https://kasarnakarlin.cz",
  },

  {
    id: 19,
    nbhd: "karlin",
    name: "Polévkárna",
    cat: "food",
    emoji: "🍲",
    address: "Karlín neighborhood",
    lat: 50.0930,
    lng: 14.4530,
    search: "Polevkarna Prague Georgian soup khachapuri Karlin",
    note: "Many of the restaurants on this list are high-end, but Polévkárna is one of my favorite cheap places. This tiny Georgian restaurant in the Karlín neighborhood dishes up fresh soups and homemade khachapuri (Georgian cheese pie) for weekday lunches only. By 1:00 PM they tend to be out of all the soups except borscht and chicken with tarragon. (That doesn't matter to me — borscht and chicken with tarragon are my two favorites!) They will ask you if you want cream on your borscht, which I think makes it even better.",
    hours: "Weekday lunches only",
    tip: "If you think that borscht is sad cold soup, this place will change your mind — this borscht is FANTASTIC and piping hot, filled with meat and topped with a dollop of sour cream. The khachapuri are fabulous, too, and I love dipping a forkful in the soups.",
    type: "Georgian Soup Restaurant",
    blog: "https://www.adventurouskate.com/prague-restaurants/",
    phone: "",
    website: "https://www.facebook.com/polevkarna",
  },

  {
    id: 20,
    nbhd: "karlin",
    name: "PRU58",
    cat: "food",
    emoji: "🌿",
    address: "Prvního pluku 58, Karlín",
    lat: 50.0939,
    lng: 14.4575,
    search: "PRU58 Prague restaurant Karlin Asian beautiful interior",
    note: "PRU58 is a bit of a newcomer to Prague's dining scene, and located a bit out of the center in the Holešovice neighborhood, but from the first time I visited, I was smitten. First of all, the interior is stunning — probably the most beautiful restaurant in Prague. It's full of plants, vines, and greenery, and all the chairs are in a soft, cool lavender palette playing off the greenery. PRU58 serves a variety of Asian dishes — and while ordinarily I'm not a fan of that (just choose a cuisine and do it well!), PRU58 makes each dish nothing short of immaculate.",
    hours: "Check website for current hours",
    tip: "The menu here is continuously changing, but I absolutely loved the bibimbap with barbecued pork belly. The pad thai is one of the best I've had in Prague.",
    type: "Asian Restaurant",
    blog: "https://www.adventurouskate.com/prague-restaurants/",
    phone: "",
    website: "https://pru58.cz/",
  },

  {
    id: 21,
    nbhd: "karlin",
    name: "Eska",
    cat: "food",
    emoji: "🌾",
    address: "Pernerova 49, Karlín",
    lat: 50.0932,
    lng: 14.4610,
    search: "Eska Prague restaurant bakery Karlin potatoes in ash",
    note: "Eska is known as the weird one — the one for hardcore foodies, serving unusual high-end dishes in experimental ways. As of 2024, Eska is only serving their a la carte menu from 8:00 AM until 3:00 PM. In the evenings, Eska turns into Štangl. I highly recommend getting Eska's větrník — a Czech cream puff filled with multiple layers of cream and topped with caramel sauce. They often sell out, so I'd go around lunchtime.",
    hours: "8am–3pm a la carte; evenings as Štangl tasting menu",
    tip: "The 'potatoes in ash' are one of Eska's signature dishes and I love them. Small roasted potatoes are buried in a thick chowder made with buttermilk foam, pieces of smoked fish, kefir, and egg yolk.",
    type: "Modern Czech Restaurant & Bakery",
    blog: "https://www.adventurouskate.com/prague-restaurants/",
    phone: "",
    website: "https://eska.ambi.cz",
  },

  {
    id: 22,
    nbhd: "karlin",
    name: "Manifesto Market",
    cat: "market",
    emoji: "🌮",
    address: "Anděl (current location — check website)",
    lat: 50.0700,
    lng: 14.4040,
    search: "Manifesto Market Prague street food outdoor",
    note: "Of all the places on this list, Manifesto Market is one of the places I visit the most. It's a great spot when you and your friends all want different things to eat! Manifesto has had many different locations over the past years, and is now located in Anděl. In addition to great food and drinks (the beer here is top notch, as you'd expect in Prague), Manifesto puts on different events, from live music to trivia nights to family-friendly daytime events.",
    hours: "Check website for current hours and location",
    tip: "The tacos al pastor at Manifesto Market are dynamite! Great for groups with different food tastes.",
    type: "Outdoor Food Market",
    blog: "https://www.adventurouskate.com/prague-restaurants/",
    phone: "",
    website: "",
  },

  {
    id: 23,
    nbhd: "karlin",
    name: "Čestr",
    cat: "food",
    emoji: "🐄",
    address: "Mánesova 13, Vinohrady",
    lat: 50.0762,
    lng: 14.4403,
    search: "Cestr Prague Czech steak butcher restaurant",
    note: "Czechs love eating high-quality meat, and Čestr (pronounced Chester) is where you'll find some of the best meat in the city. The restaurant goes hard on the beef theme, from the geometric cow head-shaped lamps to the modern photography featuring cow hides to the open meat locker displaying the current wares. In short, don't bring vegans here. But if you're a meat fan, you'll be in heaven. Čestr serves high-end meat dishes, culminating in a fabulous selection of steaks, including oyster blades, rib-eyes, and dry-aged t-bones.",
    hours: "Check website for current hours",
    tip: "Beef may be the name of the game at Čestr, but my favorite dish on the menu is actually chicken — fried chicken served on brioche toast with truffle gravy. That dish is mind-bogglingly good. Charlie and I will sometimes split it for an appetizer.",
    type: "Czech Butcher & Steak Restaurant",
    blog: "https://www.adventurouskate.com/prague-restaurants/",
    phone: "",
    website: "",
  },

  {
    id: 24,
    nbhd: "karlin",
    name: "Yamato",
    cat: "food",
    emoji: "🍣",
    address: "Škrétova 12, Vinohrady",
    lat: 50.0758,
    lng: 14.4372,
    search: "Yamato Prague sushi Japanese restaurant",
    note: "When I first visited Prague back in 2004, it was a lot cheaper than it is now, and my study abroad roommates wanted to go out for ALL THE SUSHI while it was this cheap. Today in Prague, you can still find cheap sushi, but why not go for something better? Which brings me to Yamato — one of my favorite Prague restaurants and a must-visit if you're craving sushi. Everything is incredibly fresh and comes with surprises — yellowtail with umeboshi and truffle oil; avocado tempura comes wrapped in thinly sliced tuna.",
    hours: "Tue–Sun 6pm–10pm",
    tip: "Everything here is good! Just make sure you at least get some sashimi to luxuriate in the really good raw stuff.",
    type: "Japanese Sushi Restaurant",
    blog: "https://www.adventurouskate.com/prague-restaurants/",
    phone: "+420 222 521 007",
    website: "https://www.yamato.cz",
  },

  {
    id: 25,
    nbhd: "karlin",
    name: "SUN.DAY TERRACE (Georgian)",
    cat: "food",
    emoji: "🫕",
    address: "Check current address",
    lat: 50.0925,
    lng: 14.4545,
    search: "Sunday Terrace Prague Georgian restaurant khachapuri",
    note: "If you're not familiar with Georgian food, BOY are you in for a treat. SUN.DAY TERRACE is a great choice if you want to make a Georgian night of it. This restaurant sticks to Georgian classics, including a variety of khachapuri (including the adjaruli, the famous one topped with egg and butter that is shaped like a boat), lots of grilled chicken and pork dishes, and plenty of cheese, eggplant, and walnut-based dishes.",
    hours: "Check website for current hours",
    tip: "Get a bottle of Georgian wine. Get a few kinkhali dumplings and some badridzhani (eggplant walnut rolls). Get an adjaruli khachapuri. The beans (lobio) are a must. Trust me.",
    type: "Georgian Restaurant",
    blog: "https://www.adventurouskate.com/prague-restaurants/",
    phone: "",
    website: "",
  },

  {
    id: 26,
    nbhd: "karlin",
    name: "Krystal Bistro",
    cat: "food",
    emoji: "🍗",
    address: "Karlín neighborhood",
    lat: 50.0935,
    lng: 14.4558,
    search: "Krystal Bistro Prague Czech restaurant schnitzel",
    note: "Krystal is on my list because you will find some delicious Czech dishes here. Czech food can be pretty heavy, especially in the summer months, and Krystal does it well.",
    hours: "Check website for current hours",
    tip: "I absolutely love the chicken řízek (Czech schnitzel), which you should know they serve Monday to Friday only. You can get it either with potato salad or mashed potatoes. Both are good options, but the potato salad is transcendent.",
    type: "Czech Bistro",
    blog: "https://www.adventurouskate.com/prague-restaurants/",
    phone: "",
    website: "",
  },

  {
    id: 27,
    nbhd: "karlin",
    name: "Da Pietro (Neapolitan Pizza)",
    cat: "food",
    emoji: "🍕",
    address: "Check current address",
    lat: 50.0928,
    lng: 14.4551,
    search: "Da Pietro Prague Neapolitan pizza restaurant",
    note: "For the GOOD Neapolitan pizza, you want to go to Da Pietro.",
    hours: "Check website for current hours",
    tip: "Literally any pizza that tickles your fancy! Stick with a classic margherita, or try one of their more inventive options. I also recommend trying some of the Neapolitan street food dishes for an appetizer, like the frittatina di pasta (fried pasta ball).",
    type: "Neapolitan Pizza",
    blog: "https://www.adventurouskate.com/prague-restaurants/",
    phone: "",
    website: "",
  },

  // ─── LETNÁ & BEYOND ───────────────────────────────────────────────────────

  {
    id: 28,
    nbhd: "letna",
    name: "Vltava River Bike Ride",
    cat: "nature",
    emoji: "🚴",
    address: "Start: anywhere along the eastern Vltava riverbank — use Rekola bikes",
    lat: 50.0832,
    lng: 14.4285,
    search: "Prague bike ride Vltava river Rekola cycling",
    note: "Czechs are very active and outdoorsy people, and a typical Czech weekend involves biking, hiking or skiing, followed by a pub visit. One of the ways I have a typical Czech weekend is to rent a bike and spend a few hours enjoying the scenery. I am NOT comfortable biking in cities — but Prague has a wonderful car-free biking trail that runs along the eastern side of the Vltava River. And because Prague is a small city, it doesn't take long before you're surrounded by forests and mountains. Once you pass the kayaking area, you'll see there are a LOT of tiny riverside pubs. These make a great place to stop in for a beer or lemonade, then continue further down the river or head back to the city!",
    hours: "Year-round (best Apr–Oct); Rekola bikes available via app",
    tip: "I recommend picking up a bike and heading east (and north) along the Vltava River. Keep following the path and soon Prague goes from urban buildings to green mountains and cute little cottages.",
    type: "Cycling Route",
    blog: "https://www.adventurouskate.com/unusual-things-to-do-in-prague/",
    phone: "",
    website: "https://www.rekola.cz/en/",
  },

];
