// A Perfect Day — Adventurous Kate / Prague
// data.js — 55 places curated from adventurouskate.com
// DO NOT add GUIDE_CITY, BLOGGER_NAME, FAVS_KEY, map, or global state here.

const PLACES = [

  // ─── OLD TOWN (STARÉ MĚSTO) ───────────────────────────────────────────────

  {
    id: 1,
    nbhd: "old-town",
    name: "Old Town Square (Staroměstské náměstí)",
    cat: "landmark",
    emoji: "🏛️",
    address: "Staroměstské náměstí, Staré Město",
    lat: 50.0875,
    lng: 14.4213,
    search: "Old Town Square Prague Staromestske namesti",
    note: "I've walked through this square hundreds of times since moving to Prague and it still stops me in my tracks on a clear morning when the light hits those Gothic and Baroque towers just right. Old Town Square is the heart of historic Prague — surrounded by beautiful churches, the Týn Cathedral with its dramatic black spires, the medieval Town Hall, and that famous Astronomical Clock. Yes, it's packed with tourists. Yes, the restaurants on the square are overpriced tourist traps. But the square itself is genuinely spectacular and earns every bit of its fame.",
    hours: "Open 24 hours; Astronomical Clock chimes on the hour 9am–11pm",
    tip: "Visit early morning (before 9am) or late evening to have the square almost to yourself. The restaurants ON the square are all tourist traps — eat anywhere one block away and the quality doubles and the price halves.",
    type: "Historic Square",
    blog: "https://www.adventurouskate.com/unusual-things-to-do-in-prague/",
    phone: "",
    website: "",
  },

  {
    id: 2,
    nbhd: "old-town",
    name: "Astronomical Clock (Orloj)",
    cat: "landmark",
    emoji: "🕰️",
    address: "Staroměstské náměstí 1, Staré Město",
    lat: 50.0870,
    lng: 14.4208,
    search: "Prague Astronomical Clock Orloj Old Town Hall",
    note: "The most famous clock in Central Europe — a medieval masterpiece installed in 1410 that still works today. Every hour on the hour, the clock puts on a show: the twelve apostles parade through little windows, the figure of Death rings a bell, and the cock crows. It's kitsch and magnificent simultaneously. I'll be honest — when I first moved to Prague I was slightly dismissive of it. Now I think there's something genuinely wonderful about a 600-year-old machine that still makes a whole square full of people stop and stare.",
    hours: "Clock chimes 9am–11pm hourly; Tower open Tue–Sun 9am–9pm",
    tip: "Climb the Old Town Hall tower for the best view down onto the square and across the city rooftops — €8 and absolutely worth it. The clock mechanism is most dramatic at the top of the hour; position yourself with a clear view a few minutes before.",
    type: "Medieval Astronomical Clock",
    blog: "https://www.adventurouskate.com/unusual-things-to-do-in-prague/",
    phone: "",
    website: "https://www.prague.eu/en/object/places/94",
  },

  {
    id: 3,
    nbhd: "old-town",
    name: "Josefov — Jewish Quarter",
    cat: "landmark",
    emoji: "✡️",
    address: "Josefov, Staré Město",
    lat: 50.0906,
    lng: 14.4178,
    search: "Josefov Jewish Quarter Prague synagogues",
    note: "Prague has one of the best-preserved Jewish quarters in the world — a result of the Nazis' perverse decision to preserve it as a museum of an 'extinct race.' Six synagogues, the Jewish Town Hall, and the extraordinary Old Jewish Cemetery, where generations of burials layered over each other create an eerie landscape of 12,000 headstones packed impossibly close together. It's one of the most moving places I've visited in Europe. The Jewish heritage of Prague is beautiful, tragic, and essential to understanding the city.",
    hours: "Sun–Fri 9am–6pm (Nov–Mar until 4:30pm); closed Saturdays and Jewish holidays",
    tip: "The combined ticket covering all six synagogues and the cemetery is €16 — buy online to skip the long queues. The Old Jewish Cemetery alone is worth the visit. The Spanish Synagogue has the most beautiful interior.",
    type: "Jewish Historic Quarter",
    blog: "https://www.adventurouskate.com/unusual-things-to-do-in-prague/",
    phone: "+420 222 317 191",
    website: "https://www.jewishmuseum.cz",
  },

  {
    id: 4,
    nbhd: "old-town",
    name: "Charles Bridge (Karlův most)",
    cat: "landmark",
    emoji: "🌉",
    address: "Karlův most, Staré Město",
    lat: 50.0865,
    lng: 14.4112,
    search: "Charles Bridge Prague Karluv most",
    note: "The most iconic bridge in Central Europe — built in 1357, lined with 30 Baroque statues of saints, and linking Old Town with Malá Strana across the Vltava. By day it's absolutely rammed with tourists, souvenir vendors, and street musicians. But at 6am on a misty autumn morning, with the castle emerging from the fog above and the river sliding past below? It's one of the most beautiful urban experiences I know. I make a point of walking it early at least once every autumn. Worth it every time.",
    hours: "Open 24 hours; best at dawn",
    tip: "Cross it at sunrise — the light on the castle and river is extraordinary and you'll nearly have it to yourself. At midday in summer it's shoulder-to-shoulder and genuinely unpleasant. Touch the bronze plaque on the St John of Nepomuk statue for good luck — the shiny patch shows how many millions of hands have done the same.",
    type: "Medieval Stone Bridge",
    blog: "https://www.adventurouskate.com/unusual-things-to-do-in-prague/",
    phone: "",
    website: "",
  },

  {
    id: 5,
    nbhd: "old-town",
    name: "Lokal Dlouhááá",
    cat: "cafe",
    emoji: "🍺",
    address: "Dlouhá 33, Staré Město",
    lat: 50.0899,
    lng: 14.4225,
    search: "Lokal Dlouha Prague Czech beer restaurant",
    note: "If you want to understand what Czech pub culture is really about — and you should — Lokal is the place to do it. This bustling, convivial long hall of a restaurant in Old Town serves impeccably fresh Pilsner Urquell tank beer alongside traditional Czech food done properly: svíčková (beef tenderloin in cream sauce), goulash with bread dumplings, fried cheese. It's loud and fun and full of locals and visitors who all came for the same thing. The beer here is exceptional — poured by trained staff using the proper Czech method.",
    hours: "Mon–Thu 11am–1am; Fri–Sat 11am–2am; Sun noon–midnight",
    tip: "You can take a beer-pouring class here! The Draughting School costs around 3,800 CZK — you learn all the Czech pouring styles from mlíko (all foam) to šnyt (tiny portion). Also great just for dinner — make a reservation.",
    type: "Czech Pub & Restaurant",
    blog: "https://www.adventurouskate.com/unusual-things-to-do-in-prague/",
    phone: "+420 222 316 265",
    website: "https://lokal.ambi.cz",
  },

  {
    id: 6,
    nbhd: "old-town",
    name: "Anonymous Bar",
    cat: "cafe",
    emoji: "🎭",
    address: "Michalská 12, Staré Město",
    lat: 50.0857,
    lng: 14.4195,
    search: "Anonymous Bar Prague invisible cocktail menu",
    note: "One of my favorite quirky things to do in Prague — a cocktail bar where the menu is invisible. Not metaphorically; literally invisible. The cocktail menu at Anonymous Bar is printed in transparent ink and you need a UV light to read it. If that's too much effort, you can just describe what you're in the mood for and the bartenders will create something for you. The bar itself is gorgeous and atmospheric — a vaulted Gothic cellar in Old Town that feels like you've stumbled into a secret. Very Prague.",
    hours: "Daily 6pm–2am",
    tip: "Ask for the UV light when you arrive or just describe your flavor preferences — the bartenders are excellent. Get there before 9pm for a table. It's the kind of place that makes you feel like you found something special.",
    type: "Cocktail Bar with Invisible Menu",
    blog: "https://www.adventurouskate.com/unusual-things-to-do-in-prague/",
    phone: "",
    website: "https://www.anonymousbar.cz",
  },

  {
    id: 7,
    nbhd: "old-town",
    name: "Manifesto Market Holešovice",
    cat: "food",
    emoji: "🚌",
    address: "Ortenovo náměstí 8, Holešovice",
    lat: 50.1001,
    lng: 14.4421,
    search: "Manifesto Market Prague food trucks Holesovice",
    note: "My favorite food market in Prague — a pop-up market in the Holešovice neighbourhood built entirely from repurposed shipping containers, with some of the best and most diverse food stalls in the city. Korean bibimbap, al pastor tacos, fried chicken, craft beer, cocktails, Vietnamese food, Czech sausages. Plus live music, events, and a wonderfully young, local vibe. I specifically called it out in the New York Times because I was shocked that readers were surprised Czechs eat things other than pork knuckle. They definitely do.",
    hours: "Apr–Oct: Mon–Fri 11am–10pm; Sat–Sun 11am–11pm",
    tip: "Seasonal — only open spring through fall. I especially love the Korean stall Bab;rýže, the tacos al pastor from Alebrijes, and the animal-style fries. Come for lunch on a weekday when it's less packed.",
    type: "Seasonal Food Truck Market",
    blog: "https://www.adventurouskate.com/prague-restaurants/",
    phone: "",
    website: "https://www.manifesto.cz",
  },

  {
    id: 8,
    nbhd: "old-town",
    name: "Náplavka Farmers' Market",
    cat: "market",
    emoji: "🥕",
    address: "Náplavka, Nové Město (riverbank south of Palackého náměstí)",
    lat: 50.0741,
    lng: 14.4148,
    search: "Naplavka Farmers Market Prague Saturday riverside",
    note: "The best farmers' market in Prague — held every Saturday morning along the Vltava riverbank. Local farmers sell fresh vegetables, fruit, bread, honey, cheese, pickles, and prepared foods. The setting is beautiful: the river on one side, the embankment apartments above, and Vyšehrad in the distance. Prague locals come here for their weekly shop and to have coffee and chat. It's one of the most pleasant Saturday morning experiences in the city and feels far less touristy than anything in the city center.",
    hours: "Saturday 8am–2pm (year-round, weather permitting)",
    tip: "Come hungry — the food stalls are excellent for breakfast. The Vietnamese bánh mì stall is always popular. Get there before 11am for the best produce selection. Combine with a walk along the river or a visit to Vyšehrad.",
    type: "Weekly Farmers' Market",
    blog: "https://www.adventurouskate.com/unusual-things-to-do-in-prague/",
    phone: "",
    website: "",
  },

  // ─── MALÁ STRANA & HRADČANY ───────────────────────────────────────────────

  {
    id: 9,
    nbhd: "mala-strana",
    name: "Prague Castle (Pražský hrad)",
    cat: "landmark",
    emoji: "🏰",
    address: "Hradčany, Praha 1",
    lat: 50.0902,
    lng: 14.4021,
    search: "Prague Castle Prazsky hrad",
    note: "The largest ancient castle complex in the world — a walled city unto itself sitting on the hill above Prague with the whole city spread out below. The St Vitus Cathedral inside is astonishing Gothic architecture; Golden Lane is a charming little street of tiny colourful houses where Franz Kafka's sister once lived; and the views from the castle ramparts over the red rooftops and church spires of Prague are ones you'll never forget. I've been hundreds of times and never get tired of the view.",
    hours: "Castle grounds daily 6am–10pm; buildings Tue–Sun 9am–5pm",
    tip: "The castle area is free to enter — you only pay to go inside individual buildings. The basic ticket covering St Vitus Cathedral and the Old Royal Palace is around €15. Go at opening time; the crowds build quickly by 10am.",
    type: "Castle Complex & UNESCO World Heritage Site",
    blog: "https://www.adventurouskate.com/unusual-things-to-do-in-prague/",
    phone: "+420 224 372 423",
    website: "https://www.hrad.cz",
  },

  {
    id: 10,
    nbhd: "mala-strana",
    name: "Petřín Tower & Hill",
    cat: "nature",
    emoji: "🗼",
    address: "Petřínské sady, Malá Strana",
    lat: 50.0832,
    lng: 14.3932,
    search: "Petrin Tower Prague mini Eiffel Tower hill",
    note: "Prague has its own (much smaller and even more charming) Eiffel Tower — built for the Prague Jubilee Exhibition in 1891, a fifth the height of the Paris original but set on a hill so high that the views from the top are genuinely spectacular. But honestly, the whole Petřín hill is my favourite green escape in the city. Apple orchards, rose gardens, walking paths through the forest, a funicular railway for the lazy, and a mirror maze for the easily entertained. In spring, cherry blossom season makes this hill one of the most beautiful places in Prague.",
    hours: "Tower: daily 10am–8pm (Nov–Feb until 6pm); Funicular: daily 9am–11:20pm",
    tip: "The funicular (tram ticket) takes you up the hill effortlessly and is a fun ride in itself. The cherry blossom season in April transforms the hill into something genuinely magical — it's my favourite time of year in Prague.",
    type: "Park, Tower & Viewpoint",
    blog: "https://www.adventurouskate.com/unusual-things-to-do-in-prague/",
    phone: "+420 257 320 112",
    website: "https://www.petrin-rozhledna.cz",
  },

  {
    id: 11,
    nbhd: "mala-strana",
    name: "John Lennon Wall",
    cat: "landmark",
    emoji: "🎨",
    address: "Velkopřevorské náměstí, Malá Strana",
    lat: 50.0841,
    lng: 14.4069,
    search: "John Lennon Wall Prague Mala Strana",
    note: "A wall in a quiet square in Malá Strana that has been continuously covered in Beatles lyrics, peace messages, portraits of John Lennon, and colourful graffiti since the 1980s, when Czech youth used it as a symbol of peaceful resistance against the communist regime. Today it's a bit of a tourist attraction, but still genuinely moving — the wall gets repainted constantly as new visitors add their messages, and it remains a living document of hope and rebellion. Take a photo if you feel compelled to do so. Then move on and explore the rest of Malá Strana.",
    hours: "Open 24 hours",
    tip: "It's on a beautiful quiet square right by the Knights of Malta. Worth a few minutes but don't make it your primary destination. Combine with a walk through Malá Strana's beautiful embassy-lined streets and a visit to Kampa Island.",
    type: "Peace Monument & Street Art Wall",
    blog: "https://www.adventurouskate.com/unusual-things-to-do-in-prague/",
    phone: "",
    website: "",
  },

  {
    id: 12,
    nbhd: "mala-strana",
    name: "Kampa Island & Museum Kampa",
    cat: "landmark",
    emoji: "🏝️",
    address: "U Sovových mlýnů 2, Malá Strana",
    lat: 50.0843,
    lng: 14.4087,
    search: "Kampa Island Prague museum modern art",
    note: "A small island in the middle of the Vltava just south of the Charles Bridge — one of the quietest and most beautiful spots in central Prague. The riverfront park has lovely views of the bridge and Old Town, and Museum Kampa houses an excellent collection of Central European modern art in a converted mill building. The yellow rubber ducks and giant crawling babies by David Černý that dot the grounds are charming and weird in equal measure — very Prague.",
    hours: "Museum Kampa: daily 10am–6pm; Park: open 24 hours",
    tip: "The park is free and perfect for a picnic with a Charles Bridge view. Museum Kampa admission is around €8 — the František Kupka collection inside is extraordinary. Look for the 'Piss' sculpture by David Černý — two bronze figures urinating into a Czech-shaped pool.",
    type: "Island Park & Contemporary Art Museum",
    blog: "https://www.adventurouskate.com/unusual-things-to-do-in-prague/",
    phone: "+420 257 286 147",
    website: "https://www.museumkampa.cz",
  },

  {
    id: 13,
    nbhd: "mala-strana",
    name: "Strahov Monastery & Library",
    cat: "landmark",
    emoji: "📚",
    address: "Strahovské nádvoří 1/132, Hradčany",
    lat: 50.0868,
    lng: 14.3881,
    search: "Strahov Monastery Library Prague Baroque",
    note: "Two of the most beautiful library rooms in the world are tucked into this 12th-century monastery above Malá Strana — the Theological Hall and the Philosophical Hall, both Baroque masterpieces of gilded shelves, painted ceilings, and thousands of leather-bound books you're not allowed to touch. The monastery also has a wonderful beer garden and its own microbrewery serving excellent Strahov beer with views over the city. The combination of extraordinary art and excellent lager in one place is deeply satisfying.",
    hours: "Library daily 9am–noon and 1pm–5pm; Brewery daily 10am–10pm",
    tip: "The library rooms are viewed from behind a rope — you can't enter them — but they're astonishing even from the doorway. The St Norbert microbrewery in the monastery courtyard serves St Norbert beer with rooftop views of the city: one of the best beer spots in Prague.",
    type: "Historic Monastery, Library & Brewery",
    blog: "https://www.adventurouskate.com/unusual-things-to-do-in-prague/",
    phone: "+420 233 107 711",
    website: "https://www.strahovskyklaster.cz",
  },

  {
    id: 14,
    nbhd: "mala-strana",
    name: "CottoCrudo (Four Seasons)",
    cat: "food",
    emoji: "🍽️",
    address: "Veleslavínova 2a, Staré Město",
    lat: 50.0872,
    lng: 14.4133,
    search: "CottoCrudo Four Seasons Prague business lunch",
    note: "Here's the secret that Prague locals know and visitors don't: some of Prague's most expensive restaurants have remarkably affordable lunch menus. CottoCrudo is the restaurant at the Four Seasons hotel with a small outdoor terrace that has a perfect view of Prague Castle. The two-course business lunch costs around 525 CZK ($25) — for a restaurant this beautiful, in a hotel this prestigious, that price is almost absurd. I took my sister here and she thought we'd spent a fortune. We had not.",
    hours: "Mon–Fri lunch noon–2:30pm; dinner daily 6:30pm–10pm",
    tip: "Reserve the outdoor terrace for lunch — the castle view is the whole point. The fun cocktails are excellent and the two-course lunch menu is outstanding value. This is my go-to for impressing visitors without breaking the bank.",
    type: "Hotel Restaurant with Castle View",
    blog: "https://www.adventurouskate.com/unusual-things-to-do-in-prague/",
    phone: "+420 221 426 880",
    website: "https://www.fourseasons.com/prague/dining/restaurants/cottocrudo/",
  },

  // ─── NOVÉ MĚSTO (NEW TOWN) ────────────────────────────────────────────────

  {
    id: 15,
    nbhd: "new-town",
    name: "Dancing House (Tančící dům)",
    cat: "landmark",
    emoji: "🏗️",
    address: "Jiráskovo náměstí 1981/6, Nové Město",
    lat: 50.0753,
    lng: 14.4140,
    search: "Dancing House Prague Fred Ginger Frank Gehry",
    note: "Take a photo at the Dancing House! Designed by Frank Gehry and Vlado Milunić, this 1996 building on the Vltava embankment depicts a dancing couple (nicknamed Fred and Ginger after Astaire and Rogers) — one tower glass and curvy, one concrete and straight. It's one of the most distinctive pieces of architecture I've seen anywhere, made even more striking by its setting between elegant Art Nouveau buildings. The rooftop café has great views over the river. I walk past it regularly and still find it brilliant.",
    hours: "Building exterior always visible; rooftop café daily 10am–10pm",
    tip: "The rooftop café Glass Bar has some of the best views in Prague over the Vltava and the castle — have a drink and enjoy the view. The building is on the beautiful Rašínovo nábřeží embankment, perfect for a riverside walk.",
    type: "Deconstructivist Architecture Landmark",
    blog: "https://www.adventurouskate.com/unusual-things-to-do-in-prague/",
    phone: "",
    website: "https://www.tancici-dum.cz",
  },

  {
    id: 16,
    nbhd: "new-town",
    name: "Museum of Communism",
    cat: "landmark",
    emoji: "☭",
    address: "V Celnici 4, Nové Město",
    lat: 50.0880,
    lng: 14.4295,
    search: "Museum of Communism Prague",
    note: "I finally visited for the first time this year and came out with SO MANY THOUGHTS. This museum documents daily life in Czechoslovakia under communist rule from 1948 to 1989 — the propaganda, the secret police, the show trials, the empty shelves, and the brave people who resisted. For Americans especially, it's a fascinating and sobering history lesson about what real communism actually looked like in practice versus how it's often discussed back home. The parallels with contemporary politics are impossible to ignore.",
    hours: "Daily 9am–8pm",
    tip: "Allow 90 minutes. The sections on the secret police (StB) and on the 1989 Velvet Revolution are the most powerful. Admission is around €13. There's also a good communism walking tour if you want more context.",
    type: "Communist-Era History Museum",
    blog: "https://www.adventurouskate.com/ak-monthly-recap-february-2026/",
    phone: "+420 224 212 966",
    website: "https://www.muzeumkomunismu.cz",
  },

  {
    id: 17,
    nbhd: "new-town",
    name: "Wenceslas Square (Václavské náměstí)",
    cat: "landmark",
    emoji: "🏙️",
    address: "Václavské náměstí, Nové Město",
    lat: 50.0813,
    lng: 14.4276,
    search: "Wenceslas Square Prague Vaclavske namesti",
    note: "The heart of modern Prague — a long, grand boulevard that has been the stage for Czech history: the declaration of independence in 1918, the Nazi occupation, the communist coup, Jan Palach's self-immolation in protest of the Soviet invasion, and the 1989 Velvet Revolution. It doesn't look like a square at all (it's more of a wide boulevard) but it pulses with life. The National Museum at the top end is spectacular. The surrounding streets have great cafes and the metro runs right underneath.",
    hours: "Open 24 hours; National Museum daily 10am–6pm",
    tip: "The National Museum at the top of the square is underrated — beautiful Neo-Renaissance building with good natural history and history collections, €15 admission. Avoid the tourist restaurants on the square itself — walk one block in any direction for dramatically better and cheaper options.",
    type: "Historic Boulevard & Cultural Centre",
    blog: "https://www.adventurouskate.com/unusual-things-to-do-in-prague/",
    phone: "",
    website: "",
  },

  {
    id: 18,
    nbhd: "new-town",
    name: "Paternoster at Nová Radnice",
    cat: "landmark",
    emoji: "🔄",
    address: "Mariánské náměstí 2, Staré Město",
    lat: 50.0892,
    lng: 14.4195,
    search: "Prague paternoster elevator New Town Hall",
    note: "One of the most delightfully quirky things in Prague: a paternoster elevator — a continuously moving loop of open cubicles with no doors that you have to step in and out of while it's moving. They were common across Europe until health and safety regulations shut most of them down. Prague still has several working ones, including at the New Town Hall. You step in, ride it up, and have to step out quickly before it goes over the top. My husband Charlie attempted this and needed an extra rotation to gather his courage. Go. Try it. It's a tiny burst of mid-century engineering joy.",
    hours: "Mon–Fri during office hours (approx 8am–6pm)",
    tip: "The paternoster is inside a working municipal building — just walk in. Watch a few people use it before stepping in yourself. Step out decisively — hesitating is what gets people in trouble. It moves slowly; it's fine.",
    type: "Historic Moving Elevator (Paternoster)",
    blog: "https://www.adventurouskate.com/unusual-things-to-do-in-prague/",
    phone: "",
    website: "",
  },

  {
    id: 19,
    nbhd: "new-town",
    name: "Vltava River Surfing",
    cat: "nature",
    emoji: "🏄",
    address: "Vltava River wave, Smíchov/Císařský ostrov area",
    lat: 50.0801,
    lng: 14.4089,
    search: "river surfing Prague Vltava Biko Adventures",
    note: "If you've been to Munich you've seen the famous Eisbachwelle river surfers. Prague has its own river wave and it's one of the more unusual things to do here. You don't need to be an expert surfer — you just need to be able to swim. Biko Adventures runs group surfing tours in the afternoons, providing all the equipment. I have not done this (I'm not convinced I can stand on anything moving in water) but plenty of my Prague friends have and they LOVED it. Cowabunga in the Czech Republic!",
    hours: "Afternoon tours (seasonal, Apr–Oct); check Biko Adventures for schedule",
    tip: "Book through Biko Adventures — they provide boards, wetsuits, and instruction. No prior surfing experience needed. Only requirement is being able to swim. A completely unique activity in landlocked Central Europe.",
    type: "River Surfing Activity",
    blog: "https://www.adventurouskate.com/unusual-things-to-do-in-prague/",
    phone: "",
    website: "https://www.bikoadventures.com/river-surfing-prague/",
  },

  {
    id: 20,
    nbhd: "new-town",
    name: "Veltlin Wine Bar",
    cat: "cafe",
    emoji: "🍷",
    address: "Mánesova 13, Vinohrady",
    lat: 50.0763,
    lng: 14.4405,
    search: "Veltlin wine bar Prague Central European wines",
    note: "The most interesting wine bar in Prague — and one of the most interesting wine bars I've visited anywhere. Veltlin specialises exclusively in Central European wines: Czech, Slovak, Austrian, Hungarian, and Slovenian producers that you will never encounter outside this region. The wine knowledge here is extraordinary. I brought a wine-loving friend from New York who insisted she'd tried everything — she had not tried any of this and was completely overwhelmed in the best possible way.",
    hours: "Mon–Sat 4pm–midnight",
    tip: "Tell the staff your wine preferences and budget and let them guide you — their knowledge of Central European wines is genuinely expert. The small bites to accompany the wines are also good. Reservations recommended for evenings.",
    type: "Central European Wine Bar",
    blog: "https://www.adventurouskate.com/unusual-things-to-do-in-prague/",
    phone: "",
    website: "https://www.veltlin.cz",
  },

  // ─── VINOHRADY ────────────────────────────────────────────────────────────

  {
    id: 21,
    nbhd: "vinohrady",
    name: "Vinohrady Neighbourhood",
    cat: "landmark",
    emoji: "🌿",
    address: "Vinohrady, Praha 2",
    lat: 50.0740,
    lng: 14.4440,
    search: "Vinohrady Prague neighbourhood walk",
    note: "The neighbourhood where visitors go when they want a break from tourist Prague — and the neighbourhood I recommend to everyone. Vinohrady is a beautiful, leafy residential area east of the city centre, full of gorgeous Art Nouveau apartment buildings, excellent restaurants and cafes, and a genuine neighbourhood atmosphere. Náměstí Míru (Peace Square) at its heart has a lovely park surrounded by restaurants and the beautiful Neo-Gothic Church of St Ludmila. If you're planning a longer trip to Prague and want to feel like a local, stay in Vinohrady.",
    hours: "Best explored daytime and evening",
    tip: "Americke Street in Vinohrady becomes a street festival the second weekend of September with food from all over the world and live music — one of my favourite annual events in the city. Riegrovy sady park nearby has a beer garden with a skyline view.",
    type: "Upscale Residential Neighbourhood",
    blog: "https://www.adventurouskate.com/unusual-things-to-do-in-prague/",
    phone: "",
    website: "",
  },

  {
    id: 22,
    nbhd: "vinohrady",
    name: "Riegrovy Sady Beer Garden",
    cat: "cafe",
    emoji: "🍻",
    address: "Riegrovy sady, Vinohrady",
    lat: 50.0774,
    lng: 14.4459,
    search: "Riegrovy sady beer garden Prague skyline view",
    note: "The best beer garden in Prague — and competition for that title is fierce. Riegrovy sady is a beautiful hilltop park in Vinohrady with a large outdoor beer garden that has sweeping views of the Prague skyline: you can see the castle, the TV tower, and the church spires while drinking excellent Pilsner Urquell for about €2 a glass. On warm evenings it fills with young Praguers after work, and the atmosphere is exactly what a European beer garden should be: relaxed, convivial, and outdoors.",
    hours: "Beer garden Apr–Sep daily from noon (weather dependent)",
    tip: "Go on a clear evening for the best skyline views. Beer prices are spectacularly low for such a beautiful setting. The park itself is lovely for an afternoon walk even when the garden is closed.",
    type: "Park & Beer Garden with City Views",
    blog: "https://www.adventurouskate.com/unusual-things-to-do-in-prague/",
    phone: "",
    website: "",
  },

  {
    id: 23,
    nbhd: "vinohrady",
    name: "El Camino Tapas Restaurant",
    cat: "food",
    emoji: "🦑",
    address: "Mánesova 9, Vinohrady",
    lat: 50.0760,
    lng: 14.4400,
    search: "El Camino Tapas Restaurant Prague Vinohrady Spanish",
    note: "The first restaurant in Prague I truly fell in love with — and the one Charlie and I still go back to for anniversaries. El Camino serves Spanish tapas with some of the most inventive, offbeat dishes I've had in Prague, and the service is exceptional — the kind that makes you feel genuinely taken care of without being fussy. I've had oxtail dishes here that I still dream about. The wine list is primarily Spanish and excellent. This is not a budget meal, but for a special evening it's one of the best in the city.",
    hours: "Tue–Sun 6pm–11pm",
    tip: "Book ahead — the restaurant is small and popular. The menu rotates regularly so you never know exactly what you'll get, but I've never had a disappointing dish here. The small plates format means you can try many different things.",
    type: "Spanish Tapas Restaurant",
    blog: "https://www.adventurouskate.com/prague-restaurants/",
    phone: "+420 222 510 773",
    website: "https://www.elcaminotapas.cz",
  },

  {
    id: 24,
    nbhd: "vinohrady",
    name: "Aromi",
    cat: "food",
    emoji: "🍝",
    address: "Mánesova 78, Vinohrady",
    lat: 50.0752,
    lng: 14.4427,
    search: "Aromi Restaurant Prague Italian fine dining Vinohrady",
    note: "The restaurant where Charlie and I celebrated our anniversary eating their truffle pasta — and the finest Italian restaurant in Prague by a considerable distance. Aromi is upscale, beautifully designed, and serves Italian cuisine at a level that would stand up in Milan. The truffle pasta is legendary among Prague's food community and I'm not sure I've ever had better anywhere. If you're going to splurge on one special meal in Prague, this is my recommendation.",
    hours: "Mon–Sat noon–2:30pm and 6pm–10:30pm",
    tip: "Reservations are essential for dinner. The truffle pasta is non-negotiable. The business lunch menu is also excellent value. Budget €50–70 per person with wine for a dinner here.",
    type: "Fine Italian Restaurant",
    blog: "https://www.adventurouskate.com/ak-monthly-recap-april-2025/",
    phone: "+420 222 713 222",
    website: "https://www.aromi.cz",
  },

  {
    id: 25,
    nbhd: "vinohrady",
    name: "Ngô Restaurant",
    cat: "food",
    emoji: "🍜",
    address: "Blanická 17, Vinohrady",
    lat: 50.0748,
    lng: 14.4391,
    search: "Ngo Restaurant Prague Vietnamese Vinohrady pho",
    note: "My favourite Vietnamese restaurant in Prague — and the best pho I've had in the city. Ngô is the second-generation Vietnamese restaurant at its finest: inventive, beautifully presented dishes that go far beyond what the first-generation pho shops serve. Their roasted beef pho is extraordinary — deep, complex flavour from the roasted sirloin. The back garden is lovely on warm evenings. Prague's Vietnamese food scene is genuinely world-class and Ngô is its standard-bearer.",
    hours: "Mon–Sun noon–10pm",
    tip: "Order the roasted beef pho — it's what they're famous for and it deserves the reputation. The lunch specials are excellent value. The back garden is one of the nicest outdoor dining spots in Vinohrady in summer.",
    type: "Vietnamese Restaurant",
    blog: "https://www.adventurouskate.com/prague-restaurants/",
    phone: "+420 739 078 895",
    website: "https://ngorestaurant.cz",
  },

  {
    id: 26,
    nbhd: "vinohrady",
    name: "QQ Asian Kitchen",
    cat: "food",
    emoji: "🦀",
    address: "Římská 19, Vinohrady",
    lat: 50.0764,
    lng: 14.4393,
    search: "QQ Asian Kitchen Prague Asian fusion restaurant",
    note: "The best pan-Asian restaurant in Prague — and the one that makes you reconsider the whole 'pan-Asian' concept. QQ is run by Balinese and Taiwanese American chefs and the flavour combinations are extraordinary: roast rabbit betutu curry, pan-fried prawns in coconut laksa, slow-cooked beef rendang. My friend ordered the soft-shell crab mushu taco and then immediately ordered a second one for dessert. That's the QQ experience in a nutshell.",
    hours: "Tue–Sun 6pm–10:30pm",
    tip: "The soft-shell crab mushu taco is mandatory — everyone who goes gets one and everyone who gets one immediately wants another. The four-course tasting menu is excellent value for the quality. Book ahead for weekends.",
    type: "Asian Fusion Restaurant",
    blog: "https://www.adventurouskate.com/prague-restaurants/",
    phone: "+420 602 272 427",
    website: "https://www.qqasiankitchen.com",
  },

  {
    id: 27,
    nbhd: "vinohrady",
    name: "SUN.DAY TERRACE",
    cat: "food",
    emoji: "🫕",
    address: "Mánesova 87, Vinohrady",
    lat: 50.0748,
    lng: 14.4429,
    search: "Sunday Terrace Prague Georgian restaurant",
    note: "The best Georgian restaurant in Prague — and one of the things I love about living here is that we have a really excellent Georgian restaurant. Georgian cuisine is extraordinary: khachapuri (cheese-filled bread), khinkali (soup dumplings), various grilled meats and stews. SUN.DAY TERRACE does it all beautifully and the warm, convivial atmosphere makes you want to stay all evening. If you haven't had Georgian food before, Prague is an excellent place to try it.",
    hours: "Mon–Sun noon–10:30pm",
    tip: "Order the Adjarian khachapuri (the boat-shaped one with an egg on top) — you mix the egg into the melted cheese and eat it with the crust. The khinkali soup dumplings are also exceptional. Come hungry.",
    type: "Georgian Restaurant",
    blog: "https://www.adventurouskate.com/prague-restaurants/",
    phone: "+420 773 990 188",
    website: "",
  },

  // ─── KARLÍN ──────────────────────────────────────────────────────────────

  {
    id: 28,
    nbhd: "karlin",
    name: "Kantyna",
    cat: "food",
    emoji: "🥩",
    address: "Politických vězňů 5, Nové Město",
    lat: 50.0825,
    lng: 14.4303,
    search: "Kantyna Prague butcher restaurant best burger",
    note: "My favourite place in Prague. My husband's favourite place. My entire friend group's favourite place. The question I ask before any friend visits is: 'Do you eat meat and drink beer?' because if the answer is yes, we are going to Kantyna. This is a Czech butcher shop restaurant — part butcher, part casual restaurant — serving extraordinary local meats alongside perfect Czech pilsner. I think Kantyna makes the best burger in the world. Yes, world. Their steaks are also outstanding. The carpaccio and tartare are how you start. Beer is how you finish.",
    hours: "Mon–Fri 11am–11pm; Sat noon–11pm",
    tip: "No reservations for regular dining — arrive early or expect to stand at the central table (actually a fun way to meet people). The Dinner Off the Bone tasting menu is reservation-only for 6-12 people and one of my favourite unusual things to do in Prague. Start with carpaccio AND tartare if you're with a group.",
    type: "Czech Butcher Shop Restaurant",
    blog: "https://www.adventurouskate.com/prague-restaurants/",
    phone: "+420 773 201 403",
    website: "https://www.kantyna.ambi.cz",
  },

  {
    id: 29,
    nbhd: "karlin",
    name: "Kasárna Karlín",
    cat: "cafe",
    emoji: "🎪",
    address: "Prvního pluku 20/2, Karlín",
    lat: 50.0940,
    lng: 14.4540,
    search: "Kasarna Karlin Prague cultural space courtyard",
    note: "Here's a place that locals love and you'll never find in a guidebook. Kasárna Karlín is a big open courtyard in my neighbourhood that was once a barracks — now reimagined as a creative cultural space with cafes, bars, art galleries, playgrounds, sculptures, a fire pit, and outdoor sitting areas. In summer there are concerts, movie screenings, and events. My neighbours call Karlín 'Small Berlin,' and Kasárna captures that energy perfectly: creative, alternative, and completely unpretentious. One of my favourite evening hangouts.",
    hours: "Daily noon–late (summer evenings are best); check schedule for events",
    tip: "Check their social media for upcoming events — summer evenings often have live performances. The bar in the former swimming pool is a particular highlight. This is where Prague locals spend their evenings in summer.",
    type: "Creative Cultural Courtyard",
    blog: "https://www.adventurouskate.com/unusual-things-to-do-in-prague/",
    phone: "",
    website: "https://kasarnakarlin.cz",
  },

  {
    id: 30,
    nbhd: "karlin",
    name: "Polévkárna",
    cat: "food",
    emoji: "🍲",
    address: "Sokolovská 53, Karlín",
    lat: 50.0930,
    lng: 14.4525,
    search: "Polevkarna Prague Georgian soup khachapuri Karlin",
    note: "One of my favourite cheap lunch spots in my neighbourhood — a tiny Georgian-Czech soup restaurant that does two things brilliantly: hearty, warming soups and outstanding khachapuri (Georgian cheese pie). The borscht here will change your mind about borscht forever. It's piping hot, filled with meat, and topped with sour cream. The khachapuri is the ideal accompaniment — tear off pieces and dip them in the soup. It's a weekday lunch place only, which I actually love about it.",
    hours: "Mon–Fri 11am–3pm ONLY (lunch service only, weekdays only)",
    tip: "Czechs eat lunch early — arrive by noon or the soups sell out. The borscht and the chicken with tarragon are my favourites. The khachapuri (both cheese and spinach versions) are excellent. Cash preferred.",
    type: "Georgian Soup & Khachapuri Restaurant",
    blog: "https://www.adventurouskate.com/prague-restaurants/",
    phone: "",
    website: "https://www.facebook.com/polevkarna",
  },

  {
    id: 31,
    nbhd: "karlin",
    name: "Eska",
    cat: "food",
    emoji: "🌾",
    address: "Pernerova 49, Karlín",
    lat: 50.0921,
    lng: 14.4538,
    search: "Eska Prague restaurant bakery fermentation Karlin",
    note: "The restaurant that made me believe Prague had truly arrived as a serious food city. Eska is a bakery-restaurant in a converted industrial space in Karlín that takes the Czech fermentation and bread tradition completely seriously — and combines it with modern, creative cooking that's genuinely exciting. Everything is made in-house, from the sourdough bread to the fermented vegetables. The weekend brunch is one of the best I've had anywhere in Europe. A genuine landmark restaurant.",
    hours: "Mon–Fri noon–3pm and 6pm–10pm; Sat–Sun 10am–3pm and 6pm–10pm",
    tip: "The weekend brunch is spectacular and worth booking. The bread alone would justify the visit. Book at least a week ahead for Friday and Saturday dinner. The industrial Karlín setting is perfect.",
    type: "Modern Czech Bakery-Restaurant",
    blog: "https://www.adventurouskate.com/prague-restaurants/",
    phone: "+420 731 140 884",
    website: "https://www.eska.ambi.cz",
  },

  {
    id: 32,
    nbhd: "karlin",
    name: "House of Axes",
    cat: "landmark",
    emoji: "🪓",
    address: "Thámova 16, Karlín",
    lat: 50.0935,
    lng: 14.4527,
    search: "House of Axes Prague axe throwing bar",
    note: "Axe-throwing has come to Prague and it is VERY CZECH. The House of Axes is a basement venue in Karlín where you get your own throwing range, a tutorial on technique, and discover that some people are inexplicably excellent at this with zero athletic ability and no explanation. My friends and I went and drank mulled wine out of tiny china teacups between throws. The juxtaposition of dainty teacups and flying axes is exactly right. Genuinely fun, great for groups, and one of my favourite unusual Prague activities.",
    hours: "Mon–Sun noon–10pm (last booking 8pm)",
    tip: "Book ahead — sessions fill up. Alcohol is served (svařák in winter, beer and cocktails year-round). Don't worry about technique — the staff teach you and some people are naturally gifted. Great for groups of 4-8.",
    type: "Axe-Throwing Venue & Bar",
    blog: "https://www.adventurouskate.com/unusual-things-to-do-in-prague/",
    phone: "",
    website: "https://thehouseofaxes.com",
  },

  {
    id: 33,
    nbhd: "karlin",
    name: "Pivo a Burger Festival",
    cat: "food",
    emoji: "🍔",
    address: "Karlínské náměstí, Karlín",
    lat: 50.0928,
    lng: 14.4514,
    search: "Pivo a Burger festival Prague Karlin beer festival",
    note: "Prague's best food festival — and it happens in my neighbourhood, which I take as a personal compliment. Pivo a Burger (Beer and Burger) takes place twice a year, in May and September, on Karlínské náměstí, and it's exactly what it sounds like: extraordinary burgers, Czech craft beers, and general merriment in an outdoor square. We once tried a scorpion pepper burger that was so hot we had to go home and drink milk. I regret nothing. Follow their social media to find out the exact dates.",
    hours: "Festival weekend in May and September; usually Fri–Sun",
    tip: "Beware the scorpion pepper burger unless you have a genuine death wish for your mouth. The line for the most popular burger stalls gets long — arrive at opening on Saturday for the best selection. Cash preferred.",
    type: "Seasonal Beer & Burger Festival",
    blog: "https://www.adventurouskate.com/unusual-things-to-do-in-prague/",
    phone: "",
    website: "",
  },

  // ─── LETNÁ & HOLEŠOVICE ──────────────────────────────────────────────────

  {
    id: 34,
    nbhd: "letna",
    name: "Letná Park Beer Garden",
    cat: "cafe",
    emoji: "🌳",
    address: "Letenské sady, Letná",
    lat: 50.0985,
    lng: 14.4189,
    search: "Letna Park beer garden Prague views",
    note: "Have a beer at the beer garden in Letná Park! This is my standard advice to absolutely every visitor. Letná Park sits on a bluff high above the city, and the beer garden at the eastern end has one of the most spectacular views in Prague: the river, the bridges, the castle, the red rooftops below. Czech beer for €2. No crowds, no tourists, just locals enjoying a warm evening. It's one of those places where you sit down for a quick beer and look up two hours later wondering what happened.",
    hours: "Apr–Oct daily from noon (weather dependent)",
    tip: "The view to the east over the river bends is the best. Come at sunset for extraordinary light. It's a 20-minute walk from Old Town through the park, or take the 1 or 8 tram to Letenské náměstí. The park itself is excellent for running and cycling.",
    type: "Park Beer Garden with City Views",
    blog: "https://www.adventurouskate.com/unusual-things-to-do-in-prague/",
    phone: "",
    website: "",
  },

  {
    id: 35,
    nbhd: "letna",
    name: "Dejvice Farmers' Market (Kulaťák)",
    cat: "market",
    emoji: "🧅",
    address: "Vítězné náměstí (Kulaťák), Dejvice",
    lat: 50.1004,
    lng: 14.3936,
    search: "Dejvice Farmers Market Prague Kulatak Saturday",
    note: "My favourite Saturday morning routine in Prague: the Dejvice Farmers' Market at Kulaťák. This large circular square in the residential Dejvice neighbourhood hosts a weekly market with local farmers selling vegetables, fruit, cheese, honey, meat, eggs, and prepared foods. It's primarily locals shopping for the week — not a tourist attraction. The atmosphere is warm and neighbourhood-y in the best way. The prepared food stalls do excellent breakfast, and the Vietnamese bánh mì stall is outstanding.",
    hours: "Saturday 8am–2pm year-round",
    tip: "Take the metro to Dejvická (green line A) — the market is a 2-minute walk. Arrive before 10am for the best produce and to get a seat at the food stalls. Much more authentic than any market in the city centre.",
    type: "Weekly Local Farmers' Market",
    blog: "https://www.adventurouskate.com/unusual-things-to-do-in-prague/",
    phone: "",
    website: "",
  },

  {
    id: 36,
    nbhd: "letna",
    name: "Spa Spa Private Wellness",
    cat: "cafe",
    emoji: "🛁",
    address: "Korunovační 39, Letná",
    lat: 50.1001,
    lng: 14.4072,
    search: "Spa Spa Letna Prague private sauna jacuzzi wellness",
    note: "One of Prague's best-kept secrets: private spa rentals where you can book your own personal sauna, jacuzzi, and relaxation space for two hours. Spa Spa in Letná is my recommendation — clean, beautifully designed, and genuinely relaxing. This is the perfect option for exhausted parents who need two hours of complete silence, or for couples who want a lovely private experience without a hotel price tag. Two hours for about 2,490 CZK (~$115). Absolute value.",
    hours: "Daily 10am–10pm (book in advance)",
    tip: "Book online at least a few days ahead — the private wellness rooms fill up quickly on weekends. Bring your own Prosecco if you want to make it special (they allow it). Some packages include it. A wonderful low-key Prague experience.",
    type: "Private Spa & Wellness",
    blog: "https://www.adventurouskate.com/unusual-things-to-do-in-prague/",
    phone: "+420 775 113 113",
    website: "https://spaspa.cz",
  },

  {
    id: 37,
    nbhd: "letna",
    name: "Sapa Vietnamese Market",
    cat: "market",
    emoji: "🥢",
    address: "Libušská 319, Praha 4 (outskirts)",
    lat: 50.0169,
    lng: 14.4556,
    search: "Sapa Market Prague Vietnamese Little Hanoi",
    note: "Prague's massive Vietnamese market on the city's outskirts — sometimes called 'Little Hanoi' — and one of the largest Vietnamese markets outside Vietnam. During communism, Czechoslovakia ran a guest worker program with fellow communist Vietnam, and many Vietnamese workers stayed and built this extraordinary community. Sapa is a melange of Vietnamese shops, restaurants, cafes, and wholesale businesses. Spending a few hours here eating your way through the food stalls is one of the most unusual and fascinating things to do in Prague. This is NOT a tourist attraction — treat it with respect.",
    hours: "Daily 7am–6pm (restaurants open later)",
    tip: "Ask before photographing anyone — this is a working community, not a tourist attraction. Look at what people are ordering at restaurants before you decide. The food is exceptional and extremely cheap. Take the 113 bus from Kačerov metro station.",
    type: "Vietnamese Community Market",
    blog: "https://www.adventurouskate.com/unusual-things-to-do-in-prague/",
    phone: "",
    website: "",
  },

  {
    id: 38,
    nbhd: "letna",
    name: "Beer Spa",
    cat: "landmark",
    emoji: "🛁",
    address: "Náměstí Republiky 8, Nové Město",
    lat: 50.0876,
    lng: 14.4316,
    search: "Beer Spa Prague beer bath Krusovice",
    note: "Czechs love beer so much you can literally bathe in it. The Beer Spa offers a chance to soak in brewer's yeast while drinking unlimited Krušovice beer directly from a tap at your tub, then relaxing on a bed of straw afterward. Is this medicinal? Probably not. Is it uniquely Czech and genuinely fun? Absolutely yes. I've done it and I recommend it. Just know that the more you drink, the more frequently you will need to exit the tub. Plan accordingly.",
    hours: "Daily 10am–10pm (book in advance)",
    tip: "Book the two-person tub with separate tubs option — sharing a beer bath with a stranger is more intimate than most visitors bargain for. One hour costs around 2,000–3,300 CZK per person. Bring a friend or come as a couple.",
    type: "Beer Bath & Spa Experience",
    blog: "https://www.adventurouskate.com/unusual-things-to-do-in-prague/",
    phone: "",
    website: "https://www.beerspa.com",
  },

  {
    id: 39,
    nbhd: "letna",
    name: "Taro Restaurant",
    cat: "food",
    emoji: "🥢",
    address: "Mánesova 58, Vinohrady",
    lat: 50.0756,
    lng: 14.4414,
    search: "Taro Restaurant Prague Asian tasting menu Vietnamese",
    note: "The perfect special occasion restaurant in Prague. Taro serves an eight-course tasting menu of Vietnamese-inspired Asian cuisine made with modern European techniques, all in a 20-seat restaurant surrounding an open kitchen. It's expensive for Prague (€83 for the tasting menu) but they also do a brilliant four-course business lunch for around €34. I've been several times and every course has made me stop and think about what I just ate. The inventive house lemonades alone are worth the trip.",
    hours: "Tue–Sat lunch noon–2pm; dinner 6:30pm–10pm",
    tip: "Reservations essential — only 20 seats. Best for couples or solo diners (the open kitchen seating isn't ideal for large groups). The business lunch is exceptional value. Check if they've moved locations — they relocated in 2024.",
    type: "Asian Tasting Menu Restaurant",
    blog: "https://www.adventurouskate.com/unusual-things-to-do-in-prague/",
    phone: "",
    website: "https://www.taro.cz",
  },

  {
    id: 40,
    nbhd: "letna",
    name: "The Italians Wine and Food Market",
    cat: "food",
    emoji: "🍕",
    address: "Mánesova 56, Vinohrady",
    lat: 50.0755,
    lng: 14.4413,
    search: "The Italians Wine Food Market Prague Italian restaurant",
    note: "The Eataly of Prague — and genuinely excellent. The Italians is a big Italian food market and restaurant where you can shop for imported Italian produce (the wine selection is extraordinary) and eat in the attached restaurant. I've had birthday dinners here and been back countless times. The pizza feels as close to good New York pizza as Prague gets. The salume platters are gorgeous. Charlie and I once ate our way through charcuterie, a giant pizza, three Italian desserts, Franciacorta, and Primitivo here. I regret nothing.",
    hours: "Restaurant daily noon–10:30pm; Market Mon–Sat 9am–9pm",
    tip: "Order the large pizza to share — it's enormous and excellent. The dessert case at the entrance is not to be skipped (the tiramisu is exceptional). Large enough for families and special occasions equally.",
    type: "Italian Food Market & Restaurant",
    blog: "https://www.adventurouskate.com/prague-restaurants/",
    phone: "+420 739 078 895",
    website: "https://www.theitalians.cz",
  },

  {
    id: 41,
    nbhd: "letna",
    name: "Čestr Restaurant",
    cat: "food",
    emoji: "🐄",
    address: "Mánesova 13, Vinohrady",
    lat: 50.0763,
    lng: 14.4403,
    search: "Cestr Prague Czech butcher restaurant grill Vinohrady",
    note: "Czech cuisine at its absolute best — a butcher shop restaurant with cow-head chandeliers and serious commitment to local Czech beef. Čestr serves steaks, burgers, tartare, and roasted meats with a dedication to quality that's genuinely impressive. The Czech Republic has excellent local cattle breeds and Čestr showcases them properly. The goulash with bread dumplings here is also the real thing — not the tourist-trap version. This is what Czech food actually tastes like when it's done properly.",
    hours: "Daily noon–11pm",
    tip: "The Czech beef tartare is excellent and a great way to start before a steak. The bread dumplings with goulash are properly made and satisfying without being heavy. Good for groups.",
    type: "Czech Butcher Restaurant",
    blog: "https://www.adventurouskate.com/prague-restaurants/",
    phone: "+420 222 727 851",
    website: "https://www.cestr.cz",
  },

  {
    id: 42,
    nbhd: "letna",
    name: "Krystal Bistro",
    cat: "food",
    emoji: "🧊",
    address: "náměstí Míru 10, Vinohrady",
    lat: 50.0741,
    lng: 14.4397,
    search: "Krystal Bistro Prague Czech food Vinohrady",
    note: "A beautiful Art Deco bistro on Náměstí Míru in Vinohrady that does Czech cuisine in a way that feels both traditional and modern. The space itself — all geometric tilework and vintage furnishings — is gorgeous. The food leans into classic Czech dishes done with care: svíčková, duck confit, grilled trout, roasted pork. This is the place I take visitors who want to try proper Czech food in a setting that doesn't feel like a tourist trap.",
    hours: "Daily 8am–11pm",
    tip: "Breakfast here is also excellent — good coffee and pastries. The svíčková (beef tenderloin with cream sauce and bread dumplings) is a Czech classic and Krystal does it well. Right on the main Vinohrady square.",
    type: "Modern Czech Bistro",
    blog: "https://www.adventurouskate.com/prague-restaurants/",
    phone: "+420 222 251 440",
    website: "https://krystalbistro.cz",
  },

  // ─── FURTHER AFIELD & DAY TRIPS ──────────────────────────────────────────

  {
    id: 43,
    nbhd: "old-town",
    name: "Únětice Brewery",
    cat: "cafe",
    emoji: "🏭",
    address: "Únětice 1, 252 62 Únětice (near Prague)",
    lat: 50.1512,
    lng: 14.3318,
    search: "Unetice Brewery Prague day trip Czech craft beer",
    note: "One of my favourite unusual Prague activities: getting out of the city and cycling to the Únětice Brewery, a small traditional Czech brewery in a village about 12km northwest of Prague. The beer — Únětické pivo — is extraordinary and the brewery has a beautiful beer garden where you drink it right at the source. Únětice is a picturesque Bohemian village and the whole outing feels like a genuine escape from tourist Prague. You can cycle there along the river and reward yourself with multiple beers.",
    hours: "Beer garden Tue–Sun 11am–8pm (summer); check for updated hours",
    tip: "Cycle there along the Vltava path (about 1.5 hours from central Prague) for the full experience. The 10° lager is their signature — extraordinarily smooth and refreshing. Combine with a walk around the village.",
    type: "Traditional Czech Brewery & Beer Garden",
    blog: "https://www.adventurouskate.com/unusual-things-to-do-in-prague/",
    phone: "",
    website: "https://www.unetickypivovar.cz",
  },

  {
    id: 44,
    nbhd: "old-town",
    name: "Kutná Hora Day Trip",
    cat: "landmark",
    emoji: "💀",
    address: "Kutná Hora (50 min by train from Praha hl.n.)",
    lat: 49.9484,
    lng: 15.2683,
    search: "Kutna Hora day trip Prague bone church Sedlec Ossuary",
    note: "My personal pick for the best day trip from Prague — and I recommend it to absolutely everyone. Kutná Hora is a beautiful medieval Bohemian town with a fascinating bone church (Sedlec Ossuary) where the bones of 40,000 people have been artistically arranged into chandeliers, coats of arms, and decorations. It sounds macabre; it is genuinely extraordinary. But beyond the ossuary, the town is lovely, underrated, and easy. The Cathedral of St Barbara is a Gothic masterpiece. Come here, not to Český Krumlov.",
    hours: "Trains every 30-60 min from Praha hl.n.; Ossuary Tue–Sun 9am–5pm",
    tip: "The ossuary requires timed tickets — book online. The Cathedral of St Barbara and the historic town centre are free to wander. The whole day trip costs under €30 including transport, admission, and a Czech lunch.",
    type: "Day Trip — Medieval Town & Bone Church",
    blog: "https://www.adventurouskate.com/day-trips-from-prague/",
    phone: "",
    website: "https://www.kostnice.cz",
  },

  {
    id: 45,
    nbhd: "old-town",
    name: "Prague Food Tour",
    cat: "food",
    emoji: "🧆",
    address: "Meets in Old Town (various starting points)",
    lat: 50.0878,
    lng: 14.4205,
    search: "Prague food tour Czech specialties neighborhoods",
    note: "My favourite thing to do in any city is take a food tour — and in Prague this is especially worthwhile because the food scene is so much more interesting than most visitors expect. The Taste of Prague food tours are the best I've found: small groups, knowledgeable guides, stops in local neighbourhoods (including my neighbourhood of Karlín!), and genuine Czech food rather than tourist interpretations. You'll try svíčková, trdelník, Czech charcuterie, craft beer, and things you'd never find on your own.",
    hours: "Various tour times; check Taste of Prague website",
    tip: "Book the full food tour rather than the shortened version — the extra stops and the neighbourhood exploration are the whole point. Come very hungry. The Taste of Prague website is also an excellent resource for finding restaurants on your own.",
    type: "Guided Food Tour",
    blog: "https://www.adventurouskate.com/unusual-things-to-do-in-prague/",
    phone: "",
    website: "https://www.tasteofprague.com",
  },

  {
    id: 46,
    nbhd: "mala-strana",
    name: "Prague Castle Walking Tour",
    cat: "landmark",
    emoji: "🚶‍♀️",
    address: "Meets in Old Town (various operators)",
    lat: 50.0875,
    lng: 14.4213,
    search: "Prague walking tour castle history",
    note: "Before I lived here, I took a walking tour of Prague on my first visit and it completely transformed how I understood the city. Prague is dense with history — from the medieval Jewish Quarter to the communist era to the Velvet Revolution — and a good walking tour brings all of it to life in a way that independent exploration can't. I especially recommend the alternative walking tour focused on the Prague of today, or the communism and nuclear bunker tour if you want to understand the country's 20th-century history.",
    hours: "Various operators run daily tours; check Prague Experience or Viator",
    tip: "The free walking tours are tip-based and generally excellent. The communism tour is my favourite for American visitors — the parallels to contemporary US politics are both fascinating and unsettling. Book the Jewish Quarter tour separately for a dedicated 2.5-hour deep dive.",
    type: "Guided Walking Tour",
    blog: "https://www.adventurouskate.com/prague-in-winter/",
    phone: "",
    website: "",
  },

  {
    id: 47,
    nbhd: "new-town",
    name: "Vyšehrad Fortress",
    cat: "landmark",
    emoji: "⛪",
    address: "V Pevnosti 159/5b, Vyšehrad",
    lat: 50.0640,
    lng: 14.4183,
    search: "Vysehrad Prague fortress castle cemetery",
    note: "The most overlooked major sight in Prague — and the one I send visitors to when they want to escape the crowds. Vyšehrad is an ancient hilltop fortress overlooking the Vltava, with a beautiful Neo-Gothic church, sweeping river views, and — my favourite part — the Vyšehrad Cemetery, where the greatest Czech artists, writers, composers, and national heroes are buried. Dvořák, Smetana, Mucha, and dozens more. The atmosphere is quietly magnificent and completely tourist-free compared to the castle.",
    hours: "Grounds daily 24 hours; Casemates daily 9:30am–6pm",
    tip: "Take the metro to Vyšehrad (red line C) — 5 minutes from Old Town. The cemetery is free and extraordinary — give yourself an hour to wander the graves. The river views from the fortress walls are among the best in Prague.",
    type: "Ancient Fortress, Church & Cemetery",
    blog: "https://www.adventurouskate.com/unusual-things-to-do-in-prague/",
    phone: "+420 241 410 348",
    website: "https://www.praha-vysehrad.cz",
  },

  {
    id: 48,
    nbhd: "new-town",
    name: "Prague Zoo",
    cat: "nature",
    emoji: "🦒",
    address: "U Trojského zámku 120/3, Troja",
    lat: 50.1173,
    lng: 14.4105,
    search: "Prague Zoo Troja Czech Republic animals",
    note: "I finally visited for the first time last year and immediately understood why Prague Zoo is considered one of the best in the world. The setting — along the Vltava north of the city — is spectacular, and the enclosures are large and well-designed. Elephants, giraffes, gorillas, penguins, and a somewhat terrifying chairlift over the main valley. My absolute favourites were the meerkats. It's a genuinely excellent day out, especially with kids, and the journey on the ferry from the city centre makes it feel like an adventure.",
    hours: "Daily 9am–7pm (summer); 9am–4pm (winter)",
    tip: "Take the scenic route: boat from Rašínovo nábřeží to Troja pier (runs Apr–Oct), then walk 10 minutes to the zoo. A full day activity — budget at least 3-4 hours. Adults around €12.",
    type: "World-Class City Zoo",
    blog: "https://www.adventurouskate.com/ak-monthly-recap-october-2023/",
    phone: "+420 296 112 230",
    website: "https://www.zoopraha.cz",
  },

  {
    id: 49,
    nbhd: "new-town",
    name: "Yamato",
    cat: "food",
    emoji: "🍣",
    address: "Mánesova 49, Vinohrady",
    lat: 50.0758,
    lng: 14.4408,
    search: "Yamato Prague sushi Japanese restaurant Vinohrady",
    note: "The best sushi in Prague — and people who know sushi agree. Yamato is a small, serious Japanese restaurant in Vinohrady run by a Japanese chef who takes the freshness and quality of his fish with absolute seriousness. The omakase menu is exceptional. When I first moved to Prague, I was worried about the quality of Japanese food here. Yamato completely eliminated that concern. It's not cheap by Prague standards but it's excellent.",
    hours: "Tue–Sun 6pm–10pm",
    tip: "The omakase menu is the way to go if budget allows. Reservations essential — the restaurant is small and popular. A special occasion restaurant that delivers on the occasion.",
    type: "Japanese Sushi Restaurant",
    blog: "https://www.adventurouskate.com/prague-restaurants/",
    phone: "+420 222 521 007",
    website: "https://www.yamato.cz",
  },

  {
    id: 50,
    nbhd: "karlin",
    name: "PRU58",
    cat: "food",
    emoji: "🍱",
    address: "Prvního pluku 58, Karlín",
    lat: 50.0939,
    lng: 14.4575,
    search: "PRU58 Prague restaurant Karlin Asian fusion",
    note: "A relatively new addition to the Karlín restaurant scene and quickly one of my favourites. PRU58 is an Asian fusion restaurant that takes its flavours seriously — there's nothing timid about the cooking here. The menu changes regularly and the chefs are genuinely creative. It's in a cool, slightly industrial Karlín space and the whole experience feels right for the neighbourhood. Great addition to the Karlín food scene that I tell everyone about.",
    hours: "Tue–Sat 6pm–10:30pm",
    tip: "Reservations recommended for weekends. The small plates format works well for exploration — order widely. Combine with a drink at Kasárna Karlín before or after.",
    type: "Asian Fusion Restaurant",
    blog: "https://www.adventurouskate.com/prague-restaurants/",
    phone: "",
    website: "",
  },

  {
    id: 51,
    nbhd: "old-town",
    name: "Vltava River Bike Ride",
    cat: "nature",
    emoji: "🚴",
    address: "Start anywhere along the eastern Vltava riverbank",
    lat: 50.0832,
    lng: 14.4285,
    search: "Prague bike ride Vltava river cycling path",
    note: "Czechs are incredibly active and outdoorsy — a typical Czech weekend involves biking, hiking, or skiing, followed by a pub. One of my favourite ways to feel Czech is to rent a Rekola bike and follow the car-free path along the eastern Vltava River. Quickly the city gives way to forests, mountains, and tiny riverside pubs. You'll pass kayakers on the river, cute cottages, and stretches of pure tranquillity. It's extraordinary that you can go from the centre of a major European capital to the middle of the forest in 30 minutes.",
    hours: "Year-round (best Apr–Oct); Rekola bikes available daily",
    tip: "Download the Rekola app to find and unlock bikes across the city. Head north along the eastern riverbank. The tiny riverside pubs that appear after about 45 minutes are the perfect turnaround point — stop for a beer.",
    type: "Cycling Route along the River",
    blog: "https://www.adventurouskate.com/unusual-things-to-do-in-prague/",
    phone: "",
    website: "https://www.rekola.cz",
  },

  {
    id: 52,
    nbhd: "mala-strana",
    name: "Vietnamese Egg Coffee",
    cat: "cafe",
    emoji: "☕",
    address: "Cà Phê Cổ (search current address in Vinohrady/Žižkov)",
    lat: 50.0812,
    lng: 14.4432,
    search: "Vietnamese egg coffee Prague Ca Phe Co",
    note: "One of the more unusual food experiences I've had in Prague: Vietnamese egg coffee. The drink originated in Hanoi in the 1940s when milk was scarce — a barista started whipping egg yolks with sugar and condensed milk to create a frothy, custard-like topping for strong Vietnamese drip coffee. The result is extraordinary — rich, creamy, sweet, and intensely caffeinated. Prague's large Vietnamese community means you can find this here, and it's absolutely worth seeking out.",
    hours: "Check Cà Phê Cổ or local Vietnamese cafes for current hours",
    tip: "Cà Phê Cổ is the place most often recommended for egg coffee in Prague — check their current location as they've moved. Drink it warm rather than cold to get the full custard-foam effect. One of Prague's most unusual food souvenirs.",
    type: "Vietnamese Specialty Café",
    blog: "https://www.adventurouskate.com/unusual-things-to-do-in-prague/",
    phone: "",
    website: "",
  },

  {
    id: 53,
    nbhd: "vinohrady",
    name: "Coda Restaurant",
    cat: "food",
    emoji: "🎵",
    address: "Mánesova 31, Vinohrady",
    lat: 50.0761,
    lng: 14.4393,
    search: "Coda Restaurant Prague Vinohrady Czech modern",
    note: "A beautifully designed restaurant in Vinohrady that does Czech cuisine with a modern twist — the kind of place that makes you see traditional ingredients in a completely new way. The svíčková here is exceptional; the Czech game dishes are extraordinary in season. The interior is gorgeous — all warm wood and soft lighting — and the wine list is thoughtfully Czech-focused. This is the elevated Czech food experience that most visitors don't realise exists.",
    hours: "Mon–Sat noon–3pm and 6pm–10:30pm",
    tip: "Try the svíčková if you want to understand the Czech national dish at its finest. The tasting menu in the evening is excellent for a special occasion. Book ahead.",
    type: "Modern Czech Restaurant",
    blog: "https://www.adventurouskate.com/prague-restaurants/",
    phone: "+420 773 400 200",
    website: "https://www.codarestaurant.cz",
  },

  {
    id: 54,
    nbhd: "old-town",
    name: "Větrník Pastry at the Hidden Garden",
    cat: "food",
    emoji: "🍮",
    address: "Search for Café Savoy or U Mloka for Větrník pastry",
    lat: 50.0818,
    lng: 14.4053,
    search: "Vetrnik pastry Prague eclair Czech cream puff hidden garden",
    note: "A větrník is the Czech answer to the éclair — a choux pastry filled with cream and topped with a caramelised sugar crust — and Prague makes some of the best in the world. My favourite version comes from a café with a hidden garden (the gardens of small Prague cafes and restaurants are some of the most enchanting things about the city). Finding the right one is part of the experience. Ask a local — everyone has an opinion about the best větrník in their neighbourhood.",
    hours: "Varies by location; most cafes open from 9am",
    tip: "Café Savoy in Malá Strana is one of the most beautiful cafes in Prague and makes an excellent větrník. Alternatively, ask at any neighbourhood bakery-café — the Czech pastry tradition is extraordinary and every neighbourhood has its own version.",
    type: "Czech Pastry & Café Experience",
    blog: "https://www.adventurouskate.com/unusual-things-to-do-in-prague/",
    phone: "",
    website: "",
  },

  {
    id: 55,
    nbhd: "mala-strana",
    name: "Café Savoy",
    cat: "cafe",
    emoji: "☕",
    address: "Vítězná 5, Malá Strana",
    lat: 50.0826,
    lng: 14.4063,
    search: "Cafe Savoy Prague Neo-Renaissance cafe breakfast",
    note: "The most beautiful café in Prague — a stunning Neo-Renaissance interior with high ceilings, chandeliers, and graceful proportions in a space that dates to 1893. Café Savoy does breakfast, brunch, and afternoon pastries at a level that matches the setting. Their větrník is excellent, their eggs benedict are superb, and the French toast is one of the best I've had in Europe. It's on the expensive side by Prague standards but the experience of eating in this room justifies every Crown. A perfect rainy day refuge.",
    hours: "Daily 8am–10:30pm",
    tip: "Brunch on weekends can mean a queue — arrive right at opening (8am) to walk straight in. The Eggs Benedict and the house pastries are the highlights. Even if you just come for coffee and a větrník, it's worth it for the interior alone.",
    type: "Historic Belle Époque Café",
    blog: "https://www.adventurouskate.com/unusual-things-to-do-in-prague/",
    phone: "+420 257 311 562",
    website: "https://www.ambi.cz/savoy",
  },

];
