// A Perfect Day — Ludara / New Orleans
// data.js — 50 curated places
//
// Demo guide for A Perfect Day platform.
// Sources: Times-Picayune / Ian McNulty, Gambit, The Infatuation, Resy,
//          Where Y'at, Out All Day NOLA, New Orleans Magazine, AFAR,
//          Lonely Planet, Atlas Obscura, official venue websites.
//
// All hours, addresses and GPS coordinates verified April 2026.
//
// Neighbourhoods:
//   french-quarter / marigny-bywater / treme
//   garden-district / warehouse / mid-city / uptown

const PLACES = [

  // ─── FRENCH QUARTER ──────────────────────────────────────────────────────

  {
    id: 1,
    nbhd: "french-quarter",
    name: "Jackson Square & St. Louis Cathedral",
    cat: "landmark",
    emoji: "⛪",
    address: "Jackson Square, 751 Decatur Street, French Quarter",
    lat: 29.9575,
    lng: -90.0630,
    search: "Jackson Square St Louis Cathedral New Orleans French Quarter",
    note: "The heart of old New Orleans. The triple-spired St. Louis Cathedral — the oldest continuously active Catholic cathedral in the United States, built on this site since 1718 — overlooks the formal gardens and the equestrian statue of Andrew Jackson. The flanking Cabildo (where the Louisiana Purchase was signed in 1803) and the Presbytère are both outstanding museums. The iron fence is lined daily with artists, fortune-tellers and street performers.",
    hours: "Jackson Square: daily 8am–7pm. Cathedral: daily 9:30am–4pm (free)",
    tip: "The view of the Cathedral from across the square at dawn, before the crowds arrive, is one of the finest city vistas in the United States.",
    type: "Historic Square & Cathedral",
    blog: "",
    phone: "+1 504-525-9585",
    website: "https://www.stlouiscathedral.org",
  },

  {
    id: 2,
    nbhd: "french-quarter",
    name: "Café du Monde",
    cat: "cafe",
    emoji: "☕",
    address: "800 Decatur Street, French Quarter",
    lat: 29.9560,
    lng: -90.0617,
    search: "Cafe du Monde New Orleans beignets chicory coffee French Market",
    note: "Open since 1862 and unchanged. Café du Monde serves exactly two things: beignets dusted with powdered sugar and café au lait made with Louisiana chicory coffee. The open-air terrace on Decatur Street, with its green-and-white striped awning, is the most recognisable café scene in the American South. Every local has strong opinions about the powdered sugar cloud that inevitably covers your clothes.",
    hours: "Sun–Thu 7:15am–11pm; Fri–Sat 7:15am–midnight",
    tip: "Come early morning or late at night to avoid peak queues. Ask for extra napkins. The powdered sugar drifts.",
    type: "Historic Beignet Café",
    blog: "",
    phone: "+1 504-525-4544",
    website: "https://www.cafedumonde.com",
  },

  {
    id: 3,
    nbhd: "french-quarter",
    name: "St. Louis Cemetery No. 1",
    cat: "landmark",
    emoji: "⚰️",
    address: "425 Basin Street, French Quarter",
    lat: 29.9593,
    lng: -90.0714,
    search: "Saint Louis Cemetery 1 New Orleans above ground tombs narrow alleys",
    note: "The oldest extant cemetery in New Orleans, established in 1789. Mark Twain called the city's above-ground graveyards 'cities of the dead' — and this is the most atmospheric of all. Over 600 elaborate family tombs line maze-like alleys: the supposed resting place of Voodoo Queen Marie Laveau, Homer Plessy (plaintiff in Plessy v. Ferguson), and the tomb Nicolas Cage had built for himself. The architecture of death here is unlike anything in North America.",
    hours: "Mon–Sat 9am–3pm; Sun 9am–noon. Guided tour required (tours by Cemetery Tours New Orleans)",
    tip: "Independent entry is not permitted — you must join a licensed guided tour. Book online in advance. The tour is genuinely excellent.",
    type: "Historic Cemetery",
    blog: "",
    phone: "+1 504-596-3050",
    website: "",
  },

  {
    id: 4,
    nbhd: "french-quarter",
    name: "Steamboat Natchez",
    cat: "landmark",
    emoji: "🚢",
    address: "400 Toulouse Street at the River, French Quarter",
    lat: 29.9568,
    lng: -90.0592,
    search: "Steamboat Natchez New Orleans Mississippi River jazz cruise",
    note: "The last authentic steam-powered paddlewheel steamboat working the Mississippi. Three daily cruises — daytime harbour, evening dinner jazz, and Sunday brunch — take passengers along the river while a live jazz band plays and the steam calliope announces departure. The self-guided steam engine room tour is a highlight. The views of the New Orleans skyline from the water are unlike any view from the shore.",
    hours: "Three daily cruises; ticket office open daily 9am–7pm",
    tip: "The daytime harbour cruise is the best value. Book the upper deck for the best views of the city.",
    type: "Historic Steamboat Cruise",
    blog: "",
    phone: "+1 504-569-1401",
    website: "https://www.steamboatnatchez.com",
  },

  {
    id: 5,
    nbhd: "french-quarter",
    name: "Preservation Hall",
    cat: "landmark",
    emoji: "🎷",
    address: "726 St. Peter Street, French Quarter",
    lat: 29.9576,
    lng: -90.0641,
    search: "Preservation Hall New Orleans interior musicians jazz stage benches",
    note: "One of the most important music rooms in the world. Founded in 1961 to preserve traditional New Orleans jazz, the hall is deliberately spare — bare walls, worn benches, standing room — so that nothing distracts from the music. The house band plays multiple sets nightly. The intimacy of the room, the proximity to the musicians, and the weight of the history make this an experience unlike any other jazz venue.",
    hours: "Doors open 5pm; sets nightly at 8pm, 9pm, 10pm",
    tip: "General admission ($20) is standing room. Bench seating is $40. Queue 30 minutes before the set you want for a good spot.",
    type: "Historic Jazz Hall",
    blog: "",
    phone: "+1 504-522-2841",
    website: "https://www.preservationhall.com",
  },

  {
    id: 6,
    nbhd: "french-quarter",
    name: "GW Fins",
    cat: "food",
    emoji: "🐟",
    address: "808 Bienville Street, French Quarter",
    lat: 29.9556,
    lng: -90.0688,
    direct_image: "https://popmenucloud.com/cdn-cgi/image/width%3D600%2Cheight%3D600%2Cfit%3Dscale-down%2Cformat%3Dauto%2Cquality%3D60/jzsvdhre/3eb53cf1-a564-4547-809c-6f917bc50c1f.jpg",
    search: "GW Fins seafood restaurant New Orleans French Quarter",
    note: "New Orleans' premier fine dining seafood restaurant, owned and operated by Gary Wollerman since 2001. The menu changes nightly based on the catch — only the most pristine fish from local Gulf waters and global sources, treated with maximum respect and minimal fuss. Executive Chef Michael Nelson pioneered dry-aged fish and brought seacuterie to the mainstream. Named to OpenTable's Top 100 Restaurants in 2025. Consistently one of the city's most celebrated dining experiences.",
    hours: "Daily 5pm–9:30pm; Fri–Sat until 10pm",
    tip: "The menu changes every night based on the catch. Ask the server what just came in. Book well ahead for weekends.",
    type: "Fine Dining Seafood",
    blog: "",
    phone: "+1 504-581-3467",
    website: "https://www.gwfins.com",
  },

  {
    id: 7,
    nbhd: "french-quarter",
    name: "Bar Tonique",
    cat: "pub",
    emoji: "🍸",
    address: "820 N. Rampart Street, French Quarter",
    lat: 29.9621,
    lng: -90.0697,
    search: "Bar Tonique New Orleans cocktail bar N Rampart Street",
    note: "Three blocks from Bourbon Street but a world apart. Bar Tonique is the city's standard-bearer for serious cocktails — the bartenders take their craft seriously, the pours are generous, and there's a rotating $6 daily cocktail. The U-shaped bar invites conversation. The crowd is an excellent mix of locals and visitors who know to avoid the chaos a few blocks west.",
    hours: "Daily 4pm–2am",
    tip: "Ask what the daily special is — it is always well-made and excellent value. The mai tai is one of the city's best.",
    type: "Craft Cocktail Bar",
    blog: "",
    phone: "+1 504-324-6045",
    website: "https://www.bartonique.com",
  },

  {
    id: 8,
    nbhd: "french-quarter",
    name: "Carousel Bar & Lounge",
    cat: "pub",
    emoji: "🎠",
    address: "214 Royal Street, Hotel Monteleone, French Quarter",
    lat: 29.9577,
    lng: -90.0655,
    search: "Carousel Bar Hotel Monteleone New Orleans Royal Street revolving",
    note: "The bar revolves — slowly, one full rotation every 15 minutes — and has been doing so since 1949 inside the Hotel Monteleone, which hosted William Faulkner, Truman Capote, Tennessee Williams and Ernest Hemingway. Gambit readers consistently vote it the city's best bar. The Vieux Carré cocktail was invented here in the 1930s by bartender Walter Bergeron. Recognised as a Tales of the Cocktail Spirited Awards Regional Top 10 Honoree for Best U.S. Hotel Bar in both 2025 and 2026. Arrive early in the evening for a seat on the carousel itself.",
    hours: "Sun–Thu 11am–midnight; Fri–Sat 11am–1am",
    tip: "Order a Vieux Carré — rye, cognac, sweet vermouth, Bénédictine, bitters. It was invented at this bar and it is still the best version in the city.",
    type: "Historic Revolving Bar",
    blog: "",
    phone: "+1 504-523-3341",
    website: "https://www.hotelmonteleone.com/entertainment/carousel-bar",
  },

  {
    id: 9,
    nbhd: "french-quarter",
    name: "Royal Street",
    cat: "market",
    emoji: "🖼️",
    address: "Royal Street, French Quarter",
    lat: 29.9578,
    lng: -90.0663,
    search: "Royal Street New Orleans antiques galleries shopping French Quarter",
    note: "The Quarter's most elegant street and the best address in the city for antiques and art. The six blocks between St. Ann and Canal Street are lined with estate silver, antique maps, 19th-century Louisiana paintings, rare books, fine jewellery and handmade crafts. M.S. Rau Antiques — recently voted the city's best antique dealer by New Orleans Magazine readers — is the anchor. Street musicians play at the Royal Street 'living room' intersection on weekend afternoons.",
    hours: "Most galleries Mon–Sat 10am–5pm; some open Sunday",
    tip: "M.S. Rau (630 Royal) has the most extraordinary collection — walk through even if you're not buying. The back room is a museum.",
    type: "Antiques & Art Street",
    blog: "",
    phone: "",
    website: "",
  },

  {
    id: 10,
    nbhd: "french-quarter",
    name: "Jewel of the South",
    cat: "food",
    emoji: "🦞",
    address: "1026 St. Louis Street, French Quarter",
    lat: 29.9623,
    lng: -90.0678,
    search: "Jewel of the South restaurant cocktail bar New Orleans French Quarter",
    note: "Winner of the 2024 James Beard Outstanding Bar award — the highest bar honour in the United States. Also voted Best Bar in South USA three years running (2023–2025) and ranked on the World's 50 Best Bars and North America's 50 Best Bars. Bar maestro Chris Hannah — among the most celebrated cocktail minds in the American South — runs this intimate 1830s Creole cottage where the drinks programme matches world-class standards. The menu leans into British technique with Louisiana ingredients: caviar, wagyu tongue, duck neck sausage, and off-menu classics alongside Hannah's signature creations. The courtyard is one of the most beautiful drinking spots in the city. Ian McNulty rates it among the city's essential restaurants.",
    hours: "Dinner Tue–Sun from 5pm; Fri–Sat lunch 11:30am–5pm",
    tip: "The bar seats are first-come, first-served — a great option on busy nights. The Wednesday night 'Casual Caviar' happy hour runs 5–7pm.",
    type: "Restaurant & Cocktail Bar",
    blog: "",
    phone: "+1 504-265-8816",
    website: "https://www.jewelnola.com",
  },

  // ─── MARIGNY & BYWATER ───────────────────────────────────────────────────

  {
    id: 11,
    nbhd: "marigny-bywater",
    name: "Frenchmen Street",
    cat: "pub",
    emoji: "🎶",
    address: "Frenchmen Street, Faubourg Marigny",
    lat: 29.9614,
    lng: -90.0570,
    search: "Frenchmen Street New Orleans live music Marigny jazz bars",
    note: "Where locals go for live music instead of Bourbon Street. Two blocks through the Marigny that come alive after dark with free live jazz spilling from open doorways at The Spotted Cat, Blue Nile, Café Negril and Maison. On most nights three bands play simultaneously within earshot of each other. The outdoor Frenchmen Art Bazaar runs Wednesday through Sunday evenings alongside the music — paintings, jewellery and handmade crafts from local artists.",
    hours: "Music starts around 9pm; peaks midnight–2am",
    tip: "No cover at most venues — walk in, listen, tip the band generously and move on. The art market sets up on the pavement from around 8pm.",
    type: "Live Music Street",
    blog: "",
    phone: "",
    website: "",
  },

  {
    id: 12,
    nbhd: "marigny-bywater",
    name: "The Spotted Cat Music Club",
    cat: "pub",
    emoji: "🐱",
    address: "623 Frenchmen Street, Marigny",
    lat: 29.9614,
    lng: -90.0574,
    search: "Spotted Cat Music Club Frenchmen Street New Orleans jazz live",
    note: "The most consistently excellent live music venue on Frenchmen Street. No cover, no attitude — a narrow, dimly-lit room where some of the city's finest jazz musicians play swing, bebop and traditional New Orleans jazz from 4pm every day. The stage is so close you can watch the pianist's hands. One of the best free entertainment experiences in any American city.",
    hours: "Daily 4pm–2am; music from 4pm",
    tip: "Drinks are cash only. Come on a weekday afternoon to hear great jazz in a relaxed room before the crowds arrive.",
    type: "Jazz Music Club",
    blog: "",
    phone: "+1 504-943-3887",
    website: "https://www.spottedcatmusicclub.com",
  },

  {
    id: 13,
    nbhd: "marigny-bywater",
    name: "Bacchanal Wine",
    cat: "pub",
    emoji: "🍷",
    address: "600 Poland Avenue, Bywater",
    lat: 29.9598,
    lng: -90.0332,
    search: "Bacchanal Wine Bywater New Orleans Poland Avenue wine music garden",
    note: "What started as a neighbourhood wine shop evolved into one of the most beloved gathering places in the city. Pick a bottle of natural wine from the shop, head to the sprawling backyard, order cheese and Mediterranean small plates, and settle in for live jazz that starts every evening. There is also a semi-secret cocktail bar upstairs. Outdoor, communal, festive — this is New Orleans at its most convivial. NOLA's original pop-up restaurant concept was born here after Katrina.",
    hours: "Mon–Thu 4–10pm; Fri–Sun noon–11pm. Live music nightly",
    tip: "Wednesday evenings have free wine tastings. Come on a weeknight to actually find a seat in the backyard.",
    type: "Wine Bar & Live Music Garden",
    blog: "",
    phone: "+1 504-948-9111",
    website: "https://www.bacchanalwine.com",
  },

  {
    id: 14,
    nbhd: "marigny-bywater",
    name: "N7",
    cat: "food",
    emoji: "🇫🇷",
    address: "1117 Montegut Street, Bywater",
    lat: 29.9582,
    lng: -90.0378,
    search: "N7 Bywater New Orleans hidden garden patio string lights French bistro",
    note: "Notoriously difficult to find — look for a red stencil 'N7' on a wooden fence gate on a quiet Bywater side street. Inside is a Christmas-light-strung garden patio and one of the most quietly extraordinary restaurants in the city. Chef Yuki Yamaguchi blends French bistro with Japanese sensibility: steak au poivre, pork katsu, bouillabaisse, canned seafood and natural wines from small European producers. Named Bon Appétit Top 10 Best New Restaurants in America. No phone — reservations via Resy.",
    hours: "Mon–Sun 5:30pm–9pm; Brunch Fri–Sun 11:30am–2:30pm",
    tip: "Reserve ahead. The garden is the place to sit. The olive oil cake with mascarpone for dessert is not optional.",
    type: "French-Japanese Wine Bar & Restaurant",
    blog: "",
    phone: "",
    website: "https://www.n7nola.com",
  },

  {
    id: 15,
    nbhd: "marigny-bywater",
    name: "Hotel Peter & Paul / Elysian Bar",
    cat: "landmark",
    emoji: "⛪",
    address: "2317 Burgundy Street, Marigny",
    lat: 29.9682,
    lng: -90.0568,
    search: "Hotel Peter Paul Elysian Bar New Orleans Marigny historic church",
    note: "Four 19th-century buildings — a church, schoolhouse, rectory and convent — converted into one of the most beautiful boutique hotels in the American South. The Elysian Bar is accessible without a room: saffron rugs, a hand-painted mural of lemon trees, and a drinks menu built around French, Spanish and Italian vermouths and amaros. The warm pink glow of the room is unlike anywhere else in the city. One of the best new hotel bars in the United States.",
    hours: "Bar: daily 5pm–midnight",
    tip: "Walk through the main former church space even if you are only visiting the bar. The stained glass restoration is extraordinary.",
    type: "Boutique Hotel & Bar",
    blog: "",
    phone: "+1 504-356-5400",
    website: "https://www.hotelpeterandpaul.com",
  },

  {
    id: 16,
    nbhd: "marigny-bywater",
    name: "Crescent Park",
    cat: "nature",
    emoji: "🌊",
    address: "700 N. Peters Street (Elysian Fields access), Marigny",
    lat: 29.9633,
    lng: -90.0518,
    search: "Crescent Park New Orleans arch bridge Marigny riverfront Mississippi",
    note: "A long, narrow riverfront park running along the Mississippi levee through the Marigny and Bywater. The sweeping views of the river and the skyline are the best in New Orleans — better than anything from the French Quarter riverfront. A dramatic arched bridge at the Marigny entrance spans the flood wall. Locals come here to run, walk, read and watch the barges pass. Essentially unknown to most visitors.",
    hours: "Daily 6am–9pm",
    tip: "Enter via the arched bridge off Elysian Fields Avenue at the river. The view upstream toward the French Quarter at golden hour is extraordinary.",
    type: "Riverfront Park",
    blog: "",
    phone: "",
    website: "",
  },

  {
    id: 17,
    nbhd: "marigny-bywater",
    name: "Satsuma Cafe",
    cat: "cafe",
    emoji: "🥑",
    address: "3218 Dauphine Street, Bywater",
    lat: 29.9593,
    lng: -90.0481,
    search: "Satsuma Cafe New Orleans Bywater breakfast brunch coffee",
    note: "The Bywater's essential daytime spot. A small neighbourhood café serving fresh juices, avocado toast, salads and a reliably excellent bacon-egg-and-cheese, with a lovely garden patio that is the most pleasant place to start a morning in this part of the city. Locals pack it on weekends — arrive early or expect a short wait.",
    hours: "Daily 7am–5pm",
    tip: "The ginger lemonade is the thing to order if the previous night went long. The garden patio fills up fast on weekends.",
    type: "Neighbourhood Café",
    blog: "",
    phone: "+1 504-304-5962",
    website: "https://www.satsumacafe.com",
  },

  // ─── TREME ───────────────────────────────────────────────────────────────

  {
    id: 18,
    nbhd: "treme",
    name: "Louis Armstrong Park & Congo Square",
    cat: "landmark",
    emoji: "🎺",
    address: "701 N. Rampart Street, Tremé",
    lat: 29.9627,
    lng: -90.0711,
    search: "Louis Armstrong Park New Orleans entrance arch Rampart Street Treme",
    note: "One of the most historically significant sites in American music. Congo Square, within Louis Armstrong Park, was the only place in antebellum New Orleans where enslaved Africans were permitted to gather on Sundays — and where African musical traditions, the roots of jazz, blues and rock and roll, were preserved. The surrounding Tremé is the oldest Black neighbourhood in the United States. Beautiful park with lagoons, fountains and bronze sculptures of Armstrong himself.",
    hours: "Daily 6am–10pm. Free entry",
    tip: "Read the Congo Square historical plaques carefully — the story they tell is the foundation of American popular music.",
    type: "Historic Park & Cultural Site",
    blog: "",
    phone: "",
    website: "",
  },

  {
    id: 19,
    nbhd: "treme",
    name: "Backstreet Cultural Museum",
    cat: "landmark",
    emoji: "🎭",
    address: "1531 St. Philip Street, Tremé",
    lat: 29.9658,
    lng: -90.0702,
    search: "Backstreet Cultural Museum New Orleans Treme Mardi Gras Indian jazz funeral",
    note: "The essential museum for understanding the African American cultural traditions that make New Orleans unique. Founded by Sylvester Francis, the museum documents Mardi Gras Indian suits (among the most extraordinary examples of handmade art in America), second-line parades, jazz funerals and Social Aid and Pleasure Clubs. The collection of Mardi Gras Indian suits — each sewn by hand over thousands of hours — is staggering in its craftsmanship and beauty.",
    hours: "Tue–Sat 10am–4pm",
    tip: "If you can visit during Mardi Gras season (January–March), ask about Super Sunday, when the Mardi Gras Indians parade in full suits through the neighbourhood.",
    type: "Cultural Museum",
    blog: "",
    phone: "+1 504-522-4806",
    website: "https://www.backstreetmuseum.org",
  },

  {
    id: 20,
    nbhd: "treme",
    name: "Kermit's Tremé Mother-in-Law Lounge",
    cat: "pub",
    emoji: "🎷",
    address: "1500 N. Claiborne Avenue, Tremé",
    lat: 29.9693,
    lng: -90.0763,
    search: "Kermit's Treme Mother in Law Lounge New Orleans jazz Thursday",
    note: "Trumpeter Kermit Ruffins took over the legendary Mother-in-Law Lounge — once owned by New Orleans R&B singer Ernie K-Doe — and turned it into a Thursday-night institution. Kermit and his Barbecue Swingers play to a mix of deep locals and music pilgrims. He often barbecues outside on the grill before the music starts. This is as close to authentic neighbourhood New Orleans as a visitor can get.",
    hours: "Thu–Sat evenings; check Facebook page for schedule",
    tip: "Thursday nights are the main event. Come before the music starts (around 9pm) to find a spot and grab a plate of barbecue.",
    type: "Neighbourhood Music Lounge",
    blog: "",
    phone: "+1 504-975-3955",
    website: "https://www.facebook.com/KermitsMotherInLawLounge",
  },

  // ─── GARDEN DISTRICT ─────────────────────────────────────────────────────

  {
    id: 21,
    nbhd: "garden-district",
    name: "St. Charles Streetcar & Garden District Mansions",
    cat: "landmark",
    emoji: "🚋",
    address: "St. Charles Avenue at Canal Street (boarding point)",
    lat: 29.9500,
    lng: -90.0696,
    search: "St Charles Streetcar New Orleans Garden District mansions historic",
    note: "The oldest continuously operating streetcar line in the world, running since 1835. Board at Canal Street for $1.25 and ride through the Garden District — one of the finest residential streets in America: Greek Revival, Italianate and Victorian mansions behind cast-iron fences and live oaks draped in Spanish moss. The houses of Anne Rice, Sandra Bullock and John Goodman line the route. Alight at Washington Avenue and walk three blocks to Commander's Palace and Lafayette Cemetery.",
    hours: "Runs 24 hours daily; every 6–7 minutes in daytime, every 20–30 minutes at night",
    tip: "Exact change ($1.25) or the Le Pass app required. Ride to the end of the line and back for the best full tour of Uptown.",
    type: "Historic Streetcar",
    blog: "",
    phone: "",
    website: "https://www.norta.com",
  },

  {
    id: 22,
    nbhd: "garden-district",
    name: "Commander's Palace",
    cat: "food",
    emoji: "🍽️",
    address: "1403 Washington Avenue, Garden District",
    lat: 29.9294,
    lng: -90.0893,
    search: "Commanders Palace New Orleans turquoise Victorian restaurant exterior Washington Avenue",
    note: "The anchor of New Orleans fine dining since 1893. The turquoise Victorian mansion launched the careers of Paul Prudhomme and Emeril Lagasse and has won seven James Beard Foundation Awards — the most of any New Orleans restaurant. Holds the Wine Spectator Grand Award every year since 2012, one of only a handful of restaurants in the world to do so continuously. The current kitchen team continues to define the standard for Creole cuisine. The Saturday jazz brunch is a New Orleans institution — three courses, live jazz, 25-cent martinis (limit three per person). The turtle soup and bread pudding soufflé are the dishes that have been on this menu for decades for good reason.",
    hours: "Lunch Mon–Fri 11:30am–1:30pm; Dinner nightly from 6pm; Brunch Sat–Sun 10am–1:30pm",
    tip: "The 25-cent martini lunch special runs on weekdays. Book brunch well ahead — it fills up weeks in advance on weekends.",
    type: "Creole Fine Dining",
    blog: "",
    phone: "+1 504-899-8221",
    website: "https://www.commanderspalace.com",
  },

  {
    id: 23,
    nbhd: "garden-district",
    name: "Lafayette Cemetery No. 1",
    cat: "landmark",
    emoji: "🌿",
    address: "1427 Washington Avenue, Garden District",
    lat: 29.9299,
    lng: -90.0908,
    search: "Lafayette Cemetery Garden District New Orleans above ground tombs",
    note: "Established in 1833, this is the most beautiful and accessible of New Orleans' famous above-ground cemeteries. Narrow brick lanes thread between whitewashed family tombs, live oaks drape the paths in shade, and the whole place has an atmosphere of calm grandeur rather than grim morbidity. Anne Rice set scenes from Interview with the Vampire here. Directly opposite Commander's Palace — the two make a natural pairing.",
    hours: "Mon–Fri 7am–3:30pm; Sat 7am–noon",
    tip: "Free entry. No guide required (unlike St. Louis No. 1). Early morning is the best time — quiet, good light, and no crowds.",
    type: "Historic Cemetery",
    blog: "",
    phone: "",
    website: "",
  },

  {
    id: 24,
    nbhd: "garden-district",
    name: "Coquette",
    cat: "food",
    emoji: "🦞",
    address: "2800 Magazine Street, Garden District",
    lat: 29.9338,
    lng: -90.0952,
    search: "Coquette restaurant Magazine Street New Orleans Garden District",
    note: "Ian McNulty of the Times-Picayune has championed Coquette for 17 years as the most consistently excellent restaurant on Magazine Street. Chef Michael Stoltzfus has earned six James Beard Award semifinalist nominations and one nominee spot for Best Chef: South — the most of any active New Orleans chef. The kitchen is always different and never predictable — wide-ranging imagination, deft technique, exuberantly fresh ingredients. The long bar up front is prime territory for a solo meal or a drop-in visit for a snack and a cocktail. A New Orleans institution.",
    hours: "Dinner Tue–Sat from 5:30pm; Lunch Thu–Fri 11:30am–2pm",
    tip: "Bar seats are first-come, first-served. Order whatever sounds most unusual — it is always the best thing on the menu.",
    type: "Contemporary Creole Restaurant",
    blog: "",
    phone: "+1 504-265-0421",
    website: "https://www.coquettenola.com",
  },

  {
    id: 25,
    nbhd: "garden-district",
    name: "Magazine Street",
    cat: "market",
    emoji: "🛍️",
    address: "Magazine Street, Garden District to Uptown",
    lat: 29.9290,
    lng: -90.0960,
    search: "Magazine Street New Orleans shopping boutiques antiques Garden District",
    note: "Six miles of independent boutiques, antique shops, galleries, cafés and restaurants running from the Lower Garden District to Uptown. The best stretch is from Washington Avenue to Napoleon Avenue. Look for: Home Malone for locally-made goods, Aux Belles Choses for French linens and soaps, Magpie for vintage clothing and jewellery, Alice and Amelia for New Orleans-style homewares. The street changes character every few blocks — more upscale toward Uptown, quirkier in the Lower Garden District.",
    hours: "Most shops Mon–Sat 10am–6pm",
    tip: "Hop on the St. Charles streetcar rather than walking the full length. Alight wherever catches your eye.",
    type: "Independent Shopping Street",
    blog: "",
    phone: "",
    website: "",
  },

  {
    id: 26,
    nbhd: "garden-district",
    name: "Hotel Saint Vincent",
    cat: "pub",
    emoji: "🏊",
    address: "1507 Magazine Street, Lower Garden District",
    lat: 29.9358,
    lng: -90.0768,
    search: "Hotel Saint Vincent New Orleans Magazine Street bar pool Lower Garden District",
    note: "A former 1861 orphanage converted into one of the city's most stylish hotels. Non-guests are welcome at the Paradise Lounge — a dark and beautiful lobby bar — and the poolside area, one of the best places in the city for a lazy afternoon cocktail. The fashion boutique ByGeorge carries Cartier and Tom Dixon. A perfect mid-Magazine Street stop.",
    hours: "Bar: daily noon–midnight",
    tip: "Day passes to the pool are available. The lobby bar does not require a room.",
    type: "Boutique Hotel & Bar",
    blog: "",
    phone: "+1 504-570-8000",
    website: "https://www.hotelsaintvincent.com",
  },

  // ─── WAREHOUSE & ARTS DISTRICT ───────────────────────────────────────────

  {
    id: 27,
    nbhd: "warehouse",
    name: "The National WWII Museum",
    cat: "landmark",
    emoji: "🎖️",
    address: "945 Magazine Street, Warehouse District",
    lat: 29.9449,
    lng: -90.0690,
    search: "National WWII Museum New Orleans Warehouse District",
    note: "One of the finest museums in the United States. The sprawling 400,000-square-foot complex tells the full story of the Second World War through immersive exhibitions, oral histories, artefacts and the 4D film Beyond All Boundaries narrated by Tom Hanks. The Liberation Pavilion, opened in 2023, is the newest and most emotionally affecting addition. Plan four hours minimum; serious visitors come for a full day.",
    hours: "Daily 9am–5pm",
    tip: "Book tickets online. The Solomon Victory Theater film runs every 90 minutes and is not to be missed.",
    type: "World-Class History Museum",
    blog: "",
    phone: "+1 504-528-1944",
    website: "https://www.nationalww2museum.org",
  },

  {
    id: 28,
    nbhd: "warehouse",
    name: "Ogden Museum of Southern Art",
    cat: "landmark",
    emoji: "🎨",
    address: "925 Camp Street, Warehouse District",
    lat: 29.9450,
    lng: -90.0702,
    search: "Ogden Museum Southern Art New Orleans Warehouse District Ogden After Hours",
    note: "The most comprehensive collection of Southern art in the world — paintings, sculpture, photography and crafts from 15 Southern states. Thursday evenings the museum hosts Ogden After Hours: local musicians play while patrons dance, drink and mingle in the galleries. National Geographic called it 'the best regularly scheduled cocktail party in town.' The permanent collection includes Clementine Hunter, Benny Andrews and Kendall Shaw.",
    hours: "Wed–Mon 10am–5pm; Thu until 8pm (Ogden After Hours 6–8pm, $10)",
    tip: "Come on a Thursday evening — the After Hours admission includes the full museum. Cochon restaurant is a short walk.",
    type: "Art Museum",
    blog: "",
    phone: "+1 504-539-9600",
    website: "https://www.ogdenmuseum.org",
  },

  {
    id: 29,
    nbhd: "warehouse",
    name: "Cochon",
    cat: "food",
    emoji: "🐷",
    address: "930 Tchoupitoulas Street, Warehouse District",
    lat: 29.9436,
    lng: -90.0701,
    search: "Cochon restaurant New Orleans Warehouse District Cajun pork Donald Link",
    note: "Donald Link's landmark Cajun restaurant has defined the Warehouse District's dining scene since 2006 and earned a Michelin Bib Gourmand in the inaugural 2025 Michelin Guide American South. The menu is built around the whole pig — cracklins, boudin, pork cheeks, smoked ham hocks — alongside Gulf seafood and wood-fired dishes that capture the flavour of south Louisiana better than almost anywhere in the city. Ian McNulty includes it on his annual best-of list every year. The Cochon Butcher shop next door does excellent sandwiches at lunch.",
    hours: "Lunch Mon–Fri 11am–2pm; Dinner Mon–Sat 5:30–10pm",
    tip: "The Louisiana cochon (pulled pork with turnips and cabbage) and the wood-fired oysters are the essential orders.",
    type: "Cajun Restaurant",
    blog: "",
    phone: "+1 504-588-2123",
    website: "https://www.cochonrestaurant.com",
  },

  {
    id: 30,
    nbhd: "warehouse",
    name: "Maison de la Luz / Bar Marilou",
    cat: "landmark",
    emoji: "🌟",
    address: "546 Carondelet Street, Warehouse District",
    lat: 29.9480,
    lng: -90.0712,
    search: "Maison de la Luz Bar Marilou New Orleans boutique hotel Warehouse",
    note: "The most glamorous boutique hotel in New Orleans — embossed linen keys, twin grand staircases, and a bespoke concierge experience. Bar Marilou is accessed through a faux bookcase and has earned a devoted following for its European-accented cocktails. The Modern Muse (vodka, Pineau des Charentes, verjus, pepita orgeat, mint) is the signature. Non-guests are welcome at the bar.",
    hours: "Bar Marilou: daily 5pm–midnight",
    tip: "You do not need to be staying to drink at Bar Marilou. Arrive before 8pm for a seat on a sofa.",
    type: "Luxury Boutique Hotel & Bar",
    blog: "",
    phone: "+1 504-814-0770",
    website: "https://www.maisondeluz.com",
  },

  {
    id: 31,
    nbhd: "warehouse",
    name: "Willie Mae's NOLA",
    cat: "food",
    emoji: "🍗",
    address: "898 Baronne Street, Central Business District",
    lat: 29.9419,
    lng: -90.0776,
    search: "Willie Mae's Scotch House New Orleans fried chicken Baronne Street",
    note: "The Willie Mae's family reopened downtown in November 2024 as Willie Mae's NOLA — bringing the legendary fried chicken recipe back to New Orleans after the original Tremé Scotch House was damaged by fire. The recipe is unchanged: brined, battered, fried to a crackling golden crust since 1957. Recognised in the inaugural 2025 Michelin Guide American South. The downtown location is a full-service restaurant with a proper bar and cocktail programme alongside the classics: cornbread, red beans, peach cobbler. Ian McNulty covered the reopening for the Times-Picayune. The original Scotch House on St. Ann Street is planned to reopen separately.",
    hours: "Mon/Wed–Sun 11am–9pm (closed Tuesday)",
    tip: "Unlike the original cash-only lunch counter, this location takes reservations (OpenTable), serves dinner and has cocktails. Arrive for lunch — the chicken is consistently available mid-week.",
    type: "Legendary Fried Chicken",
    blog: "",
    phone: "+1 504-354-8194",
    website: "https://www.williemaesnola.com",
  },

  {
    id: 32,
    nbhd: "warehouse",
    name: "Contemporary Arts Center",
    cat: "landmark",
    emoji: "🎭",
    address: "900 Camp Street, Warehouse District",
    lat: 29.9451,
    lng: -90.0694,
    search: "Contemporary Arts Center New Orleans CAC Warehouse District exhibitions",
    note: "The anchor of New Orleans' visual and performing arts scene, housed in a converted 19th-century warehouse. The CAC hosts rotating exhibitions from local and national artists, performance art, film, theatre and community events. Free on Thursdays. The building is beautiful and the programming consistently stretches beyond the expected.",
    hours: "Thu–Mon 11am–5pm",
    tip: "Free on Thursdays. Check the calendar for evening performance events — among the city's best cultural offerings.",
    type: "Contemporary Arts Centre",
    blog: "",
    phone: "+1 504-528-3805",
    website: "https://www.cacno.org",
  },

  // ─── MID-CITY & BAYOU ST JOHN ────────────────────────────────────────────

  {
    id: 33,
    nbhd: "mid-city",
    name: "City Park & New Orleans Museum of Art",
    cat: "nature",
    emoji: "🌳",
    address: "1 Collins Diboll Circle, City Park",
    lat: 29.9892,
    lng: -90.0935,
    search: "City Park New Orleans Museum of Art NOMA sculpture garden",
    note: "At 1,300 acres, City Park is larger than Central Park in New York. The New Orleans Museum of Art anchors the cultural offerings, while the free Sydney & Walda Besthoff Sculpture Garden — 90 contemporary works by Louise Bourgeois, Henry Moore, Rodin and others — spreads across five oak-shaded acres beside the lagoon. The Botanical Gardens, the Couturie Forest, a 300-year-old duelling oak and a 1906 antique carousel round out what could easily fill an entire day.",
    hours: "Park: daily sunrise–10pm. NOMA: Wed–Mon 10am–5pm ($15)",
    tip: "The sculpture garden is free and extraordinary. Take the Canal streetcar from the French Quarter — the stop is at the park gate.",
    type: "Park & Art Museum",
    blog: "",
    phone: "+1 504-658-4100",
    website: "https://www.noma.org",
  },

  {
    id: 34,
    nbhd: "mid-city",
    name: "Bayou St. John",
    cat: "nature",
    emoji: "🛶",
    address: "Bayou St. John, Mid-City",
    lat: 29.9838,
    lng: -90.0827,
    search: "Bayou St John New Orleans cypress spanish moss reflections houses",
    note: "A natural waterway running through Mid-City that gives New Orleans its most authentically Southern atmosphere: Spanish moss, historic wooden houses on the banks, herons wading in the shallows. Locals walk, run, kayak and picnic along the banks. The Pitot House on the waterway (circa 1799) is one of the oldest intact homes in the city. The most peaceful place in New Orleans within easy reach of the centre.",
    hours: "Always open",
    tip: "Pick up a po-boy from Parkway Bakery, walk 10 minutes to the bayou and eat on the bank. A perfect New Orleans afternoon.",
    type: "Natural Waterway",
    blog: "",
    phone: "",
    website: "",
  },

  {
    id: 35,
    nbhd: "mid-city",
    name: "Café Degas",
    cat: "food",
    emoji: "🇫🇷",
    address: "3127 Esplanade Avenue, Mid-City",
    lat: 29.9802,
    lng: -90.0772,
    search: "Cafe Degas New Orleans Esplanade Avenue French bistro romantic",
    note: "A romantic French bistro tucked under oak trees on Esplanade Avenue, named for Edgar Degas who once lived in the neighbourhood and painted the New Orleans Cotton Exchange. The partially open-air porch is strung with lights and feels like a garden bistro in Paris. Classic dishes — duck confit, bouillabaisse, steak frites — executed with genuine French attention. Recommended by local guides as one of the most romantic restaurants in New Orleans.",
    hours: "Lunch Wed–Fri 11am–3pm; Dinner Wed–Sun 5:30–9:30pm; Brunch Sat–Sun 10:30am–3pm",
    tip: "Request a table on the porch. The warm goat cheese salad and the duck confit are the dishes to anchor a meal around.",
    type: "French Bistro",
    blog: "",
    phone: "+1 504-945-5635",
    website: "https://www.cafedegas.com",
  },

  {
    id: 36,
    nbhd: "mid-city",
    name: "Angelo Brocato",
    cat: "cafe",
    emoji: "🍦",
    address: "214 N. Carrollton Avenue, Mid-City",
    lat: 29.9770,
    lng: -90.0916,
    search: "Angelo Brocato New Orleans Italian ice cream gelato cannoli Mid-City",
    note: "Angelo Brocato has been making Italian gelato, spumoni and granita in New Orleans since 1905. The family recipes are unchanged and the pink-tiled shop on Carrollton Avenue is an institution. The cannoli are the best in the city; the strawberry gelato in season is extraordinary. Ian McNulty lists it as one of New Orleans' great irreplaceable pleasures.",
    hours: "Tue–Sun 10am–9pm (closed Mon)",
    tip: "The spumoni — layered Italian ice cream with fruit and nuts — is the house speciality and rarely seen outside Sicily and New Orleans.",
    type: "Historic Italian Gelato",
    blog: "",
    phone: "+1 504-486-0078",
    website: "https://www.angelobrocatoicecream.com",
  },

  {
    id: 37,
    nbhd: "mid-city",
    name: "Parkway Bakery & Tavern",
    cat: "food",
    emoji: "🥖",
    address: "538 Hagan Avenue, Mid-City",
    lat: 29.9843,
    lng: -90.0841,
    search: "Parkway Bakery Tavern po-boy New Orleans Mid-City roast beef",
    note: "The city's most celebrated po-boy shop, making roast beef po-boys since 1911, and awarded a Michelin Bib Gourmand in the inaugural 2025 Michelin Guide American South. The slow-roasted beef debris — the scraps and drippings that fall into the roasting pan — is the definitive version of the city's most iconic sandwich. Queue at the counter, find a seat on the bayou-adjacent patio, and pair it with a long-neck Barq's root beer. Purely, essentially New Orleans.",
    hours: "Wed–Mon 11am–10pm (closed Tue)",
    tip: "Order the roast beef debris, fully dressed (lettuce, tomato, pickle, mayo on fresh French bread). The debris is what locals order.",
    type: "Po-Boy Institution",
    blog: "",
    phone: "+1 504-482-3047",
    website: "https://www.parkwaybakeryandtavern.com",
  },

  {
    id: 38,
    nbhd: "mid-city",
    name: "Lafitte Greenway",
    cat: "nature",
    emoji: "🚲",
    address: "Lafitte Greenway, Mid-City to Tremé",
    lat: 29.9756,
    lng: -90.0820,
    search: "Lafitte Greenway New Orleans cycling walking trail Mid-City Treme",
    note: "A 2.6-mile linear park and trail running from the French Quarter edge through Tremé and into Mid-City near Bayou St. John. Built on a former railroad corridor, the Greenway is the city's best route for cycling or walking between neighbourhoods — passing community gardens, murals and neighbourhood bars. Blue Bikes stations sit at both ends. Wrong Iron on Toulouse Street is the ideal pit stop for a pint mid-walk.",
    hours: "Always open",
    tip: "Blue Bikes stations at both ends. Rent a bike and ride it end-to-end for the best cross-section of the city away from tourists.",
    type: "Urban Trail & Park",
    blog: "",
    phone: "",
    website: "",
  },

  // ─── UPTOWN & CARROLLTON ─────────────────────────────────────────────────

  {
    id: 39,
    nbhd: "uptown",
    name: "The Kingsway",
    cat: "food",
    emoji: "🍜",
    address: "4201 Magazine Street, Uptown",
    lat: 29.9183,
    lng: -90.1020,
    direct_image: "https://static.wixstatic.com/media/f286e9_2b04bcadb5e749839c8edd2ea6af65ec~mv2.jpg/v1/fill/w_980,h_653,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/f286e9_2b04bcadb5e749839c8edd2ea6af65ec~mv2.jpg",
    search: "The Kingsway restaurant Magazine Street New Orleans Asian tasting menu 2025",
    note: "Chef Ashwin Vilkhu's debut solo restaurant — his family's culinary journey from New Delhi through Singapore and New Orleans told through an Asian tasting menu. A four-course prix-fixe ($92) includes dishes like refrigerator noodles, steamed snapper in dashi, and a tuna solera. Recognised in the inaugural 2025 Michelin Guide American South. Ian McNulty named it one of his five best new restaurants of 2025. Vilkhu and his father Arvinder received a 2025 James Beard Foundation Award nomination for Best Chef: South.",
    hours: "Tue–Thu 5–9:15pm; Fri–Sat 5–9:45pm (closed Sun–Mon)",
    tip: "The bar menu offers à la carte small plates if you want a shorter visit. The cocktail programme is as creative as the food.",
    type: "Asian Tasting Menu",
    blog: "",
    phone: "+1 504-506-9272",
    website: "https://www.kingswaynola.com",
  },

  {
    id: 40,
    nbhd: "uptown",
    name: "Tipitina's",
    cat: "pub",
    emoji: "🎸",
    address: "501 Napoleon Avenue, Uptown",
    lat: 29.9228,
    lng: -90.1036,
    search: "Tipitina's New Orleans music venue Napoleon Avenue Uptown",
    note: "The most storied music venue in New Orleans after Preservation Hall. Named after a Professor Longhair song, Tipitina's opened in 1977 as a place for local musicians who couldn't get booked elsewhere. The room is large, the sound system is excellent, and the wooden dance floor has been worn smooth by decades of New Orleans feet. Every genre from local brass bands to major touring acts.",
    hours: "Doors open at 7pm on show nights. Check calendar",
    tip: "Check tipitinas.com for the show calendar before you go — it varies from local R&B to major international acts.",
    type: "Historic Music Venue",
    blog: "",
    phone: "+1 504-895-8477",
    website: "https://www.tipitinas.com",
  },

  {
    id: 41,
    nbhd: "uptown",
    name: "Brigtsen's",
    cat: "food",
    emoji: "🦞",
    address: "723 Dante Street, Uptown",
    lat: 29.9182,
    lng: -90.1110,
    search: "Brigtsen's restaurant New Orleans Uptown Dante Street Cajun Creole",
    note: "Frank Brigtsen studied under Paul Prudhomme and has run this intimate Uptown cottage since 1986. This is Cajun-Creole cooking at its most personal: rabbit tenderloin with Creole mustard sauce, redfish court-bouillon, and a pecan pie that has no equal in the city. Ian McNulty includes it on his annual best-of list year after year. The dining room holds 60 people and is as warm as the cooking.",
    hours: "Dinner Tue–Sat from 5:30pm",
    tip: "The prix-fixe menu is the best value. Book ahead — it fills up every night.",
    type: "Creole-Cajun Neighbourhood Restaurant",
    blog: "",
    phone: "+1 504-861-7610",
    website: "https://www.brigtsens.com",
  },

  {
    id: 42,
    nbhd: "uptown",
    name: "Clancy's",
    cat: "food",
    emoji: "🦀",
    address: "6100 Annunciation Street, Uptown",
    lat: 29.9126,
    lng: -90.1044,
    search: "Clancys restaurant New Orleans Uptown Annunciation neighborhood Creole dining",
    note: "The restaurant most beloved by people who actually live in New Orleans. Clancy's is upscale without being formal — the dining room is clubby and comfortable, servers have been here for decades, and the menu is a roster of New Orleans classics executed with total confidence: smoked soft-shell crab, duck with fig sauce, oysters and brie. Recognised in the inaugural 2025 Michelin Guide American South. Ian McNulty has called it the place he would choose for a special dinner over any other restaurant in the city.",
    hours: "Lunch Thu–Fri 11:30am–1:30pm; Dinner Mon–Sat from 5:30pm",
    tip: "The smoked soft-shell crab is the signature dish. Dress smart-casual — the room expects it.",
    type: "Upscale Neighbourhood Restaurant",
    blog: "",
    phone: "+1 504-895-1111",
    website: "https://www.clancysneworleans.com",
  },

  {
    id: 43,
    nbhd: "uptown",
    name: "The Chloe",
    cat: "landmark",
    emoji: "🏡",
    address: "4125 St. Charles Avenue, Uptown",
    lat: 29.9228,
    lng: -90.0990,
    direct_image: "https://images.squarespace-cdn.com/content/v1/653ee72ec3c8b952ff750d37/1698621458515-1LMMLBKIVWMLYZMTHTME/TheChloe_Reception.jpg",
    search: "The Chloe hotel New Orleans St Charles Avenue Uptown boutique",
    note: "A cerulean blue 19th-century mansion on St. Charles Avenue — 14 rooms, a rooftop pool that is among the city's most coveted daytime spots, and record players with Marshall speakers in every room. The St. Charles streetcar stops at the door. Magazine Street is a short walk. The poolside bar and patio are open to non-guests during the day.",
    hours: "Bar & pool: daily 8am–10pm",
    tip: "The streetcar passes the front door roughly every 20 minutes — at $1.25 it is the best value transport in the city.",
    type: "Boutique Hotel",
    blog: "",
    phone: "+1 504-304-4000",
    website: "https://www.thechloe.com",
  },

  {
    id: 44,
    nbhd: "uptown",
    name: "Audubon Park",
    cat: "nature",
    emoji: "🦆",
    address: "6500 Magazine Street, Uptown",
    lat: 29.9232,
    lng: -90.1254,
    search: "Audubon Park New Orleans Uptown lagoon Spanish moss live oaks",
    note: "New Orleans' most beautiful green space in Uptown: 350 acres bordered by Magazine Street and the Mississippi levee, with a two-mile jogging loop around a lagoon, 500-year-old live oaks draped in Spanish moss, and the iconic Tree of Life. The Audubon Zoo occupies the park's riverside edge. Locals picnic here on Sunday afternoons — it is the most Southern park experience in the city.",
    hours: "Daily 6am–10pm",
    tip: "Walk the full lagoon loop at dusk. The light through the Spanish moss in the late afternoon is extraordinary.",
    type: "City Park",
    blog: "",
    phone: "",
    website: "",
  },

  {
    id: 45,
    nbhd: "uptown",
    name: "Barrel Proof",
    cat: "pub",
    emoji: "🥃",
    address: "1201 S. Carrollton Avenue, Carrollton",
    lat: 29.9226,
    lng: -90.1081,
    direct_image: "https://images.squarespace-cdn.com/content/v1/64ad7f8fd847f44824b303f1/e733c072-fecc-453a-9f39-e314e258b985/BarrelProof_RushJagoe%285%29.JPG",
    search: "Barrel Proof whiskey bar New Orleans Carrollton Uptown",
    note: "New Orleans' essential whiskey bar: 390 varieties in a spacious room that manages to feel both like a neighbourhood local and deeply serious about spirits. Beyond the whiskey, the cocktail programme is excellent, the beer list deep, and local food pop-ups run out of the kitchen until midnight. Good for a nightcap after Tipitina's, which is a short walk away.",
    hours: "Daily 4pm–2am",
    tip: "Ask the bartender to recommend something from the back shelf you wouldn't find anywhere else — they know the collection well.",
    type: "Whiskey Bar",
    blog: "",
    phone: "+1 504-299-1888",
    website: "https://www.barrelproofnola.com",
  },

  {
    id: 46,
    nbhd: "uptown",
    name: "La Petite Grocery",
    cat: "food",
    emoji: "🍝",
    address: "4238 Magazine Street, Uptown",
    lat: 29.9200,
    lng: -90.1014,
    search: "La Petite Grocery restaurant New Orleans Magazine Street Uptown",
    note: "Husband and wife chefs Mia and Justin Devillier have run this quietly excellent Uptown restaurant for over a decade. Recognised in the inaugural 2025 Michelin Guide American South. Justin Devillier won the James Beard Award for Best Chef: South in 2016. The dining room is gracious and unhurried; the bar up front is first-come, first-served for last-minute drop-ins. The menu blends classic and contemporary: one of those rare restaurants that works equally well for a special occasion dinner or an excellent Tuesday evening. Ian McNulty rates it among the city's consistent best.",
    hours: "Lunch Tue–Sat 11:30am–2:30pm; Dinner Mon–Thu & Sun 5–9:30pm, Fri–Sat 5–10:30pm; Brunch Sun 10:30am–2:30pm",
    tip: "The bar seats are great for a solo or impromptu visit. The turtle bolognese when it appears on the menu is not to be missed.",
    type: "Contemporary Neighbourhood Restaurant",
    blog: "",
    phone: "+1 504-891-3377",
    website: "https://www.lapetitegrocery.com",
  },

  {
    id: 47,
    nbhd: "uptown",
    name: "Cooter Brown's Tavern",
    cat: "pub",
    emoji: "🦪",
    address: "509 S. Carrollton Avenue, Carrollton",
    lat: 29.9228,
    lng: -90.1277,
    search: "Cooter Brown's Tavern New Orleans oyster bar beer Carrollton",
    note: "New Orleans Magazine readers have voted Cooter Brown's the city's best bar for years running. Over 400 beers, an excellent raw oyster bar, and a crowd that spans university students, old-timers and everyone in between. The back bar stocks experimental local beers; the front bar has Shucker's Oyster Sampler. As New Orleans as it gets.",
    hours: "Daily 11am–2am",
    tip: "Order the oyster sampler and a local craft beer to start. Always cold, always reliable.",
    type: "Neighbourhood Tavern & Oyster Bar",
    blog: "",
    phone: "+1 504-866-9104",
    website: "https://www.cooterbrowns.com",
  },

  {
    id: 48,
    nbhd: "french-quarter",
    name: "Fives Oyster Bar",
    cat: "food",
    emoji: "🦪",
    address: "529 St. Ann Street, French Quarter",
    lat: 29.9581,
    lng: -90.0647,
    search: "Fives oyster bar New Orleans Jackson Square 2023",
    note: "A standout addition to Jackson Square: a French Quarter oyster and cocktail bar in the 1851 Lower Pontalba Building with views of the Cathedral. The horseshoe marble bar, daily changing oyster selection from Gulf Coast and East Coast, and a tight cocktail menu (the Columns Martini is the signature) have quickly made it a local favourite. Gambit described it as the classy destination Jackson Square deserved. From Sandstone, the hospitality team behind Hotel Saint Vincent and The Columns.",
    hours: "Daily 11am–10pm; happy hour Mon–Thu 3–6pm",
    tip: "Sit at the marble bar for the full experience. The oyster selection changes daily — ask the shucker what came in that morning.",
    type: "Oyster Bar & Cocktail Bar",
    blog: "",
    phone: "+1 504-399-6954",
    website: "https://www.fives.bar",
  },

  {
    id: 49,
    nbhd: "french-quarter",
    name: "New Orleans Pharmacy Museum",
    cat: "landmark",
    emoji: "⚗️",
    address: "514 Chartres Street, French Quarter",
    lat: 29.9572,
    lng: -90.0646,
    search: "New Orleans Pharmacy Museum interior 19th century apothecary jars bottles",
    note: "Housed in the 1823 apothecary of America's first licensed pharmacist, Louis Joseph Dufilho Jr., this compact museum is one of the most quietly fascinating stops in the Quarter. The collection includes 19th-century medical instruments, voodoo potions, patent medicines and a jaw-dropping array of remedies from an era before pharmaceutical regulation. Takes 45 minutes and is far more interesting than it sounds. Almost universally overlooked by repeat visitors.",
    hours: "Tue–Sat 10am–4pm",
    tip: "Admission $5. Pair it with a walk down Chartres Street and a detour into St. Anthony's Garden behind the Cathedral.",
    type: "Historic Museum",
    blog: "",
    phone: "+1 504-565-8027",
    website: "https://www.pharmacymuseum.org",
  },

  {
    id: 50,
    nbhd: "warehouse",
    name: "Mardi Gras World",
    cat: "landmark",
    emoji: "🎭",
    address: "1380 Port of New Orleans Place, Warehouse District",
    lat: 29.9373,
    lng: -90.0653,
    search: "Mardi Gras World New Orleans parade floats tour warehouse",
    note: "The working studio of Blaine Kern Artists — the company that has built Mardi Gras parade floats for over 75 years. The guided tour walks through enormous warehouses packed with full-size floats in various states of construction, papier-mâché figures 20 feet tall, and thousands of costumes and props. Even if you can't be here for Mardi Gras, this is as close as you can get to the spectacle year-round. The scale of it is genuinely staggering.",
    hours: "Daily 9am–4:30pm (last tour 3:30pm)",
    tip: "The tour is about an hour and is genuinely worth it. Free king cake and coffee is included. Book online to skip the queue.",
    type: "Mardi Gras Float Studio Tour",
    blog: "",
    phone: "+1 504-361-7821",
    website: "https://www.mardigrasworld.com",
  },

];
