// A Perfect Day — Venice
// venice_data_v1.js — 43 curated places
//
// v1 — May 2026
// Voice: boutique hotel concierge — direct, specific, opinionated
// Six categories: Art & History · Bacaro · Dining · Artisan · Wander · Islands
//
// House-curated by Ludara.AI for the Ca' Sagredo Hotel demo
// Research sources: Italian press (Gambero Rosso, Veneto Secrets, Venezia da Vivere,
//   Venice Wiki, Dissapore, 1600venezia.it, Conoscerevenezia.it),
//   MICHELIN Guide Italia 2026, official hotel and artisan sites.
// All facts verified May 2026.

const PLACES = [

  // ── CANNAREGIO ────────────────────────────────────────────────────────────

  {
    id: 1,
    nbhd: 'cannaregio',
    name: 'Ca\' Sagredo Hotel',
    cat: 'art',
    emoji: '🎨',
    address: 'Campo Santa Sofia 4198/99, Cannaregio, Venezia',
    lat: 45.4409, lng: 12.3374,
    search: 'Ca Sagredo Hotel Venice Grand Canal palazzo facade pink',
    note: 'The only hotel in Venice that is also, formally, a museum. The frescoed staircase is Tirali; the ceiling paintings are Tiepolo, Bambini and Ricci; Pietro Longhi painted the walls while the plaster was still drying. The art was here long before any guest arrived — the Sagredo family were among the most serious collectors in the Serenissima. Galileo was a regular guest of the household. Walk slowly on the staircase.',
    hours: 'Guests only — lobby visible to visitors by arrangement with reception',
    tip: 'Ask at reception for the printed art guide to the rooms. The staircase fresco is best seen in morning light. The Grand Canal terrace serves aperitivo from 17:00.',
    type: '15th-century palazzo — private museum and Grand Canal hotel',
    awards: 'Small Luxury Hotels of the World',
    website: 'https://www.casagredohotel.com',
  },
  {
    id: 2,
    nbhd: 'cannaregio',
    name: 'Ca\' d\'Oro',
    cat: 'art',
    emoji: '🏛️',
    address: 'Calle di Ca\' d\'Oro 3932, Cannaregio, Venezia',
    lat: 45.4404, lng: 12.3367,
    search: 'Ca d\'Oro Venice Gothic palace facade Grand Canal gold',
    note: 'The finest Gothic facade on the Grand Canal — once gilded, hence the name. Almost everyone photographs it from the water and walks on. Almost no one goes inside, which means the Mantegna Saint Sebastian on the piano nobile is usually yours alone. The carved stonework by Matteo Raverti is the finest surviving Venetian flamboyant Gothic. Go in.',
    hours: 'Mon 08:15–14:00; Tue–Sun 08:15–19:15; closed first and third Mon of month',
    tip: 'Buy tickets online to skip the queue. The Mantegna Saint Sebastian is on the piano nobile to the right of the loggia — do not leave without finding it. The courtyard well-head is 14th century.',
    type: 'Gothic palazzo — Galleria Giorgio Franchetti',
    website: 'https://caoro.cultura.gov.it',
  },
  {
    id: 3,
    nbhd: 'cannaregio',
    name: 'Madonna dell\'Orto',
    cat: 'art',
    emoji: '⛪',
    address: 'Campo della Madonna dell\'Orto 3512, Cannaregio, Venezia',
    lat: 45.4488, lng: 12.3222,
    search: 'Madonna dell\'Orto Venice church Tintoretto Cannaregio Gothic facade',
    note: 'Tintoretto\'s own church. He lived two minutes away, donated ten paintings over his lifetime, and was buried here in 1594. Two of those paintings flank the high altar — each over ten metres tall, painted directly for this room and never moved. In the quieter part of Cannaregio, this is one of the most moving churches in Venice and one of the least crowded.',
    hours: 'Mon–Sat 10:00–17:00; closed Sun morning',
    tip: 'Arrive before 10:30 to have the Tintoretto paintings to yourself. The sacristy contains a small Bellini. The walk along the Fondamenta della Misericordia back toward the centre is the most authentic stretch of Cannaregio.',
    type: 'Tintoretto\'s parish church — his tomb and ten paintings in situ',
    website: 'https://www.madonnadellortovenezia.it',
  },
  {
    id: 4,
    nbhd: 'cannaregio',
    name: 'Santa Maria dei Miracoli',
    cat: 'art',
    emoji: '💎',
    address: 'Campo dei Miracoli, Cannaregio, Venezia',
    lat: 45.4421, lng: 12.3352,
    search: 'Santa Maria dei Miracoli Venice interior marble Renaissance Pietro Lombardo',
    note: 'Pietro Lombardo covered every surface in coloured marble — floors, pilasters, barrel vault, carved ceiling panels — in a space no larger than a chapel. From outside it reads as pretty; from inside it is a perfect act of Renaissance architecture. The proportions are immaculate, the light falls exactly where it should. There is almost never a queue.',
    hours: 'Mon–Sat 10:00–17:00 (Chorus Pass or ticket)',
    tip: 'Combine with the Chorus Pass (covers 16 Venetian churches — good value if you plan to visit several). The church is small and fills quickly at noon; early morning or late afternoon is best.',
    type: 'Renaissance jewel — Pietro Lombardo, 1481–1489',
    website: 'https://www.chorusvenezia.org',
  },
  {
    id: 5,
    nbhd: 'cannaregio',
    name: 'Vini da Gigio',
    cat: 'bacaro',
    emoji: '🍷',
    address: 'Fondamenta San Felice 3628, Cannaregio, Venezia',
    lat: 45.4411, lng: 12.3349,
    search: 'Vini da Gigio Venice canal bacaro wine cellar interior',
    note: 'MICHELIN-listed and respected by Venetian restaurateurs — which is harder to earn than the listing. The cellar runs to several hundred labels, strong in Veneto and Friuli small-producers. Co-owner Paolo Lazzari is likely behind the bar; tell him your budget and let him choose. The sarde in saor is a benchmark version of the dish.',
    hours: 'Wed–Sun 12:00–14:30, 19:00–22:30; closed Mon–Tue',
    tip: 'Book ahead — the room is small. Tell Paolo your budget and let him choose the wine. The sarde in saor is a benchmark version of the dish.',
    type: 'MICHELIN-listed bacaro and wine bar — canal-side, Cannaregio',
    awards: 'MICHELIN Guide Italia 2026',
    website: 'https://www.vinidagigio.com',
  },
  {
    id: 6,
    nbhd: 'cannaregio',
    name: 'Anice Stellato',
    cat: 'bacaro',
    emoji: '🌿',
    address: 'Fondamenta della Sensa 3272, Cannaregio, Venezia',
    lat: 45.4476, lng: 12.3238,
    search: 'Anice Stellato Venice bacaro canal Fondamenta Sensa Cannaregio',
    note: 'Canal-side tables, natural wines, a blackboard menu that changes with the market. In the northern reaches of Cannaregio where tourists are genuinely rare. The baccalà mantecato is consistently good. Come at 18:00 for the best chance at an outdoor seat — the regulars know to arrive early and are glad they did.',
    hours: 'Wed–Sun 10:00–15:00, 18:00–22:30; closed Mon–Tue',
    tip: 'The outdoor canal-side tables are first-come. Arrive at 18:00 when they open in the evening and you will get one. Ask what arrived from the market that morning.',
    type: 'Canal-front bacaro — natural wines, Cannaregio',
    website: 'https://www.osteriaanicestellato.com',
  },
  {
    id: 7,
    nbhd: 'cannaregio',
    name: 'Antica Adelaide',
    cat: 'bacaro',
    emoji: '🕯️',
    address: 'Calle Priuli 3728, Cannaregio, Venezia',
    lat: 45.4444, lng: 12.3277,
    search: 'Antica Adelaide Venice osteria interior candlelit wood Cannaregio',
    note: 'An 18th-century osteria that has never tried to be anything other than an osteria. Bare wood, low light, creative Venetian cooking — and the kitchen stays open until 1am, which in Venice is extraordinary. When everywhere else has closed and the conversation has gone on longer than expected, this is where Venetians go.',
    hours: 'Daily 12:00–15:00, 18:00–01:00',
    tip: 'The late closing makes this the obvious last stop of an evening. The kitchen genuinely runs until 1am — not a token menu, the full kitchen.',
    type: '18th-century osteria — creative Venetian, open until 1am',
    website: 'https://www.anticaadelaide.com',
  },
  {
    id: 8,
    nbhd: 'cannaregio',
    name: 'Campo de\' Mori',
    cat: 'wander',
    emoji: '🗿',
    address: 'Campo de\' Mori, Cannaregio, Venezia',
    lat: 45.4482, lng: 12.3225,
    search: 'Campo dei Mori Venice medieval statues street corner Cannaregio',
    note: 'Three medieval stone merchants are embedded in the corner walls, noses worn smooth from centuries of hands reaching to touch them for luck. Tintoretto\'s house is steps away on the Fondamenta dei Mori — the plaque is easy to find. Come in the evening when the light is low and the stone takes on a quality that is difficult to describe.',
    hours: 'Open always',
    tip: 'Walk from here along the Fondamenta dei Mori to the church of Madonna dell\'Orto — ten minutes, almost no tourist foot traffic, and one of the best sequences of streets in Venice.',
    type: 'Medieval campo — the Mastelli brothers and Tintoretto\'s neighbourhood',
  },
  {
    id: 9,
    nbhd: 'cannaregio',
    name: 'Fondamenta della Misericordia',
    cat: 'wander',
    emoji: '🌅',
    address: 'Fondamenta della Misericordia, Cannaregio, Venezia',
    lat: 45.4467, lng: 12.3252,
    search: 'Fondamenta Misericordia Venice canal evening aperitivo bacari row locals',
    note: 'Venice\'s real aperitivo hour. Bacari string along this canal-side walkway with tables on the pavement, the canal filling with reflections. A glass of Spritz, a plate of cicchetti for three euros. This is where Venetians actually spend their evenings — not around Rialto, but here. Walk the full length and stop wherever looks right.',
    hours: 'Most bacari active 17:00–22:00',
    tip: 'No reservations needed — this is a walk-in aperitivo strip. Osteria al Bacco, Al Timon, and Paradiso Perduto are the anchor points but the mood is consistent throughout. Come between 18:30 and 20:00 for the fullest version of it.',
    type: 'Canal-side aperitivo strip — the real Venetian evening',
  },

  // ── SAN POLO ──────────────────────────────────────────────────────────────

  {
    id: 10,
    nbhd: 'san_polo',
    name: 'Cantina Do Mori',
    cat: 'bacaro',
    emoji: '🍾',
    address: 'Calle Do Mori 429, San Polo, Venezia',
    lat: 45.4378, lng: 12.3349,
    search: 'Cantina Do Mori Venice oldest bacaro interior copper pots hanging',
    note: 'Founded around 1462 — the oldest bacaro in Venice. The interior is what authenticity actually looks like when it has not been restored for atmosphere: old photographs, antique jugs hanging from the beams, a bar polished by six centuries of elbows. Casanova valued the double exit doors for fast departures. The cicchetti are seasonal and house-made. Come before noon.',
    hours: 'Mon–Sat 08:00–20:00; closed Sun',
    tip: 'Arrive early — by 12:30 it fills. Order the francobolli (small tramezzini squares) and the baccalà mantecato on white polenta. The house wine is better than it needs to be at this price.',
    type: 'Venice\'s oldest bacaro — est. 1462, Rialto',
    website: 'https://www.cantinadomori.com',
  },
  {
    id: 11,
    nbhd: 'san_polo',
    name: 'All\'Arco',
    cat: 'bacaro',
    emoji: '🥂',
    address: 'Calle dell\'Arco 436, San Polo, Venezia',
    lat: 45.4378, lng: 12.3354,
    search: 'All\'Arco Venice bacaro cicchetti crostini Francesco Matteo Rialto',
    note: 'Francesco and his son Matteo buy from the Rialto market every morning and build the cicchetti board from what arrived. The result changes daily and reflects the season honestly. Venetians rank the crostini among the best in the city — which is the only ranking that matters. Lunch only. Come before 12:30. Cash preferred.',
    hours: 'Mon–Sat 08:00–14:30; closed Sun',
    tip: 'Lunch only. Come between 11:00 and 12:30 to see the full board before the best pieces sell. Ask Matteo what is freshest. Cash preferred.',
    type: 'Standing cicchetti bar — market-to-bar, Rialto',
    website: 'https://veneziaautentica.com/venice-bacaro-bar-osteria-all-arco/',
  },
  {
    id: 12,
    nbhd: 'san_polo',
    name: 'Mercato di Rialto',
    cat: 'wander',
    emoji: '🐟',
    address: 'Campo della Pescaria, San Polo, Venezia',
    lat: 45.4383, lng: 12.3355,
    search: 'Rialto fish market Venice pescheria morning seafood lagoon stalls',
    note: 'On this site since the 12th century. Arrive at 8:00 for crates of spider crab, seppie still moving, clams raked from the lagoon that morning. The restaurants behind these stalls serve the same fish for lunch; the bacari on the surrounding calli use what did not sell. The whole system still works exactly as designed, five hundred years later.',
    hours: 'Pescheria: Tue–Sat 07:30–12:00. Vegetables: Mon–Sat 07:00–13:00',
    tip: 'Be there by 8:00 on a Tuesday or Wednesday. The cicchetti at All\'Arco (two minutes away) use what was bought here that morning — the connection is direct.',
    type: 'Historic wholesale food market — fish and vegetables since the 12th century',
  },
  {
    id: 13,
    nbhd: 'san_polo',
    name: 'Antiche Carampane',
    cat: 'dining',
    emoji: '🦞',
    address: 'Rio Terà delle Carampane 1911, San Polo, Venezia',
    lat: 45.4381, lng: 12.3313,
    search: 'Antiche Carampane Venice restaurant no pizza tourist menu sign fish',
    note: 'The sign at the door reads: No pizza, no lasagne, no menù turistico. Nani Bortoluzzi\'s father was a fish wholesaler at the Rialto; the sourcing is in the family. MICHELIN-listed and respected by Venetian restaurateurs. The spaghetti in cassopipa — a slow-cooked Venetian brodetto — is the dish to order. The address is deliberately hard to find. Book ahead.',
    hours: 'Tue–Sat 12:30–14:00, 19:30–22:00; closed Sun–Mon',
    tip: 'Book ahead — the room is not large and fills with regulars. The spaghetti in cassopipa is the dish to order. Do not arrive expecting to improvise a booking.',
    type: 'MICHELIN-listed Venetian fish restaurant — Rialto',
    awards: 'MICHELIN Guide Italia 2026',
    website: 'https://www.antichecarampane.com',
  },
  {
    id: 14,
    nbhd: 'san_polo',
    name: 'Campo San Polo',
    cat: 'wander',
    emoji: '☀️',
    address: 'Campo San Polo, San Polo, Venezia',
    lat: 45.4389, lng: 12.3296,
    search: 'Campo San Polo Venice largest square open space market',
    note: 'Venice\'s largest square after San Marco — and completely different in character. Children on bicycles in the afternoon, couples on benches in the evening, a Tintoretto and a Tiepolo Stations of the Cross along the north church wall. Come at dusk when the light goes horizontal and the school groups have gone home.',
    hours: 'Open always; church Mon–Sat 10:00–17:00',
    tip: 'The campo is a natural rest stop on any walk through San Polo. The bar on the northwest corner serves coffee at a price honest enough for locals.',
    type: 'Venice\'s second-largest campo — neighbourhood life, San Polo',
  },

  // ── CASTELLO ──────────────────────────────────────────────────────────────

  {
    id: 15,
    nbhd: 'castello',
    name: 'Osteria alle Testiere',
    cat: 'dining',
    emoji: '🦀',
    address: 'Calle del Mondo Novo 5801, Castello, Venezia',
    lat: 45.4371, lng: 12.3396,
    search: 'Osteria alle Testiere Venice small MICHELIN Bruno Gavagnin seafood',
    note: 'Twenty-two seats, MICHELIN-listed since 1993, and Bruno Gavagnin has never once served a tourist menu. The menu changes daily based on what came from the lagoon — there is no fixed card and no point asking in advance. This is the restaurant Venetian food professionals use as their baseline. Book at least two weeks ahead.',
    hours: 'Tue–Sat 12:30–14:00, 19:30–21:30; closed Sun–Mon; closed Aug',
    tip: 'Book at least two weeks ahead for dinner. There are two sittings per service — confirm your time. The crudo di scampi is always on the menu in some form when scampi are running.',
    type: 'MICHELIN-listed trattoria — 22 seats, daily-changing market menu',
    awards: 'MICHELIN Guide Italia 2026',
    website: 'http://www.osterialletestiere.it',
  },
  {
    id: 16,
    nbhd: 'castello',
    name: 'Al Covo',
    cat: 'dining',
    emoji: '🍝',
    address: 'Campiello della Pescaria 3968, Castello, Venezia',
    lat: 45.4346, lng: 12.3454,
    search: 'Al Covo Venice restaurant Castello MICHELIN Diane Rankin Cesare Benelli',
    note: 'Cesare Benelli and his Texan wife Diane opened this in 1987 with one intention: Venetian ingredients, Venetian manner, no compromise. MICHELIN has listed it every year since. The room is in a quiet campiello near the Arsenale, in a part of Castello most visitors never reach. Diane\'s warmth is as much part of the restaurant as the food.',
    hours: 'Thu–Mon 12:45–14:30, 19:30–22:00; closed Tue–Wed',
    tip: 'The neighbourhood between Al Covo and the Arsenale is the least-visited in the city. Combine the dinner with an afternoon walk along Via Garibaldi and the Riva dei Sette Martiri.',
    type: 'MICHELIN-listed trattoria — seasonal Venetian since 1987',
    awards: 'MICHELIN Guide Italia 2026',
    website: 'https://www.ristorantealcovo.com',
  },
  {
    id: 17,
    nbhd: 'castello',
    name: 'Libreria Acqua Alta',
    cat: 'artisan',
    emoji: '📚',
    address: 'Calle Lunga Santa Maria Formosa 5176/b, Castello, Venezia',
    lat: 45.4358, lng: 12.3413,
    search: 'Libreria Acqua Alta Venice books gondola bathtub cats bookshop interior',
    note: 'Luigi Frizzo stores his used books in gondolas, bathtubs and a full-sized rowboat because acqua alta can\'t reach anything above the waterline. The cats help with neither the flooding nor the alphabetical order. A staircase made of books leads to a canal-side terrace. Multilingual, joyfully unorganised, and worth thirty minutes minimum.',
    hours: 'Daily 09:00–19:30',
    tip: 'Go to the back for the canal terrace — it is the best reason to stay. The multilingual children\'s section is stacked in the bathtub near the entrance. Budget thirty minutes minimum.',
    type: 'Legendary used bookshop — books in gondolas, resident cats, canal terrace',
    website: 'https://www.libreriaacquaalta.it',
  },
  {
    id: 18,
    nbhd: 'castello',
    name: 'Via Garibaldi',
    cat: 'wander',
    emoji: '🥬',
    address: 'Via Garibaldi, Castello, Venezia',
    lat: 45.4330, lng: 12.3490,
    search: 'Via Garibaldi Venice wide street local market greengrocers Castello',
    note: 'Napoleon ordered the canal filled in 1808 to create Venice\'s only wide, straight boulevard. Today it is fruit stalls, a fish seller, coffee bars and ordinary shops for an ordinary neighbourhood. No souvenir shops. Walk to the end for the southern lagoon view along the Riva dei Sette Martiri.',
    hours: 'Market stalls: Mon–Sat 07:30–13:00',
    tip: 'Walk from here along the Riva dei Sette Martiri toward the Giardini for the best unrestricted view of the southern lagoon. The whole eastern Castello loop takes two hours and is almost entirely tourist-free.',
    type: 'The wide street — local market boulevard, working-class Castello',
  },

  // ── DORSODURO ─────────────────────────────────────────────────────────────

  {
    id: 19,
    nbhd: 'dorsoduro',
    name: 'Gallerie dell\'Accademia',
    cat: 'art',
    emoji: '🖼️',
    address: 'Campo della Carità 1050, Dorsoduro, Venezia',
    lat: 45.4311, lng: 12.3278,
    search: 'Gallerie dell\'Accademia Venice interior Titian Veronese Tintoretto sala',
    note: 'The canonical survey of Venetian painting from 1300 to 1800 — Bellini, Carpaccio, Giorgione, Titian, Veronese, Tintoretto — housed in a converted convent. The Titian Presentation of the Virgin hangs in the room it was painted for and has never left. Veronese\'s Feast in the House of Levi was renamed under Inquisition pressure after it was completed as a Last Supper. Budget three hours minimum.',
    hours: 'Mon 08:15–14:00; Tue–Sun 08:15–19:15',
    tip: 'Book online. The Titian Presentation of the Virgin is in Room 24 — the only painting still in the room it was made for. Room 21 (Carpaccio Ursula cycle) requires a separate timed entry; book it when you buy your ticket.',
    type: 'Canonical Venetian painting from 1300–1800 — Bellini, Titian, Veronese, Tintoretto',
    website: 'https://www.gallerieaccademia.it',
  },
  {
    id: 20,
    nbhd: 'dorsoduro',
    name: 'Punta della Dogana',
    cat: 'art',
    emoji: '⛵',
    address: 'Fondamenta della Dogana alla Salute 2, Dorsoduro, Venezia',
    lat: 45.4301, lng: 12.3347,
    search: 'Punta della Dogana Venice contemporary art Pinault Foundation tip Grand Canal',
    note: 'The 17th-century customs house at the tip of Dorsoduro, converted by Tadao Ando for François Pinault\'s collection in 2009. The Pinault Foundation holds serious contemporary work — Koons, Hirst, Kara Walker, Cy Twombly — but what Ando did with the light is the real achievement. Two open-water views and the dome of the Salute behind you.',
    hours: 'Wed–Mon 10:00–19:00; closed Tue',
    tip: 'Combined ticket with Palazzo Grassi (Pinault\'s other Venice museum) is available and worth it. The tip of the building, outside the museum entrance, is publicly accessible and one of the finest standing points in the city.',
    type: 'Pinault Foundation — contemporary art in a 17th-century customs house',
    website: 'https://www.puntadelladogana.it',
  },
  {
    id: 21,
    nbhd: 'dorsoduro',
    name: 'San Sebastiano',
    cat: 'art',
    emoji: '✝️',
    address: 'Campo San Sebastiano, Dorsoduro, Venezia',
    lat: 45.4296, lng: 12.3207,
    search: 'San Sebastiano Venice church Veronese ceiling frescoes Dorsoduro',
    note: 'Veronese arrived in Venice around 1553 and treated this western Dorsoduro church as his personal studio for thirty years — painting the ceiling, the sacristy, the organ doors, the chancel, the high altar, the choir. When he died in 1588 he was buried under the organ loft. The exterior is plain brick. The contrast with the interior is one of the great surprises in Venice. Almost no tourists find it.',
    hours: 'Mon–Sat 10:00–17:00 (Chorus Pass or ticket)',
    tip: 'Bring binoculars or use the phone camera\'s zoom to read the ceiling. The sacristy ceiling (Stories of Esther) is the best place to start. Veronese\'s tomb is under the organ loft — the plaque is modest.',
    type: 'Veronese\'s personal chapel — three decades of painting in a single church',
    website: 'https://www.chorusvenezia.org',
  },
  {
    id: 22,
    nbhd: 'dorsoduro',
    name: 'Santa Maria della Salute',
    cat: 'art',
    emoji: '⛩️',
    address: 'Fondamenta della Dogana alla Salute 1, Dorsoduro, Venezia',
    lat: 45.4310, lng: 12.3349,
    search: 'Santa Maria della Salute Venice Baroque dome Grand Canal Longhena exterior',
    note: 'Baldassare Longhena won this commission at 26, building an ex-voto on the Grand Canal for the end of a plague that killed a third of Venice. The result — octagonal plan, two great domes, the scrolled volutes he invented — is one of the most recognisable silhouettes in European architecture. The Titian sacristy ceiling requires a separate ticket and is worth it.',
    hours: 'Daily 09:00–12:00, 15:00–17:30; sacristy ticket required for Titans',
    tip: 'The Titian ceiling in the sacristy requires a small entrance fee paid separately. Enter from the right side of the nave. The view back across the Grand Canal from the steps is one of the photographs everyone takes — allow time for it.',
    type: 'Baroque votive basilica — Longhena, 1631; Titian ceiling in sacristy',
    website: 'https://www.seminariovenezia.it/basilica-salute/',
  },
  {
    id: 23,
    nbhd: 'dorsoduro',
    name: 'Campo Santa Margherita',
    cat: 'wander',
    emoji: '🛖',
    address: 'Campo Santa Margherita, Dorsoduro, Venezia',
    lat: 45.4330, lng: 12.3236,
    search: 'Campo Santa Margherita Venice local square students cafe fruit stalls',
    note: 'Dorsoduro\'s main square — elongated, uneven, and genuinely alive. Ca\' Foscari university is nearby; the aperitivo bars run from noon; the fruit stall has been in the same position for as long as anyone remembers. The Scuola dei Carmini on the south side has a Tiepolo ceiling upstairs worth a short detour. Come between 17:00 and 19:00.',
    hours: 'Open always; stalls active 07:30–13:00; bars 08:00 onwards',
    tip: 'Il Caffe (also called Bar Rosso) on the western side has been there since 1870 and serves the neighbourhood\'s aperitivo. Come between 17:00 and 19:00. The Scuola dei Carmini closes at 16:00 — plan accordingly.',
    type: 'The neighbourhood square — students, fruit stalls, Dorsoduro life',
  },
  {
    id: 24,
    nbhd: 'dorsoduro',
    name: 'Squero di San Trovaso',
    cat: 'wander',
    emoji: '⚓',
    address: 'Fondamenta Bonlini 1097, Dorsoduro, Venezia',
    lat: 45.4313, lng: 12.3265,
    search: 'Squero San Trovaso Venice gondola workshop canal Dorsoduro mountain building',
    note: 'One of the last working gondola workshops in Venice, operating since the 17th century. The building looks architecturally wrong — alpine timber, sloping roof — because the craftsmen came from the Cadore mountains and built in the style they knew. A gondola requires 200 hand-made components and 500 hours of labour. From the opposite fondamenta, you can watch the work for free.',
    hours: 'Exterior viewable always; guided tours — check squero directly for current schedule',
    tip: 'From the Fondamenta Nani across the canal you can watch the work for free. The guided tour includes the workshop floor and is worth booking if it is available.',
    type: '17th-century gondola workshop — still building by hand',
    website: 'http://www.squerosantrovaso.com',
  },

  // ── SANTA CROCE ───────────────────────────────────────────────────────────

  {
    id: 25,
    nbhd: 'santa_croce',
    name: 'Tessitura Luigi Bevilacqua',
    cat: 'artisan',
    emoji: '🪡',
    address: 'Campiello della Comare 1320, Santa Croce, Venezia',
    lat: 45.4399, lng: 12.3239,
    search: 'Tessitura Bevilacqua Venice historic loom velvet brocade weaving Santa Croce',
    note: 'Eighteen original 18th-century wooden looms, still running, producing the soprarizzo velvet — pile-on-pile, one metre per day per loom — that furnished the palaces of the Serenissima. The archive holds 3,500 original punch-card designs, all still in use. The sound of the looms is audible from the street. Ask to see the archive room.',
    hours: 'Mon–Fri 09:00–17:00; Sat by appointment',
    tip: 'Ask to see the archive room — the perforated cardboard punch-patterns that program the looms are extraordinary objects in themselves. The showroom pieces start at accessible prices for small items; the full velvets are investment purchases.',
    type: 'Artisan textile mill — 18 antique looms, soprarizzo velvet since 1875',
    website: 'https://www.luigi-bevilacqua.com',
  },
  {
    id: 26,
    nbhd: 'santa_croce',
    name: 'Osteria Mocenigo',
    cat: 'dining',
    emoji: '🍤',
    address: 'Salizada San Stae 1919, Santa Croce, Venezia',
    lat: 45.4399, lng: 12.3269,
    search: 'Osteria Mocenigo Venice Santa Croce San Stae local trattoria',
    note: 'The neighbourhood trattoria that the neighbourhood actually uses. Mixed fried fish, pasta al nero di seppia, sarde in saor, a rotating secondo based on the Rialto market. The wine is local and honest. Better quality-to-price than anything in the tourist circuits. No reservation needed for lunch.',
    hours: 'Mon–Sat 12:00–15:00, 19:00–22:30; closed Sun',
    tip: 'No reservation required for lunch. The bacaro seating at the bar is good for cicchetti and a glass before the proper lunch sitting. Ask what the secondo is today before ordering.',
    type: 'Neighbourhood trattoria — market Venetian cooking, Santa Croce',
    website: 'https://www.osteriamocenigo.com',
  },
  {
    id: 27,
    nbhd: 'santa_croce',
    name: 'La Zucca',
    cat: 'dining',
    emoji: '🎃',
    address: 'Ponte del Megio 1762, Santa Croce, Venezia',
    lat: 45.4407, lng: 12.3256,
    search: 'La Zucca Venice vegetarian pumpkin flan canal restaurant Santa Croce',
    note: 'The pumpkin flan with aged Montasio cheese has been on the menu since the 1990s and has never needed replacing. The kitchen is genuinely vegetable-focused — not ideological, just interested in what the market brings. The canal runs two metres from the table. The gnocchi change by season. Book for dinner.',
    hours: 'Mon–Sat 12:30–14:30, 19:00–22:30; closed Sun',
    tip: 'Order the flan di zucca con Montasio — it has been on the menu for decades for good reason. The canal table is first-come but worth arriving early for. Book for dinner.',
    type: 'Vegetable-focused trattoria — pumpkin flan, canal-side, Santa Croce',
    website: 'https://www.lazucca.it',
  },

  // ── SAN MARCO ─────────────────────────────────────────────────────────────

  {
    id: 28,
    nbhd: 'san_marco',
    name: 'Palazzo Fortuny',
    cat: 'art',
    emoji: '🎭',
    address: 'Campo San Beneto 3780, San Marco, Venezia',
    lat: 45.4344, lng: 12.3307,
    search: 'Palazzo Fortuny Venice interior Mariano Fortuny studio museum fabric collection',
    note: 'Mariano Fortuny — painter, photographer, textile genius, inventor of the Delphos gown — lived and worked in this 15th-century Gothic palazzo from 1899 until his death in 1949, and it still looks like he might return. His paintings, photographs, stage-set models, fabrics and fifty years of collected objects are all still here. Less curated museum than personal world, still intact.',
    hours: 'Wed–Mon 10:00–18:00; closed Tue; temporary exhibitions may vary',
    tip: 'The permanent collection rooms on the upper floors are often overlooked by visitors focused on whatever temporary show is running. The upper studio, with its original warp-printed fabrics and stage-design drawings, is the most revealing room.',
    type: 'Fortuny\'s studio and home — Gothic palazzo, permanent collection',
    website: 'https://fortuny.visitmuve.it',
  },
  {
    id: 29,
    nbhd: 'san_marco',
    name: 'Damocle Edizioni',
    cat: 'artisan',
    emoji: '📖',
    address: 'Calle dello Spezier 2867, San Marco, Venezia',
    lat: 45.4349, lng: 12.3320,
    search: 'Damocle Edizioni Venice independent bookshop art gallery San Marco',
    note: 'An independent bookshop and small gallery in San Marco that operates as though location theory is someone else\'s problem. The stock is strong in architecture, art history and Venetian subjects — one of the most carefully selected Venetian sections in the city. Artist\'s books and exhibition catalogues appear here before reaching most other stockists. The owner has a point of view.',
    hours: 'Mon–Sat 10:00–19:30',
    tip: 'The Venetian history and art section is worth extended browsing. Ask the owner what is worth reading on Venice in Italian — the response will be specific and personal.',
    type: 'Independent bookshop and art gallery — architecture, art history, Venetian specialisms',
    website: 'https://www.damocleedizioni.com',
  },

  // ── SAN POLO / ARTISAN ────────────────────────────────────────────────────

  {
    id: 30,
    nbhd: 'san_polo',
    name: 'Il Pavone',
    cat: 'artisan',
    emoji: '🦚',
    address: 'Fondamenta dei Preti 721, Dorsoduro, Venezia',
    lat: 45.4373, lng: 12.3274,
    search: 'Il Pavone Venice paper marbling marbled paper artisan workshop',
    note: 'Paolo Pelosin has been marbling paper by hand for thirty years in a small studio near the Frari. Coloured inks float on water, combed into patterns — peacock, stone, bouquet, French curl — and transferred to paper in a single motion. Each sheet cannot be exactly repeated. Watch the process if he is working. The smaller sheets pack flat and are honestly priced.',
    hours: 'Mon–Sat 10:00–13:00, 14:00–18:00',
    tip: 'Watch the process if he is making while you are there — it takes less than five minutes per sheet and is worth seeing once. The smaller sheets are an accessible price and pack flat.',
    type: 'Paper marbling studio — Venetian carta marmorizzata tradition, 30+ years',
    website: 'https://www.ilpavonedivenezia.it',
  },

  // ── ISLANDS ───────────────────────────────────────────────────────────────

  {
    id: 31,
    nbhd: 'murano',
    name: 'Murano',
    cat: 'island',
    emoji: '🫧',
    address: 'Isola di Murano, Venezia',
    lat: 45.4568, lng: 12.3540,
    search: 'Murano Venice glass blowing furnace master artisan workshop island',
    note: 'The Republic moved all glass production here in 1291 — officially a fire precaution, really to control the technology. The serious furnaces still operate: Venini, Barovier & Toso. Come on a weekday morning before the tour groups arrive. The island also has its own Grand Canal, its own Byzantine church, and its own neighbourhood life entirely separate from the glass trade.',
    hours: 'Vaporetto Line 4.1 or 4.2 from Fondamente Nuove — approx. 12 min. Museo del Vetro: daily 10:00–18:00',
    tip: 'Walk past the main Colonna waterfront and head into the interior campos — Murano has its own Grand Canal, its own parish churches (Santa Maria e Donato has the finest Byzantine mosaic floor in the Veneto), and its own neighbourhood life separate from the glass trade.',
    type: 'Glass island — furnaces since 1291, Museo del Vetro',
    website: 'https://museovetro.visitmuve.it',
  },
  {
    id: 32,
    nbhd: 'burano',
    name: 'Burano',
    cat: 'island',
    emoji: '🌈',
    address: 'Isola di Burano, Venezia',
    lat: 45.4849, lng: 12.4172,
    search: 'Burano Venice colored houses island canal lace tradition fishermen',
    note: 'The houses are painted in strong primary colours — ochre, cobalt, pink, terracotta — so fishermen could identify their homes from the water through the lagoon fog. The colour system is still regulated by the municipality. Come early morning before the day-trip boats arrive, when the canals are running with fishing boats returning from the night.',
    hours: 'Vaporetto Line 12 from Fondamente Nuove — approx. 40 min. Museo del Merletto: daily 10:00–18:00',
    tip: 'Trattoria da Romano on the main square has been serving the same Venetian fish menu since 1947 and has a serious wine cellar. Book ahead for lunch and arrive hungry.',
    type: 'Coloured-house island — fishermen\'s tradition, lace museum',
    website: 'https://museomerletto.visitmuve.it',
  },
  {
    id: 33,
    nbhd: 'torcello',
    name: 'Torcello',
    cat: 'island',
    emoji: '🏛️',
    address: 'Isola di Torcello, Venezia',
    lat: 45.4978, lng: 12.4170,
    search: 'Torcello Venice Byzantine mosaic cathedral Santa Maria Assunta ancient',
    note: 'Once had 20,000 inhabitants. Now has perhaps fifteen. The Cathedral of Santa Maria Assunta has stood since 639 AD and contains the finest Byzantine mosaics north of Ravenna — a gold-ground Madonna in the apse and a Last Judgement covering the entire west wall. No souvenir shops. No queues. The bell tower is the tallest point in the lagoon.',
    hours: 'Vaporetto Line 12 via Burano — approx. 45 min total from Fondamente Nuove. Cathedral: daily 10:30–17:30 (Nov–Feb: closes 17:00)',
    tip: 'Combine with Burano on the same morning: take the 9:00 boat, spend an hour on Torcello (cathedral, bell tower, the stone chair called Attila\'s Throne outside), then walk to the Burano boat stop for lunch at da Romano. Back in Venice by 15:00.',
    type: 'Ancient lagoon settlement — Byzantine cathedral since 639, almost no tourists',
    website: 'https://www.torcello.it',
  },


  // ── MURANO — additional places ────────────────────────────────────────────

  {
    id: 34,
    nbhd: 'murano',
    name: 'Museo del Vetro',
    cat: 'art',
    emoji: '🏺',
    address: 'Fondamenta Marco Giustinian 8, Murano, Venezia',
    lat: 45.4576, lng: 12.3569,
    search: 'Museo del Vetro Murano glass museum Palazzo Giustinian Venice',
    note: 'The world\'s finest glass museum is on Murano, inside the 17th-century Palazzo Giustinian. Two millennia of glassmaking — Roman, Byzantine, Renaissance filigrana, 18th-century aventurine golds, 20th-century studio work. The centrepiece is the Barovier Marriage Cup from around 1470: deep-blue enamel-decorated glass, considered the finest of its kind to survive from the Renaissance.',
    hours: 'Daily 10:00–18:00 (Nov–Mar: 10:00–17:00); closed 1 Jan, 1 May, 25 Dec',
    tip: 'The top floor holds the 20th-century collection, including Venini studio pieces from the postwar period that influenced global design. Usually quiet even when the lower floors are busy. Book combined Murano + Burano vaporetto ticket at Fondamente Nuove.',
    type: 'Museum — 2,000 years of Venetian glass, 17th-century palazzo',
    website: 'https://museovetro.visitmuve.it',
  },
  {
    id: 35,
    nbhd: 'murano',
    name: 'Basilica dei Santi Maria e Donato',
    cat: 'art',
    emoji: '⛪',
    address: 'Campo San Donato, Murano, Venezia',
    lat: 45.4582, lng: 12.3552,
    search: 'Basilica Santi Maria Donato Murano Byzantine church mosaic floor dragon bones',
    note: 'Founded in the 7th century, rebuilt in 1140 — this church predates the glass industry by two centuries and has nothing to do with it. The mosaic floor, laid in 1140, is a carpet of geometric patterns in marble, porphyry and glass. Behind the high altar, four bones are identified by tradition as those of a dragon slain by San Donato. They are prehistoric whale bones. The church does not advertise this.',
    hours: 'Daily 09:00–18:00',
    tip: 'Arrive from the canal side, not from the campo — the 12th-century apse facing the water is the most important façade and sets the architecture correctly in its Byzantine context. Free to enter.',
    type: '7th-century basilica — Byzantine mosaic floor, dragon bones, no queues',
    website: 'https://www.veneziaunica.it',
  },

  // ── BURANO — additional places ────────────────────────────────────────────

  {
    id: 36,
    nbhd: 'burano',
    name: 'Museo del Merletto',
    cat: 'artisan',
    emoji: '🧵',
    address: 'Piazza Baldassare Galuppi 187, Burano, Venezia',
    lat: 45.4854, lng: 12.4165,
    search: 'Museo del Merletto Burano lace museum needle lace tradition Venice',
    note: 'Punto in aria — stitch in the air — was the most refined textile luxury in 16th-century Europe. France banned its import because the treasury was bleeding. The technique requires no frame: the lacemaker builds the pattern stitch by stitch using a single needle and thread. There are perhaps a dozen women left who still know it. The demonstration room changes how you see the finished objects.',
    hours: 'Daily 10:00–18:00 (Nov–Mar: 10:00–17:00); closed Mon in winter',
    tip: 'The demonstration room is the reason to come — watching the work being made, stitch by stitch, changes how you see the finished objects. Small pieces sold in the museum shop are authentic and priced honestly. Much of what is sold on the street outside is machine-made elsewhere.',
    type: 'Lace museum — needle lace tradition since the 16th century',
    website: 'https://museomerletto.visitmuve.it',
  },
  {
    id: 37,
    nbhd: 'burano',
    name: 'Trattoria al Gatto Nero',
    cat: 'dining',
    emoji: '🐟',
    address: 'Fondamenta della Giudecca 88, Burano, Venezia',
    lat: 45.4855, lng: 12.4148,
    search: 'Gatto Nero Burano restaurant risotto lagoon fish Venice trattoria',
    note: 'Since 1965, one thing better than anywhere in the lagoon: risotto di gò, made from the goby fish native to the Venetian lagoon, producing a stock of unusual depth and sweetness. From the table you watch the fishing boats that supply the kitchen. If moleche (soft-shell crab) are on the menu, order those too — they are only available in spring and autumn. Book at least a week ahead.',
    hours: 'Wed–Mon 12:00–15:00, 19:00–22:00; closed Tue',
    tip: 'Order the risotto di gò. If moleche are listed, order those too — they are only available in spring and autumn and this is one of the best places in Venice to eat them. Book well in advance for weekends.',
    type: 'Lagoon trattoria — risotto di gò since 1965, canal-side Burano',
    website: 'https://www.gattonero.com',
  },

  // ── TORCELLO — additional places ──────────────────────────────────────────

  {
    id: 38,
    nbhd: 'torcello',
    name: 'Cattedrale di Santa Maria Assunta',
    cat: 'art',
    emoji: '🕌',
    address: 'Piazza di Torcello, Torcello, Venezia',
    lat: 45.4981, lng: 12.4175,
    search: 'Torcello cathedral Santa Maria Assunta Byzantine mosaic Last Judgement Venice',
    note: 'Standing since 639 AD — the oldest building in the Venetian lagoon. The apse mosaic of the Virgin on gold ground is among the great images of Byzantine art in the West. The entire west wall carries an 11th-century Last Judgement, recently restored to its full intensity: Christ in Majesty, the weighing of souls, the torments of the damned, the elect rising. At a scale that makes most frescoes look tentative.',
    hours: 'Daily 10:30–17:30 (Nov–Feb: closes 17:00)',
    tip: 'Enter the baptistery on the left before the cathedral — the separate circular building preserves early medieval stonework that the main church renovation partially obscured. Climb the bell tower for the only elevated view of the entire northern lagoon. Admission charged separately.',
    type: 'Byzantine cathedral — founded 639 AD, Last Judgement mosaic, bell tower',
    website: 'https://www.torcello.it',
  },
  {
    id: 39,
    nbhd: 'torcello',
    name: 'Locanda Cipriani',
    cat: 'dining',
    emoji: '🌿',
    address: 'Piazza Santa Fosca 29, Torcello, Venezia',
    lat: 45.4979, lng: 12.4171,
    search: 'Locanda Cipriani Torcello Venice Hemingway garden restaurant historic',
    note: 'Giuseppe Cipriani opened this in 1934. Hemingway wrote parts of Across the River and Into the Trees at one of the garden tables. The kitchen serves classic Venetian cucina — risotto primavera, branzino al forno — in a walled garden with roses and herbs, at a degree of tranquillity that is improbable this close to one of the world\'s most crowded cities. Book the garden table.',
    hours: 'Wed–Mon 12:00–15:00; also dinner Fri–Sat 19:30–21:30. Closed Tue. Closed Nov–Mar.',
    tip: 'Book the garden table in advance — the walled garden is the reason to come. Arrive by the first morning vaporetto, visit the cathedral first, then lunch here. The return boat is a half-hour walk away and the schedule should be checked before you sit down.',
    type: 'Historic garden restaurant — since 1934, Hemingway\'s table, Torcello',
    website: 'https://www.locandacipriani.com',
  },

  // ── SAN MARCO — additional place ──────────────────────────────────────────

  {
    id: 40,
    nbhd: 'san_marco',
    name: 'Teatro La Fenice',
    cat: 'art',
    emoji: '🎼',
    address: 'Campo San Fantin 1965, San Marco, Venezia',
    lat: 45.4333, lng: 12.3317,
    search: 'Teatro La Fenice Venice opera house interior gilded horseshoe Verdi Mozart',
    note: 'The Phoenix — burned and rebuilt three times since 1792, each time restored to look exactly as before. The current gilded horseshoe interior replicates the 1836 version precisely. World premieres here include Rossini, Bellini, Donizetti and Verdi — who premiered La Traviata and Rigoletto in this room. Book a performance if the programme allows. The acoustic is extraordinary.',
    hours: 'Guided tours daily 09:30–18:00 (subject to rehearsal schedule). Performances year-round — check calendar.',
    tip: 'Book a performance rather than just the tour if the programme permits — the acoustic is extraordinary and the sight lines from the boxes are exactly what Verdi intended. Day-of tickets sometimes available from the box office. The tour is worthwhile regardless: 45 minutes, no crowds before 10:00.',
    type: 'Historic opera house — world premieres since 1792, gilded horseshoe interior',
    website: 'https://www.teatrolafenice.it',
  },

  // ── ADDITIONAL RESTAURANTS ────────────────────────────────────────────────

  {
    id: 41,
    nbhd: 'san_polo',
    name: 'Da Fiore',
    cat: 'dining',
    emoji: '🌸',
    address: 'Calle del Scaleter 2202, San Polo, Venezia',
    lat: 45.4376, lng: 12.3274,
    search: 'Da Fiore Venice MICHELIN star restaurant fish seafood Mara Martin San Polo',
    note: 'Mara Martin runs the kitchen; her husband Maurizio the dining room — the same division since 1978. They held a MICHELIN star for 26 years and then chose to give it back, on their own terms. The menu follows the lagoon strictly: what the fishermen brought, what the season allows. Bigoli in sauce, risotto, eel from the northern lagoon. Nothing is designed to impress; everything is designed to be accurate. Booking two to three weeks ahead is the minimum.',
    hours: 'Tue–Sat 12:30–14:30, 19:30–22:30; closed Sun–Mon',
    tip: 'Book two to three weeks ahead — this is not a restaurant where walk-ins happen. Ask Maurizio\'s advice on the wine; he will not oversell. The tasting menu lets the kitchen decide based on what arrived that morning.',
    type: 'Venetian seafood institution — lagoon sourcing since 1978, San Polo',
    website: 'https://www.ristorantedafiore.com',
  },
  {
    id: 42,
    nbhd: 'castello',
    name: 'Corte Sconta',
    cat: 'dining',
    emoji: '🦐',
    address: 'Calle del Pestrin 3886, Castello, Venezia',
    lat: 45.4360, lng: 12.3510,
    search: 'Corte Sconta Venice restaurant hidden courtyard Castello seafood antipasto Bib Gourmand',
    note: 'The name means hidden courtyard — which it is, on a calle that requires intent to find. MICHELIN Bib Gourmand, consistently respected by the Venetian food community. The antipasto di mare is a sequence of perhaps eight small dishes, each one a different preparation of the morning\'s catch; it is the reason to come. The room fills with regulars who know it is not a discovery — it is the real thing.',
    hours: 'Tue–Sat 12:30–14:00, 19:00–21:30; closed Sun–Mon and January',
    tip: 'Order the antipasto di mare and let it run its full course before ordering anything else. Book ahead — the courtyard fills fast in good weather and the interior is not large. The restaurant closes for most of January.',
    type: 'MICHELIN Bib Gourmand — hidden courtyard, Castello seafood',
    awards: 'MICHELIN Guide Italia 2026 — Bib Gourmand',
    website: 'https://www.cortescontavenezia.com',
  },
  {
    id: 43,
    nbhd: 'cannaregio',
    name: "Osteria L'Orto dei Mori",
    cat: 'dining',
    emoji: '🌿',
    address: 'Campo dei Mori 3386, Cannaregio, Venezia',
    lat: 45.4454, lng: 12.3266,
    search: "Orto dei Mori Venice osteria Cannaregio Madonna dell'Orto local restaurant garden",
    note: "On Campo dei Mori, two minutes from the Madonna dell'Orto — one of Venice's quietest corners. The menu is short and changes with what arrived at the Rialto market. Creative without being showy: Venetian ingredients, modern technique, no tourist expectations. This is where the Cannaregio neighbourhood eats on a good night. No grand reputation, no MICHELIN citation — just very good food in the right place.",
    hours: 'Mon, Wed–Sun 12:30–15:00, 19:00–22:30; closed Tue',
    tip: "The campo outside is one of the most peaceful spots in Venice. Eat early and stay for the quiet. Ask what the kitchen is proud of that day — the menu changes frequently and the staff will tell you.",
    type: 'Neighbourhood osteria — Cannaregio, creative Venetian, no tourists',
    website: 'https://osteriaortodeimori.com',
  },

];
