// A Perfect Day — Venice
// venice_data_v1.js — 33 curated places
//
// v1 — May 2026
// Voice: boutique hotel concierge — direct, specific, opinionated
// Six categories: Art & History · Bacaro · Dining · Artisan · Wander · Islands
//
// House-curated by Ludara.AI for the Ca' Sagredo Hotel demo
// Research sources: Italian press (Gambero Rosso, Veneto Secrets, Venezia da Vivere,
//   Venice Wiki, Dissapore, 1600venezia.it, Conoscerevenezia.it),
//   MICHELIN Guide Italia 2026, official hotel and artisan sites.
// All facts verified May 2026.

const PLACES = [

  // ── CANNAREGIO ────────────────────────────────────────────────────────────

  {
    id: 1,
    nbhd: 'cannaregio',
    name: 'Ca\' Sagredo Hotel',
    cat: 'art',
    emoji: '🎨',
    address: 'Campo Santa Sofia 4198/99, Cannaregio, Venezia',
    lat: 45.4409, lng: 12.3374,
    search: 'Ca Sagredo Hotel Venice Grand Canal palazzo facade pink',
    note: 'The only hotel in Venice that is also, formally, a museum. The 15th-century palazzo sits on the Grand Canal between Ca\' d\'Oro and the Rialto Bridge, and its interiors hold one of the most significant private art collections in the city. The frescoed staircase was designed by Andrea Tirali in the 1730s; Pietro Longhi painted the surrounding walls while the plaster was still drying. The Sala del Doge ceiling carries Niccolò Bambini\'s La Sconfitta dei Vizi, framed in early 18th-century stucco. Giambattista Tiepolo\'s ceiling painting — dating to around 1740, gilt-framed — dominates the principal hall. Sebastiano Ricci completed further rooms. The Sagredo family were among the most serious collectors in the Serenissima: the art here was not assembled for hotel guests, it was already here when they arrived. A connection to Galileo Galilei is noted in the family archives — the physicist was a guest of the Sagredo household during his Paduan years, and his correspondence with Giovanfrancesco Sagredo runs to dozens of letters. Walk slowly on the staircase.',
    hours: 'Guests only — lobby visible to visitors by arrangement with reception',
    tip: 'Ask at reception for the printed art guide to the rooms. The staircase fresco is best seen in morning light. The Grand Canal terrace serves aperitivo from 17:00.',
    type: '15th-century palazzo — private museum and Grand Canal hotel',
    awards: 'Small Luxury Hotels of the World',
    website: 'https://www.casagredohotel.com',
  },
  {
    id: 2,
    nbhd: 'cannaregio',
    name: 'Ca\' d\'Oro',
    cat: 'art',
    emoji: '🏛️',
    address: 'Calle di Ca\' d\'Oro 3932, Cannaregio, Venezia',
    lat: 45.4404, lng: 12.3367,
    search: 'Ca d\'Oro Venice Gothic palace facade Grand Canal gold',
    note: 'The most photographed Gothic facade on the Grand Canal, built between 1421 and 1440 for the Contarini family and once gilded — hence the name, House of Gold. Today it houses the Galleria Giorgio Franchetti, the bequest of a collector who restored the building in the 1890s and filled it with Venetian and Flemish masters, bronzes, medals and a superb Mantegna: his Saint Sebastian, pierced and calm, on the piano nobile. The building itself is the exhibit. The open loggia on the first floor, with its trefoil arches and carved stonework by Matteo Raverti and the Bon workshop, is the finest surviving example of Venetian flamboyant Gothic. Crowds stay on the waterfront looking up — most never go in. They should.',
    hours: 'Mon 08:15–14:00; Tue–Sun 08:15–19:15; closed first and third Mon of month',
    tip: 'Buy tickets online to skip the queue. The Mantegna Saint Sebastian is on the piano nobile to the right of the loggia — do not leave without finding it. The courtyard well-head is 14th century.',
    type: 'Gothic palazzo — Galleria Giorgio Franchetti',
    website: 'https://caoro.cultura.gov.it',
  },
  {
    id: 3,
    nbhd: 'cannaregio',
    name: 'Madonna dell\'Orto',
    cat: 'art',
    emoji: '⛪',
    address: 'Campo della Madonna dell\'Orto 3512, Cannaregio, Venezia',
    lat: 45.4488, lng: 12.3222,
    search: 'Madonna dell\'Orto Venice church Tintoretto Cannaregio Gothic facade',
    note: 'Tintoretto lived nearby, in the Campo dei Mori. He chose this church as his own, donated ten paintings to it over his lifetime, and was buried here in 1594 — his tomb is on the left side of the apse, alongside his children Domenico and Marietta. The two enormous paintings flanking the high altar are his masterpieces in place: the Adorazione del Vitello d\'Oro and the Giudizio Universale, both completed between 1562 and 1564 and both over ten metres tall. They were painted directly for this location and have never left it. The church dates to around 1350, the brick Gothic facade is early 15th century, and the campanile was completed in 1503. Outside the high-season crowds, this is the quietest of the great Venetian churches and one of the most moving. The neighbourhood around it — the northern tip of Cannaregio — is genuine working Venice.',
    hours: 'Mon–Sat 10:00–17:00; closed Sun morning',
    tip: 'Arrive before 10:30 to have the Tintoretto paintings to yourself. The sacristy contains a small Bellini. The walk along the Fondamenta della Misericordia back toward the centre is the most authentic stretch of Cannaregio.',
    type: 'Tintoretto\'s parish church — his tomb and ten paintings in situ',
    website: 'https://www.madonnadellortovenezia.it',
  },
  {
    id: 4,
    nbhd: 'cannaregio',
    name: 'Santa Maria dei Miracoli',
    cat: 'art',
    emoji: '💎',
    address: 'Campo dei Miracoli, Cannaregio, Venezia',
    lat: 45.4421, lng: 12.3352,
    search: 'Santa Maria dei Miracoli Venice interior marble Renaissance Pietro Lombardo',
    note: 'The most intimate church in Venice, and one of the most perfectly resolved interiors in Italian Renaissance architecture. Pietro Lombardo built it between 1481 and 1489 to house a miraculous image of the Virgin found in the neighbourhood, and he covered every surface: coloured marble inlays, carved pilasters, gilded barrel vault, carved and painted ceiling panels. It is no larger than a chapel. The proportions are immaculate. The light through the small windows at the east end falls exactly where it should. Tourists tend to photograph the exterior — the pink and grey marble facade above the canal — and move on. The interior is the reason to stop. There is almost never a queue.',
    hours: 'Mon–Sat 10:00–17:00 (Chorus Pass or ticket)',
    tip: 'Combine with the Chorus Pass (covers 16 Venetian churches — good value if you plan to visit several). The church is small and fills quickly at noon; early morning or late afternoon is best.',
    type: 'Renaissance jewel — Pietro Lombardo, 1481–1489',
    website: 'https://www.chorusvenezia.org',
  },
  {
    id: 5,
    nbhd: 'cannaregio',
    name: 'Vini da Gigio',
    cat: 'bacaro',
    emoji: '🍷',
    address: 'Fondamenta San Felice 3628, Cannaregio, Venezia',
    lat: 45.4411, lng: 12.3349,
    search: 'Vini da Gigio Venice canal bacaro wine cellar interior',
    note: 'Listed in the MICHELIN Guide and respected by Venetian restaurateurs — which is a harder thing to earn than a listing. The cellar is serious: several hundred labels, many natural and small-production, with a particular strength in Veneto and Friuli. The food is proper cucina veneziana: sarde in saor, fegato alla veneziana, pasta e fagioli made the old way. The dining room is small and has the layered feel of a place that has been improving for decades without changing its nature. Sommelier and co-owner Paolo Lazzari is likely to be behind the bar and has a genuine point of view about what you should drink. Ask him. The canal-side location in the quieter part of Cannaregio means you will not be competing with a tourist group for the last table.',
    hours: 'Wed–Sun 12:00–14:30, 19:00–22:30; closed Mon–Tue',
    tip: 'Book ahead — the room is small. Tell Paolo your budget and let him choose the wine. The sarde in saor is a benchmark version of the dish.',
    type: 'MICHELIN-listed bacaro and wine bar — canal-side, Cannaregio',
    awards: 'MICHELIN Guide Italia 2026',
    website: 'https://www.vinidagigio.com',
  },
  {
    id: 6,
    nbhd: 'cannaregio',
    name: 'Anice Stellato',
    cat: 'bacaro',
    emoji: '🌿',
    address: 'Fondamenta della Sensa 3272, Cannaregio, Venezia',
    lat: 45.4476, lng: 12.3238,
    search: 'Anice Stellato Venice bacaro canal Fondamenta Sensa Cannaregio',
    note: 'On the Fondamenta della Sensa in the northern reaches of Cannaregio, where tourists are rare and the calli narrow to something like the Venice that existed before mass tourism. Anice Stellato faces the canal, keeps a blackboard menu, and works with natural and low-intervention wines at a time when most Venetian bacari are still serving the same three house pours they have served for thirty years. The cicchetti board changes with the market. The baccalà mantecato is consistently good. On warm evenings the tables outside fill with a mix of neighbourhood regulars and people who have walked far enough to find the place — and are glad they did. This is the right kind of discovery.',
    hours: 'Wed–Sun 10:00–15:00, 18:00–22:30; closed Mon–Tue',
    tip: 'The outdoor canal-side tables are first-come. Arrive at 18:00 when they open in the evening and you will get one. Ask what arrived from the market that morning.',
    type: 'Canal-front bacaro — natural wines, Cannaregio',
    website: 'https://www.osteriaanicestellato.com',
  },
  {
    id: 7,
    nbhd: 'cannaregio',
    name: 'Antica Adelaide',
    cat: 'bacaro',
    emoji: '🕯️',
    address: 'Calle Priuli 3728, Cannaregio, Venezia',
    lat: 45.4444, lng: 12.3277,
    search: 'Antica Adelaide Venice osteria interior candlelit wood Cannaregio',
    note: 'An 18th-century osteria that has never tried to be anything other than an osteria. The room has bare wood, low light, and the smell of a kitchen that has been running for a long time. The cooking is creative Venetian — dishes built on traditional ingredients but without the obligation to reproduce museum pieces. The kitchen stays open until 1am, which in Venice is extraordinary and occasionally essential. The wine list favours smaller producers. Venetians come here for a late dinner when everywhere else is already closed and the conversation has gone on longer than expected. The neighbourhood around it is unpretentious in the best way.',
    hours: 'Daily 12:00–15:00, 18:00–01:00',
    tip: 'The late closing makes this the obvious last stop of an evening. The kitchen genuinely runs until 1am — not a token menu, the full kitchen.',
    type: '18th-century osteria — creative Venetian, open until 1am',
    website: 'https://www.anticaadelaide.com',
  },
  {
    id: 8,
    nbhd: 'cannaregio',
    name: 'Campo de\' Mori',
    cat: 'wander',
    emoji: '🗿',
    address: 'Campo de\' Mori, Cannaregio, Venezia',
    lat: 45.4482, lng: 12.3225,
    search: 'Campo dei Mori Venice medieval statues street corner Cannaregio',
    note: 'A small campo in northern Cannaregio with three medieval merchant statues embedded in the corner walls of a building — their noses worn smooth from centuries of hands reaching to touch them for luck. The Mori were the Mastelli brothers, traders from the Levant who settled here in the 12th century, and Venetian legend has never been entirely sure what to do with them: their figures appear in several stories, none entirely reliable. Tintoretto\'s house is steps away on the Fondamenta dei Mori — the plaque is easy to find. The campo itself is small, unpolished, and mostly unknown to tourists. Come in the evening when the light is low and the stone takes on a quality that is difficult to describe.',
    hours: 'Open always',
    tip: 'Walk from here along the Fondamenta dei Mori to the church of Madonna dell\'Orto — ten minutes, almost no tourist foot traffic, and one of the best sequences of streets in Venice.',
    type: 'Medieval campo — the Mastelli brothers and Tintoretto\'s neighbourhood',
  },
  {
    id: 9,
    nbhd: 'cannaregio',
    name: 'Fondamenta della Misericordia',
    cat: 'wander',
    emoji: '🌅',
    address: 'Fondamenta della Misericordia, Cannaregio, Venezia',
    lat: 45.4467, lng: 12.3252,
    search: 'Fondamenta Misericordia Venice canal evening aperitivo bacari row locals',
    note: 'The long canal-side walkway that serves as the evening gathering place for the working part of Venice. From early afternoon through midnight, bacari string along the fondamenta with tables on the pavement and wooden benches pushed against the walls, and the canal in front fills with reflections. This is where Venetians — not just young ones — actually spend their evenings: not in the tourist restaurants around the Accademia or Rialto, but here, with a glass of Prosecco or Spritz and a plate of cicchetti that costs three euros. The atmosphere owes nothing to design. It has been this way for decades and shows no sign of changing. Walk the full length from the Ponte delle Guglie end toward Madonna dell\'Orto and stop at whatever looks right.',
    hours: 'Most bacari active 17:00–22:00',
    tip: 'No reservations needed — this is a walk-in aperitivo strip. Osteria al Bacco, Al Timon, and Paradiso Perduto are the anchor points but the mood is consistent throughout. Come between 18:30 and 20:00 for the fullest version of it.',
    type: 'Canal-side aperitivo strip — the real Venetian evening',
  },

  // ── SAN POLO ──────────────────────────────────────────────────────────────

  {
    id: 10,
    nbhd: 'san_polo',
    name: 'Cantina Do Mori',
    cat: 'bacaro',
    emoji: '🍾',
    address: 'Calle Do Mori 429, San Polo, Venezia',
    lat: 45.4378, lng: 12.3349,
    search: 'Cantina Do Mori Venice oldest bacaro interior copper pots hanging',
    note: 'Founded around 1462 and the oldest bacaro in Venice — a claim that Venetians occasionally contest and that the evidence strongly supports. The interior is what authenticity actually looks like when it has not been restored for atmosphere: damigiane of wine, old photographs pinned to the panelling, antique water jugs hanging from the ceiling beams, a bar worn to a high polish by six centuries of elbows. The entrance is a double door in a narrow alley off the Rialto market, which was the point — two exits for fast departures, a feature Casanova apparently valued during his visits in the 18th century. Today the management is resolutely Venetian, the cicchetti are seasonal and house-made, and the wines are mostly local. The standing-room format has never changed. Come before noon when the market crowd arrives, order whatever is on the board, and stay longer than you planned.',
    hours: 'Mon–Sat 08:00–20:00; closed Sun',
    tip: 'Arrive early — by 12:30 it fills. Order the francobolli (small tramezzini squares) and the baccalà mantecato on white polenta. The house wine is better than it needs to be at this price.',
    type: 'Venice\'s oldest bacaro — est. 1462, Rialto',
    website: 'https://www.cantinadomori.com',
  },
  {
    id: 11,
    nbhd: 'san_polo',
    name: 'All\'Arco',
    cat: 'bacaro',
    emoji: '🥂',
    address: 'Calle dell\'Arco 436, San Polo, Venezia',
    lat: 45.4378, lng: 12.3354,
    search: 'All\'Arco Venice bacaro cicchetti crostini Francesco Matteo Rialto',
    note: 'Run by Francesco and his son Matteo, who buy from the Rialto fish and vegetable markets every morning and build the cicchetti board from what arrived. The result is a standing menu that changes daily and reflects the season honestly: sardines when they run, artichokes when they are small and tender, shellfish from the lagoon rather than the Adriatic when they are available. The crostini are consistently ranked among the best in the city by Venetians, which is the only ranking that matters. The address is a side alley under the brick arch between buildings — easy to walk past, easy to find once you know it. Locals have been coming here for decades; so have knowing food journalists, who tend not to publicise it loudly. The prices are among the lowest for wine by the glass in Venice.',
    hours: 'Mon–Sat 08:00–14:30; closed Sun',
    tip: 'Lunch only. Come between 11:00 and 12:30 to see the full board before the best pieces sell. Ask Matteo what is freshest. Cash preferred.',
    type: 'Standing cicchetti bar — market-to-bar, Rialto',
    website: 'https://veneziaautentica.com/venice-bacaro-bar-osteria-all-arco/',
  },
  {
    id: 12,
    nbhd: 'san_polo',
    name: 'Mercato di Rialto',
    cat: 'wander',
    emoji: '🐟',
    address: 'Campo della Pescaria, San Polo, Venezia',
    lat: 45.4383, lng: 12.3355,
    search: 'Rialto fish market Venice pescheria morning seafood lagoon stalls',
    note: 'Venice\'s wholesale food market has occupied this site, under the loggia of the Fabbriche Vecchie, since the 12th century. The fish hall — the Pescheria, built in 1907 in a neo-Gothic style that manages not to look like an imitation — opens at 7:30 and is done by noon. Arrive at 8:00 for the full version: crates of spider crab, sea bass, seppie still moving, clams raked from the lagoon bed that morning, sole, scampi, monkfish. The vegetable market alongside it keeps stone fruits, radicchio di Treviso, and seasonal produce from the mainland. The restaurants behind these stalls serve the same fish for lunch. The bacari on the surrounding calli are using what did not sell. The whole system is still working as it has worked for five hundred years, and it requires only a short walk and an early start to see it.',
    hours: 'Pescheria: Tue–Sat 07:30–12:00. Vegetables: Mon–Sat 07:00–13:00',
    tip: 'Be there by 8:00 on a Tuesday or Wednesday. The cicchetti at All\'Arco (two minutes away) use what was bought here that morning — the connection is direct.',
    type: 'Historic wholesale food market — fish and vegetables since the 12th century',
  },
  {
    id: 13,
    nbhd: 'san_polo',
    name: 'Antiche Carampane',
    cat: 'dining',
    emoji: '🦞',
    address: 'Rio Terà delle Carampane 1911, San Polo, Venezia',
    lat: 45.4381, lng: 12.3313,
    search: 'Antiche Carampane Venice restaurant no pizza tourist menu sign fish',
    note: 'The sign at the door reads: No pizza, no lasagne, no menù turistico. It has been there since Nani Bortoluzzi took over the osteria in 1983, and it has never needed changing. Nani\'s father was a fish wholesaler at the Rialto market; the sourcing is in the family. The MICHELIN Guide lists it; Venetian restaurateurs eat here. The fish is bought daily and cooked in the old Venetian manner — carpaccio di pesce, spaghetti in cassopipa (a slow-cooked Venetian brodetto), grilled and fried mixed platters with what came in that morning. The address is deliberately hard to find: the approach from the Rialto requires three turns down alleys that are not on tourist maps. This is entirely intentional. The clientele that finds it is the clientele the restaurant wants.',
    hours: 'Tue–Sat 12:30–14:00, 19:30–22:00; closed Sun–Mon',
    tip: 'Book ahead — the room is not large and fills with regulars. The spaghetti in cassopipa is the dish to order. Do not arrive expecting to improvise a booking.',
    type: 'MICHELIN-listed Venetian fish restaurant — Rialto',
    awards: 'MICHELIN Guide Italia 2026',
    website: 'https://www.antichecarampane.com',
  },
  {
    id: 14,
    nbhd: 'san_polo',
    name: 'Campo San Polo',
    cat: 'wander',
    emoji: '☀️',
    address: 'Campo San Polo, San Polo, Venezia',
    lat: 45.4389, lng: 12.3296,
    search: 'Campo San Polo Venice largest square open space market',
    note: 'The largest open square in Venice after Piazza San Marco, and a completely different thing. San Marco was built to impress foreign visitors and heads of state. Campo San Polo has always belonged to the neighbourhood: bullfights, markets, carnival events, public executions, and now children on bicycles in the afternoon and couples on the benches in the evening. The church on the northern edge is worth a look for the Tintoretto Last Supper and the Giandomenico Tiepolo Stations of the Cross. The campo itself, paved in the characteristic Venetian brick herringbone, is best experienced with no plan — arrive at dusk when the light goes horizontal and the campo empties of school groups.',
    hours: 'Open always; church Mon–Sat 10:00–17:00',
    tip: 'The campo is a natural rest stop on any walk through San Polo. The bar on the northwest corner serves coffee at a price honest enough for locals.',
    type: 'Venice\'s second-largest campo — neighbourhood life, San Polo',
  },

  // ── CASTELLO ──────────────────────────────────────────────────────────────

  {
    id: 15,
    nbhd: 'castello',
    name: 'Osteria alle Testiere',
    cat: 'dining',
    emoji: '🦀',
    address: 'Calle del Mondo Novo 5801, Castello, Venezia',
    lat: 45.4371, lng: 12.3396,
    search: 'Osteria alle Testiere Venice small MICHELIN Bruno Gavagnin seafood',
    note: 'Bruno Gavagnin and sommelier Luca di Vita opened this room in 1993 with twenty-two seats and a conviction that Venetian fish cookery did not need to be amplified to be excellent. Thirty years later the MICHELIN Guide is still listing it and the room is still twenty-two seats. The menu changes daily based on what Bruno\'s supplier brought from the lagoon; there is no fixed card and no point asking in advance what will be available. Expect crudo di scampi, razor clams with herbs, pasta with cuttlefish ink or clam broth, sole or turbot cooked simply and correctly. Luca\'s wine list is thoughtful and Veneto-anchored. There are two sittings per service — arriving at the wrong time for the sitting is the only way to get turned away. Book well ahead. This is the restaurant that Venetian food professionals use as a baseline when describing what serious local cooking looks like.',
    hours: 'Tue–Sat 12:30–14:00, 19:30–21:30; closed Sun–Mon; closed Aug',
    tip: 'Book at least two weeks ahead for dinner. There are two sittings per service — confirm your time. The crudo di scampi is always on the menu in some form when scampi are running.',
    type: 'MICHELIN-listed trattoria — 22 seats, daily-changing market menu',
    awards: 'MICHELIN Guide Italia 2026',
    website: 'http://www.osterialletestiere.it',
  },
  {
    id: 16,
    nbhd: 'castello',
    name: 'Al Covo',
    cat: 'dining',
    emoji: '🍝',
    address: 'Campiello della Pescaria 3968, Castello, Venezia',
    lat: 45.4346, lng: 12.3454,
    search: 'Al Covo Venice restaurant Castello MICHELIN Diane Rankin Cesare Benelli',
    note: 'Cesare Benelli and his Texan wife Diane opened Al Covo in 1987 with a specific intention: Venetian ingredients cooked in the Venetian manner, without compromise toward either tourist expectations or fashion. The MICHELIN Guide has listed it consistently ever since. The menu is seasonal and built on lagoon fish, market vegetables, and the kind of pasta that takes several hours to make. Diane handles the front of house with a warmth that has become part of the restaurant\'s character. The room is in a small campiello near the Arsenale, quiet and without foot traffic, in a part of Castello that most visitors never reach. The wine list is entirely Italian, well-chosen and deeply stocked in older Veneto vintages. Closed Tuesday and Wednesday — plan accordingly.',
    hours: 'Thu–Mon 12:45–14:30, 19:30–22:00; closed Tue–Wed',
    tip: 'The neighbourhood between Al Covo and the Arsenale is the least-visited in the city. Combine the dinner with an afternoon walk along Via Garibaldi and the Riva dei Sette Martiri.',
    type: 'MICHELIN-listed trattoria — seasonal Venetian since 1987',
    awards: 'MICHELIN Guide Italia 2026',
    website: 'https://www.ristorantealcovo.com',
  },
  {
    id: 17,
    nbhd: 'castello',
    name: 'Libreria Acqua Alta',
    cat: 'artisan',
    emoji: '📚',
    address: 'Calle Lunga Santa Maria Formosa 5176/b, Castello, Venezia',
    lat: 45.4358, lng: 12.3413,
    search: 'Libreria Acqua Alta Venice books gondola bathtub cats bookshop interior',
    note: 'Luigi Frizzo has been storing his used books in gondolas, bathtubs, a full-sized rowboat, and a gondola-shaped bookcase since the shop opened on Calle Lunga Santa Maria Formosa. The logic is functional: acqua alta, the seasonal flooding that fills Venice\'s ground floors to ankle depth, cannot reach books stored above the waterline. The cats help with neither the flooding nor the alphabetical order, but they are permanent residents. The inventory is large, multilingual and beautifully unorganised. There is a staircase made of books at the back that leads to a canal-side terrace. Frizzo does not run a bookshop the way a bookseller runs a bookshop — he runs it the way a collector who happens to sell things runs a collection. There is no obvious logic to the pricing. There is no obvious logic to anything. It works.',
    hours: 'Daily 09:00–19:30',
    tip: 'Go to the back for the canal terrace — it is the best reason to stay. The multilingual children\'s section is stacked in the bathtub near the entrance. Budget thirty minutes minimum.',
    type: 'Legendary used bookshop — books in gondolas, resident cats, canal terrace',
    website: 'https://www.libreriaacquaalta.it',
  },
  {
    id: 18,
    nbhd: 'castello',
    name: 'Via Garibaldi',
    cat: 'wander',
    emoji: '🥬',
    address: 'Via Garibaldi, Castello, Venezia',
    lat: 45.4330, lng: 12.3490,
    search: 'Via Garibaldi Venice wide street local market greengrocers Castello',
    note: 'Venice has almost no straight streets and almost no streets wide enough for two people walking in opposite directions to pass without turning sideways. Via Garibaldi, in the eastern part of Castello near the Arsenale, is the exception: a wide, straight boulevard, paved and lined with fruit and vegetable stalls, a fish seller, coffee bars, and ordinary shops serving an ordinary neighbourhood. Napoleon ordered the canal filled in 1808 to create it. The Biennale gardens are at one end; the waterfront at the other. The stalls are local supply chains, not tourist market theatre. Venetians buy their radicchio here, their artichokes in season, their peaches and figs. The area around it — eastern Castello, south of the Arsenale — is where Venice\'s workers have lived for centuries and where they still live. There are no souvenir shops.',
    hours: 'Market stalls: Mon–Sat 07:30–13:00',
    tip: 'Walk from here along the Riva dei Sette Martiri toward the Giardini for the best unrestricted view of the southern lagoon. The whole eastern Castello loop takes two hours and is almost entirely tourist-free.',
    type: 'The wide street — local market boulevard, working-class Castello',
  },

  // ── DORSODURO ─────────────────────────────────────────────────────────────

  {
    id: 19,
    nbhd: 'dorsoduro',
    name: 'Gallerie dell\'Accademia',
    cat: 'art',
    emoji: '🖼️',
    address: 'Campo della Carità 1050, Dorsoduro, Venezia',
    lat: 45.4311, lng: 12.3278,
    search: 'Gallerie dell\'Accademia Venice interior Titian Veronese Tintoretto sala',
    note: 'The canonical collection of Venetian painting from the 14th to the 18th century, housed in a converted convent and scuola. The works came here gradually after Napoleon suppressed the city\'s churches and confraternities from 1797 onward — this is where the paintings went when they had nowhere else to go. The result is a survey with no obvious gaps: Bellini\'s altarpieces, Carpaccio\'s cycle of Saint Ursula, Giorgione\'s Tempesta, Titian\'s Presentation of the Virgin (painted for the room it still hangs in), Veronese\'s Feast in the House of Levi (begun as a Last Supper, renamed under Inquisition pressure), and a full room of Tintorettos. The building itself, the former Scuola Grande di Santa Maria della Carità, is 15th century. Budget at minimum three hours. The rooms in the new wing, often skipped, hold the most important drawings collection in Italy.',
    hours: 'Mon 08:15–14:00; Tue–Sun 08:15–19:15',
    tip: 'Book online. The Titian Presentation of the Virgin is in Room 24 — the only painting still in the room it was made for. Room 21 (Carpaccio Ursula cycle) requires a separate timed entry; book it when you buy your ticket.',
    type: 'Canonical Venetian painting from 1300–1800 — Bellini, Titian, Veronese, Tintoretto',
    website: 'https://www.gallerieaccademia.it',
  },
  {
    id: 20,
    nbhd: 'dorsoduro',
    name: 'Punta della Dogana',
    cat: 'art',
    emoji: '⛵',
    address: 'Fondamenta della Dogana alla Salute 2, Dorsoduro, Venezia',
    lat: 45.4301, lng: 12.3347,
    search: 'Punta della Dogana Venice contemporary art Pinault Foundation tip Grand Canal',
    note: 'François Pinault\'s second Venice museum occupies the 17th-century customs warehouse at the tip of Dorsoduro where the Grand Canal meets the Giudecca Canal. Tadao Ando converted the building in 2009, keeping the brick shell and installing his characteristic poured concrete within it. The Pinault Foundation collection is serious contemporary art: Koons, Hirst, Kara Walker, Cy Twombly, Rudolf Stingel, and works commissioned specifically for the space. The building\'s position is unmatched — two open-water views, the dome of the Salute behind you, the Giudecca and San Giorgio ahead. What Ando did with the light is the real achievement: the concrete interior registers every change in the Venetian sky. The programming rotates every six months.',
    hours: 'Wed–Mon 10:00–19:00; closed Tue',
    tip: 'Combined ticket with Palazzo Grassi (Pinault\'s other Venice museum) is available and worth it. The tip of the building, outside the museum entrance, is publicly accessible and one of the finest standing points in the city.',
    type: 'Pinault Foundation — contemporary art in a 17th-century customs house',
    website: 'https://www.puntadelladogana.it',
  },
  {
    id: 21,
    nbhd: 'dorsoduro',
    name: 'San Sebastiano',
    cat: 'art',
    emoji: '✝️',
    address: 'Campo San Sebastiano, Dorsoduro, Venezia',
    lat: 45.4296, lng: 12.3207,
    search: 'San Sebastiano Venice church Veronese ceiling frescoes Dorsoduro',
    note: 'Paolo Veronese arrived in Venice around 1553, found this parish church in western Dorsoduro, and for the next two decades treated it as his personal studio and monument. The ceiling of the sacristy, the nave ceiling, the organ doors, the chancel, the high altar, the choir — he painted all of it. The Scenes from the Life of Esther on the ceiling are among his finest narrative paintings. When he died in 1588 he was buried beneath the organ loft, in the church he had decorated for thirty years. The building is otherwise unremarkable Gothic, which is entirely the point: the contrast between the plain exterior and the interior completely covered in Veronese\'s colour and light is one of the great surprises in Venice. Almost no tourists find it.',
    hours: 'Mon–Sat 10:00–17:00 (Chorus Pass or ticket)',
    tip: 'Bring binoculars or use the phone camera\'s zoom to read the ceiling. The sacristy ceiling (Stories of Esther) is the best place to start. Veronese\'s tomb is under the organ loft — the plaque is modest.',
    type: 'Veronese\'s personal chapel — three decades of painting in a single church',
    website: 'https://www.chorusvenezia.org',
  },
  {
    id: 22,
    nbhd: 'dorsoduro',
    name: 'Santa Maria della Salute',
    cat: 'art',
    emoji: '⛩️',
    address: 'Fondamenta della Dogana alla Salute 1, Dorsoduro, Venezia',
    lat: 45.4310, lng: 12.3349,
    search: 'Santa Maria della Salute Venice Baroque dome Grand Canal Longhena exterior',
    note: 'Baldassare Longhena won the commission in 1631 to build a church on the Grand Canal as an ex-voto offering for the end of a plague that had killed a third of Venice\'s population. He was 26 years old. The result is one of the most recognisable buildings in European architecture: the octagonal base, the two great domes, the scrolled volutes that Longhena invented to solve the structural problem of the transition from octagon to drum. Construction took 56 years. The interior holds six Titian paintings in the sacristy — including the ceiling of Saint Mark Enthroned with Saints, brought from the demolished church of Santo Spirito. The Tintoretto Wedding at Cana hangs in the chancel. Candles are left at the base of the altar continuously, in the tradition of the original votive offering. The building is free to enter.',
    hours: 'Daily 09:00–12:00, 15:00–17:30; sacristy ticket required for Titans',
    tip: 'The Titian ceiling in the sacristy requires a small entrance fee paid separately. Enter from the right side of the nave. The view back across the Grand Canal from the steps is one of the photographs everyone takes — allow time for it.',
    type: 'Baroque votive basilica — Longhena, 1631; Titian ceiling in sacristy',
    website: 'https://www.seminariovenezia.it/basilica-salute/',
  },
  {
    id: 23,
    nbhd: 'dorsoduro',
    name: 'Campo Santa Margherita',
    cat: 'wander',
    emoji: '🛖',
    address: 'Campo Santa Margherita, Dorsoduro, Venezia',
    lat: 45.4330, lng: 12.3236,
    search: 'Campo Santa Margherita Venice local square students cafe fruit stalls',
    note: 'Dorsoduro\'s main square, elongated, uneven and alive in a way that the more polished campos are not. The Ca\' Foscari university is nearby and the campo\'s character reflects it: aperitivo bars with outdoor tables from midday, a fruit and vegetable stall that has been in the same position for as long as anyone remembers, a fish seller at the northern end, and a Venetian lion carved into the campanile stump that serves as a base for conversations at all hours. The Scuola Grande dei Carmini, on the south side, has a Tiepolo ceiling in the upstairs hall worth a short detour. The campo itself is what outdoor sociability looks like in a city where cars are impossible and streets are corridors: the square is the piazza, the living room, the neighbourhood park.',
    hours: 'Open always; stalls active 07:30–13:00; bars 08:00 onwards',
    tip: 'Il Caffe (also called Bar Rosso) on the western side has been there since 1870 and serves the neighbourhood\'s aperitivo. Come between 17:00 and 19:00. The Scuola dei Carmini closes at 16:00 — plan accordingly.',
    type: 'The neighbourhood square — students, fruit stalls, Dorsoduro life',
  },
  {
    id: 24,
    nbhd: 'dorsoduro',
    name: 'Squero di San Trovaso',
    cat: 'wander',
    emoji: '⚓',
    address: 'Fondamenta Bonlini 1097, Dorsoduro, Venezia',
    lat: 45.4313, lng: 12.3265,
    search: 'Squero San Trovaso Venice gondola workshop canal Dorsoduro mountain building',
    note: 'One of the last working gondola workshops in Venice, operating on the Rio di San Trovaso since the early 17th century. The main building is immediately striking because it looks completely wrong for Venice: a wooden alpine structure, with exposed beams and a sloping roof, that belongs architecturally in the Dolomites. The reason is historical — the craftsmen who built gondolas came from the Cadore, a mountain zone of northern Veneto, and built their workshop in the style they knew. The gondola requires eight different types of wood, over 200 hand-made components, and approximately 500 hours of skilled labour. Today guided tours of thirty minutes run inside, led by a master carpenter. From the opposite fondamenta, the whole squero is visible without a ticket: the canal between is narrow enough to see the work being done.',
    hours: 'Exterior viewable always; guided tours — check squero directly for current schedule',
    tip: 'From the Fondamenta Nani across the canal you can watch the work for free. The guided tour includes the workshop floor and is worth booking if it is available.',
    type: '17th-century gondola workshop — still building by hand',
    website: 'http://www.squerosantrovaso.com',
  },

  // ── SANTA CROCE ───────────────────────────────────────────────────────────

  {
    id: 25,
    nbhd: 'santa_croce',
    name: 'Tessitura Luigi Bevilacqua',
    cat: 'artisan',
    emoji: '🪡',
    address: 'Campiello della Comare 1320, Santa Croce, Venezia',
    lat: 45.4399, lng: 12.3239,
    search: 'Tessitura Bevilacqua Venice historic loom velvet brocade weaving Santa Croce',
    note: 'Founded in 1875 by Luigi Bevilacqua, who rebuilt the Tessitura from ancient looms recovered from the Silk School of the Serenissima and from the Bevilacqua family archive, where a commission document dating to 1499 names Giacomo Bevilacqua as a master weaver. Today 18 original 18th-century wooden looms — the same ones, still running — produce velvets, damasks, lampas and the precious soprarizzo velvet, a pile-on-pile technique that can take one metre of fabric per day per loom. The historical archive holds over 3,500 perforated card designs, all original, all still in use. The Santa Croce showroom and shop sell contemporary creations alongside archive reproductions. The workshop behind the shop is open to visitors and the sound of the looms — a rhythm that has not changed in three hundred years — is audible from the street.',
    hours: 'Mon–Fri 09:00–17:00; Sat by appointment',
    tip: 'Ask to see the archive room — the perforated cardboard punch-patterns that program the looms are extraordinary objects in themselves. The showroom pieces start at accessible prices for small items; the full velvets are investment purchases.',
    type: 'Artisan textile mill — 18 antique looms, soprarizzo velvet since 1875',
    website: 'https://www.luigi-bevilacqua.com',
  },
  {
    id: 26,
    nbhd: 'santa_croce',
    name: 'Osteria Mocenigo',
    cat: 'dining',
    emoji: '🍤',
    address: 'Salizada San Stae 1919, Santa Croce, Venezia',
    lat: 45.4399, lng: 12.3269,
    search: 'Osteria Mocenigo Venice Santa Croce San Stae local trattoria',
    note: 'Near the church of San Stae on the Grand Canal, in a part of Santa Croce that receives few tourists and provides no reason to hurry. The Mocenigo is the neighbourhood trattoria that the neighbourhood actually uses: lunch and dinner for local professionals, a menu built on market availability, cicchetti at the bar from noon. The cooking is honest cucina veneziana without pretension or performance — mixed fried fish, pasta al nero di seppia, sarde in saor, a rotating secondo based on what came from the Rialto that morning. The room is small and the tables are close. The wine is local and inexpensive. The quality-to-price ratio is consistently better than anything in the tourist circuits. The kind of place that is immediately pleasant and takes a week to become a habit.',
    hours: 'Mon–Sat 12:00–15:00, 19:00–22:30; closed Sun',
    tip: 'No reservation required for lunch. The bacaro seating at the bar is good for cicchetti and a glass before the proper lunch sitting. Ask what the secondo is today before ordering.',
    type: 'Neighbourhood trattoria — market Venetian cooking, Santa Croce',
    website: 'https://www.osteriamocenigo.com',
  },
  {
    id: 27,
    nbhd: 'santa_croce',
    name: 'La Zucca',
    cat: 'dining',
    emoji: '🎃',
    address: 'Ponte del Megio 1762, Santa Croce, Venezia',
    lat: 45.4407, lng: 12.3256,
    search: 'La Zucca Venice vegetarian pumpkin flan canal restaurant Santa Croce',
    note: 'A small canal-side restaurant in Santa Croce that has been making the same pumpkin flan — a warm, barely sweet, almost savoury custard with aged Montasio cheese — since it opened in the 1990s, and has never had a reason to stop. The kitchen is vegetable-focused in the original sense: not ideological, not in pursuit of a trend, but genuinely interested in what the markets bring and what can be done with it. Meat appears on the menu occasionally; the best things here are always the vegetable dishes. The gnocchi change by season, the radicchio dishes are benchmark preparations, and the pumpkin reappears in various forms throughout the year. The room is small, the canal runs two metres from the table, and the booking fills quickly.',
    hours: 'Mon–Sat 12:30–14:30, 19:00–22:30; closed Sun',
    tip: 'Order the flan di zucca con Montasio — it has been on the menu for decades for good reason. The canal table is first-come but worth arriving early for. Book for dinner.',
    type: 'Vegetable-focused trattoria — pumpkin flan, canal-side, Santa Croce',
    website: 'https://www.lazucca.it',
  },

  // ── SAN MARCO ─────────────────────────────────────────────────────────────

  {
    id: 28,
    nbhd: 'san_marco',
    name: 'Palazzo Fortuny',
    cat: 'art',
    emoji: '🎭',
    address: 'Campo San Beneto 3780, San Marco, Venezia',
    lat: 45.4344, lng: 12.3307,
    search: 'Palazzo Fortuny Venice interior Mariano Fortuny studio museum fabric collection',
    note: 'Mariano Fortuny y Madrazo — painter, photographer, textile designer, stage lighting inventor, architect of the famous pleated Delphos gown — lived and worked in this 15th-century Gothic palazzo from 1899 until his death in 1949, and it still looks like he might return. The rooms hold his paintings, his photographs, his stage-set models, his fabric samples and the extraordinary collection of objects he gathered over fifty years: Near Eastern textiles, Venetian laces, Flemish tapestries, antique prints. The building was donated to the city of Venice, which now uses it both as a permanent Fortuny collection and as a venue for temporary exhibitions. The atmosphere is singular — less curated museum than personal world, still intact.',
    hours: 'Wed–Mon 10:00–18:00; closed Tue; temporary exhibitions may vary',
    tip: 'The permanent collection rooms on the upper floors are often overlooked by visitors focused on whatever temporary show is running. The upper studio, with its original warp-printed fabrics and stage-design drawings, is the most revealing room.',
    type: 'Fortuny\'s studio and home — Gothic palazzo, permanent collection',
    website: 'https://fortuny.visitmuve.it',
  },
  {
    id: 29,
    nbhd: 'san_marco',
    name: 'Damocle Edizioni',
    cat: 'artisan',
    emoji: '📖',
    address: 'Calle dello Spezier 2867, San Marco, Venezia',
    lat: 45.4349, lng: 12.3320,
    search: 'Damocle Edizioni Venice independent bookshop art gallery San Marco',
    note: 'An independent bookshop and small art gallery in San Marco that operates as though the rule about bookshops needing high foot-traffic locations is someone else\'s problem. The stock is strong in architecture, art history, design and Venetian subjects; the Venetian section, covering the city\'s art and history in Italian and occasionally in English, is one of the most carefully selected in the city. Small editions, artist\'s books and exhibition catalogues from galleries and museums elsewhere in Europe appear here before they reach most other stockists. The gallery programme runs in the back of the shop, turning over roughly every six weeks. The owner selects the stock personally and has a point of view about what goes in.',
    hours: 'Mon–Sat 10:00–19:30',
    tip: 'The Venetian history and art section is worth extended browsing. Ask the owner what is worth reading on Venice in Italian — the response will be specific and personal.',
    type: 'Independent bookshop and art gallery — architecture, art history, Venetian specialisms',
    website: 'https://www.damocleedizioni.com',
  },

  // ── SAN POLO / ARTISAN ────────────────────────────────────────────────────

  {
    id: 30,
    nbhd: 'san_polo',
    name: 'Il Pavone',
    cat: 'artisan',
    emoji: '🦚',
    address: 'Fondamenta dei Preti 721, Dorsoduro, Venezia',
    lat: 45.4373, lng: 12.3274,
    search: 'Il Pavone Venice paper marbling marbled paper artisan workshop',
    note: 'Paolo Pelosin has been marbling paper in the Venetian tradition for over thirty years, working in a small studio near the Frari. Carta marmorizzata — paper decorated with patterns created by floating coloured inks on water — was a Venetian speciality from the 17th century onward, used for bookbinding, endpapers and stationery. The patterns are made by combing and stylusing the floating ink before transferring it to paper in a single motion; the result cannot be exactly repeated. Pelosin\'s patterns draw on the traditional repertoire — peacock, stone, bouquet, French curl — but are made entirely by hand and carry the idiosyncrasies of a craftsman working in his own time. The studio sells directly and the prices are honest for what is being sold.',
    hours: 'Mon–Sat 10:00–13:00, 14:00–18:00',
    tip: 'Watch the process if he is making while you are there — it takes less than five minutes per sheet and is worth seeing once. The smaller sheets are an accessible price and pack flat.',
    type: 'Paper marbling studio — Venetian carta marmorizzata tradition, 30+ years',
    website: 'https://www.ilpavonedivenezia.it',
  },

  // ── ISLANDS ───────────────────────────────────────────────────────────────

  {
    id: 31,
    nbhd: 'murano',
    name: 'Murano',
    cat: 'island',
    emoji: '🫧',
    address: 'Isola di Murano, Venezia',
    lat: 45.4568, lng: 12.3540,
    search: 'Murano Venice glass blowing furnace master artisan workshop island',
    note: 'The Venetian Republic moved all glass production to Murano in 1291, ostensibly as a fire precaution but primarily to control the technology: glassblowers were forbidden to leave, their families held as effective hostages, their techniques treated as state secrets. The industry moved and the secrets eventually spread, but the island\'s identity never recovered from anything other than glass. Today the furnaces (fornaci) still operate; the serious ones — Venini, Barovier & Toso, Seguso — are legitimate industrial studios producing work that enters museum collections. The Museo del Vetro in the Palazzo Giustinian traces the full history from the Roman period. The water-bus from the Fondamente Nuove takes twelve minutes. Come on a weekday morning when the furnaces are running and the island has not yet filled with tour groups.',
    hours: 'Vaporetto Line 4.1 or 4.2 from Fondamente Nuove — approx. 12 min. Museo del Vetro: daily 10:00–18:00',
    tip: 'Walk past the main Colonna waterfront and head into the interior campos — Murano has its own Grand Canal, its own parish churches (Santa Maria e Donato has the finest Byzantine mosaic floor in the Veneto), and its own neighbourhood life separate from the glass trade.',
    type: 'Glass island — furnaces since 1291, Museo del Vetro',
    website: 'https://museovetro.visitmuve.it',
  },
  {
    id: 32,
    nbhd: 'burano',
    name: 'Burano',
    cat: 'island',
    emoji: '🌈',
    address: 'Isola di Burano, Venezia',
    lat: 45.4849, lng: 12.4172,
    search: 'Burano Venice colored houses island canal lace tradition fishermen',
    note: 'The houses on Burano are painted in the strong primary colours — ochre, terracotta, cobalt, pink, olive — that fishermen used to identify their homes from the water through the lagoon fog. The colour-coding system is regulated by the municipality: residents must apply to the local authority before repainting, and the authority specifies which colours are permitted on which facades. The result, accumulated over centuries of sequential repainting, is one of the most genuinely photogenic things in the Veneto. Burano also produced the finest needle-lace in Europe from the 16th century onward, a tradition almost extinct now but documented in the Museo del Merletto on the main square. The island is forty minutes by vaporetto from Fondamente Nuove. Come early in the morning, before the day-trip boats from Venice arrive, when the canals are running with fishing boats returning from the night.',
    hours: 'Vaporetto Line 12 from Fondamente Nuove — approx. 40 min. Museo del Merletto: daily 10:00–18:00',
    tip: 'Trattoria da Romano on the main square has been serving the same Venetian fish menu since 1947 and has a serious wine cellar. Book ahead for lunch and arrive hungry.',
    type: 'Coloured-house island — fishermen\'s tradition, lace museum',
    website: 'https://museomerletto.visitmuve.it',
  },
  {
    id: 33,
    nbhd: 'torcello',
    name: 'Torcello',
    cat: 'island',
    emoji: '🏛️',
    address: 'Isola di Torcello, Venezia',
    lat: 45.4978, lng: 12.4170,
    search: 'Torcello Venice Byzantine mosaic cathedral Santa Maria Assunta ancient',
    note: 'Torcello was the first settlement in the Venetian lagoon, populated from the mainland during the Lombard invasions of the 7th century. At its peak in the 10th century it had 20,000 inhabitants and three cathedrals. Today it has perhaps fifteen permanent residents, one hotel, one restaurant, one osteria, and the Cathedral of Santa Maria Assunta, which has stood continuously since 639 and contains the finest Byzantine mosaics north of Ravenna. The apse mosaic of the Madonna and Child is 12th century; the Last Judgement covering the entire west wall is 11th to 12th century, recently restored, and one of the great medieval images in Italy. The island is reached by vaporetto via Burano — forty-five minutes total from Fondamente Nuove. Almost nothing goes wrong here. There are no souvenir shops, no queues, no food trucks. The bell tower, which you can climb, is the tallest point in the lagoon.',
    hours: 'Vaporetto Line 12 via Burano — approx. 45 min total from Fondamente Nuove. Cathedral: daily 10:30–17:30 (Nov–Feb: closes 17:00)',
    tip: 'Combine with Burano on the same morning: take the 9:00 boat, spend an hour on Torcello (cathedral, bell tower, the stone chair called Attila\'s Throne outside), then walk to the Burano boat stop for lunch at da Romano. Back in Venice by 15:00.',
    type: 'Ancient lagoon settlement — Byzantine cathedral since 639, almost no tourists',
    website: 'https://www.torcello.it',
  },

];
