// A Perfect Day, ZenKimchi / Seoul
// data.js, curated places
//
// ══ CONTENT AUTHENTICITY RULES ══
//   note:  Joe McPherson's exact published words, verbatim from zenkimchi.com
//   tip:   Joe's exact words, or empty string. Never invented.
//   label: Always "Visitor Tip" in index.html, never blogger's name.
//
// SOURCE ARTICLES:
//   A = https://zenkimchi.com/tour-tips/must-eat-korean-food-in-seoul-and-where-to-eat-it/
//   B = https://zenkimchi.com/top-posts/best-korean-fried-chicken-joints/
//   C = https://zenkimchi.com/zenkimchi-korean-food-journal/restaurants/great-korean-restaurant-franchises/
//   D = https://zenkimchi.com/zenkimchi-korean-food-journal/restaurants/linus-bama-style-bbq/
//   E = https://zenkimchi.com/tour-tips/noryangjin-fish-market-new-guide/
//   F = https://zenkimchi.com/tour-tips/restaurants-myeong-dong-quick-guide/
//   G = https://zenkimchi.com/tour-tips/what-to-actually-do-in-seoul-a-real-top-10-list-with-zero-bullsht/
//   H = https://zenkimchi.com/tour-tips/majang-meat-market-seoul/
//   I = https://zenkimchi.com/zenkimchi-get-immersed-in-korea/the-authentic-korean-chicken-and-beer-experience/

const PLACES = [
  {
    "id": 1,
    "nbhd": "nbhd-mapo",
    "name": "Jeong Daepo 마포정대포",
    "cat": "bbq",
    "emoji": "🥩",
    "address": "Mapo-daero, Mapo-gu (near Gongdeok Station)",
    "lat": 37.5465,
    "lng": 126.9513,
    "search": "Jeong Daepo BBQ Seoul Gongdeok",
    "note": "My go-to for Korean BBQ, right by Gongdeok Station where the whole area smells of grilling meat. We made sure Anthony Bourdain ate here.",
    "hours": "Daily, lunch and dinner",
    "tip": "",
    "type": "Korean BBQ",
    "blog": "https://zenkimchi.com/tour-tips/must-eat-korean-food-in-seoul-and-where-to-eat-it/",
    "website": "",
    "noRes": true
  },
  {
    "id": 2,
    "nbhd": "nbhd-mapo",
    "name": "Hongik Sutbul Galbi 홍익숯불갈비소금구",
    "cat": "bbq",
    "emoji": "🔥",
    "address": "Mapo-gu, Seoul (Gongdeok area)",
    "lat": 37.5468,
    "lng": 126.9521,
    "search": "Hongik Sutbul Galbi Sogeum Gwi Gongdeok Seoul",
    "note": "Packed, packed, packed. They pre-cook your meat over strong fire, then finish it at your table. Catch it before gentrification wins.",
    "hours": "Daily, dinner",
    "tip": "",
    "type": "Korean BBQ",
    "blog": "https://zenkimchi.com/tour-tips/must-eat-korean-food-in-seoul-and-where-to-eat-it/",
    "website": "",
    "noRes": true
  },
  {
    "id": 3,
    "nbhd": "nbhd-mapo",
    "name": "Two-Two Chicken 둘둘치킨",
    "cat": "pub",
    "emoji": "🍗",
    "address": "Near Gongdeok Station, Mapo-gu (multiple locations across Seoul)",
    "lat": 37.5474,
    "lng": 126.9517,
    "search": "Two Two Chicken 둘둘치킨 Gongdeok Seoul",
    "note": "You can't go wrong with Two-Two. A franchise that acts like a mom-and-pop, run by a welcoming couple outside Gongdeok Station. I want them to get more love.",
    "hours": "Daily 17:00, 02:00",
    "tip": "",
    "type": "Chicken Hof",
    "blog": "https://zenkimchi.com/tour-tips/must-eat-korean-food-in-seoul-and-where-to-eat-it/",
    "website": ""
  },
  {
    "id": 4,
    "nbhd": "nbhd-mapo",
    "name": "Nureungji Tongdalk 누릉지통닭",
    "cat": "pub",
    "emoji": "🐓",
    "address": "Near Gongdeok Station and Sookmyung Women's University, Seoul",
    "lat": 37.5471,
    "lng": 126.951,
    "search": "Nureungji Tongdalk 누릉지통닭 Gongdeok Seoul",
    "note": "No fried here. Chicken is spit-roasted over wood and served on sizzling platters of crispy rice. The ones near Gongdeok and Sookmyung kill.",
    "hours": "Daily 17:00, 02:00",
    "tip": "",
    "type": "Rotisserie Chicken",
    "blog": "https://zenkimchi.com/tour-tips/must-eat-korean-food-in-seoul-and-where-to-eat-it/",
    "website": ""
  },
  {
    "id": 5,
    "nbhd": "nbhd-mapo",
    "name": "Ddobagi Chicken 또바기치킨",
    "cat": "pub",
    "emoji": "🌶️",
    "address": "Multiple locations across Seoul (search 또바기치킨 on Naver Map)",
    "lat": 37.5469,
    "lng": 126.9508,
    "search": "Ddobagi Chicken 또바기치킨 Seoul",
    "note": "Classic-style chicken since 1986, brined 24 hours then coated in spicy powder and fried. Go mild, or take on the spicy version as a satisfying challenge.",
    "hours": "Daily 17:00, 02:00",
    "tip": "",
    "type": "Fried Chicken",
    "blog": "https://zenkimchi.com/top-posts/best-korean-fried-chicken-joints/",
    "website": "http://ddobagi.kr/"
  },
  {
    "id": 6,
    "nbhd": "nbhd-hongdae",
    "name": "Chicken Baengi 치킨뱅이",
    "cat": "pub",
    "emoji": "🍺",
    "address": "North of main Hongdae strip, exit 7 Hongik University Station, head south two blocks",
    "lat": 37.5574,
    "lng": 126.9268,
    "search": "Chicken Baengi 치킨뱅이 Hongdae Seoul",
    "note": "Get the chicken three ways: fried, sauced, and garlic. Then the pa dalk, boneless thighs over ribbons of green onion. My favorite spot is run by two ladies.",
    "hours": "Daily 17:00, 02:00",
    "tip": "",
    "type": "Chicken Hof",
    "blog": "https://zenkimchi.com/tour-tips/must-eat-korean-food-in-seoul-and-where-to-eat-it/",
    "website": ""
  },
  {
    "id": 7,
    "nbhd": "nbhd-hongdae",
    "name": "Hongdae Crazy Street Food Alley",
    "cat": "market",
    "emoji": "🛒",
    "address": "Exit 9, Hongik University Station, head south past the buskers",
    "lat": 37.5558,
    "lng": 126.9244,
    "search": "Hongdae street food alley 홍대 Seoul",
    "note": "Past the buskers is what I call Crazy Street Food Alley: rotating stalls throwing every new street food idea against the wall to see what sticks.",
    "hours": "Daily, afternoon into late night",
    "tip": "",
    "type": "Street Food",
    "blog": "https://zenkimchi.com/tour-tips/must-eat-korean-food-in-seoul-and-where-to-eat-it/",
    "website": ""
  },
  {
    "id": 8,
    "nbhd": "nbhd-hongdae",
    "name": "Mangwon Market 망원시장",
    "cat": "market",
    "emoji": "🥟",
    "address": "Mangwon-dong, Mapo-gu (Mangwon Station, Line 6)",
    "lat": 37.5559,
    "lng": 126.9061,
    "search": "Mangwon Market 망원시장 Seoul",
    "note": "Where real Koreans shop and young vendors reinvent street food: deep-fried bulgogi dumplings, creme brulee hotteok, and next-gen bungeoppang.",
    "hours": "Daily 10:00, 22:00",
    "tip": "",
    "type": "Traditional Market",
    "blog": "https://zenkimchi.com/tour-tips/what-to-actually-do-in-seoul-a-real-top-10-list-with-zero-bullsht/",
    "website": ""
  },
  {
    "id": 9,
    "nbhd": "nbhd-hongdae",
    "name": "Won Halmoni Bossam 원할머니보쌈",
    "cat": "food",
    "emoji": "🐷",
    "address": "Multiple locations across Seoul (search 원할머니보쌈 on Naver Map)",
    "lat": 37.5572,
    "lng": 126.9252,
    "search": "Won Halmoni Bossam 원할머니보쌈 Seoul",
    "note": "Yeah, it's just bossam, but consistently good and best in the restaurant itself. The banchan is always diverse, including that sweet, fruity fresh kimchi.",
    "hours": "Daily, lunch and dinner",
    "tip": "",
    "type": "Bossam (Pork Wraps)",
    "blog": "https://zenkimchi.com/zenkimchi-korean-food-journal/restaurants/great-korean-restaurant-franchises/",
    "website": "http://www.bossam.co.kr/"
  },
  {
    "id": 10,
    "nbhd": "nbhd-hongdae",
    "name": "Jaws Tteokbokki 죠스떡볶이",
    "cat": "food",
    "emoji": "🌊",
    "address": "Multiple locations across Seoul (search 죠스떡볶이 on Naver Map)",
    "lat": 37.5568,
    "lng": 126.9258,
    "search": "Jaws Tteokbokki 죠스떡볶이 Seoul",
    "note": "A guy quit his job and spent months perfecting the recipe. The result is spicy, addictive tteokbokki. Mix it with the soondae, odeng, and crispy twigim.",
    "hours": "Daily 11:00, 22:00",
    "tip": "",
    "type": "Tteokbokki",
    "blog": "https://zenkimchi.com/zenkimchi-korean-food-journal/restaurants/great-korean-restaurant-franchises/",
    "website": "http://www.jawsfood.co.kr/"
  },
  {
    "id": 11,
    "nbhd": "nbhd-hongdae",
    "name": "BHC 비에이치씨",
    "cat": "pub",
    "emoji": "🍗",
    "address": "Multiple locations across Seoul (search BHC치킨 on Naver Map)",
    "lat": 37.5563,
    "lng": 126.926,
    "search": "BHC Chicken Seoul",
    "note": "Big Hit Chicken, the old standby family-style joint. Reliable, predictable, but satisfying.",
    "hours": "Daily 17:00, 02:00",
    "tip": "",
    "type": "Fried Chicken",
    "blog": "https://zenkimchi.com/top-posts/best-korean-fried-chicken-joints/",
    "website": "https://www.bhc.co.kr/"
  },
  {
    "id": 12,
    "nbhd": "nbhd-hongdae",
    "name": "Sulbing 설빙",
    "cat": "cafe",
    "emoji": "🧊",
    "address": "Multiple locations across Seoul (search 설빙 on Naver Map)",
    "lat": 37.5567,
    "lng": 126.9252,
    "search": "Sulbing 설빙 Seoul bingsu",
    "note": "The franchise that made me wonder who orders bingsu in winter. Turns out plenty of people. They specialize in Instagrammy shaved ice, and that's a good thing.",
    "hours": "Daily 11:00, 22:00",
    "tip": "",
    "type": "Bingsu (Shaved Ice)",
    "blog": "https://zenkimchi.com/tour-tips/must-eat-korean-food-in-seoul-and-where-to-eat-it/",
    "website": ""
  },
  {
    "id": 13,
    "nbhd": "nbhd-jongno",
    "name": "Gwanghwamun Jip 광화문집",
    "cat": "food",
    "emoji": "🍲",
    "address": "Near Gyeongbokgung Palace, Jongno-gu, Seoul",
    "lat": 37.5771,
    "lng": 126.9769,
    "search": "Gwanghwamun Jip 광화문집 Seoul kimchi jjigae",
    "note": "Tiny, tiny, tiny place near Gyeongbokgung with just two items: kimchi jjigae and gyeran mari. Get both.",
    "hours": "Mon, Fri 11:00, 15:00",
    "tip": "",
    "type": "Kimchi Jjigae",
    "blog": "https://zenkimchi.com/tour-tips/must-eat-korean-food-in-seoul-and-where-to-eat-it/",
    "website": "",
    "noRes": true
  },
  {
    "id": 14,
    "nbhd": "nbhd-jongno",
    "name": "Jeonju Yuhalmeoni Bibimbap 전주유할머니비빔밥",
    "cat": "food",
    "emoji": "🍚",
    "address": "Insadong area, Jongno-gu, Seoul",
    "lat": 37.5726,
    "lng": 126.9817,
    "search": "Jeonju Yuhalmeoni Bibimbap 전주유할머니비빔밥 Seoul",
    "note": "Respect, respect, respect. Grandmother has made good bibimbap here for over 50 years. Simple menu: get the bibimbap and the kongnamul gukbap.",
    "hours": "Daily, lunch and dinner",
    "tip": "",
    "type": "Bibimbap",
    "blog": "https://zenkimchi.com/tour-tips/must-eat-korean-food-in-seoul-and-where-to-eat-it/",
    "website": "",
    "noRes": true
  },
  {
    "id": 15,
    "nbhd": "nbhd-jongno",
    "name": "Tosokchon 토속촌",
    "cat": "food",
    "emoji": "🐓",
    "address": "5 Jahamun-ro 5-gil, Jongno-gu, Seoul",
    "lat": 37.5796,
    "lng": 126.9718,
    "search": "Tosokchon samgyetang Seoul Gyeongbokgung",
    "note": "A favorite of former president Roh Mu-hyun, in a classic hanok complex serving one thing: samgyetang. I'm not a fan of it, but I make an exception here.",
    "hours": "Daily 10:00, 22:00",
    "tip": "",
    "type": "Samgyetang (Ginseng Chicken Soup)",
    "blog": "https://zenkimchi.com/zenkimchi-korean-food-journal/",
    "website": "",
    "noRes": true
  },
  {
    "id": 16,
    "nbhd": "nbhd-jongno",
    "name": "Gwangjang Market 광장시장",
    "cat": "market",
    "emoji": "🥘",
    "address": "88 Changgyeonggung-ro, Jongno-gu, Seoul",
    "lat": 37.5704,
    "lng": 126.9996,
    "search": "Gwangjang Market 광장시장 Seoul bindaeddeok",
    "note": "Explore Gwangjang and try some bindaeddeok, one of my favorites, washed down with some road beers. That's always fun.",
    "hours": "Daily 09:00, 23:00",
    "tip": "",
    "type": "Traditional Market",
    "blog": "https://zenkimchi.com/tour-tips/must-eat-korean-food-in-seoul-and-where-to-eat-it/",
    "website": ""
  },
  {
    "id": 17,
    "nbhd": "nbhd-jongno",
    "name": "Ikseon-dong Hanok Village 익선동",
    "cat": "bar",
    "emoji": "🏮",
    "address": "Ikseon-dong, Jongno-gu, Seoul (near Jongno 3-ga Station)",
    "lat": 37.5762,
    "lng": 126.9939,
    "search": "Ikseon-dong 익선동 Seoul cocktail bar hanok",
    "note": "Not a soulless theme park but a tight-knit warren of century-old hanok filled with cocktail dens, handmade crafts, and surprisingly good bistros.",
    "hours": "Daily 12:00, 02:00",
    "tip": "Avoid midday weekends, it's a zoo. Go early evening instead.",
    "type": "Cocktail Bars & Bistros",
    "blog": "https://zenkimchi.com/tour-tips/what-to-actually-do-in-seoul-a-real-top-10-list-with-zero-bullsht/",
    "website": ""
  },
  {
    "id": 18,
    "nbhd": "nbhd-jongno",
    "name": "Balwoo Gongyang 발우공양",
    "cat": "food",
    "emoji": "☸️",
    "address": "71 Ujeongguk-ro, Jongno-gu, Seoul (near Jogyesa Temple)",
    "lat": 37.5735,
    "lng": 126.9809,
    "search": "Balwoo Gongyang temple food Seoul Jogyesa",
    "note": "Book a temple food tasting near Jogyesa. It's vegan, but don't panic: Korean Buddhist food means deep flavors, fermented everything, and zero fake-meat nonsense.",
    "hours": "Lunch and dinner sittings, reservations essential",
    "tip": "",
    "type": "Buddhist Temple Cuisine",
    "blog": "https://zenkimchi.com/tour-tips/what-to-actually-do-in-seoul-a-real-top-10-list-with-zero-bullsht/",
    "website": "",
    "resUrl": "https://www.catchtable.net/shop/Y2F0Y2hfYzh3YnZFVHVueWI4WENBVURxNFdTQT09",
    "phone": "+82 2-733-2081"
  },
  {
    "id": 19,
    "nbhd": "nbhd-jongno",
    "name": "Insa-dong Street Food 인사동",
    "cat": "market",
    "emoji": "🥐",
    "address": "Insadong main street, Jongno-gu, Seoul (Anguk Station exit 6)",
    "lat": 37.5749,
    "lng": 126.9855,
    "search": "Insadong street food Seoul hotteok",
    "note": "Home of Insa-dong hotteok, with cornmeal in the dough for extra crunch. Also fire-grilled chicken on a stick and my beloved egg breads.",
    "hours": "Daily 10:00, 21:00",
    "tip": "",
    "type": "Street Food",
    "blog": "https://zenkimchi.com/tour-tips/must-eat-korean-food-in-seoul-and-where-to-eat-it/",
    "website": ""
  },
  {
    "id": 20,
    "nbhd": "nbhd-jongno",
    "name": "Samhaejip 삼해집",
    "cat": "food",
    "emoji": "🦪",
    "address": "Alley south of Jongno 3-ga Station, Jongno-gu, Seoul",
    "lat": 37.5699,
    "lng": 126.9904,
    "search": "Samhaejip 삼해집 bossam Jongno Seoul",
    "note": "In the alley maze south of Jongno 3-ga, a joint serving bossam with oysters for over 35 years. Weekend lines out the door, and it's good!",
    "hours": "Daily lunch and dinner, busiest weekends",
    "tip": "",
    "type": "Bossam with Oysters",
    "blog": "https://zenkimchi.com/zenkimchi-korean-food-journal/",
    "website": "",
    "noRes": true
  },
  {
    "id": 21,
    "nbhd": "nbhd-jongno",
    "name": "Maetdollo-man 맷돌로만",
    "cat": "food",
    "emoji": "🥩",
    "address": "Multiple locations across Seoul (search 맷돌로만 on Naver Map)",
    "lat": 37.5738,
    "lng": 126.9855,
    "search": "Maetdollo-man 맷돌로만 tofu Seoul",
    "note": "My new favorite franchise, all about housemade tofu made right in the window. Get the Dubu Bossam set and the crunchy Dubu Jeon. Pure protein.",
    "hours": "Daily, lunch and dinner",
    "tip": "",
    "type": "Housemade Tofu",
    "blog": "https://zenkimchi.com/zenkimchi-korean-food-journal/restaurants/great-korean-restaurant-franchises/",
    "website": ""
  },
  {
    "id": 22,
    "nbhd": "nbhd-euljiro",
    "name": "Euljiro After Dark 을지로",
    "cat": "bar",
    "emoji": "🌃",
    "address": "Euljiro 3-ga area, Jung-gu, Seoul (Euljiro 3-ga Station)",
    "lat": 37.566,
    "lng": 126.9966,
    "search": "Euljiro 을지로 bar Seoul neon dive bar",
    "note": "Industrial workshops bathed in green and pink neon. Tiny staircases lead to smoky hideouts where bartenders serve cocktails in teacups.",
    "hours": "Daily 18:00, 03:00",
    "tip": "Best for: Night owls, creatives, anti-influencer types.",
    "type": "Bar District",
    "blog": "https://zenkimchi.com/tour-tips/what-to-actually-do-in-seoul-a-real-top-10-list-with-zero-bullsht/",
    "website": ""
  },
  {
    "id": 23,
    "nbhd": "nbhd-euljiro",
    "name": "Woo Lae Oak 우래옥",
    "cat": "food",
    "emoji": "🍜",
    "address": "62-29 Changgyeonggung-ro, Jung-gu, Seoul",
    "lat": 37.5656,
    "lng": 126.9898,
    "search": "Woo Lae Oak 우래옥 naengmyeon Seoul",
    "note": "Famous, almost too famous. A bit stodgy, the place you take grandma after church, but the naengmyeon is worth the premium price.",
    "hours": "Daily 11:30, 21:30",
    "tip": "",
    "type": "Naengmyeon (Cold Buckwheat Noodles)",
    "blog": "https://zenkimchi.com/tour-tips/must-eat-korean-food-in-seoul-and-where-to-eat-it/",
    "website": "",
    "resUrl": "https://www.catchtable.net/shop/Y2F0Y2hfc0EvanB2VHpFTGdIeTlaL0dUVkpxdz09",
    "phone": "+82 2-2265-0151"
  },
  {
    "id": 24,
    "nbhd": "nbhd-euljiro",
    "name": "Dongmu Bapsang 둥무밥상",
    "cat": "food",
    "emoji": "🇰🇵",
    "address": "Jung-gu, Seoul (search 둥무밥상 on Naver Map)",
    "lat": 37.5632,
    "lng": 126.975,
    "search": "Dongmu Bapsang 둥무밥상 naengmyeon North Korean Seoul",
    "note": "The owner cooked for North Korean army officers before defecting. Now his cozy shop serves the dishes he misses: eat the naengmyeon and the soondae.",
    "hours": "Daily, lunch and dinner",
    "tip": "",
    "type": "North Korean Cuisine",
    "blog": "https://zenkimchi.com/tour-tips/must-eat-korean-food-in-seoul-and-where-to-eat-it/",
    "website": "",
    "noRes": true
  },
  {
    "id": 25,
    "nbhd": "nbhd-euljiro",
    "name": "Sae Maul Sikdang 새마을식당",
    "cat": "bbq",
    "emoji": "🏮",
    "address": "Multiple locations across Seoul (search 새마을식당 on Naver Map)",
    "lat": 37.5648,
    "lng": 126.995,
    "search": "Sae Maul Sikdang 새마을식당 Seoul yeoltan bulgogi",
    "note": "A 1970s-nostalgia chain popular with Koreans and expats. Order the yeoltan bulgogi, shaved pork in spicy sauce, and grill it. Look for the yellow roof.",
    "hours": "Daily 11:00, 23:00",
    "tip": "",
    "type": "Korean BBQ (Pork)",
    "blog": "https://zenkimchi.com/zenkimchi-korean-food-journal/restaurants/great-korean-restaurant-franchises/",
    "website": "http://www.newmaul.com/"
  },
  {
    "id": 26,
    "nbhd": "nbhd-euljiro",
    "name": "Goobne Chicken 굽네치킨",
    "cat": "pub",
    "emoji": "♨️",
    "address": "Multiple locations across Seoul (search 굽네치킨 on Naver Map)",
    "lat": 37.5651,
    "lng": 126.9955,
    "search": "Goobne Chicken 굽네치킨 Seoul oven roasted",
    "note": "Oven chicken territory. Goobne bills itself as a healthy alternative to fried, and when we order it, it's stripped clean to the bone.",
    "hours": "Daily 17:00, 02:00",
    "tip": "",
    "type": "Oven Roasted Chicken",
    "blog": "https://zenkimchi.com/top-posts/best-korean-fried-chicken-joints/",
    "website": ""
  },
  {
    "id": 27,
    "nbhd": "nbhd-euljiro",
    "name": "Myeongdong Street Food 명동",
    "cat": "market",
    "emoji": "🌪️",
    "address": "Myeongdong main street, Jung-gu, Seoul (Myeongdong Station exit 6)",
    "lat": 37.561,
    "lng": 126.983,
    "search": "Myeongdong street food Seoul tornado potato",
    "note": "Street food for the tourist crowd, and where the weirder inventions debut. The Tornado Potato was born right here.",
    "hours": "Daily 11:00, 23:00",
    "tip": "",
    "type": "Street Food",
    "blog": "https://zenkimchi.com/tour-tips/restaurants-myeong-dong-quick-guide/",
    "website": ""
  },
  {
    "id": 28,
    "nbhd": "nbhd-euljiro",
    "name": "Andong Jjimdalk 안동찜닭 (Myeongdong)",
    "cat": "food",
    "emoji": "🍛",
    "address": "Myeongdong, Jung-gu, Seoul",
    "lat": 37.5607,
    "lng": 126.9843,
    "search": "Andong Jjimdalk 안동찜닭 Myeongdong Seoul",
    "note": "A franchise, but one of the better ones. Jjimdalk is braised garlicky sweet chicken, rich and hearty. Come with company for these huge plates.",
    "hours": "Daily 11:00, 22:00",
    "tip": "",
    "type": "Braised Chicken",
    "blog": "https://zenkimchi.com/tour-tips/restaurants-myeong-dong-quick-guide/",
    "website": "",
    "noRes": true
  },
  {
    "id": 29,
    "nbhd": "nbhd-euljiro",
    "name": "Myeongdong Pizza",
    "cat": "food",
    "emoji": "🍕",
    "address": "Myeongdong, Jung-gu, Seoul",
    "lat": 37.5621,
    "lng": 126.985,
    "search": "Myeongdong Pizza Seoul Italian",
    "note": "My Myeongdong lunch spot. Chef Eddie Ahn trained in Italy, so no sugar-coated garlic bread here: by far the best Italian in Myeong-dong.",
    "hours": "Daily, lunch and dinner",
    "tip": "",
    "type": "Italian Pizza",
    "blog": "https://zenkimchi.com/tour-tips/restaurants-myeong-dong-quick-guide/",
    "website": ""
  },
  {
    "id": 30,
    "nbhd": "nbhd-euljiro",
    "name": "Myeongdong Haidilao 하이디라오",
    "cat": "food",
    "emoji": "🫕",
    "address": "Myeongdong, Jung-gu, Seoul",
    "lat": 37.5619,
    "lng": 126.9848,
    "search": "Haidilao Myeongdong Seoul hot pot Chinese",
    "note": "The Chinese embassy is nearby, so the Chinese food is good. This hot pot franchise is English-friendly with a sauce bar. Go for the spicy Sichuan broth.",
    "hours": "Daily 11:00, 02:00",
    "tip": "",
    "type": "Chinese Hot Pot",
    "blog": "https://zenkimchi.com/tour-tips/restaurants-myeong-dong-quick-guide/",
    "website": "",
    "resUrl": "https://www.catchtable.net/shop/haidilao_myungdong"
  },
  {
    "id": 31,
    "nbhd": "nbhd-itaewon",
    "name": "Linus' Bama Style BBQ 라이너스바베큐",
    "cat": "bbq",
    "emoji": "🤠",
    "address": "56-20 Itaewon-dong, Yongsan-gu, Seoul",
    "lat": 37.5348,
    "lng": 126.994,
    "search": "Linus Bama Style BBQ Itaewon Seoul",
    "note": "Alabama native Linus Kim went to America to learn from the best, then opened here. Slow-cooked, perfectly seasoned Q so good it doesn't need the sauce.",
    "hours": "Tue, Sun 11:00, 22:00",
    "tip": "The Skinny Fries are best slathered in the pork sauce.",
    "type": "American BBQ",
    "blog": "https://zenkimchi.com/zenkimchi-korean-food-journal/restaurants/linus-bama-style-bbq/",
    "phone": "02-790-2920",
    "website": "",
    "resUrl": "https://www.catchtable.net/shop/linusbbq"
  },
  {
    "id": 32,
    "nbhd": "nbhd-itaewon",
    "name": "Orai Sutbul DalkGalbi 오라이숯불닭갈비",
    "cat": "bbq",
    "emoji": "🍖",
    "address": "Multiple locations across Seoul (search 오라이숯불닭갈비 on Naver Map)",
    "lat": 37.5343,
    "lng": 126.9945,
    "search": "Orai Sutbul DalkGalbi 오라이숯불닭갈비 Seoul charcoal chicken",
    "note": "Great stuff! Dark-meat chicken in sweet-spicy sauce, grilled on charcoal in front of you. Reasonably priced: one order feeds two, or one Joe.",
    "hours": "Daily, lunch and dinner",
    "tip": "",
    "type": "Charcoal Grilled DalkGalbi",
    "blog": "https://zenkimchi.com/zenkimchi-korean-food-journal/restaurants/great-korean-restaurant-franchises/"
  },
  {
    "id": 33,
    "nbhd": "nbhd-gangnam",
    "name": "Gogung 고궁 (Starfield Gangnam)",
    "cat": "food",
    "emoji": "👑",
    "address": "COEX Starfield Mall, 513 Yeongdong-daero, Gangnam-gu, Seoul",
    "lat": 37.5115,
    "lng": 127.059,
    "search": "Gogung 고궁 bibimbap Gangnam Starfield Seoul",
    "note": "I love Gogung. The Jeonju original got hard to find in Seoul, but this Starfield Mall branch serves classic royal Jeonju bibimbap in brass bowls.",
    "hours": "Daily 11:00, 21:00",
    "tip": "",
    "type": "Royal Jeonju Bibimbap",
    "blog": "https://zenkimchi.com/tour-tips/must-eat-korean-food-in-seoul-and-where-to-eat-it/",
    "website": "",
    "noRes": true
  },
  {
    "id": 34,
    "nbhd": "nbhd-gangnam",
    "name": "Omori Jjigae 오모리찌개 (Jamsil)",
    "cat": "food",
    "emoji": "🌶️",
    "address": "Jamsil, across the lake from Lotte World, Seoul (2nd floor)",
    "lat": 37.5133,
    "lng": 127.0829,
    "search": "Omori Jjigae 오모리찌개 Jamsil Seoul kimchi stew",
    "note": "Head to Jamsil, across the lake from Lotte World, up to the second floor. This flagship serves 3-year-old kimchi jjigae, surprisingly subtle and smooth.",
    "hours": "Daily, lunch and dinner",
    "tip": "",
    "type": "Kimchi Jjigae (3-Year-Old Kimchi)",
    "blog": "https://zenkimchi.com/tour-tips/must-eat-korean-food-in-seoul-and-where-to-eat-it/",
    "website": "",
    "noRes": true
  },
  {
    "id": 35,
    "nbhd": "nbhd-gangnam",
    "name": "Kyochon 교촌치킨",
    "cat": "pub",
    "emoji": "🍗",
    "address": "Multiple locations across Seoul (search 교촌치킨 on Naver Map)",
    "lat": 37.51,
    "lng": 127.026,
    "search": "Kyochon 교촌치킨 Seoul battered fried chicken",
    "note": "The one Americans picture for Korean fried chicken: batter-dipped, garlicky, shatteringly crisp. Order it yangnyeom, but beware the hot geyser of juice on first bite.",
    "hours": "Daily 15:00, 23:00",
    "tip": "",
    "type": "Battered Fried Chicken",
    "blog": "https://zenkimchi.com/top-posts/best-korean-fried-chicken-joints/",
    "website": "http://www.kyochon.com/"
  },
  {
    "id": 36,
    "nbhd": "nbhd-gangnam",
    "name": "Gyerimwon 계림원",
    "cat": "pub",
    "emoji": "🪵",
    "address": "Gangnam-gu, Seoul (search 계림원 누릉지통닭 on Naver Map)",
    "lat": 37.5058,
    "lng": 127.025,
    "search": "Gyerimwon 계림원 nureungji tongdalk Seoul Gangnam",
    "note": "Nureungji tongdalk, scorched-rice fried chicken from Gangwon. Know it by the rotisserie birds, oak logs out front, and heavenly smoke. Your new chicken-and-beer pairing.",
    "hours": "Daily 17:00, 02:00",
    "tip": "",
    "type": "Scorched Rice Rotisserie Chicken",
    "blog": "https://zenkimchi.com/top-posts/best-korean-fried-chicken-joints/",
    "website": ""
  },
  {
    "id": 37,
    "nbhd": "nbhd-gangnam",
    "name": "Nolboo 놀부",
    "cat": "food",
    "emoji": "🦆",
    "address": "Multiple locations across Seoul (search 놀부 on Naver Map)",
    "lat": 37.5092,
    "lng": 127.028,
    "search": "Nolboo 놀부 Seoul clay pot duck budae jjigae",
    "note": "A brand of many Korean restaurants, all good. The Clay Pot Duck, stuffed with rice, seeds, and medicinal ingredients and baked for hours, is Thanksgiving in Korea.",
    "hours": "Daily, lunch and dinner",
    "tip": "Bring a bottle of pinot noir for the Clay Pot Duck.",
    "type": "Clay Pot Duck / Budae Jjigae",
    "blog": "https://zenkimchi.com/zenkimchi-korean-food-journal/restaurants/great-korean-restaurant-franchises/"
  },
  {
    "id": 38,
    "nbhd": "nbhd-gangnam",
    "name": "Majang Meat Market 마장축산물시장",
    "cat": "bbq",
    "emoji": "🥩",
    "address": "Majang-dong, Seongdong-gu, Seoul (Majang Station, Line 5 Exit 2, 5 min walk)",
    "lat": 37.5527,
    "lng": 127.0563,
    "search": "Majang Meat Market 마장동 Seoul Hanwoo beef",
    "note": "Seoul's largest meat market, but tourists rarely go because it smells like beef. Pick your Hanwoo, grill it upstairs with the guys who butchered it. Glorious.",
    "hours": "Daily 06:00, 20:00",
    "tip": "Many butchers throw in complimentary service cuts, often lean beef to eat raw with sesame oil and salt.",
    "type": "Hanwoo Beef Market & BBQ",
    "blog": "https://zenkimchi.com/tour-tips/majang-meat-market-seoul/",
    "website": ""
  },
  {
    "id": 39,
    "nbhd": "nbhd-gangnam",
    "name": "Seongsu-dong 성수동",
    "cat": "cafe",
    "emoji": "☕",
    "address": "Seongsu-dong, Seongdong-gu, Seoul (Seongsu Station, Line 2)",
    "lat": 37.5443,
    "lng": 127.057,
    "search": "Seongsu-dong 성수동 Seoul cafes creative district",
    "note": "Once a grimy shoe-factory district, now where Seoul's creative class sips espresso in concrete bunkers and shops indie pop-ups inside shipping containers.",
    "hours": "Daily 10:00, 22:00",
    "tip": "Best for: Hipsters, brunchers, design geeks.",
    "type": "Café District",
    "blog": "https://zenkimchi.com/tour-tips/what-to-actually-do-in-seoul-a-real-top-10-list-with-zero-bullsht/",
    "website": ""
  },
  {
    "id": 40,
    "nbhd": "nbhd-noryangjin",
    "name": "Noryangjin Fish Market 노량진수산시장",
    "cat": "market",
    "emoji": "🐙",
    "address": "674 Nodeul-ro, Dongjak-gu, Seoul (Noryangjin Station, Line 1 Exit 2)",
    "lat": 37.5108,
    "lng": 126.9398,
    "search": "Noryangjin Fish Market 노량진수산시장 Seoul seafood",
    "note": "One of the best places in Seoul: an aquarium where you eat the exhibits. Much of the fish is still alive in tanks, so it barely smells.",
    "hours": "Open 24/7",
    "tip": "Ask for SAN NAKJI (산낙지) in Section H if you want to try the squirming live octopus.",
    "type": "Live Seafood Market",
    "blog": "https://zenkimchi.com/tour-tips/noryangjin-fish-market-new-guide/",
    "website": ""
  },
  {
    "id": 41,
    "nbhd": "nbhd-noryangjin",
    "name": "Noryangjin Salted Seafood Marketplace",
    "cat": "market",
    "emoji": "🦐",
    "address": "Inside Noryangjin Fish Market (2nd floor), Dongjak-gu, Seoul",
    "lat": 37.5108,
    "lng": 126.9395,
    "search": "Noryangjin salted seafood jeotgal market Seoul",
    "note": "My favorite part of the market: all this fermented salted seafood, toothpicks out for sampling. My guilty pleasure is the spicy raw oysters on buttery crackers.",
    "hours": "Daily 09:00, 20:00",
    "tip": "",
    "type": "Fermented Seafood",
    "blog": "https://zenkimchi.com/tour-tips/noryangjin-fish-market-new-guide/",
    "website": ""
  },
  {
    "id": 42,
    "nbhd": "nbhd-noryangjin",
    "name": "Noryangjin Cup Rice Road 컵밥거리",
    "cat": "market",
    "emoji": "🍱",
    "address": "Noryangjin-dong, Dongjak-gu (exit Fish Market, walk east past subway station)",
    "lat": 37.5118,
    "lng": 126.9421,
    "search": "Noryangjin Cup Rice Road 컵밥거리 bomb rice Seoul",
    "note": "A favorite secret corner: a row of streetside vendors feeding students cramming for exams. Cheap, varied, good. Hunt down the super-spicy Bomb Rice.",
    "hours": "Daily 08:00, 22:00",
    "tip": "",
    "type": "Student Street Food",
    "blog": "https://zenkimchi.com/tour-tips/must-eat-korean-food-in-seoul-and-where-to-eat-it/",
    "website": ""
  },
  {
    "id": 43,
    "nbhd": "nbhd-noryangjin",
    "name": "Jeongin Myeonok 정인면옥",
    "cat": "food",
    "emoji": "🍜",
    "address": "Yeouido, Yeongdeungpo-gu, Seoul",
    "lat": 37.5219,
    "lng": 126.9245,
    "search": "Jeongin Myeonok 정인면옥 naengmyeon Yeouido Seoul",
    "note": "Watch for the lunch lines. The naengmyeon is great, though it helps that it's one of the few good restaurants in Yeouido.",
    "hours": "Mon, Sat 11:00, 15:00",
    "tip": "",
    "type": "Naengmyeon (Cold Buckwheat Noodles)",
    "blog": "https://zenkimchi.com/tour-tips/must-eat-korean-food-in-seoul-and-where-to-eat-it/",
    "website": "",
    "phone": "+82 2-2683-2615",
    "noRes": true
  },
  {
    "id": 44,
    "nbhd": "nbhd-noryangjin",
    "name": "Lotte Department Store Basement 롯데백화점 지하",
    "cat": "market",
    "emoji": "🏬",
    "address": "Lotte Department Store, Sogong-ro, Jung-gu, Seoul (Euljiro 1-ga Station)",
    "lat": 37.5651,
    "lng": 126.9819,
    "search": "Lotte Department Store Basement Seoul food court",
    "note": "I recommend department store basements for food journeys and foodie souvenirs. The stalls constantly change, so just go check it out and sample anything interesting.",
    "hours": "Daily 10:30, 20:00",
    "tip": "",
    "type": "Department Store Food Hall",
    "blog": "https://zenkimchi.com/tour-tips/restaurants-myeong-dong-quick-guide/",
    "website": ""
  },
  {
    "id": 45,
    "nbhd": "nbhd-noryangjin",
    "name": "Dragon Hill Spa 용산드래곤힐스파",
    "cat": "landmark",
    "emoji": "🥚",
    "address": "40-713 Hangang-daero, Yongsan-gu, Seoul",
    "lat": 37.5145,
    "lng": 126.954,
    "search": "Siloam Sauna Dragon Hill Spa jjimjilbang Seoul",
    "note": "Hit a real jjimjilbang. Sweat in a kiln, nap on a heated floor, snack on baked eggs and cold sikhye. You'll emerge cleaner, softer, and slightly dehydrated.",
    "hours": "24 hours",
    "tip": "",
    "type": "Korean Bathhouse (Jjimjilbang)",
    "blog": "https://zenkimchi.com/tour-tips/what-to-actually-do-in-seoul-a-real-top-10-list-with-zero-bullsht/",
    "website": ""
  },
  {
    "id": 46,
    "nbhd": "nbhd-noryangjin",
    "name": "Woo Lae Oak Noryangjin 우래옥 별관",
    "cat": "food",
    "emoji": "🍥",
    "address": "Near Noryangjin area (see Naver Map for branches)",
    "lat": 37.5115,
    "lng": 126.9409,
    "search": "Woo Lae Oak 우래옥 Noryangjin naengmyeon Seoul",
    "note": "Naengmyeon always hits after a barbecue meal, with a few squirts of vinegar and hot mustard. That's why places like Woo Lae Oak are famous for it.",
    "hours": "Daily lunch and dinner",
    "tip": "",
    "type": "Naengmyeon (Cold Noodles)",
    "blog": "https://zenkimchi.com/tour-tips/must-eat-korean-food-in-seoul-and-where-to-eat-it/",
    "website": ""
  },
  {
    "id": 47,
    "nbhd": "nbhd-mapo",
    "name": "Anthracite Coffee 안트라시트",
    "cat": "cafe",
    "emoji": "☕",
    "address": "19 Tojeong-ro 37-gil, Hapjeong, Mapo-gu, Seoul (Hapjeong Station exit 1)",
    "lat": 37.5504,
    "lng": 126.9083,
    "search": "Anthracite Coffee 안트라시트 Hapjeong Seoul",
    "note": "Coffee and coal vibes, with outlets and moody lighting to work from. Just remember: camp for six hours and you'd better buy a second drink.",
    "hours": "Daily 09:00, 22:00",
    "tip": "",
    "type": "Specialty Coffee",
    "blog": "https://zenkimchi.com/tour-tips/what-kind-of-traveler-are-you-heres-how-to-do-seoul-right/",
    "website": "https://anthracitecoffee.com"
  },
  {
    "id": 48,
    "nbhd": "nbhd-hongdae",
    "name": "Convenience Store Bar 편의점 야외 술자리",
    "cat": "bar",
    "emoji": "🏪",
    "address": "Any GS25, CU or 7-Eleven near Hongdae, Mangwon or Euljiro, pick the one with outdoor tables",
    "lat": 37.556,
    "lng": 126.9255,
    "search": "convenience store bar Seoul outdoor tables",
    "note": "One of the great charms of Korea: grab drinks, cups, and snacks, pull up a table outside a convenience store, and you've got a cheap all-night spot.",
    "hours": "24 hours",
    "tip": "Triangle kimbap (₩1,200), instant ramen (₩900), cold beer (₩2,500). Korea's most democratic nightlife.",
    "type": "Outdoor Convenience Store Bar",
    "blog": "https://zenkimchi.com/zenkimchi-get-immersed-in-korea/the-authentic-korean-chicken-and-beer-experience/",
    "website": ""
  },
  {
    "id": 49,
    "nbhd": "nbhd-jongno",
    "name": "Sol-ip Makgeolli Bar 솔입막걸리 (Insadong)",
    "cat": "bar",
    "emoji": "🍶",
    "address": "North side of Insadong, across the street in a back alley, Jongno-gu",
    "lat": 37.5752,
    "lng": 126.9858,
    "search": "Sol-ip Makgeolli bar Insadong Seoul 솔입막걸리",
    "note": "You'll never forget this makgeolli bar, pouring regional brews in many flavors. The fusion is the good kind: get the American Potato Pancake with sour cream and bacon.",
    "hours": "Daily 17:00, 02:00",
    "tip": "Upgrade your makgeolli with a dusting of pine needle powder on top (Sol-eep Makkolli 솔입막걸리).",
    "type": "Makgeolli Bar",
    "blog": "https://zenkimchi.com/tour-tips/the-curmudgeons-guide-to-insa-dong/",
    "website": ""
  },
  {
    "id": 50,
    "nbhd": "nbhd-jongno",
    "name": "Gyeongbokgung Palace 경복궁",
    "cat": "landmark",
    "emoji": "🏯",
    "address": "161 Sajik-ro, Jongno-gu, Seoul (Gyeongbokgung Station exit 5)",
    "lat": 37.5796,
    "lng": 126.977,
    "search": "Gyeongbokgung Palace Seoul 경복궁",
    "note": "Wear a hanbok for free entry, arrive early before the tour buses, and actually take in the architecture. Then hit the National Folk Museum behind it.",
    "hours": "Wed, Mon 09:00, 18:00",
    "tip": "Skip the Changing of the Guard if you're short on time: it's more cosplay than ceremony.",
    "type": "Royal Palace",
    "blog": "https://zenkimchi.com/tour-tips/what-to-actually-do-in-seoul-a-real-top-10-list-with-zero-bullsht/"
  },
  {
    "id": 51,
    "nbhd": "nbhd-jongno",
    "name": "Inwangsan Hike 인왕산",
    "cat": "landmark",
    "emoji": "⛰️",
    "address": "Hongjecheon-ro trailhead, Seodaemun-gu, Seoul",
    "lat": 37.5843,
    "lng": 126.9543,
    "search": "Inwangsan hike Seoul mountain shrine",
    "note": "Forget Namsan Tower. This hike has better views, fewer tourists, and no overpriced elevator tickets. Plus you might pass a shrine or shamanic altar along the way.",
    "hours": "Open year-round; best at dawn",
    "tip": "Best for hikers and photographers; skip it on rainy days unless you enjoy slipping on wet pine needles.",
    "type": "City Mountain Hike",
    "blog": "https://zenkimchi.com/tour-tips/what-to-actually-do-in-seoul-a-real-top-10-list-with-zero-bullsht/",
    "website": ""
  },
  {
    "id": 52,
    "nbhd": "nbhd-itaewon",
    "name": "Hamilton Shirts 해밀턴 셔츠",
    "cat": "landmark",
    "emoji": "👔",
    "address": "Itaewon-ro, Yongsan-gu, Seoul (near Hamilton Hotel)",
    "lat": 37.5352,
    "lng": 126.9948,
    "search": "Hamilton Shirts Itaewon Seoul tailor made",
    "note": "I get tailor-made shirts here. They keep my specs on file, so I just pick fabric and style and they ship within ten days, even overseas.",
    "hours": "Mon, Sat 10:00, 19:00",
    "tip": "",
    "type": "Custom Tailor",
    "blog": "https://zenkimchi.com/tour-tips/10-unique-korean-souvenirs-seoul/",
    "phone": "02-792-5596",
    "website": ""
  },
  {
    "id": 53,
    "nbhd": "nbhd-euljiro",
    "name": "Dongmyo Flea Market 동묘벼룩시장",
    "cat": "market",
    "emoji": "🕹️",
    "address": "Dongmyo-dong, Jongno-gu, Seoul (Dongmyo Station, Line 1 & 6, exit 3)",
    "lat": 37.5721,
    "lng": 127.0163,
    "search": "Dongmyo flea market 동묘 벼룩시장 Seoul vintage",
    "note": "Skip the Myeongdong crowds and head east to Dongmyo: part thrift paradise, part museum of random antiques, vintage leather jackets beside dusty LPs. It still feels real.",
    "hours": "Daily 09:00, 18:00",
    "tip": "If you want an adventure (and bargains), Dongmyo is the treasure hunt you didn't know you needed.",
    "type": "Vintage Flea Market",
    "blog": "https://zenkimchi.com/category/tour-tips/",
    "website": ""
  },
  {
    "id": 54,
    "nbhd": "nbhd-jongno",
    "name": "Bukchon Hanok Village 북첬한옥마을",
    "cat": "landmark",
    "emoji": "🏯",
    "address": "Gahoe-dong, Jongno-gu, Seoul (Anguk Station exit 3)",
    "lat": 37.5822,
    "lng": 126.984,
    "search": "Bukchon Hanok Village 북첬한옆마을 Seoul traditional",
    "note": "Six hundred traditional hanok on a hillside between two palaces, still residential. Bukchon Alley 11 gives the most photographed view in the city: tiled rooftops against the skyline.",
    "hours": "Outdoor neighbourhood, always accessible. Culture Center: Tue, Sun 09:00, 18:00.",
    "tip": "Come before 09:00 or after 17:00; the signs asking for quiet are not decorative.",
    "type": "Traditional hanok neighbourhood, between Gyeongbokgung & Changdeokgung, Jongno"
  },
  {
    "id": 55,
    "nbhd": "nbhd-jongno",
    "name": "Changdeokgung Palace & Secret Garden 창덕궁 후원",
    "cat": "landmark",
    "emoji": "🌿",
    "address": "99 Yulgok-ro, Waryong-dong, Jongno-gu, Seoul (Anguk Station exit 3)",
    "lat": 37.5793,
    "lng": 126.9911,
    "search": "Changdeokgung Palace Secret Garden 창덕궁 후원 Seoul UNESCO",
    "note": "The most intact of Seoul's five royal palaces and UNESCO-listed. The Huwon (Secret Garden) at the rear is the real reason to come, accessible by timed tour only.",
    "hours": "Tue, Sun 09:00, 17:30 (winter) / 09:00, 18:30 (summer); closed Mon. Moonlight tours select dates Apr, Oct.",
    "tip": "Book the Huwon tour online weeks ahead; it sells out fast in spring and autumn.",
    "type": "Royal palace (1405) & UNESCO Secret Garden, Jongno",
    "website": "https://cgg.cha.go.kr",
    "resUrl": "https://royal.khs.go.kr/ROYAL/contents/R601000000.do?schGroupCode=cdg"
  },
  {
    "id": 56,
    "nbhd": "nbhd-jongno",
    "name": "Samcheong-dong 삼청동",
    "cat": "landmark",
    "emoji": "🖼️",
    "address": "Samcheong-ro, Jongno-gu, Seoul (Anguk Station exit 1)",
    "lat": 37.5793,
    "lng": 126.9813,
    "search": "Samcheong-dong galleries Seoul craft shops 삼청동",
    "note": "The street from Gyeongbokgung to Bukchon has Seoul's highest density of independent galleries, around thirty in converted hanok. The craft shops sell celadon and hanji well above Insadong quality.",
    "hours": "Most galleries and shops Tue-Sun 10:00-18:00; closed Mon.",
    "tip": "Walk Samcheong-ro from Anguk Station toward Bukchon; the galleries cluster densest near Bukchon-ro.",
    "type": "30+ art galleries & traditional craft shops, between palace and Bukchon, Jongno"
  },
  {
    "id": 57,
    "nbhd": "nbhd-euljiro",
    "name": "Cheonggyecheon Stream 청계천",
    "cat": "landmark",
    "emoji": "💧",
    "address": "Cheonggyecheon-ro, Jung-gu, Seoul (start: Cheonggyecheon Plaza near Gwanghwamun)",
    "lat": 37.5697,
    "lng": 126.9784,
    "search": "Cheonggyecheon Stream 청계천 Seoul urban park",
    "note": "A six-kilometre stream through central Seoul, restored in 2005 after they tore down the highway that had buried it for four decades. Now a linear park below the city grid.",
    "hours": "Open 24 hours. Walkway lighting on from dusk.",
    "tip": "Walk east from Cheonggyecheon Plaza in the evening when the lantern installations are lit. The Christmas light display (November, January) draws large crowds, go late afternoon on a weekday to avoid them.",
    "type": "Restored urban stream & linear park, 6km through central Seoul",
    "website": "https://www.cheonggyecheon.or.kr"
  },
  {
    "id": 58,
    "nbhd": "nbhd-euljiro",
    "name": "Dongdaemun Design Plaza (DDP) 동대문디자인플라자",
    "cat": "landmark",
    "emoji": "🛸",
    "address": "281 Eulji-ro, Jung-gu, Seoul (Dongdaemun History & Culture Park Station exits 1, 3)",
    "lat": 37.5672,
    "lng": 127.0096,
    "search": "Dongdaemun Design Plaza DDP Zaha Hadid Seoul",
    "note": "Zaha Hadid's largest project: 86,000 square metres of aluminium curves with no straight walls, opened in 2014. Best at night when the surface is lit.",
    "hours": "DDP galleries 10:00, 21:00 (exhibition times vary); exterior and plaza 24 hours.",
    "tip": "Check the DDP events calendar before visiting, the programme changes weekly. The rooftop garden above the excavated Joseon-era fortress wall is worth 20 minutes.",
    "type": "Zaha Hadid landmark (2014), exhibition halls, design museum & night architecture",
    "website": "https://www.ddp.or.kr"
  },
  {
    "id": 59,
    "nbhd": "nbhd-itaewon",
    "name": "National Museum of Korea 국립중앙박물관",
    "cat": "landmark",
    "emoji": "🏛️",
    "address": "137 Seobinggo-ro, Yongsan-gu, Seoul (Ichon Station exit 2)",
    "lat": 37.5236,
    "lng": 126.9805,
    "search": "National Museum Korea 국립중앙박물관 Seoul free",
    "note": "Asia's largest museum by collection, and free. Korean history from the Palaeolithic to Joseon: gold crowns, the world's finest Goryeo celadon, a 14-metre indoor pagoda.",
    "hours": "Tue, Sun 10:00, 18:00; Wed & Sat until 21:00; closed Mon.",
    "tip": "Allow three hours minimum; the cafe terrace faces Namsan Tower across the reflecting pool, a peaceful lunch stop.",
    "type": "National Museum (free entry), largest collection in Asia, Yongsan-gu",
    "website": "https://www.museum.go.kr"
  },
  {
    "id": 60,
    "nbhd": "nbhd-itaewon",
    "name": "Leeum Museum of Art 리움미술관",
    "cat": "landmark",
    "emoji": "🎨",
    "address": "60-16 Itaewon-ro 55-gil, Yongsan-gu, Seoul (Hangangjin Station exit 1)",
    "lat": 37.538,
    "lng": 126.9975,
    "search": "Leeum Museum Art 리움미술관 Seoul Samsung Botta Nouvel",
    "note": "Samsung's private museum, built by Botta, Nouvel, and Koolhaas. Historic Korean celadon and bronze meet contemporary works by Lee Ufan, Hirst, and Kapoor. One of Asia's strongest.",
    "hours": "Tue, Sun 10:00, 18:00; closed Mon.",
    "tip": "Book online, weekends sell out; the shop has Seoul's best art books and design objects.",
    "type": "Private art museum, Botta, Nouvel & Koolhaas buildings, Itaewon",
    "website": "https://www.leeum.org",
    "resUrl": "https://ticket.leeum.org/leeum/personal/exhibitList.do"
  },
  {
    "id": 61,
    "nbhd": "nbhd-gangnam",
    "name": "Garosu-gil 가로수길",
    "cat": "cafe",
    "emoji": "🌿",
    "address": "Near Sinnonhyeon Station (Line 9), Gangnam-gu, Seoul",
    "lat": 37.5194,
    "lng": 127.0198,
    "search": "Garosu-gil 가로수길 Apgujeong Seoul boutique cafe",
    "note": "A 700-metre ginkgo-lined boulevard of independent boutiques, beauty flagships, and specialty coffee, best in autumn. The most interesting spots have retreated into the side alleys behind.",
    "hours": "Most shops 10:30-21:00.",
    "tip": "Skip the main strip on weekends; the side alleys hold the independent boutiques and quieter cafes.",
    "type": "Upscale boutique, café & luxury retail district, Gangnam",
    "website": ""
  },
  {
    "id": 62,
    "nbhd": "nbhd-hongdae",
    "name": "Yeonnam-dong 연낙동",
    "cat": "cafe",
    "emoji": "☕",
    "address": "Yeonnam-dong, Mapo-gu, Seoul (Hongik University Station exit 3, walk west)",
    "lat": 37.5638,
    "lng": 126.9246,
    "search": "Yeonnam-dong 연낙동 Seoul cafe natural wine",
    "note": "The neighbourhood west of Hongdae, now Seoul's densest strip of independent cafes, natural wine bars, and single-item restaurants, still without the tourists.",
    "hours": "Most cafés 11:00, 22:00; bars later. Busiest Thu, Sun evenings.",
    "tip": "Go mid-week; the natural wine bars on the west end of Yeonnam-ro are best after 20:00.",
    "type": "Independent café & natural wine district, along decommissioned rail line, Mapo",
    "website": ""
  },
  {
    "id": 63,
    "nbhd": "nbhd-noryangjin",
    "name": "Han River Park 한강공원 (Yeouido)",
    "cat": "landmark",
    "emoji": "🌇",
    "address": "Yeouido Hangang Park, Yeouido-dong, Yeongdeungpo-gu (Yeouinaru Station exit 2)",
    "lat": 37.528,
    "lng": 126.9327,
    "search": "Han River Park Yeouido 한강공원 Seoul cycling picnic",
    "note": "Twelve riverside parks line the Han; Yeouido is the most used. Summer evenings the banks fill with Seoulites picnicking on delivery food, local culture most visitors miss entirely.",
    "hours": "Open 24 hours. Bike rental: dawn to dusk.",
    "tip": "Go at dusk; order fried chicken delivery to the entrance, exactly how Seoulites eat on summer nights.",
    "type": "Han River riverside park, cycling, picnic culture & city views, Yeouido"
  },
  {
    "id": 64,
    "nbhd": "nbhd-jongno",
    "name": "Bukhansan National Park 북한산국립공원",
    "cat": "landmark",
    "emoji": "⛰️",
    "address": "Trailhead: Gupabal Station (Line 3) for Baegundae peak / Dobongsan Station (Lines 1 & 7) for Dobongsan ridge",
    "lat": 37.659,
    "lng": 126.983,
    "search": "Bukhansan National Park 북한산 Seoul hike Baegundae",
    "note": "A granite massif rising to 836 metres on Seoul's edge, 30 minutes by metro. The Baegundae route ends on bare granite with an unobstructed panorama of the city.",
    "hours": "Open year-round. Entrance gates close at 16:00 in winter. No facilities on upper sections.",
    "tip": "Go on a weekday and bring water; there are no vendors above the visitor centre.",
    "type": "Granite national park, 836m peak & fortress wall, 30 min by metro from city centre"
  },
  {
    "id": 65,
    "nbhd": "nbhd-jongno",
    "name": "Gwanghwamun Square 광화문광장",
    "cat": "landmark",
    "emoji": "🏛️",
    "address": "Sejongno, Jongno-gu, Seoul (Gwanghwamun Station exit 2)",
    "lat": 37.5759,
    "lng": 126.9769,
    "search": "Gwanghwamun Square Cheongwadae Blue House Seoul 청와대",
    "note": "Redesigned in 2022, doubled in width with traffic removed, a proper civic forecourt to Gyeongbokgung. The Yi Sun-sin and King Sejong statues stand on axis with the palace gate.",
    "hours": "24 hours",
    "tip": "On clear days the view frames Baegundae peak in Bukhansan directly behind the palace gate.",
    "type": "Redesigned civic square (2022) & opened presidential residence (free), central Seoul"
  }
];
