// A Perfect Day — Ludara / Ramat HaSharon
// data.js — 15 places, verified on Google Maps April 2026
// Descriptions sourced from Google Reviews and Ontopo listings.
// Minimum rating: 4.0 | Minimum reviews: 5 | All verified in Ramat HaSharon.

const PLACES = [

  {
    // SOURCE: Google Maps + Google Reviews ✅ Rating 4.2 (3,602 reviews)
    id: 1,
    nbhd: 'nbhd-sokolov',
    name: 'Reviva and Celia',
    cat: 'cafe',
    emoji: '🥐',
    address: 'Ha-Meyasdim 1, Ramat HaSharon',
    lat: 32.1367115,
    lng: 34.837104,
    search: 'Reviva Celia Ramat HaSharon',
    note: 'Opened in 1988, this neighbourhood institution introduced traditional French baking to Israel. Order the leek patties, the enormous schnitzel with buttery mashed potatoes, or the avocado toast. The compact menu of salads, pasta and fish is made from quality ingredients. Friday mornings are packed — come early or book in advance. Reservation is mandatory for lunch and dinner.',
    hours: 'Sun–Thu 8am–10:30pm · Fri 8am–3pm & 5:30–10:30pm · Sat closed',
    tip: '',
    type: 'Café & Deli',
    blog: '',
    phone: '+972 3-540-0179',
    website: '',
  },

  {
    // SOURCE: Google Maps + Google Reviews ✅ Rating 4.0 (1,083 reviews)
    id: 2,
    nbhd: 'nbhd-sokolov',
    name: 'Cafe 111',
    cat: 'cafe',
    emoji: '☕',
    address: 'Sokolov 111, Ramat HaSharon',
    lat: 32.1516179,
    lng: 34.8414914,
    search: 'Cafe 111 Sokolov Ramat HaSharon',
    note: 'Open for over 20 years and still one of Sokolov\'s most consistent spots. Try the shakshuka with eggplant on crispy multigrain bread, the salad with crispy sweet potatoes, or the fresh-squeezed orange juice and vanilla shake. Breakfasts are served all day. The outdoor terrace is great for people-watching; the inner hall is lively but loud.',
    hours: 'Sun–Thu 7:30am–midnight · Fri 7:30am–4pm · Sat 5:30pm–midnight',
    tip: '',
    type: 'Café & Restaurant',
    blog: '',
    phone: '+972 3-540-2227',
    website: '',
  },

  {
    // SOURCE: Google Maps + Google Reviews ✅ Rating 4.6 (180 reviews)
    id: 3,
    nbhd: 'nbhd-sokolov',
    name: 'Lila Pizza',
    cat: 'food',
    emoji: '🍕',
    address: 'Sokolov 79, Ramat HaSharon',
    lat: 32.1471978,
    lng: 34.8388568,
    search: 'Lila Pizza Sokolov Ramat HaSharon',
    note: 'Run by two young enthusiastic chefs in a garden where they grow their own vegetables and herbs. Everything is made fresh — no frozen dough. The thin crispy base sets these pizzas apart from any chain. The vegan pizza with garlic and artichokes is a standout; they even keep a separate vegan pizza cutter. Seasonal menu means it changes regularly.',
    hours: 'Sun–Wed 5–11pm · Thu 2–11pm · Fri 9am–4pm · Sat closed',
    tip: '',
    type: 'Pizza',
    blog: '',
    phone: '+972 3-516-8244',
    website: '',
  },

  {
    // SOURCE: Google Maps + Google Reviews ✅ Rating 4.3 (894 reviews)
    id: 4,
    nbhd: 'nbhd-sokolov',
    name: 'Pizza Porto',
    cat: 'food',
    emoji: '🍕',
    address: 'Sokolov 93, Ramat HaSharon',
    lat: 32.1488885,
    lng: 34.8397162,
    search: 'Pizza Porto Sokolov 93 Ramat HaSharon',
    note: 'One of the best Italian experiences in the Sharon region. Order the arancini and artichoke-eggplant pizza to start, then the mushroom cream pasta or the spaghetti carbonara. For dessert, the vanilla ice cream with toppings is superb. Happy hour on Sundays with wine by the glass. Good value for the quality — most dishes in the ₪100–150 range.',
    hours: 'Daily 12pm–11pm',
    tip: '',
    type: 'Italian Restaurant',
    blog: '',
    phone: '+972 3-800-0888',
    website: '',
  },

  {
    // SOURCE: Google Maps + Google Reviews ✅ Rating 4.1 (2,770 reviews)
    id: 5,
    nbhd: 'nbhd-sokolov',
    name: 'Assaf Artisanal',
    cat: 'cafe',
    emoji: '🥖',
    address: 'HaTomer 28, Ramat HaSharon',
    lat: 32.1318891,
    lng: 34.8468546,
    search: 'Assaf Artisanal HaTomer Ramat HaSharon',
    note: 'A café-restaurant with a large shaded garden that is one of its main draws. Come for coffee and cake during the day — the handcrafted pastries and breads are the highlight. The garden is beautiful but very hot without shade in summer, so aim for a spot under the trees. Popular for leisurely weekend breakfasts.',
    hours: 'Sun–Fri 8am–midnight · Sat 9am–midnight',
    tip: '',
    type: 'Artisanal Café',
    blog: '',
    phone: '+972 3-549-8333',
    website: '',
  },

  {
    // SOURCE: Google Maps + Google Reviews + Ontopo ✅ Rating 4.2 (80 reviews)
    id: 6,
    nbhd: 'nbhd-park',
    name: 'La Terrazza',
    cat: 'cafe',
    emoji: '🌿',
    address: 'HaNetsach 11, Ramat HaSharon',
    lat: 32.1392527,
    lng: 34.8461764,
    search: 'La Terrazza park Ramat HaSharon',
    note: 'A coffee and wine bar on a terrace inside the city park — one of the most atmospheric spots in Ramat HaSharon. Come during the day for good matcha and coffee while children play in the garden around you. In the evenings it transforms into a wine bar with chef dishes and cocktails. The setting is magical; service can be slow on busy days.',
    hours: 'Daily 8am–11pm · Fri until 7pm',
    tip: '',
    type: 'Park Café & Wine Bar',
    blog: '',
    phone: '+972 50-899-8879',
    website: '',
  },

  {
    // SOURCE: Google Maps + Google Reviews ✅ Rating 4.2 (1,126 reviews)
    id: 7,
    nbhd: 'nbhd-sokolov',
    name: 'Soko 77',
    cat: 'pub',
    emoji: '🍺',
    address: 'Sokolov 77, Ramat HaSharon',
    lat: 32.147004,
    lng: 34.8388418,
    search: 'Soko 77 Sokolov Ramat HaSharon',
    note: 'The best bar on Sokolov, with rock music, a young crowd, and food that punches well above typical bar fare. Order the "sour flower" cocktail if you like sour. Happy hour runs 7–8:30pm with 50% off all alcohol including wine bottles, and 15% off food. The staff genuinely care about your experience.',
    hours: 'Sun–Thu 7pm–2am · Fri 8pm–3am · Sat 7pm–2am',
    tip: '',
    type: 'Bar & Restaurant',
    blog: '',
    phone: '+972 54-572-0270',
    website: '',
  },

  {
    // SOURCE: Google Maps + Google Reviews ✅ Rating 4.1 (725 reviews)
    id: 8,
    nbhd: 'nbhd-sokolov',
    name: 'Sushi Bar',
    cat: 'food',
    emoji: '🍣',
    address: 'Sokolov 111, Ramat HaSharon',
    lat: 32.1513828,
    lng: 34.8414647,
    search: 'Sushi Bar Sokolov 111 Ramat HaSharon',
    note: 'A Ramat HaSharon institution since 1997, formerly Sushi Bar Basel. Known for meticulous, high-quality sushi with a unique recipe. Reviewers recommend the beers alongside the sushi — described as "really unique and delicious." Clean and tidy with friendly service. Open every day including Shabbat.',
    hours: 'Daily 12pm–10:30pm · Thu until 11pm',
    tip: '',
    type: 'Sushi & Asian',
    blog: '',
    phone: '+972 3-547-7755',
    website: 'https://sushibar-sokolov.co.il',
  },

  {
    // SOURCE: Google Maps + Google Reviews + Ontopo ✅ Rating 4.8 (72 reviews)
    id: 9,
    nbhd: 'nbhd-sokolov',
    name: 'Vineria',
    cat: 'pub',
    emoji: '🍷',
    address: 'Sokolov 59, Ramat HaSharon',
    lat: 32.1445984,
    lng: 34.8378635,
    search: 'Vineria wine bar Sokolov Ramat HaSharon',
    note: 'The first and highest-rated wine bar in Ramat HaSharon, opened by Ronit, who has spent years building a world of wine. The service is 10/10 — they carefully choose each glass for you. Excellent variety of spirits, unique cheese plates and desserts, including vegan options. Friday lunch with wine tastings has become a local tradition. Outdoor seating available.',
    hours: 'Sun 5:30pm–midnight · Mon–Thu 2pm–midnight · Fri 10am–5pm · Sat 6pm–midnight',
    tip: '',
    type: 'Wine Bar',
    blog: '',
    phone: '+972 54-670-0966',
    website: '',
  },

  {
    // SOURCE: Google Maps + Google Reviews ✅ Rating 4.5 (28 reviews)
    id: 10,
    nbhd: 'nbhd-sokolov',
    name: 'Dali Wine Bar',
    cat: 'pub',
    emoji: '🍷',
    address: 'Sokolov 71, Ramat HaSharon',
    lat: 32.1461945,
    lng: 34.838536,
    search: 'Dali wine bar Sokolov Ramat HaSharon',
    note: 'A stylish wine bar with a relaxed, intimate courtyard atmosphere. The team really knows their wine pairing — they select each bottle with care. Food is beautifully presented and perfectly portioned. Particularly good for birthdays and special evenings. Warm and welcoming staff.',
    hours: 'Sun–Thu & Sat 5pm–midnight · Fri closed',
    tip: '',
    type: 'Wine Bar',
    blog: '',
    phone: '+972 52-484-0866',
    website: '',
  },

  {
    // SOURCE: Google Maps + Google Reviews ✅ Rating 4.2 (114 reviews)
    id: 11,
    nbhd: 'nbhd-sokolov',
    name: 'Sophia Wine Salon',
    cat: 'pub',
    emoji: '🍷',
    address: 'Sokolov 68, Ramat HaSharon',
    lat: 32.145347,
    lng: 34.8385166,
    search: 'Sophia wine salon Sokolov Ramat HaSharon',
    note: 'A wine and cocktails salon with great vibes and good music. Order the carpaccio or the eggplant dochesh — both standouts. Come with a group and order a few bottles of champagne for the full experience. Note that tables are timed at 2 hours during busy periods. Closed Fridays.',
    hours: 'Sun–Thu & Sat 5pm–midnight · Fri closed',
    tip: '',
    type: 'Wine Bar & Cocktails',
    blog: '',
    phone: '+972 50-665-5304',
    website: '',
  },

  {
    // SOURCE: Google Maps + Google Reviews ✅ Rating 4.6 (78 reviews)
    id: 12,
    nbhd: 'nbhd-sokolov',
    name: 'Beleza Wine Bar',
    cat: 'pub',
    emoji: '🎶',
    address: 'Sokolov 89, Ramat HaSharon',
    lat: 32.1483985,
    lng: 34.8394859,
    search: 'Beleza wine bar Sokolov Ramat HaSharon',
    note: 'One of Sokolov\'s highest-rated bars, blending music, food and wine with a warm family atmosphere. The food is precise and ingredient-driven — don\'t miss the German Sandwich. Tapas-style dishes pair beautifully with the wine list. The staff are local, exceptionally friendly and attentive. Closed Sundays.',
    hours: 'Mon–Fri 5pm–1am · Sat 6pm–1am · Sun closed',
    tip: '',
    type: 'Wine Bar',
    blog: '',
    phone: '+972 3-573-9331',
    website: '',
  },

  {
    // SOURCE: Google Maps + Google Reviews ✅ Rating 4.4 (2,860 reviews)
    id: 13,
    nbhd: 'nbhd-park',
    name: 'Park Ramat HaSharon',
    cat: 'nature',
    emoji: '🌳',
    address: 'HaNetsach 25, Ramat HaSharon',
    lat: 32.1388263,
    lng: 34.8454128,
    search: 'Park Ramat HaSharon',
    note: 'The city\'s main park with a lake, lotus flowers, cycling paths, playgrounds for all ages, an outdoor gym, a concert stage and a dedicated dog area. Arrive at sunrise to see the lotus flowers blooming and mandarin fish in the lake. Well maintained and free to enter.',
    hours: 'Daily 7am–11pm',
    tip: '',
    type: 'Park',
    blog: '',
    phone: '+972 3-548-3888',
    website: '',
  },

  {
    // SOURCE: Google Maps + Google Reviews ✅ Rating 4.9 (12 reviews)
    id: 14,
    nbhd: 'nbhd-sokolov',
    name: 'Municipal Gallery',
    cat: 'landmark',
    emoji: '🎨',
    address: 'Sderot Weizman 20, Ramat HaSharon',
    lat: 32.1470627,
    lng: 34.8356725,
    search: 'Ramat HaSharon Municipal Gallery contemporary art',
    note: 'Ramat HaSharon\'s gallery of contemporary art in a striking building that preserves an original underground cistern. Rotating exhibitions explore themes from local and national artists. A recent show called "The Green Village" examined the city\'s transformation from orchards to urban buildings. Described by visitors as the city\'s first real cultural landmark.',
    hours: 'Mon–Thu 9am–5pm · Fri–Sat 10am–2pm · Sun closed',
    tip: '',
    type: 'Contemporary Art Gallery',
    blog: '',
    phone: '+972 3-548-9346',
    website: '',
  },

  {
    // SOURCE: Google Maps + Google Reviews ✅ Rating 4.2 (90 reviews)
    id: 15,
    nbhd: 'nbhd-sokolov',
    name: 'Geological Museum',
    cat: 'landmark',
    emoji: '💎',
    address: 'HaPalmakh 12, Ramat HaSharon',
    lat: 32.1467332,
    lng: 34.8431730,
    search: 'Geological Museum Ramat HaSharon minerals',
    note: 'A hidden gem with a rare and high-quality collection of minerals and gems. Small but impressive — one room packed with specimens of unusual quality and rarity alongside seasonal art exhibitions. The staff are knowledgeable and happy to talk you through the collection. Children\'s programmes available — contact in advance. Descriptions currently in Hebrew only.',
    hours: 'Mon 10am–2pm & 4–6pm · Tue–Sat 10am–2pm · Sun closed',
    tip: '',
    type: 'Museum',
    blog: '',
    phone: '+972 3-549-7185',
    website: '',
  },

];
