// A Perfect Story Map — Screen Maps: Bath & Bristol (Visit West)
// data.js — 10 Bridgerton filming locations in Bath + 6 Rivals locations in Bristol
//
// v2 — July 2026 — UNLISTED CONCEPT DEMO / bespoke sample for Visit West.
// Not affiliated with Netflix, Shondaland, Disney+ or the productions.
// Scene references are described in our own words; no script is reproduced.
// Bath (Bridgerton) locations confirmed by VisitBath:
//   https://www.visitbath.co.uk/inspire-me/film-and-tv-in-bath/bridgerton-in-bath
// Bristol (Rivals) locations confirmed by Visit Bristol / Visit West.
// Real-place facts (history, visiting info) are from public sources.
//
//   book    : the scene this place plays in the show (shown with a film icon)
//   visit   : one compact "If you visit" footer line
//   hours   : short access / opening status (hotel-style)
//   website : official link where one exists
// Categories: Glamour & Society (ton) · Grand Houses & Buildings (home) · Streets & Squares (street)
// Regions: crescent, centre, pulteney (Bath) · bristol (Bristol)

const PLACES = [

  // ── ROYAL CRESCENT & THE CIRCUS (BATH) ────────────────────────────────────
  {
    id: 2,
    nbhd: 'crescent',
    name: 'The Royal Crescent',
    cat: 'ton',
    emoji: '👑',
    address: 'Royal Crescent, Bath BA1 2LR',
    lat: 51.3870, lng: -2.3720,
    search: 'Royal Crescent Bath Georgian terrace',
    note: 'The single most recognisable face of Bridgerton\'s Bath: the great sweep of the Royal Crescent stands in for the grandest addresses of the ton, where the season\'s families promenade and arrive by carriage. Built between 1767 and 1775 to a design by John Wood the Younger, its thirty Georgian houses curve in one continuous palace front above Royal Victoria Park. It is fully outdoors and free to walk, which makes it the natural first stop of any Bridgerton day.',
    book: 'The ton promenading: grand exterior street scenes',
    visit: 'Open parkland, free at any hour. Best light is late afternoon, when the honey-coloured stone glows.',
    hours: 'Free · open any time',
    type: 'Bridgerton · the world of the ton',
  },
  {
    id: 3,
    nbhd: 'crescent',
    name: 'No.1 Royal Crescent',
    cat: 'home',
    emoji: '🏠',
    address: '1 Royal Crescent, Bath BA1 2LR',
    lat: 51.3866, lng: -2.3696,
    search: 'No 1 Royal Crescent museum Bath',
    note: 'The end house of the Crescent plays a family home of the ton, its door and entrance hall dressed for the season. Today it is a restored Georgian townhouse museum that shows both the elegant rooms upstairs and the working world below stairs, exactly the two worlds the show loves to move between. The exterior is free to admire; the interior is a ticketed museum.',
    book: 'A grand family townhouse of the season',
    visit: 'Museum open most days, ticketed. The exterior and the Crescent lawn are free.',
    hours: 'Ticketed museum — see no1royalcrescent.org.uk',
    type: 'Bridgerton · a house of the ton',
    website: 'https://no1royalcrescent.org.uk',
    phone: '01225 428126',
  },

  // ── THE GEORGIAN CENTRE (BATH) ────────────────────────────────────────────
  {
    id: 4,
    nbhd: 'centre',
    name: 'Abbey Green (The Abbey Deli)',
    cat: 'street',
    emoji: '👗',
    address: 'Abbey Green, Bath BA1 1NW',
    lat: 51.3803, lng: -2.3585,
    search: 'Abbey Green Bath Abbey Deli plane tree',
    note: 'This quiet, tree-shaded square behind the Roman Baths is where the modiste\'s dress shop comes to life, and part of the square also stood in for the bustle of Covent Garden. The double-fronted, bay-windowed Abbey Deli plays the dressmaker\'s, and still leans into the connection with themed treats. A huge London plane tree fills the middle of the square, so it reads as pure Regency the moment you step in.',
    book: 'Madame Delacroix\'s modiste, and a Covent Garden stand-in',
    visit: 'A working square and cafe, free to wander. Quietest early morning before the lanes fill.',
    hours: 'Free square · deli open daytime',
    type: 'Bridgerton · the modiste',
  },
  {
    id: 5,
    nbhd: 'centre',
    name: 'Bath Street',
    cat: 'street',
    emoji: '🏛️',
    address: 'Bath Street, Bath BA1 1SA',
    lat: 51.3813, lng: -2.3600,
    search: 'Bath Street colonnade Cross Bath',
    note: 'A short, elegant street lined with covered colonnades on both sides, running between the Cross Bath and the Grand Pump Room. With no modern shopfronts or signage in view, it films as authentic eighteenth-century Bath and appears in the show\'s Regency street scenes. Being fully pedestrian and symmetrical, it is one of the most photogenic stops on the trail.',
    book: 'Regency street scenes under the colonnades',
    visit: 'Pedestrian and free, day or night. Walk it toward the Cross Bath for the framed view.',
    hours: 'Free · open any time',
    type: 'Bridgerton · Regency streets',
  },
  {
    id: 6,
    nbhd: 'centre',
    name: 'Beauford Square',
    cat: 'ton',
    emoji: '💃',
    address: 'Beauford Square, Bath BA1 1JY',
    lat: 51.3838, lng: -2.3635,
    search: 'Beauford Square Bath Theatre Royal cottages',
    note: 'A hidden square of small two-storey cottages laid out in 1730, with the original frontage of the Theatre Royal along its south side and a railed lawn in the middle. It hosts carriage and strolling scenes, including a well-remembered quiet conversation between two of the show\'s young women. Note the spelling: it is Beauford, not Beaufort. It is outdoors and free.',
    book: 'Carriage and strolling scenes between characters',
    visit: 'A residential square, free to visit. Please keep noise down for residents.',
    hours: 'Free · open any time',
    type: 'Bridgerton · the season on foot',
  },
  {
    id: 7,
    nbhd: 'centre',
    name: 'Trim Street',
    cat: 'street',
    emoji: '🚶',
    address: 'Trim Street, Bath BA1 1HB',
    lat: 51.3840, lng: -2.3625,
    search: 'Trim Street Bath historic lane',
    note: 'A narrow historic street just around the corner from Beauford Square, used for additional exterior street scenes. It is an easy few steps from several other stops, which is what makes the compact Georgian core of Bath so filmable: whole streetscapes stay in period without a single modern intrusion. Free to walk as part of the central loop.',
    book: 'Additional Regency exterior street scenes',
    visit: 'Central and free. Combine with Beauford Square, which is next door.',
    hours: 'Free · open any time',
    type: 'Bridgerton · Regency streets',
  },
  {
    id: 8,
    nbhd: 'centre',
    name: 'The Assembly Rooms',
    cat: 'ton',
    emoji: '🕯️',
    address: 'Bennett Street, Bath BA1 2QH',
    lat: 51.3862, lng: -2.3607,
    search: 'Bath Assembly Rooms ballroom chandeliers',
    note: 'The social heart of Georgian Bath, and a natural home for the show\'s grand balls and society gatherings. Its ballroom is the largest eighteenth-century room in the city and still hangs its original crystal chandeliers. Owned by the National Trust, the interiors are currently open by guided tour only while a new Georgian visitor experience is created, so check access before you go.',
    book: 'Grand balls and society gatherings',
    visit: 'Interiors by guided tour for now; a new experience is due to open in 2027. Check ahead.',
    hours: 'Guided tours only for now — check National Trust',
    type: 'Bridgerton · the ballroom',
    website: 'https://www.nationaltrust.org.uk/visit/bath-bristol/bath-assembly-rooms',
    phone: '01225 466414',
  },
  {
    id: 9,
    nbhd: 'centre',
    name: 'The Guildhall',
    cat: 'ton',
    emoji: '✨',
    address: 'High Street, Bath BA1 5AW',
    lat: 51.3818, lng: -2.3585,
    search: 'Bath Guildhall Banqueting Room interior',
    note: 'The Guildhall\'s Banqueting Room, all gilded plasterwork, chandeliers and full-length portraits, provides interiors for additional ball scenes. It is a working civic and events venue, so public access is by event or hire rather than a daily walk-in, but the exterior sits right in the centre beside the Guildhall Market. A good stop to admire from the street on the central loop.',
    book: 'Interiors for additional ball scenes',
    visit: 'Event and hire venue, so interiors are not a daily walk-in. Admire the exterior from High Street.',
    hours: 'Events venue — not a daily walk-in',
    type: 'Bridgerton · the ballroom',
    website: 'https://bathvenues.co.uk/venues/guildhall',
    phone: '01225 477786',
  },

  // ── GREAT PULTENEY & BATHWICK (BATH) ──────────────────────────────────────
  {
    id: 1,
    nbhd: 'pulteney',
    name: 'The Holburne Museum',
    cat: 'home',
    emoji: '🏛️',
    address: 'Great Pulteney Street, Bath BA2 4DB',
    lat: 51.3856, lng: -2.3520,
    search: 'Holburne Museum Bath Great Pulteney Street facade',
    note: 'The grand facade at the head of Great Pulteney Street is the exterior of Lady Danbury\'s house, one of the show\'s most beloved addresses, seen across the seasons. The building began as an eighteenth-century hotel and is now an art museum with a permanent collection, changing exhibitions and a garden behind. The exterior and garden are free to enjoy; the galleries are ticketed.',
    book: 'Lady Danbury\'s house (exterior), across the seasons',
    visit: 'Grounds and exterior free. Galleries ticketed, closed some Mondays. Cafe in the garden.',
    hours: 'Grounds free daily · galleries ticketed — see holburne.org',
    type: 'Bridgerton · Lady Danbury\'s residence',
    website: 'https://www.holburne.org',
    phone: '01225 388569',
  },
  {
    id: 10,
    nbhd: 'pulteney',
    name: 'Edward Street',
    cat: 'street',
    emoji: '🐎',
    address: 'Edward Street, Bath BA2 4DP',
    lat: 51.3853, lng: -2.3548,
    search: 'Edward Street Bath Georgian Bathwick',
    note: 'A picture-perfect residential Georgian street just off Great Pulteney Street, steps from the Holburne Museum, used from Season 3 for carriage and crowd scenes. For filming the road was gravelled over to look period-accurate, a small touch that shows how little of Bath needs changing to become the Regency world. Outdoors and free, and a natural pairing with the Holburne next door.',
    book: 'Carriage and crowd scenes, from Season 3',
    visit: 'A residential street, free to walk. Pair it with the Holburne Museum a minute away.',
    hours: 'Free · open any time',
    type: 'Bridgerton · the streets of the season',
  },

  // ── BRISTOL · RIVALS (Disney+) ────────────────────────────────────────────
  {
    id: 11,
    nbhd: 'bristol',
    name: 'Corn Street, Old City',
    cat: 'street',
    emoji: '🎬',
    address: 'Corn Street, Bristol BS1 1HQ',
    lat: 51.4548, lng: -2.5940,
    search: 'Corn Street Bristol Old City former banks',
    note: 'A handsome historic thoroughfare at the medieval heart of Bristol\'s Old City, lined with grand former banks and the covered markets. In Rivals it was dressed with 1980s cars and a red Routemaster bus for the glamorous television awards red carpet. It is free to wander, and the natural anchor of a Bristol walk, since several other Rivals locations sit right on it.',
    book: 'The television awards red carpet',
    visit: 'A public street, free any time. Start here: three other stops are a few steps away.',
    hours: 'Free · open any time',
    type: 'Rivals · the awards red carpet',
  },
  {
    id: 12,
    nbhd: 'bristol',
    name: 'Harbour Hotel Bristol',
    cat: 'ton',
    emoji: '🥂',
    address: '53-55 Corn Street, Bristol BS1 1HT',
    lat: 51.4545, lng: -2.5940,
    search: 'Harbour Hotel Bristol Corn Street former bank Sansovino',
    note: 'A boutique hotel set inside a palatial nineteenth-century former bank on Corn Street, whose opulent Sansovino Hall stood in for the television awards ceremony in Rivals. The hall itself is a private hotel interior, but the grand columned facade is worth seeing from the street, and the old bank vaults now hold a spa.',
    book: 'The television awards ceremony hall',
    visit: 'Private hotel interior; admire the facade from Corn Street, or book afternoon tea.',
    hours: 'Private hotel — exterior visible from Corn Street',
    type: 'Rivals · the awards ceremony',
    website: 'https://www.harbourhotels.co.uk/bristol',
    phone: '0117 203 4445',
  },
  {
    id: 13,
    nbhd: 'bristol',
    name: 'Cosy Club Bristol',
    cat: 'home',
    emoji: '📚',
    address: '31 Corn Street, Bristol BS1 1HT',
    lat: 51.4540, lng: -2.5950,
    search: 'Cosy Club Bristol Corn Street former banking hall dome',
    note: 'An all-day restaurant and bar set in a majestic former banking hall, with marble floors and a domed ceiling. In Rivals it hosts the scene where the writer meets her literary agent, and author Jilly Cooper herself makes a cameo. Walk in for a coffee under the dome and you are standing in the shot.',
    book: 'The literary-agent scene, with Jilly Cooper\'s cameo',
    visit: 'Open through the day for food and drink. Look up at the domed ceiling.',
    hours: 'Open daily for food & drink',
    type: 'Rivals · the author\'s cameo',
    website: 'https://www.cosyclub.co.uk/locations/bristol',
    phone: '0117 253 0997',
  },
  {
    id: 14,
    nbhd: 'bristol',
    name: 'St Nicholas Market',
    cat: 'street',
    emoji: '🛍️',
    address: 'Corn Street, Bristol BS1 1JQ',
    lat: 51.4541, lng: -2.5936,
    search: 'St Nicholas Market Bristol Exchange Nails',
    note: 'Bristol\'s beloved covered market inside the Georgian Exchange building, full of independent stalls and street food, with the historic brass "Nails" trading pillars standing outside on Corn Street. Its doors and facade appear in the background of the Rivals awards scenes. A lively, free stop right on the walking route.',
    book: 'Backdrop to the awards scenes',
    visit: 'Open most days; liveliest at lunch for street food. Closed some Sundays.',
    hours: 'Open most days — check times',
    type: 'Rivals · the Old City backdrop',
    website: 'https://www.stnicholasmarketbristol.co.uk',
  },
  {
    id: 15,
    nbhd: 'bristol',
    name: 'Aerospace Bristol (Concorde)',
    cat: 'ton',
    emoji: '✈️',
    address: 'Hayes Way, Patchway, Bristol BS34 5BZ',
    lat: 51.5188, lng: -2.5850,
    search: 'Aerospace Bristol Concorde G-BOAF Filton museum',
    note: 'An award-winning aviation museum at Filton, just north of the city, telling Bristol\'s aerospace and Concorde story, and home to the very last Concorde ever to fly. Rivals filmed its Concorde scenes aboard this actual aircraft, Alpha Foxtrot. You can step aboard yourself; a ticket is valid for a whole year.',
    book: 'Aboard Concorde',
    visit: 'Ticketed; open most days, and a ticket lasts a year. Allow a couple of hours.',
    hours: 'Ticketed; open most days — see aerospacebristol.org',
    type: 'Rivals · the Concorde scenes',
    website: 'https://aerospacebristol.org',
  },
  {
    id: 16,
    nbhd: 'bristol',
    name: 'Queen Square',
    cat: 'street',
    emoji: '🌳',
    address: 'Queen Square, Bristol BS1 4JQ',
    lat: 51.4513, lng: -2.5945,
    search: 'Queen Square Bristol William III statue Georgian',
    note: 'A large, tranquil Georgian square between the city centre and the harbour, built around Rysbrack\'s equestrian statue of William III. In Rivals it was dressed as a London street for several scenes, including a night-time moment beside the statue. It is free and open, a calm green finish to a Bristol walk.',
    book: 'Dressed as a London street',
    visit: 'Open green space, free any time. The William III statue marks the centre.',
    hours: 'Free · open any time',
    type: 'Rivals · a London stand-in',
  },

];
